### Deploy semantic search using with finetuned model 
The deployment architecture includes: 
- Choose a pretrain BERT model, here we use all-MiniLM-L6-v2 model
- Save the ML models in S3 bucket
- Host the ML models using SageMaker endpoints 
- Create Vector index and load data into the index 
- Create API gateway handels queries from web applications and pass it to lambda 
- Create a Lambda function to call SageMaker endpoints to generate embeddings from user query, and send the query results back to API gateway 
- API gateway sends the search results to frontend, and return search results to the users 

![Semantic_search_finetuned_fullstack](image/Semantic_search_finetune_fullstack.png)

In [13]:
!conda install ipykernel -y

Retrieving notices: done
Channels:
 - conda-forge
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done

# All requested packages already installed.

In [14]:
import torch 
print(torch.__version__)

2.10.0+cu128

In [15]:
#installed in the previous notebook
!pip install -q boto3
!pip install -q requests
!pip install -q requests-aws4auth
!pip install -q opensearch-py
!pip install -q tqdm
!pip install -q install transformers[torch]
!pip install -q transformers==4.52.4
!pip install -q sentence-transformers rank_bm25
!pip install -q sagemaker
!pip install -q datasets

ERROR: Could not find a version that satisfies the requirement install (from versions: none)
ERROR: No matching distribution found for install
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sentence-transformers 6.0.1 requires huggingface-hub<2.0.0,>=1.3.0, but you have huggingface-hub 0.36.2 which is incompatible.
sentence-transformers 6.0.1 requires transformers<6.0.0,>=5.0.0, but you have transformers 4.52.4 which is incompatible.

In [16]:
!pip list | grep transformers

sentence-transformers                6.0.1
transformers                         5.16.1

In [17]:
import sagemaker
role = sagemaker.get_execution_role()
role

2026-09-09 15:26:25,857 - INFO - Found credentials from IAM Role: BaseNotebookInstanceEc2InstanceRole

'arn:aws:iam::759472643633:role/geocore-semantic-search-with-opensearch-stag-NBRole-MnTqEOckqG8y'

In [18]:
import pandas as pd 
from sentence_transformers import SentenceTransformer, util
from datasets import Dataset
import boto3
import torch
import io
import json
import os
import sys
sys.path.append('/home/ec2-user/SageMaker/semantic-search-with-amazon-opensearch/src')
sys.path.append('/home/ec2-user/SageMaker/semantic-search-model-evaluation/src/')
sys.path.append('/home/ec2-user/SageMaker/semantic-search-model-evaluation/src/data_processing/')

from tqdm import tqdm

from data_processing.utils.full_processing import process_data_e2e
from src.inference import model_fn, predict_fn

import logging
import sys

logging.basicConfig(
    level=logging.INFO,
    stream=sys.stdout,
    format='%(asctime)s - %(levelname)s - %(message)s'
)

In [19]:
# Load metadata
def read_parquet_from_s3_as_df(region, s3_bucket, s3_key):
    """
    Load a Parquet file from an S3 bucket into a pandas DataFrame.

    Parameters:
    - region: AWS region where the S3 bucket is located.
    - s3_bucket: Name of the S3 bucket.
    - s3_key: Key (path) to the Parquet file within the S3 bucket.

    Returns:
    - df: pandas DataFrame containing the data from the Parquet file.
    """

    # Setup AWS session and clients
    session = boto3.Session(region_name=region)
    s3 = session.resource('s3')

    # Load the Parquet file as a pandas DataFrame
    object = s3.Object(s3_bucket, s3_key)
    body = object.get()['Body'].read()
    df = pd.read_parquet(io.BytesIO(body))
    return df


# Upload the duplicate date to S3 as a parquet file 
def upload_df_to_s3_as_parquet(df, bucket_name, file_key):
    # Save DataFrame as a Parquet file locally
    parquet_file_path = 'temp.parquet'
    df.to_parquet(parquet_file_path)

    # Create an S3 client
    s3_client = boto3.client('s3')

    # Upload the Parquet file to S3 bucket
    try:
        response = s3_client.upload_file(parquet_file_path, bucket_name, file_key)
        os.remove(parquet_file_path)
        print(f'Uploading {file_key} to {bucket_name} as parquet file')
        # Delete the local Parquet file
        return True
    except Exception as e:
        print(e)
        return False

## 1.Preprocess the text [No need to run for model deployment]

Note, change the parquet bucket name to'-dev', '-stage', or '-prod' based on the environment you are running the file.

In [7]:
# 1. Load the data
df_parquet = read_parquet_from_s3_as_df('ca-central-1', 'webpresence-geocore-geojson-to-parquet-stage', '1-records.parquet')
df_sentinel1 = read_parquet_from_s3_as_df('ca-central-1', 'webpresence-geocore-geojson-to-parquet-stage', '1-sentinel1.parquet')
# df_sentinel2 = read_parquet_from_s3_as_df('ca-central-1', 'webpresence-geocore-geojson-to-parquet-stage', '2-sentinel1.parquet')
df_rcm = read_parquet_from_s3_as_df('ca-central-1', 'webpresence-geocore-geojson-to-parquet-stage', '1-rcm-ard.parquet')

# df = pd.concat([df_parquet, df_sentinel1, df_sentinel2, df_rcm], ignore_index=True)
df = pd.concat([df_parquet, df_sentinel1, df_rcm], ignore_index=True)
df.shape

2026-08-25 13:59:40,169 - INFO - Found credentials from IAM Role: BaseNotebookInstanceEc2InstanceRole
2026-08-25 13:59:41,156 - INFO - Found credentials from IAM Role: BaseNotebookInstanceEc2InstanceRole
2026-08-25 13:59:41,369 - INFO - Found credentials from IAM Role: BaseNotebookInstanceEc2InstanceRole

(22132, 72)

In [ ]:
# 2. Apply all required preprocessing on the data
df_processed = process_data_e2e(df, region='ca-central-1', keep_eoCollections=True)
df_processed.shape

2026-08-25 13:59:42,108 - INFO - Starting processing job. Applying full preprocessing to entire dataset before text_normalization and train-test split.
2026-08-25 13:59:42,119 - INFO - Selected required columns. Dataset shape: (22132, 24)
2026-08-25 13:59:42,120 - INFO - Starting data normalization
2026-08-25 13:59:42,121 - INFO - Replacing 'Not Available; Indisponible' with None in columns: ['features_properties_date_published_date', 'features_properties_date_created_date']
2026-08-25 13:59:42,130 - INFO - Successfully replaced
2026-08-25 13:59:42,131 - INFO - Updating source system name from 'cgp' or None to 'geo-ca'
2026-08-25 13:59:42,135 - INFO - Successfully updated
2026-08-25 13:59:42,136 - INFO - Converting values to lists for columns: ['features_properties_topicCategory', 'features_properties_keywords_en', 'features_properties_keywords_fr']
2026-08-25 13:59:42,747 - INFO - Successfully converted
2026-08-25 13:59:42,748 - INFO - Extracting unique descriptions for features_properties_type
2026-08-25 13:59:43,425 - INFO - Successfully extracted
2026-08-25 13:59:43,425 - INFO - Starting feature engineering
2026-08-25 13:59:43,426 - INFO - Creating temporalExtent feature
2026-08-25 13:59:43,627 - INFO - Dropping original temporalExtent columns
2026-08-25 13:59:43,643 - INFO - Successfully created temporalExtent feature
2026-08-25 13:59:43,643 - INFO - Extracting organization information into features_properties_org. Prioritizing cited over contact.
2026-08-25 13:59:43,946 - INFO - Successfully extracted organization information
2026-08-25 13:59:43,947 - INFO - Creating features_properties_mappable based on features_properties_options
2026-08-25 13:59:44,564 - INFO - Successfully created mappable feature
2026-08-25 13:59:44,565 - INFO - Adding geo theme
2026-08-25 13:59:44,609 - INFO - Successfully added geo theme via mapping
2026-08-25 13:59:44,609 - INFO - Enriching geo theme with DynamoDB data
2026-08-25 13:59:44,627 - INFO - Found credentials from IAM Role: BaseNotebookInstanceEc2InstanceRole
2026-08-25 13:59:45,236 - INFO - Creating is_foundational feature based on geo theme
2026-08-25 13:59:45,254 - INFO - Successfully created is_foundational feature
2026-08-25 13:59:45,255 - INFO - Completed DynamoDB enrichment.
2026-08-25 13:59:45,255 - INFO - Complete preprocessing disabled. Applying preprocessing for natural language processing and training preparation without feature engineering.
2026-08-25 13:59:45,256 - INFO - Converting values to lists for columns: ['features_properties_keywords_en', 'features_properties_keywords_fr']
2026-08-25 13:59:45,271 - INFO - Successfully converted
2026-08-25 13:59:45,272 - INFO - Starting text normalization for semantic search
2026-08-25 13:59:45,272 - INFO - Normalizing text in columns: ['features_properties_description']
2026-08-25 13:59:45,273 - WARNING - Some columns in text_columns do not end with '_en' or '_fr'. Expanding column list to include all language variants.
2026-08-25 13:59:45,274 - INFO - Normalizing column features_properties_description_en into new column features_properties_description_normalized_en
2026-08-25 13:59:45,302 - WARNING - Invalid text being passed for section removal: <NA>. Skipping.
2026-08-25 13:59:45,375 - INFO - Applied function remove_section_and_onwards to column features_properties_description_normalized_en. Rows affected: 886.
2026-08-25 13:59:45,437 - WARNING - Invalid text being passed for url masking: <NA>. Returning text without masking urls.
2026-08-25 13:59:45,647 - INFO - Applied function mask_urls to column features_properties_description_normalized_en. Rows affected: 11518.
2026-08-25 13:59:45,863 - WARNING - Invalid text being passed for email masking: <NA>. Returning text without masking emails.
2026-08-25 13:59:46,677 - INFO - Applied function mask_emails to column features_properties_description_normalized_en. Rows affected: 494.
2026-08-25 13:59:46,692 - WARNING - Invalid text, symbol, or word being passed for symbol-to-word mapping:
Symbol: -->
Word:  then
Text: <NA>. Skipping.
2026-08-25 13:59:46,723 - INFO - Applied function map_symbol_to_word to column features_properties_description_normalized_en. Rows affected: 6.
2026-08-25 13:59:46,738 - WARNING - Invalid text, symbol, or word being passed for symbol-to-word mapping:
Symbol: °
Word:  degrees
Text: <NA>. Skipping.
2026-08-25 13:59:46,771 - INFO - Applied function map_symbol_to_word to column features_properties_description_normalized_en. Rows affected: 176.
2026-08-25 13:59:46,795 - WARNING - Invalid text, symbol, or word being passed for symbol-to-word mapping:
Symbol: \n
Word:

Text: <NA>. Skipping.
2026-08-25 13:59:46,863 - INFO - Applied function map_symbol_to_word to column features_properties_description_normalized_en. Rows affected: 17022.
2026-08-25 13:59:47,027 - WARNING - Invalid text being passed for table conversion: <NA>. Skipping.
2026-08-25 13:59:47,562 - INFO - Applied function convert_tables_to_text to column features_properties_description_normalized_en. Rows affected: 4.
2026-08-25 13:59:47,623 - WARNING - Invalid text being passed for punctuation removal: <NA>. Skipping.
2026-08-25 13:59:47,868 - INFO - Applied function remove_unnatural_punctuation to column features_properties_description_normalized_en. Rows affected: 15353.
2026-08-25 13:59:48,170 - WARNING - Invalid text being passed for whitespace removal: <NA>. Skipping.
2026-08-25 13:59:49,131 - INFO - Applied function remove_extra_whitespace to column features_properties_description_normalized_en. Rows affected: 16142.
2026-08-25 13:59:49,134 - INFO - Normalizing column features_properties_description_fr into new column features_properties_description_normalized_fr
2026-08-25 13:59:49,233 - INFO - Applied function remove_section_and_onwards to column features_properties_description_normalized_fr. Rows affected: 3452.
2026-08-25 13:59:49,495 - INFO - Applied function mask_urls to column features_properties_description_normalized_fr. Rows affected: 11516.

In [ ]:
print(type(df_processed['text_seq'].head(6)[2]))
print(df_processed['text_seq'].head(6)[2])

### Test Embed (requires update of inference.py import load)

In [ ]:
# getting subset of corpus for test
df_processed_subset = df_processed.iloc[:1000]

In [16]:
# Step 4: Embedding text 
tqdm.pandas()
model_directory ="/home/ec2-user/SageMaker/semantic-search-with-amazon-opensearch/model/gte-multi-ft2-se"
model = model_fn(model_directory) #(model, tokenizer)
model[0].eval()
model[1].model_max_length = 1024

# fixing corrupted position_ids buffer according to: https://huggingface.co/Alibaba-NLP/gte-multilingual-base/discussions/30
# embeddings = model[0].embeddings
# max_pos = embeddings.position_ids.size(0)
# embeddings.register_buffer("position_ids", torch.arange(max_pos), persistent=True)

df_processed_subset['vector'] = df_processed_subset['text_seq'].progress_apply(lambda x: predict_fn({"inputs": x}, model))

Loading weights: 100%|██████████| 136/136 [00:00<00:00, 4517.93it/s]
  0%|          | 1/1000 [00:00<00:11, 86.42it/s]

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:13                                                                                   │
│                                                                                                  │
│   10 # max_pos = embeddings.position_ids.size(0)                                                 │
│   11 # embeddings.register_buffer("position_ids", torch.arange(max_pos), persistent=True)        │
│   12                                                                                             │
│ ❱ 13 df_processed_subset['vector'] = df_processed_subset['text_seq'].progress_apply(lambda x:    │
│   14                                                                                             │
│                                                                                                  │
│ /home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/tqdm/std.py:923 in inner      │
│                                                                                                  │
│    920 │   │   │   │   # Apply the provided function (in **kwargs)                               │
│    921 │   │   │   │   # on the df using our wrapper (which provides bar updating)               │
│    922 │   │   │   │   try:                                                                      │
│ ❱  923 │   │   │   │   │   return getattr(df, df_function)(wrapper, **kwargs)                    │
│    924 │   │   │   │   finally:                                                                  │
│    925 │   │   │   │   │   t.close()                                                             │
│    926                                                                                           │
│                                                                                                  │
│ /home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/pandas/core/series.py:4943 in │
│ apply                                                                                            │
│                                                                                                  │
│   4940 │   │   │   by_row=by_row,                                                                │
│   4941 │   │   │   args=args,                                                                    │
│   4942 │   │   │   kwargs=kwargs,                                                                │
│ ❱ 4943 │   │   ).apply()                                                                         │
│   4944 │                                                                                         │
│   4945 │   def _reindex_indexer(                                                                 │
│   4946 │   │   self,                                                                             │
│                                                                                                  │
│ /home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/pandas/core/apply.py:1422 in  │
│ apply                                                                                            │
│                                                                                                  │
│   1419 │   │   │   return self.apply_compat()                                                    │
│   1420 │   │                                                                                     │
│   1421 │   │   # self.func is Callable                                                           │
│ ❱ 1422 │   │   return self.apply_standard()                                                      │
│   1423 │                                                                                         │
│   1424 │   def agg(self):                                                                        │
│   1425 │   │   result = super().agg()                                                            │
│                                                                                                  │
│ /home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/pandas/core/apply.py:1502 in  │
│ apply_standard                                                                                   │
│                                                                                                  │
│   1499 │   │   # TODO: remove the `na_action="ignore"` when that default has been changed in     │
│   1500 │   │   #  Categorical (GH51645).                                                         │
│   1501 │   │   action = "ignore" if isinstance(obj.dtype, CategoricalDtype) else None            │
│ ❱ 1502 │   │   mapped = obj._map_values(                                                         │
│   1503 │   │   │   mapper=curried, na_action=action, convert=self.convert_dtype                  │
│   1504 │   │   )                                                                                 │
│   1505                                                                                           │
│                                                                                                  │
│ /home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/pandas/core/base.py:925 in    │
│ _map_values                                                                                      │
│                                                                                                  │
│    922 │   │   if isinstance(arr, ExtensionArray):                                               │
│    923 │   │   │   return arr.map(mapper, na_action=na_action)                                   │
│    924 │   │                                                                                     │
│ ❱  925 │   │   return algorithms.map_array(arr, mapper, na_action=na_action, convert=convert)    │
│    926 │                                                                                         │
│    927 │   @final                                                                                │
│    928 │   def value_counts(                                                                     │
│                                                                                                  │
│ /home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/pandas/core/algorithms.py:174 │
│ 3 in map_array                                                                                   │
│                                                                                                  │
│   1740 │   # we must convert to python types                                                     │
│   1741 │   values = arr.astype(object, copy=False)                                               │
│   1742 │   if na_action is None:                                                                 │
│ ❱ 1743 │   │   return lib.map_infer(values, mapper, convert=convert)                             │
│   1744 │   else:                                                                                 │
│   1745 │   │   return lib.map_infer_mask(                                                        │
│   1746 │   │   │   values, mapper, mask=isna(values).view(np.uint8), convert=convert             │
│                                                                                                  │
│ in pandas._libs.lib.map_infer:2999                                                               │
│                                                                                                  │
│ /home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/tqdm/std.py:918 in wrapper    │
│                                                                                                  │
│    915 │   │   │   │   │   # on the first column/row to decide whether it can                    │
│    916 │   │   │   │   │   # take a fast or slow code path; so stop when t.total==t.n            │
│    917 │   │   │   │   │   t.update(n=1 if not t.total or t.n < t.total else 0)                  │
│ ❱  918 │   │   │   │   │   return func(*args, **kwargs)                                          │
│    919 │   │   │   │                                                                             │
│    920 │   │   │   │   # Apply the provided function (in **kwargs)                               │
│    921 │   │   │   │   # on the df using our wrapper (which provides bar updating)               │
│                                                                                                  │
│ in <lambda>:13                                                                                   │
│                                                                                                  │
│   10 # max_pos = embeddings.position_ids.size(0)                                                 │
│   11 # embeddings.register_buffer("position_ids", torch.arange(max_pos), persistent=True)        │
│   12                                                                                             │
│ ❱ 13 df_processed_subset['vector'] = df_processed_subset['text_seq'].progress_apply(lambda x:    │
│   14                                                                                             │
│                                                                                                  │
│ /home/ec2-user/SageMaker/semantic-search-with-amazon-opensearch/src/inference.py:55 in           │
│ predict_fn                                                                                       │
│                                                                                                  │
│   52 │                                                                                           │
│   53 │   # Compute token embeddings                                                              │
│   54 │   with torch.no_grad():                                                                   │
│ ❱ 55 │   │   model_output = model(**encoded_input)                                               │
│   56 │                                                                                           │
│   57 │   # Perform pooling                                                                       │
│   58 │   sentence_embeddings = mean_pooling(model_output, encoded_input['attention_mask'])       │
│                                                                                                  │
│ /home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/torch/nn/modules/module.py:17 │
│ 78 in _wrapped_call_impl                                                                         │
│                                                                                                  │
│   1775 │   │   if self._compiled_call_impl is not None:                                          │
│   1776 │   │   │   return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]        │
│   1777 │   │   else:                                                                             │
│ ❱ 1778 │   │   │   return self._call_impl(*args, **kwargs)                                       │
│   1779 │                                                                                         │
│   1780 │   # torchrec tests the code consistency with the following code                         │
│   1781 │   # fmt: off                                                                            │
│                                                                                                  │
│ /home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/torch/nn/modules/module.py:17 │
│ 89 in _call_impl                                                                                 │
│                                                                                                  │
│   1786 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1787 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1788 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1789 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1790 │   │                                                                                     │
│   1791 │   │   result = None                                                                     │
│   1792 │   │   called_always_called_hooks = set()                                                │
│                                                                                                  │
│ /home/ec2-user/.cache/huggingface/modules/transformers_modules/gte_hyphen_multi_hyphen_ft2_hyphe │
│ n_se/3e236c84b2a8f05e/modeling.py:901 in forward                                                 │
│                                                                                                  │
│    898 │   │   # head_mask = self.get_head_mask(head_mask, self.config.num_hidden_layers)        │
│    899 │   │                                                                                     │
│    900 │   │   # Get embeddings, may unpad them                                                  │
│ ❱  901 │   │   (embedding_output, attention_mask, rope_embeds, length) = self.embeddings(        │
│    902 │   │   │   unpad_inputs,                                                                 │
│    903 │   │   │   input_ids=input_ids,                                                          │
│    904 │   │   │   attention_mask=attention_mask,                                                │
│                                                                                                  │
│ /home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/torch/nn/modules/module.py:17 │
│ 78 in _wrapped_call_impl                                                                         │
│                                                                                                  │
│   1775 │   │   if self._compiled_call_impl is not None:                                          │
│   1776 │   │   │   return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]        │
│   1777 │   │   else:                                                                             │
│ ❱ 1778 │   │   │   return self._call_impl(*args, **kwargs)                                       │
│   1779 │                                                                                         │
│   1780 │   # torchrec tests the code consistency with the following code                         │
│   1781 │   # fmt: off                                                                            │
│                                                                                                  │
│ /home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/torch/nn/modules/module.py:17 │
│ 89 in _call_impl                                                                                 │
│                                                                                                  │
│   1786 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1787 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1788 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1789 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1790 │   │                                                                                     │
│   1791 │   │   result = None                                                                     │
│   1792 │   │   called_always_called_hooks = set()                                                │
│                                                                                                  │
│ /home/ec2-user/.cache/huggingface/modules/transformers_modules/gte_hyphen_multi_hyphen_ft2_hyphe │
│ n_se/3e236c84b2a8f05e/modeling.py:392 in forward                                                 │
│                                                                                                  │
│    389 │   │   # Compute rotary embedding                                                        │
│    390 │   │   if self.position_embedding_type == 'rope':                                        │
│    391 │   │   │   rope_cos, rope_sin = self.rotary_emb(inputs_embeds, seq_len=seq_length)       │
│ ❱  392 │   │   │   rope_cos = rope_cos[position_ids].unsqueeze(2)  # [bs, seq_len, 1, dim]       │
│    393 │   │   │   rope_sin = rope_sin[position_ids].unsqueeze(2)  # [bs, seq_len, 1, dim]       │
│    394 │   │   │   rope_embeds = rope_cos, rope_sin                                              │
│    395 │   │   else:                                                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
IndexError: index 94330941776059 is out of bounds for dimension 0 with size 1024

In [17]:
vector = df_processed_subset['vector'].head(6) 
# print(vector[0])
print(type(vector[0]))
print(len(vector[0]))
print(df_processed_subset['vector'].shape)

<class 'list'>
768
(1000,)

In [18]:
df_processed_subset.head(4)

,features_properties_id,features_geometry_coordinates,features_properties_title_en,features_properties_title_fr,features_properties_description_en,features_properties_description_fr,features_properties_date_published_date,features_properties_keywords_en,features_properties_keywords_fr,features_properties_options,...,features_properties_mappable,features_properties_geo_theme,features_properties_foundational,features_properties_description_normalized_en,features_properties_description_normalized_fr,text_en,text_fr,text_seq,text_para,vector
0,d3881c4c-650d-4070-bf9b-1e00aabf0a1d,"[[[-143, 39.05], [-47, 39.05], [-47, 85], [-14...",Canadian Hydrographic Service Non-Navigational...,Données bathymétriques non navigationnelles (N...,"**CHS NONNA data has been updated: April 1, 20...",**Les données NONNA du Service hydrographique ...,2018-10-11,"[Bathymetry, Depth, Hydrography]","[Bathymétrie, les profondeurs des fonds marins...","[{""url"": ""https://data.chs-shc.ca/"", ""protocol...",...,true,"[environment, foundational]",true,"*CHS NONNA data has been updated: April 1, 202...",*Les données NONNA du Service hydrographique d...,Canadian Hydrographic Service Non-Navigational...,Données bathymétriques non navigationnelles (N...,Canadian Hydrographic Service Non-Navigational...,Canadian Hydrographic Service Non-Navigational...,"[-0.057738080620765686, 0.045166634023189545, ..."
1,3d282116-e556-400c-9306-ca1a3cada77f,"[[[-141.0027151, 41.7], [-52.6, 41.7], [-52.6,...",National Road Network - NRN - GeoBase Series,Réseau routier national - RRN - Série GéoBase,Notice - Format decommissioning\n\nGML (Geogra...,Avis - Changement aux formats offerts\n\nLes f...,2015,"[Canada, Geographic Infrastructure, NRN, Natio...","[Canada, Infrastructure géographique, RRN, Rés...","[{""url"": ""https://geo.statcan.gc.ca/geo_wa/ser...",...,true,"[administration, foundational]",true,Notice - Format decommissioning\nGML (Geograph...,Avis - Changement aux formats offerts\nLes for...,National Road Network - NRN - GeoBase Series\n...,Réseau routier national - RRN - Série GéoBase\...,National Road Network - NRN - GeoBase Series\n...,National Road Network - NRN - GeoBase Series\n...,"[-0.06598811596632004, 0.053342439234256744, -..."
2,b6567c5c-8339-4055-99fa-63f92114d9e4,"[[[-141.003, 41.6755], [-52.6174, 41.6755], [-...",First Nations Location,Localisation des Premières Nations,The First Nations geographic location dataset ...,Le jeu de données des Premières Nations contie...,2015-05-01,"[First Nation, Band, Aboriginal, Indian and No...","[Première Nation, bande, autochtone, Affaires ...","[{""url"": ""https://data.aadnc-aandc.gc.ca/geoma...",...,true,"[administration, society, foundational]",true,The First Nations geographic location dataset ...,Le jeu de données des Premières Nations contie...,"First Nations Location\nkeywords:First Nation,...",Localisation des Premières Nations\nmots-clés ...,"First Nations Location\nkeywords:First Nation,...",First Nations Location\nLocalisation des Premi...,"[-0.0812927633523941, 0.06198863312602043, -0...."
3,522b07b9-78e2-4819-b736-ad9208eb1067,"[[[-141.003, 41.6755], [-52.6174, 41.6755], [-...",Aboriginal Lands of Canada Legislative Boundaries,Limites législatives des terres autochtones du...,The Aboriginal Lands of Canada Legislative Bou...,Le service web des limites législatives des te...,2017-07-28,"[Canada Lands, Indian reserves, Land managemen...","[Terres du Canada, Réserves indiennes, Gestion...","[{""url"": ""https://proxyinternet.nrcan-rncan.gc...",...,true,"[administration, foundational]",true,The Aboriginal Lands of Canada Legislative Bou...,Le service web des limites législatives des te...,Aboriginal Lands of Canada Legislative Boundar...,Limites législatives des terres autochtones du...,Aboriginal Lands of Canada Legislative Boundar...,Aboriginal Lands of Canada Legislative Boundar...,"[-0.07931932061910629, 0.04605397209525108, -0..."

## 2. Generate embeddings using local model

In [20]:
import os
os.environ['ENV']='stage'

Set model_max_length in tokenizer_config.json manually.
Make sure code/inference.py is added to the gte model files.

**Important**: copy custom inference.py code to model folder under a code/ directory

- !mkdir /home/ec2-user/SageMaker/semantic-search-with-amazon-opensearch/model/gte-multi-ft-se/code
- !cp /home/ec2-user/SageMaker/semantic-search-with-amazon-opensearch/src/inference.py /home/ec2-user/SageMaker/semantic-search-with-amazon-opensearch/model/gte-multi-ft2-se/code/


Copy of Contents of inference.py:

```
import logging
import requests

# import os
# import json
# import io
# import time
import torch
from transformers import AutoTokenizer, AutoConfig, AutoModel
import torch.nn.functional as F

logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)

#Mean Pooling - Take attention mask into account for correct averaging
def mean_pooling(model_output, attention_mask):
    token_embeddings = model_output[0] #First element of model_output contains all token embeddings
    input_mask_expanded = attention_mask.unsqueeze(-1).expand(token_embeddings.size()).float()
    return torch.sum(token_embeddings * input_mask_expanded, 1) / torch.clamp(input_mask_expanded.sum(1), min=1e-9)


def model_fn(model_dir):
    # Load model from HuggingFace Hub
    config = AutoConfig.from_pretrained(
        model_dir,
        trust_remote_code=True,
        local_files_only=True
    )
    
    tokenizer = AutoTokenizer.from_pretrained(
        model_dir,
        trust_remote_code=True,
        local_files_only=True
    )
    
    model = AutoModel.from_pretrained(
        model_dir,
        config=config,
        trust_remote_code=True,
        local_files_only=True
    )
    
    return model, tokenizer

def predict_fn(data, model_and_tokenizer):
    # destruct model and tokenizer
    model, tokenizer = model_and_tokenizer

    # Tokenize sentences
    sentences = data.pop("inputs", data)
    encoded_input = tokenizer(sentences, padding=True, truncation=True, max_length = tokenizer.model_max_length, return_tensors='pt')

    # Compute token embeddings
    with torch.no_grad():
        model_output = model(**encoded_input)

    # Perform pooling
    sentence_embeddings = mean_pooling(model_output, encoded_input['attention_mask'])

    # Normalize embeddings
    sentence_embeddings = F.normalize(sentence_embeddings, p=2, dim=1)

    # return dictonary, which will be json serializable
    return  sentence_embeddings[0].tolist()

```

In [6]:
# DO NOT RERUN - test
# !python ./src/embed_all_records/run_embedding_job.py \
#     --sagemaker_job_name "semantic-search-nbv3se-e2e-processing" \
#     --input_s3 "webpresence-geocore-geojson-to-parquet-stage" \
#     --output_s3 "webpresence-nlp-data-preprocessing-stage" \
#     --model_name "gte-multi-ft-se" \
#     --run_test \

sagemaker.config INFO - Not applying SDK defaults from location: /etc/xdg/sagemaker/config.yaml
sagemaker.config INFO - Not applying SDK defaults from location: /home/ec2-user/.config/sagemaker/config.yaml
/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/sagemaker/__init__.py:86: SageMakerV2DeprecationWarning: You are using the SageMaker Python SDK v2, which is on path of deprecation. v3 is the actively developed major version.
See https://github.com/aws/sagemaker-python-sdk/blob/master/migration.md for the migration guide. Set SAGEMAKER_SUPPRESS_V2_WARNING=1 to silence this warning.
  warn_v2_deprecation()
You are using the SageMaker Python SDK v2, which is on path of deprecation. v3 is the actively developed major version.
See https://github.com/aws/sagemaker-python-sdk/blob/master/migration.md for the migration guide. Set SAGEMAKER_SUPPRESS_V2_WARNING=1 to silence this warning.
2026-08-25 14:05:15,838 - __main__ - INFO - Kickstarting embedding job
usage: run_embedding_job.py [-h] [--sagemaker_job_name SAGEMAKER_JOB_NAME]
                            [--input_s3 INPUT_S3] [--output_s3 OUTPUT_S3]
                            [--model_name MODEL_NAME] [--run_test]
run_embedding_job.py: error: unrecognized arguments: \

In [10]:
# embed all records [remove wait and logs for it to run in background, takes approx 3h]
!python ./src/embed_all_records/run_embedding_job.py --sagemaker_job_name "semantic-search-nbv3se-e2e-processing" --input_s3 "webpresence-geocore-geojson-to-parquet-stage" --output_s3 "webpresence-nlp-data-preprocessing-stage" --model_name "gte-multi-ft2-se"

sagemaker.config INFO - Not applying SDK defaults from location: /etc/xdg/sagemaker/config.yaml
sagemaker.config INFO - Not applying SDK defaults from location: /home/ec2-user/.config/sagemaker/config.yaml
/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/sagemaker/__init__.py:86: SageMakerV2DeprecationWarning: You are using the SageMaker Python SDK v2, which is on path of deprecation. v3 is the actively developed major version.
See https://github.com/aws/sagemaker-python-sdk/blob/master/migration.md for the migration guide. Set SAGEMAKER_SUPPRESS_V2_WARNING=1 to silence this warning.
  warn_v2_deprecation()
You are using the SageMaker Python SDK v2, which is on path of deprecation. v3 is the actively developed major version.
See https://github.com/aws/sagemaker-python-sdk/blob/master/migration.md for the migration guide. Set SAGEMAKER_SUPPRESS_V2_WARNING=1 to silence this warning.
2026-08-25 14:09:50,701 - __main__ - INFO - Kickstarting embedding job
2026-08-25 14:09:50,702 - __main__ - INFO - Argument 'sagemaker_job_name' is set to: semantic-search-nbv3se-e2e-processing
2026-08-25 14:09:50,702 - __main__ - INFO - Argument 'input_s3' is set to: webpresence-geocore-geojson-to-parquet-stage
2026-08-25 14:09:50,702 - __main__ - INFO - Argument 'output_s3' is set to: webpresence-nlp-data-preprocessing-stage
2026-08-25 14:09:50,702 - __main__ - INFO - Argument 'model_name' is set to: gte-multi-ft2-se
2026-08-25 14:09:50,702 - __main__ - INFO - Argument 'run_test' is set to: False
2026-08-25 14:09:50,702 - __main__ - INFO - Authenticating
2026-08-25 14:09:50,719 - botocore.credentials - INFO - Found credentials from IAM Role: BaseNotebookInstanceEc2InstanceRole
2026-08-25 14:09:51,030 - __main__ - INFO - Authentication complete.
/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/sagemaker/processing.py:138: SageMakerV2DeprecationWarning: FrameworkProcessor is part of the SageMaker Python SDK v2, which is on path of deprecation. In v3, use `DataProcessor` (`from sagemaker.mlops.processing import DataProcessor`).
See https://github.com/aws/sagemaker-python-sdk/blob/master/migration.md for the migration guide. Set SAGEMAKER_SUPPRESS_V2_WARNING=1 to silence this warning.
  warn_v2_deprecation(
2026-08-25 14:09:51,032 - sagemaker.deprecations - WARNING - FrameworkProcessor is part of the SageMaker Python SDK v2, which is on path of deprecation. In v3, use `DataProcessor` (`from sagemaker.mlops.processing import DataProcessor`).
See https://github.com/aws/sagemaker-python-sdk/blob/master/migration.md for the migration guide. Set SAGEMAKER_SUPPRESS_V2_WARNING=1 to silence this warning.
2026-08-25 14:09:51,047 - botocore.credentials - INFO - Found credentials from IAM Role: BaseNotebookInstanceEc2InstanceRole
/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/sagemaker/estimator.py:588: SageMakerV2DeprecationWarning: SKLearn is part of the SageMaker Python SDK v2, which is on path of deprecation. In v3, use `ModelTrainer` (`from sagemaker.train import ModelTrainer`).
See https://github.com/aws/sagemaker-python-sdk/blob/master/migration.md for the migration guide. Set SAGEMAKER_SUPPRESS_V2_WARNING=1 to silence this warning.
  warn_v2_deprecation(
2026-08-25 14:09:51,195 - sagemaker.deprecations - WARNING - SKLearn is part of the SageMaker Python SDK v2, which is on path of deprecation. In v3, use `ModelTrainer` (`from sagemaker.train import ModelTrainer`).
See https://github.com/aws/sagemaker-python-sdk/blob/master/migration.md for the migration guide. Set SAGEMAKER_SUPPRESS_V2_WARNING=1 to silence this warning.
2026-08-25 14:09:51,210 - botocore.credentials - INFO - Found credentials from IAM Role: BaseNotebookInstanceEc2InstanceRole
2026-08-25 14:09:51,951 - sagemaker.processing - INFO - Uploaded src/embed_all_records to s3://sagemaker-ca-central-1-759472643633/semantic-search-nbv3se-e2e-processing-stage-20260825-140950/source/sourcedir.tar.gz
2026-08-25 14:09:52,028 - sagemaker.processing - INFO - runproc.sh uploaded to s3://sagemaker-ca-central-1-759472643633/semantic-search-nbv3se-e2e-processing-stage-20260825-140950/source/runproc.sh
2026-08-25 14:09:58,495 - sagemaker - INFO - Creating processing-job with name semantic-search-nbv3se-e2e-processing-stage-20260825-140950
2026-08-25 14:09:58,735 - __main__ - INFO - Finished preprocessing job.

## 3. Deploy model using sagemaker

Pre-requisite: go to the tokenizer_config.json in the model files and change model_max_length to 512. Can do this using the terminal

In [22]:
import boto3
import re
import time
import sagemaker
from sagemaker import get_execution_role
from sagemaker.huggingface.model import HuggingFaceModel

In [16]:
!cd /home/ec2-user/SageMaker/semantic-search-with-amazon-opensearch/model/gte-multi-ft2-se && tar czvf ../gte-multi-ft2-se.tar.gz *
# !cd /home/ec2-user/SageMaker/semantic-search-with-amazon-opensearch/model/gte-multi-ft-se && tar czvf ../gte-multi-ft-se.tar.gz *

1_Pooling/
1_Pooling/config.json
1_Pooling/.ipynb_checkpoints/
1_Pooling/.ipynb_checkpoints/config-checkpoint.json
2_Normalize/
README.md
code/
code/.ipynb_checkpoints/
code/.ipynb_checkpoints/inference-checkpoint.py
code/inference.py
config.json
config_sentence_transformers.json
configuration.py
eval/
eval/Information-Retrieval_evaluation_results.csv
model.safetensors
modeling.py
modules.json
sentence_bert_config.json
special_tokens_map.json
tokenizer.json
tokenizer_config.json
training_args.bin

In [23]:
LOCAL_MODEL_NAME_TO_DEPLOY =  "gte-multi-ft2-se"
SAGEMAKER_MODEL_NAME = "gte-multi-ft2"
# LOCAL_MODEL_NAME_TO_DEPLOY =  "gte-multi-ft-se"
# SAGEMAKER_MODEL_NAME = "gte-multi-ft-se"


sagemaker_session = sagemaker.Session()
inputs = sagemaker_session.upload_data(path=f'/home/ec2-user/SageMaker/semantic-search-with-amazon-opensearch/model/{LOCAL_MODEL_NAME_TO_DEPLOY}.tar.gz', key_prefix='sentence-transformers-model')
print(f"Response from model upload: {inputs}") 

# Create a SageMaker session and get the execution role to be used later 
role = sagemaker.get_execution_role()

# Deploy with model data 
hub = {
    # 'HF_TASK':'feature-extraction', # auto-builds pipeline with model and tokenizer, returns embeddings
}

# create Hugging Face Model Class
huggingface_model = HuggingFaceModel(
   model_data=inputs,  # path to your trained SageMaker model
   role=role,                                            # IAM role with permissions to create an endpoint
   transformers_version="4.51",                           # Transformers version used (closest to supported)
   pytorch_version="2.6",                                # PyTorch version used
   py_version='py312',                                    # Python version used (closest to supported)
   env=hub
)

# deploy model to SageMaker Inference
predictor = huggingface_model.deploy(
   initial_instance_count=1,
   instance_type="ml.m5.large", # Previous ml.t2.medium is deprecated, t3 is not available within list of valid configs, switching to m5 architecture
   endpoint_name = SAGEMAKER_MODEL_NAME
)

2026-09-09 15:28:57,843 - INFO - Found credentials from IAM Role: BaseNotebookInstanceEc2InstanceRole
Response from model upload: s3://sagemaker-ca-central-1-759472643633/sentence-transformers-model/gte-multi-ft2-se.tar.gz
2026-09-09 15:29:00,626 - INFO - Found credentials from IAM Role: BaseNotebookInstanceEc2InstanceRole
2026-09-09 15:29:00,806 - WARNING - HuggingFaceModel is part of the SageMaker Python SDK v2, which is on path of deprecation. In v3, use `ModelBuilder` (`from sagemaker.serve import ModelBuilder`).
See https://github.com/aws/sagemaker-python-sdk/blob/master/migration.md for the migration guide. Set SAGEMAKER_SUPPRESS_V2_WARNING=1 to silence this warning.
2026-09-09 15:29:00,822 - INFO - Found credentials from IAM Role: BaseNotebookInstanceEc2InstanceRole

/home/ec2-user/anaconda3/envs/pytorch/lib/python3.10/site-packages/sagemaker/model.py:347: SageMakerV2DeprecationWarning: HuggingFaceModel is part of the SageMaker Python SDK v2, which is on path of deprecation. In v3, use `ModelBuilder` (`from sagemaker.serve import ModelBuilder`).
See https://github.com/aws/sagemaker-python-sdk/blob/master/migration.md for the migration guide. Set SAGEMAKER_SUPPRESS_V2_WARNING=1 to silence this warning.
  warn_v2_deprecation(

2026-09-09 15:29:01,660 - INFO - Creating model with name: huggingface-pytorch-inference-2026-09-09-15-29-01-659
2026-09-09 15:29:02,161 - INFO - Creating endpoint-config with name gte-multi-ft2
2026-09-09 15:29:02,447 - INFO - Creating endpoint with name gte-multi-ft2
------!2026-09-09 15:32:33,382 - WARNING - HuggingFacePredictor is part of the SageMaker Python SDK v2, which is on path of deprecation. In v3, use `sagemaker.core.resources.Endpoint`.
See https://github.com/aws/sagemaker-python-sdk/blob/master/migration.md for the migration guide. Set SAGEMAKER_SUPPRESS_V2_WARNING=1 to silence this warning.

/home/ec2-user/anaconda3/envs/pytorch/lib/python3.10/site-packages/sagemaker/base_predictor.py:140: SageMakerV2DeprecationWarning: HuggingFacePredictor is part of the SageMaker Python SDK v2, which is on path of deprecation. In v3, use `sagemaker.core.resources.Endpoint`.
See https://github.com/aws/sagemaker-python-sdk/blob/master/migration.md for the migration guide. Set SAGEMAKER_SUPPRESS_V2_WARNING=1 to silence this warning.
  warn_v2_deprecation(

In [24]:
# example request: you always need to define "inputs"
data = {"inputs":" Today is a sunny and nice day in Ottawa"} 
# request
vector = predictor.predict(data)
len(vector)#{"inputs": ["floods event in Canada", "earthquakes"]}

768

## 4. Create OpenSearch index and load text/vector data into the index

In [30]:
df = read_parquet_from_s3_as_df('ca-central-1', 'webpresence-nlp-data-preprocessing-stage', 'semantic_search_embeddings-gte-multi-ft2-se.parquet')
df.shape

2026-09-09 18:20:47,879 - INFO - Found credentials from IAM Role: BaseNotebookInstanceEc2InstanceRole

(22132, 34)

In [31]:
# import json
# import time
# import boto3

# from tqdm import tqdm
# from urllib.parse import urlparse
# from opensearchpy import OpenSearch, RequestsHttpConnection, AWSV4SignerAuth
# import src.opensearch as opensearch
from src.opensearch import get_awsauth_from_secret, create_opensearch_connection, delete_aos_index_if_exists, load_data_to_opensearch_index
# from Preprocess_and_embed_text import read_parquet_from_s3_as_df

In [32]:
df.head(4)

,features_properties_id,features_geometry_coordinates,features_properties_title_en,features_properties_title_fr,features_properties_description_en,features_properties_description_fr,features_properties_date_published_date,features_properties_keywords_en,features_properties_keywords_fr,features_properties_options,...,features_properties_mappable,features_properties_geo_theme,features_properties_foundational,features_properties_description_normalized_en,features_properties_description_normalized_fr,text_en,text_fr,text_seq,text_para,vector
0,eodms-rcm-ard,"[[[-180.0, -90.0], [180.0, -90.0], [180.0, 90....",STAC-Collection - RADARSAT Constellation Missi...,STAC-Collection - RADARSAT Constellation Missi...,The RADARSAT Constellation Mission (RCM) is Ca...,La Mission de la Constellation RADARSAT (MCR) ...,<NA>,"[SpatioTemporal Asset Catalog, stac, sar, eo, ...","[SpatioTemporal Asset Catalog, stac, rcm, rcm-...","[{""url"": ""https://eodms-sgdot.nrcan-rncan.gc.c...",...,false,[imagery],false,The RADARSAT Constellation Mission (RCM) is Ca...,La Mission de la Constellation RADARSAT (MCR) ...,STAC-Collection - RADARSAT Constellation Missi...,STAC-Collection - RADARSAT Constellation Missi...,STAC-Collection - RADARSAT Constellation Missi...,STAC-Collection - RADARSAT Constellation Missi...,"[[-0.05734883248806, 0.05576413497328758, -0.0..."
1,eodms-rcm-ard-00018e6e-c08c-4439-b0ae-263ba4a8...,"[[[-107.98, 50.54], [-105.97, 50.54], [-105.97...",STAC-Item - RCM1-OK3433412-PK3549259-2-SC30MCP...,STAC-Item - RCM1-OK3433412-PK3549259-2-SC30MCP...,The RADARSAT Constellation Mission (RCM) is Ca...,La Mission de la Constellation RADARSAT (MCR) ...,2025-04-04T11:28:16.645473+00:00,"[SpatioTemporal Asset Catalog, stac, sar, eo, ...","[SpatioTemporal Asset Catalog, stac, rcm, rcm-...","[{""url"": ""https://eodms-sgdot.nrcan-rncan.gc.c...",...,false,[imagery],false,The RADARSAT Constellation Mission (RCM) is Ca...,La Mission de la Constellation RADARSAT (MCR) ...,STAC-Item - RCM1-OK3433412-PK3549259-2-SC30MCP...,STAC-Item - RCM1-OK3433412-PK3549259-2-SC30MCP...,STAC-Item - RCM1-OK3433412-PK3549259-2-SC30MCP...,STAC-Item - RCM1-OK3433412-PK3549259-2-SC30MCP...,"[[-0.06447061896324158, 0.05838947743177414, -..."
2,eodms-rcm-ard-000439c3-fa89-413a-8993-50fe8139...,"[[[-98.39, 56.61], [-95.58, 56.61], [-95.58, 5...",STAC-Item - RCM1-OK3556292-PK3699728-1-SC30MCP...,STAC-Item - RCM1-OK3556292-PK3699728-1-SC30MCP...,The RADARSAT Constellation Mission (RCM) is Ca...,La Mission de la Constellation RADARSAT (MCR) ...,2025-07-15T12:41:56.153210+00:00,"[SpatioTemporal Asset Catalog, stac, sar, eo, ...","[SpatioTemporal Asset Catalog, stac, rcm, rcm-...","[{""url"": ""https://eodms-sgdot.nrcan-rncan.gc.c...",...,false,[imagery],false,The RADARSAT Constellation Mission (RCM) is Ca...,La Mission de la Constellation RADARSAT (MCR) ...,STAC-Item - RCM1-OK3556292-PK3699728-1-SC30MCP...,STAC-Item - RCM1-OK3556292-PK3699728-1-SC30MCP...,STAC-Item - RCM1-OK3556292-PK3699728-1-SC30MCP...,STAC-Item - RCM1-OK3556292-PK3699728-1-SC30MCP...,"[[-0.058503106236457825, 0.0576583668589592, -..."
3,eodms-rcm-ard-0006529a-374c-47cb-9ab4-978fa858...,"[[[-73.14, 47.7], [-71.14, 47.7], [-71.14, 48....",STAC-Item - RCM1-OK3433412-PK3552250-2-SC30MCP...,STAC-Item - RCM1-OK3433412-PK3552250-2-SC30MCP...,The RADARSAT Constellation Mission (RCM) is Ca...,La Mission de la Constellation RADARSAT (MCR) ...,2025-04-07T12:45:24.136872+00:00,"[SpatioTemporal Asset Catalog, stac, sar, eo, ...","[SpatioTemporal Asset Catalog, stac, rcm, rcm-...","[{""url"": ""https://eodms-sgdot.nrcan-rncan.gc.c...",...,false,[imagery],false,The RADARSAT Constellation Mission (RCM) is Ca...,La Mission de la Constellation RADARSAT (MCR) ...,STAC-Item - RCM1-OK3433412-PK3552250-2-SC30MCP...,STAC-Item - RCM1-OK3433412-PK3552250-2-SC30MCP...,STAC-Item - RCM1-OK3433412-PK3552250-2-SC30MCP...,STAC-Item - RCM1-OK3433412-PK3552250-2-SC30MCP...,"[[-0.05846245586872101, 0.052547745406627655, ..."

In [33]:
df.columns

Index(['features_properties_id', 'features_geometry_coordinates',
       'features_properties_title_en', 'features_properties_title_fr',
       'features_properties_description_en',
       'features_properties_description_fr',
       'features_properties_date_published_date',
       'features_properties_keywords_en', 'features_properties_keywords_fr',
       'features_properties_options', 'features_properties_contact',
       'features_properties_cited', 'features_properties_topicCategory',
       'features_properties_date_created_date',
       'features_properties_spatialRepresentation', 'features_properties_type',
       'features_properties_graphicOverview', 'features_properties_language',
       'features_popularity', 'features_properties_sourceSystemName',
       'features_properties_eoCollection', 'features_properties_eoFilters',
       'temporalExtent', 'features_properties_org',
       'features_properties_mappable', 'features_properties_geo_theme',
       'features_properties_foundational',
       'features_properties_description_normalized_en',
       'features_properties_description_normalized_fr', 'text_en', 'text_fr',
       'text_seq', 'text_para', 'vector'],
      dtype='object')

In [34]:
df.iloc[0]['features_properties_org']

{'en': 'Natural Resources Canada', 'fr': 'Ressources naturelles Canada'}

In [35]:
df.iloc[0]['text_en']

"STAC-Collection - RADARSAT Constellation Mission, CEOS-ARD\nkeywords:SpatioTemporal Asset Catalog, stac, sar, eo, radar, radarsat, canada, rcm\nThe RADARSAT Constellation Mission (RCM) is Canada's third generation of Earth observation satellites. Launched on June 12, 2019, the three identical satellites work together to provide frequent, reliable radar imagery that supports a wide range of applications, including disaster management, environmental monitoring, maritime surveillance, and resource management.\nAs part of Canada's Open Government initiative, Natural Resources Canada (NRCan) produces a Canada-wide *CEOS Analysis Ready Data (ARD)* product covering the country's landmass at 30 m resolution using Compact Polarization (CP) imagery, updated every 12 days. The RCM CEOS-ARD (POL) product is the world's first polarimetric Analysis Ready Data dataset to receive approval from the Committee on Earth Observation Satellites (CEOS).\nTraditionally, users had to search for, order, download, and process Level-1 RCM imagery themselves—a time-consuming workflow that often required specialized expertise and expensive commercial software. The RCM CEOS-ARD (POL) dataset removes these barriers by providing preprocessed, analysis-ready imagery through a STAC catalog, enabling users to easily discover and directly download data for immediate use in GIS, remote sensing, and machine learning applications.\nThe RCM-ARD STAC collection on GEO.ca contains the most recent 10,000 harvested records from the Earth Observation Data Management System (EODMS). The complete RCM-ARD archive is available through the EODMS STAC API:\n*[eodms-sgdot.nrcan-rncan.gc.ca [url](eodms-sgdot.nrcan-rncan.gc.ca [url])* \n*This third party metadata element follows the Spatio Temporal Asset Catalog (STAC) specification.*"

In [36]:
import numpy as np

df['vector'] = df['vector'].apply(lambda x: x[0] if isinstance(x, np.ndarray) else x) # flatten vector if nested
df['vector'].iloc[0]

array([-0.05734883,  0.05576413, -0.02155791,  0.01239859,  0.02695446,
       -0.03818827,  0.01593043,  0.00220621,  0.06176485, -0.03431602,
       -0.03516543,  0.00375353, -0.05277827, -0.00724729, -0.0374023 ,
        0.05139132,  0.04843679,  0.04758472,  0.04543806,  0.01658751,
        0.03732302,  0.03272959,  0.0065688 , -0.00533454,  0.01294639,
        0.008801  ,  0.00828888, -0.04894459, -0.02695884,  0.01936491,
       -0.0436781 , -0.03902434,  0.00336892,  0.01342508,  0.05073424,
       -0.01233866,  0.02387898,  0.03332675,  0.01149063,  0.00595412,
       -0.03427663, -0.04196415,  0.03295107,  0.03067205, -0.02650969,
        0.02754686, -0.028095  ,  0.04619481, -0.03260451,  0.03651948,
       -0.00128593,  0.00456296,  0.0263576 ,  0.01770289,  0.05754316,
        0.02434408, -0.06959401,  0.02696146,  0.04812455,  0.01382929,
        0.01726251, -0.01297694,  0.01063029, -0.01005436,  0.004951  ,
       -0.00027916,  0.02188816,  0.02602805,  0.09059728,  0.03389744,
       -0.00827866,  0.02802965, -0.03138858,  0.0243042 ,  0.02661492,
        0.01033407, -0.03730573, -0.01364049,  0.0048901 ,  0.03775788,
       -0.0103242 , -0.01521987,  0.02547506,  0.01506581, -0.0196244 ,
        0.00375937, -0.0239806 , -0.07060147, -0.00901048, -0.00150298,
        0.04281637,  0.01918729,  0.00536773, -0.02296493,  0.02628159,
        0.03623233,  0.02236345, -0.00854473,  0.01510214, -0.00595624,
       -0.00053727,  0.00587249,  0.03341296, -0.00263091,  0.0051692 ,
       -0.0325998 ,  0.0288993 ,  0.00104196, -0.02763562, -0.00778266,
       -0.00923964, -0.02721515, -0.04960929, -0.03229785, -0.02851789,
        0.00887527,  0.02336942, -0.02034724,  0.01734822,  0.02692503,
       -0.02092778, -0.01956191, -0.01812303,  0.02749659, -0.08863764,
        0.03036672, -0.03995557, -0.03760703, -0.02335382, -0.04174392,
        0.03608634,  0.0139687 ,  0.00459125, -0.04148832,  0.00733338,
       -0.02712367, -0.02093281,  0.07616775,  0.0171588 , -0.00196343,
       -0.05671151,  0.01211582, -0.06643061, -0.03690084,  0.00486442,
        0.01375848, -0.04319622, -0.02446037,  0.0231385 ,  0.03712222,
       -0.01278398,  0.03782221,  0.03712642,  0.0004241 ,  0.0492488 ,
       -0.03377091, -0.01753201,  0.0302205 , -0.01198291,  0.00684201,
        0.03955062,  0.01474984,  0.03538432, -0.01476874, -0.02894471,
       -0.04063347, -0.01755007,  0.03432097,  0.0425001 , -0.0042981 ,
       -0.05671147,  0.04554208,  0.04016471,  0.02280781,  0.01656308,
       -0.00493632, -0.04303739,  0.04768781, -0.02518558,  0.0197935 ,
        0.00826333, -0.04183784, -0.02607515, -0.0167757 ,  0.03548589,
        0.02634257, -0.01389541, -0.03503864, -0.01067131,  0.01608767,
        0.01366803,  0.04483947, -0.10732518, -0.02421636, -0.00052577,
       -0.00918089, -0.01650044,  0.0122244 ,  0.01077022,  0.00359015,
        0.00402123, -0.03037303,  0.02538923,  0.048551  , -0.03732331,
       -0.01035147, -0.00346016, -0.04298517, -0.01237065, -0.04349045,
        0.02996342,  0.02074566,  0.03803537,  0.00378409, -0.01978628,
       -0.02468799, -0.0122047 , -0.037242  ,  0.04393184, -0.03834741,
       -0.03347021, -0.01194743, -0.05003896, -0.01036607,  0.01910304,
       -0.02703509, -0.03790927,  0.05138057,  0.03385172, -0.03471122,
        0.00936318, -0.01793597,  0.04156873, -0.02334269,  0.00123184,
       -0.00225014,  0.00978739, -0.01335182, -0.02000855, -0.02350774,
        0.02860052, -0.00341545,  0.00688724,  0.00834682, -0.00685082,
       -0.03665018, -0.01365724, -0.037566  , -0.01846776, -0.04387739,
        0.02938406,  0.00638024, -0.00906445,  0.00845713, -0.00662003,
       -0.06228723, -0.04216504,  0.03503329,  0.00377744, -0.01387323,
       -0.05753769, -0.03300621, -0.00686977,  0.00712316,  0.04577765,
       -0.0830607 ,  0.04352307,  0.00265114, -0.03617479,  0.04859022,
        0.00132372,  0.02955532, -0.00988826,  0.03836116, -0.01720994,
       -0.01880648, -0.01072117, -0.01211753,  0.04717821, -0.04582327,
        0.02189567, -0.01084925, -0.00445177, -0.01942536, -0.0092439 ,
        0.013842  ,  0.02643197, -0.00421478, -0.00969422,  0.03733156,
        0.00569932, -0.01013228, -0.01443284,  0.04272824,  0.04649645,
        0.02637454, -0.05171081,  0.02600996,  0.01158815, -0.01487783,
       -0.03401789, -0.04401715,  0.02285154, -0.00409461, -0.05434931,
       -0.01963966, -0.05182324,  0.00140261, -0.01807779,  0.03059032,
       -0.02923291,  0.0297759 ,  0.01599407, -0.02415217,  0.04283909,
        0.03976031,  0.03575721,  0.00741494, -0.01684148,  0.00809664,
        0.00677942,  0.16475567, -0.03899865, -0.00198566, -0.01775786,
       -0.05041559,  0.03523669,  0.03344247, -0.02184201,  0.00112029,
        0.01841828, -0.00026206, -0.04313817, -0.08326501,  0.00369122,
        0.0196299 ,  0.03671356, -0.02489877,  0.02800819, -0.00708354,
       -0.00180246,  0.05083505, -0.0646308 ,  0.03264534,  0.01201116,
       -0.04677432,  0.03527073, -0.0231549 ,  0.00723222, -0.04228879,
        0.02968501, -0.01438918,  0.03000344,  0.03207212, -0.02050002,
       -0.01286071, -0.04801591,  0.03860366,  0.0032018 ,  0.03442844,
        0.04111506,  0.03131347,  0.04417789,  0.05323632,  0.01254342,
       -0.01706283, -0.08989279,  0.03639055, -0.03019319,  0.03849153,
        0.00592941,  0.03473135, -0.00620836,  0.06921267, -0.02356819,
       -0.00085597,  0.02024569,  0.03078962,  0.03585801,  0.02477571,
       -0.07526913, -0.01581944, -0.00132833,  0.02793691, -0.04166964,
        0.0215426 ,  0.0365019 , -0.04249884, -0.02096742,  0.00133546,
        0.03424967,  0.05128629, -0.00483276, -0.0367578 ,  0.00577093,
        0.04337233,  0.04007225,  0.03487306, -0.02474888,  0.02525618,
        0.01742413,  0.00783103,  0.04039811, -0.01651111,  0.01380399,
        0.06367402,  0.05632859, -0.05435365,  0.00251717, -0.03522943,
        0.02113383, -0.01925712,  0.01543369, -0.06718291, -0.00495682,
        0.0470367 ,  0.047446  ,  0.04308206,  0.12681578, -0.04805055,
        0.044412  ,  0.01910778,  0.02371334, -0.03256948, -0.03619417,
        0.05388571,  0.03126308,  0.01303727, -0.02330842,  0.05720127,
       -0.04487376,  0.02770675,  0.01039223, -0.00812397, -0.00766324,
        0.05609418, -0.01055954, -0.00173097,  0.0325783 , -0.02295738,
        0.00263054,  0.02663546,  0.03357588, -0.03430415, -0.01462462,
       -0.02975668,  0.02409138,  0.02032954, -0.00941417, -0.06312279,
       -0.04719608,  0.03968394, -0.03580355, -0.02665703,  0.00468372,
       -0.0003725 ,  0.00462265, -0.05033964,  0.00393551, -0.16097714,
        0.00152492, -0.03885627,  0.01041978,  0.02357129,  0.024179  ,
        0.01113621,  0.0332066 ,  0.03458177, -0.06124498,  0.04757035,
       -0.03006715,  0.04490186,  0.01327821, -0.02585152, -0.00413142,
       -0.00174909, -0.0181556 ,  0.03414122,  0.0103868 , -0.10157748,
        0.02387045,  0.04040891, -0.04469493, -0.03317431,  0.03438227,
        0.02112266, -0.01149315, -0.08968599,  0.00828915,  0.05431185,
        0.05503315,  0.04177273, -0.01665   ,  0.0077273 ,  0.02116889,
        0.02957522,  0.02680911,  0.07317277,  0.03278402,  0.03547916,
       -0.04655121, -0.05062223, -0.01961315,  0.02572461,  0.03925693,
       -0.00889451,  0.06887936, -0.02847825,  0.02166408,  0.00034339,
       -0.01967643, -0.05007636,  0.007892  , -0.01276369, -0.03897808,
        0.00469665, -0.0047801 ,  0.03855117,  0.00117156,  0.04817576,
        0.04042793,  0.02343734, -0.01452053, -0.02678866,  0.02417002,
       -0.03229135, -0.04948917,  0.00030193,  0.00752599, -0.00745942,
       -0.020493  ,  0.05571395, -0.02006602,  0.03261312,  0.04176229,
       -0.01498887,  0.0214108 ,  0.05032142, -0.03186764,  0.04419745,
        0.05059934, -0.00510447,  0.02174778, -0.02238149,  0.0146239 ,
        0.01224576,  0.02893437, -0.0792651 , -0.02402776,  0.03835998,
        0.05283049,  0.05042522,  0.02275717,  0.04858077, -0.0228016 ,
       -0.02953656, -0.05413393, -0.0481055 , -0.03416497,  0.01772844,
       -0.05717265, -0.02170595,  0.00924498,  0.01460103,  0.00407104,
       -0.02413023,  0.00224173,  0.00039441,  0.01678072,  0.00037306,
        0.0618799 ,  0.03753294,  0.02773141, -0.02828943,  0.0147232 ,
        0.05310953,  0.03691145, -0.02610064, -0.03197954,  0.00517475,
       -0.10140068, -0.04328448,  0.06226482,  0.03152923, -0.00997398,
       -0.01577418, -0.05339001,  0.04260258, -0.00124729, -0.03202457,
       -0.01435812,  0.02734259, -0.01114987, -0.02432521, -0.04704403,
        0.01058981,  0.02363425, -0.0371696 ,  0.03293653,  0.03429403,
       -0.03163743, -0.08963741,  0.02491023,  0.01253908,  0.05416469,
        0.03910115,  0.00389056, -0.09253589, -0.0442822 ,  0.04365133,
       -0.04521344, -0.03251251,  0.02363841, -0.02246979,  0.03781858,
       -0.03086128, -0.03070093,  0.02769131, -0.02320155,  0.01553618,
       -0.04512155,  0.01987213,  0.04390752, -0.0228097 ,  0.01485583,
        0.02948244, -0.04787928, -0.06556947, -0.08857726, -0.03120065,
       -0.0212887 , -0.00094873,  0.03843797, -0.03298329, -0.05092812,
       -0.00470923, -0.07841094, -0.03716173, -0.03516696, -0.02345507,
       -0.01300988, -0.06769527, -0.00838682,  0.04188791,  0.05089671,
        0.04285439,  0.03160577, -0.00203935, -0.04048998,  0.03796125,
       -0.01134916, -0.04652375, -0.02027969,  0.09621385, -0.0369442 ,
        0.06339718, -0.0268888 , -0.03459866,  0.04849949,  0.0833995 ,
        0.0152747 ,  0.0407303 ,  0.08148029,  0.00079477, -0.0137582 ,
        0.01535333,  0.03262997,  0.04740967,  0.00740359,  0.02906503,
        0.02117035, -0.00293496,  0.01598096,  0.04892518, -0.08275555,
        0.01060989,  0.04694125, -0.0363673 , -0.03591255,  0.01202363,
       -0.03181882,  0.01860141,  0.03627916, -0.05640322, -0.0198372 ,
       -0.03282804,  0.03040469, -0.04700011,  0.03262246,  0.01709384,
        0.06387881,  0.04183479,  0.07476543, -0.00468676,  0.04083318,
       -0.0316498 ,  0.02479158,  0.0334391 , -0.01990934, -0.00992478,
        0.02454093, -0.01848109, -0.00140756,  0.00796657,  0.01357756,
       -0.03360282,  0.03785857, -0.00955704,  0.04485222,  0.017695  ,
        0.03944881,  0.01141392, -0.02086693, -0.03584647, -0.04889017,
       -0.03896943, -0.0204288 ,  0.02143296,  0.02600343,  0.124228  ,
       -0.01276396,  0.04757462, -0.04743731,  0.00870432,  0.09099612,
        0.01237975,  0.03209217,  0.04623294,  0.03155432,  0.05977214,
        0.03645177,  0.01591029,  0.00993987,  0.03346889, -0.04829758,
       -0.02386829,  0.00241648, -0.04496749,  0.03200755, -0.02460559,
        0.04369019, -0.04204682, -0.00527993,  0.03783871, -0.03034531,
        0.06972515,  0.03803995,  0.12238533,  0.00493797,  0.04089242,
       -0.02877609,  0.04337503, -0.05574691,  0.0420223 ,  0.06839791,
       -0.00393035,  0.01512186,  0.00206158, -0.01310129,  0.03300372,
       -0.03406359, -0.01074367, -0.0299081 , -0.02555576, -0.04069597,
        0.02524206,  0.0177865 , -0.0081205 ])

Under the cloudformation template 'geocore-semantic-search-with-opensearch-stage; Output tab, find the values for region, aos_host, and os_secret_id

In [37]:
from opensearchpy import OpenSearch, Urllib3AWSV4SignerAuth, Urllib3HttpConnection

host = "search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com"
region = "ca-central-1"
service = "es"

credentials = boto3.Session().get_credentials()

auth = Urllib3AWSV4SignerAuth(
    credentials,
    region,
    service
)

aos_client = OpenSearch(
    hosts=[{"host": host, "port": 443}],
    http_auth=auth,
    use_ssl=True,
    verify_certs=True,
    connection_class=Urllib3HttpConnection,
)

print(aos_client.info())

2026-09-09 18:21:14,094 - INFO - Found credentials from IAM Role: BaseNotebookInstanceEc2InstanceRole
2026-09-09 18:21:14,166 - INFO - GET https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/ [status:200 request:0.071s]
{'name': 'c5c720e62d05e7029e56c0bad3996b11', 'cluster_name': '759472643633:semantic-search', 'cluster_uuid': 'zU9eoXc_Tcy5L6s4Chcd7g', 'version': {'number': '7.10.2', 'build_type': 'tar', 'build_hash': 'unknown', 'build_date': '2025-12-02T19:15:52.128251828Z', 'build_snapshot': False, 'lucene_version': '9.12.1', 'minimum_wire_compatibility_version': '7.10.0', 'minimum_index_compatibility_version': '7.0.0'}, 'tagline': 'The OpenSearch Project: https://opensearch.org/'}

In [38]:
all_indices = aos_client.cat.indices(format='json')
existing_indices = [index['index'] for index in all_indices]
print("Current indexes:", existing_indices)

2026-09-09 18:21:16,385 - INFO - GET https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/_cat/indices?format=json [status:200 request:0.033s]
Current indexes: ['.plugins-ml-model-group', 'geolocation-index-demo', '.ql-datasources', 'minilm-knn-multilingual', '.plugins-ml-task', '.opendistro-reports-definitions', 'gte-multi-ft2', '.opendistro_security', '.opendistro-reports-instances', 'geolocation-analytics-table', 'vcs-audit-logs-v2', 'minilm-knn', 'geolocation-index-v4', '.opensearch-observability', 'nts-index', '.plugins-ml-model', 'index_name_address_range', 'gte-multi-ft-test', 'geolocation-address-range-index', 'id-audit-logs', 'minilm-pretrain-knn', 'geolocation-index-address-range', 'semantic-search-audit-logs', '.plugins-flow-framework-state', 'minilm-knn-2', 'gte-multi-ft', '.kibana_92668751_admin_1', '.plugins-ml-agent', '.kibana_92668751_admin_2', '.plugins-flow-framework-templates', '.kibana_2', 'vcs-audit-logs', '.kibana_1', '.tasks', '.plugins-ml-config', 'audit-logs-stage', 'opensearch_dashboards_sample_data_logs', 'geolocator-audit-logs', '.plugins-flow-framework-config', 'opensearch_dashboards_sample_data_flights', 'geolocation-index', 'semantic-search-canidate-audit-logs', '.opendistro-job-scheduler-lock', 'fsa-postal-code-index', 'mpnet-mpf-knn']

In [45]:
# aos_client.indices.delete(index="gte-multi-ft-test")

2026-09-10 19:24:26,450 - INFO - DELETE https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft-test [status:200 request:0.315s]

{'acknowledged': True}

In [39]:
#Create an index 
index_name = "gte-multi-ft2"
knn_index = {
    "settings": {
        "index.knn": True, #This enables the k-nearest neighbor (KNN) search capability on the index.
        "index.knn.space_type": "cosinesimil", #cosine similarity 
        "analysis": {
          "analyzer": {
            "default": {
              "type": "standard",
              "stopwords": "_english_"
            }
          }
        }
    },
    "mappings": {
        "properties": {
            "vector": {
                "type": "knn_vector",
                "dimension": 768,
                "store": True,
                "space_type": "cosinesimil" # defining it again for newer versions of Opensearch
            },
            "coordinates":{
              "type": "geo_shape", 
              "store": True 
            }  
        }
    }
}

In [51]:
# Delete index if it exists
delete_aos_index_if_exists(aos_client, index_to_delete=index_name)

2026-08-26 12:34:41,717 - INFO - GET https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/_cat/indices?format=json [status:200 request:0.026s]
Current indexes: ['.plugins-ml-model-group', 'geolocation-index-demo', '.ql-datasources', 'minilm-knn-multilingual', '.plugins-ml-task', '.opendistro-reports-definitions', '.opendistro_security', '.opendistro-reports-instances', 'geolocation-analytics-table', 'vcs-audit-logs-v2', 'minilm-knn', 'geolocation-index-v4', '.opensearch-observability', 'nts-index', '.plugins-ml-model', 'index_name_address_range', 'gte-multi-ft-test', 'geolocation-address-range-index', 'id-audit-logs', 'minilm-pretrain-knn', 'geolocation-index-address-range', 'semantic-search-audit-logs', '.plugins-flow-framework-state', 'minilm-knn-2', 'gte-multi-ft', '.kibana_92668751_admin_1', '.plugins-ml-agent', '.kibana_92668751_admin_2', '.plugins-flow-framework-templates', '.kibana_2', 'vcs-audit-logs', '.kibana_1', '.tasks', '.plugins-ml-config', 'audit-logs-stage', 'opensearch_dashboards_sample_data_logs', 'geolocator-audit-logs', '.plugins-flow-framework-config', 'opensearch_dashboards_sample_data_flights', 'geolocation-index', 'semantic-search-canidate-audit-logs', '.opendistro-job-scheduler-lock', 'fsa-postal-code-index', 'mpnet-mpf-knn']
2026-08-26 12:34:42,102 - INFO - DELETE https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft [status:200 request:0.385s]
Deleted index: gte-multi-ft
Response: {'acknowledged': True}
2026-08-26 12:34:42,126 - INFO - GET https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/_cat/indices?format=json [status:200 request:0.022s]
Indexes after deletion attempt: ['.plugins-ml-model-group', 'geolocation-index-demo', '.ql-datasources', 'minilm-knn-multilingual', '.plugins-ml-task', '.opendistro-reports-definitions', '.opendistro_security', '.opendistro-reports-instances', 'geolocation-analytics-table', 'vcs-audit-logs-v2', 'minilm-knn', 'geolocation-index-v4', '.opensearch-observability', 'nts-index', '.plugins-ml-model', 'index_name_address_range', 'gte-multi-ft-test', 'geolocation-address-range-index', 'id-audit-logs', 'minilm-pretrain-knn', 'geolocation-index-address-range', 'semantic-search-audit-logs', '.plugins-flow-framework-state', 'minilm-knn-2', '.kibana_92668751_admin_1', '.plugins-ml-agent', '.kibana_92668751_admin_2', '.plugins-flow-framework-templates', '.kibana_2', 'vcs-audit-logs', '.kibana_1', '.tasks', '.plugins-ml-config', 'audit-logs-stage', 'opensearch_dashboards_sample_data_logs', 'geolocator-audit-logs', '.plugins-flow-framework-config', 'opensearch_dashboards_sample_data_flights', 'geolocation-index', 'semantic-search-canidate-audit-logs', '.opendistro-job-scheduler-lock', 'fsa-postal-code-index', 'mpnet-mpf-knn']

In [29]:
#Create a index 
aos_client.indices.create(index=index_name,body=knn_index,ignore=400)

2026-09-09 15:50:50,430 - INFO - PUT https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2 [status:200 request:0.816s]

{'acknowledged': True, 'shards_acknowledged': True, 'index': 'gte-multi-ft2'}

In [40]:
#Load data to OpenSearch Index 
load_data_to_opensearch_index(df, aos_client, index_name)

vector has null values: False

Indexing Records:   0%|          | 0/22132 [00:00<?, ?it/s]

2026-09-09 18:21:46,305 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.445s]

Indexing Records:   0%|          | 1/22132 [00:00<2:44:53,  2.24it/s]

2026-09-09 18:21:46,500 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.192s]

Indexing Records:   0%|          | 2/22132 [00:00<1:50:08,  3.35it/s]

2026-09-09 18:21:46,559 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.057s]
2026-09-09 18:21:46,608 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.047s]

Indexing Records:   0%|          | 4/22132 [00:00<53:28,  6.90it/s]

2026-09-09 18:21:46,659 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.050s]
2026-09-09 18:21:46,708 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.047s]

Indexing Records:   0%|          | 6/22132 [00:00<36:55,  9.99it/s]

2026-09-09 18:21:46,753 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.043s]
2026-09-09 18:21:46,801 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.047s]
2026-09-09 18:21:46,840 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.038s]

Indexing Records:   0%|          | 9/22132 [00:00<26:33, 13.89it/s]

2026-09-09 18:21:46,888 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.046s]
2026-09-09 18:21:46,935 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.046s]
2026-09-09 18:21:46,983 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.047s]

Indexing Records:   0%|          | 12/22132 [00:01<22:47, 16.18it/s]

2026-09-09 18:21:47,033 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.048s]
2026-09-09 18:21:47,082 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.047s]
2026-09-09 18:21:47,122 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.039s]

Indexing Records:   0%|          | 15/22132 [00:01<20:39, 17.84it/s]

2026-09-09 18:21:47,175 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.051s]
2026-09-09 18:21:47,213 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.037s]
2026-09-09 18:21:47,257 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.043s]

Indexing Records:   0%|          | 18/22132 [00:01<19:14, 19.16it/s]

2026-09-09 18:21:47,305 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.045s]
2026-09-09 18:21:47,355 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.049s]
2026-09-09 18:21:47,393 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.037s]

Indexing Records:   0%|          | 21/22132 [00:01<18:22, 20.05it/s]

2026-09-09 18:21:47,434 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.039s]
2026-09-09 18:21:47,474 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.038s]
2026-09-09 18:21:47,516 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.041s]

Indexing Records:   0%|          | 24/22132 [00:01<17:20, 21.25it/s]

2026-09-09 18:21:47,552 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]
2026-09-09 18:21:47,592 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.038s]
2026-09-09 18:21:47,641 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.046s]

Indexing Records:   0%|          | 27/22132 [00:01<16:41, 22.08it/s]

2026-09-09 18:21:47,679 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.036s]
2026-09-09 18:21:47,721 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.041s]
2026-09-09 18:21:47,755 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]

Indexing Records:   0%|          | 30/22132 [00:01<15:51, 23.22it/s]

2026-09-09 18:21:47,797 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.039s]
2026-09-09 18:21:47,836 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.038s]
2026-09-09 18:21:47,876 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.038s]

Indexing Records:   0%|          | 33/22132 [00:02<15:31, 23.72it/s]

2026-09-09 18:21:47,913 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]
2026-09-09 18:21:47,952 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.038s]
2026-09-09 18:21:47,984 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]

Indexing Records:   0%|          | 36/22132 [00:02<14:51, 24.78it/s]

2026-09-09 18:21:48,021 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]
2026-09-09 18:21:48,058 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.036s]
2026-09-09 18:21:48,089 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]

Indexing Records:   0%|          | 39/22132 [00:02<14:14, 25.84it/s]

2026-09-09 18:21:48,125 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]
2026-09-09 18:21:48,155 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:21:48,187 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:21:48,219 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]

Indexing Records:   0%|          | 43/22132 [00:02<13:24, 27.47it/s]

2026-09-09 18:21:48,251 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:21:48,281 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:21:48,315 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:21:48,347 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]

Indexing Records:   0%|          | 47/22132 [00:02<12:51, 28.64it/s]

2026-09-09 18:21:48,382 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]
2026-09-09 18:21:48,417 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]
2026-09-09 18:21:48,452 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]

Indexing Records:   0%|          | 50/22132 [00:02<12:51, 28.64it/s]

2026-09-09 18:21:48,485 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:21:48,529 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.042s]
2026-09-09 18:21:48,576 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.046s]

Indexing Records:   0%|          | 53/22132 [00:02<13:32, 27.19it/s]

2026-09-09 18:21:48,619 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.040s]
2026-09-09 18:21:48,661 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.041s]
2026-09-09 18:21:48,698 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]

Indexing Records:   0%|          | 56/22132 [00:02<13:54, 26.47it/s]

2026-09-09 18:21:48,745 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.045s]
2026-09-09 18:21:48,781 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]
2026-09-09 18:21:48,814 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]

Indexing Records:   0%|          | 59/22132 [00:02<14:00, 26.26it/s]

2026-09-09 18:21:48,850 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]
2026-09-09 18:21:48,900 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.048s]
2026-09-09 18:21:48,958 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.057s]

Indexing Records:   0%|          | 62/22132 [00:03<15:03, 24.42it/s]

2026-09-09 18:21:49,005 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.044s]
2026-09-09 18:21:49,039 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:21:49,065 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:   0%|          | 65/22132 [00:03<14:30, 25.34it/s]

2026-09-09 18:21:49,096 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:21:49,123 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:21:49,155 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:21:49,187 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]

Indexing Records:   0%|          | 69/22132 [00:03<13:18, 27.62it/s]

2026-09-09 18:21:49,217 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:21:49,246 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:21:49,278 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:21:49,310 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]

Indexing Records:   0%|          | 73/22132 [00:03<12:39, 29.05it/s]

2026-09-09 18:21:49,342 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:21:49,370 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:21:49,397 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:21:49,424 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]

Indexing Records:   0%|          | 77/22132 [00:03<11:54, 30.85it/s]

2026-09-09 18:21:49,460 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]
2026-09-09 18:21:49,487 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:21:49,512 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:21:49,540 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]

Indexing Records:   0%|          | 81/22132 [00:03<11:31, 31.88it/s]

2026-09-09 18:21:49,566 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:21:49,595 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:21:49,622 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:21:49,648 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:   0%|          | 85/22132 [00:03<11:00, 33.36it/s]

2026-09-09 18:21:49,690 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.040s]
2026-09-09 18:21:49,721 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:21:49,746 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:21:49,776 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]

Indexing Records:   0%|          | 89/22132 [00:03<11:14, 32.68it/s]

2026-09-09 18:21:49,809 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:21:49,839 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:21:49,865 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:21:49,892 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]

Indexing Records:   0%|          | 93/22132 [00:04<11:03, 33.23it/s]

2026-09-09 18:21:49,926 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:21:49,963 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.036s]
2026-09-09 18:21:49,992 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:21:50,031 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.038s]

Indexing Records:   0%|          | 97/22132 [00:04<11:34, 31.74it/s]

2026-09-09 18:21:50,059 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:21:50,086 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:21:50,114 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:21:50,151 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]

Indexing Records:   0%|          | 101/22132 [00:04<11:24, 32.20it/s]

2026-09-09 18:21:50,187 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]
2026-09-09 18:21:50,220 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:21:50,251 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:21:50,279 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]

Indexing Records:   0%|          | 105/22132 [00:04<11:31, 31.87it/s]

2026-09-09 18:21:50,307 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:21:50,335 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:21:50,371 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]
2026-09-09 18:21:50,396 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:   0%|          | 109/22132 [00:04<11:16, 32.55it/s]

2026-09-09 18:21:50,427 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:21:50,468 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.039s]
2026-09-09 18:21:50,501 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:21:50,532 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]

Indexing Records:   1%|          | 113/22132 [00:04<11:38, 31.52it/s]

2026-09-09 18:21:50,573 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.038s]
2026-09-09 18:21:50,600 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:21:50,631 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:21:50,662 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]

Indexing Records:   1%|          | 117/22132 [00:04<11:42, 31.34it/s]

2026-09-09 18:21:50,697 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]
2026-09-09 18:21:50,729 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:21:50,758 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:21:50,788 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]

Indexing Records:   1%|          | 121/22132 [00:04<11:41, 31.40it/s]

2026-09-09 18:21:50,816 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:21:50,854 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.037s]
2026-09-09 18:21:50,884 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:21:50,915 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]

Indexing Records:   1%|          | 125/22132 [00:05<11:39, 31.46it/s]

2026-09-09 18:21:50,942 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:21:50,970 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:21:51,000 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:21:51,055 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.053s]

Indexing Records:   1%|          | 129/22132 [00:05<12:00, 30.55it/s]

2026-09-09 18:21:51,080 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:21:51,104 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:21:51,129 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:21:51,154 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:21:51,179 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:   1%|          | 134/22132 [00:05<10:59, 33.35it/s]

2026-09-09 18:21:51,207 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:21:51,233 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:21:51,255 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:51,284 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]

Indexing Records:   1%|          | 138/22132 [00:05<10:35, 34.63it/s]

2026-09-09 18:21:51,309 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:21:51,335 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:21:51,360 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:21:51,383 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:51,406 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:   1%|          | 143/22132 [00:05<10:02, 36.50it/s]

2026-09-09 18:21:51,430 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:21:51,458 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:21:51,483 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:21:51,505 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:51,530 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:   1%|          | 148/22132 [00:05<09:43, 37.65it/s]

2026-09-09 18:21:51,557 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:21:51,582 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:21:51,606 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:21:51,635 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]

Indexing Records:   1%|          | 152/22132 [00:05<09:41, 37.81it/s]

2026-09-09 18:21:51,658 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:51,681 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:51,706 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:21:51,729 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:21:51,751 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:   1%|          | 157/22132 [00:05<09:17, 39.40it/s]

2026-09-09 18:21:51,777 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:21:51,801 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:21:51,823 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:51,846 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:51,870 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:   1%|          | 162/22132 [00:06<09:06, 40.18it/s]

2026-09-09 18:21:51,895 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:21:51,920 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:21:51,945 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:21:51,972 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:21:51,995 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:   1%|          | 167/22132 [00:06<09:07, 40.15it/s]

2026-09-09 18:21:52,018 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:52,053 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]
2026-09-09 18:21:52,076 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:52,099 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:52,123 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:   1%|          | 172/22132 [00:06<09:11, 39.80it/s]

2026-09-09 18:21:52,145 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:52,181 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]
2026-09-09 18:21:52,202 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:52,223 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:   1%|          | 176/22132 [00:06<09:11, 39.80it/s]

2026-09-09 18:21:52,247 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:21:52,268 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:52,289 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:52,311 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:52,333 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:   1%|          | 181/22132 [00:06<08:50, 41.38it/s]

2026-09-09 18:21:52,356 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:52,379 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:52,403 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:21:52,427 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:21:52,453 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:   1%|          | 186/22132 [00:06<08:48, 41.52it/s]

2026-09-09 18:21:52,476 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:52,500 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:21:52,524 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:21:52,547 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:52,568 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:   1%|          | 191/22132 [00:06<08:40, 42.15it/s]

2026-09-09 18:21:52,592 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:21:52,616 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:21:52,638 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:52,662 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:21:52,682 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:   1%|          | 196/22132 [00:06<08:34, 42.62it/s]

2026-09-09 18:21:52,706 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:52,727 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:52,747 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:52,769 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:52,788 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:   1%|          | 201/22132 [00:06<08:18, 43.96it/s]

2026-09-09 18:21:52,810 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:52,832 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:52,870 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.037s]
2026-09-09 18:21:52,892 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:52,915 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:   1%|          | 206/22132 [00:07<08:36, 42.45it/s]

2026-09-09 18:21:52,937 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:52,965 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:21:52,986 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:53,008 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:53,028 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:   1%|          | 211/22132 [00:07<08:30, 42.96it/s]

2026-09-09 18:21:53,049 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:53,072 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:21:53,093 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:53,115 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:53,139 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:   1%|          | 216/22132 [00:07<08:23, 43.51it/s]

2026-09-09 18:21:53,163 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:53,182 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:21:53,204 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:53,223 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:21:53,242 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:   1%|          | 221/22132 [00:07<08:07, 44.90it/s]

2026-09-09 18:21:53,264 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:53,284 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:53,304 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:53,327 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:53,347 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:   1%|          | 226/22132 [00:07<07:58, 45.74it/s]

2026-09-09 18:21:53,369 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:53,390 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:53,412 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:53,433 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:53,454 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:   1%|          | 231/22132 [00:07<07:55, 46.01it/s]

2026-09-09 18:21:53,480 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:21:53,501 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:53,521 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:53,542 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:53,564 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:   1%|          | 236/22132 [00:07<07:57, 45.90it/s]

2026-09-09 18:21:53,584 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:53,605 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:53,628 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:21:53,651 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:53,671 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:   1%|          | 241/22132 [00:07<07:55, 46.08it/s]

2026-09-09 18:21:53,695 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:53,715 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:53,735 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:53,758 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:21:53,779 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:   1%|          | 246/22132 [00:07<07:53, 46.18it/s]

2026-09-09 18:21:53,802 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:53,825 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:53,848 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:21:53,878 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:21:53,907 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]

Indexing Records:   1%|          | 251/22132 [00:08<08:19, 43.82it/s]

2026-09-09 18:21:53,929 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:53,951 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:53,972 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:53,992 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:21:54,011 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:   1%|          | 256/22132 [00:08<08:07, 44.92it/s]

2026-09-09 18:21:54,032 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:54,052 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:54,076 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:21:54,099 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:54,119 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:   1%|          | 261/22132 [00:08<08:02, 45.32it/s]

2026-09-09 18:21:54,146 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:21:54,169 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:54,190 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:54,211 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:54,231 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:   1%|          | 266/22132 [00:08<08:03, 45.20it/s]

2026-09-09 18:21:54,252 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:54,273 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:54,297 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:21:54,319 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:54,341 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:   1%|          | 271/22132 [00:08<08:03, 45.17it/s]

2026-09-09 18:21:54,364 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:54,384 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:54,405 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:54,424 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:21:54,451 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]

Indexing Records:   1%|          | 276/22132 [00:08<08:01, 45.39it/s]

2026-09-09 18:21:54,475 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:21:54,501 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:21:54,523 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:54,545 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:54,566 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:   1%|▏         | 281/22132 [00:08<08:08, 44.74it/s]

2026-09-09 18:21:54,587 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:54,607 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:54,635 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:21:54,657 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:54,677 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:   1%|▏         | 286/22132 [00:08<08:07, 44.79it/s]

2026-09-09 18:21:54,699 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:54,719 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:54,743 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:21:54,766 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:54,786 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:   1%|▏         | 291/22132 [00:08<08:03, 45.14it/s]

2026-09-09 18:21:54,807 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:54,830 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:54,855 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:21:54,876 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:54,905 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]

Indexing Records:   1%|▏         | 296/22132 [00:09<08:14, 44.18it/s]

2026-09-09 18:21:54,932 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:21:54,960 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:21:54,982 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:55,005 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:55,032 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]

Indexing Records:   1%|▏         | 301/22132 [00:09<08:31, 42.66it/s]

2026-09-09 18:21:55,078 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.044s]
2026-09-09 18:21:55,105 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:21:55,125 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:55,146 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:55,167 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:   1%|▏         | 306/22132 [00:09<08:54, 40.80it/s]

2026-09-09 18:21:55,191 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:21:55,213 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:55,238 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:21:55,260 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:55,285 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:   1%|▏         | 311/22132 [00:09<08:48, 41.27it/s]

2026-09-09 18:21:55,309 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:21:55,332 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:55,353 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:55,374 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:55,398 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:   1%|▏         | 316/22132 [00:09<08:38, 42.09it/s]

2026-09-09 18:21:55,421 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:55,443 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:55,464 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:55,491 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:21:55,516 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:   1%|▏         | 321/22132 [00:09<08:36, 42.20it/s]

2026-09-09 18:21:55,538 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:55,561 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:55,581 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:55,604 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:55,624 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:   1%|▏         | 326/22132 [00:09<08:23, 43.31it/s]

2026-09-09 18:21:55,645 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:55,667 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:55,687 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:55,708 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:55,729 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:   1%|▏         | 331/22132 [00:09<08:09, 44.56it/s]

2026-09-09 18:21:55,751 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:55,775 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:21:55,795 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:55,818 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:21:55,842 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:   2%|▏         | 336/22132 [00:09<08:10, 44.46it/s]

2026-09-09 18:21:55,863 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:55,885 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:55,906 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:55,928 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:55,950 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:   2%|▏         | 341/22132 [00:10<08:04, 44.97it/s]

2026-09-09 18:21:55,972 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:55,995 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:21:56,017 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:56,038 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:56,059 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:   2%|▏         | 346/22132 [00:10<08:01, 45.23it/s]

2026-09-09 18:21:56,082 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:56,106 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:21:56,128 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:56,160 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:21:56,187 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]

Indexing Records:   2%|▏         | 351/22132 [00:10<08:24, 43.20it/s]

2026-09-09 18:21:56,220 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:21:56,241 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:56,261 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:56,282 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:56,303 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:   2%|▏         | 356/22132 [00:10<08:25, 43.09it/s]

2026-09-09 18:21:56,326 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:56,357 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:21:56,382 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:21:56,401 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:56,421 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:   2%|▏         | 361/22132 [00:10<08:27, 42.88it/s]

2026-09-09 18:21:56,444 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:56,465 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:56,493 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:21:56,515 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:56,537 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:   2%|▏         | 366/22132 [00:10<08:26, 42.97it/s]

2026-09-09 18:21:56,559 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:56,580 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:56,603 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:56,625 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:56,647 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:   2%|▏         | 371/22132 [00:10<08:17, 43.73it/s]

2026-09-09 18:21:56,669 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:56,689 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:56,711 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:56,742 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:21:56,763 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:   2%|▏         | 376/22132 [00:10<08:19, 43.58it/s]

2026-09-09 18:21:56,786 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:56,807 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:56,829 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:56,851 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:56,873 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:   2%|▏         | 381/22132 [00:11<08:13, 44.03it/s]

2026-09-09 18:21:56,895 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:56,916 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:56,939 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:56,962 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:56,982 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:   2%|▏         | 386/22132 [00:11<08:07, 44.56it/s]

2026-09-09 18:21:57,007 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:21:57,041 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]
2026-09-09 18:21:57,064 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:57,086 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:57,106 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:   2%|▏         | 391/22132 [00:11<08:22, 43.24it/s]

2026-09-09 18:21:57,129 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:57,151 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:57,171 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:57,191 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:57,213 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:   2%|▏         | 396/22132 [00:11<08:11, 44.20it/s]

2026-09-09 18:21:57,236 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:57,258 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:57,280 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:57,300 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:57,321 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:   2%|▏         | 401/22132 [00:11<08:04, 44.86it/s]

2026-09-09 18:21:57,350 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:21:57,370 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:21:57,389 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:21:57,410 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:57,431 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:   2%|▏         | 406/22132 [00:11<08:02, 45.05it/s]

2026-09-09 18:21:57,456 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:21:57,476 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:57,497 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:57,521 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:21:57,543 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:   2%|▏         | 411/22132 [00:11<08:04, 44.84it/s]

2026-09-09 18:21:57,564 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:57,587 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:57,608 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:57,629 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:57,651 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:   2%|▏         | 416/22132 [00:11<07:58, 45.35it/s]

2026-09-09 18:21:57,672 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:57,693 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:57,713 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:57,735 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:57,761 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:   2%|▏         | 421/22132 [00:11<07:58, 45.42it/s]

2026-09-09 18:21:57,784 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:21:57,807 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:57,829 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:57,850 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:57,870 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:   2%|▏         | 426/22132 [00:12<07:56, 45.52it/s]

2026-09-09 18:21:57,890 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:21:57,910 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:21:57,935 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:21:57,958 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:57,978 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:   2%|▏         | 431/22132 [00:12<07:54, 45.78it/s]

2026-09-09 18:21:58,000 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:58,028 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:21:58,048 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:58,068 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:58,088 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:   2%|▏         | 436/22132 [00:12<07:55, 45.66it/s]

2026-09-09 18:21:58,109 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:58,132 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:58,157 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:21:58,183 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:21:58,204 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:   2%|▏         | 441/22132 [00:12<08:03, 44.84it/s]

2026-09-09 18:21:58,226 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:58,248 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:58,270 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:58,295 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:21:58,314 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:   2%|▏         | 446/22132 [00:12<08:01, 45.02it/s]

2026-09-09 18:21:58,338 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:21:58,359 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:58,380 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:58,403 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:58,425 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:   2%|▏         | 451/22132 [00:12<08:01, 45.00it/s]

2026-09-09 18:21:58,448 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:58,467 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:21:58,489 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:58,509 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:21:58,531 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:   2%|▏         | 456/22132 [00:12<07:54, 45.69it/s]

2026-09-09 18:21:58,554 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:58,576 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:58,598 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:58,626 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:21:58,647 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:   2%|▏         | 461/22132 [00:12<08:03, 44.78it/s]

2026-09-09 18:21:58,674 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:21:58,699 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:21:58,722 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:58,743 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:58,768 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:   2%|▏         | 466/22132 [00:12<08:14, 43.80it/s]

2026-09-09 18:21:58,789 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:58,810 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:58,830 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:58,851 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:58,873 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:   2%|▏         | 471/22132 [00:13<08:03, 44.84it/s]

2026-09-09 18:21:58,894 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:21:58,915 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:58,936 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:58,957 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:58,977 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:   2%|▏         | 476/22132 [00:13<07:53, 45.74it/s]

2026-09-09 18:21:58,997 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:21:59,018 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:59,041 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:21:59,062 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:59,083 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:   2%|▏         | 481/22132 [00:13<07:49, 46.14it/s]

2026-09-09 18:21:59,105 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:59,125 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:21:59,146 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:21:59,167 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:59,187 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:   2%|▏         | 486/22132 [00:13<07:42, 46.78it/s]

2026-09-09 18:21:59,207 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:21:59,228 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:59,246 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:21:59,267 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:59,288 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:   2%|▏         | 491/22132 [00:13<07:35, 47.48it/s]

2026-09-09 18:21:59,309 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:59,331 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:59,351 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:59,370 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:21:59,391 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:   2%|▏         | 496/22132 [00:13<07:31, 47.88it/s]

2026-09-09 18:21:59,416 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:21:59,438 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:59,459 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:59,481 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:59,503 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:   2%|▏         | 501/22132 [00:13<07:42, 46.82it/s]

2026-09-09 18:21:59,524 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:59,553 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:21:59,575 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:59,594 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:21:59,617 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:   2%|▏         | 506/22132 [00:13<07:51, 45.84it/s]

2026-09-09 18:21:59,643 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:21:59,665 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:59,684 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:21:59,704 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:59,724 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:   2%|▏         | 511/22132 [00:13<07:48, 46.13it/s]

2026-09-09 18:21:59,747 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:59,768 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:59,788 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:21:59,808 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:59,828 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:   2%|▏         | 516/22132 [00:13<07:42, 46.77it/s]

2026-09-09 18:21:59,851 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:21:59,872 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:59,893 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:59,914 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:21:59,935 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:   2%|▏         | 521/22132 [00:14<07:42, 46.71it/s]

2026-09-09 18:21:59,956 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:21:59,993 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]
2026-09-09 18:22:00,139 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.144s]
2026-09-09 18:22:00,169 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:22:00,201 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]

Indexing Records:   2%|▏         | 526/22132 [00:14<11:08, 32.31it/s]

2026-09-09 18:22:00,226 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:22:00,263 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]
2026-09-09 18:22:00,290 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:22:00,332 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.040s]

Indexing Records:   2%|▏         | 530/22132 [00:14<11:18, 31.85it/s]

2026-09-09 18:22:00,355 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:00,383 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:22:00,402 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:00,423 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:00,445 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:   2%|▏         | 535/22132 [00:14<10:19, 34.88it/s]

2026-09-09 18:22:00,467 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:00,488 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:00,508 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:00,528 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:00,548 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:   2%|▏         | 540/22132 [00:14<09:24, 38.22it/s]

2026-09-09 18:22:00,572 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:00,596 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:00,615 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:00,637 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:00,657 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:   2%|▏         | 545/22132 [00:14<08:55, 40.28it/s]

2026-09-09 18:22:00,677 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:00,700 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:00,720 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:00,745 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:22:00,765 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:   2%|▏         | 550/22132 [00:14<08:34, 41.97it/s]

2026-09-09 18:22:00,790 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:22:00,810 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:00,830 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:00,850 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:00,869 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:   3%|▎         | 555/22132 [00:15<08:15, 43.56it/s]

2026-09-09 18:22:00,892 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:00,913 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:00,935 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:00,955 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:00,975 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:   3%|▎         | 560/22132 [00:15<08:03, 44.65it/s]

2026-09-09 18:22:00,998 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:01,021 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:01,052 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:22:01,077 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:22:01,113 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]

Indexing Records:   3%|▎         | 565/22132 [00:15<08:36, 41.74it/s]

2026-09-09 18:22:01,139 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:22:01,183 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.043s]
2026-09-09 18:22:01,243 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.058s]
2026-09-09 18:22:01,371 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.127s]
2026-09-09 18:22:01,462 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.089s]

Indexing Records:   3%|▎         | 570/22132 [00:15<13:34, 26.49it/s]

2026-09-09 18:22:01,690 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.226s]
2026-09-09 18:22:01,989 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.297s]
2026-09-09 18:22:02,157 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.166s]
2026-09-09 18:22:02,253 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.095s]

Indexing Records:   3%|▎         | 574/22132 [00:16<28:18, 12.70it/s]

2026-09-09 18:22:02,346 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.090s]
2026-09-09 18:22:02,448 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.100s]
2026-09-09 18:22:02,582 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.132s]

Indexing Records:   3%|▎         | 577/22132 [00:16<30:40, 11.71it/s]

2026-09-09 18:22:02,648 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.064s]
2026-09-09 18:22:02,746 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.096s]
2026-09-09 18:22:02,860 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.113s]

Indexing Records:   3%|▎         | 580/22132 [00:17<31:17, 11.48it/s]

2026-09-09 18:22:02,938 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.075s]
2026-09-09 18:22:03,014 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.074s]

Indexing Records:   3%|▎         | 582/22132 [00:17<30:36, 11.73it/s]

2026-09-09 18:22:03,088 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.072s]
2026-09-09 18:22:03,180 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.090s]

Indexing Records:   3%|▎         | 584/22132 [00:17<30:27, 11.79it/s]

2026-09-09 18:22:03,320 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.137s]
2026-09-09 18:22:03,388 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.066s]

Indexing Records:   3%|▎         | 586/22132 [00:17<32:00, 11.22it/s]

2026-09-09 18:22:03,445 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.055s]
2026-09-09 18:22:03,492 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.045s]

Indexing Records:   3%|▎         | 588/22132 [00:17<28:42, 12.50it/s]

2026-09-09 18:22:03,534 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.040s]
2026-09-09 18:22:03,571 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]
2026-09-09 18:22:03,608 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.036s]

Indexing Records:   3%|▎         | 591/22132 [00:17<23:36, 15.21it/s]

2026-09-09 18:22:03,682 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.072s]
2026-09-09 18:22:03,719 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]

Indexing Records:   3%|▎         | 593/22132 [00:17<22:41, 15.82it/s]

2026-09-09 18:22:03,741 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:03,779 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.037s]
2026-09-09 18:22:03,804 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:22:03,840 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]

Indexing Records:   3%|▎         | 597/22132 [00:17<17:47, 20.17it/s]

2026-09-09 18:22:03,864 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:03,902 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.037s]
2026-09-09 18:22:03,935 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:22:03,974 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.037s]

Indexing Records:   3%|▎         | 601/22132 [00:18<15:38, 22.94it/s]

2026-09-09 18:22:04,335 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.359s]
2026-09-09 18:22:04,390 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.054s]
2026-09-09 18:22:04,420 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]

Indexing Records:   3%|▎         | 604/22132 [00:18<26:21, 13.61it/s]

2026-09-09 18:22:04,487 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.065s]
2026-09-09 18:22:04,539 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.051s]

Indexing Records:   3%|▎         | 606/22132 [00:18<25:19, 14.17it/s]

2026-09-09 18:22:04,575 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]
2026-09-09 18:22:04,602 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:22:04,631 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:22:04,664 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]

Indexing Records:   3%|▎         | 610/22132 [00:18<19:57, 17.97it/s]

2026-09-09 18:22:04,694 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:22:04,726 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:22:04,751 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:22:04,791 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.039s]

Indexing Records:   3%|▎         | 614/22132 [00:18<16:56, 21.17it/s]

2026-09-09 18:22:04,826 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]
2026-09-09 18:22:04,855 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:22:04,904 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.048s]

Indexing Records:   3%|▎         | 617/22132 [00:19<15:59, 22.41it/s]

2026-09-09 18:22:04,933 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:22:05,002 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.068s]
2026-09-09 18:22:05,031 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]

Indexing Records:   3%|▎         | 620/22132 [00:19<15:47, 22.70it/s]

2026-09-09 18:22:05,058 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:22:05,081 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:05,111 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:22:05,134 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:   3%|▎         | 624/22132 [00:19<13:29, 26.58it/s]

2026-09-09 18:22:05,162 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:22:05,208 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.045s]
2026-09-09 18:22:05,286 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.076s]

Indexing Records:   3%|▎         | 627/22132 [00:19<14:45, 24.29it/s]

2026-09-09 18:22:05,326 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.038s]
2026-09-09 18:22:05,359 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:22:05,399 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.039s]

Indexing Records:   3%|▎         | 630/22132 [00:19<14:25, 24.86it/s]

2026-09-09 18:22:05,430 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:22:05,458 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:22:05,490 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:22:05,510 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:   3%|▎         | 634/22132 [00:19<12:51, 27.86it/s]

2026-09-09 18:22:05,550 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.038s]
2026-09-09 18:22:05,598 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.046s]
2026-09-09 18:22:05,641 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.042s]

Indexing Records:   3%|▎         | 637/22132 [00:19<13:37, 26.31it/s]

2026-09-09 18:22:05,672 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:22:05,712 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.038s]
2026-09-09 18:22:05,763 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.050s]

Indexing Records:   3%|▎         | 640/22132 [00:19<13:53, 25.80it/s]

2026-09-09 18:22:05,801 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.036s]
2026-09-09 18:22:05,835 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:22:05,863 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:22:05,897 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]

Indexing Records:   3%|▎         | 644/22132 [00:20<13:12, 27.10it/s]

2026-09-09 18:22:05,929 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:22:05,966 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.036s]
2026-09-09 18:22:06,010 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.042s]

Indexing Records:   3%|▎         | 647/22132 [00:20<13:16, 26.99it/s]

2026-09-09 18:22:06,050 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.037s]
2026-09-09 18:22:06,078 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:22:06,106 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:22:06,135 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]

Indexing Records:   3%|▎         | 651/22132 [00:20<12:33, 28.50it/s]

2026-09-09 18:22:06,170 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]
2026-09-09 18:22:06,199 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:22:06,231 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:22:06,256 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:   3%|▎         | 655/22132 [00:20<12:00, 29.82it/s]

2026-09-09 18:22:06,296 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.037s]
2026-09-09 18:22:06,322 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:22:06,347 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:22:06,371 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:   3%|▎         | 659/22132 [00:20<11:27, 31.25it/s]

2026-09-09 18:22:06,395 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:06,420 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:22:06,454 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:22:06,478 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:   3%|▎         | 663/22132 [00:20<10:52, 32.92it/s]

2026-09-09 18:22:06,510 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:22:06,551 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.040s]
2026-09-09 18:22:06,582 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:22:06,625 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.042s]

Indexing Records:   3%|▎         | 667/22132 [00:20<11:34, 30.93it/s]

2026-09-09 18:22:06,662 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]
2026-09-09 18:22:06,691 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:22:06,719 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:22:06,751 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]

Indexing Records:   3%|▎         | 671/22132 [00:20<11:29, 31.13it/s]

2026-09-09 18:22:06,781 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:22:06,811 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:22:06,837 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:22:06,864 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]

Indexing Records:   3%|▎         | 675/22132 [00:21<11:02, 32.40it/s]

2026-09-09 18:22:06,894 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:22:06,927 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:22:06,960 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:22:06,989 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]

Indexing Records:   3%|▎         | 679/22132 [00:21<11:05, 32.24it/s]

2026-09-09 18:22:07,019 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:22:07,052 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:22:07,095 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.041s]
2026-09-09 18:22:07,132 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.036s]

Indexing Records:   3%|▎         | 683/22132 [00:21<11:36, 30.81it/s]

2026-09-09 18:22:07,160 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:22:07,203 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.041s]
2026-09-09 18:22:07,233 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:22:07,268 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]

Indexing Records:   3%|▎         | 687/22132 [00:21<11:44, 30.43it/s]

2026-09-09 18:22:07,305 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.036s]
2026-09-09 18:22:07,339 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:22:07,370 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:22:07,402 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]

Indexing Records:   3%|▎         | 691/22132 [00:21<11:49, 30.23it/s]

2026-09-09 18:22:07,434 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:22:07,454 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:07,483 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:22:07,508 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:   3%|▎         | 695/22132 [00:21<11:06, 32.18it/s]

2026-09-09 18:22:07,543 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]
2026-09-09 18:22:07,571 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:22:07,606 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]
2026-09-09 18:22:07,650 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.043s]

Indexing Records:   3%|▎         | 699/22132 [00:21<11:35, 30.80it/s]

2026-09-09 18:22:07,675 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:22:07,705 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:22:07,730 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:22:07,758 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]

Indexing Records:   3%|▎         | 703/22132 [00:21<11:00, 32.44it/s]

2026-09-09 18:22:07,806 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.046s]
2026-09-09 18:22:07,828 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:07,873 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.043s]
2026-09-09 18:22:07,905 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]

Indexing Records:   3%|▎         | 707/22132 [00:22<11:38, 30.69it/s]

2026-09-09 18:22:07,940 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]
2026-09-09 18:22:07,971 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:22:08,003 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:22:08,030 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]

Indexing Records:   3%|▎         | 711/22132 [00:22<11:28, 31.09it/s]

2026-09-09 18:22:08,056 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:22:08,082 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:22:08,110 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:22:08,131 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:   3%|▎         | 715/22132 [00:22<10:44, 33.23it/s]

2026-09-09 18:22:08,152 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:08,176 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:08,196 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:08,220 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:08,242 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:   3%|▎         | 720/22132 [00:22<09:45, 36.57it/s]

2026-09-09 18:22:08,266 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:08,297 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:22:08,329 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:22:08,354 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:   3%|▎         | 724/22132 [00:22<09:49, 36.32it/s]

2026-09-09 18:22:08,376 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:08,397 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:08,421 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:08,448 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:22:08,482 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]

Indexing Records:   3%|▎         | 729/22132 [00:22<09:36, 37.14it/s]

2026-09-09 18:22:08,505 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:08,528 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:08,555 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:22:08,577 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:08,601 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:   3%|▎         | 734/22132 [00:22<09:13, 38.66it/s]

2026-09-09 18:22:08,621 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:08,642 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:08,663 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:08,689 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:22:08,711 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:   3%|▎         | 739/22132 [00:22<08:47, 40.53it/s]

2026-09-09 18:22:08,736 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:22:08,760 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:08,780 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:08,800 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:08,822 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:   3%|▎         | 744/22132 [00:22<08:30, 41.93it/s]

2026-09-09 18:22:08,844 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:08,868 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:08,890 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:08,927 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.036s]
2026-09-09 18:22:08,952 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:   3%|▎         | 749/22132 [00:23<08:44, 40.74it/s]

2026-09-09 18:22:08,977 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:22:09,006 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:22:09,036 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:22:09,056 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:09,077 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:   3%|▎         | 754/22132 [00:23<08:47, 40.50it/s]

2026-09-09 18:22:09,100 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:09,123 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:09,143 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:09,166 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:09,187 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:   3%|▎         | 759/22132 [00:23<08:29, 41.95it/s]

2026-09-09 18:22:09,211 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:09,232 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:09,254 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:09,274 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:09,295 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:   3%|▎         | 764/22132 [00:23<08:15, 43.10it/s]

2026-09-09 18:22:09,317 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:09,338 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:09,356 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:09,386 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:22:09,408 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:   3%|▎         | 769/22132 [00:23<08:11, 43.44it/s]

2026-09-09 18:22:09,431 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:09,452 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:09,474 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:09,495 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:09,516 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:   3%|▎         | 774/22132 [00:23<08:01, 44.33it/s]

2026-09-09 18:22:09,537 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:09,557 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:09,577 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:09,596 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:09,615 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:09,637 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:   4%|▎         | 780/22132 [00:23<07:43, 46.03it/s]

2026-09-09 18:22:09,657 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:09,677 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:09,695 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:09,716 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:09,744 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]

Indexing Records:   4%|▎         | 785/22132 [00:23<07:42, 46.20it/s]

2026-09-09 18:22:09,769 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:22:09,794 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:22:09,813 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:09,837 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:09,857 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:   4%|▎         | 790/22132 [00:23<07:48, 45.57it/s]

2026-09-09 18:22:09,879 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:09,902 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:09,923 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:09,943 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:09,963 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:   4%|▎         | 795/22132 [00:24<07:43, 46.03it/s]

2026-09-09 18:22:09,985 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:10,007 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:10,032 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:22:10,055 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:10,074 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:   4%|▎         | 800/22132 [00:24<07:46, 45.71it/s]

2026-09-09 18:22:10,101 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:22:10,122 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:10,142 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:10,163 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:10,181 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:   4%|▎         | 805/22132 [00:24<07:43, 46.05it/s]

2026-09-09 18:22:10,201 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:10,218 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:10,237 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:10,260 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:10,283 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:   4%|▎         | 810/22132 [00:24<07:34, 46.90it/s]

2026-09-09 18:22:10,315 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:22:10,341 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:22:10,372 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:22:10,397 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:22:10,424 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]

Indexing Records:   4%|▎         | 815/22132 [00:24<08:18, 42.73it/s]

2026-09-09 18:22:10,449 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:10,467 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:10,490 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:10,508 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:10,529 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:   4%|▎         | 820/22132 [00:24<08:02, 44.15it/s]

2026-09-09 18:22:10,550 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:10,571 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:10,592 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:10,613 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:10,635 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:   4%|▎         | 825/22132 [00:24<07:54, 44.93it/s]

2026-09-09 18:22:10,656 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:10,677 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:10,697 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:10,715 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:10,739 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:   4%|▍         | 830/22132 [00:24<07:43, 45.94it/s]

2026-09-09 18:22:10,760 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:10,785 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:22:10,804 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:10,822 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:10,842 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:   4%|▍         | 835/22132 [00:24<07:36, 46.69it/s]

2026-09-09 18:22:10,860 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:10,878 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:10,895 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:10,913 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:10,933 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:10,954 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:   4%|▍         | 841/22132 [00:25<07:16, 48.75it/s]

2026-09-09 18:22:10,974 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:11,002 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:22:11,026 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:22:11,061 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]
2026-09-09 18:22:11,085 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:   4%|▍         | 846/22132 [00:25<07:51, 45.19it/s]

2026-09-09 18:22:11,110 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:22:11,134 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:22:11,158 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:22:11,181 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:11,201 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:   4%|▍         | 851/22132 [00:25<07:57, 44.58it/s]

2026-09-09 18:22:11,221 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:11,242 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:11,263 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:11,281 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:11,301 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:   4%|▍         | 856/22132 [00:25<07:42, 45.95it/s]

2026-09-09 18:22:11,320 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:11,339 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:11,358 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:11,382 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:11,404 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:   4%|▍         | 861/22132 [00:25<07:35, 46.74it/s]

2026-09-09 18:22:11,425 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:11,444 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:11,462 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:11,480 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:11,497 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:11,515 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:   4%|▍         | 867/22132 [00:25<07:13, 49.01it/s]

2026-09-09 18:22:11,536 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:11,555 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:11,574 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:11,594 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:11,617 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:   4%|▍         | 872/22132 [00:25<07:14, 48.90it/s]

2026-09-09 18:22:11,642 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:22:11,662 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:11,680 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:11,702 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:11,724 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:   4%|▍         | 877/22132 [00:25<07:20, 48.29it/s]

2026-09-09 18:22:11,744 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:11,762 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:11,782 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:11,801 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:11,819 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:11,836 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:   4%|▍         | 883/22132 [00:25<07:05, 49.91it/s]

2026-09-09 18:22:11,855 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:11,872 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:11,888 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:11,906 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:11,923 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:11,942 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:   4%|▍         | 889/22132 [00:26<06:49, 51.88it/s]

2026-09-09 18:22:11,960 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:11,977 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:11,993 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:12,019 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:22:12,042 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:12,062 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:   4%|▍         | 895/22132 [00:26<06:54, 51.26it/s]

2026-09-09 18:22:12,083 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:12,102 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:12,121 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:12,139 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:12,160 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:12,177 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:   4%|▍         | 901/22132 [00:26<06:51, 51.54it/s]

2026-09-09 18:22:12,195 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:12,215 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:12,234 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:12,251 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:12,268 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:12,285 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:   4%|▍         | 907/22132 [00:26<06:42, 52.77it/s]

2026-09-09 18:22:12,304 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:12,322 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:12,341 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:12,361 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:12,380 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:12,398 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:   4%|▍         | 913/22132 [00:26<06:41, 52.91it/s]

2026-09-09 18:22:12,416 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:12,439 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:12,459 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:12,476 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:12,495 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:12,514 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:   4%|▍         | 919/22132 [00:26<06:44, 52.48it/s]

2026-09-09 18:22:12,536 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:12,557 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:12,586 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:22:12,609 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:12,626 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:12,649 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:   4%|▍         | 925/22132 [00:26<07:05, 49.81it/s]

2026-09-09 18:22:12,668 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:12,689 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:12,713 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:22:12,736 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:12,753 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:12,771 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:   4%|▍         | 931/22132 [00:26<07:06, 49.65it/s]

2026-09-09 18:22:12,791 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:12,812 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:12,834 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:12,855 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:12,874 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:   4%|▍         | 936/22132 [00:27<07:09, 49.34it/s]

2026-09-09 18:22:12,892 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:12,909 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:12,926 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:12,943 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:12,963 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:12,980 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:   4%|▍         | 942/22132 [00:27<06:52, 51.31it/s]

2026-09-09 18:22:13,000 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:13,033 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:22:13,050 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:13,070 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:13,091 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:13,118 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]

Indexing Records:   4%|▍         | 948/22132 [00:27<07:15, 48.60it/s]

2026-09-09 18:22:13,139 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:13,157 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:13,175 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:13,194 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:13,215 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:13,234 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:   4%|▍         | 954/22132 [00:27<07:07, 49.51it/s]

2026-09-09 18:22:13,253 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:13,271 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:13,290 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:13,308 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:13,328 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:13,347 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:   4%|▍         | 960/22132 [00:27<06:58, 50.55it/s]

2026-09-09 18:22:13,367 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:13,384 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:13,403 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:13,423 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:13,446 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:13,465 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:   4%|▍         | 966/22132 [00:27<06:57, 50.64it/s]

2026-09-09 18:22:13,484 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:13,503 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:13,522 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:13,542 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:13,562 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:13,583 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:   4%|▍         | 972/22132 [00:27<06:56, 50.80it/s]

2026-09-09 18:22:13,602 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:13,622 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:13,640 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:13,660 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:13,677 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:13,696 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:   4%|▍         | 978/22132 [00:27<06:51, 51.40it/s]

2026-09-09 18:22:13,717 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:13,736 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:13,756 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:13,774 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:13,792 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:13,810 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:   4%|▍         | 984/22132 [00:27<06:48, 51.74it/s]

2026-09-09 18:22:13,831 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:13,848 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:13,867 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:13,889 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:13,910 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:13,930 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:   4%|▍         | 990/22132 [00:28<06:52, 51.31it/s]

2026-09-09 18:22:13,951 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:13,974 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:13,992 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:14,019 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:22:14,043 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:22:14,065 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:   5%|▍         | 996/22132 [00:28<07:11, 49.01it/s]

2026-09-09 18:22:14,086 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:14,106 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:14,128 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:14,145 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:14,166 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:   5%|▍         | 1001/22132 [00:28<07:09, 49.14it/s]

2026-09-09 18:22:14,188 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:14,209 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:14,227 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:14,246 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:14,263 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:14,281 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:   5%|▍         | 1007/22132 [00:28<07:02, 50.01it/s]

2026-09-09 18:22:14,300 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:14,319 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:14,336 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:14,358 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:14,378 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:14,399 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:   5%|▍         | 1013/22132 [00:28<06:59, 50.31it/s]

2026-09-09 18:22:14,421 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:14,442 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:14,461 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:14,482 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:14,503 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:14,527 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:   5%|▍         | 1019/22132 [00:28<07:09, 49.17it/s]

2026-09-09 18:22:14,546 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:14,563 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:14,582 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:14,603 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:14,621 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:14,638 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:   5%|▍         | 1025/22132 [00:28<06:58, 50.49it/s]

2026-09-09 18:22:14,658 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:14,679 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:14,698 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:14,716 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:14,740 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:14,763 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:   5%|▍         | 1031/22132 [00:28<07:03, 49.79it/s]

2026-09-09 18:22:14,784 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:14,801 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:14,820 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:14,838 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:14,859 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:14,877 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:   5%|▍         | 1037/22132 [00:29<06:57, 50.52it/s]

2026-09-09 18:22:14,897 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:14,914 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:14,932 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:14,953 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:14,974 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:14,996 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:   5%|▍         | 1043/22132 [00:29<06:57, 50.55it/s]

2026-09-09 18:22:15,033 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]
2026-09-09 18:22:15,053 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:15,074 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:15,092 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:15,114 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:15,133 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:   5%|▍         | 1049/22132 [00:29<07:15, 48.36it/s]

2026-09-09 18:22:15,154 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:15,178 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:15,202 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:22:15,221 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:15,237 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:   5%|▍         | 1054/22132 [00:29<07:16, 48.29it/s]

2026-09-09 18:22:15,258 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:15,275 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:15,291 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:15,308 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:15,326 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:15,342 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:   5%|▍         | 1060/22132 [00:29<06:56, 50.63it/s]

2026-09-09 18:22:15,362 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:15,378 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:15,395 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:15,412 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:15,431 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:15,452 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:   5%|▍         | 1066/22132 [00:29<06:46, 51.84it/s]

2026-09-09 18:22:15,471 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:15,495 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:15,517 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:15,536 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:15,557 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:15,573 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:   5%|▍         | 1072/22132 [00:29<06:52, 51.07it/s]

2026-09-09 18:22:15,592 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:15,610 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:15,627 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:15,646 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:15,664 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:15,681 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:   5%|▍         | 1078/22132 [00:29<06:41, 52.44it/s]

2026-09-09 18:22:15,699 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:15,716 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:15,734 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:15,751 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:15,768 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:15,785 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:   5%|▍         | 1084/22132 [00:29<06:30, 53.91it/s]

2026-09-09 18:22:15,804 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:15,822 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:15,850 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:22:15,867 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:15,886 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:15,903 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:   5%|▍         | 1090/22132 [00:30<06:37, 52.97it/s]

2026-09-09 18:22:15,921 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:15,942 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:15,959 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:15,977 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:15,995 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:16,015 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:   5%|▍         | 1096/22132 [00:30<06:36, 53.10it/s]

2026-09-09 18:22:16,035 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:16,053 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:16,074 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:16,094 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:16,117 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:16,136 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:   5%|▍         | 1102/22132 [00:30<06:43, 52.06it/s]

2026-09-09 18:22:16,155 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:16,178 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:16,201 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:16,223 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:16,240 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:16,258 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:   5%|▌         | 1108/22132 [00:30<06:51, 51.08it/s]

2026-09-09 18:22:16,277 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:16,294 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:16,315 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:16,337 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:16,353 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:16,371 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:   5%|▌         | 1114/22132 [00:30<06:46, 51.76it/s]

2026-09-09 18:22:16,390 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:16,412 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:16,433 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:16,454 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:16,471 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:16,490 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:   5%|▌         | 1120/22132 [00:30<06:49, 51.32it/s]

2026-09-09 18:22:16,510 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:16,530 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:16,550 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:16,569 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:16,586 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:16,607 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:   5%|▌         | 1126/22132 [00:30<06:50, 51.23it/s]

2026-09-09 18:22:16,626 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:16,643 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:16,662 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:16,681 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:16,703 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:16,722 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:   5%|▌         | 1132/22132 [00:30<06:47, 51.53it/s]

2026-09-09 18:22:16,742 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:16,761 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:16,778 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:16,801 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:16,819 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:16,835 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:   5%|▌         | 1138/22132 [00:30<06:43, 52.00it/s]

2026-09-09 18:22:16,853 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:16,870 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:16,888 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:16,906 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:16,927 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:16,948 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:   5%|▌         | 1144/22132 [00:31<06:40, 52.37it/s]

2026-09-09 18:22:16,967 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:16,984 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:17,002 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:17,021 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:17,038 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:17,055 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:   5%|▌         | 1150/22132 [00:31<06:32, 53.42it/s]

2026-09-09 18:22:17,073 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:17,091 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:17,111 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:17,130 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:17,147 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:17,164 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:   5%|▌         | 1156/22132 [00:31<06:29, 53.86it/s]

2026-09-09 18:22:17,183 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:17,201 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:17,219 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:17,236 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:17,253 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:17,271 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:   5%|▌         | 1162/22132 [00:31<06:24, 54.55it/s]

2026-09-09 18:22:17,290 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:17,308 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:17,325 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:17,343 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:17,361 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:17,379 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:   5%|▌         | 1168/22132 [00:31<06:22, 54.82it/s]

2026-09-09 18:22:17,398 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:17,416 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:17,432 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:17,448 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:17,465 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:17,482 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:   5%|▌         | 1174/22132 [00:31<06:15, 55.77it/s]

2026-09-09 18:22:17,500 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:17,518 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:17,534 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:17,551 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:17,567 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:17,585 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:   5%|▌         | 1180/22132 [00:31<06:10, 56.52it/s]

2026-09-09 18:22:17,606 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:17,625 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:17,643 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:17,659 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:17,679 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:17,696 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:   5%|▌         | 1186/22132 [00:31<06:16, 55.70it/s]

2026-09-09 18:22:17,714 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:17,733 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:17,755 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:17,772 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:17,789 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:17,807 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:   5%|▌         | 1192/22132 [00:31<06:18, 55.27it/s]

2026-09-09 18:22:17,825 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:17,842 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:17,861 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:17,879 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:17,896 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:17,913 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:   5%|▌         | 1198/22132 [00:32<06:16, 55.67it/s]

2026-09-09 18:22:17,930 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:17,948 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:17,965 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:17,982 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:17,999 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:18,017 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:   5%|▌         | 1204/22132 [00:32<06:12, 56.20it/s]

2026-09-09 18:22:18,034 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:18,051 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:18,067 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:18,084 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:18,100 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:18,118 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:   5%|▌         | 1210/22132 [00:32<06:05, 57.23it/s]

2026-09-09 18:22:18,140 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:18,156 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:18,173 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:18,189 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:18,206 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:18,225 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:   5%|▌         | 1216/22132 [00:32<06:08, 56.76it/s]

2026-09-09 18:22:18,245 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:18,263 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:18,280 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:18,300 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:18,317 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:18,335 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:   6%|▌         | 1222/22132 [00:32<06:13, 56.06it/s]

2026-09-09 18:22:18,357 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:18,379 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:18,402 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:18,431 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:22:18,452 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:18,473 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:   6%|▌         | 1228/22132 [00:32<06:45, 51.58it/s]

2026-09-09 18:22:18,494 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:18,519 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:22:18,539 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:18,559 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:18,580 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:18,601 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:   6%|▌         | 1234/22132 [00:32<06:57, 50.07it/s]

2026-09-09 18:22:18,621 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:18,640 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:18,662 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:18,681 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:18,700 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:18,719 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:   6%|▌         | 1240/22132 [00:32<06:54, 50.41it/s]

2026-09-09 18:22:18,739 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:18,759 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:18,780 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:18,800 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:18,818 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:18,837 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:   6%|▌         | 1246/22132 [00:32<06:53, 50.46it/s]

2026-09-09 18:22:18,857 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:18,874 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:18,891 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:18,908 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:18,925 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:18,976 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.050s]

Indexing Records:   6%|▌         | 1252/22132 [00:33<07:14, 48.06it/s]

2026-09-09 18:22:19,004 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:22:19,025 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:19,045 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:19,064 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:19,085 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:   6%|▌         | 1257/22132 [00:33<07:20, 47.43it/s]

2026-09-09 18:22:19,105 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:19,125 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:19,153 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:22:19,180 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:22:19,204 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:   6%|▌         | 1262/22132 [00:33<07:35, 45.86it/s]

2026-09-09 18:22:19,225 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:19,247 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:19,265 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:19,284 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:19,304 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:19,326 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:   6%|▌         | 1268/22132 [00:33<07:25, 46.88it/s]

2026-09-09 18:22:19,347 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:19,367 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:19,387 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:19,406 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:19,426 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:   6%|▌         | 1273/22132 [00:33<07:17, 47.67it/s]

2026-09-09 18:22:19,449 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:19,473 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:19,494 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:19,518 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:19,543 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:   6%|▌         | 1278/22132 [00:33<07:32, 46.12it/s]

2026-09-09 18:22:19,566 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:19,585 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:19,605 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:19,624 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:19,645 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:   6%|▌         | 1283/22132 [00:33<07:23, 46.99it/s]

2026-09-09 18:22:19,666 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:19,685 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:19,705 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:19,726 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:19,745 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:   6%|▌         | 1288/22132 [00:33<07:16, 47.78it/s]

2026-09-09 18:22:19,766 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:19,788 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:19,808 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:19,828 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:19,854 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:   6%|▌         | 1293/22132 [00:33<07:21, 47.22it/s]

2026-09-09 18:22:19,875 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:19,946 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.069s]
2026-09-09 18:22:19,976 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:22:20,002 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:22:20,037 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]

Indexing Records:   6%|▌         | 1298/22132 [00:34<08:55, 38.91it/s]

2026-09-09 18:22:20,057 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:20,077 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:20,096 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:20,117 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:20,137 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:   6%|▌         | 1303/22132 [00:34<08:20, 41.61it/s]

2026-09-09 18:22:20,157 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:20,196 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.038s]
2026-09-09 18:22:20,215 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:20,236 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:20,255 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:   6%|▌         | 1308/22132 [00:34<08:18, 41.79it/s]

2026-09-09 18:22:20,283 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:22:20,308 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:22:20,329 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:20,348 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:20,370 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:   6%|▌         | 1313/22132 [00:34<08:11, 42.33it/s]

2026-09-09 18:22:20,390 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:20,409 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:20,430 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:20,449 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:20,470 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:20,490 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:   6%|▌         | 1319/22132 [00:34<07:46, 44.60it/s]

2026-09-09 18:22:20,511 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:20,532 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:20,550 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:20,570 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:20,589 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:20,607 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:   6%|▌         | 1325/22132 [00:34<07:27, 46.54it/s]

2026-09-09 18:22:20,629 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:20,650 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:20,669 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:20,689 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:20,709 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:   6%|▌         | 1330/22132 [00:34<07:19, 47.29it/s]

2026-09-09 18:22:20,729 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:20,747 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:20,766 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:20,786 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:20,806 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:20,825 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:   6%|▌         | 1336/22132 [00:34<07:07, 48.65it/s]

2026-09-09 18:22:20,844 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:20,866 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:20,894 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:22:20,915 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:20,932 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:   6%|▌         | 1341/22132 [00:35<07:12, 48.04it/s]

2026-09-09 18:22:20,950 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:20,974 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:20,995 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:21,012 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:21,031 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:21,047 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:   6%|▌         | 1347/22132 [00:35<07:01, 49.31it/s]

2026-09-09 18:22:21,065 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:21,085 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:21,102 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:21,119 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:21,135 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:21,153 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:   6%|▌         | 1353/22132 [00:35<06:43, 51.46it/s]

2026-09-09 18:22:21,172 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:21,193 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:21,215 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:21,233 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:21,251 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:21,268 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:   6%|▌         | 1359/22132 [00:35<06:42, 51.62it/s]

2026-09-09 18:22:21,290 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:21,309 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:21,327 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:21,347 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:21,366 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:21,383 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:   6%|▌         | 1365/22132 [00:35<06:40, 51.87it/s]

2026-09-09 18:22:21,402 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:21,420 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:21,474 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.053s]
2026-09-09 18:22:21,490 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:21,506 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:22:21,521 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:   6%|▌         | 1371/22132 [00:35<07:04, 48.91it/s]

2026-09-09 18:22:21,537 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:22:21,552 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:22:21,565 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:22:21,580 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:22:21,595 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:22:21,610 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:22:21,624 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]

Indexing Records:   6%|▌         | 1378/22132 [00:35<06:23, 54.09it/s]

2026-09-09 18:22:21,640 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:22:21,654 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:22:21,669 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:22:21,684 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:22:21,700 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:21,717 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:21,734 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:   6%|▋         | 1385/22132 [00:35<06:04, 56.89it/s]

2026-09-09 18:22:21,751 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:21,767 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:21,788 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:21,804 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:21,821 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:21,839 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:   6%|▋         | 1391/22132 [00:35<06:04, 56.97it/s]

2026-09-09 18:22:21,857 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:21,874 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:21,890 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:21,907 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:21,930 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:21,950 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:   6%|▋         | 1397/22132 [00:36<06:09, 56.09it/s]

2026-09-09 18:22:21,972 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:21,991 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:22,018 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:22:22,042 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:22,065 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:22,083 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:   6%|▋         | 1403/22132 [00:36<06:35, 52.35it/s]

2026-09-09 18:22:22,101 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:22,118 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:22,136 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:22,153 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:22,171 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:22,189 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:   6%|▋         | 1409/22132 [00:36<06:27, 53.51it/s]

2026-09-09 18:22:22,206 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:22,225 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:22,241 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:22,257 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:22,274 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:22,291 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:   6%|▋         | 1415/22132 [00:36<06:16, 54.98it/s]

2026-09-09 18:22:22,308 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:22,326 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:22,343 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:22,360 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:22,377 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:22,395 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:   6%|▋         | 1421/22132 [00:36<06:11, 55.80it/s]

2026-09-09 18:22:22,411 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:22,429 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:22,448 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:22,471 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:22,491 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:22,512 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:   6%|▋         | 1427/22132 [00:36<06:20, 54.34it/s]

2026-09-09 18:22:22,533 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:22,552 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:22,571 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:22,590 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:22,610 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:22,629 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:   6%|▋         | 1433/22132 [00:36<06:27, 53.37it/s]

2026-09-09 18:22:22,651 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:22,670 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:22,687 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:22,702 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:22:22,722 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:22,738 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:   7%|▋         | 1439/22132 [00:36<06:24, 53.89it/s]

2026-09-09 18:22:22,755 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:22,771 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:22,790 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:22,807 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:22,823 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:22,840 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:   7%|▋         | 1445/22132 [00:36<06:14, 55.24it/s]

2026-09-09 18:22:22,857 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:22,874 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:22,891 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:22,907 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:22,925 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:22,941 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:   7%|▋         | 1451/22132 [00:37<06:06, 56.45it/s]

2026-09-09 18:22:22,959 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:22,977 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:23,004 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:22:23,025 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:23,045 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:23,067 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:   7%|▋         | 1457/22132 [00:37<06:26, 53.53it/s]

2026-09-09 18:22:23,095 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:22:23,117 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:23,136 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:23,154 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:23,173 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:23,194 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:   7%|▋         | 1463/22132 [00:37<06:42, 51.38it/s]

2026-09-09 18:22:23,224 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:22:23,246 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:23,269 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:23,286 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:23,303 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:23,321 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:   7%|▋         | 1469/22132 [00:37<06:52, 50.07it/s]

2026-09-09 18:22:23,341 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:23,363 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:23,384 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:23,404 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:23,423 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:23,442 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:   7%|▋         | 1475/22132 [00:37<06:54, 49.89it/s]

2026-09-09 18:22:23,464 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:23,484 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:23,501 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:23,518 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:23,535 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:23,551 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:   7%|▋         | 1481/22132 [00:37<06:41, 51.39it/s]

2026-09-09 18:22:23,568 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:23,586 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:23,604 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:23,620 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:23,637 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:23,655 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:   7%|▋         | 1487/22132 [00:37<06:28, 53.18it/s]

2026-09-09 18:22:23,672 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:23,688 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:23,705 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:23,723 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:23,740 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:23,756 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:   7%|▋         | 1493/22132 [00:37<06:15, 54.90it/s]

2026-09-09 18:22:23,775 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:23,791 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:23,810 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:23,826 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:23,842 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:22:23,859 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:   7%|▋         | 1499/22132 [00:38<06:09, 55.87it/s]

2026-09-09 18:22:23,878 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:23,897 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:23,916 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:23,932 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:23,949 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:23,966 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:   7%|▋         | 1505/22132 [00:38<06:09, 55.90it/s]

2026-09-09 18:22:23,983 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:24,003 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:24,019 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:24,037 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:24,054 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:24,071 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:   7%|▋         | 1511/22132 [00:38<06:06, 56.19it/s]

2026-09-09 18:22:24,091 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:24,108 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:24,126 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:24,145 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:24,165 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:24,184 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:   7%|▋         | 1517/22132 [00:38<06:13, 55.24it/s]

2026-09-09 18:22:24,208 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:24,226 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:24,243 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:24,263 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:24,280 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:24,296 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:   7%|▋         | 1523/22132 [00:38<06:16, 54.72it/s]

2026-09-09 18:22:24,315 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:24,332 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:24,349 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:24,367 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:24,384 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:24,402 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:   7%|▋         | 1529/22132 [00:38<06:12, 55.32it/s]

2026-09-09 18:22:24,420 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:24,438 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:24,454 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:24,471 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:24,487 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:24,503 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:   7%|▋         | 1535/22132 [00:38<06:05, 56.41it/s]

2026-09-09 18:22:24,528 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:24,545 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:24,564 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:24,581 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:24,597 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:24,616 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:   7%|▋         | 1541/22132 [00:38<06:10, 55.52it/s]

2026-09-09 18:22:24,639 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:24,658 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:24,676 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:24,694 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:24,712 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:24,729 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:   7%|▋         | 1547/22132 [00:38<06:16, 54.69it/s]

2026-09-09 18:22:24,749 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:24,765 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:24,782 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:24,799 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:24,818 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:24,835 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:   7%|▋         | 1553/22132 [00:38<06:12, 55.19it/s]

2026-09-09 18:22:24,854 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:24,874 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:24,895 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:24,912 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:24,928 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:24,945 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:   7%|▋         | 1559/22132 [00:39<06:13, 55.08it/s]

2026-09-09 18:22:24,965 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:24,982 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:24,999 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:25,017 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:25,035 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:25,051 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:   7%|▋         | 1565/22132 [00:39<06:10, 55.45it/s]

2026-09-09 18:22:25,070 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:25,086 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:25,102 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:22:25,121 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:25,138 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:25,155 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:   7%|▋         | 1571/22132 [00:39<06:06, 56.18it/s]

2026-09-09 18:22:25,173 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:25,190 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:25,207 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:25,225 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:25,245 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:25,265 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:   7%|▋         | 1577/22132 [00:39<06:09, 55.60it/s]

2026-09-09 18:22:25,286 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:25,305 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:25,323 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:25,340 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:25,361 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:25,378 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:   7%|▋         | 1583/22132 [00:39<06:14, 54.87it/s]

2026-09-09 18:22:25,396 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:25,415 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:25,434 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:25,451 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:25,470 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:25,492 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:   7%|▋         | 1589/22132 [00:39<06:19, 54.19it/s]

2026-09-09 18:22:25,514 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:25,534 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:25,551 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:25,570 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:25,587 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:25,605 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:   7%|▋         | 1595/22132 [00:39<06:21, 53.85it/s]

2026-09-09 18:22:25,626 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:25,645 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:25,663 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:25,682 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:25,699 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:25,716 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:   7%|▋         | 1601/22132 [00:39<06:20, 53.93it/s]

2026-09-09 18:22:25,738 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:25,758 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:25,779 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:25,800 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:25,825 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:22:25,855 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]

Indexing Records:   7%|▋         | 1607/22132 [00:39<06:48, 50.22it/s]

2026-09-09 18:22:25,881 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:22:25,906 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:22:25,938 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:22:25,963 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:22:25,990 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:22:26,025 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]

Indexing Records:   7%|▋         | 1613/22132 [00:40<07:40, 44.53it/s]

2026-09-09 18:22:26,045 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:26,064 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:26,081 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:26,099 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:26,118 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:26,138 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:   7%|▋         | 1619/22132 [00:40<07:18, 46.82it/s]

2026-09-09 18:22:26,159 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:26,179 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:26,199 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:26,223 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:26,244 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:   7%|▋         | 1624/22132 [00:40<07:17, 46.91it/s]

2026-09-09 18:22:26,261 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:26,282 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:26,299 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:26,315 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:26,335 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:26,355 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:   7%|▋         | 1630/22132 [00:40<06:59, 48.90it/s]

2026-09-09 18:22:26,377 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:26,395 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:26,413 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:26,431 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:26,448 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:26,465 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:   7%|▋         | 1636/22132 [00:40<06:45, 50.49it/s]

2026-09-09 18:22:26,483 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:26,501 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:26,520 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:26,540 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:26,559 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:26,579 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:   7%|▋         | 1642/22132 [00:40<06:40, 51.13it/s]

2026-09-09 18:22:26,606 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:22:26,625 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:26,646 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:26,667 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:26,687 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:26,706 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:   7%|▋         | 1648/22132 [00:40<06:50, 49.93it/s]

2026-09-09 18:22:26,727 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:26,746 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:26,765 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:26,784 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:26,803 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:26,823 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:   7%|▋         | 1654/22132 [00:40<06:47, 50.29it/s]

2026-09-09 18:22:26,843 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:26,863 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:26,883 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:26,902 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:26,920 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:26,940 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:   8%|▊         | 1660/22132 [00:41<06:44, 50.60it/s]

2026-09-09 18:22:26,959 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:26,980 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:27,000 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:27,021 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:27,045 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:22:27,065 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:   8%|▊         | 1666/22132 [00:41<06:51, 49.74it/s]

2026-09-09 18:22:27,087 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:27,107 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:27,125 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:27,145 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:27,164 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:27,185 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:   8%|▊         | 1672/22132 [00:41<06:50, 49.84it/s]

2026-09-09 18:22:27,204 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:27,220 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:22:27,236 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:27,254 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:27,272 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:27,293 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:   8%|▊         | 1678/22132 [00:41<06:37, 51.41it/s]

2026-09-09 18:22:27,312 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:27,333 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:27,349 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:27,365 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:27,383 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:27,402 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:   8%|▊         | 1684/22132 [00:41<06:29, 52.44it/s]

2026-09-09 18:22:27,422 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:27,449 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:22:27,465 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:27,485 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:27,502 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:27,519 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:   8%|▊         | 1690/22132 [00:41<06:31, 52.16it/s]

2026-09-09 18:22:27,537 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:27,553 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:22:27,569 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:27,590 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:27,609 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:27,626 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:   8%|▊         | 1696/22132 [00:41<06:23, 53.31it/s]

2026-09-09 18:22:27,643 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:27,660 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:27,677 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:27,696 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:27,713 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:27,729 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:   8%|▊         | 1702/22132 [00:41<06:14, 54.60it/s]

2026-09-09 18:22:27,748 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:27,764 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:27,784 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:27,802 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:27,819 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:27,836 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:   8%|▊         | 1708/22132 [00:41<06:10, 55.09it/s]

2026-09-09 18:22:27,854 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:27,871 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:27,889 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:27,905 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:27,922 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:27,940 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:   8%|▊         | 1714/22132 [00:42<06:05, 55.79it/s]

2026-09-09 18:22:27,958 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:27,976 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:27,993 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:28,012 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:28,031 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:28,048 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:   8%|▊         | 1720/22132 [00:42<06:06, 55.76it/s]

2026-09-09 18:22:28,067 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:28,084 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:28,101 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:28,118 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:28,135 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:28,151 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:   8%|▊         | 1726/22132 [00:42<06:01, 56.49it/s]

2026-09-09 18:22:28,169 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:28,189 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:28,208 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:28,225 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:28,243 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:28,259 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:   8%|▊         | 1732/22132 [00:42<06:02, 56.21it/s]

2026-09-09 18:22:28,276 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:28,294 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:28,311 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:28,328 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:28,345 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:28,362 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:   8%|▊         | 1738/22132 [00:42<05:58, 56.88it/s]

2026-09-09 18:22:28,380 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:28,398 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:28,418 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:28,439 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:28,466 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:22:28,486 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:   8%|▊         | 1744/22132 [00:42<06:17, 54.03it/s]

2026-09-09 18:22:28,504 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:28,521 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:28,537 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:28,556 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:28,576 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:28,594 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:   8%|▊         | 1750/22132 [00:42<06:14, 54.40it/s]

2026-09-09 18:22:28,613 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:28,630 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:28,648 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:28,666 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:28,687 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:28,705 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:   8%|▊         | 1756/22132 [00:42<06:15, 54.33it/s]

2026-09-09 18:22:28,726 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:28,748 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:28,767 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:28,788 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:28,806 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:28,825 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:   8%|▊         | 1762/22132 [00:42<06:25, 52.90it/s]

2026-09-09 18:22:28,844 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:28,861 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:28,879 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:28,896 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:28,913 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:28,932 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:   8%|▊         | 1768/22132 [00:43<06:18, 53.87it/s]

2026-09-09 18:22:28,950 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:28,968 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:28,985 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:29,002 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:29,020 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:29,037 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:   8%|▊         | 1774/22132 [00:43<06:11, 54.77it/s]

2026-09-09 18:22:29,054 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:29,072 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:29,089 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:29,107 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:29,124 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:29,140 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:   8%|▊         | 1780/22132 [00:43<06:05, 55.75it/s]

2026-09-09 18:22:29,158 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:29,176 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:29,192 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:29,210 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:29,227 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:29,243 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:   8%|▊         | 1786/22132 [00:43<06:00, 56.45it/s]

2026-09-09 18:22:29,260 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:29,277 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:29,293 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:29,312 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:29,332 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:29,349 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:   8%|▊         | 1792/22132 [00:43<05:59, 56.54it/s]

2026-09-09 18:22:29,368 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:29,384 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:29,401 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:29,418 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:29,438 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:29,456 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:   8%|▊         | 1798/22132 [00:43<06:00, 56.46it/s]

2026-09-09 18:22:29,473 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:29,490 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:29,508 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:29,525 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:29,541 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:29,557 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:   8%|▊         | 1804/22132 [00:43<05:55, 57.25it/s]

2026-09-09 18:22:29,575 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:29,591 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:29,608 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:29,633 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:22:29,653 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:29,674 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:   8%|▊         | 1810/22132 [00:43<06:06, 55.39it/s]

2026-09-09 18:22:29,697 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:29,716 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:29,737 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:29,758 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:29,778 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:29,798 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:   8%|▊         | 1816/22132 [00:43<06:22, 53.09it/s]

2026-09-09 18:22:29,818 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:29,838 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:29,861 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:29,881 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:29,902 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:29,923 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:   8%|▊         | 1822/22132 [00:44<06:34, 51.47it/s]

2026-09-09 18:22:29,951 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:22:29,968 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:29,986 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:30,008 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:30,035 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:22:30,051 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:   8%|▊         | 1828/22132 [00:44<06:46, 49.95it/s]

2026-09-09 18:22:30,069 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:30,086 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:30,104 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:30,122 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:30,139 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:30,157 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:   8%|▊         | 1834/22132 [00:44<06:31, 51.80it/s]

2026-09-09 18:22:30,175 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:30,190 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:30,211 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:30,236 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:22:30,252 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:30,271 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:   8%|▊         | 1840/22132 [00:44<06:29, 52.06it/s]

2026-09-09 18:22:30,290 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:30,311 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:30,330 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:30,350 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:30,367 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:30,387 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:   8%|▊         | 1846/22132 [00:44<06:30, 51.90it/s]

2026-09-09 18:22:30,405 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:30,421 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:30,437 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:30,456 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:30,473 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:30,489 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:   8%|▊         | 1852/22132 [00:44<06:16, 53.79it/s]

2026-09-09 18:22:30,507 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:30,526 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:30,543 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:30,560 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:30,576 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:30,595 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:   8%|▊         | 1858/22132 [00:44<06:10, 54.67it/s]

2026-09-09 18:22:30,615 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:30,631 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:30,648 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:30,668 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:30,691 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:30,709 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:   8%|▊         | 1864/22132 [00:44<06:15, 53.98it/s]

2026-09-09 18:22:30,733 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:30,759 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:22:30,785 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:22:30,804 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:30,823 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:30,843 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:   8%|▊         | 1870/22132 [00:44<06:38, 50.90it/s]

2026-09-09 18:22:30,861 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:30,879 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:30,899 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:30,915 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:30,934 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:30,950 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:   8%|▊         | 1876/22132 [00:45<06:27, 52.30it/s]

2026-09-09 18:22:30,970 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:30,988 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:31,007 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:31,027 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:31,046 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:31,064 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:   9%|▊         | 1882/22132 [00:45<06:26, 52.41it/s]

2026-09-09 18:22:31,087 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:31,105 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:31,123 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:31,140 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:31,156 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:31,173 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:   9%|▊         | 1888/22132 [00:45<06:20, 53.17it/s]

2026-09-09 18:22:31,191 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:31,210 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:31,232 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:31,251 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:31,271 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:31,290 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:   9%|▊         | 1894/22132 [00:45<06:24, 52.59it/s]

2026-09-09 18:22:31,352 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.060s]
2026-09-09 18:22:31,371 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:31,388 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:31,406 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:31,423 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:31,440 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:   9%|▊         | 1900/22132 [00:45<07:01, 48.04it/s]

2026-09-09 18:22:31,458 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:31,475 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:31,491 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:31,508 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:31,526 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:31,544 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:   9%|▊         | 1906/22132 [00:45<06:40, 50.53it/s]

2026-09-09 18:22:31,563 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:31,580 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:31,601 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:31,620 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:31,638 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:31,656 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:   9%|▊         | 1912/22132 [00:45<06:32, 51.49it/s]

2026-09-09 18:22:31,673 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:31,691 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:31,708 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:31,724 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:31,741 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:31,757 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:   9%|▊         | 1918/22132 [00:45<06:16, 53.64it/s]

2026-09-09 18:22:31,776 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:31,795 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:31,821 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:22:31,839 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:31,856 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:31,872 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:   9%|▊         | 1924/22132 [00:46<06:19, 53.23it/s]

2026-09-09 18:22:31,890 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:31,907 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:31,924 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:32,864 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.939s]
2026-09-09 18:22:32,887 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:32,909 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:   9%|▊         | 1930/22132 [00:47<21:53, 15.38it/s]

2026-09-09 18:22:32,931 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:32,949 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:32,972 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:32,993 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:33,015 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:   9%|▊         | 1935/22132 [00:47<17:59, 18.70it/s]

2026-09-09 18:22:33,037 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:33,058 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:33,079 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:33,098 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:33,118 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:   9%|▉         | 1940/22132 [00:47<14:58, 22.48it/s]

2026-09-09 18:22:33,138 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:33,162 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:33,180 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:33,200 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:33,219 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:   9%|▉         | 1945/22132 [00:47<12:40, 26.56it/s]

2026-09-09 18:22:33,240 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:33,259 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:33,279 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:33,302 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:33,326 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:   9%|▉         | 1950/22132 [00:47<11:06, 30.28it/s]

2026-09-09 18:22:33,346 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:33,365 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:33,382 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:33,400 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:33,418 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:33,435 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:   9%|▉         | 1956/22132 [00:47<09:27, 35.55it/s]

2026-09-09 18:22:33,452 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:33,470 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:33,488 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:33,507 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:33,527 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:33,550 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:   9%|▉         | 1962/22132 [00:47<08:29, 39.61it/s]

2026-09-09 18:22:33,569 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:33,588 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:33,607 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:33,627 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:33,646 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:33,665 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:   9%|▉         | 1968/22132 [00:47<07:51, 42.79it/s]

2026-09-09 18:22:33,687 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:33,706 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:33,723 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:33,742 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:33,759 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:33,777 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:   9%|▉         | 1974/22132 [00:47<07:21, 45.66it/s]

2026-09-09 18:22:33,797 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:33,815 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:33,833 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:33,851 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:33,868 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:33,885 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:   9%|▉         | 1980/22132 [00:48<06:57, 48.25it/s]

2026-09-09 18:22:33,905 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:33,925 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:33,946 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:33,966 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:33,987 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:34,004 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:   9%|▉         | 1986/22132 [00:48<06:51, 48.96it/s]

2026-09-09 18:22:34,023 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:34,041 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:34,059 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:34,077 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:34,097 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:34,114 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:   9%|▉         | 1992/22132 [00:48<06:38, 50.54it/s]

2026-09-09 18:22:34,133 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:34,159 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:22:34,180 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:34,200 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:34,220 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:34,243 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:   9%|▉         | 1998/22132 [00:48<06:48, 49.25it/s]

2026-09-09 18:22:34,266 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:34,286 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:34,309 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:34,565 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.255s]
2026-09-09 18:22:34,591 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:22:34,612 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:   9%|▉         | 2004/22132 [00:48<10:59, 30.54it/s]

2026-09-09 18:22:34,632 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:34,648 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:22:34,663 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:22:34,680 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:34,696 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:34,714 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:   9%|▉         | 2010/22132 [00:48<09:23, 35.72it/s]

2026-09-09 18:22:34,730 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:22:34,745 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:22:34,762 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:34,779 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:34,794 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:22:34,811 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:34,828 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:   9%|▉         | 2017/22132 [00:48<08:04, 41.50it/s]

2026-09-09 18:22:34,845 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:34,864 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:34,883 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:34,901 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:34,921 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:34,943 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:   9%|▉         | 2023/22132 [00:49<07:35, 44.16it/s]

2026-09-09 18:22:34,965 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:34,982 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:34,999 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:35,019 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:35,034 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:22:35,048 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]

Indexing Records:   9%|▉         | 2029/22132 [00:49<07:05, 47.30it/s]

2026-09-09 18:22:35,066 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:35,084 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:35,101 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:35,118 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:35,132 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]
2026-09-09 18:22:35,147 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:22:35,163 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:   9%|▉         | 2036/22132 [00:49<06:34, 50.98it/s]

2026-09-09 18:22:35,180 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:22:35,197 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:35,215 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:35,233 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:35,249 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:22:35,264 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:   9%|▉         | 2042/22132 [00:49<06:18, 53.13it/s]

2026-09-09 18:22:35,287 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:35,302 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:22:35,321 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:35,340 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:35,358 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:35,377 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:   9%|▉         | 2048/22132 [00:49<06:17, 53.22it/s]

2026-09-09 18:22:35,394 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:35,408 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:22:35,426 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:35,442 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:35,458 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:35,476 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:35,490 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]

Indexing Records:   9%|▉         | 2055/22132 [00:49<06:00, 55.75it/s]

2026-09-09 18:22:35,510 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:35,524 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:22:35,539 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:22:35,558 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:35,573 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:22:35,587 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:22:35,604 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:   9%|▉         | 2062/22132 [00:49<05:49, 57.47it/s]

2026-09-09 18:22:35,621 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:35,636 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:22:35,651 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:22:35,668 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:35,683 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:22:35,697 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:22:35,713 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:   9%|▉         | 2069/22132 [00:49<05:37, 59.44it/s]

2026-09-09 18:22:35,727 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:22:35,745 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:35,763 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:35,782 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:35,801 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:35,821 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:35,844 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:   9%|▉         | 2076/22132 [00:49<05:49, 57.45it/s]

2026-09-09 18:22:35,862 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:35,882 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:35,899 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:35,916 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:35,935 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:35,956 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:   9%|▉         | 2082/22132 [00:50<05:56, 56.24it/s]

2026-09-09 18:22:35,973 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:35,990 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:36,009 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:36,027 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:36,045 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:36,062 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:   9%|▉         | 2088/22132 [00:50<05:55, 56.31it/s]

2026-09-09 18:22:36,081 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:36,098 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:36,116 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:36,136 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:36,155 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:36,175 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:   9%|▉         | 2094/22132 [00:50<06:01, 55.46it/s]

2026-09-09 18:22:36,192 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:36,213 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:36,230 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:36,248 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:36,267 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:36,287 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:   9%|▉         | 2100/22132 [00:50<06:05, 54.84it/s]

2026-09-09 18:22:36,307 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:36,325 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:36,348 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:36,368 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:36,389 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:36,406 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  10%|▉         | 2106/22132 [00:50<06:14, 53.46it/s]

2026-09-09 18:22:36,428 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:36,448 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:36,467 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:36,495 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:22:36,513 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:36,531 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  10%|▉         | 2112/22132 [00:50<06:27, 51.71it/s]

2026-09-09 18:22:36,549 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:36,569 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:36,591 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:36,610 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:36,628 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:36,647 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  10%|▉         | 2118/22132 [00:50<06:27, 51.71it/s]

2026-09-09 18:22:36,667 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:36,685 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:36,704 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:36,722 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:36,740 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:36,760 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  10%|▉         | 2124/22132 [00:50<06:23, 52.16it/s]

2026-09-09 18:22:36,780 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:36,799 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:36,817 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:36,834 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:36,854 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:36,872 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  10%|▉         | 2130/22132 [00:51<06:20, 52.50it/s]

2026-09-09 18:22:36,890 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:36,909 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:36,928 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:36,947 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:36,966 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:36,985 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  10%|▉         | 2136/22132 [00:51<06:19, 52.67it/s]

2026-09-09 18:22:37,005 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:37,022 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:37,039 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:37,056 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:37,074 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:37,091 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  10%|▉         | 2142/22132 [00:51<06:10, 53.90it/s]

2026-09-09 18:22:37,108 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:37,128 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:37,147 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:37,166 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:37,182 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:37,200 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  10%|▉         | 2148/22132 [00:51<06:08, 54.24it/s]

2026-09-09 18:22:37,217 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:37,233 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:37,249 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:37,268 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:37,286 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:37,304 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  10%|▉         | 2154/22132 [00:51<06:01, 55.22it/s]

2026-09-09 18:22:37,323 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:37,341 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:37,359 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:37,376 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:37,398 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:37,420 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  10%|▉         | 2160/22132 [00:51<06:09, 54.01it/s]

2026-09-09 18:22:37,441 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:37,459 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:37,477 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:37,494 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:37,512 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:37,531 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  10%|▉         | 2166/22132 [00:51<06:08, 54.15it/s]

2026-09-09 18:22:37,549 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:37,570 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:37,587 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:37,609 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:37,629 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:37,655 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]

Indexing Records:  10%|▉         | 2172/22132 [00:51<06:22, 52.18it/s]

2026-09-09 18:22:37,678 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:37,699 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:37,716 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:37,737 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:37,756 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:37,774 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  10%|▉         | 2178/22132 [00:51<06:26, 51.68it/s]

2026-09-09 18:22:37,792 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:37,813 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:37,832 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:37,852 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:37,870 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:37,886 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  10%|▉         | 2184/22132 [00:52<06:22, 52.18it/s]

2026-09-09 18:22:37,906 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:37,937 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:22:37,955 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:37,973 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:37,990 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:38,008 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  10%|▉         | 2190/22132 [00:52<06:29, 51.25it/s]

2026-09-09 18:22:38,027 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:38,047 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:38,064 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:38,081 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:38,101 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:38,117 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  10%|▉         | 2196/22132 [00:52<06:21, 52.31it/s]

2026-09-09 18:22:38,135 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:38,153 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:38,169 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:38,186 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:38,203 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:38,220 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  10%|▉         | 2202/22132 [00:52<06:08, 54.10it/s]

2026-09-09 18:22:38,238 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:38,256 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:38,272 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:38,290 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:38,307 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:38,326 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  10%|▉         | 2208/22132 [00:52<06:03, 54.82it/s]

2026-09-09 18:22:38,343 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:38,359 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:38,380 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:38,399 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:38,418 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:38,444 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  10%|█         | 2214/22132 [00:52<06:12, 53.46it/s]

2026-09-09 18:22:38,463 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:38,481 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:38,498 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:38,520 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:38,540 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:38,557 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  10%|█         | 2220/22132 [00:52<06:13, 53.35it/s]

2026-09-09 18:22:38,576 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:38,594 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:38,612 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:38,630 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:38,647 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:38,664 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  10%|█         | 2226/22132 [00:52<06:07, 54.16it/s]

2026-09-09 18:22:38,685 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:38,703 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:38,722 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:38,741 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:38,759 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:38,776 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  10%|█         | 2232/22132 [00:52<06:08, 54.02it/s]

2026-09-09 18:22:38,795 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:38,811 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:38,830 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:38,847 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:38,865 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:38,882 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  10%|█         | 2238/22132 [00:53<06:03, 54.70it/s]

2026-09-09 18:22:38,900 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:38,918 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:38,936 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:38,954 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:38,979 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:22:39,002 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  10%|█         | 2244/22132 [00:53<06:13, 53.29it/s]

2026-09-09 18:22:39,056 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.052s]
2026-09-09 18:22:39,086 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:22:39,106 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:39,135 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:22:39,154 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:39,170 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  10%|█         | 2250/22132 [00:53<07:08, 46.44it/s]

2026-09-09 18:22:39,189 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:39,207 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:39,225 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:39,243 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:39,261 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:39,280 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  10%|█         | 2256/22132 [00:53<06:48, 48.62it/s]

2026-09-09 18:22:39,297 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:39,315 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:39,332 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:39,349 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:39,368 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:39,384 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  10%|█         | 2262/22132 [00:53<06:30, 50.93it/s]

2026-09-09 18:22:39,402 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:39,419 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:39,437 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:39,454 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:39,472 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:39,491 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  10%|█         | 2268/22132 [00:53<06:19, 52.37it/s]

2026-09-09 18:22:39,512 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:39,530 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:39,548 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:39,567 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:39,584 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:39,601 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  10%|█         | 2274/22132 [00:53<06:14, 53.05it/s]

2026-09-09 18:22:39,621 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:39,645 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:22:39,662 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:39,681 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:39,731 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.049s]
2026-09-09 18:22:39,751 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  10%|█         | 2280/22132 [00:53<06:50, 48.34it/s]

2026-09-09 18:22:39,767 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:22:39,784 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:39,800 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:39,817 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:39,835 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:39,852 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  10%|█         | 2286/22132 [00:53<06:27, 51.26it/s]

2026-09-09 18:22:39,870 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:39,886 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:39,904 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:39,922 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:39,940 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:39,959 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  10%|█         | 2292/22132 [00:54<06:17, 52.61it/s]

2026-09-09 18:22:39,977 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:39,994 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:40,023 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:22:40,041 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:40,059 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:40,077 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  10%|█         | 2298/22132 [00:54<06:21, 52.01it/s]

2026-09-09 18:22:40,096 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:40,114 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:40,133 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:40,151 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:40,171 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:40,189 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  10%|█         | 2304/22132 [00:54<06:18, 52.42it/s]

2026-09-09 18:22:40,209 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:40,229 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:40,246 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:40,262 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:40,283 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:40,298 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]

Indexing Records:  10%|█         | 2310/22132 [00:54<06:12, 53.27it/s]

2026-09-09 18:22:40,314 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:22:40,330 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:22:40,345 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:22:40,363 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:40,378 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:22:40,393 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:22:40,408 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  10%|█         | 2317/22132 [00:54<05:51, 56.31it/s]

2026-09-09 18:22:40,424 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:22:40,440 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:22:40,454 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:22:40,468 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:22:40,487 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:40,501 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]
2026-09-09 18:22:40,517 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  11%|█         | 2324/22132 [00:54<05:37, 58.67it/s]

2026-09-09 18:22:40,533 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:22:40,550 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:40,565 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:22:40,582 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:40,599 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:40,618 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  11%|█         | 2330/22132 [00:54<05:36, 58.82it/s]

2026-09-09 18:22:40,637 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:40,655 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:40,671 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:40,688 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:40,707 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:40,725 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  11%|█         | 2336/22132 [00:54<05:40, 58.05it/s]

2026-09-09 18:22:40,747 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:40,765 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:40,786 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:40,804 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:40,822 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:40,840 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  11%|█         | 2342/22132 [00:54<05:52, 56.14it/s]

2026-09-09 18:22:40,857 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:40,874 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:40,893 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:40,911 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:40,929 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:40,946 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  11%|█         | 2348/22132 [00:55<05:51, 56.28it/s]

2026-09-09 18:22:40,966 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:40,989 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:41,009 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:41,029 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:41,046 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:41,065 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  11%|█         | 2354/22132 [00:55<06:03, 54.40it/s]

2026-09-09 18:22:41,085 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:41,104 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:41,123 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:41,142 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:41,159 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:41,176 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  11%|█         | 2360/22132 [00:55<06:04, 54.30it/s]

2026-09-09 18:22:41,195 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:41,213 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:41,231 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:41,248 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:41,269 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:41,286 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  11%|█         | 2366/22132 [00:55<06:03, 54.36it/s]

2026-09-09 18:22:41,305 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:41,322 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:41,341 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:41,367 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:22:41,391 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:41,413 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  11%|█         | 2372/22132 [00:55<06:19, 52.07it/s]

2026-09-09 18:22:41,437 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:41,457 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:41,478 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:41,501 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:41,527 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:22:41,551 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  11%|█         | 2378/22132 [00:55<06:42, 49.13it/s]

2026-09-09 18:22:41,573 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:41,592 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:41,612 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:41,629 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:41,648 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:41,667 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  11%|█         | 2384/22132 [00:55<06:36, 49.85it/s]

2026-09-09 18:22:41,686 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:41,703 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:41,726 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:41,752 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:22:41,774 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:41,795 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  11%|█         | 2390/22132 [00:55<06:43, 48.94it/s]

2026-09-09 18:22:41,813 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:41,830 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:41,850 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:41,868 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:41,885 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:41,902 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  11%|█         | 2396/22132 [00:56<06:27, 50.95it/s]

2026-09-09 18:22:41,919 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:41,935 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:41,952 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:41,969 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:41,986 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:42,003 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  11%|█         | 2402/22132 [00:56<06:10, 53.21it/s]

2026-09-09 18:22:42,023 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:42,041 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:42,058 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:42,074 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:42,092 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:42,110 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  11%|█         | 2408/22132 [00:56<06:04, 54.06it/s]

2026-09-09 18:22:42,128 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:42,149 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:42,166 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:42,186 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:42,205 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:42,222 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  11%|█         | 2414/22132 [00:56<06:06, 53.84it/s]

2026-09-09 18:22:42,241 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:42,258 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:42,276 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:42,295 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:42,313 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:42,332 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  11%|█         | 2420/22132 [00:56<06:04, 54.06it/s]

2026-09-09 18:22:42,352 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:42,372 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:42,390 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:42,408 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:42,426 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:42,444 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  11%|█         | 2426/22132 [00:56<06:05, 53.94it/s]

2026-09-09 18:22:42,464 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:42,484 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:42,502 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:42,525 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:42,544 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:42,560 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  11%|█         | 2432/22132 [00:56<06:09, 53.26it/s]

2026-09-09 18:22:42,579 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:42,596 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:42,614 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:42,632 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:42,651 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:42,669 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  11%|█         | 2438/22132 [00:56<06:06, 53.76it/s]

2026-09-09 18:22:42,686 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:42,704 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:42,726 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:42,744 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:42,762 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:42,779 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  11%|█         | 2444/22132 [00:56<06:05, 53.94it/s]

2026-09-09 18:22:42,798 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:42,817 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:42,839 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:42,855 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:42,872 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:42,889 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  11%|█         | 2450/22132 [00:57<06:03, 54.18it/s]

2026-09-09 18:22:42,907 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:42,926 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:42,948 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:42,967 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:42,984 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:43,005 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  11%|█         | 2456/22132 [00:57<06:08, 53.35it/s]

2026-09-09 18:22:43,035 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:22:43,055 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:43,077 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:43,103 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:22:43,125 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:43,144 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  11%|█         | 2462/22132 [00:57<06:34, 49.83it/s]

2026-09-09 18:22:43,163 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:43,183 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:43,202 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:43,222 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:43,241 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:43,258 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  11%|█         | 2468/22132 [00:57<06:27, 50.70it/s]

2026-09-09 18:22:43,276 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:43,293 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:43,310 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:43,328 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:43,344 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:22:43,363 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  11%|█         | 2474/22132 [00:57<06:15, 52.41it/s]

2026-09-09 18:22:43,381 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:43,397 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:43,416 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:43,433 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:43,449 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:43,465 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  11%|█         | 2480/22132 [00:57<06:02, 54.19it/s]

2026-09-09 18:22:43,483 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:43,501 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:43,519 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:43,537 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:43,556 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:43,578 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  11%|█         | 2486/22132 [00:57<06:04, 53.93it/s]

2026-09-09 18:22:43,598 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:43,620 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:43,637 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:43,654 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:43,675 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:43,692 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  11%|█▏        | 2492/22132 [00:57<06:07, 53.51it/s]

2026-09-09 18:22:43,714 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:43,737 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:43,761 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:22:43,784 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:43,804 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:43,823 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  11%|█▏        | 2498/22132 [00:57<06:25, 50.92it/s]

2026-09-09 18:22:43,843 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:43,863 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:43,884 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:43,909 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:22:43,930 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:43,948 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  11%|█▏        | 2504/22132 [00:58<06:32, 49.96it/s]

2026-09-09 18:22:43,970 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:43,991 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:44,010 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:44,029 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:44,046 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:44,063 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  11%|█▏        | 2510/22132 [00:58<06:27, 50.69it/s]

2026-09-09 18:22:44,081 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:44,097 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:44,116 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:44,133 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:44,151 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:44,167 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  11%|█▏        | 2516/22132 [00:58<06:13, 52.52it/s]

2026-09-09 18:22:44,186 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:44,204 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:44,220 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:22:44,238 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:44,254 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:22:44,270 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  11%|█▏        | 2522/22132 [00:58<06:02, 54.12it/s]

2026-09-09 18:22:44,290 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:44,306 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:44,323 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:44,339 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:44,357 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:44,373 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  11%|█▏        | 2528/22132 [00:58<05:54, 55.36it/s]

2026-09-09 18:22:44,392 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:44,410 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:44,426 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:44,444 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:44,461 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:44,479 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  11%|█▏        | 2534/22132 [00:58<05:51, 55.78it/s]

2026-09-09 18:22:44,496 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:44,515 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:44,534 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:44,552 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:44,568 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:44,586 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  11%|█▏        | 2540/22132 [00:58<05:50, 55.87it/s]

2026-09-09 18:22:44,603 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:44,619 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:44,639 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:44,656 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:44,673 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:44,695 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  12%|█▏        | 2546/22132 [00:58<05:52, 55.60it/s]

2026-09-09 18:22:44,712 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:44,731 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:44,747 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:44,765 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:44,784 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:44,801 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  12%|█▏        | 2552/22132 [00:58<05:50, 55.87it/s]

2026-09-09 18:22:44,819 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:44,835 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:44,853 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:44,872 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:44,892 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:44,908 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  12%|█▏        | 2558/22132 [00:59<05:50, 55.88it/s]

2026-09-09 18:22:44,926 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:44,943 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:44,961 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:44,977 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:44,994 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:45,015 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  12%|█▏        | 2564/22132 [00:59<05:49, 55.96it/s]

2026-09-09 18:22:45,033 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:45,049 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:22:45,066 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:45,084 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:45,102 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:45,119 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  12%|█▏        | 2570/22132 [00:59<05:46, 56.53it/s]

2026-09-09 18:22:45,139 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:45,159 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:45,177 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:45,195 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:45,212 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:45,229 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  12%|█▏        | 2576/22132 [00:59<05:49, 55.92it/s]

2026-09-09 18:22:45,247 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:45,264 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:45,284 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:45,301 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:45,319 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:45,336 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  12%|█▏        | 2582/22132 [00:59<05:49, 55.91it/s]

2026-09-09 18:22:45,355 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:45,372 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:45,391 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:45,408 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:45,430 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:45,451 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  12%|█▏        | 2588/22132 [00:59<05:56, 54.79it/s]

2026-09-09 18:22:45,474 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:45,490 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:45,510 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:45,529 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:45,547 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:45,564 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  12%|█▏        | 2594/22132 [00:59<06:00, 54.24it/s]

2026-09-09 18:22:45,582 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:45,599 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:45,618 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:45,635 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:45,654 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:45,670 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  12%|█▏        | 2600/22132 [00:59<05:55, 54.93it/s]

2026-09-09 18:22:45,689 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:45,705 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:45,724 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:45,741 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:45,760 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:45,778 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  12%|█▏        | 2606/22132 [00:59<05:54, 55.11it/s]

2026-09-09 18:22:45,798 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:45,815 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:45,833 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:45,849 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:45,867 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:45,885 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  12%|█▏        | 2612/22132 [01:00<05:52, 55.37it/s]

2026-09-09 18:22:45,903 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:45,920 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:45,936 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:45,952 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:45,969 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:45,986 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  12%|█▏        | 2618/22132 [01:00<05:44, 56.61it/s]

2026-09-09 18:22:46,003 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:46,020 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:46,037 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:46,055 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:46,072 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:46,091 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  12%|█▏        | 2624/22132 [01:00<05:43, 56.78it/s]

2026-09-09 18:22:46,109 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:46,127 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:46,144 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:46,162 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:46,179 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:46,198 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  12%|█▏        | 2630/22132 [01:00<05:44, 56.55it/s]

2026-09-09 18:22:46,218 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:46,235 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:46,253 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:46,269 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:46,286 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:46,308 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  12%|█▏        | 2636/22132 [01:00<05:48, 55.91it/s]

2026-09-09 18:22:46,326 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:46,342 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:46,358 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:46,375 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:46,392 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:46,409 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  12%|█▏        | 2642/22132 [01:00<05:42, 56.87it/s]

2026-09-09 18:22:46,427 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:46,445 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:46,463 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:46,480 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:46,496 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:46,515 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  12%|█▏        | 2648/22132 [01:00<05:43, 56.79it/s]

2026-09-09 18:22:46,534 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:46,553 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:46,571 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:46,588 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:46,605 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:46,625 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  12%|█▏        | 2654/22132 [01:00<05:46, 56.16it/s]

2026-09-09 18:22:46,642 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:46,660 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:46,678 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:46,694 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:46,710 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:46,727 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  12%|█▏        | 2660/22132 [01:00<05:41, 56.94it/s]

2026-09-09 18:22:46,746 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:46,764 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:46,780 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:46,796 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:46,813 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:46,830 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  12%|█▏        | 2666/22132 [01:00<05:40, 57.19it/s]

2026-09-09 18:22:46,848 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:46,867 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:46,886 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:46,905 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:46,927 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:46,950 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  12%|█▏        | 2672/22132 [01:01<05:54, 54.94it/s]

2026-09-09 18:22:46,971 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:46,992 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:47,013 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:47,037 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:47,062 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:22:47,082 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  12%|█▏        | 2678/22132 [01:01<06:16, 51.67it/s]

2026-09-09 18:22:47,102 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:47,120 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:47,139 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:47,156 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:47,175 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:47,192 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  12%|█▏        | 2684/22132 [01:01<06:11, 52.41it/s]

2026-09-09 18:22:47,213 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:47,231 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:47,248 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:47,267 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:47,285 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:47,302 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  12%|█▏        | 2690/22132 [01:01<06:05, 53.19it/s]

2026-09-09 18:22:47,319 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:47,335 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:47,353 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:47,371 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:47,396 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:22:47,419 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  12%|█▏        | 2696/22132 [01:01<06:09, 52.55it/s]

2026-09-09 18:22:47,445 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:22:47,468 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:47,489 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:47,513 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:22:47,533 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:47,551 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  12%|█▏        | 2702/22132 [01:01<06:27, 50.13it/s]

2026-09-09 18:22:47,570 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:47,588 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:47,608 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:47,627 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:47,644 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:47,668 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  12%|█▏        | 2708/22132 [01:01<06:24, 50.53it/s]

2026-09-09 18:22:47,688 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:47,708 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:47,732 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:47,749 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:47,767 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:47,786 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  12%|█▏        | 2714/22132 [01:01<06:23, 50.68it/s]

2026-09-09 18:22:47,804 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:47,823 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:47,840 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:47,857 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:47,876 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:47,896 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  12%|█▏        | 2720/22132 [01:02<06:14, 51.78it/s]

2026-09-09 18:22:47,916 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:47,933 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:47,951 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:47,969 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:47,987 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:48,003 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  12%|█▏        | 2726/22132 [01:02<06:06, 52.92it/s]

2026-09-09 18:22:48,022 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:48,039 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:48,056 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:48,073 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:48,089 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:48,105 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  12%|█▏        | 2732/22132 [01:02<05:55, 54.51it/s]

2026-09-09 18:22:48,124 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:48,141 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:48,157 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:48,175 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:48,192 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:48,209 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  12%|█▏        | 2738/22132 [01:02<05:49, 55.46it/s]

2026-09-09 18:22:48,228 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:48,245 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:48,261 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:48,277 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:48,295 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:48,313 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  12%|█▏        | 2744/22132 [01:02<05:45, 56.16it/s]

2026-09-09 18:22:48,331 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:48,347 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:22:48,365 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:48,383 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:48,399 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:48,415 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  12%|█▏        | 2750/22132 [01:02<05:40, 56.90it/s]

2026-09-09 18:22:48,433 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:48,450 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:48,467 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:48,485 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:48,503 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:48,525 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  12%|█▏        | 2756/22132 [01:02<05:44, 56.22it/s]

2026-09-09 18:22:48,544 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:48,565 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:48,601 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]
2026-09-09 18:22:48,629 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:22:48,652 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:48,675 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  12%|█▏        | 2762/22132 [01:02<06:26, 50.12it/s]

2026-09-09 18:22:48,699 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:48,719 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:48,738 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:48,758 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:48,781 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:48,805 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  13%|█▎        | 2768/22132 [01:02<06:36, 48.80it/s]

2026-09-09 18:22:48,829 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:48,850 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:48,873 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:48,892 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:48,913 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  13%|█▎        | 2773/22132 [01:03<06:42, 48.11it/s]

2026-09-09 18:22:48,932 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:48,950 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:48,967 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:48,984 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:49,001 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:49,021 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  13%|█▎        | 2779/22132 [01:03<06:25, 50.20it/s]

2026-09-09 18:22:49,038 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:49,055 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:49,072 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:49,089 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:49,105 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:49,123 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  13%|█▎        | 2785/22132 [01:03<06:07, 52.64it/s]

2026-09-09 18:22:49,142 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:49,159 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:49,177 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:49,193 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:49,211 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:49,230 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  13%|█▎        | 2791/22132 [01:03<06:00, 53.67it/s]

2026-09-09 18:22:49,248 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:49,268 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:49,286 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:49,302 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:49,319 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:49,336 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  13%|█▎        | 2797/22132 [01:03<05:54, 54.53it/s]

2026-09-09 18:22:49,354 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:49,372 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:49,388 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:49,405 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:49,421 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:49,440 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  13%|█▎        | 2803/22132 [01:03<05:48, 55.47it/s]

2026-09-09 18:22:49,456 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:49,475 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:49,491 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:49,509 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:49,530 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:49,550 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  13%|█▎        | 2809/22132 [01:03<05:50, 55.18it/s]

2026-09-09 18:22:49,568 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:49,589 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:49,609 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:49,630 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:49,647 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:49,666 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  13%|█▎        | 2815/22132 [01:03<05:57, 53.99it/s]

2026-09-09 18:22:49,684 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:49,700 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:49,718 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:49,735 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:49,752 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:49,769 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  13%|█▎        | 2821/22132 [01:03<05:49, 55.22it/s]

2026-09-09 18:22:49,787 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:49,803 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:49,821 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:49,839 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:49,856 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:49,873 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  13%|█▎        | 2827/22132 [01:04<05:44, 56.02it/s]

2026-09-09 18:22:49,891 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:49,912 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:49,930 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:49,949 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:49,967 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:49,983 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  13%|█▎        | 2833/22132 [01:04<05:47, 55.46it/s]

2026-09-09 18:22:50,005 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:50,028 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:50,047 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:50,064 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:50,081 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:50,098 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  13%|█▎        | 2839/22132 [01:04<05:54, 54.50it/s]

2026-09-09 18:22:50,118 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:50,138 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:50,155 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:50,179 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:50,199 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:50,219 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  13%|█▎        | 2845/22132 [01:04<06:04, 52.98it/s]

2026-09-09 18:22:50,239 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:50,259 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:50,282 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:50,303 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:50,323 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:50,343 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  13%|█▎        | 2851/22132 [01:04<06:15, 51.41it/s]

2026-09-09 18:22:50,365 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:50,385 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:50,406 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:50,427 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:50,446 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:50,465 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  13%|█▎        | 2857/22132 [01:04<06:20, 50.71it/s]

2026-09-09 18:22:50,484 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:50,505 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:50,526 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:50,545 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:50,562 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:50,579 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  13%|█▎        | 2863/22132 [01:04<06:15, 51.37it/s]

2026-09-09 18:22:50,596 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:50,615 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:50,633 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:50,651 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:50,668 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:50,685 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  13%|█▎        | 2869/22132 [01:04<06:04, 52.85it/s]

2026-09-09 18:22:50,704 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:50,723 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:50,743 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:50,762 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:50,785 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:50,808 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  13%|█▎        | 2875/22132 [01:04<06:13, 51.53it/s]

2026-09-09 18:22:50,829 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:50,848 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:50,867 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:50,886 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:50,904 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:50,922 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  13%|█▎        | 2881/22132 [01:05<06:11, 51.86it/s]

2026-09-09 18:22:50,940 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:50,958 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:50,977 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:50,996 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:51,025 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:22:51,046 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  13%|█▎        | 2887/22132 [01:05<06:18, 50.79it/s]

2026-09-09 18:22:51,067 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:51,088 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:51,106 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:51,123 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:51,141 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:51,160 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  13%|█▎        | 2893/22132 [01:05<06:15, 51.26it/s]

2026-09-09 18:22:51,179 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:51,197 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:51,217 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:51,234 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:51,250 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:51,273 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  13%|█▎        | 2899/22132 [01:05<06:11, 51.82it/s]

2026-09-09 18:22:51,296 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:51,315 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:51,336 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:51,354 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:51,371 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:51,389 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  13%|█▎        | 2905/22132 [01:05<06:10, 51.85it/s]

2026-09-09 18:22:51,406 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:51,424 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:51,441 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:51,458 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:51,474 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:51,492 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  13%|█▎        | 2911/22132 [01:05<05:58, 53.59it/s]

2026-09-09 18:22:51,509 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:51,528 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:51,545 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:51,562 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:51,580 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:51,598 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  13%|█▎        | 2917/22132 [01:05<05:52, 54.50it/s]

2026-09-09 18:22:51,617 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:51,636 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:51,652 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:51,669 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:51,687 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:51,705 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  13%|█▎        | 2923/22132 [01:05<05:49, 54.92it/s]

2026-09-09 18:22:51,722 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:51,738 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:51,755 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:51,771 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:51,788 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:51,804 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:51,820 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  13%|█▎        | 2930/22132 [01:05<05:38, 56.66it/s]

2026-09-09 18:22:51,839 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:51,856 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:51,872 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:51,908 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]
2026-09-09 18:22:51,924 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:51,941 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  13%|█▎        | 2936/22132 [01:06<05:52, 54.43it/s]

2026-09-09 18:22:51,959 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:51,977 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:51,995 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:52,013 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:52,030 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:52,048 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  13%|█▎        | 2942/22132 [01:06<05:49, 54.97it/s]

2026-09-09 18:22:52,065 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:52,082 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:52,099 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:52,115 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:52,131 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:52,148 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  13%|█▎        | 2948/22132 [01:06<05:40, 56.33it/s]

2026-09-09 18:22:52,166 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:52,192 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:22:52,211 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:52,229 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:52,248 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:52,265 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  13%|█▎        | 2954/22132 [01:06<05:50, 54.76it/s]

2026-09-09 18:22:52,284 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:52,300 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:52,317 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:52,333 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:52,351 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:52,368 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  13%|█▎        | 2960/22132 [01:06<05:43, 55.75it/s]

2026-09-09 18:22:52,387 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:52,403 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:52,420 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:52,438 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:52,454 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:52,471 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  13%|█▎        | 2966/22132 [01:06<05:39, 56.52it/s]

2026-09-09 18:22:52,489 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:52,505 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:52,522 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:52,539 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:52,557 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:52,575 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  13%|█▎        | 2972/22132 [01:06<05:37, 56.82it/s]

2026-09-09 18:22:52,593 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:52,610 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:52,627 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:52,643 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:52,661 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:52,681 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  13%|█▎        | 2978/22132 [01:06<05:37, 56.72it/s]

2026-09-09 18:22:52,700 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:52,717 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:52,738 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:52,758 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:52,778 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:52,797 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  13%|█▎        | 2984/22132 [01:06<05:47, 55.15it/s]

2026-09-09 18:22:52,817 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:52,838 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:52,862 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:22:52,893 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:22:52,911 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:52,930 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  14%|█▎        | 2990/22132 [01:07<06:10, 51.70it/s]

2026-09-09 18:22:52,950 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:52,969 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:52,987 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:53,006 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:53,027 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:53,048 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  14%|█▎        | 2996/22132 [01:07<06:12, 51.43it/s]

2026-09-09 18:22:53,067 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:53,084 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:53,103 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:53,125 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:53,144 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:53,163 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  14%|█▎        | 3002/22132 [01:07<06:10, 51.67it/s]

2026-09-09 18:22:53,182 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:53,199 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:53,219 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:53,238 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:53,254 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:53,271 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  14%|█▎        | 3008/22132 [01:07<06:02, 52.74it/s]

2026-09-09 18:22:53,289 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:53,307 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:53,329 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:53,349 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:53,366 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:53,383 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  14%|█▎        | 3014/22132 [01:07<06:00, 53.03it/s]

2026-09-09 18:22:53,405 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:53,423 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:53,442 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:53,460 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:53,477 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:53,494 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  14%|█▎        | 3020/22132 [01:07<05:58, 53.32it/s]

2026-09-09 18:22:53,511 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:53,529 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:53,546 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:53,565 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:53,584 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:53,601 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  14%|█▎        | 3026/22132 [01:07<05:53, 54.12it/s]

2026-09-09 18:22:53,620 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:53,637 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:53,652 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:53,669 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:53,686 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:53,704 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  14%|█▎        | 3032/22132 [01:07<05:45, 55.34it/s]

2026-09-09 18:22:53,722 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:53,739 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:53,755 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:53,772 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:53,789 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:53,808 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  14%|█▎        | 3038/22132 [01:07<05:41, 55.94it/s]

2026-09-09 18:22:53,826 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:53,843 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:53,860 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:53,880 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:53,899 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:53,917 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  14%|█▍        | 3044/22132 [01:08<05:43, 55.65it/s]

2026-09-09 18:22:53,935 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:53,960 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:22:53,982 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:53,999 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:54,021 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:54,041 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  14%|█▍        | 3050/22132 [01:08<05:57, 53.35it/s]

2026-09-09 18:22:54,058 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:54,076 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:54,093 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:54,111 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:54,128 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:54,147 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  14%|█▍        | 3056/22132 [01:08<05:51, 54.28it/s]

2026-09-09 18:22:54,165 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:54,184 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:54,202 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:54,222 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:54,241 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:54,259 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  14%|█▍        | 3062/22132 [01:08<05:52, 54.10it/s]

2026-09-09 18:22:54,277 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:54,296 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:54,314 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:54,332 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:54,350 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:54,377 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]

Indexing Records:  14%|█▍        | 3068/22132 [01:08<05:59, 52.96it/s]

2026-09-09 18:22:54,396 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:54,414 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:54,431 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:54,451 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:54,469 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:54,486 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  14%|█▍        | 3074/22132 [01:08<05:55, 53.61it/s]

2026-09-09 18:22:54,505 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:54,528 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:54,546 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:54,564 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:54,582 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:54,599 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  14%|█▍        | 3080/22132 [01:08<05:55, 53.54it/s]

2026-09-09 18:22:54,617 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:54,637 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:54,655 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:54,672 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:54,691 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:54,708 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  14%|█▍        | 3086/22132 [01:08<05:53, 53.88it/s]

2026-09-09 18:22:54,727 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:54,745 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:54,765 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:54,784 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:54,802 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:54,824 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  14%|█▍        | 3092/22132 [01:08<05:57, 53.30it/s]

2026-09-09 18:22:54,845 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:54,863 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:54,881 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:54,902 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:54,923 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:54,943 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  14%|█▍        | 3098/22132 [01:09<06:04, 52.29it/s]

2026-09-09 18:22:54,962 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:54,983 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:55,005 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:55,025 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:55,044 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:55,063 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  14%|█▍        | 3104/22132 [01:09<06:08, 51.68it/s]

2026-09-09 18:22:55,081 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:55,099 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:55,115 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:55,132 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:55,148 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:55,165 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  14%|█▍        | 3110/22132 [01:09<05:54, 53.63it/s]

2026-09-09 18:22:55,183 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:55,199 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:55,215 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:55,235 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:55,252 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:55,269 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  14%|█▍        | 3116/22132 [01:09<05:47, 54.69it/s]

2026-09-09 18:22:55,292 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:55,313 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:55,330 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:55,349 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:55,366 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:55,387 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  14%|█▍        | 3122/22132 [01:09<05:54, 53.59it/s]

2026-09-09 18:22:55,406 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:55,425 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:55,443 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:55,460 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:55,477 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:55,494 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  14%|█▍        | 3128/22132 [01:09<05:50, 54.17it/s]

2026-09-09 18:22:55,511 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:55,530 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:55,547 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:55,572 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:22:55,588 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:55,605 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  14%|█▍        | 3134/22132 [01:09<05:50, 54.23it/s]

2026-09-09 18:22:55,623 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:55,639 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:55,656 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:55,674 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:55,692 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:55,709 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  14%|█▍        | 3140/22132 [01:09<05:43, 55.24it/s]

2026-09-09 18:22:55,727 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:55,744 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:55,760 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:55,780 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:55,799 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:55,818 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  14%|█▍        | 3146/22132 [01:09<05:43, 55.21it/s]

2026-09-09 18:22:55,842 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:55,865 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:55,886 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:55,904 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:55,923 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:55,943 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  14%|█▍        | 3152/22132 [01:10<05:59, 52.78it/s]

2026-09-09 18:22:55,962 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:55,978 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:55,996 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:56,020 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:22:56,040 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:56,059 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  14%|█▍        | 3158/22132 [01:10<06:01, 52.48it/s]

2026-09-09 18:22:56,078 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:56,096 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:56,115 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:56,132 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:56,155 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:56,173 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  14%|█▍        | 3164/22132 [01:10<06:01, 52.48it/s]

2026-09-09 18:22:56,193 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:56,211 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:56,229 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:56,246 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:56,264 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:56,282 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  14%|█▍        | 3170/22132 [01:10<05:55, 53.28it/s]

2026-09-09 18:22:56,301 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:56,319 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:56,337 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:56,356 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:56,373 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:56,391 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  14%|█▍        | 3176/22132 [01:10<05:52, 53.72it/s]

2026-09-09 18:22:56,408 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:56,426 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:56,446 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:56,472 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:22:56,489 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:56,511 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  14%|█▍        | 3182/22132 [01:10<06:00, 52.61it/s]

2026-09-09 18:22:56,530 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:56,547 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:56,564 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:56,585 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:56,602 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:56,618 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  14%|█▍        | 3188/22132 [01:10<05:54, 53.51it/s]

2026-09-09 18:22:56,637 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:56,656 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:56,673 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:56,690 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:56,706 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:56,723 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  14%|█▍        | 3194/22132 [01:10<05:46, 54.69it/s]

2026-09-09 18:22:56,740 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:56,756 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:56,773 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:56,789 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:56,807 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:56,825 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  14%|█▍        | 3200/22132 [01:10<05:39, 55.82it/s]

2026-09-09 18:22:56,843 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:56,862 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:56,880 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:56,897 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:56,913 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:56,931 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  14%|█▍        | 3206/22132 [01:11<05:37, 56.02it/s]

2026-09-09 18:22:56,948 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:56,966 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:56,985 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:57,002 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:57,022 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:57,041 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  15%|█▍        | 3212/22132 [01:11<05:40, 55.54it/s]

2026-09-09 18:22:57,060 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:57,077 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:57,097 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:57,120 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:57,137 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:57,155 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  15%|█▍        | 3218/22132 [01:11<05:45, 54.69it/s]

2026-09-09 18:22:57,172 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:57,189 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:57,207 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:57,225 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:57,243 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:57,260 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  15%|█▍        | 3224/22132 [01:11<05:41, 55.37it/s]

2026-09-09 18:22:57,279 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:57,299 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:57,315 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:57,334 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:57,352 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:57,369 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  15%|█▍        | 3230/22132 [01:11<05:41, 55.29it/s]

2026-09-09 18:22:57,388 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:57,407 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:57,429 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:57,449 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:57,467 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:57,485 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  15%|█▍        | 3236/22132 [01:11<05:48, 54.20it/s]

2026-09-09 18:22:57,502 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:57,519 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:57,536 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:57,553 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:57,569 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:57,586 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  15%|█▍        | 3242/22132 [01:11<05:39, 55.67it/s]

2026-09-09 18:22:57,605 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:57,622 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:57,640 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:57,656 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:57,674 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:57,692 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  15%|█▍        | 3248/22132 [01:11<05:37, 55.95it/s]

2026-09-09 18:22:57,711 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:57,728 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:57,745 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:57,767 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:57,787 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:57,803 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  15%|█▍        | 3254/22132 [01:11<05:41, 55.28it/s]

2026-09-09 18:22:57,821 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:57,837 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:57,856 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:57,875 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:57,895 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:57,912 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  15%|█▍        | 3260/22132 [01:12<05:41, 55.23it/s]

2026-09-09 18:22:57,930 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:57,950 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:57,973 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:57,992 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:58,014 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:58,039 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  15%|█▍        | 3266/22132 [01:12<05:58, 52.62it/s]

2026-09-09 18:22:58,062 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:22:58,082 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:58,099 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:58,118 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:58,135 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:58,152 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  15%|█▍        | 3272/22132 [01:12<05:57, 52.78it/s]

2026-09-09 18:22:58,169 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:58,185 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:58,202 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:58,221 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:58,239 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:58,258 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  15%|█▍        | 3278/22132 [01:12<05:49, 53.87it/s]

2026-09-09 18:22:58,275 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:58,294 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:58,311 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:58,329 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:58,346 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:58,363 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  15%|█▍        | 3284/22132 [01:12<05:43, 54.85it/s]

2026-09-09 18:22:58,381 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:58,399 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:58,417 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:58,438 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:58,456 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:58,476 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  15%|█▍        | 3290/22132 [01:12<05:47, 54.24it/s]

2026-09-09 18:22:58,496 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:58,517 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:58,535 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:58,552 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:58,571 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:58,589 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  15%|█▍        | 3296/22132 [01:12<05:49, 53.93it/s]

2026-09-09 18:22:58,609 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:58,634 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:22:58,653 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:58,672 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:58,690 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:58,707 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  15%|█▍        | 3302/22132 [01:12<05:55, 52.95it/s]

2026-09-09 18:22:58,726 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:58,743 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:58,760 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:58,780 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:58,797 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:58,814 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  15%|█▍        | 3308/22132 [01:12<05:49, 53.80it/s]

2026-09-09 18:22:58,832 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:58,851 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:58,868 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:58,886 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:58,903 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:58,919 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  15%|█▍        | 3314/22132 [01:13<05:43, 54.79it/s]

2026-09-09 18:22:58,937 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:58,954 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:58,971 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:58,989 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:59,007 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:59,028 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  15%|█▌        | 3320/22132 [01:13<05:42, 54.93it/s]

2026-09-09 18:22:59,050 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:22:59,069 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:59,086 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:59,104 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:59,121 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:59,138 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  15%|█▌        | 3326/22132 [01:13<05:43, 54.71it/s]

2026-09-09 18:22:59,159 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:59,175 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:59,192 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:59,208 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:59,225 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:59,242 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  15%|█▌        | 3332/22132 [01:13<05:38, 55.60it/s]

2026-09-09 18:22:59,261 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:59,277 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:59,293 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:22:59,310 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:59,328 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:59,345 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  15%|█▌        | 3338/22132 [01:13<05:33, 56.33it/s]

2026-09-09 18:22:59,366 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:59,383 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:59,401 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:59,419 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:59,439 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:59,457 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  15%|█▌        | 3344/22132 [01:13<05:38, 55.58it/s]

2026-09-09 18:22:59,481 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:22:59,502 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:59,523 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:59,542 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:59,561 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:22:59,579 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  15%|█▌        | 3350/22132 [01:13<05:51, 53.44it/s]

2026-09-09 18:22:59,597 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:59,614 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:59,634 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:22:59,652 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:59,669 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:59,690 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  15%|█▌        | 3356/22132 [01:13<05:49, 53.68it/s]

2026-09-09 18:22:59,716 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:22:59,734 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:59,752 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:59,770 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:59,788 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:59,806 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  15%|█▌        | 3362/22132 [01:13<05:53, 53.07it/s]

2026-09-09 18:22:59,824 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:59,843 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:59,861 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:59,878 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:59,896 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:22:59,915 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  15%|█▌        | 3368/22132 [01:14<05:49, 53.62it/s]

2026-09-09 18:22:59,933 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:22:59,950 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:59,966 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:22:59,986 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:00,028 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.040s]
2026-09-09 18:23:00,063 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]

Indexing Records:  15%|█▌        | 3374/22132 [01:14<06:24, 48.84it/s]

2026-09-09 18:23:00,099 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]
2026-09-09 18:23:00,145 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.045s]
2026-09-09 18:23:00,182 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]
2026-09-09 18:23:00,210 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:23:00,240 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]

Indexing Records:  15%|█▌        | 3379/22132 [01:14<07:37, 40.98it/s]

2026-09-09 18:23:00,265 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:00,288 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:00,318 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:23:00,341 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:00,359 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  15%|█▌        | 3384/22132 [01:14<07:33, 41.30it/s]

2026-09-09 18:23:00,378 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:00,395 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:00,412 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:00,431 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:00,452 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:00,470 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  15%|█▌        | 3390/22132 [01:14<06:59, 44.64it/s]

2026-09-09 18:23:00,490 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:00,509 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:00,529 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:00,548 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:00,567 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:00,585 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  15%|█▌        | 3396/22132 [01:14<06:40, 46.73it/s]

2026-09-09 18:23:00,605 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:00,622 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:00,641 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:00,659 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:00,679 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:00,698 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  15%|█▌        | 3402/22132 [01:14<06:25, 48.61it/s]

2026-09-09 18:23:00,716 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:00,736 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:00,754 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:00,773 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:00,792 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:00,813 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  15%|█▌        | 3408/22132 [01:14<06:23, 48.81it/s]

2026-09-09 18:23:00,842 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:00,862 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:00,886 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:00,908 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:00,936 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  15%|█▌        | 3413/22132 [01:15<06:37, 47.06it/s]

2026-09-09 18:23:00,955 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:00,972 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:00,990 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:01,013 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:01,044 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]

Indexing Records:  15%|█▌        | 3418/22132 [01:15<06:39, 46.80it/s]

2026-09-09 18:23:01,099 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.053s]
2026-09-09 18:23:01,127 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:23:01,159 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:23:01,185 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:23:01,227 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.041s]

Indexing Records:  15%|█▌        | 3423/22132 [01:15<08:00, 38.95it/s]

2026-09-09 18:23:01,268 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.039s]
2026-09-09 18:23:01,311 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.041s]
2026-09-09 18:23:01,349 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.036s]
2026-09-09 18:23:01,379 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:23:01,447 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.067s]

Indexing Records:  15%|█▌        | 3428/22132 [01:15<09:38, 32.32it/s]

2026-09-09 18:23:01,507 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.058s]
2026-09-09 18:23:01,557 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.049s]
2026-09-09 18:23:01,618 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.059s]
2026-09-09 18:23:01,661 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.042s]

Indexing Records:  16%|█▌        | 3432/22132 [01:15<11:22, 27.38it/s]

2026-09-09 18:23:01,709 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.046s]
2026-09-09 18:23:01,758 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.048s]
2026-09-09 18:23:01,840 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.081s]
2026-09-09 18:23:01,912 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.070s]

Indexing Records:  16%|█▌        | 3436/22132 [01:16<13:30, 23.06it/s]

2026-09-09 18:23:01,951 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.037s]
2026-09-09 18:23:02,068 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.116s]
2026-09-09 18:23:02,165 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.096s]

Indexing Records:  16%|█▌        | 3439/22132 [01:16<16:18, 19.10it/s]

2026-09-09 18:23:02,213 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.045s]
2026-09-09 18:23:02,253 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.038s]
2026-09-09 18:23:02,307 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.052s]

Indexing Records:  16%|█▌        | 3442/22132 [01:16<15:55, 19.56it/s]

2026-09-09 18:23:02,362 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.052s]
2026-09-09 18:23:02,476 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.113s]
2026-09-09 18:23:02,644 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.167s]

Indexing Records:  16%|█▌        | 3445/22132 [01:16<20:46, 14.99it/s]

2026-09-09 18:23:02,705 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.058s]
2026-09-09 18:23:02,756 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.049s]

Indexing Records:  16%|█▌        | 3447/22132 [01:16<20:06, 15.49it/s]

2026-09-09 18:23:02,789 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:23:02,815 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:23:02,853 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.036s]
2026-09-09 18:23:02,892 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.038s]

Indexing Records:  16%|█▌        | 3451/22132 [01:17<16:41, 18.65it/s]

2026-09-09 18:23:02,933 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.039s]
2026-09-09 18:23:02,981 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.047s]
2026-09-09 18:23:03,065 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.082s]

Indexing Records:  16%|█▌        | 3454/22132 [01:17<17:02, 18.26it/s]

2026-09-09 18:23:03,112 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.045s]
2026-09-09 18:23:03,142 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:23:03,165 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  16%|█▌        | 3457/22132 [01:17<15:10, 20.52it/s]

2026-09-09 18:23:03,194 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:23:03,265 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.069s]
2026-09-09 18:23:03,328 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.062s]

Indexing Records:  16%|█▌        | 3460/22132 [01:17<15:39, 19.87it/s]

2026-09-09 18:23:03,377 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.046s]
2026-09-09 18:23:03,415 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.037s]
2026-09-09 18:23:03,465 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.048s]

Indexing Records:  16%|█▌        | 3463/22132 [01:17<15:13, 20.44it/s]

2026-09-09 18:23:03,527 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.060s]
2026-09-09 18:23:03,600 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.072s]
2026-09-09 18:23:03,652 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.051s]

Indexing Records:  16%|█▌        | 3466/22132 [01:17<16:27, 18.90it/s]

2026-09-09 18:23:03,686 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:23:03,751 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.064s]
2026-09-09 18:23:03,776 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  16%|█▌        | 3469/22132 [01:17<15:23, 20.22it/s]

2026-09-09 18:23:03,810 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:23:03,837 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:23:03,858 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:03,907 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.047s]

Indexing Records:  16%|█▌        | 3473/22132 [01:18<13:30, 23.03it/s]

2026-09-09 18:23:03,942 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:23:03,968 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:23:03,989 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:04,013 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  16%|█▌        | 3477/22132 [01:18<11:43, 26.52it/s]

2026-09-09 18:23:04,043 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:23:04,063 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:04,093 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:23:04,120 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]

Indexing Records:  16%|█▌        | 3481/22132 [01:18<10:35, 29.36it/s]

2026-09-09 18:23:04,141 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:04,162 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:04,187 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:23:04,213 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:23:04,284 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.070s]

Indexing Records:  16%|█▌        | 3486/22132 [01:18<10:27, 29.71it/s]

2026-09-09 18:23:04,332 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.045s]
2026-09-09 18:23:04,366 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:23:04,391 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:23:04,421 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]

Indexing Records:  16%|█▌        | 3490/22132 [01:18<10:30, 29.58it/s]

2026-09-09 18:23:04,457 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]
2026-09-09 18:23:04,517 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.058s]
2026-09-09 18:23:04,537 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:04,562 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  16%|█▌        | 3494/22132 [01:18<10:37, 29.24it/s]

2026-09-09 18:23:04,584 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:04,605 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:04,629 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:04,654 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:23:04,677 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  16%|█▌        | 3499/22132 [01:18<09:25, 32.93it/s]

2026-09-09 18:23:04,701 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:04,723 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:04,755 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:23:04,777 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:04,798 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  16%|█▌        | 3504/22132 [01:18<08:47, 35.31it/s]

2026-09-09 18:23:04,819 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:04,841 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:04,866 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:23:04,892 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:23:04,913 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  16%|█▌        | 3509/22132 [01:19<08:14, 37.64it/s]

2026-09-09 18:23:04,943 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:23:05,071 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.127s]
2026-09-09 18:23:05,093 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:05,113 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  16%|█▌        | 3513/22132 [01:19<10:12, 30.41it/s]

2026-09-09 18:23:05,132 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:05,158 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:23:05,176 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:05,197 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:05,219 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  16%|█▌        | 3518/22132 [01:19<09:02, 34.33it/s]

2026-09-09 18:23:05,249 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:23:05,285 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]
2026-09-09 18:23:05,337 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.051s]
2026-09-09 18:23:05,371 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]

Indexing Records:  16%|█▌        | 3522/22132 [01:19<09:46, 31.75it/s]

2026-09-09 18:23:05,398 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:23:05,427 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:23:05,447 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:05,483 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]

Indexing Records:  16%|█▌        | 3526/22132 [01:19<09:28, 32.75it/s]

2026-09-09 18:23:05,523 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.038s]
2026-09-09 18:23:05,547 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:23:05,569 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:05,596 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]

Indexing Records:  16%|█▌        | 3530/22132 [01:19<09:15, 33.48it/s]

2026-09-09 18:23:05,615 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:05,652 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.036s]
2026-09-09 18:23:05,671 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:05,692 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:05,713 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  16%|█▌        | 3535/22132 [01:19<08:34, 36.13it/s]

2026-09-09 18:23:05,751 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.036s]
2026-09-09 18:23:05,812 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.060s]
2026-09-09 18:23:05,844 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:23:05,872 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]

Indexing Records:  16%|█▌        | 3539/22132 [01:20<09:37, 32.21it/s]

2026-09-09 18:23:05,905 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:23:05,934 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:23:05,963 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:23:06,001 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.036s]

Indexing Records:  16%|█▌        | 3543/22132 [01:20<09:43, 31.87it/s]

2026-09-09 18:23:06,027 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:23:06,052 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:23:06,079 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:23:06,099 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:06,121 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  16%|█▌        | 3548/22132 [01:20<08:57, 34.56it/s]

2026-09-09 18:23:06,140 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:06,158 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:06,187 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:23:06,210 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:06,229 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  16%|█▌        | 3553/22132 [01:20<08:12, 37.73it/s]

2026-09-09 18:23:06,249 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:06,269 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:06,289 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:06,304 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:23:06,345 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.040s]

Indexing Records:  16%|█▌        | 3558/22132 [01:20<07:53, 39.22it/s]

2026-09-09 18:23:06,363 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:06,380 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:06,399 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:06,422 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:06,442 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:06,463 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  16%|█▌        | 3564/22132 [01:20<07:14, 42.73it/s]

2026-09-09 18:23:06,489 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:23:06,511 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:06,542 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:23:06,571 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:23:06,604 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]

Indexing Records:  16%|█▌        | 3569/22132 [01:20<07:41, 40.25it/s]

2026-09-09 18:23:06,632 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:23:06,662 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:23:06,680 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:06,701 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:06,717 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  16%|█▌        | 3574/22132 [01:20<07:28, 41.37it/s]

2026-09-09 18:23:06,736 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:06,761 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:23:06,780 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:06,796 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:06,813 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:06,832 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  16%|█▌        | 3580/22132 [01:20<06:56, 44.52it/s]

2026-09-09 18:23:06,849 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:06,868 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:06,882 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:23:06,897 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:23:06,915 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:06,934 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  16%|█▌        | 3586/22132 [01:21<06:23, 48.31it/s]

2026-09-09 18:23:06,952 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:06,972 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:06,987 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:23:07,005 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:07,028 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:07,045 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  16%|█▌        | 3592/22132 [01:21<06:11, 49.91it/s]

2026-09-09 18:23:07,065 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:07,080 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:23:07,098 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:07,121 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:07,137 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:07,155 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  16%|█▋        | 3598/22132 [01:21<06:01, 51.26it/s]

2026-09-09 18:23:07,174 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:07,190 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:07,205 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:23:07,221 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:07,246 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:23:07,262 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  16%|█▋        | 3604/22132 [01:21<05:51, 52.74it/s]

2026-09-09 18:23:07,280 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:07,304 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:23:07,321 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:07,339 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:07,355 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:07,371 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  16%|█▋        | 3610/22132 [01:21<05:47, 53.37it/s]

2026-09-09 18:23:07,388 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:23:07,404 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:07,423 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:07,440 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:07,455 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:23:07,471 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:23:07,486 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  16%|█▋        | 3617/22132 [01:21<05:32, 55.65it/s]

2026-09-09 18:23:07,502 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:23:07,517 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:23:07,534 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:07,551 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:07,565 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:23:07,579 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]
2026-09-09 18:23:07,593 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]

Indexing Records:  16%|█▋        | 3624/22132 [01:21<05:16, 58.56it/s]

2026-09-09 18:23:07,609 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:23:07,623 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:23:07,638 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:23:07,652 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:23:07,667 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:23:07,681 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:23:07,696 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]

Indexing Records:  16%|█▋        | 3631/22132 [01:21<05:01, 61.31it/s]

2026-09-09 18:23:07,711 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:23:07,732 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:07,748 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:23:07,765 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:07,783 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:07,797 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:23:07,813 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  16%|█▋        | 3638/22132 [01:21<05:04, 60.81it/s]

2026-09-09 18:23:07,832 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:07,855 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:07,873 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:07,897 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:07,913 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:23:07,929 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:07,943 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]

Indexing Records:  16%|█▋        | 3645/22132 [01:22<05:16, 58.44it/s]

2026-09-09 18:23:07,958 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:23:07,972 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]
2026-09-09 18:23:07,987 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:23:08,002 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:23:08,018 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:08,035 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:08,052 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  17%|█▋        | 3652/22132 [01:22<05:07, 60.17it/s]

2026-09-09 18:23:08,068 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:23:08,084 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:08,099 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:23:08,116 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:08,132 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:23:08,150 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:08,166 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  17%|█▋        | 3659/22132 [01:22<05:05, 60.49it/s]

2026-09-09 18:23:08,183 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:23:08,196 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:23:08,211 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:23:08,227 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:08,242 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:23:08,258 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:23:08,273 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  17%|█▋        | 3666/22132 [01:22<04:58, 61.84it/s]

2026-09-09 18:23:08,288 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:23:08,306 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:08,325 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:08,342 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:08,358 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:08,374 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:08,390 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  17%|█▋        | 3673/22132 [01:22<05:00, 61.34it/s]

2026-09-09 18:23:08,409 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:08,425 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:23:08,443 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:08,461 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:08,477 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:08,494 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:08,510 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  17%|█▋        | 3680/22132 [01:22<05:05, 60.33it/s]

2026-09-09 18:23:08,528 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:08,547 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:08,564 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:08,581 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:08,597 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:23:08,611 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:23:08,627 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  17%|█▋        | 3687/22132 [01:22<05:06, 60.20it/s]

2026-09-09 18:23:08,644 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:08,661 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:08,680 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:08,699 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:08,718 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:08,737 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:08,751 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]

Indexing Records:  17%|█▋        | 3694/22132 [01:22<05:12, 58.96it/s]

2026-09-09 18:23:08,772 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:08,790 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:08,807 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:08,821 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:23:08,837 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:23:08,853 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  17%|█▋        | 3700/22132 [01:22<05:12, 59.01it/s]

2026-09-09 18:23:08,869 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:23:08,887 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:08,902 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:23:08,917 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:23:08,932 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:23:08,947 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:23:08,962 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  17%|█▋        | 3707/22132 [01:23<05:04, 60.46it/s]

2026-09-09 18:23:08,978 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:23:08,992 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:23:09,008 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:23:09,023 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:23:09,041 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:09,058 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:09,073 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  17%|█▋        | 3714/22132 [01:23<05:00, 61.34it/s]

2026-09-09 18:23:09,090 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:09,105 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:23:09,121 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:09,139 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:09,156 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:09,172 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:23:09,187 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  17%|█▋        | 3721/22132 [01:23<05:00, 61.33it/s]

2026-09-09 18:23:09,203 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:23:09,220 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:09,236 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:23:09,251 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:23:09,266 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:23:09,281 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:23:09,299 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  17%|█▋        | 3728/22132 [01:23<04:58, 61.69it/s]

2026-09-09 18:23:09,316 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:09,334 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:09,357 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:09,375 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:09,393 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:09,409 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:09,432 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  17%|█▋        | 3735/22132 [01:23<05:14, 58.58it/s]

2026-09-09 18:23:09,453 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:09,473 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:09,491 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:09,508 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:09,526 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:09,545 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  17%|█▋        | 3741/22132 [01:23<05:22, 56.95it/s]

2026-09-09 18:23:09,566 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:09,584 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:09,600 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:09,617 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:09,634 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:09,652 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  17%|█▋        | 3747/22132 [01:23<05:23, 56.77it/s]

2026-09-09 18:23:09,672 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:09,692 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:09,711 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:09,731 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:09,749 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:09,766 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  17%|█▋        | 3753/22132 [01:23<05:31, 55.46it/s]

2026-09-09 18:23:09,789 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:09,808 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:09,826 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:09,844 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:09,863 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:09,883 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  17%|█▋        | 3759/22132 [01:24<05:38, 54.30it/s]

2026-09-09 18:23:09,902 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:09,924 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:09,947 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:09,975 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:23:10,011 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]
2026-09-09 18:23:10,039 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]

Indexing Records:  17%|█▋        | 3765/22132 [01:24<06:19, 48.44it/s]

2026-09-09 18:23:10,059 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:10,079 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:10,102 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:10,120 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:10,138 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:10,162 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  17%|█▋        | 3771/22132 [01:24<06:18, 48.54it/s]

2026-09-09 18:23:10,185 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:10,202 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:10,221 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:10,239 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:10,257 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:10,278 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  17%|█▋        | 3777/22132 [01:24<06:11, 49.38it/s]

2026-09-09 18:23:10,297 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:10,321 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:10,340 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:10,359 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:10,376 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:10,393 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  17%|█▋        | 3783/22132 [01:24<06:05, 50.24it/s]

2026-09-09 18:23:10,411 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:10,430 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:10,448 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:10,465 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:10,482 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:10,500 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  17%|█▋        | 3789/22132 [01:24<05:53, 51.90it/s]

2026-09-09 18:23:10,520 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:10,538 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:10,558 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:10,579 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:10,599 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:10,621 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  17%|█▋        | 3795/22132 [01:24<05:58, 51.13it/s]

2026-09-09 18:23:10,641 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:10,658 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:10,676 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:10,693 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:10,717 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:23:10,741 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  17%|█▋        | 3801/22132 [01:24<06:01, 50.74it/s]

2026-09-09 18:23:10,760 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:10,779 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:10,800 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:10,817 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:10,835 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:10,851 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  17%|█▋        | 3807/22132 [01:24<05:53, 51.91it/s]

2026-09-09 18:23:10,870 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:10,888 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:10,906 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:10,924 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:10,943 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:10,960 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  17%|█▋        | 3813/22132 [01:25<05:46, 52.80it/s]

2026-09-09 18:23:10,980 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:10,999 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:11,022 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:11,044 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:11,063 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:11,084 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  17%|█▋        | 3819/22132 [01:25<05:56, 51.42it/s]

2026-09-09 18:23:11,102 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:11,122 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:11,143 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:11,161 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:11,184 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:11,205 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  17%|█▋        | 3825/22132 [01:25<06:00, 50.84it/s]

2026-09-09 18:23:11,227 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:11,254 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:23:11,277 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:11,298 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:11,319 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:11,339 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  17%|█▋        | 3831/22132 [01:25<06:15, 48.79it/s]

2026-09-09 18:23:11,360 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:11,387 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:23:11,407 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:11,425 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:11,446 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  17%|█▋        | 3836/22132 [01:25<06:18, 48.29it/s]

2026-09-09 18:23:11,469 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:11,493 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:23:11,517 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:11,541 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:23:11,563 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  17%|█▋        | 3841/22132 [01:25<06:32, 46.54it/s]

2026-09-09 18:23:11,586 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:11,602 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:11,621 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:11,640 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:11,659 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:11,678 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  17%|█▋        | 3847/22132 [01:25<06:19, 48.23it/s]

2026-09-09 18:23:11,697 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:11,717 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:11,740 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:11,765 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:23:11,786 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  17%|█▋        | 3852/22132 [01:25<06:23, 47.72it/s]

2026-09-09 18:23:11,808 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:11,830 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:11,851 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:11,869 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:11,886 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  17%|█▋        | 3857/22132 [01:26<06:18, 48.33it/s]

2026-09-09 18:23:11,906 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:11,927 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:11,944 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:11,961 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:11,979 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:12,006 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]

Indexing Records:  17%|█▋        | 3863/22132 [01:26<06:14, 48.84it/s]

2026-09-09 18:23:12,030 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:12,046 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:12,064 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:12,082 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:12,100 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:12,117 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  17%|█▋        | 3869/22132 [01:26<06:02, 50.39it/s]

2026-09-09 18:23:12,135 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:12,154 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:12,172 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:12,189 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:12,207 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:12,226 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  18%|█▊        | 3875/22132 [01:26<05:52, 51.83it/s]

2026-09-09 18:23:12,243 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:12,260 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:12,279 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:12,296 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:12,314 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:12,330 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  18%|█▊        | 3881/22132 [01:26<05:41, 53.40it/s]

2026-09-09 18:23:12,348 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:12,368 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:12,385 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:12,402 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:12,420 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:12,438 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  18%|█▊        | 3887/22132 [01:26<05:37, 54.06it/s]

2026-09-09 18:23:12,455 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:12,473 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:12,490 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:12,507 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:12,523 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:12,543 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  18%|█▊        | 3893/22132 [01:26<05:31, 55.04it/s]

2026-09-09 18:23:12,561 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:12,581 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:12,601 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:12,620 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:12,638 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:12,660 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  18%|█▊        | 3899/22132 [01:26<05:38, 53.84it/s]

2026-09-09 18:23:12,680 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:12,701 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:12,719 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:12,739 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:12,759 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:12,781 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  18%|█▊        | 3905/22132 [01:26<05:47, 52.48it/s]

2026-09-09 18:23:12,804 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:12,826 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:12,846 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:12,865 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:12,885 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:12,908 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  18%|█▊        | 3911/22132 [01:27<05:59, 50.73it/s]

2026-09-09 18:23:12,929 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:12,946 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:12,965 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:12,986 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:13,009 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:13,030 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  18%|█▊        | 3917/22132 [01:27<06:01, 50.32it/s]

2026-09-09 18:23:13,049 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:13,070 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:13,091 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:13,110 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:13,127 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:13,146 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  18%|█▊        | 3923/22132 [01:27<05:59, 50.69it/s]

2026-09-09 18:23:13,166 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:13,185 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:13,202 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:13,220 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:13,237 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:13,257 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  18%|█▊        | 3929/22132 [01:27<05:52, 51.64it/s]

2026-09-09 18:23:13,279 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:13,296 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:13,316 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:13,335 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:13,355 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:13,373 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  18%|█▊        | 3935/22132 [01:27<05:51, 51.72it/s]

2026-09-09 18:23:13,391 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:13,411 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:13,436 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:23:13,455 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:13,480 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:23:13,502 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  18%|█▊        | 3941/22132 [01:27<06:03, 50.05it/s]

2026-09-09 18:23:13,525 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:13,548 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:13,569 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:13,586 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:13,604 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:13,622 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  18%|█▊        | 3947/22132 [01:27<06:03, 50.05it/s]

2026-09-09 18:23:13,638 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:13,654 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:13,672 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:13,691 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:13,710 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:13,728 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  18%|█▊        | 3953/22132 [01:27<05:51, 51.77it/s]

2026-09-09 18:23:13,747 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:13,766 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:13,785 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:13,802 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:13,820 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:13,838 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  18%|█▊        | 3959/22132 [01:27<05:45, 52.62it/s]

2026-09-09 18:23:13,855 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:13,876 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:13,900 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:13,924 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:13,946 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:13,963 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  18%|█▊        | 3965/22132 [01:28<05:54, 51.19it/s]

2026-09-09 18:23:13,981 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:13,997 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:14,019 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:14,045 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:23:14,076 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:23:14,095 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  18%|█▊        | 3971/22132 [01:28<06:08, 49.32it/s]

2026-09-09 18:23:14,113 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:14,129 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:14,147 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:14,166 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:14,183 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:14,200 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  18%|█▊        | 3977/22132 [01:28<05:53, 51.35it/s]

2026-09-09 18:23:14,220 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:14,239 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:14,258 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:14,279 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:14,297 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:14,316 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  18%|█▊        | 3983/22132 [01:28<05:52, 51.47it/s]

2026-09-09 18:23:14,339 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:14,359 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:14,387 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:23:14,407 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:14,428 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:14,448 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  18%|█▊        | 3989/22132 [01:28<06:06, 49.50it/s]

2026-09-09 18:23:14,468 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:14,488 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:14,505 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:14,523 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:14,541 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:14,558 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  18%|█▊        | 3995/22132 [01:28<05:55, 50.96it/s]

2026-09-09 18:23:14,579 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:14,600 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:14,621 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:14,641 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:14,664 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:14,684 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  18%|█▊        | 4001/22132 [01:28<06:03, 49.91it/s]

2026-09-09 18:23:14,703 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:14,727 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:14,746 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:14,766 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:14,785 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:14,805 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  18%|█▊        | 4007/22132 [01:28<06:03, 49.81it/s]

2026-09-09 18:23:14,826 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:14,846 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:14,865 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:14,884 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:14,903 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:14,920 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  18%|█▊        | 4013/22132 [01:29<05:59, 50.41it/s]

2026-09-09 18:23:14,940 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:14,960 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:14,981 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:15,002 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:15,025 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:15,045 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  18%|█▊        | 4019/22132 [01:29<06:04, 49.71it/s]

2026-09-09 18:23:15,070 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:23:15,088 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:15,108 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:15,125 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:15,144 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:15,160 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  18%|█▊        | 4025/22132 [01:29<05:59, 50.41it/s]

2026-09-09 18:23:15,178 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:15,195 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:15,211 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:15,228 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:15,245 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:15,263 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  18%|█▊        | 4031/22132 [01:29<05:44, 52.57it/s]

2026-09-09 18:23:15,282 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:15,300 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:15,320 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:15,339 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:15,356 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:15,373 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  18%|█▊        | 4037/22132 [01:29<05:40, 53.18it/s]

2026-09-09 18:23:15,391 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:15,407 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:15,424 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:15,442 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:15,460 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:15,477 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  18%|█▊        | 4043/22132 [01:29<05:32, 54.38it/s]

2026-09-09 18:23:15,496 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:15,513 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:15,534 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:15,553 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:15,571 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:15,596 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  18%|█▊        | 4049/22132 [01:29<05:40, 53.15it/s]

2026-09-09 18:23:15,616 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:15,634 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:15,653 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:15,672 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:15,690 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:15,708 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  18%|█▊        | 4055/22132 [01:29<05:39, 53.28it/s]

2026-09-09 18:23:15,725 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:15,743 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:15,759 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:15,776 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:15,795 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:15,813 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  18%|█▊        | 4061/22132 [01:29<05:32, 54.38it/s]

2026-09-09 18:23:15,831 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:15,857 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:23:15,877 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:15,898 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:15,919 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:15,943 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  18%|█▊        | 4067/22132 [01:30<05:49, 51.68it/s]

2026-09-09 18:23:15,962 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:15,981 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:15,999 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:16,020 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:16,039 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:16,055 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  18%|█▊        | 4073/22132 [01:30<05:46, 52.18it/s]

2026-09-09 18:23:16,073 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:16,092 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:16,117 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:23:16,137 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:16,155 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:16,175 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  18%|█▊        | 4079/22132 [01:30<05:50, 51.55it/s]

2026-09-09 18:23:16,197 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:16,221 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:23:16,239 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:16,262 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:16,280 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:16,297 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  18%|█▊        | 4085/22132 [01:30<05:55, 50.74it/s]

2026-09-09 18:23:16,316 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:16,333 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:16,350 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:16,370 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:16,388 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:16,405 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  18%|█▊        | 4091/22132 [01:30<05:46, 52.12it/s]

2026-09-09 18:23:16,422 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:16,440 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:16,459 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:16,475 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:16,492 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:16,509 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  19%|█▊        | 4097/22132 [01:30<05:36, 53.61it/s]

2026-09-09 18:23:16,527 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:16,545 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:16,562 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:16,579 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:16,604 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:23:16,625 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  19%|█▊        | 4103/22132 [01:30<05:39, 53.08it/s]

2026-09-09 18:23:16,643 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:16,662 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:16,679 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:16,695 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:16,714 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:16,735 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  19%|█▊        | 4109/22132 [01:30<05:36, 53.51it/s]

2026-09-09 18:23:16,756 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:16,776 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:16,795 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:16,813 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:16,830 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:16,846 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  19%|█▊        | 4115/22132 [01:30<05:35, 53.68it/s]

2026-09-09 18:23:16,866 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:16,885 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:16,903 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:16,921 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:16,939 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:16,956 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  19%|█▊        | 4121/22132 [01:31<05:33, 53.99it/s]

2026-09-09 18:23:16,974 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:16,990 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:17,007 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:17,026 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:17,043 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:17,061 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  19%|█▊        | 4127/22132 [01:31<05:28, 54.88it/s]

2026-09-09 18:23:17,080 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:17,101 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:17,127 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:23:17,152 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:23:17,178 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:23:17,196 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  19%|█▊        | 4133/22132 [01:31<05:51, 51.27it/s]

2026-09-09 18:23:17,214 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:17,231 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:17,247 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:17,266 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:17,284 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:17,301 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  19%|█▊        | 4139/22132 [01:31<05:40, 52.81it/s]

2026-09-09 18:23:17,319 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:17,336 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:17,353 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:17,370 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:17,391 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:17,409 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  19%|█▊        | 4145/22132 [01:31<05:35, 53.63it/s]

2026-09-09 18:23:17,433 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:17,451 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:17,468 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:17,485 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:17,503 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:17,522 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  19%|█▉        | 4151/22132 [01:31<05:36, 53.50it/s]

2026-09-09 18:23:17,541 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:17,560 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:17,578 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:17,595 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:17,611 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:17,627 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  19%|█▉        | 4157/22132 [01:31<05:29, 54.50it/s]

2026-09-09 18:23:17,648 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:17,670 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:17,688 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:17,707 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:17,725 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:17,741 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  19%|█▉        | 4163/22132 [01:31<05:33, 53.94it/s]

2026-09-09 18:23:17,759 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:17,776 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:17,795 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:17,814 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:17,832 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:17,850 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  19%|█▉        | 4169/22132 [01:31<05:30, 54.38it/s]

2026-09-09 18:23:17,873 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:17,892 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:17,939 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.046s]
2026-09-09 18:23:17,967 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:23:17,989 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:18,011 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  19%|█▉        | 4175/22132 [01:32<06:16, 47.71it/s]

2026-09-09 18:23:18,035 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:18,056 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:18,076 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:18,097 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:18,117 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  19%|█▉        | 4180/22132 [01:32<06:16, 47.63it/s]

2026-09-09 18:23:18,141 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:18,161 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:18,182 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:18,202 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:18,223 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  19%|█▉        | 4185/22132 [01:32<06:17, 47.50it/s]

2026-09-09 18:23:18,243 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:18,263 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:18,282 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:18,307 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:23:18,348 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.040s]

Indexing Records:  19%|█▉        | 4190/22132 [01:32<06:37, 45.13it/s]

2026-09-09 18:23:18,373 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:23:18,406 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:23:18,439 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:23:18,460 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:18,480 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  19%|█▉        | 4195/22132 [01:32<06:59, 42.72it/s]

2026-09-09 18:23:18,504 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:18,524 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:18,546 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:18,566 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:18,593 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]

Indexing Records:  19%|█▉        | 4200/22132 [01:32<06:55, 43.18it/s]

2026-09-09 18:23:18,615 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:18,640 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:23:18,662 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:18,685 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:18,711 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  19%|█▉        | 4205/22132 [01:32<06:56, 43.00it/s]

2026-09-09 18:23:18,738 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:23:18,762 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:18,793 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:23:18,816 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:18,836 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  19%|█▉        | 4210/22132 [01:32<07:06, 41.99it/s]

2026-09-09 18:23:18,859 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:18,879 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:18,900 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:18,923 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:18,945 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  19%|█▉        | 4215/22132 [01:33<06:55, 43.16it/s]

2026-09-09 18:23:18,978 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:23:19,001 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:19,023 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:19,048 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:23:19,069 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  19%|█▉        | 4220/22132 [01:33<07:03, 42.26it/s]

2026-09-09 18:23:19,178 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.107s]
2026-09-09 18:23:19,200 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:19,218 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:19,236 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:19,255 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  19%|█▉        | 4225/22132 [01:33<08:16, 36.05it/s]

2026-09-09 18:23:19,276 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:19,297 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:19,318 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:19,339 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:19,359 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  19%|█▉        | 4230/22132 [01:33<07:39, 39.00it/s]

2026-09-09 18:23:19,379 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:19,399 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:19,419 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:19,439 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:19,462 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  19%|█▉        | 4235/22132 [01:33<07:11, 41.45it/s]

2026-09-09 18:23:19,482 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:19,500 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:19,521 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:19,549 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:23:19,570 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  19%|█▉        | 4240/22132 [01:33<06:58, 42.79it/s]

2026-09-09 18:23:19,589 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:19,609 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:19,628 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:19,649 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:19,670 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:19,688 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  19%|█▉        | 4246/22132 [01:33<06:36, 45.16it/s]

2026-09-09 18:23:19,710 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:19,732 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:19,751 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:19,769 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:19,788 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:19,805 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  19%|█▉        | 4252/22132 [01:33<06:19, 47.06it/s]

2026-09-09 18:23:19,822 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:19,839 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:19,856 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:19,873 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:19,893 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:19,912 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  19%|█▉        | 4258/22132 [01:34<06:00, 49.62it/s]

2026-09-09 18:23:19,930 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:19,951 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:19,969 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:19,987 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:20,006 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:20,034 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]

Indexing Records:  19%|█▉        | 4264/22132 [01:34<06:01, 49.42it/s]

2026-09-09 18:23:20,052 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:20,070 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:20,090 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:20,111 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:20,128 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:20,145 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  19%|█▉        | 4270/22132 [01:34<05:52, 50.73it/s]

2026-09-09 18:23:20,169 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:20,190 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:20,213 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:20,234 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:20,250 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:20,267 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  19%|█▉        | 4276/22132 [01:34<05:55, 50.24it/s]

2026-09-09 18:23:20,287 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:20,308 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:20,331 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:20,350 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:20,368 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:20,387 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  19%|█▉        | 4282/22132 [01:34<05:55, 50.16it/s]

2026-09-09 18:23:20,405 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:20,424 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:20,444 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:20,462 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:20,481 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:20,498 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  19%|█▉        | 4288/22132 [01:34<05:47, 51.35it/s]

2026-09-09 18:23:20,518 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:20,536 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:20,558 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:20,575 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:20,591 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:20,608 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  19%|█▉        | 4294/22132 [01:34<05:41, 52.23it/s]

2026-09-09 18:23:20,627 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:20,646 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:20,664 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:20,682 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:20,699 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:20,715 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  19%|█▉        | 4300/22132 [01:34<05:34, 53.32it/s]

2026-09-09 18:23:20,736 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:20,754 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:20,772 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:20,793 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:20,814 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:20,842 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]

Indexing Records:  19%|█▉        | 4306/22132 [01:34<05:46, 51.41it/s]

2026-09-09 18:23:20,864 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:20,890 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:23:20,921 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:23:20,959 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.037s]
2026-09-09 18:23:21,002 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.042s]
2026-09-09 18:23:21,024 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  19%|█▉        | 4312/22132 [01:35<06:45, 43.98it/s]

2026-09-09 18:23:21,044 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:21,063 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:21,085 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:21,111 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:23:21,133 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  20%|█▉        | 4317/22132 [01:35<06:40, 44.51it/s]

2026-09-09 18:23:21,153 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:21,176 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:21,200 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:21,228 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:23:21,248 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  20%|█▉        | 4322/22132 [01:35<06:42, 44.20it/s]

2026-09-09 18:23:21,267 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:21,286 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:21,304 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:21,320 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:21,339 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:21,355 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  20%|█▉        | 4328/22132 [01:35<06:16, 47.33it/s]

2026-09-09 18:23:21,374 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:21,392 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:21,410 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:21,426 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:21,445 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:21,464 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  20%|█▉        | 4334/22132 [01:35<05:59, 49.53it/s]

2026-09-09 18:23:21,483 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:21,499 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:21,516 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:21,535 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:21,552 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:21,570 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  20%|█▉        | 4340/22132 [01:35<05:44, 51.61it/s]

2026-09-09 18:23:21,588 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:21,608 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:21,626 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:21,644 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:21,662 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:21,680 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  20%|█▉        | 4346/22132 [01:35<05:39, 52.43it/s]

2026-09-09 18:23:21,699 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:21,722 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:21,744 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:21,763 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:21,782 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:21,801 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  20%|█▉        | 4352/22132 [01:35<05:44, 51.57it/s]

2026-09-09 18:23:21,819 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:21,836 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:21,854 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:21,875 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:21,893 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:21,916 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  20%|█▉        | 4358/22132 [01:36<05:43, 51.67it/s]

2026-09-09 18:23:21,935 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:21,956 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:21,975 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:21,992 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:22,009 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:22,027 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  20%|█▉        | 4364/22132 [01:36<05:39, 52.38it/s]

2026-09-09 18:23:22,049 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:22,069 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:22,088 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:22,106 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:22,123 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:22,140 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  20%|█▉        | 4370/22132 [01:36<05:37, 52.62it/s]

2026-09-09 18:23:22,158 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:22,176 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:22,194 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:22,213 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:22,235 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:22,267 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]

Indexing Records:  20%|█▉        | 4376/22132 [01:36<05:49, 50.87it/s]

2026-09-09 18:23:22,292 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:23:22,310 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:22,328 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:22,347 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:22,365 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:22,383 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  20%|█▉        | 4382/22132 [01:36<05:47, 51.14it/s]

2026-09-09 18:23:22,404 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:22,423 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:22,447 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:22,467 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:22,485 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:22,503 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  20%|█▉        | 4388/22132 [01:36<05:49, 50.82it/s]

2026-09-09 18:23:22,521 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:22,538 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:22,559 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:22,580 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:22,603 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:22,621 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  20%|█▉        | 4394/22132 [01:36<05:49, 50.71it/s]

2026-09-09 18:23:22,639 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:22,657 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:22,675 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:22,693 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:22,711 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:22,729 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  20%|█▉        | 4400/22132 [01:36<05:40, 52.14it/s]

2026-09-09 18:23:22,747 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:22,765 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:22,782 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:22,801 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:22,818 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:22,835 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  20%|█▉        | 4406/22132 [01:36<05:32, 53.36it/s]

2026-09-09 18:23:22,857 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:22,880 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:22,897 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:22,916 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:22,934 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:22,952 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  20%|█▉        | 4412/22132 [01:37<05:35, 52.84it/s]

2026-09-09 18:23:22,968 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:22,984 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:23,004 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:23,026 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:23,046 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:23,069 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  20%|█▉        | 4418/22132 [01:37<05:38, 52.36it/s]

2026-09-09 18:23:23,092 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:23,114 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:23,132 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:23,151 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:23,171 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:23,194 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  20%|█▉        | 4424/22132 [01:37<05:48, 50.87it/s]

2026-09-09 18:23:23,212 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:23,231 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:23,251 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:23,269 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:23,313 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.042s]
2026-09-09 18:23:23,345 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]

Indexing Records:  20%|██        | 4430/22132 [01:37<06:16, 46.98it/s]

2026-09-09 18:23:23,364 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:23,387 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:23,408 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:23,429 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:23,452 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  20%|██        | 4435/22132 [01:37<06:17, 46.89it/s]

2026-09-09 18:23:23,473 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:23,493 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:23,514 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:23,537 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:23,559 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  20%|██        | 4440/22132 [01:37<06:17, 46.87it/s]

2026-09-09 18:23:23,580 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:23,598 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:23,620 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:23,639 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:23,661 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  20%|██        | 4445/22132 [01:37<06:12, 47.47it/s]

2026-09-09 18:23:23,685 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:23,703 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:23,721 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:23,737 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:23,754 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:23,773 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  20%|██        | 4451/22132 [01:37<05:59, 49.23it/s]

2026-09-09 18:23:23,795 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:23,815 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:23,834 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:23,858 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:23,877 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  20%|██        | 4456/22132 [01:38<06:01, 48.94it/s]

2026-09-09 18:23:23,901 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:23,924 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:23,947 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:23,964 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:23,984 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  20%|██        | 4461/22132 [01:38<06:05, 48.33it/s]

2026-09-09 18:23:24,005 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:24,028 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:24,047 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:24,065 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:24,083 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:24,111 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]

Indexing Records:  20%|██        | 4467/22132 [01:38<06:09, 47.87it/s]

2026-09-09 18:23:24,144 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:23:24,165 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:24,188 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:24,222 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]
2026-09-09 18:23:24,242 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  20%|██        | 4472/22132 [01:38<06:34, 44.73it/s]

2026-09-09 18:23:24,264 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:24,286 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:24,309 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:24,339 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:23:24,361 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  20%|██        | 4477/22132 [01:38<06:42, 43.87it/s]

2026-09-09 18:23:24,382 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:24,400 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:24,420 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:24,441 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:24,461 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  20%|██        | 4482/22132 [01:38<06:28, 45.48it/s]

2026-09-09 18:23:24,485 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:24,506 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:24,527 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:24,550 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:24,572 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  20%|██        | 4487/22132 [01:38<06:29, 45.35it/s]

2026-09-09 18:23:24,594 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:24,612 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:24,629 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:24,647 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:24,664 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:24,684 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  20%|██        | 4493/22132 [01:38<06:08, 47.88it/s]

2026-09-09 18:23:24,701 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:24,721 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:24,737 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:24,754 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:24,771 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:24,791 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  20%|██        | 4499/22132 [01:38<05:51, 50.18it/s]

2026-09-09 18:23:24,811 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:24,834 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:24,851 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:24,870 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:24,894 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:24,919 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  20%|██        | 4505/22132 [01:39<05:58, 49.15it/s]

2026-09-09 18:23:24,941 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:24,965 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:23:24,985 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:25,009 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:25,032 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  20%|██        | 4510/22132 [01:39<06:09, 47.67it/s]

2026-09-09 18:23:25,062 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:23:25,104 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.041s]
2026-09-09 18:23:25,125 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:25,143 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:25,160 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  20%|██        | 4515/22132 [01:39<06:32, 44.90it/s]

2026-09-09 18:23:25,179 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:25,198 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:25,216 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:25,235 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:25,254 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:25,276 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  20%|██        | 4521/22132 [01:39<06:14, 47.00it/s]

2026-09-09 18:23:25,295 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:25,312 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:25,333 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:25,351 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:25,371 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:25,391 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  20%|██        | 4527/22132 [01:39<06:03, 48.42it/s]

2026-09-09 18:23:25,409 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:25,427 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:25,446 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:25,463 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:25,480 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:25,497 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  20%|██        | 4533/22132 [01:39<05:46, 50.81it/s]

2026-09-09 18:23:25,514 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:25,531 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:25,548 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:25,565 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:25,584 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:25,600 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  21%|██        | 4539/22132 [01:39<05:33, 52.78it/s]

2026-09-09 18:23:25,620 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:25,639 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:25,657 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:25,674 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:25,694 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:25,714 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  21%|██        | 4545/22132 [01:39<05:33, 52.72it/s]

2026-09-09 18:23:25,733 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:25,751 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:25,770 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:25,788 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:25,808 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:25,826 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  21%|██        | 4551/22132 [01:39<05:31, 53.04it/s]

2026-09-09 18:23:25,850 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:25,873 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:25,894 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:25,914 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:25,935 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:25,962 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]

Indexing Records:  21%|██        | 4557/22132 [01:40<05:51, 49.98it/s]

2026-09-09 18:23:25,983 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:26,002 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:26,021 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:26,039 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:26,056 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:26,075 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  21%|██        | 4563/22132 [01:40<05:45, 50.84it/s]

2026-09-09 18:23:26,092 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:26,110 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:26,131 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:26,154 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:26,174 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:26,193 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  21%|██        | 4569/22132 [01:40<05:44, 50.93it/s]

2026-09-09 18:23:26,218 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:23:26,238 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:26,255 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:26,272 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:26,290 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:26,307 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  21%|██        | 4575/22132 [01:40<05:41, 51.42it/s]

2026-09-09 18:23:26,324 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:26,341 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:26,362 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:26,381 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:26,398 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:26,415 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  21%|██        | 4581/22132 [01:40<05:34, 52.54it/s]

2026-09-09 18:23:26,433 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:26,452 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:26,471 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:26,488 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:26,514 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:23:26,535 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  21%|██        | 4587/22132 [01:40<05:39, 51.75it/s]

2026-09-09 18:23:26,555 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:26,571 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:26,590 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:26,612 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:26,633 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:26,665 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]

Indexing Records:  21%|██        | 4593/22132 [01:40<05:51, 49.95it/s]

2026-09-09 18:23:26,683 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:26,699 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:26,716 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:26,733 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:26,750 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:26,769 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  21%|██        | 4599/22132 [01:40<05:36, 52.09it/s]

2026-09-09 18:23:26,786 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:26,804 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:26,821 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:26,841 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:26,860 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:26,881 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  21%|██        | 4605/22132 [01:41<05:34, 52.47it/s]

2026-09-09 18:23:26,903 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:26,921 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:26,940 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:26,964 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:26,985 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:27,012 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]

Indexing Records:  21%|██        | 4611/22132 [01:41<05:48, 50.31it/s]

2026-09-09 18:23:27,033 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:27,054 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:27,077 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:27,097 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:27,127 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:23:27,179 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.051s]

Indexing Records:  21%|██        | 4617/22132 [01:41<06:30, 44.89it/s]

2026-09-09 18:23:27,205 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:23:27,233 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:23:27,255 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:27,279 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:27,298 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  21%|██        | 4622/22132 [01:41<06:37, 44.06it/s]

2026-09-09 18:23:27,319 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:27,339 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:27,357 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:27,374 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:27,391 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:27,408 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  21%|██        | 4628/22132 [01:41<06:13, 46.87it/s]

2026-09-09 18:23:27,428 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:27,447 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:27,463 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:27,486 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:27,503 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:27,520 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  21%|██        | 4634/22132 [01:41<05:58, 48.79it/s]

2026-09-09 18:23:27,538 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:27,556 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:27,574 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:27,594 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:27,611 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:27,629 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  21%|██        | 4640/22132 [01:41<05:45, 50.59it/s]

2026-09-09 18:23:27,646 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:27,662 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:27,679 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:27,695 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:27,712 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:27,729 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  21%|██        | 4646/22132 [01:41<05:29, 53.06it/s]

2026-09-09 18:23:27,747 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:27,767 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:27,784 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:27,802 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:27,819 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:27,837 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  21%|██        | 4652/22132 [01:41<05:25, 53.76it/s]

2026-09-09 18:23:27,855 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:27,873 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:27,889 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:27,906 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:27,923 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:27,939 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  21%|██        | 4658/22132 [01:42<05:16, 55.22it/s]

2026-09-09 18:23:27,958 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:27,974 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:27,992 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:28,009 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:28,027 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:28,043 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  21%|██        | 4664/22132 [01:42<05:11, 56.01it/s]

2026-09-09 18:23:28,060 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:28,077 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:28,095 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:28,114 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:28,135 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:28,154 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  21%|██        | 4670/22132 [01:42<05:15, 55.29it/s]

2026-09-09 18:23:28,173 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:28,191 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:28,214 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:28,241 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:23:28,267 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:23:28,293 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  21%|██        | 4676/22132 [01:42<05:41, 51.08it/s]

2026-09-09 18:23:28,313 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:28,336 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:28,362 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:23:28,382 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:28,418 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]
2026-09-09 18:23:28,442 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  21%|██        | 4682/22132 [01:42<06:09, 47.18it/s]

2026-09-09 18:23:28,466 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:28,491 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:23:28,510 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:28,528 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:28,547 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  21%|██        | 4687/22132 [01:42<06:08, 47.38it/s]

2026-09-09 18:23:28,565 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:28,586 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:28,607 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:28,624 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:28,648 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  21%|██        | 4692/22132 [01:42<06:04, 47.86it/s]

2026-09-09 18:23:28,674 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:23:28,698 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:23:28,723 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:23:28,744 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:28,762 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  21%|██        | 4697/22132 [01:42<06:13, 46.72it/s]

2026-09-09 18:23:28,784 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:28,802 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:28,819 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:28,835 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:28,851 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:28,868 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  21%|██        | 4703/22132 [01:43<05:51, 49.52it/s]

2026-09-09 18:23:28,888 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:28,906 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:28,923 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:28,940 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:28,957 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:28,974 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  21%|██▏       | 4709/22132 [01:43<05:37, 51.59it/s]

2026-09-09 18:23:28,996 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:29,015 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:29,036 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:29,058 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:29,078 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:29,097 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  21%|██▏       | 4715/22132 [01:43<05:43, 50.65it/s]

2026-09-09 18:23:29,117 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:29,135 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:29,153 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:29,174 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:29,196 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:29,218 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  21%|██▏       | 4721/22132 [01:43<05:46, 50.27it/s]

2026-09-09 18:23:29,250 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:23:29,271 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:29,291 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:29,307 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:29,325 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:29,342 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  21%|██▏       | 4727/22132 [01:43<05:50, 49.72it/s]

2026-09-09 18:23:29,363 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:29,382 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:29,400 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:29,418 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:29,437 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:29,458 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  21%|██▏       | 4733/22132 [01:43<05:46, 50.28it/s]

2026-09-09 18:23:29,485 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:23:29,505 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:29,524 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:29,546 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:29,566 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:29,585 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  21%|██▏       | 4739/22132 [01:43<05:52, 49.35it/s]

2026-09-09 18:23:29,603 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:29,639 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]
2026-09-09 18:23:29,658 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:29,724 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.064s]
2026-09-09 18:23:29,745 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  21%|██▏       | 4744/22132 [01:43<06:46, 42.77it/s]

2026-09-09 18:23:29,767 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:29,801 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:23:29,822 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:29,843 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:29,865 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  21%|██▏       | 4749/22132 [01:44<06:49, 42.49it/s]

2026-09-09 18:23:29,893 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:23:29,930 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]
2026-09-09 18:23:29,958 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:23:29,986 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:23:30,037 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.050s]

Indexing Records:  21%|██▏       | 4754/22132 [01:44<07:42, 37.60it/s]

2026-09-09 18:23:30,111 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.072s]
2026-09-09 18:23:30,141 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:23:30,170 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:23:30,192 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  21%|██▏       | 4758/22132 [01:44<08:33, 33.84it/s]

2026-09-09 18:23:30,223 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:23:30,257 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:23:36,939 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:6.681s]
2026-09-09 18:23:36,969 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]

Indexing Records:  22%|██▏       | 4762/22132 [01:51<2:12:57,  2.18it/s]

2026-09-09 18:23:36,992 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:37,011 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:37,038 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:23:37,060 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:37,080 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  22%|██▏       | 4767/22132 [01:51<1:33:00,  3.11it/s]

2026-09-09 18:23:37,100 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:37,117 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:37,135 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:37,158 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:37,177 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:37,198 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  22%|██▏       | 4773/22132 [01:51<1:02:20,  4.64it/s]

2026-09-09 18:23:37,217 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:37,235 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:37,254 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:37,272 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:37,291 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:37,309 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  22%|██▏       | 4779/22132 [01:51<43:17,  6.68it/s]

2026-09-09 18:23:37,328 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:37,346 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:37,363 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:37,383 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:37,405 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:37,422 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  22%|██▏       | 4785/22132 [01:51<31:03,  9.31it/s]

2026-09-09 18:23:37,443 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:37,463 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:37,482 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:37,497 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:37,512 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:23:37,528 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  22%|██▏       | 4791/22132 [01:51<22:51, 12.64it/s]

2026-09-09 18:23:37,547 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:37,561 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:23:37,582 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:37,599 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:37,613 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:23:37,630 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  22%|██▏       | 4797/22132 [01:51<17:15, 16.73it/s]

2026-09-09 18:23:37,649 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:37,664 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:23:37,681 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:37,697 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:23:37,711 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:23:37,729 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:37,751 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  22%|██▏       | 4804/22132 [01:51<13:04, 22.09it/s]

2026-09-09 18:23:37,766 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:23:37,787 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:37,805 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:37,824 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:37,839 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:23:37,854 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]

Indexing Records:  22%|██▏       | 4810/22132 [01:51<10:40, 27.05it/s]

2026-09-09 18:23:37,869 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:23:37,885 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:37,901 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:23:37,917 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:37,945 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:23:37,986 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.039s]

Indexing Records:  22%|██▏       | 4816/22132 [01:52<09:23, 30.73it/s]

2026-09-09 18:23:38,005 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:38,023 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:38,040 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:38,057 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:38,076 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:38,096 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  22%|██▏       | 4822/22132 [01:52<08:10, 35.27it/s]

2026-09-09 18:23:38,115 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:38,133 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:38,150 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:38,167 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:38,188 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:38,212 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  22%|██▏       | 4828/22132 [01:52<07:23, 39.00it/s]

2026-09-09 18:23:38,230 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:38,250 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:38,270 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:38,289 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:38,309 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:38,331 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  22%|██▏       | 4834/22132 [01:52<06:53, 41.79it/s]

2026-09-09 18:23:38,355 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:38,375 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:38,397 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:38,422 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:23:38,450 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:23:38,472 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  22%|██▏       | 4840/22132 [01:52<06:51, 42.07it/s]

2026-09-09 18:23:38,493 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:38,516 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:38,534 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:38,552 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:38,572 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  22%|██▏       | 4845/22132 [01:52<06:34, 43.84it/s]

2026-09-09 18:23:38,592 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:38,610 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:38,630 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:38,652 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:38,677 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  22%|██▏       | 4850/22132 [01:52<06:25, 44.83it/s]

2026-09-09 18:23:38,697 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:38,716 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:38,735 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:38,754 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:38,776 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:38,794 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  22%|██▏       | 4856/22132 [01:52<06:09, 46.78it/s]

2026-09-09 18:23:38,815 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:38,833 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:38,852 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:38,872 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:38,896 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  22%|██▏       | 4861/22132 [01:53<06:05, 47.26it/s]

2026-09-09 18:23:38,918 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:38,942 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:38,963 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:38,980 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:38,996 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:39,015 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  22%|██▏       | 4867/22132 [01:53<05:57, 48.28it/s]

2026-09-09 18:23:39,034 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:39,056 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:39,078 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:39,117 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.038s]
2026-09-09 18:23:39,138 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  22%|██▏       | 4872/22132 [01:53<06:16, 45.89it/s]

2026-09-09 18:23:39,166 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:23:39,187 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:39,205 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:39,222 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:39,240 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  22%|██▏       | 4877/22132 [01:53<06:09, 46.72it/s]

2026-09-09 18:23:39,259 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:39,276 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:39,293 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:39,311 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:39,328 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:39,344 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  22%|██▏       | 4883/22132 [01:53<05:46, 49.82it/s]

2026-09-09 18:23:39,363 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:39,380 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:39,397 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:39,417 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:39,434 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:39,452 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  22%|██▏       | 4889/22132 [01:53<05:34, 51.50it/s]

2026-09-09 18:23:39,471 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:39,496 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:23:39,516 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:39,536 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:39,559 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:39,577 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  22%|██▏       | 4895/22132 [01:53<05:42, 50.36it/s]

2026-09-09 18:23:39,596 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:39,613 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:39,631 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:39,649 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:39,667 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:39,687 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  22%|██▏       | 4901/22132 [01:53<05:33, 51.67it/s]

2026-09-09 18:23:39,706 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:39,725 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:39,742 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:39,759 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:39,777 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:39,793 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  22%|██▏       | 4907/22132 [01:53<05:25, 52.97it/s]

2026-09-09 18:23:39,811 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:39,828 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:39,846 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:39,863 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:39,881 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:39,899 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  22%|██▏       | 4913/22132 [01:54<05:18, 54.06it/s]

2026-09-09 18:23:39,918 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:39,935 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:39,951 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:39,968 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:39,987 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:40,006 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  22%|██▏       | 4919/22132 [01:54<05:14, 54.72it/s]

2026-09-09 18:23:40,026 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:40,047 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:40,093 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.044s]
2026-09-09 18:23:40,111 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:40,133 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:40,152 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  22%|██▏       | 4925/22132 [01:54<05:46, 49.65it/s]

2026-09-09 18:23:40,171 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:40,189 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:40,208 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:40,225 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:40,244 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:40,261 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  22%|██▏       | 4931/22132 [01:54<05:35, 51.21it/s]

2026-09-09 18:23:40,281 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:40,301 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:40,321 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:40,342 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:40,360 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:40,379 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  22%|██▏       | 4937/22132 [01:54<05:36, 51.08it/s]

2026-09-09 18:23:40,403 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:40,426 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:40,449 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:40,470 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:40,492 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:40,512 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  22%|██▏       | 4943/22132 [01:54<05:49, 49.17it/s]

2026-09-09 18:23:40,534 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:40,551 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:40,570 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:40,589 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:40,607 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:40,625 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  22%|██▏       | 4949/22132 [01:54<05:41, 50.32it/s]

2026-09-09 18:23:40,645 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:40,661 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:40,682 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:40,700 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:40,719 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:40,745 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  22%|██▏       | 4955/22132 [01:54<05:41, 50.24it/s]

2026-09-09 18:23:40,764 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:40,781 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:40,799 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:40,818 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:40,837 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:40,856 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  22%|██▏       | 4961/22132 [01:54<05:34, 51.27it/s]

2026-09-09 18:23:40,875 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:40,904 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:23:40,928 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:40,952 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:23:40,978 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:23:41,000 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  22%|██▏       | 4967/22132 [01:55<05:58, 47.90it/s]

2026-09-09 18:23:41,026 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:23:41,046 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:41,064 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:41,083 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:41,105 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  22%|██▏       | 4972/22132 [01:55<05:58, 47.87it/s]

2026-09-09 18:23:41,128 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:41,152 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:41,182 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:23:41,205 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:41,319 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.112s]

Indexing Records:  22%|██▏       | 4977/22132 [01:55<07:40, 37.22it/s]

2026-09-09 18:23:41,344 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:41,361 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:41,381 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:41,404 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:41,422 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  23%|██▎       | 4982/22132 [01:55<07:10, 39.83it/s]

2026-09-09 18:23:41,444 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:41,465 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:41,484 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:41,502 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:41,520 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:41,540 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  23%|██▎       | 4988/22132 [01:55<06:40, 42.81it/s]

2026-09-09 18:23:41,560 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:41,577 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:41,599 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:41,617 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:41,636 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:41,654 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  23%|██▎       | 4994/22132 [01:55<06:16, 45.55it/s]

2026-09-09 18:23:41,671 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:41,688 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:41,707 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:41,724 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:41,741 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:41,758 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  23%|██▎       | 5000/22132 [01:55<05:51, 48.76it/s]

2026-09-09 18:23:41,776 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:41,795 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:41,813 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:41,829 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:41,846 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:41,864 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  23%|██▎       | 5006/22132 [01:56<05:36, 50.92it/s]

2026-09-09 18:23:41,882 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:41,900 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:41,916 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:41,933 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:41,950 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:41,971 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  23%|██▎       | 5012/22132 [01:56<05:26, 52.39it/s]

2026-09-09 18:23:41,989 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:42,009 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:42,029 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:42,050 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:42,073 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:42,091 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  23%|██▎       | 5018/22132 [01:56<05:31, 51.67it/s]

2026-09-09 18:23:42,112 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:42,132 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:42,156 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:23:42,174 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:42,202 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:23:42,220 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  23%|██▎       | 5024/22132 [01:56<05:42, 49.92it/s]

2026-09-09 18:23:42,240 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:42,261 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:42,279 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:42,297 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:42,315 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:42,332 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  23%|██▎       | 5030/22132 [01:56<05:35, 50.96it/s]

2026-09-09 18:23:42,353 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:42,370 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:42,387 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:42,404 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:42,422 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:42,441 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  23%|██▎       | 5036/22132 [01:56<05:27, 52.18it/s]

2026-09-09 18:23:42,462 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:42,480 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:42,499 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:42,517 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:42,537 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:42,556 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  23%|██▎       | 5042/22132 [01:56<05:27, 52.12it/s]

2026-09-09 18:23:42,583 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:23:42,601 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:42,618 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:42,635 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:42,652 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:42,668 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  23%|██▎       | 5048/22132 [01:56<05:25, 52.54it/s]

2026-09-09 18:23:42,686 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:42,704 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:42,721 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:42,743 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:42,765 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:42,784 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  23%|██▎       | 5054/22132 [01:56<05:26, 52.35it/s]

2026-09-09 18:23:42,802 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:42,821 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:42,840 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:42,859 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:42,879 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:42,897 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  23%|██▎       | 5060/22132 [01:57<05:24, 52.56it/s]

2026-09-09 18:23:42,916 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:42,934 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:42,951 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:42,968 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:42,985 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:43,005 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  23%|██▎       | 5066/22132 [01:57<05:19, 53.40it/s]

2026-09-09 18:23:43,049 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.042s]
2026-09-09 18:23:43,070 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:43,088 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:43,106 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:43,124 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:43,142 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  23%|██▎       | 5072/22132 [01:57<05:40, 50.09it/s]

2026-09-09 18:23:43,160 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:43,177 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:43,195 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:43,220 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:23:43,239 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:43,262 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  23%|██▎       | 5078/22132 [01:57<05:40, 50.14it/s]

2026-09-09 18:23:43,285 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:43,308 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:43,336 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:23:43,360 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:43,390 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:23:43,410 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  23%|██▎       | 5084/22132 [01:57<06:04, 46.74it/s]

2026-09-09 18:23:43,432 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:43,453 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:43,474 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:43,496 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:43,531 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]

Indexing Records:  23%|██▎       | 5089/22132 [01:57<06:17, 45.20it/s]

2026-09-09 18:23:43,553 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:43,572 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:43,594 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:43,614 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:43,634 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  23%|██▎       | 5094/22132 [01:57<06:09, 46.11it/s]

2026-09-09 18:23:43,655 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:43,697 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.041s]
2026-09-09 18:23:43,719 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:43,737 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:43,759 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  23%|██▎       | 5099/22132 [01:57<06:25, 44.24it/s]

2026-09-09 18:23:43,779 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:43,800 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:43,822 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:43,840 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:43,865 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  23%|██▎       | 5104/22132 [01:58<06:18, 45.00it/s]

2026-09-09 18:23:43,888 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:43,912 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:43,931 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:43,950 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:43,967 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  23%|██▎       | 5109/22132 [01:58<06:08, 46.15it/s]

2026-09-09 18:23:43,985 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:44,009 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:23:44,031 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:44,053 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:44,073 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  23%|██▎       | 5114/22132 [01:58<06:06, 46.42it/s]

2026-09-09 18:23:44,092 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:44,114 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:44,134 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:44,153 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:44,170 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:44,186 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  23%|██▎       | 5120/22132 [01:58<05:51, 48.43it/s]

2026-09-09 18:23:44,205 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:44,223 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:44,241 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:44,259 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:44,275 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:44,293 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  23%|██▎       | 5126/22132 [01:58<05:35, 50.67it/s]

2026-09-09 18:23:44,310 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:44,327 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:44,345 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:44,360 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:23:44,378 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:44,393 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  23%|██▎       | 5132/22132 [01:58<05:19, 53.23it/s]

2026-09-09 18:23:44,411 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:44,428 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:44,449 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:44,465 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:44,484 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:44,502 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  23%|██▎       | 5138/22132 [01:58<05:15, 53.87it/s]

2026-09-09 18:23:44,519 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:44,537 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:44,553 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:44,572 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:44,592 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:44,614 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  23%|██▎       | 5144/22132 [01:58<05:15, 53.78it/s]

2026-09-09 18:23:44,636 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:44,654 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:44,672 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:44,693 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:44,711 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:44,728 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  23%|██▎       | 5150/22132 [01:58<05:18, 53.31it/s]

2026-09-09 18:23:44,749 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:44,772 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:44,793 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:44,812 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:44,830 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:44,847 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  23%|██▎       | 5156/22132 [01:58<05:23, 52.40it/s]

2026-09-09 18:23:44,867 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:44,884 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:44,903 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:44,921 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:44,942 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:44,964 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  23%|██▎       | 5162/22132 [01:59<05:26, 52.05it/s]

2026-09-09 18:23:44,983 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:45,001 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:45,024 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:45,044 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:45,065 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:45,088 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  23%|██▎       | 5168/22132 [01:59<05:33, 50.91it/s]

2026-09-09 18:23:45,112 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:45,134 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:45,156 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:45,174 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:45,192 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:45,211 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  23%|██▎       | 5174/22132 [01:59<05:36, 50.32it/s]

2026-09-09 18:23:45,230 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:45,247 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:45,264 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:45,283 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:45,301 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:45,318 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  23%|██▎       | 5180/22132 [01:59<05:26, 51.91it/s]

2026-09-09 18:23:45,337 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:45,356 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:45,373 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:45,392 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:45,415 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:45,435 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  23%|██▎       | 5186/22132 [01:59<05:28, 51.66it/s]

2026-09-09 18:23:45,456 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:45,473 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:45,492 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:45,510 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:45,528 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:45,546 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  23%|██▎       | 5192/22132 [01:59<05:23, 52.31it/s]

2026-09-09 18:23:45,566 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:45,585 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:45,606 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:45,633 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:23:45,654 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:45,671 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  23%|██▎       | 5198/22132 [01:59<05:31, 51.01it/s]

2026-09-09 18:23:45,692 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:45,716 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:45,739 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:45,758 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:45,777 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:45,795 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  24%|██▎       | 5204/22132 [01:59<05:37, 50.14it/s]

2026-09-09 18:23:45,815 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:45,833 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:45,852 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:45,872 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:45,890 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:45,907 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  24%|██▎       | 5210/22132 [02:00<05:31, 51.12it/s]

2026-09-09 18:23:45,931 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:45,950 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:45,970 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:45,988 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:46,004 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:46,023 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  24%|██▎       | 5216/22132 [02:00<05:29, 51.38it/s]

2026-09-09 18:23:46,043 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:46,065 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:46,083 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:46,102 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:46,121 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:46,140 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  24%|██▎       | 5222/22132 [02:00<05:29, 51.27it/s]

2026-09-09 18:23:46,164 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:46,181 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:46,199 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:46,218 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:46,237 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:46,255 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  24%|██▎       | 5228/22132 [02:00<05:27, 51.58it/s]

2026-09-09 18:23:46,273 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:46,291 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:46,309 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:46,329 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:46,346 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:46,363 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  24%|██▎       | 5234/22132 [02:00<05:20, 52.76it/s]

2026-09-09 18:23:46,383 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:46,401 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:46,418 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:46,437 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:46,455 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:46,473 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  24%|██▎       | 5240/22132 [02:00<05:17, 53.20it/s]

2026-09-09 18:23:46,499 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:23:46,517 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:46,536 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:46,555 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:46,572 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:46,590 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  24%|██▎       | 5246/22132 [02:00<05:21, 52.59it/s]

2026-09-09 18:23:46,611 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:46,632 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:46,650 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:46,669 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:46,686 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:46,705 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  24%|██▎       | 5252/22132 [02:00<05:21, 52.55it/s]

2026-09-09 18:23:46,729 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:46,749 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:46,766 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:46,783 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:46,801 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:46,820 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  24%|██▍       | 5258/22132 [02:00<05:21, 52.41it/s]

2026-09-09 18:23:46,838 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:46,856 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:46,874 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:46,892 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:46,915 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:46,936 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  24%|██▍       | 5264/22132 [02:01<05:23, 52.20it/s]

2026-09-09 18:23:46,958 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:46,982 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:47,004 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:47,033 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:23:47,054 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:47,074 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  24%|██▍       | 5270/22132 [02:01<05:42, 49.20it/s]

2026-09-09 18:23:47,097 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:47,119 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:47,140 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:47,161 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:47,179 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  24%|██▍       | 5275/22132 [02:01<05:45, 48.85it/s]

2026-09-09 18:23:47,198 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:47,216 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:47,236 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:47,258 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:47,276 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:47,296 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  24%|██▍       | 5281/22132 [02:01<05:39, 49.61it/s]

2026-09-09 18:23:47,316 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:47,335 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:47,354 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:47,370 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:47,388 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:47,407 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  24%|██▍       | 5287/22132 [02:01<05:31, 50.83it/s]

2026-09-09 18:23:47,428 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:47,449 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:47,475 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:23:47,503 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:23:47,522 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:47,542 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  24%|██▍       | 5293/22132 [02:01<05:45, 48.69it/s]

2026-09-09 18:23:47,561 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:47,581 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:47,602 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:47,621 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:47,640 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:47,658 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  24%|██▍       | 5299/22132 [02:01<05:39, 49.54it/s]

2026-09-09 18:23:47,676 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:47,696 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:47,714 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:47,733 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:47,751 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:47,768 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  24%|██▍       | 5305/22132 [02:01<05:30, 50.97it/s]

2026-09-09 18:23:47,787 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:47,806 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:47,824 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:47,842 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:47,860 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:47,877 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  24%|██▍       | 5311/22132 [02:02<05:22, 52.15it/s]

2026-09-09 18:23:47,896 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:47,914 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:47,936 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:47,957 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:47,976 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:47,999 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  24%|██▍       | 5317/22132 [02:02<05:28, 51.22it/s]

2026-09-09 18:23:48,022 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:48,040 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:48,057 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:48,076 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:48,094 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:48,111 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  24%|██▍       | 5323/22132 [02:02<05:23, 51.94it/s]

2026-09-09 18:23:48,131 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:48,151 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:48,170 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:48,188 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:48,207 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:48,224 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  24%|██▍       | 5329/22132 [02:02<05:21, 52.21it/s]

2026-09-09 18:23:48,244 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:48,262 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:48,280 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:48,301 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:48,318 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:48,336 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  24%|██▍       | 5335/22132 [02:02<05:18, 52.66it/s]

2026-09-09 18:23:48,356 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:48,373 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:48,393 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:48,413 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:48,432 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:48,450 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  24%|██▍       | 5341/22132 [02:02<05:18, 52.70it/s]

2026-09-09 18:23:48,469 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:48,488 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:48,507 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:48,526 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:48,552 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:23:48,574 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  24%|██▍       | 5347/22132 [02:02<05:27, 51.24it/s]

2026-09-09 18:23:48,617 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.040s]
2026-09-09 18:23:48,650 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:23:48,678 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:23:48,702 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:23:48,726 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:23:48,762 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]

Indexing Records:  24%|██▍       | 5353/22132 [02:02<06:26, 43.43it/s]

2026-09-09 18:23:48,786 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:48,805 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:48,826 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:48,845 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:48,872 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]

Indexing Records:  24%|██▍       | 5358/22132 [02:03<06:22, 43.89it/s]

2026-09-09 18:23:48,897 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:48,920 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:48,941 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:48,965 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:48,984 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  24%|██▍       | 5363/22132 [02:03<06:20, 44.12it/s]

2026-09-09 18:23:49,005 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:49,026 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:49,046 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:49,065 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:49,082 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:49,099 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  24%|██▍       | 5369/22132 [02:03<06:01, 46.41it/s]

2026-09-09 18:23:49,117 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:49,135 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:49,153 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:49,173 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:49,191 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:49,207 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  24%|██▍       | 5375/22132 [02:03<05:42, 48.87it/s]

2026-09-09 18:23:49,227 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:49,244 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:49,263 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:49,280 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:49,299 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:49,317 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  24%|██▍       | 5381/22132 [02:03<05:31, 50.50it/s]

2026-09-09 18:23:49,337 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:49,355 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:49,372 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:49,388 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:49,405 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:49,422 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  24%|██▍       | 5387/22132 [02:03<05:19, 52.44it/s]

2026-09-09 18:23:49,441 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:49,461 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:49,479 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:49,501 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:49,518 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:49,535 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  24%|██▍       | 5393/22132 [02:03<05:18, 52.57it/s]

2026-09-09 18:23:49,553 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:49,571 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:49,589 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:49,608 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:49,630 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:49,648 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  24%|██▍       | 5399/22132 [02:03<05:16, 52.80it/s]

2026-09-09 18:23:49,670 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:49,687 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:49,707 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:49,729 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:49,750 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:49,769 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  24%|██▍       | 5405/22132 [02:03<05:23, 51.75it/s]

2026-09-09 18:23:49,789 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:49,808 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:49,832 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:49,855 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:49,878 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:49,901 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  24%|██▍       | 5411/22132 [02:04<05:36, 49.75it/s]

2026-09-09 18:23:49,927 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:23:49,951 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:23:49,972 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:49,994 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:50,019 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:23:50,044 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  24%|██▍       | 5417/22132 [02:04<05:55, 47.03it/s]

2026-09-09 18:23:50,066 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:50,084 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:50,102 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:50,146 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.043s]
2026-09-09 18:23:50,183 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]

Indexing Records:  24%|██▍       | 5422/22132 [02:04<06:23, 43.56it/s]

2026-09-09 18:23:50,221 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.037s]
2026-09-09 18:23:50,246 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:23:50,269 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:50,297 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:23:50,320 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  25%|██▍       | 5427/22132 [02:04<06:44, 41.33it/s]

2026-09-09 18:23:50,342 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:50,363 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:50,381 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:50,398 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:50,419 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:50,440 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  25%|██▍       | 5433/22132 [02:04<06:21, 43.81it/s]

2026-09-09 18:23:50,460 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:50,479 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:50,499 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:50,516 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:50,535 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:50,552 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  25%|██▍       | 5439/22132 [02:04<05:59, 46.39it/s]

2026-09-09 18:23:50,572 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:50,589 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:50,608 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:50,625 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:50,643 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:50,665 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  25%|██▍       | 5445/22132 [02:04<05:45, 48.34it/s]

2026-09-09 18:23:50,694 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:23:50,714 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:50,735 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:50,758 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:50,782 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  25%|██▍       | 5450/22132 [02:04<05:57, 46.63it/s]

2026-09-09 18:23:50,812 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:23:50,832 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:50,850 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:50,868 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:50,889 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  25%|██▍       | 5455/22132 [02:05<05:57, 46.71it/s]

2026-09-09 18:23:50,910 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:50,932 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:50,951 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:50,969 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:50,989 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  25%|██▍       | 5460/22132 [02:05<05:50, 47.58it/s]

2026-09-09 18:23:51,018 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:23:51,042 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:51,072 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:23:51,094 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:51,117 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  25%|██▍       | 5465/22132 [02:05<06:12, 44.75it/s]

2026-09-09 18:23:51,137 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:51,155 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:51,175 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:51,195 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:51,214 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:51,237 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  25%|██▍       | 5471/22132 [02:05<05:59, 46.34it/s]

2026-09-09 18:23:51,257 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:51,285 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:23:51,303 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:51,323 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:51,346 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  25%|██▍       | 5476/22132 [02:05<06:00, 46.19it/s]

2026-09-09 18:23:51,369 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:51,398 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:23:51,422 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:23:51,441 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:51,461 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  25%|██▍       | 5481/22132 [02:05<06:06, 45.46it/s]

2026-09-09 18:23:51,485 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:23:51,506 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:51,523 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:51,543 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:51,562 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  25%|██▍       | 5486/22132 [02:05<05:58, 46.49it/s]

2026-09-09 18:23:51,583 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:51,599 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:51,618 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:51,637 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:51,655 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:51,674 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  25%|██▍       | 5492/22132 [02:05<05:42, 48.65it/s]

2026-09-09 18:23:51,698 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:51,721 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:51,739 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:51,760 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:51,785 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  25%|██▍       | 5497/22132 [02:05<05:49, 47.59it/s]

2026-09-09 18:23:51,807 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:51,826 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:51,864 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.036s]
2026-09-09 18:23:51,882 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:51,898 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  25%|██▍       | 5502/22132 [02:06<05:57, 46.55it/s]

2026-09-09 18:23:51,918 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:51,934 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:51,953 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:51,971 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:51,988 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:52,009 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  25%|██▍       | 5508/22132 [02:06<05:40, 48.76it/s]

2026-09-09 18:23:52,032 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:52,050 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:52,070 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:52,088 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:52,105 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:52,122 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  25%|██▍       | 5514/22132 [02:06<05:31, 50.13it/s]

2026-09-09 18:23:52,140 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:52,159 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:52,178 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:52,196 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:52,214 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:52,234 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  25%|██▍       | 5520/22132 [02:06<05:24, 51.17it/s]

2026-09-09 18:23:52,256 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:52,277 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:52,296 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:52,315 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:52,332 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:52,353 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  25%|██▍       | 5526/22132 [02:06<05:25, 50.95it/s]

2026-09-09 18:23:52,373 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:52,392 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:52,409 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:52,427 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:52,444 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:52,463 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  25%|██▍       | 5532/22132 [02:06<05:19, 52.03it/s]

2026-09-09 18:23:52,480 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:52,497 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:52,513 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:23:52,532 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:52,549 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:52,568 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  25%|██▌       | 5538/22132 [02:06<05:10, 53.43it/s]

2026-09-09 18:23:52,587 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:52,613 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:23:52,637 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:23:52,658 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:52,679 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:52,697 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  25%|██▌       | 5544/22132 [02:06<05:24, 51.16it/s]

2026-09-09 18:23:52,717 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:52,741 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:52,759 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:52,777 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:52,797 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:52,815 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  25%|██▌       | 5550/22132 [02:06<05:24, 51.04it/s]

2026-09-09 18:23:52,835 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:52,854 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:52,871 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:52,888 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:52,906 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:52,927 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  25%|██▌       | 5556/22132 [02:07<05:19, 51.81it/s]

2026-09-09 18:23:52,950 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:52,969 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:52,990 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:53,011 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:53,029 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:53,048 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  25%|██▌       | 5562/22132 [02:07<05:24, 51.04it/s]

2026-09-09 18:23:53,073 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:23:53,093 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:53,111 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:53,128 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:53,148 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:53,167 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  25%|██▌       | 5568/22132 [02:07<05:25, 50.92it/s]

2026-09-09 18:23:53,185 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:53,204 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:53,222 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:53,240 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:53,257 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:53,275 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  25%|██▌       | 5574/22132 [02:07<05:16, 52.27it/s]

2026-09-09 18:23:53,292 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:53,308 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:53,326 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:53,343 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:53,360 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:53,379 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  25%|██▌       | 5580/22132 [02:07<05:07, 53.75it/s]

2026-09-09 18:23:53,397 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:53,416 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:53,434 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:53,453 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:53,469 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:53,487 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  25%|██▌       | 5586/22132 [02:07<05:04, 54.32it/s]

2026-09-09 18:23:53,504 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:53,524 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:53,541 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:53,557 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:53,575 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:53,593 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  25%|██▌       | 5592/22132 [02:07<05:00, 54.95it/s]

2026-09-09 18:23:53,611 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:53,627 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:53,645 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:53,661 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:23:53,679 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:53,696 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  25%|██▌       | 5598/22132 [02:07<04:55, 55.86it/s]

2026-09-09 18:23:53,714 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:53,731 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:53,749 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:53,766 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:53,783 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:53,801 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  25%|██▌       | 5604/22132 [02:07<04:53, 56.26it/s]

2026-09-09 18:23:53,818 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:53,836 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:53,853 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:53,869 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:53,885 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:53,904 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  25%|██▌       | 5610/22132 [02:08<04:50, 56.90it/s]

2026-09-09 18:23:53,921 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:53,938 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:53,957 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:53,975 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:53,992 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:54,008 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  25%|██▌       | 5616/22132 [02:08<04:49, 57.07it/s]

2026-09-09 18:23:54,026 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:54,043 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:54,061 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:54,083 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:54,102 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:54,122 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  25%|██▌       | 5622/22132 [02:08<04:56, 55.74it/s]

2026-09-09 18:23:54,141 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:54,161 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:54,178 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:54,196 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:54,216 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:54,232 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  25%|██▌       | 5628/22132 [02:08<04:58, 55.26it/s]

2026-09-09 18:23:54,252 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:54,279 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:23:54,301 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:54,319 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:54,338 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:54,358 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  25%|██▌       | 5634/22132 [02:08<05:13, 52.68it/s]

2026-09-09 18:23:54,377 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:54,396 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:54,416 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:54,436 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:54,455 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:54,473 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  25%|██▌       | 5640/22132 [02:08<05:13, 52.52it/s]

2026-09-09 18:23:54,491 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:54,508 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:54,525 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:54,543 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:54,560 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:54,577 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  26%|██▌       | 5646/22132 [02:08<05:05, 53.97it/s]

2026-09-09 18:23:54,597 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:54,615 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:54,633 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:54,653 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:54,670 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:54,687 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  26%|██▌       | 5652/22132 [02:08<05:03, 54.22it/s]

2026-09-09 18:23:54,706 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:54,724 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:54,741 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:23:54,758 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:54,778 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:54,799 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  26%|██▌       | 5658/22132 [02:08<05:04, 54.10it/s]

2026-09-09 18:23:54,819 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:54,836 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:23:54,857 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:54,879 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:54,898 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:54,923 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  26%|██▌       | 5664/22132 [02:09<05:15, 52.17it/s]

2026-09-09 18:23:54,945 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:54,968 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:54,989 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:55,010 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:55,034 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:55,053 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  26%|██▌       | 5670/22132 [02:09<05:28, 50.17it/s]

2026-09-09 18:23:55,074 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:55,096 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:55,117 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:55,139 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:55,159 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:55,179 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  26%|██▌       | 5676/22132 [02:09<05:32, 49.45it/s]

2026-09-09 18:23:55,199 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:55,218 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:55,239 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:55,258 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:55,278 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:55,298 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  26%|██▌       | 5682/22132 [02:09<05:31, 49.69it/s]

2026-09-09 18:23:55,318 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:55,337 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:55,357 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:55,376 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:55,397 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:55,418 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  26%|██▌       | 5688/22132 [02:09<05:29, 49.83it/s]

2026-09-09 18:23:55,439 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:55,458 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:55,477 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:55,496 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:55,517 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:55,546 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]

Indexing Records:  26%|██▌       | 5694/22132 [02:09<05:35, 48.93it/s]

2026-09-09 18:23:55,578 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:23:55,609 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:23:55,629 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:55,649 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:55,673 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  26%|██▌       | 5699/22132 [02:09<05:57, 45.93it/s]

2026-09-09 18:23:55,697 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:55,718 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:55,736 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:55,755 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:55,774 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  26%|██▌       | 5704/22132 [02:09<05:50, 46.83it/s]

2026-09-09 18:23:55,796 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:55,817 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:55,840 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:55,863 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:55,883 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  26%|██▌       | 5709/22132 [02:10<05:52, 46.59it/s]

2026-09-09 18:23:55,906 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:55,929 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:55,950 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:55,969 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:55,989 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  26%|██▌       | 5714/22132 [02:10<05:50, 46.79it/s]

2026-09-09 18:23:56,010 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:56,034 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:23:56,054 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:56,073 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:56,094 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  26%|██▌       | 5719/22132 [02:10<05:49, 47.03it/s]

2026-09-09 18:23:56,114 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:56,135 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:56,163 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:23:56,184 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:56,203 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  26%|██▌       | 5724/22132 [02:10<05:51, 46.64it/s]

2026-09-09 18:23:56,236 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:23:56,262 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:23:56,282 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:56,302 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:56,322 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  26%|██▌       | 5729/22132 [02:10<06:03, 45.13it/s]

2026-09-09 18:23:56,344 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:56,365 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:56,384 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:56,403 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:56,423 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  26%|██▌       | 5734/22132 [02:10<05:53, 46.44it/s]

2026-09-09 18:23:56,445 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:56,473 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:23:56,497 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:56,524 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:23:56,544 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  26%|██▌       | 5739/22132 [02:10<06:05, 44.79it/s]

2026-09-09 18:23:56,565 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:56,584 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:56,602 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:56,620 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:56,640 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:56,659 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  26%|██▌       | 5745/22132 [02:10<05:48, 47.01it/s]

2026-09-09 18:23:56,680 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:56,699 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:56,717 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:56,747 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:23:56,769 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  26%|██▌       | 5750/22132 [02:10<05:52, 46.54it/s]

2026-09-09 18:23:56,791 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:56,815 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:23:56,836 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:56,856 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:56,886 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]

Indexing Records:  26%|██▌       | 5755/22132 [02:11<06:01, 45.35it/s]

2026-09-09 18:23:56,907 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:56,927 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:56,946 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:56,966 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:56,993 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]

Indexing Records:  26%|██▌       | 5760/22132 [02:11<05:57, 45.82it/s]

2026-09-09 18:23:57,014 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:57,035 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:57,057 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:57,075 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:57,095 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  26%|██▌       | 5765/22132 [02:11<05:50, 46.66it/s]

2026-09-09 18:23:57,117 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:57,141 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:57,162 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:57,182 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:57,207 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  26%|██▌       | 5770/22132 [02:11<05:55, 45.99it/s]

2026-09-09 18:23:57,228 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:57,250 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:57,269 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:57,289 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:57,310 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  26%|██▌       | 5775/22132 [02:11<05:49, 46.84it/s]

2026-09-09 18:23:57,329 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:57,349 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:57,371 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:57,391 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:57,409 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:57,428 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  26%|██▌       | 5781/22132 [02:11<05:40, 48.03it/s]

2026-09-09 18:23:57,452 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:57,480 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:23:57,501 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:57,520 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:57,542 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  26%|██▌       | 5786/22132 [02:11<05:49, 46.83it/s]

2026-09-09 18:23:57,563 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:57,593 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:23:57,616 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:57,642 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:23:57,677 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]

Indexing Records:  26%|██▌       | 5791/22132 [02:11<06:16, 43.42it/s]

2026-09-09 18:23:57,697 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:57,716 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:57,735 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:57,755 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:57,774 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:57,793 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  26%|██▌       | 5797/22132 [02:11<05:55, 45.90it/s]

2026-09-09 18:23:57,824 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:23:57,842 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:57,860 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:57,882 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:57,901 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  26%|██▌       | 5802/22132 [02:12<05:55, 45.96it/s]

2026-09-09 18:23:57,922 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:57,943 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:57,977 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]
2026-09-09 18:23:57,996 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:58,015 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  26%|██▌       | 5807/22132 [02:12<05:59, 45.38it/s]

2026-09-09 18:23:58,037 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:58,057 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:58,075 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:58,112 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]
2026-09-09 18:23:58,137 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  26%|██▋       | 5812/22132 [02:12<06:11, 43.96it/s]

2026-09-09 18:23:58,161 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:58,184 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:58,206 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:58,226 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:58,249 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  26%|██▋       | 5817/22132 [02:12<06:09, 44.15it/s]

2026-09-09 18:23:58,269 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:58,288 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:58,308 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:58,326 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:58,350 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  26%|██▋       | 5822/22132 [02:12<05:57, 45.62it/s]

2026-09-09 18:23:58,382 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:23:58,406 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:58,425 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:58,450 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:23:58,470 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  26%|██▋       | 5827/22132 [02:12<06:06, 44.45it/s]

2026-09-09 18:23:58,494 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:58,520 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:23:58,546 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:23:58,566 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:58,586 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  26%|██▋       | 5832/22132 [02:12<06:10, 44.04it/s]

2026-09-09 18:23:58,611 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:23:58,634 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:58,663 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:23:58,682 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:58,704 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  26%|██▋       | 5837/22132 [02:12<06:14, 43.54it/s]

2026-09-09 18:23:58,725 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:58,747 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:58,767 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:58,787 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:58,808 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  26%|██▋       | 5842/22132 [02:12<06:04, 44.74it/s]

2026-09-09 18:23:58,828 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:58,846 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:58,867 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:58,890 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:58,910 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  26%|██▋       | 5847/22132 [02:13<05:53, 46.00it/s]

2026-09-09 18:23:58,931 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:58,953 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:58,973 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:59,006 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:23:59,026 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  26%|██▋       | 5852/22132 [02:13<06:01, 45.08it/s]

2026-09-09 18:23:59,049 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:59,071 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:59,106 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]
2026-09-09 18:23:59,125 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:59,145 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  26%|██▋       | 5857/22132 [02:13<06:09, 44.07it/s]

2026-09-09 18:23:59,167 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:59,187 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:59,220 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:23:59,241 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:59,263 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  26%|██▋       | 5862/22132 [02:13<06:13, 43.61it/s]

2026-09-09 18:23:59,282 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:59,364 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.081s]
2026-09-09 18:23:59,384 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:59,404 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:59,423 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  27%|██▋       | 5867/22132 [02:13<06:57, 38.98it/s]

2026-09-09 18:23:59,442 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:59,464 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:23:59,484 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:59,507 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:59,527 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  27%|██▋       | 5872/22132 [02:13<06:34, 41.25it/s]

2026-09-09 18:23:59,564 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]
2026-09-09 18:23:59,583 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:59,606 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:59,625 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:59,647 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  27%|██▋       | 5877/22132 [02:13<06:32, 41.43it/s]

2026-09-09 18:23:59,669 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:59,690 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:59,711 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:59,732 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:59,752 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  27%|██▋       | 5882/22132 [02:13<06:16, 43.14it/s]

2026-09-09 18:23:59,797 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.043s]
2026-09-09 18:23:59,815 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:23:59,840 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:23:59,861 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:23:59,881 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  27%|██▋       | 5887/22132 [02:14<06:29, 41.66it/s]

2026-09-09 18:23:59,905 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:23:59,925 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:23:59,945 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:59,965 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:23:59,995 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]

Indexing Records:  27%|██▋       | 5892/22132 [02:14<06:23, 42.31it/s]

2026-09-09 18:24:00,020 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:00,051 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:24:00,075 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:00,120 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.043s]
2026-09-09 18:24:00,182 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.061s]

Indexing Records:  27%|██▋       | 5897/22132 [02:14<07:31, 35.98it/s]

2026-09-09 18:24:00,205 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:00,230 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:00,253 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:00,291 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.036s]

Indexing Records:  27%|██▋       | 5901/22132 [02:14<07:28, 36.17it/s]

2026-09-09 18:24:00,329 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]
2026-09-09 18:24:00,353 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:00,394 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.039s]
2026-09-09 18:24:00,417 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  27%|██▋       | 5905/22132 [02:14<07:44, 34.92it/s]

2026-09-09 18:24:00,439 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:00,460 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:00,486 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:24:00,522 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]

Indexing Records:  27%|██▋       | 5909/22132 [02:14<07:34, 35.71it/s]

2026-09-09 18:24:00,554 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:24:00,574 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:00,594 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:00,613 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:00,638 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  27%|██▋       | 5914/22132 [02:14<07:08, 37.87it/s]

2026-09-09 18:24:00,660 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:00,685 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:24:00,705 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:00,730 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:24:00,753 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  27%|██▋       | 5919/22132 [02:14<06:50, 39.48it/s]

2026-09-09 18:24:00,817 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.062s]
2026-09-09 18:24:00,850 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:24:00,870 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:00,892 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  27%|██▋       | 5923/22132 [02:15<07:30, 35.97it/s]

2026-09-09 18:24:00,912 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:00,936 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:00,965 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:24:00,985 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:01,005 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  27%|██▋       | 5928/22132 [02:15<07:03, 38.25it/s]

2026-09-09 18:24:01,028 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:01,058 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:24:01,077 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:01,097 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:01,122 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  27%|██▋       | 5933/22132 [02:15<06:49, 39.58it/s]

2026-09-09 18:24:01,153 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:24:01,179 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:24:01,212 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:24:01,430 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.217s]
2026-09-09 18:24:01,849 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.417s]

Indexing Records:  27%|██▋       | 5938/22132 [02:15<16:54, 15.96it/s]

2026-09-09 18:24:02,232 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.380s]
2026-09-09 18:24:02,538 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.304s]
2026-09-09 18:24:02,709 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.170s]
2026-09-09 18:24:02,864 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.153s]

Indexing Records:  27%|██▋       | 5942/22132 [02:17<30:26,  8.87it/s]

2026-09-09 18:24:02,979 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.113s]
2026-09-09 18:24:03,131 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.149s]
2026-09-09 18:24:03,360 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.228s]

Indexing Records:  27%|██▋       | 5945/22132 [02:17<33:33,  8.04it/s]

2026-09-09 18:24:03,530 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.167s]
2026-09-09 18:24:03,731 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.200s]

Indexing Records:  27%|██▋       | 5947/22132 [02:17<36:24,  7.41it/s]

2026-09-09 18:24:03,890 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.156s]
2026-09-09 18:24:03,925 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]

Indexing Records:  27%|██▋       | 5949/22132 [02:18<34:22,  7.85it/s]

2026-09-09 18:24:04,027 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.100s]
2026-09-09 18:24:04,074 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.045s]

Indexing Records:  27%|██▋       | 5951/22132 [02:18<31:12,  8.64it/s]

2026-09-09 18:24:04,132 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.056s]
2026-09-09 18:24:04,185 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.051s]

Indexing Records:  27%|██▋       | 5953/22132 [02:18<27:18,  9.87it/s]

2026-09-09 18:24:04,256 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.068s]
2026-09-09 18:24:04,294 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.037s]

Indexing Records:  27%|██▋       | 5955/22132 [02:18<24:04, 11.20it/s]

2026-09-09 18:24:04,343 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.047s]
2026-09-09 18:24:04,389 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.044s]
2026-09-09 18:24:04,433 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.043s]

Indexing Records:  27%|██▋       | 5958/22132 [02:18<20:00, 13.48it/s]

2026-09-09 18:24:04,484 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.048s]
2026-09-09 18:24:04,526 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.040s]
2026-09-09 18:24:04,552 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]

Indexing Records:  27%|██▋       | 5961/22132 [02:18<16:52, 15.97it/s]

2026-09-09 18:24:04,599 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.044s]
2026-09-09 18:24:04,633 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:24:04,678 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.043s]

Indexing Records:  27%|██▋       | 5964/22132 [02:18<15:03, 17.90it/s]

2026-09-09 18:24:04,736 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.056s]
2026-09-09 18:24:04,782 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.045s]
2026-09-09 18:24:04,910 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.126s]

Indexing Records:  27%|██▋       | 5967/22132 [02:19<16:53, 15.96it/s]

2026-09-09 18:24:04,974 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.062s]
2026-09-09 18:24:05,021 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.045s]

Indexing Records:  27%|██▋       | 5969/22132 [02:19<16:25, 16.40it/s]

2026-09-09 18:24:05,074 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.051s]
2026-09-09 18:24:05,125 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.050s]

Indexing Records:  27%|██▋       | 5971/22132 [02:19<15:50, 17.00it/s]

2026-09-09 18:24:05,213 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.085s]
2026-09-09 18:24:05,260 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.045s]

Indexing Records:  27%|██▋       | 5973/22132 [02:19<16:25, 16.39it/s]

2026-09-09 18:24:05,314 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.052s]
2026-09-09 18:24:05,366 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.050s]

Indexing Records:  27%|██▋       | 5975/22132 [02:19<15:52, 16.97it/s]

2026-09-09 18:24:05,412 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.043s]
2026-09-09 18:24:05,469 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.056s]

Indexing Records:  27%|██▋       | 5977/22132 [02:19<15:17, 17.61it/s]

2026-09-09 18:24:05,518 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.047s]
2026-09-09 18:24:05,568 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.049s]
2026-09-09 18:24:05,621 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.051s]

Indexing Records:  27%|██▋       | 5980/22132 [02:19<14:40, 18.35it/s]

2026-09-09 18:24:05,683 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.060s]
2026-09-09 18:24:05,744 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.059s]

Indexing Records:  27%|██▋       | 5982/22132 [02:19<15:09, 17.76it/s]

2026-09-09 18:24:05,800 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.054s]
2026-09-09 18:24:05,856 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.055s]

Indexing Records:  27%|██▋       | 5984/22132 [02:19<15:08, 17.77it/s]

2026-09-09 18:24:05,961 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.102s]
2026-09-09 18:24:06,109 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.147s]

Indexing Records:  27%|██▋       | 5986/22132 [02:20<20:27, 13.15it/s]

2026-09-09 18:24:06,139 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:24:06,196 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.055s]
2026-09-09 18:24:06,286 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.088s]

Indexing Records:  27%|██▋       | 5989/22132 [02:20<18:43, 14.37it/s]

2026-09-09 18:24:06,347 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.058s]
2026-09-09 18:24:06,389 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.041s]

Indexing Records:  27%|██▋       | 5991/22132 [02:20<17:27, 15.42it/s]

2026-09-09 18:24:06,434 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.042s]
2026-09-09 18:24:06,506 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.070s]

Indexing Records:  27%|██▋       | 5993/22132 [02:20<16:58, 15.84it/s]

2026-09-09 18:24:06,550 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.041s]
2026-09-09 18:24:06,635 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.083s]

Indexing Records:  27%|██▋       | 5995/22132 [02:20<17:03, 15.77it/s]

2026-09-09 18:24:06,714 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.077s]
2026-09-09 18:24:06,770 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.055s]

Indexing Records:  27%|██▋       | 5997/22132 [02:20<17:22, 15.47it/s]

2026-09-09 18:24:06,819 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.047s]
2026-09-09 18:24:06,866 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.045s]
2026-09-09 18:24:06,940 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.072s]

Indexing Records:  27%|██▋       | 6000/22132 [02:21<16:32, 16.25it/s]

2026-09-09 18:24:06,996 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.054s]
2026-09-09 18:24:07,048 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.051s]

Indexing Records:  27%|██▋       | 6002/22132 [02:21<16:02, 16.76it/s]

2026-09-09 18:24:07,115 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.064s]
2026-09-09 18:24:07,162 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.046s]

Indexing Records:  27%|██▋       | 6004/22132 [02:21<15:49, 16.99it/s]

2026-09-09 18:24:07,212 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.047s]
2026-09-09 18:24:07,267 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.054s]

Indexing Records:  27%|██▋       | 6006/22132 [02:21<15:21, 17.51it/s]

2026-09-09 18:24:07,325 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.056s]
2026-09-09 18:24:07,376 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.049s]

Indexing Records:  27%|██▋       | 6008/22132 [02:21<15:08, 17.75it/s]

2026-09-09 18:24:07,417 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.039s]
2026-09-09 18:24:07,451 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:24:07,522 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.069s]

Indexing Records:  27%|██▋       | 6011/22132 [02:21<14:20, 18.72it/s]

2026-09-09 18:24:07,578 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.053s]
2026-09-09 18:24:07,669 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.090s]

Indexing Records:  27%|██▋       | 6013/22132 [02:21<15:47, 17.02it/s]

2026-09-09 18:24:07,706 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]
2026-09-09 18:24:07,752 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.044s]
2026-09-09 18:24:07,786 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]

Indexing Records:  27%|██▋       | 6016/22132 [02:21<13:50, 19.41it/s]

2026-09-09 18:24:07,853 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.065s]
2026-09-09 18:24:07,898 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.044s]

Indexing Records:  27%|██▋       | 6018/22132 [02:22<14:09, 18.96it/s]

2026-09-09 18:24:07,958 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.057s]
2026-09-09 18:24:08,014 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.055s]

Indexing Records:  27%|██▋       | 6020/22132 [02:22<14:32, 18.46it/s]

2026-09-09 18:24:08,064 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.048s]
2026-09-09 18:24:08,103 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.038s]
2026-09-09 18:24:08,137 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]

Indexing Records:  27%|██▋       | 6023/22132 [02:22<13:15, 20.26it/s]

2026-09-09 18:24:08,190 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.050s]
2026-09-09 18:24:08,235 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.044s]
2026-09-09 18:24:08,282 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.045s]

Indexing Records:  27%|██▋       | 6026/22132 [02:22<13:09, 20.40it/s]

2026-09-09 18:24:08,331 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.046s]
2026-09-09 18:24:08,372 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.040s]
2026-09-09 18:24:08,426 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.053s]

Indexing Records:  27%|██▋       | 6029/22132 [02:22<13:02, 20.57it/s]

2026-09-09 18:24:08,474 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.046s]
2026-09-09 18:24:08,508 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]
2026-09-09 18:24:08,594 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.084s]

Indexing Records:  27%|██▋       | 6032/22132 [02:22<13:41, 19.60it/s]

2026-09-09 18:24:08,663 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.067s]
2026-09-09 18:24:08,706 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.041s]

Indexing Records:  27%|██▋       | 6034/22132 [02:22<14:00, 19.16it/s]

2026-09-09 18:24:08,769 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.061s]
2026-09-09 18:24:08,875 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.105s]

Indexing Records:  27%|██▋       | 6036/22132 [02:23<16:09, 16.60it/s]

2026-09-09 18:24:08,909 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:24:09,015 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.105s]

Indexing Records:  27%|██▋       | 6038/22132 [02:23<16:49, 15.94it/s]

2026-09-09 18:24:09,060 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.043s]
2026-09-09 18:24:09,141 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.079s]

Indexing Records:  27%|██▋       | 6040/22132 [02:23<16:50, 15.92it/s]

2026-09-09 18:24:09,189 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.046s]
2026-09-09 18:24:09,232 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.041s]
2026-09-09 18:24:09,280 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.047s]

Indexing Records:  27%|██▋       | 6043/22132 [02:23<15:14, 17.60it/s]

2026-09-09 18:24:09,325 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.042s]
2026-09-09 18:24:09,371 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.045s]
2026-09-09 18:24:09,415 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.042s]

Indexing Records:  27%|██▋       | 6046/22132 [02:23<14:07, 18.99it/s]

2026-09-09 18:24:09,453 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.037s]
2026-09-09 18:24:09,505 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.049s]
2026-09-09 18:24:09,566 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.060s]

Indexing Records:  27%|██▋       | 6049/22132 [02:23<13:54, 19.27it/s]

2026-09-09 18:24:09,639 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.071s]
2026-09-09 18:24:09,697 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.056s]

Indexing Records:  27%|██▋       | 6051/22132 [02:23<14:47, 18.13it/s]

2026-09-09 18:24:09,746 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.046s]
2026-09-09 18:24:09,805 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.058s]

Indexing Records:  27%|██▋       | 6053/22132 [02:23<14:43, 18.19it/s]

2026-09-09 18:24:09,877 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.069s]
2026-09-09 18:24:09,911 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]

Indexing Records:  27%|██▋       | 6055/22132 [02:24<14:33, 18.41it/s]

2026-09-09 18:24:09,958 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.045s]
2026-09-09 18:24:09,999 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.040s]
2026-09-09 18:24:10,033 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]

Indexing Records:  27%|██▋       | 6058/22132 [02:24<13:14, 20.24it/s]

2026-09-09 18:24:10,066 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:24:10,096 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:24:10,291 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.193s]

Indexing Records:  27%|██▋       | 6061/22132 [02:24<16:34, 16.16it/s]

2026-09-09 18:24:10,325 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:24:10,378 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.052s]
2026-09-09 18:24:10,441 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.061s]

Indexing Records:  27%|██▋       | 6064/22132 [02:24<15:31, 17.25it/s]

2026-09-09 18:24:10,483 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.040s]
2026-09-09 18:24:10,529 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.044s]
2026-09-09 18:24:10,557 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]

Indexing Records:  27%|██▋       | 6067/22132 [02:24<13:53, 19.27it/s]

2026-09-09 18:24:10,584 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:24:10,629 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.044s]
2026-09-09 18:24:10,650 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:10,677 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]

Indexing Records:  27%|██▋       | 6071/22132 [02:24<11:39, 22.95it/s]

2026-09-09 18:24:10,727 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.048s]
2026-09-09 18:24:10,747 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:10,769 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:10,794 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  27%|██▋       | 6075/22132 [02:24<10:18, 25.95it/s]

2026-09-09 18:24:10,838 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.042s]
2026-09-09 18:24:10,877 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.038s]
2026-09-09 18:24:10,925 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.046s]

Indexing Records:  27%|██▋       | 6078/22132 [02:25<10:41, 25.02it/s]

2026-09-09 18:24:10,948 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:10,969 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:11,002 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:24:11,030 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]

Indexing Records:  27%|██▋       | 6082/22132 [02:25<09:25, 28.39it/s]

2026-09-09 18:24:11,055 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:11,087 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:24:11,105 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:11,126 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:11,157 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]

Indexing Records:  28%|██▊       | 6087/22132 [02:25<08:25, 31.71it/s]

2026-09-09 18:24:11,180 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:11,225 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.043s]
2026-09-09 18:24:11,252 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:24:11,270 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  28%|██▊       | 6091/22132 [02:25<08:10, 32.70it/s]

2026-09-09 18:24:11,290 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:11,309 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:11,337 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:24:11,357 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:11,377 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  28%|██▊       | 6096/22132 [02:25<07:17, 36.62it/s]

2026-09-09 18:24:11,403 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:24:11,429 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:24:11,450 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:11,477 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]

Indexing Records:  28%|██▊       | 6100/22132 [02:25<07:07, 37.46it/s]

2026-09-09 18:24:11,499 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:11,518 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:11,536 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:11,555 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:11,577 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:11,598 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  28%|██▊       | 6106/22132 [02:25<06:27, 41.32it/s]

2026-09-09 18:24:11,617 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:11,636 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:11,657 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:11,678 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:11,697 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:11,717 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  28%|██▊       | 6112/22132 [02:25<06:02, 44.21it/s]

2026-09-09 18:24:11,737 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:11,759 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:11,778 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:11,797 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:11,821 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  28%|██▊       | 6117/22132 [02:25<05:54, 45.23it/s]

2026-09-09 18:24:11,841 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:11,918 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.076s]
2026-09-09 18:24:11,938 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:11,957 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:11,978 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  28%|██▊       | 6122/22132 [02:26<06:38, 40.21it/s]

2026-09-09 18:24:11,999 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:12,021 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:12,040 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:12,060 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:12,080 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  28%|██▊       | 6127/22132 [02:26<06:16, 42.48it/s]

2026-09-09 18:24:12,101 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:12,120 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:12,141 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:12,162 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:12,193 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]

Indexing Records:  28%|██▊       | 6132/22132 [02:26<06:12, 42.96it/s]

2026-09-09 18:24:12,214 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:12,888 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.673s]
2026-09-09 18:24:12,910 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:12,931 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:12,957 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  28%|██▊       | 6137/22132 [02:27<16:30, 16.14it/s]

2026-09-09 18:24:12,984 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:24:13,004 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:13,036 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:24:13,057 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  28%|██▊       | 6141/22132 [02:27<14:00, 19.02it/s]

2026-09-09 18:24:13,076 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:13,095 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:13,116 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:13,139 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:13,177 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.037s]

Indexing Records:  28%|██▊       | 6146/22132 [02:27<11:37, 22.92it/s]

2026-09-09 18:24:13,198 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:13,221 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:13,245 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:13,268 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:13,288 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  28%|██▊       | 6151/22132 [02:27<09:51, 27.02it/s]

2026-09-09 18:24:13,317 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:24:13,349 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:24:13,374 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:24:13,396 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  28%|██▊       | 6155/22132 [02:27<09:09, 29.07it/s]

2026-09-09 18:24:13,417 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:13,450 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:24:13,472 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:13,493 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:13,518 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  28%|██▊       | 6160/22132 [02:27<08:18, 32.02it/s]

2026-09-09 18:24:13,556 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]
2026-09-09 18:24:13,592 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]
2026-09-09 18:24:13,616 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:13,639 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  28%|██▊       | 6164/22132 [02:27<08:14, 32.31it/s]

2026-09-09 18:24:13,665 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:24:13,685 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:13,707 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:13,735 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:24:13,755 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  28%|██▊       | 6169/22132 [02:27<07:34, 35.09it/s]

2026-09-09 18:24:13,785 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:24:13,813 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:24:13,836 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:13,861 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  28%|██▊       | 6173/22132 [02:28<07:25, 35.80it/s]

2026-09-09 18:24:13,883 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:13,942 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.058s]
2026-09-09 18:24:13,965 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:13,984 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  28%|██▊       | 6177/22132 [02:28<07:37, 34.87it/s]

2026-09-09 18:24:14,003 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:14,022 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:14,043 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:14,062 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:14,087 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  28%|██▊       | 6182/22132 [02:28<06:54, 38.45it/s]

2026-09-09 18:24:14,107 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:14,126 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:14,145 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:14,173 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:24:14,194 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  28%|██▊       | 6187/22132 [02:28<06:31, 40.71it/s]

2026-09-09 18:24:14,217 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:14,246 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:24:14,269 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:14,289 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:14,312 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  28%|██▊       | 6192/22132 [02:28<06:26, 41.26it/s]

2026-09-09 18:24:14,332 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:14,354 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:14,375 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:14,398 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:14,419 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  28%|██▊       | 6197/22132 [02:28<06:11, 42.84it/s]

2026-09-09 18:24:14,440 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:14,459 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:14,486 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:24:14,511 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:14,530 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  28%|██▊       | 6202/22132 [02:28<06:06, 43.46it/s]

2026-09-09 18:24:14,552 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:14,571 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:14,593 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:14,613 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:14,633 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  28%|██▊       | 6207/22132 [02:28<05:55, 44.81it/s]

2026-09-09 18:24:14,656 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:14,678 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:14,698 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:14,743 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.043s]
2026-09-09 18:24:14,766 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  28%|██▊       | 6212/22132 [02:28<06:15, 42.39it/s]

2026-09-09 18:24:14,789 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:14,809 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:14,828 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:14,849 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:14,878 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]

Indexing Records:  28%|██▊       | 6217/22132 [02:29<06:10, 43.00it/s]

2026-09-09 18:24:14,902 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:14,922 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:14,953 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:24:15,021 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.066s]
2026-09-09 18:24:15,042 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  28%|██▊       | 6222/22132 [02:29<06:55, 38.27it/s]

2026-09-09 18:24:15,081 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.036s]
2026-09-09 18:24:15,101 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:15,123 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:15,143 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  28%|██▊       | 6226/22132 [02:29<06:51, 38.61it/s]

2026-09-09 18:24:15,169 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:15,190 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:15,209 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:15,231 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:15,265 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]

Indexing Records:  28%|██▊       | 6231/22132 [02:29<06:44, 39.33it/s]

2026-09-09 18:24:15,288 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:15,313 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:15,334 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:15,358 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:15,379 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  28%|██▊       | 6236/22132 [02:29<06:31, 40.62it/s]

2026-09-09 18:24:15,413 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:24:15,434 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:15,456 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:15,476 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:15,502 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]

Indexing Records:  28%|██▊       | 6241/22132 [02:29<06:31, 40.64it/s]

2026-09-09 18:24:15,523 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:15,545 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:15,564 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:15,596 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:24:15,625 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]

Indexing Records:  28%|██▊       | 6246/22132 [02:29<06:30, 40.70it/s]

2026-09-09 18:24:15,653 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:24:15,679 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:24:15,709 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:24:15,730 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:15,749 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  28%|██▊       | 6251/22132 [02:29<06:31, 40.55it/s]

2026-09-09 18:24:15,773 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:15,792 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:15,811 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:15,831 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:15,858 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]

Indexing Records:  28%|██▊       | 6256/22132 [02:29<06:17, 42.06it/s]

2026-09-09 18:24:15,886 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:24:15,919 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:24:15,941 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:15,962 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:15,986 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  28%|██▊       | 6261/22132 [02:30<06:25, 41.12it/s]

2026-09-09 18:24:16,007 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:16,026 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:16,075 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.047s]
2026-09-09 18:24:16,094 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:16,117 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  28%|██▊       | 6266/22132 [02:30<06:34, 40.19it/s]

2026-09-09 18:24:16,136 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:16,157 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:16,176 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:16,210 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]
2026-09-09 18:24:16,230 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  28%|██▊       | 6271/22132 [02:30<06:24, 41.29it/s]

2026-09-09 18:24:16,251 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:16,273 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:16,292 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:16,312 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:16,332 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  28%|██▊       | 6276/22132 [02:30<06:06, 43.30it/s]

2026-09-09 18:24:16,353 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:16,377 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:16,397 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:16,416 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:16,445 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]

Indexing Records:  28%|██▊       | 6281/22132 [02:30<06:03, 43.60it/s]

2026-09-09 18:24:16,466 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:16,489 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:16,543 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.053s]
2026-09-09 18:24:16,562 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:16,585 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  28%|██▊       | 6286/22132 [02:30<06:27, 40.93it/s]

2026-09-09 18:24:16,605 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:16,632 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:24:16,663 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:24:16,685 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:16,709 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  28%|██▊       | 6291/22132 [02:30<06:29, 40.71it/s]

2026-09-09 18:24:16,734 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:16,753 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:16,774 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:16,796 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:16,822 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  28%|██▊       | 6296/22132 [02:30<06:19, 41.74it/s]

2026-09-09 18:24:16,841 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:16,871 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:24:16,900 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:24:16,920 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:16,944 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  28%|██▊       | 6301/22132 [02:31<06:21, 41.55it/s]

2026-09-09 18:24:16,964 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:16,989 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:24:17,016 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:24:17,036 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:17,057 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  28%|██▊       | 6306/22132 [02:31<06:13, 42.33it/s]

2026-09-09 18:24:17,082 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:17,100 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:17,121 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:17,141 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:17,160 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  29%|██▊       | 6311/22132 [02:31<05:59, 43.99it/s]

2026-09-09 18:24:17,180 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:17,202 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:17,222 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:17,245 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:17,265 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  29%|██▊       | 6316/22132 [02:31<05:51, 44.99it/s]

2026-09-09 18:24:17,286 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:17,314 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:24:17,335 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:17,355 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:17,385 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]

Indexing Records:  29%|██▊       | 6321/22132 [02:31<05:59, 43.94it/s]

2026-09-09 18:24:17,412 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:24:17,431 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:17,453 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:17,473 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:17,493 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  29%|██▊       | 6326/22132 [02:31<05:53, 44.67it/s]

2026-09-09 18:24:17,514 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:17,536 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:17,557 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:17,578 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:17,599 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  29%|██▊       | 6331/22132 [02:31<05:48, 45.34it/s]

2026-09-09 18:24:17,623 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:17,646 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:17,665 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:17,687 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:17,708 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  29%|██▊       | 6336/22132 [02:31<05:47, 45.45it/s]

2026-09-09 18:24:17,734 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:24:17,753 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:17,773 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:17,793 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:17,814 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  29%|██▊       | 6341/22132 [02:31<05:43, 45.94it/s]

2026-09-09 18:24:17,835 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:17,855 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:17,875 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:17,912 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.036s]
2026-09-09 18:24:17,931 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  29%|██▊       | 6346/22132 [02:32<05:50, 44.99it/s]

2026-09-09 18:24:17,959 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:24:17,979 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:18,004 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:24:18,025 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:18,046 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  29%|██▊       | 6351/22132 [02:32<05:54, 44.50it/s]

2026-09-09 18:24:18,067 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:18,095 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:24:18,125 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:24:18,146 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:18,165 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  29%|██▊       | 6356/22132 [02:32<06:00, 43.73it/s]

2026-09-09 18:24:18,194 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:24:18,218 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:18,240 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:18,265 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:18,288 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  29%|██▊       | 6361/22132 [02:32<06:08, 42.75it/s]

2026-09-09 18:24:18,314 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:24:18,340 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:24:18,360 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:18,383 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:18,403 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  29%|██▉       | 6366/22132 [02:32<06:06, 42.99it/s]

2026-09-09 18:24:18,422 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:18,451 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:24:18,469 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:18,490 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:18,510 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  29%|██▉       | 6371/22132 [02:32<05:57, 44.11it/s]

2026-09-09 18:24:18,530 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:18,554 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:18,578 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:18,599 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:18,626 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]

Indexing Records:  29%|██▉       | 6376/22132 [02:32<05:59, 43.79it/s]

2026-09-09 18:24:18,646 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:18,666 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:18,698 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:24:18,717 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:18,736 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  29%|██▉       | 6381/22132 [02:32<05:56, 44.17it/s]

2026-09-09 18:24:18,758 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:18,781 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:18,801 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:18,821 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:18,840 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  29%|██▉       | 6386/22132 [02:32<05:47, 45.30it/s]

2026-09-09 18:24:18,861 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:18,882 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:18,903 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:18,925 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:18,944 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  29%|██▉       | 6391/22132 [02:33<05:41, 46.08it/s]

2026-09-09 18:24:18,964 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:18,983 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:19,007 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:19,038 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:24:19,060 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  29%|██▉       | 6396/22132 [02:33<05:48, 45.21it/s]

2026-09-09 18:24:19,085 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:19,104 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:19,123 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:19,146 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:19,165 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  29%|██▉       | 6401/22132 [02:33<05:43, 45.85it/s]

2026-09-09 18:24:19,184 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:19,203 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:19,223 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:19,242 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:19,261 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:19,282 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  29%|██▉       | 6407/22132 [02:33<05:29, 47.67it/s]

2026-09-09 18:24:19,305 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:19,325 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:19,348 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:19,373 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:24:19,394 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  29%|██▉       | 6412/22132 [02:33<05:36, 46.70it/s]

2026-09-09 18:24:19,416 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:19,436 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:19,456 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:19,478 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:19,497 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  29%|██▉       | 6417/22132 [02:33<05:32, 47.20it/s]

2026-09-09 18:24:19,517 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:19,552 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]
2026-09-09 18:24:19,572 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:19,595 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:19,617 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  29%|██▉       | 6422/22132 [02:33<05:45, 45.46it/s]

2026-09-09 18:24:19,638 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:19,658 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:19,678 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:19,700 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:19,721 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  29%|██▉       | 6427/22132 [02:33<05:39, 46.23it/s]

2026-09-09 18:24:19,742 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:19,762 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:19,797 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]
2026-09-09 18:24:19,820 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:19,841 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  29%|██▉       | 6432/22132 [02:33<05:50, 44.79it/s]

2026-09-09 18:24:19,863 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:19,882 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:19,904 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:19,924 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:19,944 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  29%|██▉       | 6437/22132 [02:34<05:42, 45.76it/s]

2026-09-09 18:24:19,965 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:19,993 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:24:20,014 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:20,034 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:20,054 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  29%|██▉       | 6442/22132 [02:34<05:43, 45.65it/s]

2026-09-09 18:24:20,077 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:20,095 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:20,114 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:20,135 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:20,153 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:20,177 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  29%|██▉       | 6448/22132 [02:34<05:36, 46.66it/s]

2026-09-09 18:24:20,209 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:24:20,234 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:24:20,253 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:20,274 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:20,291 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  29%|██▉       | 6453/22132 [02:34<05:41, 45.87it/s]

2026-09-09 18:24:20,313 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:20,332 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:20,352 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:20,376 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:20,396 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  29%|██▉       | 6458/22132 [02:34<05:37, 46.37it/s]

2026-09-09 18:24:20,419 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:20,441 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:20,460 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:20,480 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:20,499 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  29%|██▉       | 6463/22132 [02:34<05:33, 46.93it/s]

2026-09-09 18:24:20,521 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:20,542 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:20,564 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:20,584 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:20,607 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  29%|██▉       | 6468/22132 [02:34<05:34, 46.80it/s]

2026-09-09 18:24:20,628 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:20,649 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:20,685 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]
2026-09-09 18:24:20,707 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:20,728 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  29%|██▉       | 6473/22132 [02:34<05:47, 45.04it/s]

2026-09-09 18:24:20,748 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:20,769 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:20,788 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:20,809 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:20,828 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  29%|██▉       | 6478/22132 [02:34<05:37, 46.40it/s]

2026-09-09 18:24:20,848 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:20,867 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:20,903 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]
2026-09-09 18:24:20,929 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:24:20,948 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  29%|██▉       | 6483/22132 [02:35<05:48, 44.88it/s]

2026-09-09 18:24:20,972 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:20,994 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:21,014 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:21,033 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:21,052 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  29%|██▉       | 6488/22132 [02:35<05:41, 45.75it/s]

2026-09-09 18:24:21,072 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:21,092 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:21,110 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:21,129 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:21,150 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:21,171 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  29%|██▉       | 6494/22132 [02:35<05:30, 47.28it/s]

2026-09-09 18:24:21,192 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:21,211 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:21,231 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:21,251 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:21,270 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:21,290 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  29%|██▉       | 6500/22132 [02:35<05:23, 48.29it/s]

2026-09-09 18:24:21,320 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:24:21,341 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:21,362 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:21,381 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:21,401 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  29%|██▉       | 6505/22132 [02:35<05:30, 47.33it/s]

2026-09-09 18:24:21,421 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:21,444 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:21,466 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:21,487 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:21,507 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  29%|██▉       | 6510/22132 [02:35<05:31, 47.18it/s]

2026-09-09 18:24:21,530 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:21,549 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:21,570 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:21,596 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:24:21,616 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  29%|██▉       | 6515/22132 [02:35<05:33, 46.80it/s]

2026-09-09 18:24:21,649 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:24:21,668 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:21,687 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:21,707 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:21,727 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  29%|██▉       | 6520/22132 [02:35<05:36, 46.34it/s]

2026-09-09 18:24:21,747 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:21,768 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:21,789 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:21,810 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:21,831 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  29%|██▉       | 6525/22132 [02:35<05:32, 46.88it/s]

2026-09-09 18:24:21,851 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:21,869 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:21,889 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:21,909 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:21,943 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]

Indexing Records:  30%|██▉       | 6530/22132 [02:36<05:37, 46.17it/s]

2026-09-09 18:24:21,967 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:21,996 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:24:22,017 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:22,039 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:22,058 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  30%|██▉       | 6535/22132 [02:36<05:44, 45.31it/s]

2026-09-09 18:24:22,079 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:22,099 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:22,118 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:22,141 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:22,160 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  30%|██▉       | 6540/22132 [02:36<05:36, 46.37it/s]

2026-09-09 18:24:22,182 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:22,202 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:22,222 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:22,242 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:22,263 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  30%|██▉       | 6545/22132 [02:36<05:32, 46.92it/s]

2026-09-09 18:24:22,284 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:22,304 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:22,339 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]
2026-09-09 18:24:22,360 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:22,380 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  30%|██▉       | 6550/22132 [02:36<05:41, 45.66it/s]

2026-09-09 18:24:22,400 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:22,420 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:22,440 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:22,460 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:22,484 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  30%|██▉       | 6555/22132 [02:36<05:35, 46.39it/s]

2026-09-09 18:24:22,505 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:22,529 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:22,550 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:22,569 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:22,594 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  30%|██▉       | 6560/22132 [02:36<05:38, 46.06it/s]

2026-09-09 18:24:22,615 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:22,634 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:22,656 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:22,676 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:22,696 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  30%|██▉       | 6565/22132 [02:36<05:31, 46.96it/s]

2026-09-09 18:24:22,715 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:22,735 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:22,766 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:24:22,785 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:22,804 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  30%|██▉       | 6570/22132 [02:36<05:33, 46.73it/s]

2026-09-09 18:24:22,825 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:22,844 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:22,864 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:22,884 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:22,903 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:22,923 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  30%|██▉       | 6576/22132 [02:37<05:24, 47.90it/s]

2026-09-09 18:24:22,943 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:22,967 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:22,986 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:23,015 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:24:23,035 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  30%|██▉       | 6581/22132 [02:37<05:31, 46.92it/s]

2026-09-09 18:24:23,060 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:23,091 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:24:23,110 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:23,129 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:23,149 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  30%|██▉       | 6586/22132 [02:37<05:37, 46.00it/s]

2026-09-09 18:24:23,168 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:23,187 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:23,206 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:23,226 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:23,245 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:23,266 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  30%|██▉       | 6592/22132 [02:37<05:26, 47.65it/s]

2026-09-09 18:24:23,287 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:23,308 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:23,327 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:23,347 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:23,366 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  30%|██▉       | 6597/22132 [02:37<05:22, 48.19it/s]

2026-09-09 18:24:23,391 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:23,414 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:23,435 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:23,455 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:23,475 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  30%|██▉       | 6602/22132 [02:37<05:26, 47.50it/s]

2026-09-09 18:24:23,508 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:24:23,528 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:23,547 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:23,568 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:23,589 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  30%|██▉       | 6607/22132 [02:37<05:34, 46.45it/s]

2026-09-09 18:24:23,609 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:23,628 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:23,650 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:23,670 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:23,706 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]

Indexing Records:  30%|██▉       | 6612/22132 [02:37<05:42, 45.30it/s]

2026-09-09 18:24:23,753 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.045s]
2026-09-09 18:24:23,794 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.040s]
2026-09-09 18:24:23,813 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:23,835 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:23,856 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  30%|██▉       | 6617/22132 [02:37<06:19, 40.90it/s]

2026-09-09 18:24:23,895 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.036s]
2026-09-09 18:24:23,921 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:24:23,952 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:24:23,976 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:24,001 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  30%|██▉       | 6622/22132 [02:38<06:40, 38.75it/s]

2026-09-09 18:24:24,050 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.047s]
2026-09-09 18:24:24,075 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:24:24,103 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:24:24,122 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  30%|██▉       | 6626/22132 [02:38<06:57, 37.14it/s]

2026-09-09 18:24:24,162 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.037s]
2026-09-09 18:24:24,182 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:24,201 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:24,222 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:24,244 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  30%|██▉       | 6631/22132 [02:38<06:45, 38.23it/s]

2026-09-09 18:24:24,267 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:24,289 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:24,366 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.076s]
2026-09-09 18:24:24,388 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  30%|██▉       | 6635/22132 [02:38<07:24, 34.84it/s]

2026-09-09 18:24:24,413 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:24,437 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:24,469 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:24:24,491 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  30%|██▉       | 6639/22132 [02:38<07:12, 35.86it/s]

2026-09-09 18:24:24,515 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:24,559 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.043s]
2026-09-09 18:24:24,593 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]
2026-09-09 18:24:24,615 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  30%|███       | 6643/22132 [02:38<07:25, 34.73it/s]

2026-09-09 18:24:24,638 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:24,663 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:24:24,687 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:24,708 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:24,726 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  30%|███       | 6648/22132 [02:38<06:51, 37.60it/s]

2026-09-09 18:24:24,750 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:24,771 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:24,801 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:24:24,823 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:24,842 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  30%|███       | 6653/22132 [02:38<06:34, 39.20it/s]

2026-09-09 18:24:24,865 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:24,888 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:24,912 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:24,934 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:24,953 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  30%|███       | 6658/22132 [02:39<06:18, 40.90it/s]

2026-09-09 18:24:24,973 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:24,996 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:25,016 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:25,041 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:25,060 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  30%|███       | 6663/22132 [02:39<06:03, 42.58it/s]

2026-09-09 18:24:25,080 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:25,103 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:25,128 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:24:25,149 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:25,171 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  30%|███       | 6668/22132 [02:39<05:57, 43.31it/s]

2026-09-09 18:24:25,191 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:25,218 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:24:25,237 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:25,258 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:25,283 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  30%|███       | 6673/22132 [02:39<05:53, 43.74it/s]

2026-09-09 18:24:25,304 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:25,324 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:25,343 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:25,363 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:25,381 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:25,402 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  30%|███       | 6679/22132 [02:39<05:37, 45.77it/s]

2026-09-09 18:24:25,421 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:25,443 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:25,461 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:25,482 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:25,500 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:25,521 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  30%|███       | 6685/22132 [02:39<05:26, 47.24it/s]

2026-09-09 18:24:25,540 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:25,561 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:25,580 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:25,601 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:25,622 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  30%|███       | 6690/22132 [02:39<05:22, 47.89it/s]

2026-09-09 18:24:25,641 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:25,662 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:25,682 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:25,703 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:25,723 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  30%|███       | 6695/22132 [02:39<05:19, 48.32it/s]

2026-09-09 18:24:25,743 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:25,764 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:25,785 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:25,806 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:25,827 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  30%|███       | 6700/22132 [02:39<05:20, 48.16it/s]

2026-09-09 18:24:25,854 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:24:25,884 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:24:25,930 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.044s]
2026-09-09 18:24:25,966 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]
2026-09-09 18:24:25,994 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]

Indexing Records:  30%|███       | 6705/22132 [02:40<06:16, 40.94it/s]

2026-09-09 18:24:26,025 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:24:26,072 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.046s]
2026-09-09 18:24:26,090 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:26,110 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:26,135 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  30%|███       | 6710/22132 [02:40<06:34, 39.08it/s]

2026-09-09 18:24:26,161 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:26,190 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:24:26,217 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:24:26,245 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:24:26,265 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  30%|███       | 6715/22132 [02:40<06:35, 38.96it/s]

2026-09-09 18:24:26,293 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:24:26,324 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:24:26,361 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]
2026-09-09 18:24:26,380 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  30%|███       | 6719/22132 [02:40<06:48, 37.77it/s]

2026-09-09 18:24:26,414 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:24:26,436 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:26,455 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:26,477 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:26,512 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]

Indexing Records:  30%|███       | 6724/22132 [02:40<06:46, 37.86it/s]

2026-09-09 18:24:26,533 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:26,552 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:26,577 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:24:26,625 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.046s]

Indexing Records:  30%|███       | 6728/22132 [02:40<06:54, 37.13it/s]

2026-09-09 18:24:26,645 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:26,666 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:26,693 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:24:26,712 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:26,735 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  30%|███       | 6733/22132 [02:40<06:30, 39.40it/s]

2026-09-09 18:24:26,764 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:24:26,787 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:26,812 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:24:26,832 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:26,853 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  30%|███       | 6738/22132 [02:40<06:21, 40.31it/s]

2026-09-09 18:24:26,875 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:26,895 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:26,916 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:26,936 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:26,955 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  30%|███       | 6743/22132 [02:41<06:00, 42.65it/s]

2026-09-09 18:24:26,974 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:26,995 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:27,017 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:27,038 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:27,060 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  30%|███       | 6748/22132 [02:41<05:49, 44.02it/s]

2026-09-09 18:24:27,081 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:27,099 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:27,122 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:27,146 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:27,172 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]

Indexing Records:  31%|███       | 6753/22132 [02:41<05:47, 44.22it/s]

2026-09-09 18:24:27,194 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:27,219 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:24:27,238 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:27,259 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:27,278 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  31%|███       | 6758/22132 [02:41<05:40, 45.10it/s]

2026-09-09 18:24:27,301 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:27,322 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:27,343 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:27,363 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:27,391 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]

Indexing Records:  31%|███       | 6763/22132 [02:41<05:42, 44.89it/s]

2026-09-09 18:24:27,414 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:27,434 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:27,457 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:27,477 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:27,495 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  31%|███       | 6768/22132 [02:41<05:35, 45.75it/s]

2026-09-09 18:24:27,514 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:27,535 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:27,555 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:27,576 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:27,597 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  31%|███       | 6773/22132 [02:41<05:28, 46.70it/s]

2026-09-09 18:24:27,619 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:27,638 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:27,658 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:27,685 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:24:27,705 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  31%|███       | 6778/22132 [02:41<05:29, 46.58it/s]

2026-09-09 18:24:27,726 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:27,747 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:27,767 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:27,788 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:27,806 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  31%|███       | 6783/22132 [02:41<05:24, 47.37it/s]

2026-09-09 18:24:27,827 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:27,846 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:27,866 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:27,884 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:27,904 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:27,925 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  31%|███       | 6789/22132 [02:42<05:17, 48.37it/s]

2026-09-09 18:24:27,947 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:27,966 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:27,986 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:28,009 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:28,031 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  31%|███       | 6794/22132 [02:42<05:18, 48.09it/s]

2026-09-09 18:24:28,052 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:28,074 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:28,093 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:28,112 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:28,133 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  31%|███       | 6799/22132 [02:42<05:16, 48.41it/s]

2026-09-09 18:24:28,154 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:28,173 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:28,194 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:28,213 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:28,234 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  31%|███       | 6804/22132 [02:42<05:14, 48.70it/s]

2026-09-09 18:24:28,254 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:28,274 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:28,292 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:28,312 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:28,331 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:28,351 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  31%|███       | 6810/22132 [02:42<05:09, 49.45it/s]

2026-09-09 18:24:28,374 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:28,396 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:28,417 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:28,437 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:28,456 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  31%|███       | 6815/22132 [02:42<05:12, 48.95it/s]

2026-09-09 18:24:28,476 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:28,497 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:28,518 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:28,540 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:28,559 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  31%|███       | 6820/22132 [02:42<05:13, 48.87it/s]

2026-09-09 18:24:28,581 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:28,601 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:28,622 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:28,643 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:28,665 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  31%|███       | 6825/22132 [02:42<05:16, 48.32it/s]

2026-09-09 18:24:28,686 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:28,705 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:28,729 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:28,750 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:28,770 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  31%|███       | 6830/22132 [02:42<05:17, 48.13it/s]

2026-09-09 18:24:28,794 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:28,812 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:28,830 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:28,849 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:28,866 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:28,884 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  31%|███       | 6836/22132 [02:43<05:08, 49.51it/s]

2026-09-09 18:24:28,902 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:28,919 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:28,939 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:28,958 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:28,974 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:28,990 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  31%|███       | 6842/22132 [02:43<04:56, 51.59it/s]

2026-09-09 18:24:29,009 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:29,025 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:29,043 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:29,060 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:29,077 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:29,101 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  31%|███       | 6848/22132 [02:43<04:51, 52.38it/s]

2026-09-09 18:24:29,119 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:29,138 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:29,175 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.036s]
2026-09-09 18:24:29,193 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:29,210 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:29,228 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  31%|███       | 6854/22132 [02:43<05:01, 50.65it/s]

2026-09-09 18:24:29,247 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:29,264 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:29,281 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:29,299 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:29,316 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:29,332 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  31%|███       | 6860/22132 [02:43<04:49, 52.67it/s]

2026-09-09 18:24:29,349 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:29,367 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:29,383 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:29,400 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:29,417 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:29,435 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  31%|███       | 6866/22132 [02:43<04:41, 54.24it/s]

2026-09-09 18:24:29,454 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:29,471 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:29,489 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:29,506 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:29,524 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:29,541 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  31%|███       | 6872/22132 [02:43<04:37, 54.94it/s]

2026-09-09 18:24:29,558 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:29,575 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:29,592 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:29,609 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:29,630 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:29,649 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  31%|███       | 6878/22132 [02:43<04:36, 55.19it/s]

2026-09-09 18:24:29,671 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:29,697 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:24:29,717 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:29,736 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:29,757 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:29,775 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  31%|███       | 6884/22132 [02:43<04:49, 52.60it/s]

2026-09-09 18:24:29,796 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:29,816 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:29,840 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:29,860 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:29,878 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:29,896 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  31%|███       | 6890/22132 [02:44<04:54, 51.69it/s]

2026-09-09 18:24:29,927 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:24:29,957 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:24:29,976 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:29,996 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:30,019 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:30,041 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  31%|███       | 6896/22132 [02:44<05:17, 48.02it/s]

2026-09-09 18:24:30,061 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:30,080 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:30,109 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:24:30,127 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:30,149 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  31%|███       | 6901/22132 [02:44<05:19, 47.63it/s]

2026-09-09 18:24:30,172 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:30,194 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:30,227 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:24:30,250 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:30,271 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  31%|███       | 6906/22132 [02:44<05:33, 45.61it/s]

2026-09-09 18:24:30,288 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:30,306 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:30,325 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:30,343 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:30,360 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:30,378 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  31%|███       | 6912/22132 [02:44<05:13, 48.48it/s]

2026-09-09 18:24:30,404 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:24:30,423 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:30,444 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:30,462 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:30,478 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  31%|███▏      | 6917/22132 [02:44<05:11, 48.82it/s]

2026-09-09 18:24:30,498 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:30,516 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:30,532 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:30,553 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:30,571 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:30,588 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  31%|███▏      | 6923/22132 [02:44<05:00, 50.53it/s]

2026-09-09 18:24:30,606 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:30,623 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:30,639 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:30,656 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:30,673 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:30,693 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  31%|███▏      | 6929/22132 [02:44<04:50, 52.41it/s]

2026-09-09 18:24:30,713 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:30,730 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:30,747 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:30,765 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:30,787 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:30,809 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  31%|███▏      | 6935/22132 [02:44<04:50, 52.26it/s]

2026-09-09 18:24:30,831 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:30,862 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:24:30,888 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:24:30,906 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:30,927 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:30,952 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  31%|███▏      | 6941/22132 [02:45<05:12, 48.62it/s]

2026-09-09 18:24:30,975 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:30,996 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:31,025 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:24:31,052 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:24:31,075 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  31%|███▏      | 6946/22132 [02:45<05:28, 46.22it/s]

2026-09-09 18:24:31,102 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:24:31,120 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:31,144 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:31,165 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:31,186 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  31%|███▏      | 6951/22132 [02:45<05:31, 45.82it/s]

2026-09-09 18:24:31,211 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:31,236 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:24:31,257 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:31,287 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:24:31,309 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  31%|███▏      | 6956/22132 [02:45<05:43, 44.23it/s]

2026-09-09 18:24:31,330 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:31,352 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:31,371 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:31,392 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:31,413 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  31%|███▏      | 6961/22132 [02:45<05:35, 45.26it/s]

2026-09-09 18:24:31,432 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:31,452 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:31,470 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:31,487 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:31,509 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:31,531 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  31%|███▏      | 6967/22132 [02:45<05:22, 46.99it/s]

2026-09-09 18:24:31,552 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:31,571 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:31,591 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:31,608 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:31,626 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:31,643 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  32%|███▏      | 6973/22132 [02:45<05:09, 48.98it/s]

2026-09-09 18:24:31,663 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:31,680 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:31,698 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:31,716 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:31,734 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:31,751 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  32%|███▏      | 6979/22132 [02:45<04:57, 50.89it/s]

2026-09-09 18:24:31,771 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:31,789 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:31,810 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:31,826 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:24:31,842 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:31,860 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  32%|███▏      | 6985/22132 [02:46<04:51, 51.99it/s]

2026-09-09 18:24:31,878 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:31,894 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:31,911 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:31,930 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:31,946 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:31,964 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  32%|███▏      | 6991/22132 [02:46<04:42, 53.61it/s]

2026-09-09 18:24:31,982 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:32,000 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:32,016 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:32,035 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:32,053 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:32,071 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  32%|███▏      | 6997/22132 [02:46<04:38, 54.43it/s]

2026-09-09 18:24:32,088 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:32,104 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:32,120 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:32,141 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:32,158 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:32,174 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  32%|███▏      | 7003/22132 [02:46<04:32, 55.48it/s]

2026-09-09 18:24:32,192 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:32,211 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:32,231 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:32,247 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:32,265 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:32,282 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  32%|███▏      | 7009/22132 [02:46<04:32, 55.54it/s]

2026-09-09 18:24:32,301 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:32,318 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:32,335 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:32,351 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:32,368 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:32,386 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  32%|███▏      | 7015/22132 [02:46<04:28, 56.21it/s]

2026-09-09 18:24:32,404 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:32,421 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:32,442 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:32,460 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:32,477 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:32,495 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  32%|███▏      | 7021/22132 [02:46<04:31, 55.75it/s]

2026-09-09 18:24:32,514 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:32,533 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:32,550 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:32,568 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:32,585 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:32,605 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  32%|███▏      | 7027/22132 [02:46<04:32, 55.48it/s]

2026-09-09 18:24:32,623 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:32,640 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:32,659 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:32,676 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:32,693 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:32,713 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  32%|███▏      | 7033/22132 [02:46<04:32, 55.51it/s]

2026-09-09 18:24:32,730 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:32,748 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:32,765 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:32,781 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:32,798 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:32,816 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  32%|███▏      | 7039/22132 [02:46<04:28, 56.22it/s]

2026-09-09 18:24:32,835 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:32,856 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:32,872 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:32,889 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:32,905 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:32,924 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  32%|███▏      | 7045/22132 [02:47<04:29, 56.02it/s]

2026-09-09 18:24:32,943 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:32,959 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:32,977 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:32,994 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:33,011 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:33,027 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  32%|███▏      | 7051/22132 [02:47<04:26, 56.64it/s]

2026-09-09 18:24:33,046 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:33,064 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:33,081 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:33,097 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:33,116 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:33,133 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  32%|███▏      | 7057/22132 [02:47<04:26, 56.67it/s]

2026-09-09 18:24:33,153 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:33,169 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:33,187 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:33,204 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:33,221 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:24:33,237 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  32%|███▏      | 7063/22132 [02:47<04:24, 56.99it/s]

2026-09-09 18:24:33,254 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:33,271 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:33,288 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:33,306 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:33,330 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:33,355 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  32%|███▏      | 7069/22132 [02:47<04:33, 55.06it/s]

2026-09-09 18:24:33,373 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:33,391 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:33,409 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:33,427 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:33,446 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:33,464 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  32%|███▏      | 7075/22132 [02:47<04:33, 55.04it/s]

2026-09-09 18:24:33,480 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:33,497 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:33,513 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:33,532 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:33,549 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:33,566 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  32%|███▏      | 7081/22132 [02:47<04:28, 56.04it/s]

2026-09-09 18:24:33,586 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:33,604 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:33,621 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:33,637 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:33,654 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:33,672 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  32%|███▏      | 7087/22132 [02:47<04:27, 56.26it/s]

2026-09-09 18:24:33,699 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:24:33,718 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:33,739 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:33,759 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:33,780 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:33,801 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  32%|███▏      | 7093/22132 [02:47<04:44, 52.90it/s]

2026-09-09 18:24:33,823 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:33,843 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:33,866 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:33,886 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:33,905 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:33,927 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  32%|███▏      | 7099/22132 [02:48<04:53, 51.28it/s]

2026-09-09 18:24:33,948 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:33,967 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:33,988 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:34,011 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:34,031 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:34,052 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  32%|███▏      | 7105/22132 [02:48<04:59, 50.19it/s]

2026-09-09 18:24:34,072 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:34,092 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:34,111 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:34,128 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:34,153 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:34,171 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  32%|███▏      | 7111/22132 [02:48<04:58, 50.26it/s]

2026-09-09 18:24:34,190 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:34,210 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:34,242 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:24:34,264 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:34,283 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:34,301 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  32%|███▏      | 7117/22132 [02:48<05:06, 48.92it/s]

2026-09-09 18:24:34,322 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:34,340 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:34,360 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:34,380 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:34,399 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:34,418 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  32%|███▏      | 7123/22132 [02:48<05:02, 49.68it/s]

2026-09-09 18:24:34,435 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:34,454 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:34,474 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:34,495 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:34,516 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:34,536 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  32%|███▏      | 7129/22132 [02:48<04:59, 50.02it/s]

2026-09-09 18:24:34,555 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:34,574 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:34,593 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:34,612 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:34,633 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:34,650 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  32%|███▏      | 7135/22132 [02:48<04:55, 50.75it/s]

2026-09-09 18:24:34,669 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:34,688 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:34,708 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:34,727 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:34,749 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:34,768 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  32%|███▏      | 7141/22132 [02:48<04:55, 50.75it/s]

2026-09-09 18:24:34,787 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:34,809 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:34,828 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:34,850 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:34,873 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:34,893 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  32%|███▏      | 7147/22132 [02:49<04:59, 49.97it/s]

2026-09-09 18:24:34,916 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:34,935 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:34,953 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:34,971 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:34,990 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:35,015 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  32%|███▏      | 7153/22132 [02:49<05:01, 49.67it/s]

2026-09-09 18:24:35,035 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:35,055 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:35,074 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:35,095 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:35,118 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  32%|███▏      | 7158/22132 [02:49<05:03, 49.36it/s]

2026-09-09 18:24:35,142 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:35,173 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:24:35,198 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:24:35,224 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:24:35,247 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  32%|███▏      | 7163/22132 [02:49<05:25, 45.93it/s]

2026-09-09 18:24:35,282 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]
2026-09-09 18:24:35,322 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.038s]
2026-09-09 18:24:35,359 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.036s]
2026-09-09 18:24:35,398 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.038s]
2026-09-09 18:24:35,449 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.049s]

Indexing Records:  32%|███▏      | 7168/22132 [02:49<06:43, 37.07it/s]

2026-09-09 18:24:35,485 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]
2026-09-09 18:24:35,517 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:24:35,537 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:35,560 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  32%|███▏      | 7172/22132 [02:49<06:46, 36.76it/s]

2026-09-09 18:24:35,591 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:24:35,613 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:35,650 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]
2026-09-09 18:24:35,675 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  32%|███▏      | 7176/22132 [02:49<06:53, 36.21it/s]

2026-09-09 18:24:35,724 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.047s]
2026-09-09 18:24:35,758 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:24:35,784 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:24:35,803 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  32%|███▏      | 7180/22132 [02:49<07:09, 34.81it/s]

2026-09-09 18:24:35,823 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:35,852 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:24:35,872 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:35,904 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]

Indexing Records:  32%|███▏      | 7184/22132 [02:50<06:55, 36.01it/s]

2026-09-09 18:24:35,937 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:24:35,958 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:35,984 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:24:36,014 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]

Indexing Records:  32%|███▏      | 7188/22132 [02:50<06:54, 36.10it/s]

2026-09-09 18:24:36,040 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:24:36,090 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.049s]
2026-09-09 18:24:36,113 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:36,141 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]

Indexing Records:  32%|███▏      | 7192/22132 [02:50<07:11, 34.65it/s]

2026-09-09 18:24:36,172 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:24:36,201 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:24:36,236 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]
2026-09-09 18:24:36,286 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.048s]

Indexing Records:  33%|███▎      | 7196/22132 [02:50<07:43, 32.21it/s]

2026-09-09 18:24:36,322 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]
2026-09-09 18:24:36,355 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:24:36,406 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.049s]
2026-09-09 18:24:36,433 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]

Indexing Records:  33%|███▎      | 7200/22132 [02:50<08:09, 30.53it/s]

2026-09-09 18:24:36,455 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:36,476 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:36,505 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:24:36,553 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.046s]

Indexing Records:  33%|███▎      | 7204/22132 [02:50<07:56, 31.35it/s]

2026-09-09 18:24:36,572 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:36,625 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.051s]
2026-09-09 18:24:36,646 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:36,709 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.061s]

Indexing Records:  33%|███▎      | 7208/22132 [02:50<08:27, 29.39it/s]

2026-09-09 18:24:36,733 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:36,765 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:24:36,786 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:36,825 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.038s]

Indexing Records:  33%|███▎      | 7212/22132 [02:50<08:05, 30.71it/s]

2026-09-09 18:24:36,847 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:36,867 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:36,891 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:36,910 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:36,932 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  33%|███▎      | 7217/22132 [02:51<07:06, 34.94it/s]

2026-09-09 18:24:36,953 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:36,984 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:24:37,005 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:37,030 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:37,059 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]

Indexing Records:  33%|███▎      | 7222/22132 [02:51<06:51, 36.24it/s]

2026-09-09 18:24:37,086 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:24:37,128 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.040s]
2026-09-09 18:24:37,158 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:24:37,178 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  33%|███▎      | 7226/22132 [02:51<07:00, 35.47it/s]

2026-09-09 18:24:37,201 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:37,239 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.037s]
2026-09-09 18:24:37,276 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]
2026-09-09 18:24:37,297 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  33%|███▎      | 7230/22132 [02:51<07:06, 34.94it/s]

2026-09-09 18:24:37,322 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:37,352 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:24:37,370 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:37,393 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:37,418 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  33%|███▎      | 7235/22132 [02:51<06:44, 36.84it/s]

2026-09-09 18:24:37,447 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:24:37,481 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]
2026-09-09 18:24:37,507 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:24:37,550 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.042s]

Indexing Records:  33%|███▎      | 7239/22132 [02:51<07:08, 34.75it/s]

2026-09-09 18:24:37,578 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:24:37,599 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:37,627 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:24:37,662 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]

Indexing Records:  33%|███▎      | 7243/22132 [02:51<07:04, 35.09it/s]

2026-09-09 18:24:37,702 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.038s]
2026-09-09 18:24:37,731 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:24:37,763 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:24:37,787 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  33%|███▎      | 7247/22132 [02:51<07:16, 34.09it/s]

2026-09-09 18:24:37,807 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:37,841 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]
2026-09-09 18:24:37,863 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:37,882 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:37,906 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  33%|███▎      | 7252/22132 [02:52<06:48, 36.41it/s]

2026-09-09 18:24:37,929 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:37,948 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:37,969 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:37,996 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:24:38,029 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]

Indexing Records:  33%|███▎      | 7257/22132 [02:52<06:34, 37.68it/s]

2026-09-09 18:24:38,064 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:24:38,084 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:38,104 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:38,126 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:38,157 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]

Indexing Records:  33%|███▎      | 7262/22132 [02:52<06:29, 38.14it/s]

2026-09-09 18:24:38,198 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.039s]
2026-09-09 18:24:38,220 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:38,243 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:38,287 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.042s]

Indexing Records:  33%|███▎      | 7266/22132 [02:52<06:54, 35.88it/s]

2026-09-09 18:24:38,309 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:38,328 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:38,348 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:38,384 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]
2026-09-09 18:24:38,409 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  33%|███▎      | 7271/22132 [02:52<06:38, 37.32it/s]

2026-09-09 18:24:38,434 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:38,455 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:38,473 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:38,492 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:38,515 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  33%|███▎      | 7276/22132 [02:52<06:11, 39.95it/s]

2026-09-09 18:24:38,535 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:38,555 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:38,574 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:38,594 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:38,614 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:38,635 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  33%|███▎      | 7282/22132 [02:52<05:45, 43.03it/s]

2026-09-09 18:24:38,657 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:38,683 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:24:38,702 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:38,721 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:38,740 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  33%|███▎      | 7287/22132 [02:52<05:35, 44.25it/s]

2026-09-09 18:24:38,762 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:38,783 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:38,802 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:38,822 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:38,841 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  33%|███▎      | 7292/22132 [02:52<05:24, 45.77it/s]

2026-09-09 18:24:38,859 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:38,889 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:24:38,908 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:38,928 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:38,959 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]

Indexing Records:  33%|███▎      | 7297/22132 [02:53<05:32, 44.61it/s]

2026-09-09 18:24:38,984 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:39,011 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:24:39,038 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:24:39,061 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:39,082 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  33%|███▎      | 7302/22132 [02:53<05:41, 43.40it/s]

2026-09-09 18:24:39,110 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:24:39,130 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:39,149 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:39,178 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:24:39,196 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  33%|███▎      | 7307/22132 [02:53<05:40, 43.49it/s]

2026-09-09 18:24:39,221 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:39,254 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:24:39,274 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:39,295 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:39,315 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  33%|███▎      | 7312/22132 [02:53<05:44, 43.03it/s]

2026-09-09 18:24:39,336 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:39,357 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:39,379 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:39,399 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:39,471 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.071s]

Indexing Records:  33%|███▎      | 7317/22132 [02:53<06:19, 39.05it/s]

2026-09-09 18:24:39,493 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:39,515 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:39,534 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:39,552 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:39,571 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:39,592 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  33%|███▎      | 7323/22132 [02:53<05:51, 42.10it/s]

2026-09-09 18:24:39,614 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:39,636 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:39,659 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:39,678 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:39,697 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  33%|███▎      | 7328/22132 [02:53<05:39, 43.55it/s]

2026-09-09 18:24:39,725 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:24:39,745 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:39,763 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:39,783 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:39,801 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  33%|███▎      | 7333/22132 [02:53<05:30, 44.73it/s]

2026-09-09 18:24:39,821 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:39,839 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:39,857 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:39,878 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:39,898 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:39,916 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  33%|███▎      | 7339/22132 [02:54<05:14, 47.01it/s]

2026-09-09 18:24:39,938 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:39,956 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:39,976 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:39,997 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:40,018 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  33%|███▎      | 7344/22132 [02:54<05:10, 47.57it/s]

2026-09-09 18:24:40,037 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:40,056 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:40,075 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:40,095 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:40,114 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:40,133 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  33%|███▎      | 7350/22132 [02:54<05:02, 48.94it/s]

2026-09-09 18:24:40,153 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:40,177 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:40,196 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:40,216 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:40,239 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  33%|███▎      | 7355/22132 [02:54<05:05, 48.42it/s]

2026-09-09 18:24:40,261 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:40,305 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.043s]
2026-09-09 18:24:40,324 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:40,348 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:40,368 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  33%|███▎      | 7360/22132 [02:54<05:26, 45.21it/s]

2026-09-09 18:24:40,388 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:40,406 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:40,427 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:40,447 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:40,466 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:40,484 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  33%|███▎      | 7366/22132 [02:54<05:12, 47.19it/s]

2026-09-09 18:24:40,504 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:40,523 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:40,543 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:40,563 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:40,583 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:40,602 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  33%|███▎      | 7372/22132 [02:54<05:05, 48.25it/s]

2026-09-09 18:24:40,623 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:40,643 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:40,663 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:40,683 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:40,702 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:40,725 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  33%|███▎      | 7378/22132 [02:54<05:04, 48.43it/s]

2026-09-09 18:24:40,744 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:40,763 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:40,781 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:40,801 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:40,819 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:40,838 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  33%|███▎      | 7384/22132 [02:54<04:56, 49.80it/s]

2026-09-09 18:24:40,860 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:40,878 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:40,896 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:40,916 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:40,934 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:40,952 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  33%|███▎      | 7390/22132 [02:55<04:51, 50.64it/s]

2026-09-09 18:24:40,977 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:40,995 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:41,015 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:41,035 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:41,056 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:41,074 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  33%|███▎      | 7396/22132 [02:55<04:53, 50.18it/s]

2026-09-09 18:24:41,093 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:41,115 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:41,133 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:41,163 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:24:41,185 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:41,206 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  33%|███▎      | 7402/22132 [02:55<05:02, 48.67it/s]

2026-09-09 18:24:41,230 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:41,249 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:41,273 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:41,291 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:41,309 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  33%|███▎      | 7407/22132 [02:55<05:02, 48.67it/s]

2026-09-09 18:24:41,328 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:41,346 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:41,366 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:41,385 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:41,405 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:41,423 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  33%|███▎      | 7413/22132 [02:55<04:55, 49.77it/s]

2026-09-09 18:24:41,445 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:41,464 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:41,483 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:41,504 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:41,523 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  34%|███▎      | 7418/22132 [02:55<04:55, 49.82it/s]

2026-09-09 18:24:41,545 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:41,564 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:41,584 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:41,606 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:41,625 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  34%|███▎      | 7423/22132 [02:55<04:56, 49.60it/s]

2026-09-09 18:24:41,649 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:41,668 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:41,688 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:41,707 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:41,726 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  34%|███▎      | 7428/22132 [02:55<04:56, 49.64it/s]

2026-09-09 18:24:41,747 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:41,765 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:41,786 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:41,805 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:41,824 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:41,844 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  34%|███▎      | 7434/22132 [02:55<04:53, 50.06it/s]

2026-09-09 18:24:41,863 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:41,883 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:41,901 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:41,920 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:41,941 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:41,959 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  34%|███▎      | 7440/22132 [02:56<04:50, 50.66it/s]

2026-09-09 18:24:41,981 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:42,000 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:42,020 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:42,038 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:42,058 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:42,076 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  34%|███▎      | 7446/22132 [02:56<04:48, 50.87it/s]

2026-09-09 18:24:42,100 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:42,134 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:24:42,182 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.047s]
2026-09-09 18:24:42,214 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:24:42,239 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:42,299 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.058s]

Indexing Records:  34%|███▎      | 7452/22132 [02:56<06:07, 39.92it/s]

2026-09-09 18:24:42,345 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.045s]
2026-09-09 18:24:42,370 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:24:42,424 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.052s]
2026-09-09 18:24:42,455 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:24:42,479 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  34%|███▎      | 7457/22132 [02:56<06:51, 35.67it/s]

2026-09-09 18:24:42,509 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:24:42,533 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:42,565 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:24:42,589 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  34%|███▎      | 7461/22132 [02:56<06:49, 35.86it/s]

2026-09-09 18:24:42,615 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:24:42,657 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.040s]
2026-09-09 18:24:42,688 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:24:42,731 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.042s]

Indexing Records:  34%|███▎      | 7465/22132 [02:56<07:17, 33.54it/s]

2026-09-09 18:24:42,754 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:42,773 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:42,792 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:42,811 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:42,831 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:42,850 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  34%|███▍      | 7471/22132 [02:56<06:25, 38.05it/s]

2026-09-09 18:24:42,869 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:42,898 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:24:42,918 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:42,943 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:42,963 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  34%|███▍      | 7476/22132 [02:57<06:09, 39.68it/s]

2026-09-09 18:24:42,989 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:24:43,019 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:24:43,049 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:24:43,082 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:24:43,108 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]

Indexing Records:  34%|███▍      | 7481/22132 [02:57<06:26, 37.92it/s]

2026-09-09 18:24:43,136 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:24:43,158 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:43,184 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:24:43,215 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]

Indexing Records:  34%|███▍      | 7485/22132 [02:57<06:27, 37.85it/s]

2026-09-09 18:24:43,238 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:43,262 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:43,288 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:24:43,313 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:43,338 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  34%|███▍      | 7490/22132 [02:57<06:19, 38.62it/s]

2026-09-09 18:24:43,365 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:24:43,392 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:24:43,415 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:43,438 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:43,465 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]

Indexing Records:  34%|███▍      | 7495/22132 [02:57<06:16, 38.85it/s]

2026-09-09 18:24:43,492 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:24:43,513 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:43,536 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:43,554 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:43,573 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  34%|███▍      | 7500/22132 [02:57<05:58, 40.84it/s]

2026-09-09 18:24:43,594 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:43,613 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:43,636 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:43,670 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]
2026-09-09 18:24:43,694 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  34%|███▍      | 7505/22132 [02:57<05:56, 41.01it/s]

2026-09-09 18:24:43,715 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:43,737 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:43,756 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:43,777 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:43,795 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  34%|███▍      | 7510/22132 [02:57<05:37, 43.30it/s]

2026-09-09 18:24:43,815 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:43,834 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:43,854 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:43,876 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:43,896 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  34%|███▍      | 7515/22132 [02:58<05:25, 44.93it/s]

2026-09-09 18:24:43,918 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:43,936 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:43,956 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:43,980 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:43,999 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  34%|███▍      | 7520/22132 [02:58<05:17, 46.07it/s]

2026-09-09 18:24:44,028 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:24:44,050 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:44,077 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:24:44,110 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:24:44,134 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  34%|███▍      | 7525/22132 [02:58<05:40, 42.88it/s]

2026-09-09 18:24:44,175 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.039s]
2026-09-09 18:24:44,205 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:24:44,228 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:44,250 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:44,271 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  34%|███▍      | 7530/22132 [02:58<05:58, 40.73it/s]

2026-09-09 18:24:44,295 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:44,316 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:44,340 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:44,368 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:24:44,393 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  34%|███▍      | 7535/22132 [02:58<05:57, 40.81it/s]

2026-09-09 18:24:44,416 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:44,448 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:24:44,467 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:44,493 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:24:44,522 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]

Indexing Records:  34%|███▍      | 7540/22132 [02:58<06:03, 40.19it/s]

2026-09-09 18:24:44,546 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:44,569 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:44,587 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:44,614 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:24:44,642 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]

Indexing Records:  34%|███▍      | 7545/22132 [02:58<05:59, 40.61it/s]

2026-09-09 18:24:44,662 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:44,691 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:24:44,715 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:44,734 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:44,756 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  34%|███▍      | 7550/22132 [02:58<05:51, 41.53it/s]

2026-09-09 18:24:44,781 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:44,802 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:44,831 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:24:44,850 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:44,875 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  34%|███▍      | 7555/22132 [02:59<05:49, 41.68it/s]

2026-09-09 18:24:44,896 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:44,921 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:24:44,939 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:44,964 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:44,988 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  34%|███▍      | 7560/22132 [02:59<05:43, 42.43it/s]

2026-09-09 18:24:45,009 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:45,029 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:45,053 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:45,073 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:45,092 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  34%|███▍      | 7565/22132 [02:59<05:31, 43.89it/s]

2026-09-09 18:24:45,119 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:24:45,144 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:24:45,164 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:45,183 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:45,202 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  34%|███▍      | 7570/22132 [02:59<05:28, 44.35it/s]

2026-09-09 18:24:45,221 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:45,240 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:45,261 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:45,283 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:45,304 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  34%|███▍      | 7575/22132 [02:59<05:18, 45.77it/s]

2026-09-09 18:24:45,324 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:45,343 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:45,362 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:45,384 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:45,403 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:45,424 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  34%|███▍      | 7581/22132 [02:59<05:09, 47.08it/s]

2026-09-09 18:24:45,446 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:45,470 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:45,488 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:45,508 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:45,527 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  34%|███▍      | 7586/22132 [02:59<05:06, 47.48it/s]

2026-09-09 18:24:45,547 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:45,566 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:45,586 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:45,606 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:45,625 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:45,644 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  34%|███▍      | 7592/22132 [02:59<04:58, 48.70it/s]

2026-09-09 18:24:45,663 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:45,682 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:45,704 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:45,727 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:45,746 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  34%|███▍      | 7597/22132 [02:59<04:58, 48.72it/s]

2026-09-09 18:24:45,766 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:45,787 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:45,806 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:45,827 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:45,848 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  34%|███▍      | 7602/22132 [02:59<04:57, 48.88it/s]

2026-09-09 18:24:45,867 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:45,886 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:45,905 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:45,926 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:45,946 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:45,965 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  34%|███▍      | 7608/22132 [03:00<04:52, 49.59it/s]

2026-09-09 18:24:45,987 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:46,006 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:46,026 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:46,044 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:46,064 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:46,084 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  34%|███▍      | 7614/22132 [03:00<04:50, 49.93it/s]

2026-09-09 18:24:46,114 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:24:46,137 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:46,158 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:46,177 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:46,196 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  34%|███▍      | 7619/22132 [03:00<05:00, 48.31it/s]

2026-09-09 18:24:46,217 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:46,240 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:46,261 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:46,280 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:46,300 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  34%|███▍      | 7624/22132 [03:00<05:00, 48.28it/s]

2026-09-09 18:24:46,319 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:46,339 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:46,357 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:46,376 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:46,395 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:46,415 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  34%|███▍      | 7630/22132 [03:00<04:53, 49.40it/s]

2026-09-09 18:24:46,435 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:46,456 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:46,475 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:46,506 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:24:46,525 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  34%|███▍      | 7635/22132 [03:00<05:00, 48.32it/s]

2026-09-09 18:24:46,544 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:46,563 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:46,582 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:46,602 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:46,622 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:46,641 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  35%|███▍      | 7641/22132 [03:00<04:53, 49.32it/s]

2026-09-09 18:24:46,662 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:46,681 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:46,702 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:46,720 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:46,739 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:46,758 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  35%|███▍      | 7647/22132 [03:00<04:49, 49.97it/s]

2026-09-09 18:24:46,798 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.038s]
2026-09-09 18:24:46,914 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.115s]
2026-09-09 18:24:46,933 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:46,953 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:46,971 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  35%|███▍      | 7652/22132 [03:01<06:19, 38.12it/s]

2026-09-09 18:24:46,990 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:47,009 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:47,033 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:47,049 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:47,069 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:47,091 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  35%|███▍      | 7658/22132 [03:01<05:50, 41.24it/s]

2026-09-09 18:24:47,148 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.054s]
2026-09-09 18:24:47,167 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:47,185 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:47,202 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:47,220 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  35%|███▍      | 7663/22132 [03:01<05:56, 40.61it/s]

2026-09-09 18:24:47,238 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:47,254 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:47,272 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:47,290 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:47,313 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:47,331 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  35%|███▍      | 7669/22132 [03:01<05:28, 44.05it/s]

2026-09-09 18:24:47,349 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:47,365 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:47,382 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:47,400 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:47,417 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:47,438 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  35%|███▍      | 7675/22132 [03:01<05:05, 47.31it/s]

2026-09-09 18:24:47,458 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:47,474 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:47,491 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:47,507 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:47,525 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:47,546 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  35%|███▍      | 7681/22132 [03:01<04:51, 49.57it/s]

2026-09-09 18:24:47,567 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:47,584 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:47,603 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:47,621 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:47,639 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:47,660 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  35%|███▍      | 7687/22132 [03:01<04:46, 50.46it/s]

2026-09-09 18:24:47,680 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:47,701 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:47,722 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:47,741 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:47,759 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:47,778 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  35%|███▍      | 7693/22132 [03:01<04:45, 50.55it/s]

2026-09-09 18:24:47,798 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:47,817 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:47,836 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:47,862 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:24:47,888 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:24:47,909 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  35%|███▍      | 7699/22132 [03:02<04:54, 49.01it/s]

2026-09-09 18:24:47,929 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:47,951 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:47,971 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:48,043 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.071s]
2026-09-09 18:24:48,065 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  35%|███▍      | 7704/22132 [03:02<05:35, 43.02it/s]

2026-09-09 18:24:48,087 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:48,109 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:48,129 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:48,150 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:48,176 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]

Indexing Records:  35%|███▍      | 7709/22132 [03:02<05:31, 43.52it/s]

2026-09-09 18:24:48,199 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:48,224 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:24:48,245 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:48,265 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:48,289 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  35%|███▍      | 7714/22132 [03:02<05:29, 43.70it/s]

2026-09-09 18:24:48,317 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:24:48,339 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:48,362 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:48,384 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:48,407 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  35%|███▍      | 7719/22132 [03:02<05:32, 43.35it/s]

2026-09-09 18:24:48,431 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:48,454 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:48,479 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:48,504 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:24:48,528 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  35%|███▍      | 7724/22132 [03:02<05:37, 42.72it/s]

2026-09-09 18:24:48,563 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]
2026-09-09 18:24:48,590 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:24:48,611 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:48,657 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.045s]
2026-09-09 18:24:48,701 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.042s]

Indexing Records:  35%|███▍      | 7729/22132 [03:02<06:24, 37.47it/s]

2026-09-09 18:24:48,762 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.058s]
2026-09-09 18:24:48,786 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:48,830 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.042s]
2026-09-09 18:24:48,879 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.048s]

Indexing Records:  35%|███▍      | 7733/22132 [03:03<07:28, 32.11it/s]

2026-09-09 18:24:48,917 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.036s]
2026-09-09 18:24:48,948 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:24:48,994 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.044s]
2026-09-09 18:24:49,023 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]

Indexing Records:  35%|███▍      | 7737/22132 [03:03<07:47, 30.82it/s]

2026-09-09 18:24:49,054 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:24:49,100 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.044s]
2026-09-09 18:24:49,153 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.052s]
2026-09-09 18:24:49,180 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]

Indexing Records:  35%|███▍      | 7741/22132 [03:03<08:13, 29.18it/s]

2026-09-09 18:24:49,216 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]
2026-09-09 18:24:49,235 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:49,254 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:49,279 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:49,301 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  35%|███▍      | 7746/22132 [03:03<07:25, 32.27it/s]

2026-09-09 18:24:49,322 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:49,341 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:49,365 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:49,385 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:49,405 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  35%|███▌      | 7751/22132 [03:03<06:38, 36.08it/s]

2026-09-09 18:24:49,427 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:49,447 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:49,467 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:49,488 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:49,508 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  35%|███▌      | 7756/22132 [03:03<06:06, 39.18it/s]

2026-09-09 18:24:49,529 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:49,555 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:24:49,575 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:49,599 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:49,623 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  35%|███▌      | 7761/22132 [03:03<05:55, 40.45it/s]

2026-09-09 18:24:49,645 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:49,667 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:49,688 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:49,716 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:24:49,737 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  35%|███▌      | 7766/22132 [03:03<05:46, 41.44it/s]

2026-09-09 18:24:49,757 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:49,780 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:49,808 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:24:49,829 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:49,852 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  35%|███▌      | 7771/22132 [03:03<05:42, 41.98it/s]

2026-09-09 18:24:49,876 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:49,897 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:49,918 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:49,948 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:24:49,970 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  35%|███▌      | 7776/22132 [03:04<05:40, 42.16it/s]

2026-09-09 18:24:49,995 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:50,017 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:50,039 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:50,063 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:50,084 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  35%|███▌      | 7781/22132 [03:04<05:36, 42.67it/s]

2026-09-09 18:24:50,107 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:50,129 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:50,166 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.036s]
2026-09-09 18:24:50,190 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:50,212 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  35%|███▌      | 7786/22132 [03:04<05:46, 41.45it/s]

2026-09-09 18:24:50,242 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:24:50,264 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:50,286 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:50,311 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:50,332 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  35%|███▌      | 7791/22132 [03:04<05:45, 41.53it/s]

2026-09-09 18:24:50,355 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:50,376 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:50,397 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:50,420 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:50,441 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  35%|███▌      | 7796/22132 [03:04<05:35, 42.75it/s]

2026-09-09 18:24:50,465 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:50,486 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:50,509 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:50,529 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:50,550 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  35%|███▌      | 7801/22132 [03:04<05:28, 43.67it/s]

2026-09-09 18:24:50,574 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:50,595 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:50,619 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:50,639 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:50,660 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  35%|███▌      | 7806/22132 [03:04<05:24, 44.21it/s]

2026-09-09 18:24:50,684 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:50,705 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:50,732 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:24:50,805 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.071s]
2026-09-09 18:24:50,826 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  35%|███▌      | 7811/22132 [03:04<06:09, 38.72it/s]

2026-09-09 18:24:50,854 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:24:50,877 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:50,902 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:24:50,928 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:24:50,957 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]

Indexing Records:  35%|███▌      | 7816/22132 [03:05<06:10, 38.60it/s]

2026-09-09 18:24:50,987 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:24:51,014 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:24:51,038 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:51,060 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  35%|███▌      | 7820/22132 [03:05<06:10, 38.64it/s]

2026-09-09 18:24:51,084 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:51,241 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.156s]
2026-09-09 18:24:51,280 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.037s]
2026-09-09 18:24:51,313 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]

Indexing Records:  35%|███▌      | 7824/22132 [03:05<08:33, 27.88it/s]

2026-09-09 18:24:51,340 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:24:51,363 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:51,382 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:51,402 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:51,421 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  35%|███▌      | 7829/22132 [03:05<07:26, 32.01it/s]

2026-09-09 18:24:51,441 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:51,463 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:51,483 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:51,502 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:51,521 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:51,540 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  35%|███▌      | 7835/22132 [03:05<06:28, 36.77it/s]

2026-09-09 18:24:51,560 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:51,581 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:51,606 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:51,626 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:51,649 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  35%|███▌      | 7840/22132 [03:05<06:05, 39.13it/s]

2026-09-09 18:24:51,669 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:51,690 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:51,709 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:51,728 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:51,755 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]

Indexing Records:  35%|███▌      | 7845/22132 [03:05<05:46, 41.20it/s]

2026-09-09 18:24:51,775 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:51,795 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:51,817 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:51,838 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:51,860 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  35%|███▌      | 7850/22132 [03:06<05:32, 42.96it/s]

2026-09-09 18:24:51,881 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:51,903 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:51,925 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:51,945 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:51,970 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  35%|███▌      | 7855/22132 [03:06<05:26, 43.66it/s]

2026-09-09 18:24:51,990 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:52,014 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:52,039 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:52,062 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:52,082 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  36%|███▌      | 7860/22132 [03:06<05:24, 43.93it/s]

2026-09-09 18:24:52,114 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:24:52,137 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:52,172 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]
2026-09-09 18:24:52,206 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:24:52,231 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  36%|███▌      | 7865/22132 [03:06<05:55, 40.15it/s]

2026-09-09 18:24:52,256 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:52,275 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:52,297 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:52,316 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:52,337 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  36%|███▌      | 7870/22132 [03:06<05:38, 42.08it/s]

2026-09-09 18:24:52,357 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:52,377 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:52,398 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:52,416 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:52,436 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:52,460 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  36%|███▌      | 7876/22132 [03:06<05:22, 44.14it/s]

2026-09-09 18:24:52,481 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:52,502 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:52,521 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:52,540 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:52,560 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  36%|███▌      | 7881/22132 [03:06<05:12, 45.63it/s]

2026-09-09 18:24:52,580 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:52,598 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:52,618 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:52,639 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:52,658 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:52,686 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]

Indexing Records:  36%|███▌      | 7887/22132 [03:06<05:07, 46.28it/s]

2026-09-09 18:24:52,707 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:52,727 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:52,746 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:52,765 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:52,784 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:52,803 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  36%|███▌      | 7893/22132 [03:06<04:58, 47.74it/s]

2026-09-09 18:24:52,824 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:52,844 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:52,875 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:24:52,897 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:52,916 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  36%|███▌      | 7898/22132 [03:07<05:04, 46.76it/s]

2026-09-09 18:24:52,936 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:52,960 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:52,980 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:53,001 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:53,021 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  36%|███▌      | 7903/22132 [03:07<05:02, 47.07it/s]

2026-09-09 18:24:53,041 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:53,062 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:53,083 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:53,103 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:53,122 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  36%|███▌      | 7908/22132 [03:07<04:58, 47.70it/s]

2026-09-09 18:24:53,142 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:53,173 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:24:53,192 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:53,211 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:53,230 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  36%|███▌      | 7913/22132 [03:07<05:01, 47.22it/s]

2026-09-09 18:24:53,250 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:53,269 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:53,288 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:53,308 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:53,328 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:53,348 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  36%|███▌      | 7919/22132 [03:07<04:53, 48.36it/s]

2026-09-09 18:24:53,368 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:53,389 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:53,409 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:53,430 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:53,450 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  36%|███▌      | 7924/22132 [03:07<04:52, 48.61it/s]

2026-09-09 18:24:53,471 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:53,491 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:53,513 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:53,534 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:53,555 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  36%|███▌      | 7929/22132 [03:07<04:54, 48.29it/s]

2026-09-09 18:24:53,584 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:24:53,605 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:53,625 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:53,645 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:53,665 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  36%|███▌      | 7934/22132 [03:07<04:59, 47.41it/s]

2026-09-09 18:24:53,692 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:53,711 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:53,731 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:53,750 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:53,772 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  36%|███▌      | 7939/22132 [03:07<05:00, 47.25it/s]

2026-09-09 18:24:53,792 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:53,813 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:53,835 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:53,854 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:53,884 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]

Indexing Records:  36%|███▌      | 7944/22132 [03:08<05:05, 46.49it/s]

2026-09-09 18:24:53,930 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.045s]
2026-09-09 18:24:53,950 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:53,971 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:53,992 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:54,011 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  36%|███▌      | 7949/22132 [03:08<05:22, 43.98it/s]

2026-09-09 18:24:54,033 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:54,054 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:54,075 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:54,095 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:54,115 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  36%|███▌      | 7954/22132 [03:08<05:13, 45.21it/s]

2026-09-09 18:24:54,135 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:54,170 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]
2026-09-09 18:24:54,189 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:54,210 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:54,231 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  36%|███▌      | 7959/22132 [03:08<05:18, 44.53it/s]

2026-09-09 18:24:54,252 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:54,270 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:54,290 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:54,309 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:54,328 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:54,349 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  36%|███▌      | 7965/22132 [03:08<05:04, 46.53it/s]

2026-09-09 18:24:54,369 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:54,389 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:54,408 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:54,427 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:54,447 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:54,467 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  36%|███▌      | 7971/22132 [03:08<04:55, 47.85it/s]

2026-09-09 18:24:54,488 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:54,508 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:54,529 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:54,550 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:54,569 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  36%|███▌      | 7976/22132 [03:08<04:54, 48.12it/s]

2026-09-09 18:24:54,590 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:54,609 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:54,628 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:54,650 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:54,669 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:54,690 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  36%|███▌      | 7982/22132 [03:08<04:51, 48.59it/s]

2026-09-09 18:24:54,720 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:24:54,739 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:54,761 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:54,783 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:54,802 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  36%|███▌      | 7987/22132 [03:08<04:58, 47.41it/s]

2026-09-09 18:24:54,823 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:54,842 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:54,862 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:54,883 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:54,902 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:54,922 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  36%|███▌      | 7993/22132 [03:09<04:52, 48.34it/s]

2026-09-09 18:24:54,944 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:54,973 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:24:54,993 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:55,038 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.044s]
2026-09-09 18:24:55,072 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]

Indexing Records:  36%|███▌      | 7998/22132 [03:09<05:29, 42.85it/s]

2026-09-09 18:24:55,133 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.058s]
2026-09-09 18:24:55,154 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:55,174 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:55,200 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:24:55,232 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]

Indexing Records:  36%|███▌      | 8003/22132 [03:09<06:04, 38.79it/s]

2026-09-09 18:24:55,256 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:55,279 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:55,301 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:55,320 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:55,339 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  36%|███▌      | 8008/22132 [03:09<05:46, 40.78it/s]

2026-09-09 18:24:55,360 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:55,379 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:55,398 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:55,418 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:55,439 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:55,459 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  36%|███▌      | 8014/22132 [03:09<05:24, 43.50it/s]

2026-09-09 18:24:55,480 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:55,499 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:55,520 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:55,539 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:55,559 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  36%|███▌      | 8019/22132 [03:09<05:13, 45.08it/s]

2026-09-09 18:24:55,581 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:55,602 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:55,622 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:55,642 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:55,661 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  36%|███▋      | 8024/22132 [03:09<05:05, 46.21it/s]

2026-09-09 18:24:55,681 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:55,701 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:55,726 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:55,748 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:55,772 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  36%|███▋      | 8029/22132 [03:09<05:07, 45.90it/s]

2026-09-09 18:24:55,793 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:55,812 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:55,832 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:55,851 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:55,872 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  36%|███▋      | 8034/22132 [03:10<05:00, 46.94it/s]

2026-09-09 18:24:55,892 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:55,913 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:55,935 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:55,956 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:55,976 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  36%|███▋      | 8039/22132 [03:10<04:58, 47.27it/s]

2026-09-09 18:24:55,998 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:56,017 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:56,037 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:56,056 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:56,076 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:56,095 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  36%|███▋      | 8045/22132 [03:10<04:51, 48.31it/s]

2026-09-09 18:24:56,116 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:56,137 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:56,162 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:56,183 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:56,203 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  36%|███▋      | 8050/22132 [03:10<04:55, 47.73it/s]

2026-09-09 18:24:56,232 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:24:56,257 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:24:56,277 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:56,297 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:56,317 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  36%|███▋      | 8055/22132 [03:10<05:02, 46.51it/s]

2026-09-09 18:24:56,338 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:56,361 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:56,380 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:56,401 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:56,420 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  36%|███▋      | 8060/22132 [03:10<04:58, 47.07it/s]

2026-09-09 18:24:56,441 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:56,462 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:56,482 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:56,501 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:56,520 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:56,540 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  36%|███▋      | 8066/22132 [03:10<04:52, 48.12it/s]

2026-09-09 18:24:56,560 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:56,581 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:56,601 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:56,620 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:56,641 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  36%|███▋      | 8071/22132 [03:10<04:50, 48.44it/s]

2026-09-09 18:24:56,661 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:56,683 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:56,703 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:56,722 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:56,746 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  36%|███▋      | 8076/22132 [03:10<04:51, 48.26it/s]

2026-09-09 18:24:56,765 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:56,786 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:56,805 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:56,825 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:56,844 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:56,862 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  37%|███▋      | 8082/22132 [03:11<04:45, 49.28it/s]

2026-09-09 18:24:56,884 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:56,904 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:56,926 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:56,947 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:56,966 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  37%|███▋      | 8087/22132 [03:11<04:46, 48.97it/s]

2026-09-09 18:24:56,986 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:57,006 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:57,026 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:57,045 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:57,066 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:57,087 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  37%|███▋      | 8093/22132 [03:11<04:45, 49.13it/s]

2026-09-09 18:24:57,107 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:57,128 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:57,149 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:57,171 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:57,190 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  37%|███▋      | 8098/22132 [03:11<04:46, 48.96it/s]

2026-09-09 18:24:57,212 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:57,231 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:57,250 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:57,271 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:57,291 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  37%|███▋      | 8103/22132 [03:11<04:45, 49.09it/s]

2026-09-09 18:24:57,312 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:57,332 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:57,354 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:57,375 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:57,394 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  37%|███▋      | 8108/22132 [03:11<04:46, 49.00it/s]

2026-09-09 18:24:57,416 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:57,438 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:57,498 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.058s]
2026-09-09 18:24:57,518 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:57,539 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  37%|███▋      | 8113/22132 [03:11<05:21, 43.64it/s]

2026-09-09 18:24:57,559 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:57,580 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:57,603 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:57,625 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:57,649 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  37%|███▋      | 8118/22132 [03:11<05:17, 44.10it/s]

2026-09-09 18:24:57,672 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:57,692 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:57,711 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:57,732 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:57,760 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]

Indexing Records:  37%|███▋      | 8123/22132 [03:11<05:15, 44.37it/s]

2026-09-09 18:24:57,782 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:57,802 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:57,822 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:57,842 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:57,863 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  37%|███▋      | 8128/22132 [03:12<05:07, 45.53it/s]

2026-09-09 18:24:57,884 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:57,945 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.059s]
2026-09-09 18:24:57,967 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:57,988 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:58,008 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  37%|███▋      | 8133/22132 [03:12<05:36, 41.57it/s]

2026-09-09 18:24:58,029 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:58,049 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:58,068 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:58,090 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:58,110 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  37%|███▋      | 8138/22132 [03:12<05:20, 43.61it/s]

2026-09-09 18:24:58,229 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.117s]
2026-09-09 18:24:58,251 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:58,270 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:58,292 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:58,312 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  37%|███▋      | 8143/22132 [03:12<06:34, 35.49it/s]

2026-09-09 18:24:58,334 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:58,354 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:58,375 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:58,395 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:58,417 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  37%|███▋      | 8148/22132 [03:12<06:03, 38.44it/s]

2026-09-09 18:24:58,469 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.050s]
2026-09-09 18:24:58,488 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:58,506 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:58,524 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:58,543 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  37%|███▋      | 8153/22132 [03:12<06:00, 38.81it/s]

2026-09-09 18:24:58,561 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:58,583 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:58,602 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:58,633 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:24:58,651 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  37%|███▋      | 8158/22132 [03:12<05:42, 40.75it/s]

2026-09-09 18:24:58,674 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:58,691 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:58,709 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:58,726 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:58,743 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:58,760 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  37%|███▋      | 8164/22132 [03:12<05:12, 44.76it/s]

2026-09-09 18:24:58,778 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:58,796 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:58,813 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:58,832 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:58,850 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:58,867 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  37%|███▋      | 8170/22132 [03:13<04:51, 47.92it/s]

2026-09-09 18:24:58,886 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:58,903 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:58,921 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:58,938 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:58,955 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:58,972 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  37%|███▋      | 8176/22132 [03:13<04:36, 50.49it/s]

2026-09-09 18:24:58,991 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:59,012 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:59,035 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:59,052 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:24:59,070 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:24:59,088 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  37%|███▋      | 8182/22132 [03:13<04:34, 50.82it/s]

2026-09-09 18:24:59,111 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:59,137 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:24:59,155 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:59,177 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:59,195 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:24:59,215 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  37%|███▋      | 8188/22132 [03:13<04:40, 49.68it/s]

2026-09-09 18:24:59,240 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:24:59,264 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:59,285 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:59,318 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:24:59,341 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:59,366 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  37%|███▋      | 8194/22132 [03:13<05:02, 46.08it/s]

2026-09-09 18:24:59,388 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:59,409 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:59,429 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:59,452 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:59,474 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  37%|███▋      | 8199/22132 [03:13<05:01, 46.24it/s]

2026-09-09 18:24:59,496 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:59,516 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:59,540 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:59,562 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:59,582 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  37%|███▋      | 8204/22132 [03:13<05:01, 46.23it/s]

2026-09-09 18:24:59,603 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:59,626 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:59,648 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:59,668 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:59,691 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  37%|███▋      | 8209/22132 [03:13<05:02, 46.09it/s]

2026-09-09 18:24:59,716 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:59,736 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:24:59,759 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:24:59,788 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:24:59,809 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  37%|███▋      | 8214/22132 [03:13<05:09, 45.02it/s]

2026-09-09 18:24:59,831 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:59,852 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:59,873 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:24:59,896 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:59,919 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  37%|███▋      | 8219/22132 [03:14<05:08, 45.09it/s]

2026-09-09 18:24:59,941 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:24:59,964 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:24:59,989 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:25:00,020 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:25:00,041 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  37%|███▋      | 8224/22132 [03:14<05:17, 43.80it/s]

2026-09-09 18:25:00,069 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:25:00,090 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:00,117 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:25:00,140 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:00,164 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  37%|███▋      | 8229/22132 [03:14<05:24, 42.80it/s]

2026-09-09 18:25:00,191 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:25:00,216 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:25:00,238 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:00,273 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]
2026-09-09 18:25:00,297 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  37%|███▋      | 8234/22132 [03:14<05:37, 41.13it/s]

2026-09-09 18:25:00,341 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.042s]
2026-09-09 18:25:00,369 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:25:00,396 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:25:00,417 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:00,438 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  37%|███▋      | 8239/22132 [03:14<05:53, 39.25it/s]

2026-09-09 18:25:00,462 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:00,486 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:00,517 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:25:00,548 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]

Indexing Records:  37%|███▋      | 8243/22132 [03:14<06:00, 38.48it/s]

2026-09-09 18:25:00,575 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:25:00,598 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:00,620 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:00,644 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:00,668 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  37%|███▋      | 8248/22132 [03:14<05:52, 39.44it/s]

2026-09-09 18:25:00,693 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:25:00,717 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:00,746 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:25:00,770 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  37%|███▋      | 8252/22132 [03:14<05:52, 39.35it/s]

2026-09-09 18:25:00,794 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:00,819 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:25:00,844 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:25:00,872 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]

Indexing Records:  37%|███▋      | 8256/22132 [03:15<05:53, 39.29it/s]

2026-09-09 18:25:00,896 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:00,924 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:25:00,946 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:00,967 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:00,988 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  37%|███▋      | 8261/22132 [03:15<05:42, 40.51it/s]

2026-09-09 18:25:01,011 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:01,036 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:25:01,057 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:01,079 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:01,099 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  37%|███▋      | 8266/22132 [03:15<05:31, 41.86it/s]

2026-09-09 18:25:01,122 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:01,144 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:01,170 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:25:01,193 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:01,216 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  37%|███▋      | 8271/22132 [03:15<05:29, 42.13it/s]

2026-09-09 18:25:01,238 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:01,268 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:25:01,305 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]
2026-09-09 18:25:01,363 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.057s]
2026-09-09 18:25:01,409 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.043s]

Indexing Records:  37%|███▋      | 8276/22132 [03:15<06:32, 35.32it/s]

2026-09-09 18:25:01,458 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.046s]
2026-09-09 18:25:01,511 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.052s]
2026-09-09 18:25:01,562 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.049s]
2026-09-09 18:25:01,608 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.044s]

Indexing Records:  37%|███▋      | 8280/22132 [03:15<07:49, 29.50it/s]

2026-09-09 18:25:01,656 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.046s]
2026-09-09 18:25:01,700 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.043s]
2026-09-09 18:25:01,758 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.056s]
2026-09-09 18:25:01,810 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.050s]

Indexing Records:  37%|███▋      | 8284/22132 [03:15<08:52, 26.01it/s]

2026-09-09 18:25:01,891 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.078s]
2026-09-09 18:25:01,959 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.066s]
2026-09-09 18:25:02,012 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.052s]

Indexing Records:  37%|███▋      | 8287/22132 [03:16<10:22, 22.24it/s]

2026-09-09 18:25:02,086 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.071s]
2026-09-09 18:25:02,139 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.052s]
2026-09-09 18:25:02,198 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.057s]

Indexing Records:  37%|███▋      | 8290/22132 [03:16<11:18, 20.39it/s]

2026-09-09 18:25:02,261 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.061s]
2026-09-09 18:25:02,303 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.040s]
2026-09-09 18:25:02,452 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.147s]

Indexing Records:  37%|███▋      | 8293/22132 [03:16<13:26, 17.15it/s]

2026-09-09 18:25:02,547 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.092s]
2026-09-09 18:25:02,617 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.068s]

Indexing Records:  37%|███▋      | 8295/22132 [03:16<14:32, 15.87it/s]

2026-09-09 18:25:02,680 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.060s]
2026-09-09 18:25:02,747 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.066s]

Indexing Records:  37%|███▋      | 8297/22132 [03:16<14:38, 15.74it/s]

2026-09-09 18:25:02,789 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.039s]
2026-09-09 18:25:02,824 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]
2026-09-09 18:25:02,869 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.044s]

Indexing Records:  38%|███▊      | 8300/22132 [03:17<12:57, 17.79it/s]

2026-09-09 18:25:02,914 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.042s]
2026-09-09 18:25:02,951 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]
2026-09-09 18:25:03,003 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.051s]

Indexing Records:  38%|███▊      | 8303/22132 [03:17<12:05, 19.05it/s]

2026-09-09 18:25:03,050 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.045s]
2026-09-09 18:25:03,097 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.045s]
2026-09-09 18:25:03,142 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.043s]

Indexing Records:  38%|███▊      | 8306/22132 [03:17<11:39, 19.77it/s]

2026-09-09 18:25:03,186 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.041s]
2026-09-09 18:25:03,229 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.042s]
2026-09-09 18:25:03,287 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.057s]

Indexing Records:  38%|███▊      | 8309/22132 [03:17<11:31, 20.00it/s]

2026-09-09 18:25:03,331 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.041s]
2026-09-09 18:25:03,366 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]
2026-09-09 18:25:03,408 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.041s]

Indexing Records:  38%|███▊      | 8312/22132 [03:17<10:50, 21.26it/s]

2026-09-09 18:25:03,450 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.039s]
2026-09-09 18:25:03,498 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.047s]
2026-09-09 18:25:03,574 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.074s]

Indexing Records:  38%|███▊      | 8315/22132 [03:17<11:23, 20.21it/s]

2026-09-09 18:25:03,613 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.036s]
2026-09-09 18:25:03,666 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.052s]
2026-09-09 18:25:03,722 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.054s]

Indexing Records:  38%|███▊      | 8318/22132 [03:17<11:23, 20.20it/s]

2026-09-09 18:25:03,792 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.067s]
2026-09-09 18:25:03,850 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.056s]
2026-09-09 18:25:03,894 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.042s]

Indexing Records:  38%|███▊      | 8321/22132 [03:18<11:55, 19.30it/s]

2026-09-09 18:25:03,939 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.042s]
2026-09-09 18:25:03,985 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.045s]
2026-09-09 18:25:04,046 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.060s]

Indexing Records:  38%|███▊      | 8324/22132 [03:18<11:51, 19.41it/s]

2026-09-09 18:25:04,104 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.055s]
2026-09-09 18:25:04,158 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.052s]

Indexing Records:  38%|███▊      | 8326/22132 [03:18<12:04, 19.06it/s]

2026-09-09 18:25:04,218 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.058s]
2026-09-09 18:25:04,283 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.063s]

Indexing Records:  38%|███▊      | 8328/22132 [03:18<12:37, 18.22it/s]

2026-09-09 18:25:04,344 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.058s]
2026-09-09 18:25:04,400 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.055s]

Indexing Records:  38%|███▊      | 8330/22132 [03:18<12:51, 17.89it/s]

2026-09-09 18:25:04,437 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]
2026-09-09 18:25:04,468 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:25:04,504 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]

Indexing Records:  38%|███▊      | 8333/22132 [03:18<11:06, 20.70it/s]

2026-09-09 18:25:04,547 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.040s]
2026-09-09 18:25:04,582 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]
2026-09-09 18:25:04,633 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.048s]

Indexing Records:  38%|███▊      | 8336/22132 [03:18<10:41, 21.50it/s]

2026-09-09 18:25:04,692 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.057s]
2026-09-09 18:25:04,746 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.052s]
2026-09-09 18:25:05,066 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.318s]

Indexing Records:  38%|███▊      | 8339/22132 [03:19<17:59, 12.77it/s]

2026-09-09 18:25:05,120 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.052s]
2026-09-09 18:25:05,160 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.038s]
2026-09-09 18:25:05,212 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.051s]

Indexing Records:  38%|███▊      | 8342/22132 [03:19<15:50, 14.50it/s]

2026-09-09 18:25:05,272 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.056s]
2026-09-09 18:25:05,325 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.051s]

Indexing Records:  38%|███▊      | 8344/22132 [03:19<15:09, 15.16it/s]

2026-09-09 18:25:05,371 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.044s]
2026-09-09 18:25:05,455 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.082s]

Indexing Records:  38%|███▊      | 8346/22132 [03:19<15:07, 15.19it/s]

2026-09-09 18:25:05,530 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.072s]
2026-09-09 18:25:05,566 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]

Indexing Records:  38%|███▊      | 8348/22132 [03:19<14:29, 15.85it/s]

2026-09-09 18:25:05,604 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]
2026-09-09 18:25:05,675 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.069s]

Indexing Records:  38%|███▊      | 8350/22132 [03:19<13:56, 16.48it/s]

2026-09-09 18:25:05,735 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.058s]
2026-09-09 18:25:05,841 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.105s]

Indexing Records:  38%|███▊      | 8352/22132 [03:19<15:23, 14.92it/s]

2026-09-09 18:25:05,928 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.084s]
2026-09-09 18:25:05,998 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.068s]

Indexing Records:  38%|███▊      | 8354/22132 [03:20<16:07, 14.24it/s]

2026-09-09 18:25:06,070 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.070s]
2026-09-09 18:25:06,156 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.084s]

Indexing Records:  38%|███▊      | 8356/22132 [03:20<16:42, 13.74it/s]

2026-09-09 18:25:06,251 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.093s]
2026-09-09 18:25:06,301 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.048s]

Indexing Records:  38%|███▊      | 8358/22132 [03:20<16:41, 13.75it/s]

2026-09-09 18:25:06,338 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]
2026-09-09 18:25:06,373 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]
2026-09-09 18:25:06,423 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.049s]

Indexing Records:  38%|███▊      | 8361/22132 [03:20<13:52, 16.55it/s]

2026-09-09 18:25:06,464 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.038s]
2026-09-09 18:25:06,496 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:25:06,555 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.058s]

Indexing Records:  38%|███▊      | 8364/22132 [03:20<12:30, 18.34it/s]

2026-09-09 18:25:06,632 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.074s]
2026-09-09 18:25:06,695 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.062s]

Indexing Records:  38%|███▊      | 8366/22132 [03:20<13:24, 17.11it/s]

2026-09-09 18:25:06,735 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.037s]
2026-09-09 18:25:06,787 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.050s]
2026-09-09 18:25:06,838 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.050s]

Indexing Records:  38%|███▊      | 8369/22132 [03:20<12:32, 18.30it/s]

2026-09-09 18:25:06,895 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.054s]
2026-09-09 18:25:06,992 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.096s]

Indexing Records:  38%|███▊      | 8371/22132 [03:21<13:49, 16.58it/s]

2026-09-09 18:25:07,044 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.049s]
2026-09-09 18:25:07,339 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.294s]

Indexing Records:  38%|███▊      | 8373/22132 [03:21<20:40, 11.09it/s]

2026-09-09 18:25:07,405 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.062s]
2026-09-09 18:25:07,450 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.043s]

Indexing Records:  38%|███▊      | 8375/22132 [03:21<18:29, 12.40it/s]

2026-09-09 18:25:07,511 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.058s]
2026-09-09 18:25:07,564 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.050s]

Indexing Records:  38%|███▊      | 8377/22132 [03:21<16:56, 13.53it/s]

2026-09-09 18:25:07,634 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.068s]
2026-09-09 18:25:07,725 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.089s]

Indexing Records:  38%|███▊      | 8379/22132 [03:21<17:23, 13.18it/s]

2026-09-09 18:25:07,871 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.143s]
2026-09-09 18:25:07,908 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.036s]

Indexing Records:  38%|███▊      | 8381/22132 [03:22<18:26, 12.43it/s]

2026-09-09 18:25:07,991 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.080s]
2026-09-09 18:25:08,063 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.071s]

Indexing Records:  38%|███▊      | 8383/22132 [03:22<18:14, 12.56it/s]

2026-09-09 18:25:08,125 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.059s]
2026-09-09 18:25:08,177 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.051s]

Indexing Records:  38%|███▊      | 8385/22132 [03:22<16:42, 13.72it/s]

2026-09-09 18:25:08,236 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.057s]
2026-09-09 18:25:08,318 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.080s]

Indexing Records:  38%|███▊      | 8387/22132 [03:22<16:32, 13.85it/s]

2026-09-09 18:25:08,373 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.052s]
2026-09-09 18:25:08,413 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.038s]
2026-09-09 18:25:08,450 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.036s]

Indexing Records:  38%|███▊      | 8390/22132 [03:22<14:00, 16.35it/s]

2026-09-09 18:25:08,496 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.043s]
2026-09-09 18:25:08,528 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:25:08,581 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.051s]

Indexing Records:  38%|███▊      | 8393/22132 [03:22<12:34, 18.21it/s]

2026-09-09 18:25:08,605 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:08,681 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.074s]

Indexing Records:  38%|███▊      | 8395/22132 [03:22<12:18, 18.61it/s]

2026-09-09 18:25:08,723 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.039s]
2026-09-09 18:25:08,754 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:25:08,808 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.052s]

Indexing Records:  38%|███▊      | 8398/22132 [03:22<11:22, 20.13it/s]

2026-09-09 18:25:08,857 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.046s]
2026-09-09 18:25:08,896 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.037s]
2026-09-09 18:25:08,945 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.047s]

Indexing Records:  38%|███▊      | 8401/22132 [03:23<11:03, 20.69it/s]

2026-09-09 18:25:08,990 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.043s]
2026-09-09 18:25:09,034 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.043s]
2026-09-09 18:25:09,069 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]

Indexing Records:  38%|███▊      | 8404/22132 [03:23<10:33, 21.68it/s]

2026-09-09 18:25:09,146 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.074s]
2026-09-09 18:25:09,202 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.054s]
2026-09-09 18:25:09,263 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.059s]

Indexing Records:  38%|███▊      | 8407/22132 [03:23<11:52, 19.26it/s]

2026-09-09 18:25:09,333 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.068s]
2026-09-09 18:25:09,409 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.074s]

Indexing Records:  38%|███▊      | 8409/22132 [03:23<12:59, 17.61it/s]

2026-09-09 18:25:09,474 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.063s]
2026-09-09 18:25:09,509 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]

Indexing Records:  38%|███▊      | 8411/22132 [03:23<12:37, 18.12it/s]

2026-09-09 18:25:09,544 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:25:12,769 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:3.223s]

Indexing Records:  38%|███▊      | 8413/22132 [03:26<1:46:55,  2.14it/s]

2026-09-09 18:25:12,881 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.109s]
2026-09-09 18:25:12,952 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.069s]

Indexing Records:  38%|███▊      | 8415/22132 [03:27<1:23:30,  2.74it/s]

2026-09-09 18:25:13,004 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.049s]
2026-09-09 18:25:13,033 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:25:13,077 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.042s]

Indexing Records:  38%|███▊      | 8418/22132 [03:27<56:12,  4.07it/s]

2026-09-09 18:25:13,114 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]
2026-09-09 18:25:13,158 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.043s]
2026-09-09 18:25:13,194 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]

Indexing Records:  38%|███▊      | 8421/22132 [03:27<39:53,  5.73it/s]

2026-09-09 18:25:13,251 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.055s]
2026-09-09 18:25:13,291 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.039s]
2026-09-09 18:25:13,320 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]

Indexing Records:  38%|███▊      | 8424/22132 [03:27<29:52,  7.65it/s]

2026-09-09 18:25:13,359 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.037s]
2026-09-09 18:25:13,393 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:25:13,422 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]

Indexing Records:  38%|███▊      | 8427/22132 [03:27<22:48, 10.01it/s]

2026-09-09 18:25:13,451 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:25:13,479 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:25:13,509 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:25:13,531 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  38%|███▊      | 8431/22132 [03:27<16:31, 13.82it/s]

2026-09-09 18:25:13,577 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.043s]
2026-09-09 18:25:13,609 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:25:13,633 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  38%|███▊      | 8434/22132 [03:27<13:58, 16.33it/s]

2026-09-09 18:25:13,657 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:13,676 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:13,739 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.062s]

Indexing Records:  38%|███▊      | 8437/22132 [03:27<12:14, 18.64it/s]

2026-09-09 18:25:13,781 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.040s]
2026-09-09 18:25:13,815 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:25:13,850 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]

Indexing Records:  38%|███▊      | 8440/22132 [03:27<11:08, 20.50it/s]

2026-09-09 18:25:13,887 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]
2026-09-09 18:25:13,906 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:13,937 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:25:13,968 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]

Indexing Records:  38%|███▊      | 8444/22132 [03:28<09:32, 23.92it/s]

2026-09-09 18:25:14,001 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:25:14,035 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]
2026-09-09 18:25:14,054 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:14,079 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  38%|███▊      | 8448/22132 [03:28<08:27, 26.96it/s]

2026-09-09 18:25:14,101 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:14,124 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:14,142 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:14,160 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:14,178 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:14,200 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  38%|███▊      | 8454/22132 [03:28<06:49, 33.38it/s]

2026-09-09 18:25:14,221 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:14,239 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:14,256 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:14,275 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:14,293 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:14,312 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  38%|███▊      | 8460/22132 [03:28<05:51, 38.94it/s]

2026-09-09 18:25:14,332 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:14,349 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:14,367 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:14,386 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:14,408 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:14,427 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  38%|███▊      | 8466/22132 [03:28<05:20, 42.67it/s]

2026-09-09 18:25:14,446 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:14,481 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]
2026-09-09 18:25:14,563 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.080s]
2026-09-09 18:25:14,580 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:14,597 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  38%|███▊      | 8471/22132 [03:28<06:02, 37.72it/s]

2026-09-09 18:25:14,619 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:14,638 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:14,657 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:14,676 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:14,701 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  38%|███▊      | 8476/22132 [03:28<05:38, 40.31it/s]

2026-09-09 18:25:14,720 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:14,737 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:14,761 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:14,781 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:14,797 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:14,819 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  38%|███▊      | 8482/22132 [03:28<05:15, 43.30it/s]

2026-09-09 18:25:14,840 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:14,859 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:14,875 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:14,895 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:14,916 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:14,934 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  38%|███▊      | 8488/22132 [03:29<04:58, 45.78it/s]

2026-09-09 18:25:14,952 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:14,971 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:14,993 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:15,023 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:25:15,058 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]

Indexing Records:  38%|███▊      | 8493/22132 [03:29<05:08, 44.20it/s]

2026-09-09 18:25:15,089 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:25:15,113 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:25:15,137 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:15,156 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:15,175 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  38%|███▊      | 8498/22132 [03:29<05:12, 43.67it/s]

2026-09-09 18:25:15,195 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:15,213 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:15,230 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:15,247 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:15,265 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:15,283 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  38%|███▊      | 8504/22132 [03:29<04:49, 47.03it/s]

2026-09-09 18:25:15,300 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:15,316 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:15,332 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:15,349 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:15,368 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:15,385 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  38%|███▊      | 8510/22132 [03:29<04:31, 50.20it/s]

2026-09-09 18:25:15,403 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:15,420 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:15,440 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:15,458 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:15,476 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:15,494 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  38%|███▊      | 8516/22132 [03:29<04:23, 51.63it/s]

2026-09-09 18:25:15,512 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:15,532 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:15,609 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.075s]
2026-09-09 18:25:15,627 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:15,649 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:15,671 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  39%|███▊      | 8522/22132 [03:29<05:06, 44.46it/s]

2026-09-09 18:25:15,692 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:15,709 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:15,726 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:15,745 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:15,804 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.057s]

Indexing Records:  39%|███▊      | 8527/22132 [03:29<05:20, 42.39it/s]

2026-09-09 18:25:15,822 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:15,846 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:25:15,883 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]
2026-09-09 18:25:15,903 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:15,924 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  39%|███▊      | 8532/22132 [03:30<05:22, 42.17it/s]

2026-09-09 18:25:15,945 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:15,975 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:25:15,996 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:16,016 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:16,050 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]

Indexing Records:  39%|███▊      | 8537/22132 [03:30<05:27, 41.47it/s]

2026-09-09 18:25:16,079 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:25:16,095 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:16,116 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:16,135 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:16,155 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  39%|███▊      | 8542/22132 [03:30<05:15, 43.03it/s]

2026-09-09 18:25:16,176 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:16,194 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:16,213 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:16,233 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:16,252 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:16,273 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  39%|███▊      | 8548/22132 [03:30<04:59, 45.35it/s]

2026-09-09 18:25:16,298 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:25:16,318 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:16,338 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:16,356 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:16,376 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  39%|███▊      | 8553/22132 [03:30<04:53, 46.22it/s]

2026-09-09 18:25:16,395 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:16,414 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:16,432 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:16,453 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:16,473 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:16,498 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  39%|███▊      | 8559/22132 [03:30<04:47, 47.13it/s]

2026-09-09 18:25:16,519 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:16,540 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:16,559 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:16,578 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:16,603 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  39%|███▊      | 8564/22132 [03:30<04:46, 47.33it/s]

2026-09-09 18:25:16,628 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:25:16,649 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:16,715 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.065s]
2026-09-09 18:25:16,737 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:16,770 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]

Indexing Records:  39%|███▊      | 8569/22132 [03:30<05:34, 40.50it/s]

2026-09-09 18:25:16,797 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:25:16,819 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:16,843 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:25:16,864 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:16,887 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  39%|███▊      | 8574/22132 [03:31<05:29, 41.19it/s]

2026-09-09 18:25:16,908 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:16,929 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:16,950 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:16,974 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:25:16,995 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  39%|███▉      | 8579/22132 [03:31<05:18, 42.58it/s]

2026-09-09 18:25:17,017 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:17,038 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:17,058 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:17,080 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:17,106 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  39%|███▉      | 8584/22132 [03:31<05:13, 43.24it/s]

2026-09-09 18:25:17,129 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:17,156 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:25:17,188 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:25:17,214 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:25:17,233 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  39%|███▉      | 8589/22132 [03:31<05:21, 42.06it/s]

2026-09-09 18:25:17,252 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:17,270 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:17,289 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:17,308 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:17,327 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:17,346 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  39%|███▉      | 8595/22132 [03:31<04:59, 45.22it/s]

2026-09-09 18:25:17,366 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:17,386 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:17,405 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:17,426 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:17,446 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  39%|███▉      | 8600/22132 [03:31<04:51, 46.42it/s]

2026-09-09 18:25:17,466 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:17,484 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:17,503 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:17,522 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:17,541 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:17,560 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  39%|███▉      | 8606/22132 [03:31<04:39, 48.33it/s]

2026-09-09 18:25:17,581 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:17,600 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:17,620 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:17,643 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:17,664 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  39%|███▉      | 8611/22132 [03:31<04:40, 48.25it/s]

2026-09-09 18:25:17,684 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:17,703 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:17,726 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:17,746 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:17,766 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  39%|███▉      | 8616/22132 [03:31<04:38, 48.49it/s]

2026-09-09 18:25:17,786 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:17,806 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:17,825 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:17,846 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:17,866 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:17,888 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  39%|███▉      | 8622/22132 [03:32<04:37, 48.64it/s]

2026-09-09 18:25:17,909 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:17,931 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:17,954 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:17,985 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:25:18,025 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.038s]

Indexing Records:  39%|███▉      | 8627/22132 [03:32<05:03, 44.49it/s]

2026-09-09 18:25:18,062 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]
2026-09-09 18:25:18,088 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:25:18,110 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:18,131 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:18,153 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  39%|███▉      | 8632/22132 [03:32<05:15, 42.75it/s]

2026-09-09 18:25:18,177 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:18,200 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:18,219 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:18,239 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:18,258 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  39%|███▉      | 8637/22132 [03:32<05:06, 44.09it/s]

2026-09-09 18:25:18,278 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:18,298 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:18,318 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:18,342 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:25:18,368 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  39%|███▉      | 8642/22132 [03:32<05:03, 44.48it/s]

2026-09-09 18:25:18,391 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:18,413 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:18,433 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:18,456 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:18,499 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.042s]

Indexing Records:  39%|███▉      | 8647/22132 [03:32<05:18, 42.40it/s]

2026-09-09 18:25:18,585 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.083s]
2026-09-09 18:25:18,617 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:25:18,649 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:25:18,682 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:25:18,711 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]

Indexing Records:  39%|███▉      | 8652/22132 [03:32<06:32, 34.31it/s]

2026-09-09 18:25:18,740 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:25:18,763 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:18,789 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:25:18,810 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:18,836 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]

Indexing Records:  39%|███▉      | 8657/22132 [03:32<06:16, 35.81it/s]

2026-09-09 18:25:18,885 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.046s]
2026-09-09 18:25:18,916 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:25:18,948 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:25:18,989 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.039s]

Indexing Records:  39%|███▉      | 8661/22132 [03:33<06:50, 32.78it/s]

2026-09-09 18:25:19,015 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:25:19,045 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:25:19,070 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:25:19,105 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]

Indexing Records:  39%|███▉      | 8665/22132 [03:33<06:45, 33.18it/s]

2026-09-09 18:25:19,128 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:19,152 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:19,171 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:19,189 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:19,212 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  39%|███▉      | 8670/22132 [03:33<06:07, 36.62it/s]

2026-09-09 18:25:19,234 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:19,251 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:19,278 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:25:19,299 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:19,318 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  39%|███▉      | 8675/22132 [03:33<05:41, 39.40it/s]

2026-09-09 18:25:19,339 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:19,357 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:19,375 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:19,392 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:19,409 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:19,440 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]

Indexing Records:  39%|███▉      | 8681/22132 [03:33<05:18, 42.30it/s]

2026-09-09 18:25:19,468 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:25:19,487 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:19,505 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:19,520 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:19,544 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  39%|███▉      | 8686/22132 [03:33<05:05, 43.94it/s]

2026-09-09 18:25:19,566 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:19,585 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:19,605 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:19,624 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:19,643 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:19,664 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  39%|███▉      | 8692/22132 [03:33<04:53, 45.72it/s]

2026-09-09 18:25:19,687 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:19,707 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:19,728 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:19,754 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:25:19,779 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  39%|███▉      | 8697/22132 [03:33<04:57, 45.09it/s]

2026-09-09 18:25:19,804 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:25:19,826 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:19,847 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:19,868 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:19,887 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  39%|███▉      | 8702/22132 [03:34<04:55, 45.49it/s]

2026-09-09 18:25:19,909 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:19,927 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:19,948 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:19,969 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:19,990 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  39%|███▉      | 8707/22132 [03:34<04:50, 46.24it/s]

2026-09-09 18:25:20,012 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:20,034 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:20,063 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:25:20,087 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:20,108 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  39%|███▉      | 8712/22132 [03:34<04:58, 45.03it/s]

2026-09-09 18:25:20,137 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:25:20,160 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:20,183 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:20,205 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:20,229 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  39%|███▉      | 8717/22132 [03:34<05:05, 43.86it/s]

2026-09-09 18:25:20,251 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:20,270 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:20,289 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:20,318 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:25:20,337 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  39%|███▉      | 8722/22132 [03:34<05:00, 44.63it/s]

2026-09-09 18:25:20,362 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:25:20,385 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:20,405 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:20,424 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:20,444 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  39%|███▉      | 8727/22132 [03:34<04:56, 45.19it/s]

2026-09-09 18:25:20,465 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:20,494 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:25:20,517 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:20,540 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:20,572 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]

Indexing Records:  39%|███▉      | 8732/22132 [03:34<05:10, 43.19it/s]

2026-09-09 18:25:20,604 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:25:20,624 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:20,651 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:25:20,671 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:20,696 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  39%|███▉      | 8737/22132 [03:34<05:16, 42.26it/s]

2026-09-09 18:25:20,792 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.093s]
2026-09-09 18:25:20,823 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:25:20,846 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:20,869 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:20,907 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.036s]

Indexing Records:  39%|███▉      | 8742/22132 [03:35<06:31, 34.22it/s]

2026-09-09 18:25:20,939 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:25:20,965 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:25:20,991 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:25:21,020 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]

Indexing Records:  40%|███▉      | 8746/22132 [03:35<06:27, 34.54it/s]

2026-09-09 18:25:21,046 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:25:21,076 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:25:21,099 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:21,118 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:21,137 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  40%|███▉      | 8751/22132 [03:35<06:03, 36.77it/s]

2026-09-09 18:25:21,166 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:25:21,186 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:21,218 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:25:21,238 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  40%|███▉      | 8755/22132 [03:35<05:57, 37.43it/s]

2026-09-09 18:25:21,259 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:21,294 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]
2026-09-09 18:25:21,323 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:25:21,345 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  40%|███▉      | 8759/22132 [03:35<05:57, 37.42it/s]

2026-09-09 18:25:21,367 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:21,388 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:21,408 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:21,428 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:21,447 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  40%|███▉      | 8764/22132 [03:35<05:28, 40.63it/s]

2026-09-09 18:25:21,467 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:21,491 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:25:21,517 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:25:21,540 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:21,559 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  40%|███▉      | 8769/22132 [03:35<05:19, 41.85it/s]

2026-09-09 18:25:21,580 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:21,600 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:21,619 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:21,640 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:21,661 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  40%|███▉      | 8774/22132 [03:35<05:04, 43.85it/s]

2026-09-09 18:25:21,680 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:21,700 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:21,729 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:25:21,750 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:21,780 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]

Indexing Records:  40%|███▉      | 8779/22132 [03:35<05:09, 43.21it/s]

2026-09-09 18:25:21,801 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:21,821 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:21,840 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:21,857 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:21,883 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  40%|███▉      | 8784/22132 [03:36<04:58, 44.75it/s]

2026-09-09 18:25:21,904 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:21,927 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:21,948 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:21,969 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:22,001 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]

Indexing Records:  40%|███▉      | 8789/22132 [03:36<05:03, 43.96it/s]

2026-09-09 18:25:22,027 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:25:22,047 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:22,070 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:22,089 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:22,111 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  40%|███▉      | 8794/22132 [03:36<05:00, 44.40it/s]

2026-09-09 18:25:22,133 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:22,153 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:22,178 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:25:22,205 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:25:22,225 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  40%|███▉      | 8799/22132 [03:36<05:01, 44.26it/s]

2026-09-09 18:25:22,245 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:22,264 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:22,284 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:22,308 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:22,329 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  40%|███▉      | 8804/22132 [03:36<04:54, 45.28it/s]

2026-09-09 18:25:22,355 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:25:22,379 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:22,400 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:22,422 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:22,444 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  40%|███▉      | 8809/22132 [03:36<04:57, 44.80it/s]

2026-09-09 18:25:22,474 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:25:22,494 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:22,513 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:22,533 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:22,555 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  40%|███▉      | 8814/22132 [03:36<04:56, 44.84it/s]

2026-09-09 18:25:22,584 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:25:22,604 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:22,623 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:22,643 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:22,662 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  40%|███▉      | 8819/22132 [03:36<04:53, 45.39it/s]

2026-09-09 18:25:22,687 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:25:22,706 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:22,734 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:25:22,754 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:22,775 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  40%|███▉      | 8824/22132 [03:36<04:55, 45.00it/s]

2026-09-09 18:25:22,799 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:22,824 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:25:22,845 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:22,864 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:22,882 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  40%|███▉      | 8829/22132 [03:37<04:51, 45.58it/s]

2026-09-09 18:25:22,902 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:22,923 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:22,948 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:25:22,970 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:22,990 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  40%|███▉      | 8834/22132 [03:37<04:50, 45.76it/s]

2026-09-09 18:25:23,017 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:25:23,037 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:23,067 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:25:23,088 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:23,109 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  40%|███▉      | 8839/22132 [03:37<04:58, 44.53it/s]

2026-09-09 18:25:23,135 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:25:23,154 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:23,191 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.036s]
2026-09-09 18:25:23,210 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:23,229 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  40%|███▉      | 8844/22132 [03:37<05:03, 43.73it/s]

2026-09-09 18:25:23,248 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:23,266 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:23,289 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:23,308 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:23,332 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  40%|███▉      | 8849/22132 [03:37<04:54, 45.06it/s]

2026-09-09 18:25:23,354 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:23,376 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:23,403 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:25:23,431 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:25:23,452 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  40%|████      | 8854/22132 [03:37<05:02, 43.90it/s]

2026-09-09 18:25:23,475 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:23,495 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:23,514 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:23,536 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:23,564 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]

Indexing Records:  40%|████      | 8859/22132 [03:37<05:00, 44.12it/s]

2026-09-09 18:25:23,585 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:23,604 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:23,627 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:23,648 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:23,668 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  40%|████      | 8864/22132 [03:37<04:52, 45.29it/s]

2026-09-09 18:25:23,689 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:23,713 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:25:23,733 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:23,755 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:23,775 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  40%|████      | 8869/22132 [03:37<04:50, 45.70it/s]

2026-09-09 18:25:23,795 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:23,817 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:23,836 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:23,859 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:23,884 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  40%|████      | 8874/22132 [03:38<04:50, 45.71it/s]

2026-09-09 18:25:23,914 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:25:23,935 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:23,956 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:23,978 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:24,001 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  40%|████      | 8879/22132 [03:38<04:55, 44.79it/s]

2026-09-09 18:25:24,022 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:24,041 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:24,062 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:24,081 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:24,103 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  40%|████      | 8884/22132 [03:38<04:47, 46.06it/s]

2026-09-09 18:25:24,123 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:24,157 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:25:24,183 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:25:24,270 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.086s]
2026-09-09 18:25:24,314 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.043s]

Indexing Records:  40%|████      | 8889/22132 [03:38<06:09, 35.85it/s]

2026-09-09 18:25:24,341 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:25:24,388 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.045s]
2026-09-09 18:25:24,421 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:25:24,507 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.085s]

Indexing Records:  40%|████      | 8893/22132 [03:38<07:18, 30.20it/s]

2026-09-09 18:25:24,548 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.038s]
2026-09-09 18:25:24,590 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.040s]
2026-09-09 18:25:24,624 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]
2026-09-09 18:25:24,657 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]

Indexing Records:  40%|████      | 8897/22132 [03:38<07:33, 29.16it/s]

2026-09-09 18:25:24,700 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.040s]
2026-09-09 18:25:24,774 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.072s]
2026-09-09 18:25:24,822 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.046s]
2026-09-09 18:25:24,864 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.041s]

Indexing Records:  40%|████      | 8901/22132 [03:39<08:37, 25.57it/s]

2026-09-09 18:25:24,894 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:25:24,924 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:25:24,945 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:24,966 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  40%|████      | 8905/22132 [03:39<07:45, 28.40it/s]

2026-09-09 18:25:24,996 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:25:25,034 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.036s]
2026-09-09 18:25:25,054 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:25,075 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  40%|████      | 8909/22132 [03:39<07:15, 30.34it/s]

2026-09-09 18:25:25,116 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.039s]
2026-09-09 18:25:25,150 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:25:25,172 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:25,192 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  40%|████      | 8913/22132 [03:39<07:00, 31.43it/s]

2026-09-09 18:25:25,219 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:25:25,242 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:25,264 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:25,288 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:25,308 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  40%|████      | 8918/22132 [03:39<06:22, 34.58it/s]

2026-09-09 18:25:25,332 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:25,353 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:25,371 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:25,390 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:25,407 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:25,428 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  40%|████      | 8924/22132 [03:39<05:38, 39.07it/s]

2026-09-09 18:25:25,447 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:25,465 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:25,484 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:25,501 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:25,517 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:25,535 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  40%|████      | 8930/22132 [03:39<05:02, 43.69it/s]

2026-09-09 18:25:25,553 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:25,571 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:25,592 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:25,611 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:25,628 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:25,647 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  40%|████      | 8936/22132 [03:39<04:43, 46.54it/s]

2026-09-09 18:25:25,664 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:25,684 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:25,701 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:25,724 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:25,743 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:25,762 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  40%|████      | 8942/22132 [03:39<04:33, 48.17it/s]

2026-09-09 18:25:25,781 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:25,802 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:25,823 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:25,843 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:25,866 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  40%|████      | 8947/22132 [03:40<04:33, 48.17it/s]

2026-09-09 18:25:25,893 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:25:25,919 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:25:25,942 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:25,964 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:25,983 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  40%|████      | 8952/22132 [03:40<04:43, 46.48it/s]

2026-09-09 18:25:26,009 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:25:26,027 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:26,045 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:26,061 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:26,081 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:26,099 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  40%|████      | 8958/22132 [03:40<04:34, 48.05it/s]

2026-09-09 18:25:26,116 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:26,136 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:26,154 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:26,175 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:26,192 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:26,209 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  41%|████      | 8964/22132 [03:40<04:23, 49.94it/s]

2026-09-09 18:25:26,228 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:26,255 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:25:26,275 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:26,294 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:26,312 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:26,329 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  41%|████      | 8970/22132 [03:40<04:23, 49.92it/s]

2026-09-09 18:25:26,347 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:26,363 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:26,379 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:26,396 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:26,412 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:26,429 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  41%|████      | 8976/22132 [03:40<04:10, 52.62it/s]

2026-09-09 18:25:26,452 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:26,471 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:26,489 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:26,506 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:26,522 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:26,540 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  41%|████      | 8982/22132 [03:40<04:07, 53.12it/s]

2026-09-09 18:25:26,560 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:26,585 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:25:26,604 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:26,624 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:26,642 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:26,664 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  41%|████      | 8988/22132 [03:40<04:15, 51.53it/s]

2026-09-09 18:25:26,683 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:26,725 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.041s]
2026-09-09 18:25:26,745 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:26,763 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:26,785 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:26,805 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  41%|████      | 8994/22132 [03:40<04:31, 48.48it/s]

2026-09-09 18:25:26,826 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:26,845 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:26,863 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:26,881 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:26,907 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  41%|████      | 8999/22132 [03:41<04:30, 48.55it/s]

2026-09-09 18:25:26,927 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:26,945 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:26,962 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:26,981 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:27,003 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:27,021 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  41%|████      | 9005/22132 [03:41<04:23, 49.83it/s]

2026-09-09 18:25:27,039 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:27,058 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:27,077 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:27,097 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:27,117 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:27,136 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  41%|████      | 9011/22132 [03:41<04:19, 50.51it/s]

2026-09-09 18:25:27,158 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:27,184 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:25:27,213 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:25:27,234 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:27,251 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:27,269 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  41%|████      | 9017/22132 [03:41<04:29, 48.70it/s]

2026-09-09 18:25:27,293 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:27,313 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:27,333 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:27,353 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:27,370 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  41%|████      | 9022/22132 [03:41<04:27, 48.96it/s]

2026-09-09 18:25:27,389 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:27,409 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:27,429 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:27,451 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:27,470 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:27,492 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  41%|████      | 9028/22132 [03:41<04:27, 49.03it/s]

2026-09-09 18:25:27,514 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:27,533 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:27,551 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:27,574 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:27,598 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  41%|████      | 9033/22132 [03:41<04:30, 48.51it/s]

2026-09-09 18:25:27,621 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:27,640 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:27,657 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:27,676 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:27,703 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]

Indexing Records:  41%|████      | 9038/22132 [03:41<04:31, 48.28it/s]

2026-09-09 18:25:27,727 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:27,749 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:27,768 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:27,793 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:25:27,811 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  41%|████      | 9043/22132 [03:41<04:34, 47.63it/s]

2026-09-09 18:25:27,830 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:27,847 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:27,866 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:27,888 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:27,917 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]

Indexing Records:  41%|████      | 9048/22132 [03:42<04:35, 47.53it/s]

2026-09-09 18:25:27,938 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:27,960 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:27,980 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:28,002 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:28,028 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  41%|████      | 9053/22132 [03:42<04:39, 46.81it/s]

2026-09-09 18:25:28,049 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:28,069 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:28,091 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:28,119 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:25:28,139 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  41%|████      | 9058/22132 [03:42<04:42, 46.28it/s]

2026-09-09 18:25:28,160 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:28,181 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:28,205 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:28,232 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:25:28,257 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  41%|████      | 9063/22132 [03:42<04:50, 44.99it/s]

2026-09-09 18:25:28,281 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:28,303 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:28,329 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:25:28,349 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:28,370 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  41%|████      | 9068/22132 [03:42<04:51, 44.84it/s]

2026-09-09 18:25:28,395 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:25:28,418 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:28,440 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:28,460 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:28,480 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  41%|████      | 9073/22132 [03:42<04:50, 44.94it/s]

2026-09-09 18:25:28,500 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:28,519 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:28,541 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:28,563 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:28,584 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  41%|████      | 9078/22132 [03:42<04:44, 45.92it/s]

2026-09-09 18:25:28,606 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:28,628 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:28,648 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:28,678 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:25:28,696 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  41%|████      | 9083/22132 [03:42<04:46, 45.47it/s]

2026-09-09 18:25:28,716 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:28,734 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:28,755 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:28,776 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:28,795 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:28,820 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  41%|████      | 9089/22132 [03:42<04:41, 46.39it/s]

2026-09-09 18:25:28,843 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:28,862 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:28,880 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:28,897 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:28,915 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:28,933 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  41%|████      | 9095/22132 [03:43<04:29, 48.46it/s]

2026-09-09 18:25:28,953 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:28,970 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:28,987 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:29,004 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:29,023 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:29,041 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  41%|████      | 9101/22132 [03:43<04:17, 50.51it/s]

2026-09-09 18:25:29,063 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:29,081 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:29,100 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:29,117 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:29,139 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:29,157 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  41%|████      | 9107/22132 [03:43<04:16, 50.83it/s]

2026-09-09 18:25:29,175 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:29,194 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:29,217 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:29,237 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:29,256 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:29,273 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  41%|████      | 9113/22132 [03:43<04:14, 51.11it/s]

2026-09-09 18:25:29,292 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:29,308 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:29,325 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:29,344 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:29,364 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:29,384 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  41%|████      | 9119/22132 [03:43<04:10, 52.03it/s]

2026-09-09 18:25:29,403 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:29,421 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:29,441 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:29,464 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:29,482 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:29,500 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  41%|████      | 9125/22132 [03:43<04:10, 51.90it/s]

2026-09-09 18:25:29,519 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:29,547 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:25:29,566 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:29,584 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:29,603 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:29,636 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]

Indexing Records:  41%|████▏     | 9131/22132 [03:43<04:23, 49.30it/s]

2026-09-09 18:25:29,658 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:29,681 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:29,713 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:25:29,750 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.036s]
2026-09-09 18:25:29,776 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  41%|████▏     | 9136/22132 [03:43<04:50, 44.71it/s]

2026-09-09 18:25:29,797 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:29,818 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:29,842 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:25:29,862 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:29,880 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  41%|████▏     | 9141/22132 [03:44<04:44, 45.61it/s]

2026-09-09 18:25:29,901 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:29,920 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:29,938 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:29,967 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:25:30,010 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.042s]

Indexing Records:  41%|████▏     | 9146/22132 [03:44<04:59, 43.32it/s]

2026-09-09 18:25:30,038 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:25:30,061 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:30,091 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:25:30,113 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:30,139 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]

Indexing Records:  41%|████▏     | 9151/22132 [03:44<05:09, 41.92it/s]

2026-09-09 18:25:30,174 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:25:30,200 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:25:30,217 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:30,245 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:25:30,302 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.056s]

Indexing Records:  41%|████▏     | 9156/22132 [03:44<05:42, 37.88it/s]

2026-09-09 18:25:30,337 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]
2026-09-09 18:25:30,366 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:25:30,385 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:30,404 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  41%|████▏     | 9160/22132 [03:44<05:39, 38.22it/s]

2026-09-09 18:25:30,426 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:30,451 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:25:30,473 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:30,492 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:30,511 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  41%|████▏     | 9165/22132 [03:44<05:20, 40.50it/s]

2026-09-09 18:25:30,549 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.036s]
2026-09-09 18:25:30,568 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:30,602 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]
2026-09-09 18:25:30,624 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:30,645 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  41%|████▏     | 9170/22132 [03:44<05:28, 39.43it/s]

2026-09-09 18:25:30,677 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:25:30,712 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]
2026-09-09 18:25:30,733 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:30,751 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:30,781 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]

Indexing Records:  41%|████▏     | 9175/22132 [03:44<05:35, 38.61it/s]

2026-09-09 18:25:30,808 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:25:30,829 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:30,849 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:30,868 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:30,891 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  41%|████▏     | 9180/22132 [03:45<05:20, 40.42it/s]

2026-09-09 18:25:30,917 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:25:30,947 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:25:30,966 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:30,986 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:31,018 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]

Indexing Records:  42%|████▏     | 9185/22132 [03:45<05:22, 40.16it/s]

2026-09-09 18:25:31,040 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:31,069 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:25:31,089 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:31,109 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:31,130 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  42%|████▏     | 9190/22132 [03:45<05:12, 41.44it/s]

2026-09-09 18:25:31,151 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:31,175 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:25:31,197 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:31,218 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:31,240 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  42%|████▏     | 9195/22132 [03:45<05:04, 42.49it/s]

2026-09-09 18:25:31,265 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:25:31,290 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:25:31,310 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:31,332 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:31,354 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  42%|████▏     | 9200/22132 [03:45<05:00, 42.97it/s]

2026-09-09 18:25:31,381 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:25:31,430 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.048s]
2026-09-09 18:25:31,459 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:25:31,482 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:31,511 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]

Indexing Records:  42%|████▏     | 9205/22132 [03:45<05:32, 38.89it/s]

2026-09-09 18:25:31,530 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:31,560 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:25:31,589 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:25:31,618 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]

Indexing Records:  42%|████▏     | 9209/22132 [03:45<05:36, 38.44it/s]

2026-09-09 18:25:31,641 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:31,674 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:25:31,696 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:31,732 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]

Indexing Records:  42%|████▏     | 9213/22132 [03:45<05:44, 37.45it/s]

2026-09-09 18:25:31,795 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.060s]
2026-09-09 18:25:31,855 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.058s]
2026-09-09 18:25:31,885 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:25:31,907 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  42%|████▏     | 9217/22132 [03:46<06:45, 31.87it/s]

2026-09-09 18:25:31,930 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:31,954 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:25:31,975 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:32,003 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:25:32,028 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  42%|████▏     | 9222/22132 [03:46<06:14, 34.43it/s]

2026-09-09 18:25:32,059 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:25:32,090 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:25:32,118 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:25:32,179 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.060s]

Indexing Records:  42%|████▏     | 9226/22132 [03:46<06:45, 31.84it/s]

2026-09-09 18:25:32,201 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:32,224 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:32,277 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.051s]
2026-09-09 18:25:32,300 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  42%|████▏     | 9230/22132 [03:46<06:41, 32.14it/s]

2026-09-09 18:25:32,338 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]
2026-09-09 18:25:32,358 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:32,385 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:25:32,405 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  42%|████▏     | 9234/22132 [03:46<06:22, 33.69it/s]

2026-09-09 18:25:32,432 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:25:32,462 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:25:32,483 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:32,503 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:32,523 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  42%|████▏     | 9239/22132 [03:46<05:55, 36.24it/s]

2026-09-09 18:25:32,547 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:25:32,569 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:32,588 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:32,635 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.045s]

Indexing Records:  42%|████▏     | 9243/22132 [03:46<05:57, 36.08it/s]

2026-09-09 18:25:32,657 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:32,677 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:32,699 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:32,732 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:25:32,751 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  42%|████▏     | 9248/22132 [03:46<05:38, 38.11it/s]

2026-09-09 18:25:32,771 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:32,795 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:25:32,815 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:32,847 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:25:32,866 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  42%|████▏     | 9253/22132 [03:47<05:24, 39.67it/s]

2026-09-09 18:25:32,890 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:32,908 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:32,926 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:32,957 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:25:32,978 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  42%|████▏     | 9258/22132 [03:47<05:13, 41.12it/s]

2026-09-09 18:25:33,001 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:33,026 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:25:33,050 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:25:33,076 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:25:33,095 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  42%|████▏     | 9263/22132 [03:47<05:09, 41.64it/s]

2026-09-09 18:25:33,123 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:25:33,143 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:33,162 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:33,186 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:25:33,207 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  42%|████▏     | 9268/22132 [03:47<05:02, 42.51it/s]

2026-09-09 18:25:33,227 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:33,245 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:33,265 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:33,284 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:33,303 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:33,326 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  42%|████▏     | 9274/22132 [03:47<04:46, 44.94it/s]

2026-09-09 18:25:33,352 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:25:33,371 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:33,395 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:25:33,414 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:33,432 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  42%|████▏     | 9279/22132 [03:47<04:42, 45.54it/s]

2026-09-09 18:25:33,455 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:33,475 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:33,500 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:25:33,517 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:33,541 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  42%|████▏     | 9284/22132 [03:47<04:41, 45.65it/s]

2026-09-09 18:25:33,561 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:33,581 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:33,601 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:33,620 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:33,640 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:33,659 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  42%|████▏     | 9290/22132 [03:47<04:31, 47.31it/s]

2026-09-09 18:25:33,676 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:33,694 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:33,711 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:33,729 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:33,752 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:33,775 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  42%|████▏     | 9296/22132 [03:47<04:24, 48.58it/s]

2026-09-09 18:25:33,804 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:25:33,827 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:33,848 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:33,868 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:33,889 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  42%|████▏     | 9301/22132 [03:48<04:31, 47.27it/s]

2026-09-09 18:25:33,913 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:33,935 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:33,958 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:33,982 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:25:34,003 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  42%|████▏     | 9306/22132 [03:48<04:37, 46.27it/s]

2026-09-09 18:25:34,036 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:25:34,060 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:34,080 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:34,102 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:34,126 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  42%|████▏     | 9311/22132 [03:48<04:48, 44.45it/s]

2026-09-09 18:25:34,149 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:34,168 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:34,190 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:34,209 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:34,228 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  42%|████▏     | 9316/22132 [03:48<04:40, 45.67it/s]

2026-09-09 18:25:34,251 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:34,274 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:34,295 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:34,321 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:25:34,343 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  42%|████▏     | 9321/22132 [03:48<04:44, 45.07it/s]

2026-09-09 18:25:34,364 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:34,388 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:34,409 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:34,430 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:34,450 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  42%|████▏     | 9326/22132 [03:48<04:41, 45.52it/s]

2026-09-09 18:25:34,476 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:25:34,497 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:34,519 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:34,539 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:34,560 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  42%|████▏     | 9331/22132 [03:48<04:41, 45.54it/s]

2026-09-09 18:25:34,581 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:34,608 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:25:34,631 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:34,651 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:34,673 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  42%|████▏     | 9336/22132 [03:48<04:43, 45.11it/s]

2026-09-09 18:25:34,698 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:25:34,718 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:34,738 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:34,758 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:34,782 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  42%|████▏     | 9341/22132 [03:48<04:42, 45.28it/s]

2026-09-09 18:25:34,804 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:34,836 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:25:34,857 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:34,880 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:34,904 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  42%|████▏     | 9346/22132 [03:49<04:51, 43.92it/s]

2026-09-09 18:25:34,926 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:34,951 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:25:34,981 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:25:35,000 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:35,021 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  42%|████▏     | 9351/22132 [03:49<04:53, 43.61it/s]

2026-09-09 18:25:35,045 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:35,066 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:35,086 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:35,105 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:35,127 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  42%|████▏     | 9356/22132 [03:49<04:46, 44.53it/s]

2026-09-09 18:25:35,152 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:35,172 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:35,200 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:25:35,228 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:25:35,249 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  42%|████▏     | 9361/22132 [03:49<04:53, 43.49it/s]

2026-09-09 18:25:35,268 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:35,291 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:35,312 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:35,343 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:25:35,368 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  42%|████▏     | 9366/22132 [03:49<04:56, 43.03it/s]

2026-09-09 18:25:35,395 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:25:35,418 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:35,442 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:35,464 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:35,491 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]

Indexing Records:  42%|████▏     | 9371/22132 [03:49<05:01, 42.27it/s]

2026-09-09 18:25:35,524 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:25:35,547 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:35,570 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:35,604 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]
2026-09-09 18:25:35,630 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  42%|████▏     | 9376/22132 [03:49<05:17, 40.19it/s]

2026-09-09 18:25:35,654 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:35,675 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:35,696 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:35,716 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:35,739 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  42%|████▏     | 9381/22132 [03:49<05:05, 41.70it/s]

2026-09-09 18:25:35,765 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:25:35,784 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:35,804 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:35,832 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:25:35,859 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]

Indexing Records:  42%|████▏     | 9386/22132 [03:50<05:06, 41.63it/s]

2026-09-09 18:25:35,883 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:35,903 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:35,927 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:35,949 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:35,971 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  42%|████▏     | 9391/22132 [03:50<04:59, 42.54it/s]

2026-09-09 18:25:35,992 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:36,017 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:25:36,039 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:36,069 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:25:36,089 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  42%|████▏     | 9396/22132 [03:50<04:59, 42.46it/s]

2026-09-09 18:25:36,111 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:36,130 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:36,154 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:36,177 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:36,198 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  42%|████▏     | 9401/22132 [03:50<04:53, 43.42it/s]

2026-09-09 18:25:36,223 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:36,248 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:25:36,273 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:25:36,295 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:36,317 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  42%|████▏     | 9406/22132 [03:50<04:55, 43.06it/s]

2026-09-09 18:25:36,342 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:25:36,372 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:25:36,398 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:25:36,419 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:36,439 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  43%|████▎     | 9411/22132 [03:50<05:00, 42.34it/s]

2026-09-09 18:25:36,466 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:25:36,497 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:25:36,517 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:36,537 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:36,558 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  43%|████▎     | 9416/22132 [03:50<05:01, 42.25it/s]

2026-09-09 18:25:36,587 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:25:36,611 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:36,635 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:36,657 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:36,682 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  43%|████▎     | 9421/22132 [03:50<05:04, 41.72it/s]

2026-09-09 18:25:36,701 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:36,723 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:36,744 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:36,764 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:36,786 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  43%|████▎     | 9426/22132 [03:50<04:52, 43.43it/s]

2026-09-09 18:25:36,808 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:36,832 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:25:36,851 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:36,870 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:36,890 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  43%|████▎     | 9431/22132 [03:51<04:43, 44.73it/s]

2026-09-09 18:25:36,910 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:36,931 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:36,957 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:25:36,977 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:37,003 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]

Indexing Records:  43%|████▎     | 9436/22132 [03:51<04:45, 44.52it/s]

2026-09-09 18:25:37,026 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:37,047 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:37,067 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:37,090 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:37,114 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  43%|████▎     | 9441/22132 [03:51<04:43, 44.75it/s]

2026-09-09 18:25:37,136 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:37,157 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:37,178 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:37,205 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:25:37,225 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  43%|████▎     | 9446/22132 [03:51<04:42, 44.83it/s]

2026-09-09 18:25:37,247 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:37,268 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:37,295 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:25:37,315 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:37,334 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  43%|████▎     | 9451/22132 [03:51<04:41, 45.06it/s]

2026-09-09 18:25:37,353 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:37,378 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:25:37,402 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:25:37,427 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:25:37,450 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  43%|████▎     | 9456/22132 [03:51<04:44, 44.50it/s]

2026-09-09 18:25:37,475 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:25:37,498 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:37,517 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:37,539 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:37,560 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  43%|████▎     | 9461/22132 [03:51<04:43, 44.76it/s]

2026-09-09 18:25:37,587 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:25:37,610 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:37,635 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:25:37,658 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:37,681 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  43%|████▎     | 9466/22132 [03:51<04:49, 43.74it/s]

2026-09-09 18:25:37,702 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:37,722 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:37,743 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:37,765 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:37,783 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  43%|████▎     | 9471/22132 [03:51<04:40, 45.10it/s]

2026-09-09 18:25:37,806 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:37,825 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:37,846 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:37,864 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:37,881 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:37,898 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  43%|████▎     | 9477/22132 [03:52<04:27, 47.37it/s]

2026-09-09 18:25:37,916 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:37,935 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:37,959 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:37,977 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:37,996 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:38,014 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  43%|████▎     | 9483/22132 [03:52<04:19, 48.66it/s]

2026-09-09 18:25:38,032 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:38,050 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:38,069 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:38,089 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:38,107 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:38,124 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  43%|████▎     | 9489/22132 [03:52<04:10, 50.46it/s]

2026-09-09 18:25:38,141 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:38,160 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:38,177 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:38,195 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:38,211 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:38,228 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  43%|████▎     | 9495/22132 [03:52<04:00, 52.50it/s]

2026-09-09 18:25:38,245 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:38,262 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:38,279 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:38,296 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:38,313 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:38,329 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  43%|████▎     | 9501/22132 [03:52<03:52, 54.36it/s]

2026-09-09 18:25:38,347 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:38,364 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:38,381 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:38,400 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:38,419 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:38,438 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  43%|████▎     | 9507/22132 [03:52<03:51, 54.64it/s]

2026-09-09 18:25:38,457 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:38,475 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:38,493 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:38,512 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:38,528 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:38,545 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  43%|████▎     | 9513/22132 [03:52<03:49, 55.04it/s]

2026-09-09 18:25:38,564 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:38,587 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:38,609 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:38,627 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:38,644 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:38,664 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  43%|████▎     | 9519/22132 [03:52<03:55, 53.60it/s]

2026-09-09 18:25:38,689 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:25:38,708 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:38,724 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:38,742 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:38,760 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:38,776 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  43%|████▎     | 9525/22132 [03:52<03:55, 53.57it/s]

2026-09-09 18:25:38,797 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:38,812 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:38,829 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:38,845 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:38,864 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:38,905 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.040s]

Indexing Records:  43%|████▎     | 9531/22132 [03:53<04:06, 51.18it/s]

2026-09-09 18:25:38,922 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:38,940 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:38,956 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:38,975 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:39,017 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.041s]
2026-09-09 18:25:39,034 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  43%|████▎     | 9537/22132 [03:53<04:13, 49.68it/s]

2026-09-09 18:25:39,052 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:39,074 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:39,093 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:39,115 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:39,132 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:39,149 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  43%|████▎     | 9543/22132 [03:53<04:09, 50.47it/s]

2026-09-09 18:25:39,170 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:39,194 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:39,214 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:39,234 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:39,256 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:39,277 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  43%|████▎     | 9549/22132 [03:53<04:15, 49.34it/s]

2026-09-09 18:25:39,297 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:39,317 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:39,338 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:39,359 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:39,383 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  43%|████▎     | 9554/22132 [03:53<04:18, 48.71it/s]

2026-09-09 18:25:39,405 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:39,424 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:39,447 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:39,468 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:39,489 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  43%|████▎     | 9559/22132 [03:53<04:20, 48.33it/s]

2026-09-09 18:25:39,510 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:39,584 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.073s]
2026-09-09 18:25:39,613 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:25:39,637 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:39,657 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  43%|████▎     | 9564/22132 [03:53<05:05, 41.11it/s]

2026-09-09 18:25:39,678 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:39,699 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:39,728 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:25:39,761 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:25:39,786 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  43%|████▎     | 9569/22132 [03:53<05:10, 40.41it/s]

2026-09-09 18:25:39,835 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.047s]
2026-09-09 18:25:39,861 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:25:39,881 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:39,902 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:39,923 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  43%|████▎     | 9574/22132 [03:54<05:20, 39.19it/s]

2026-09-09 18:25:39,943 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:39,963 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:39,981 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:40,001 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:40,024 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  43%|████▎     | 9579/22132 [03:54<05:00, 41.72it/s]

2026-09-09 18:25:40,048 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:40,068 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:40,088 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:40,109 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:40,132 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  43%|████▎     | 9584/22132 [03:54<04:52, 42.93it/s]

2026-09-09 18:25:40,154 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:40,177 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:40,196 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:40,218 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:40,241 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  43%|████▎     | 9589/22132 [03:54<04:46, 43.77it/s]

2026-09-09 18:25:40,261 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:40,284 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:40,304 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:40,326 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:40,347 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  43%|████▎     | 9594/22132 [03:54<04:40, 44.75it/s]

2026-09-09 18:25:40,369 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:40,394 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:40,424 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:25:40,445 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:40,464 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  43%|████▎     | 9599/22132 [03:54<04:43, 44.14it/s]

2026-09-09 18:25:40,484 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:40,512 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:25:40,531 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:40,550 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:40,571 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  43%|████▎     | 9604/22132 [03:54<04:39, 44.90it/s]

2026-09-09 18:25:40,622 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.049s]
2026-09-09 18:25:40,651 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:25:40,672 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:40,692 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:40,712 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  43%|████▎     | 9609/22132 [03:54<05:01, 41.56it/s]

2026-09-09 18:25:40,734 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:40,755 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:40,775 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:40,796 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:40,816 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  43%|████▎     | 9614/22132 [03:54<04:49, 43.29it/s]

2026-09-09 18:25:40,849 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:25:40,869 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:40,889 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:40,909 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:40,929 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  43%|████▎     | 9619/22132 [03:55<04:46, 43.61it/s]

2026-09-09 18:25:40,951 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:40,972 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:40,992 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:41,013 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:41,044 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]

Indexing Records:  43%|████▎     | 9624/22132 [03:55<04:46, 43.61it/s]

2026-09-09 18:25:41,065 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:41,084 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:41,104 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:41,123 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:41,154 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]

Indexing Records:  44%|████▎     | 9629/22132 [03:55<04:43, 44.10it/s]

2026-09-09 18:25:41,190 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]
2026-09-09 18:25:41,238 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.047s]
2026-09-09 18:25:41,272 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:25:41,301 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:25:41,337 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]

Indexing Records:  44%|████▎     | 9634/22132 [03:55<05:35, 37.27it/s]

2026-09-09 18:25:41,367 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:25:41,400 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:25:41,447 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.045s]
2026-09-09 18:25:41,474 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]

Indexing Records:  44%|████▎     | 9638/22132 [03:55<05:59, 34.76it/s]

2026-09-09 18:25:41,498 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:41,539 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.039s]
2026-09-09 18:25:41,570 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:25:41,743 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.171s]

Indexing Records:  44%|████▎     | 9642/22132 [03:55<08:07, 25.63it/s]

2026-09-09 18:25:41,774 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:25:41,793 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:41,814 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:41,832 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:41,852 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  44%|████▎     | 9647/22132 [03:55<06:57, 29.88it/s]

2026-09-09 18:25:41,871 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:41,891 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:41,911 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:41,930 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:41,949 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:41,968 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  44%|████▎     | 9653/22132 [03:56<05:54, 35.16it/s]

2026-09-09 18:25:41,988 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:42,006 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:42,024 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:42,045 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:42,064 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:42,084 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  44%|████▎     | 9659/22132 [03:56<05:16, 39.47it/s]

2026-09-09 18:25:42,103 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:42,123 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:42,157 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]
2026-09-09 18:25:42,179 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:42,198 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  44%|████▎     | 9664/22132 [03:56<05:06, 40.66it/s]

2026-09-09 18:25:42,220 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:42,239 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:42,258 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:42,278 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:42,298 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  44%|████▎     | 9669/22132 [03:56<04:49, 42.99it/s]

2026-09-09 18:25:42,319 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:42,338 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:42,356 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:42,376 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:42,400 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  44%|████▎     | 9674/22132 [03:56<04:40, 44.48it/s]

2026-09-09 18:25:42,421 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:42,441 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:42,460 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:42,479 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:42,498 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:42,520 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  44%|████▎     | 9680/22132 [03:56<04:29, 46.22it/s]

2026-09-09 18:25:42,545 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:42,568 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:42,590 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:42,610 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:42,629 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  44%|████▍     | 9685/22132 [03:56<04:29, 46.11it/s]

2026-09-09 18:25:42,650 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:42,669 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:42,688 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:42,708 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:42,729 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:42,748 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  44%|████▍     | 9691/22132 [03:56<04:22, 47.48it/s]

2026-09-09 18:25:42,769 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:42,787 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:42,808 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:42,828 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:42,849 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  44%|████▍     | 9696/22132 [03:56<04:18, 48.04it/s]

2026-09-09 18:25:42,870 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:42,889 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:42,916 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:25:42,937 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:42,960 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  44%|████▍     | 9701/22132 [03:57<04:23, 47.09it/s]

2026-09-09 18:25:42,980 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:42,999 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:43,021 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:43,051 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:25:43,072 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  44%|████▍     | 9706/22132 [03:57<04:28, 46.36it/s]

2026-09-09 18:25:43,094 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:43,114 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:43,136 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:43,155 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:43,174 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  44%|████▍     | 9711/22132 [03:57<04:23, 47.12it/s]

2026-09-09 18:25:43,194 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:43,219 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:25:43,240 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:43,261 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:43,288 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]

Indexing Records:  44%|████▍     | 9716/22132 [03:57<04:29, 46.11it/s]

2026-09-09 18:25:43,312 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:43,333 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:43,353 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:43,375 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:43,399 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  44%|████▍     | 9721/22132 [03:57<04:30, 45.84it/s]

2026-09-09 18:25:43,420 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:43,440 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:43,459 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:43,478 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:43,498 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:43,519 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  44%|████▍     | 9727/22132 [03:57<04:22, 47.19it/s]

2026-09-09 18:25:43,539 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:43,558 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:43,579 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:43,599 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:43,618 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:43,638 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  44%|████▍     | 9733/22132 [03:57<04:17, 48.15it/s]

2026-09-09 18:25:43,666 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:25:43,684 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:43,705 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:43,724 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:43,745 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  44%|████▍     | 9738/22132 [03:57<04:19, 47.80it/s]

2026-09-09 18:25:43,764 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:43,783 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:43,803 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:43,823 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:43,842 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:43,863 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  44%|████▍     | 9744/22132 [03:58<04:14, 48.71it/s]

2026-09-09 18:25:43,884 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:43,904 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:43,925 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:43,944 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:43,965 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  44%|████▍     | 9749/22132 [03:58<04:13, 48.80it/s]

2026-09-09 18:25:43,985 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:44,006 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:44,028 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:44,047 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:44,067 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  44%|████▍     | 9754/22132 [03:58<04:13, 48.81it/s]

2026-09-09 18:25:44,088 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:44,108 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:44,127 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:44,150 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:44,170 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  44%|████▍     | 9759/22132 [03:58<04:13, 48.82it/s]

2026-09-09 18:25:44,195 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:25:44,248 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.051s]
2026-09-09 18:25:44,269 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:44,289 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:44,308 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  44%|████▍     | 9764/22132 [03:58<04:39, 44.20it/s]

2026-09-09 18:25:44,329 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:44,348 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:44,369 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:44,389 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:44,409 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  44%|████▍     | 9769/22132 [03:58<04:30, 45.68it/s]

2026-09-09 18:25:44,431 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:44,454 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:44,477 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:44,495 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:44,515 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  44%|████▍     | 9774/22132 [03:58<04:27, 46.14it/s]

2026-09-09 18:25:44,535 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:44,557 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:44,578 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:44,599 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:44,619 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  44%|████▍     | 9779/22132 [03:58<04:24, 46.71it/s]

2026-09-09 18:25:44,639 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:44,658 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:44,687 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:25:44,710 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:44,729 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  44%|████▍     | 9784/22132 [03:58<04:26, 46.34it/s]

2026-09-09 18:25:44,751 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:44,774 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:44,793 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:44,810 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:44,830 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  44%|████▍     | 9789/22132 [03:58<04:21, 47.20it/s]

2026-09-09 18:25:44,852 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:44,869 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:44,889 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:44,908 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:44,928 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:44,947 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  44%|████▍     | 9795/22132 [03:59<04:14, 48.47it/s]

2026-09-09 18:25:44,970 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:44,989 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:45,011 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:45,034 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:45,055 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  44%|████▍     | 9800/22132 [03:59<04:17, 47.84it/s]

2026-09-09 18:25:45,077 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:45,095 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:45,118 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:45,137 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:45,153 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:45,171 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  44%|████▍     | 9806/22132 [03:59<04:10, 49.12it/s]

2026-09-09 18:25:45,191 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:45,215 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:25:45,233 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:45,250 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:45,270 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:45,288 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  44%|████▍     | 9812/22132 [03:59<04:07, 49.74it/s]

2026-09-09 18:25:45,305 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:45,324 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:45,341 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:45,358 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:45,375 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:45,393 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  44%|████▍     | 9818/22132 [03:59<03:57, 51.93it/s]

2026-09-09 18:25:45,411 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:45,432 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:45,450 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:45,468 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:45,486 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:45,504 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  44%|████▍     | 9824/22132 [03:59<03:54, 52.58it/s]

2026-09-09 18:25:45,521 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:45,539 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:45,557 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:45,576 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:45,594 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:45,617 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  44%|████▍     | 9830/22132 [03:59<03:53, 52.73it/s]

2026-09-09 18:25:45,636 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:45,653 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:45,670 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:45,688 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:45,706 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:45,726 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  44%|████▍     | 9836/22132 [03:59<03:50, 53.38it/s]

2026-09-09 18:25:45,746 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:45,763 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:45,779 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:45,797 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:45,814 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:45,833 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  44%|████▍     | 9842/22132 [03:59<03:47, 54.13it/s]

2026-09-09 18:25:45,851 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:45,870 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:45,888 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:45,905 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:45,923 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:45,939 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  44%|████▍     | 9848/22132 [04:00<03:43, 54.85it/s]

2026-09-09 18:25:45,956 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:45,973 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:45,991 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:46,008 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:46,025 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:46,043 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  45%|████▍     | 9854/22132 [04:00<03:40, 55.76it/s]

2026-09-09 18:25:46,061 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:46,079 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:46,097 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:46,115 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:46,135 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:46,153 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  45%|████▍     | 9860/22132 [04:00<03:41, 55.28it/s]

2026-09-09 18:25:46,171 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:46,192 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:46,208 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:46,225 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:46,241 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:46,257 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  45%|████▍     | 9866/22132 [04:00<03:38, 56.06it/s]

2026-09-09 18:25:46,274 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:46,291 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:46,309 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:46,328 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:46,347 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:46,364 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  45%|████▍     | 9872/22132 [04:00<03:38, 56.06it/s]

2026-09-09 18:25:46,383 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:46,401 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:46,418 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:46,436 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:46,453 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:46,470 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  45%|████▍     | 9878/22132 [04:00<03:38, 56.18it/s]

2026-09-09 18:25:46,488 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:46,507 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:46,524 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:46,542 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:46,559 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:46,576 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  45%|████▍     | 9884/22132 [04:00<03:37, 56.35it/s]

2026-09-09 18:25:46,593 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:46,613 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:46,632 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:46,651 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:46,669 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:46,687 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  45%|████▍     | 9890/22132 [04:00<03:40, 55.60it/s]

2026-09-09 18:25:46,705 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:46,722 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:46,739 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:46,757 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:46,774 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:46,796 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  45%|████▍     | 9896/22132 [04:00<03:40, 55.47it/s]

2026-09-09 18:25:46,815 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:46,833 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:46,850 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:46,867 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:46,883 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:46,901 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  45%|████▍     | 9902/22132 [04:01<03:38, 55.96it/s]

2026-09-09 18:25:46,918 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:46,934 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:46,952 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:46,968 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:46,985 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:47,003 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  45%|████▍     | 9908/22132 [04:01<03:35, 56.76it/s]

2026-09-09 18:25:47,022 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:47,040 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:47,059 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:47,076 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:47,094 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:47,111 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  45%|████▍     | 9914/22132 [04:01<03:36, 56.42it/s]

2026-09-09 18:25:47,128 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:47,147 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:47,164 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:47,181 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:47,199 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:47,216 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  45%|████▍     | 9920/22132 [04:01<03:35, 56.62it/s]

2026-09-09 18:25:47,233 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:47,252 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:47,270 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:47,287 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:47,305 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:47,323 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  45%|████▍     | 9926/22132 [04:01<03:36, 56.48it/s]

2026-09-09 18:25:47,341 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:47,358 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:47,375 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:47,392 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:47,409 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:47,429 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  45%|████▍     | 9932/22132 [04:01<03:35, 56.52it/s]

2026-09-09 18:25:47,449 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:47,466 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:47,484 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:47,500 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:47,518 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:47,535 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  45%|████▍     | 9938/22132 [04:01<03:35, 56.54it/s]

2026-09-09 18:25:47,553 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:47,570 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:47,591 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:47,608 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:47,627 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:47,644 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  45%|████▍     | 9944/22132 [04:01<03:37, 56.02it/s]

2026-09-09 18:25:47,664 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:47,682 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:47,699 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:47,717 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:47,733 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:47,751 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  45%|████▍     | 9950/22132 [04:01<03:36, 56.15it/s]

2026-09-09 18:25:47,769 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:47,788 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:47,807 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:47,825 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:47,843 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:47,859 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  45%|████▍     | 9956/22132 [04:02<03:38, 55.84it/s]

2026-09-09 18:25:47,877 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:47,894 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:47,912 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:47,931 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:47,948 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:47,965 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  45%|████▌     | 9962/22132 [04:02<03:36, 56.15it/s]

2026-09-09 18:25:47,984 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:48,000 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:48,019 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:48,037 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:48,053 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:48,070 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  45%|████▌     | 9968/22132 [04:02<03:35, 56.43it/s]

2026-09-09 18:25:48,088 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:48,108 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:48,125 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:48,143 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:48,161 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:48,179 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  45%|████▌     | 9974/22132 [04:02<03:37, 56.00it/s]

2026-09-09 18:25:48,197 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:48,214 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:48,232 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:48,248 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:48,265 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:48,281 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  45%|████▌     | 9980/22132 [04:02<03:34, 56.75it/s]

2026-09-09 18:25:48,300 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:48,319 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:48,336 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:48,353 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:48,371 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:48,388 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  45%|████▌     | 9986/22132 [04:02<03:34, 56.53it/s]

2026-09-09 18:25:48,407 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:48,423 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:48,442 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:48,459 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:48,476 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:48,494 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  45%|████▌     | 9992/22132 [04:02<03:34, 56.66it/s]

2026-09-09 18:25:48,511 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:48,534 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:48,555 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:48,573 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:48,601 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:25:48,642 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.039s]

Indexing Records:  45%|████▌     | 9998/22132 [04:02<04:01, 50.31it/s]

2026-09-09 18:25:48,681 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]
2026-09-09 18:25:48,702 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:48,720 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:48,742 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:48,760 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:48,779 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  45%|████▌     | 10004/22132 [04:02<04:10, 48.46it/s]

2026-09-09 18:25:48,797 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:48,820 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:48,843 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:48,862 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:48,880 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  45%|████▌     | 10009/22132 [04:03<04:09, 48.65it/s]

2026-09-09 18:25:48,899 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:48,918 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:48,936 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:48,953 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:48,972 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:48,997 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  45%|████▌     | 10015/22132 [04:03<04:04, 49.53it/s]

2026-09-09 18:25:49,015 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:49,030 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:49,046 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:49,061 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:49,076 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:25:49,091 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:49,106 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  45%|████▌     | 10022/22132 [04:03<03:45, 53.70it/s]

2026-09-09 18:25:49,122 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:49,137 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:49,153 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:49,170 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:49,186 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:49,201 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:49,217 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  45%|████▌     | 10029/22132 [04:03<03:34, 56.39it/s]

2026-09-09 18:25:49,234 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:49,250 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:49,265 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:49,281 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:49,297 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:49,395 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.097s]

Indexing Records:  45%|████▌     | 10035/22132 [04:03<04:15, 47.29it/s]

2026-09-09 18:25:49,413 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:49,428 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:49,442 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]
2026-09-09 18:25:49,454 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.011s]
2026-09-09 18:25:49,467 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]
2026-09-09 18:25:49,480 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.011s]
2026-09-09 18:25:49,493 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:25:49,506 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.011s]

Indexing Records:  45%|████▌     | 10043/22132 [04:03<03:44, 53.81it/s]

2026-09-09 18:25:49,520 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]
2026-09-09 18:25:49,533 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.011s]
2026-09-09 18:25:49,547 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:25:49,560 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]
2026-09-09 18:25:49,573 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]
2026-09-09 18:25:49,586 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.011s]
2026-09-09 18:25:49,601 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:49,617 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  45%|████▌     | 10051/22132 [04:03<03:25, 58.82it/s]

2026-09-09 18:25:49,631 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]
2026-09-09 18:25:49,644 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.011s]
2026-09-09 18:25:49,685 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.040s]
2026-09-09 18:25:49,700 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:49,716 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:49,730 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]
2026-09-09 18:25:49,745 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  45%|████▌     | 10058/22132 [04:03<03:29, 57.63it/s]

2026-09-09 18:25:49,759 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]
2026-09-09 18:25:49,774 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:49,788 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:25:49,804 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:49,818 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:25:49,831 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]
2026-09-09 18:25:49,846 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  45%|████▌     | 10065/22132 [04:03<03:18, 60.67it/s]

2026-09-09 18:25:49,859 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]
2026-09-09 18:25:49,873 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]
2026-09-09 18:25:49,886 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]
2026-09-09 18:25:49,900 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]
2026-09-09 18:25:49,912 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.011s]
2026-09-09 18:25:49,930 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:49,944 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:25:49,958 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]

Indexing Records:  46%|████▌     | 10073/22132 [04:04<03:09, 63.66it/s]

2026-09-09 18:25:49,972 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]
2026-09-09 18:25:49,985 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]
2026-09-09 18:25:49,998 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]
2026-09-09 18:25:50,015 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:50,028 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.011s]
2026-09-09 18:25:50,045 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:50,062 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  46%|████▌     | 10080/22132 [04:04<03:06, 64.68it/s]

2026-09-09 18:25:50,077 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:25:50,090 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]
2026-09-09 18:25:50,105 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:25:50,119 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:25:50,133 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:25:50,148 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:50,162 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:25:50,180 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  46%|████▌     | 10088/22132 [04:04<03:03, 65.66it/s]

2026-09-09 18:25:50,198 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:50,211 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]
2026-09-09 18:25:50,224 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.011s]
2026-09-09 18:25:50,237 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]
2026-09-09 18:25:50,252 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:25:50,269 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:50,282 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]

Indexing Records:  46%|████▌     | 10095/22132 [04:04<03:01, 66.44it/s]

2026-09-09 18:25:50,298 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:25:50,312 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]
2026-09-09 18:25:50,325 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]
2026-09-09 18:25:50,338 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]
2026-09-09 18:25:50,352 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:25:50,367 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:25:50,383 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  46%|████▌     | 10102/22132 [04:04<02:58, 67.31it/s]

2026-09-09 18:25:50,397 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]
2026-09-09 18:25:50,410 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.011s]
2026-09-09 18:25:50,422 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]
2026-09-09 18:25:50,435 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]
2026-09-09 18:25:50,450 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:25:50,462 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.011s]
2026-09-09 18:25:50,475 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]
2026-09-09 18:25:50,490 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]

Indexing Records:  46%|████▌     | 10110/22132 [04:04<02:52, 69.61it/s]

2026-09-09 18:25:50,503 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]
2026-09-09 18:25:50,516 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]
2026-09-09 18:25:50,530 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]
2026-09-09 18:25:50,542 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.011s]
2026-09-09 18:25:50,555 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.011s]
2026-09-09 18:25:50,568 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]
2026-09-09 18:25:50,581 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]
2026-09-09 18:25:50,595 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]

Indexing Records:  46%|████▌     | 10118/22132 [04:04<02:47, 71.60it/s]

2026-09-09 18:25:50,608 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.011s]
2026-09-09 18:25:50,631 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:50,644 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]
2026-09-09 18:25:50,659 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:25:50,673 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:25:50,687 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]
2026-09-09 18:25:50,700 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]
2026-09-09 18:25:50,713 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]

Indexing Records:  46%|████▌     | 10126/22132 [04:04<02:51, 70.18it/s]

2026-09-09 18:25:50,728 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:25:50,744 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:50,760 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:50,774 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]
2026-09-09 18:25:50,791 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:50,807 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:50,822 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:25:50,835 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]

Indexing Records:  46%|████▌     | 10134/22132 [04:04<02:54, 68.70it/s]

2026-09-09 18:25:50,851 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:25:50,867 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:50,882 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:25:50,896 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]
2026-09-09 18:25:50,912 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:50,927 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:25:50,943 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  46%|████▌     | 10141/22132 [04:05<02:57, 67.62it/s]

2026-09-09 18:25:50,959 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:25:50,974 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:50,989 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:25:51,008 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:51,024 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:51,039 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:51,058 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  46%|████▌     | 10148/22132 [04:05<03:02, 65.64it/s]

2026-09-09 18:25:51,077 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:51,095 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:51,112 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:51,135 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:51,158 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:51,182 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:25:51,203 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  46%|████▌     | 10155/22132 [04:05<03:21, 59.42it/s]

2026-09-09 18:25:51,226 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:51,243 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:51,258 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:51,275 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:51,290 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:51,310 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:51,329 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  46%|████▌     | 10162/22132 [04:05<03:25, 58.23it/s]

2026-09-09 18:25:51,352 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:51,368 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:51,387 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:51,404 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:51,418 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:25:51,438 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  46%|████▌     | 10168/22132 [04:05<03:28, 57.42it/s]

2026-09-09 18:25:51,456 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:51,472 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:51,489 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:51,506 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:51,522 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:51,538 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  46%|████▌     | 10174/22132 [04:05<03:26, 58.02it/s]

2026-09-09 18:25:51,556 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:51,573 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:51,589 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:51,607 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:51,622 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:25:51,645 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  46%|████▌     | 10180/22132 [04:05<03:27, 57.59it/s]

2026-09-09 18:25:51,663 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:51,678 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:25:51,691 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]
2026-09-09 18:25:51,706 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:25:51,720 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:25:51,738 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:51,755 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  46%|████▌     | 10187/22132 [04:05<03:21, 59.32it/s]

2026-09-09 18:25:51,771 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:51,786 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:51,802 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:51,818 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:51,836 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:51,852 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:51,868 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  46%|████▌     | 10194/22132 [04:06<03:18, 60.13it/s]

2026-09-09 18:25:51,885 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:51,901 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:51,916 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:51,932 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:51,947 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:51,965 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:51,982 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  46%|████▌     | 10201/22132 [04:06<03:17, 60.51it/s]

2026-09-09 18:25:51,999 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:52,019 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:52,034 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:52,050 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:52,067 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:52,083 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:52,101 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  46%|████▌     | 10208/22132 [04:06<03:18, 59.95it/s]

2026-09-09 18:25:52,120 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:52,135 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:52,150 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:52,166 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:52,189 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:52,205 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:52,220 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  46%|████▌     | 10215/22132 [04:06<03:19, 59.65it/s]

2026-09-09 18:25:52,236 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:52,251 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:52,268 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:52,284 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:52,301 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:52,316 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:52,332 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  46%|████▌     | 10222/22132 [04:06<03:16, 60.51it/s]

2026-09-09 18:25:52,349 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:52,364 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:52,379 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:52,395 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:52,411 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:52,426 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:52,443 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  46%|████▌     | 10229/22132 [04:06<03:14, 61.16it/s]

2026-09-09 18:25:52,459 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:52,475 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:52,490 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:25:52,505 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:52,521 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:52,536 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:52,553 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  46%|████▌     | 10236/22132 [04:06<03:11, 62.01it/s]

2026-09-09 18:25:52,569 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:52,585 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:52,600 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:52,617 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:52,632 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:52,647 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:52,662 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]

Indexing Records:  46%|████▋     | 10243/22132 [04:06<03:09, 62.60it/s]

2026-09-09 18:25:52,680 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:52,695 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:52,710 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:25:52,725 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:52,741 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:52,757 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:52,772 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]

Indexing Records:  46%|████▋     | 10250/22132 [04:06<03:08, 62.93it/s]

2026-09-09 18:25:52,787 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:25:52,804 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:52,820 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:52,835 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:52,854 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:52,872 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:52,888 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  46%|████▋     | 10257/22132 [04:07<03:11, 62.02it/s]

2026-09-09 18:25:52,904 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:52,920 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:52,935 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:52,951 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:52,966 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:52,982 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:52,996 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  46%|████▋     | 10264/22132 [04:07<03:08, 62.85it/s]

2026-09-09 18:25:53,014 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:53,029 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:53,045 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:53,062 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:53,079 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:53,094 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:53,110 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  46%|████▋     | 10271/22132 [04:07<03:09, 62.56it/s]

2026-09-09 18:25:53,126 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:53,142 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:53,160 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:53,179 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:53,194 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:53,209 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:53,225 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  46%|████▋     | 10278/22132 [04:07<03:11, 61.95it/s]

2026-09-09 18:25:53,241 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:53,257 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:53,275 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:53,290 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:53,306 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:53,323 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:53,340 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  46%|████▋     | 10285/22132 [04:07<03:12, 61.64it/s]

2026-09-09 18:25:53,356 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:53,374 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:53,390 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:53,406 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:53,428 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:53,446 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:53,462 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  47%|████▋     | 10292/22132 [04:07<03:16, 60.38it/s]

2026-09-09 18:25:53,478 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:53,493 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:53,511 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:53,528 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:53,543 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:53,559 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:53,573 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  47%|████▋     | 10299/22132 [04:07<03:13, 61.02it/s]

2026-09-09 18:25:53,592 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:53,609 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:53,625 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:53,641 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:53,658 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:53,673 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:53,693 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  47%|████▋     | 10306/22132 [04:07<03:16, 60.31it/s]

2026-09-09 18:25:53,709 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:53,724 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:53,739 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:53,755 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:53,771 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:53,791 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:53,807 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  47%|████▋     | 10313/22132 [04:07<03:15, 60.57it/s]

2026-09-09 18:25:53,824 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:53,840 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:53,855 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:53,881 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:25:53,896 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:25:53,912 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:53,928 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  47%|████▋     | 10320/22132 [04:08<03:17, 59.79it/s]

2026-09-09 18:25:53,944 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:53,960 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:53,977 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:53,992 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:54,007 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:54,023 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:54,038 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  47%|████▋     | 10327/22132 [04:08<03:14, 60.80it/s]

2026-09-09 18:25:54,054 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:54,071 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:54,086 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:54,101 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:54,117 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:54,132 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:54,146 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  47%|████▋     | 10334/22132 [04:08<03:10, 61.91it/s]

2026-09-09 18:25:54,162 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:25:54,178 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:54,193 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:54,209 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:54,225 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:54,239 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:25:54,255 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  47%|████▋     | 10341/22132 [04:08<03:08, 62.66it/s]

2026-09-09 18:25:54,271 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:54,285 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:54,305 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:54,321 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:54,337 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:54,352 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:54,368 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  47%|████▋     | 10348/22132 [04:08<03:08, 62.43it/s]

2026-09-09 18:25:54,385 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:54,402 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:54,417 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:25:54,437 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:54,454 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:54,469 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:54,486 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  47%|████▋     | 10355/22132 [04:08<03:11, 61.40it/s]

2026-09-09 18:25:54,502 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:54,518 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:54,533 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:54,549 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:54,564 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:54,578 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:25:54,595 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  47%|████▋     | 10362/22132 [04:08<03:08, 62.31it/s]

2026-09-09 18:25:54,611 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:54,628 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:54,644 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:54,660 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:54,675 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:54,691 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:54,707 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  47%|████▋     | 10369/22132 [04:08<03:08, 62.31it/s]

2026-09-09 18:25:54,724 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:54,739 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:54,754 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:54,771 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:54,787 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:54,805 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:54,821 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  47%|████▋     | 10376/22132 [04:08<03:09, 62.13it/s]

2026-09-09 18:25:54,838 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:54,855 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:54,872 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:54,889 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:54,905 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:54,920 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:54,938 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  47%|████▋     | 10383/22132 [04:09<03:11, 61.31it/s]

2026-09-09 18:25:54,955 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:54,972 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:54,988 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:55,005 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:55,021 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:55,037 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:55,053 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  47%|████▋     | 10390/22132 [04:09<03:11, 61.33it/s]

2026-09-09 18:25:55,069 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:55,085 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:55,101 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:55,118 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:55,133 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:55,150 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:55,165 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  47%|████▋     | 10397/22132 [04:09<03:10, 61.58it/s]

2026-09-09 18:25:55,181 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:55,198 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:55,214 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:55,230 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:55,246 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:55,261 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:55,277 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  47%|████▋     | 10404/22132 [04:09<03:09, 61.92it/s]

2026-09-09 18:25:55,297 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:55,314 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:55,329 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:55,346 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:55,363 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:55,379 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:55,394 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]

Indexing Records:  47%|████▋     | 10411/22132 [04:09<03:11, 61.27it/s]

2026-09-09 18:25:55,410 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:55,425 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:55,441 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:55,459 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:55,476 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:55,493 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:55,508 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  47%|████▋     | 10418/22132 [04:09<03:11, 61.24it/s]

2026-09-09 18:25:55,526 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:55,541 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:55,557 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:55,574 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:55,589 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:55,604 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:55,619 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  47%|████▋     | 10425/22132 [04:09<03:09, 61.71it/s]

2026-09-09 18:25:55,638 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:55,654 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:55,671 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:55,687 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:55,704 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:55,720 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:55,737 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  47%|████▋     | 10432/22132 [04:09<03:11, 60.94it/s]

2026-09-09 18:25:55,754 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:55,770 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:55,786 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:55,804 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:55,823 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:55,843 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:55,859 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  47%|████▋     | 10439/22132 [04:10<03:15, 59.90it/s]

2026-09-09 18:25:55,875 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:55,892 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:55,910 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:55,926 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:55,942 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:55,959 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  47%|████▋     | 10445/22132 [04:10<03:15, 59.90it/s]

2026-09-09 18:25:55,976 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:55,993 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:56,013 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:56,030 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:56,047 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:56,064 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  47%|████▋     | 10451/22132 [04:10<03:17, 59.16it/s]

2026-09-09 18:25:56,080 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:56,095 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:56,111 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:56,127 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:56,146 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:56,163 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:56,182 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  47%|████▋     | 10458/22132 [04:10<03:17, 59.19it/s]

2026-09-09 18:25:56,199 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:56,215 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:56,234 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:56,250 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:56,266 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:56,283 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  47%|████▋     | 10464/22132 [04:10<03:16, 59.24it/s]

2026-09-09 18:25:56,300 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:56,316 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:56,333 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:56,350 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:56,366 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:56,384 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  47%|████▋     | 10470/22132 [04:10<03:16, 59.35it/s]

2026-09-09 18:25:56,400 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:56,416 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:56,434 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:56,450 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:56,466 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:56,481 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:56,497 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  47%|████▋     | 10477/22132 [04:10<03:13, 60.18it/s]

2026-09-09 18:25:56,515 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:56,530 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:56,545 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:56,560 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:56,577 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:56,594 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:56,610 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  47%|████▋     | 10484/22132 [04:10<03:11, 60.71it/s]

2026-09-09 18:25:56,626 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:56,642 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:56,657 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:56,673 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:56,688 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:56,704 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:56,723 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  47%|████▋     | 10491/22132 [04:10<03:10, 61.02it/s]

2026-09-09 18:25:56,742 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:56,758 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:56,774 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:56,790 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:56,807 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:56,827 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:56,843 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  47%|████▋     | 10498/22132 [04:10<03:13, 60.19it/s]

2026-09-09 18:25:56,859 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:56,875 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:56,890 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:56,907 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:56,923 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:56,939 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:56,955 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  47%|████▋     | 10505/22132 [04:11<03:10, 60.95it/s]

2026-09-09 18:25:56,973 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:56,990 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:57,008 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:57,024 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:57,039 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:57,056 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:57,071 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  47%|████▋     | 10512/22132 [04:11<03:11, 60.70it/s]

2026-09-09 18:25:57,087 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:57,103 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:57,117 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:57,135 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:57,151 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:57,166 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:57,181 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  48%|████▊     | 10519/22132 [04:11<03:08, 61.53it/s]

2026-09-09 18:25:57,199 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:57,215 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:57,231 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:57,247 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:57,263 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:57,279 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:57,295 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  48%|████▊     | 10526/22132 [04:11<03:08, 61.44it/s]

2026-09-09 18:25:57,313 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:57,329 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:57,346 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:57,364 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:57,381 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:57,397 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:57,413 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  48%|████▊     | 10533/22132 [04:11<03:10, 60.93it/s]

2026-09-09 18:25:57,430 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:57,447 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:57,466 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:57,482 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:57,500 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:57,516 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:57,533 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  48%|████▊     | 10540/22132 [04:11<03:12, 60.13it/s]

2026-09-09 18:25:57,549 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:57,564 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:57,581 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:57,596 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:57,612 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:57,627 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:57,645 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  48%|████▊     | 10547/22132 [04:11<03:10, 60.74it/s]

2026-09-09 18:25:57,661 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:57,678 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:57,695 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:57,713 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:57,731 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:57,748 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:57,764 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  48%|████▊     | 10554/22132 [04:11<03:12, 60.14it/s]

2026-09-09 18:25:57,781 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:57,796 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:57,812 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:57,829 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:57,845 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:57,866 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:57,886 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  48%|████▊     | 10561/22132 [04:12<03:15, 59.28it/s]

2026-09-09 18:25:57,905 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:57,923 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:57,940 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:57,957 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:57,972 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:57,987 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  48%|████▊     | 10567/22132 [04:12<03:15, 59.29it/s]

2026-09-09 18:25:58,004 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:58,021 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:58,038 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:58,054 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:58,070 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:58,086 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:58,104 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  48%|████▊     | 10574/22132 [04:12<03:13, 59.60it/s]

2026-09-09 18:25:58,122 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:58,138 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:58,153 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:58,168 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:58,184 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:58,201 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:58,219 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  48%|████▊     | 10581/22132 [04:12<03:13, 59.85it/s]

2026-09-09 18:25:58,237 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:58,255 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:58,272 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:58,288 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:58,304 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:58,324 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  48%|████▊     | 10587/22132 [04:12<03:15, 59.15it/s]

2026-09-09 18:25:58,342 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:58,360 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:58,378 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:58,397 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:58,414 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:58,430 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  48%|████▊     | 10593/22132 [04:12<03:17, 58.44it/s]

2026-09-09 18:25:58,449 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:58,469 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:58,486 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:58,503 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:58,519 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:58,535 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  48%|████▊     | 10599/22132 [04:12<03:18, 57.96it/s]

2026-09-09 18:25:58,553 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:58,571 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:58,587 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:58,606 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:58,625 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:58,642 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  48%|████▊     | 10605/22132 [04:12<03:20, 57.50it/s]

2026-09-09 18:25:58,667 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:25:58,688 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:58,710 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:58,729 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:58,751 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:58,769 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  48%|████▊     | 10611/22132 [04:12<03:33, 54.02it/s]

2026-09-09 18:25:58,791 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:58,811 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:58,828 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:58,848 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:58,870 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:58,891 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  48%|████▊     | 10617/22132 [04:13<03:39, 52.43it/s]

2026-09-09 18:25:58,912 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:58,928 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:58,945 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:58,961 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:58,977 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:58,994 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  48%|████▊     | 10623/22132 [04:13<03:32, 54.10it/s]

2026-09-09 18:25:59,016 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:59,036 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:59,054 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:59,070 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:59,086 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:59,104 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  48%|████▊     | 10629/22132 [04:13<03:31, 54.28it/s]

2026-09-09 18:25:59,122 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:59,139 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:59,156 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:59,200 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.043s]
2026-09-09 18:25:59,216 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:59,244 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]

Indexing Records:  48%|████▊     | 10635/22132 [04:13<03:48, 50.23it/s]

2026-09-09 18:25:59,262 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:59,278 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:59,299 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:25:59,319 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:25:59,336 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:59,353 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  48%|████▊     | 10641/22132 [04:13<03:42, 51.56it/s]

2026-09-09 18:25:59,371 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:59,391 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:59,410 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:59,431 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:59,448 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:59,467 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  48%|████▊     | 10647/22132 [04:13<03:41, 51.87it/s]

2026-09-09 18:25:59,494 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:25:59,515 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:59,533 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:59,558 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:25:59,579 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:59,595 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  48%|████▊     | 10653/22132 [04:13<03:48, 50.24it/s]

2026-09-09 18:25:59,612 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:59,630 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:59,647 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:59,662 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:59,678 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:59,695 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:59,711 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  48%|████▊     | 10660/22132 [04:13<03:35, 53.23it/s]

2026-09-09 18:25:59,729 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:59,747 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:59,765 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:59,783 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:59,800 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:25:59,816 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  48%|████▊     | 10666/22132 [04:13<03:30, 54.37it/s]

2026-09-09 18:25:59,833 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:59,849 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:25:59,865 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:25:59,884 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:59,905 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:25:59,927 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  48%|████▊     | 10672/22132 [04:14<03:31, 54.25it/s]

2026-09-09 18:25:59,951 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:25:59,970 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:25:59,993 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:00,112 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.117s]
2026-09-09 18:26:00,181 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.068s]
2026-09-09 18:26:00,229 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.045s]

Indexing Records:  48%|████▊     | 10678/22132 [04:14<05:18, 35.94it/s]

2026-09-09 18:26:00,255 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:26:00,279 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:00,300 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:00,322 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:00,342 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  48%|████▊     | 10683/22132 [04:14<05:03, 37.74it/s]

2026-09-09 18:26:00,360 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:00,378 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:00,398 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:00,415 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:00,431 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:00,453 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  48%|████▊     | 10689/22132 [04:14<04:34, 41.65it/s]

2026-09-09 18:26:00,470 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:00,488 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:00,506 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:00,522 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:00,537 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:00,555 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  48%|████▊     | 10695/22132 [04:14<04:10, 45.71it/s]

2026-09-09 18:26:00,572 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:00,588 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:00,605 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:00,621 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:00,638 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:00,653 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:00,669 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  48%|████▊     | 10702/22132 [04:14<03:48, 50.07it/s]

2026-09-09 18:26:00,688 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:00,710 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:00,729 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:00,747 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:00,766 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:00,781 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  48%|████▊     | 10708/22132 [04:14<03:44, 50.96it/s]

2026-09-09 18:26:00,799 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:00,815 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:00,831 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:00,854 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:26:00,871 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:00,887 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  48%|████▊     | 10714/22132 [04:15<03:37, 52.47it/s]

2026-09-09 18:26:00,906 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:00,923 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:00,940 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:00,961 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:00,987 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:01,006 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  48%|████▊     | 10720/22132 [04:15<03:39, 51.88it/s]

2026-09-09 18:26:01,033 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:01,052 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:01,071 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:01,089 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:01,110 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:01,130 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  48%|████▊     | 10726/22132 [04:15<03:44, 50.88it/s]

2026-09-09 18:26:01,151 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:01,170 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:01,202 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:26:01,253 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.050s]
2026-09-09 18:26:01,300 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.046s]
2026-09-09 18:26:01,376 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.074s]

Indexing Records:  48%|████▊     | 10732/22132 [04:15<04:56, 38.44it/s]

2026-09-09 18:26:01,415 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.037s]
2026-09-09 18:26:01,461 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.044s]
2026-09-09 18:26:01,510 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.047s]
2026-09-09 18:26:01,589 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.077s]
2026-09-09 18:26:01,677 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.087s]

Indexing Records:  49%|████▊     | 10737/22132 [04:15<06:39, 28.56it/s]

2026-09-09 18:26:02,420 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.740s]
2026-09-09 18:26:02,508 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.087s]
2026-09-09 18:26:02,548 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.038s]
2026-09-09 18:26:02,597 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.048s]

Indexing Records:  49%|████▊     | 10741/22132 [04:16<15:10, 12.51it/s]

2026-09-09 18:26:02,630 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:26:02,666 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]
2026-09-09 18:26:02,731 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.064s]

Indexing Records:  49%|████▊     | 10744/22132 [04:16<13:50, 13.71it/s]

2026-09-09 18:26:02,779 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.046s]
2026-09-09 18:26:02,818 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.038s]
2026-09-09 18:26:02,866 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.046s]

Indexing Records:  49%|████▊     | 10747/22132 [04:17<12:40, 14.98it/s]

2026-09-09 18:26:02,933 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.065s]
2026-09-09 18:26:02,986 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.051s]
2026-09-09 18:26:03,123 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.136s]

Indexing Records:  49%|████▊     | 10750/22132 [04:17<13:31, 14.02it/s]

2026-09-09 18:26:03,322 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.196s]
2026-09-09 18:26:03,528 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.204s]
2026-09-09 18:26:03,825 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.296s]

Indexing Records:  49%|████▊     | 10753/22132 [04:17<21:23,  8.86it/s]

2026-09-09 18:26:03,853 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:26:03,888 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]
2026-09-09 18:26:03,918 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:26:03,952 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]

Indexing Records:  49%|████▊     | 10757/22132 [04:18<16:21, 11.59it/s]

2026-09-09 18:26:03,986 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:26:04,014 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:26:04,040 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:26:04,067 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]

Indexing Records:  49%|████▊     | 10761/22132 [04:18<12:52, 14.72it/s]

2026-09-09 18:26:04,092 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:26:04,121 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:26:04,151 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:26:04,174 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  49%|████▊     | 10765/22132 [04:18<10:26, 18.16it/s]

2026-09-09 18:26:04,200 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:26:04,224 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:26:04,254 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:26:04,276 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  49%|████▊     | 10769/22132 [04:18<08:42, 21.76it/s]

2026-09-09 18:26:04,304 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:26:04,327 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:26:04,371 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.042s]
2026-09-09 18:26:04,394 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  49%|████▊     | 10773/22132 [04:18<07:45, 24.42it/s]

2026-09-09 18:26:04,425 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:26:04,458 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:26:04,483 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:26:04,506 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  49%|████▊     | 10777/22132 [04:18<06:59, 27.04it/s]

2026-09-09 18:26:04,534 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:26:04,555 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:04,580 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:26:04,618 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.037s]

Indexing Records:  49%|████▊     | 10781/22132 [04:18<06:29, 29.18it/s]

2026-09-09 18:26:04,646 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:26:04,670 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:26:04,698 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:26:04,718 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:04,738 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  49%|████▊     | 10786/22132 [04:18<05:47, 32.61it/s]

2026-09-09 18:26:04,763 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:26:04,783 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:04,806 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:04,825 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:04,846 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  49%|████▉     | 10791/22132 [04:18<05:13, 36.21it/s]

2026-09-09 18:26:04,869 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:04,887 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:04,906 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:04,927 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:04,953 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  49%|████▉     | 10796/22132 [04:19<04:50, 39.07it/s]

2026-09-09 18:26:04,975 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:04,998 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:05,026 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:26:05,048 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:05,068 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  49%|████▉     | 10801/22132 [04:19<04:41, 40.30it/s]

2026-09-09 18:26:05,090 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:05,113 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:26:05,135 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:05,790 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.653s]
2026-09-09 18:26:05,822 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]

Indexing Records:  49%|████▉     | 10806/22132 [04:19<12:04, 15.63it/s]

2026-09-09 18:26:05,846 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:05,883 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]
2026-09-09 18:26:05,907 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:05,947 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.038s]

Indexing Records:  49%|████▉     | 10810/22132 [04:20<10:27, 18.05it/s]

2026-09-09 18:26:05,982 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:26:06,008 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:26:06,257 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.247s]
2026-09-09 18:26:06,285 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]

Indexing Records:  49%|████▉     | 10814/22132 [04:20<11:56, 15.79it/s]

2026-09-09 18:26:06,323 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]
2026-09-09 18:26:06,362 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.037s]
2026-09-09 18:26:06,513 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.150s]

Indexing Records:  49%|████▉     | 10817/22132 [04:20<12:28, 15.11it/s]

2026-09-09 18:26:06,542 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:26:06,567 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:26:06,605 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.036s]
2026-09-09 18:26:06,642 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]

Indexing Records:  49%|████▉     | 10821/22132 [04:20<10:33, 17.87it/s]

2026-09-09 18:26:06,684 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.039s]
2026-09-09 18:26:06,729 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.043s]
2026-09-09 18:26:06,765 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]

Indexing Records:  49%|████▉     | 10824/22132 [04:20<09:51, 19.12it/s]

2026-09-09 18:26:06,797 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:26:06,825 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:26:06,853 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:26:06,891 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.036s]

Indexing Records:  49%|████▉     | 10828/22132 [04:21<08:36, 21.88it/s]

2026-09-09 18:26:06,921 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:26:06,954 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:26:06,988 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]
2026-09-09 18:26:07,021 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]

Indexing Records:  49%|████▉     | 10832/22132 [04:21<07:49, 24.05it/s]

2026-09-09 18:26:07,061 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.038s]
2026-09-09 18:26:07,089 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:26:07,116 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:26:07,147 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]

Indexing Records:  49%|████▉     | 10836/22132 [04:21<07:14, 26.01it/s]

2026-09-09 18:26:07,173 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:26:07,210 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]
2026-09-09 18:26:07,244 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]
2026-09-09 18:26:07,269 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  49%|████▉     | 10840/22132 [04:21<06:46, 27.75it/s]

2026-09-09 18:26:07,306 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]
2026-09-09 18:26:07,334 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:26:07,364 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:26:07,391 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]

Indexing Records:  49%|████▉     | 10844/22132 [04:21<06:27, 29.11it/s]

2026-09-09 18:26:07,413 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:07,456 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.041s]
2026-09-09 18:26:07,511 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.053s]
2026-09-09 18:26:07,537 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  49%|████▉     | 10848/22132 [04:21<06:35, 28.56it/s]

2026-09-09 18:26:07,565 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:26:07,602 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.036s]
2026-09-09 18:26:07,637 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]
2026-09-09 18:26:07,669 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]

Indexing Records:  49%|████▉     | 10852/22132 [04:21<06:27, 29.08it/s]

2026-09-09 18:26:07,715 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.044s]
2026-09-09 18:26:07,741 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:26:07,782 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.039s]
2026-09-09 18:26:07,817 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]

Indexing Records:  49%|████▉     | 10856/22132 [04:21<06:36, 28.42it/s]

2026-09-09 18:26:07,857 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.037s]
2026-09-09 18:26:07,886 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:26:07,926 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.039s]

Indexing Records:  49%|████▉     | 10859/22132 [04:22<06:39, 28.20it/s]

2026-09-09 18:26:07,953 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:26:07,981 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:26:08,003 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:08,036 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]

Indexing Records:  49%|████▉     | 10863/22132 [04:22<06:11, 30.37it/s]

2026-09-09 18:26:08,075 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.037s]
2026-09-09 18:26:08,100 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:26:08,122 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:08,144 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  49%|████▉     | 10867/22132 [04:22<05:50, 32.14it/s]

2026-09-09 18:26:08,180 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]
2026-09-09 18:26:08,207 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:26:08,235 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:26:08,267 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]

Indexing Records:  49%|████▉     | 10871/22132 [04:22<05:48, 32.29it/s]

2026-09-09 18:26:08,292 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:26:08,334 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.040s]
2026-09-09 18:26:08,365 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:26:08,398 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]

Indexing Records:  49%|████▉     | 10875/22132 [04:22<05:54, 31.75it/s]

2026-09-09 18:26:08,421 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:26:08,458 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]
2026-09-09 18:26:08,487 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:26:08,523 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]

Indexing Records:  49%|████▉     | 10879/22132 [04:22<05:53, 31.80it/s]

2026-09-09 18:26:08,556 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:26:08,596 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.038s]
2026-09-09 18:26:08,634 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.036s]
2026-09-09 18:26:08,657 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  49%|████▉     | 10883/22132 [04:22<06:01, 31.16it/s]

2026-09-09 18:26:08,806 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.146s]
2026-09-09 18:26:08,843 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]
2026-09-09 18:26:08,874 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:26:08,952 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.076s]

Indexing Records:  49%|████▉     | 10887/22132 [04:23<08:21, 22.41it/s]

2026-09-09 18:26:08,983 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:26:09,050 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.066s]
2026-09-09 18:26:09,073 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  49%|████▉     | 10890/22132 [04:23<08:10, 22.93it/s]

2026-09-09 18:26:09,119 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.043s]
2026-09-09 18:26:09,146 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:26:09,172 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:26:09,210 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.036s]

Indexing Records:  49%|████▉     | 10894/22132 [04:23<07:36, 24.63it/s]

2026-09-09 18:26:09,241 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:26:09,275 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]
2026-09-09 18:26:09,306 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:26:09,327 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  49%|████▉     | 10898/22132 [04:23<06:56, 26.97it/s]

2026-09-09 18:26:09,354 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:26:09,375 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:09,413 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.037s]
2026-09-09 18:26:09,435 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  49%|████▉     | 10902/22132 [04:23<06:21, 29.46it/s]

2026-09-09 18:26:09,473 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.036s]
2026-09-09 18:26:09,501 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:26:09,526 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:26:09,549 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  49%|████▉     | 10906/22132 [04:23<06:02, 30.96it/s]

2026-09-09 18:26:09,583 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:26:09,623 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.038s]
2026-09-09 18:26:09,645 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:09,697 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.050s]

Indexing Records:  49%|████▉     | 10910/22132 [04:23<06:18, 29.67it/s]

2026-09-09 18:26:09,729 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:26:09,800 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.070s]
2026-09-09 18:26:09,841 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.040s]
2026-09-09 18:26:09,889 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.047s]

Indexing Records:  49%|████▉     | 10914/22132 [04:24<07:07, 26.25it/s]

2026-09-09 18:26:09,923 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:26:09,952 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:26:09,981 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:26:10,020 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.038s]

Indexing Records:  49%|████▉     | 10918/22132 [04:24<06:49, 27.41it/s]

2026-09-09 18:26:10,053 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:26:10,078 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:26:10,107 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:26:10,129 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  49%|████▉     | 10922/22132 [04:24<06:17, 29.71it/s]

2026-09-09 18:26:10,156 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:26:10,179 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:26:10,205 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:26:10,225 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:10,259 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]

Indexing Records:  49%|████▉     | 10927/22132 [04:24<05:46, 32.31it/s]

2026-09-09 18:26:10,289 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:26:10,311 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:10,332 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:10,356 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:26:10,379 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  49%|████▉     | 10932/22132 [04:24<05:21, 34.88it/s]

2026-09-09 18:26:10,401 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:10,420 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:10,443 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:26:10,465 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:10,485 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  49%|████▉     | 10937/22132 [04:24<04:54, 38.05it/s]

2026-09-09 18:26:10,520 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:26:10,547 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:26:10,569 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:10,593 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  49%|████▉     | 10941/22132 [04:24<04:55, 37.82it/s]

2026-09-09 18:26:10,618 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:26:10,638 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:10,657 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:10,684 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:26:10,704 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  49%|████▉     | 10946/22132 [04:24<04:40, 39.93it/s]

2026-09-09 18:26:10,730 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:26:10,749 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:10,771 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:10,797 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:26:10,822 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  49%|████▉     | 10951/22132 [04:24<04:35, 40.65it/s]

2026-09-09 18:26:10,848 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:26:10,879 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:26:10,900 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:10,924 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:26:10,952 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]

Indexing Records:  50%|████▉     | 10956/22132 [04:25<04:39, 39.92it/s]

2026-09-09 18:26:10,977 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:26:11,003 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:26:11,030 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:26:11,053 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:11,074 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  50%|████▉     | 10961/22132 [04:25<04:37, 40.22it/s]

2026-09-09 18:26:11,097 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:11,120 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:11,143 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:26:11,163 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:11,180 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  50%|████▉     | 10966/22132 [04:25<04:25, 42.10it/s]

2026-09-09 18:26:11,197 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:11,216 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:11,233 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:11,253 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:11,271 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:11,291 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  50%|████▉     | 10972/22132 [04:25<04:04, 45.62it/s]

2026-09-09 18:26:11,309 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:11,326 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:11,344 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:11,361 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:11,377 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:11,402 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  50%|████▉     | 10978/22132 [04:25<03:51, 48.11it/s]

2026-09-09 18:26:11,421 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:11,444 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:11,465 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:11,484 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:11,504 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  50%|████▉     | 10983/22132 [04:25<03:50, 48.32it/s]

2026-09-09 18:26:11,524 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:11,554 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:26:11,573 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:11,593 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:11,611 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  50%|████▉     | 10988/22132 [04:25<03:52, 47.85it/s]

2026-09-09 18:26:11,633 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:11,654 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:11,672 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:11,693 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:11,714 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  50%|████▉     | 10993/22132 [04:25<03:51, 48.08it/s]

2026-09-09 18:26:11,734 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:11,756 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:11,775 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:11,794 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:11,821 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]

Indexing Records:  50%|████▉     | 10998/22132 [04:25<03:53, 47.62it/s]

2026-09-09 18:26:11,841 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:11,857 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:11,874 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:11,894 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:11,913 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:11,937 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  50%|████▉     | 11004/22132 [04:26<03:47, 48.88it/s]

2026-09-09 18:26:11,958 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:11,979 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:11,999 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:12,022 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:12,049 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]

Indexing Records:  50%|████▉     | 11009/22132 [04:26<03:53, 47.60it/s]

2026-09-09 18:26:12,069 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:12,090 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:12,110 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:12,131 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:12,151 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  50%|████▉     | 11014/22132 [04:26<03:51, 48.01it/s]

2026-09-09 18:26:12,171 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:12,192 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:12,211 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:12,230 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:12,249 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:12,272 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  50%|████▉     | 11020/22132 [04:26<03:48, 48.61it/s]

2026-09-09 18:26:12,292 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:12,313 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:12,334 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:12,353 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:12,376 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  50%|████▉     | 11025/22132 [04:26<03:49, 48.45it/s]

2026-09-09 18:26:12,396 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:12,415 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:12,436 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:12,458 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:12,480 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  50%|████▉     | 11030/22132 [04:26<03:49, 48.33it/s]

2026-09-09 18:26:12,500 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:12,522 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:12,543 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:12,564 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:12,587 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  50%|████▉     | 11035/22132 [04:26<03:52, 47.79it/s]

2026-09-09 18:26:12,609 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:12,628 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:12,648 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:12,664 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:12,682 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:12,698 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  50%|████▉     | 11041/22132 [04:26<03:42, 49.79it/s]

2026-09-09 18:26:12,726 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:26:12,747 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:12,766 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:12,786 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:12,804 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  50%|████▉     | 11046/22132 [04:26<03:46, 48.93it/s]

2026-09-09 18:26:12,826 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:12,848 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:12,870 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:12,889 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:12,911 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  50%|████▉     | 11051/22132 [04:27<03:49, 48.31it/s]

2026-09-09 18:26:12,933 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:12,952 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:12,972 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:12,992 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:13,012 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  50%|████▉     | 11056/22132 [04:27<03:47, 48.72it/s]

2026-09-09 18:26:13,032 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:13,051 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:13,072 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:13,091 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:13,110 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:13,132 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  50%|████▉     | 11062/22132 [04:27<03:45, 49.09it/s]

2026-09-09 18:26:13,151 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:13,170 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:13,188 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:13,205 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:13,223 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:13,244 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  50%|█████     | 11068/22132 [04:27<03:39, 50.50it/s]

2026-09-09 18:26:13,265 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:13,284 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:13,303 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:13,323 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:13,343 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:13,361 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  50%|█████     | 11074/22132 [04:27<03:38, 50.64it/s]

2026-09-09 18:26:13,381 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:13,401 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:13,421 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:13,441 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:13,461 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:13,479 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  50%|█████     | 11080/22132 [04:27<03:37, 50.72it/s]

2026-09-09 18:26:13,502 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:13,521 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:13,541 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:13,561 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:13,585 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:26:13,604 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  50%|█████     | 11086/22132 [04:27<03:41, 49.94it/s]

2026-09-09 18:26:13,625 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:13,645 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:13,665 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:13,684 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:13,706 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  50%|█████     | 11091/22132 [04:27<03:42, 49.62it/s]

2026-09-09 18:26:13,726 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:13,744 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:13,763 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:13,783 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:13,805 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:13,825 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  50%|█████     | 11097/22132 [04:27<03:41, 49.86it/s]

2026-09-09 18:26:13,847 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:13,865 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:13,885 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:13,903 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:13,921 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:13,942 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  50%|█████     | 11103/22132 [04:28<03:39, 50.25it/s]

2026-09-09 18:26:13,961 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:13,982 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:14,000 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:14,017 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:14,045 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:26:14,064 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  50%|█████     | 11109/22132 [04:28<03:40, 49.96it/s]

2026-09-09 18:26:14,087 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:14,106 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:14,123 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:14,144 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:14,167 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  50%|█████     | 11114/22132 [04:28<03:42, 49.61it/s]

2026-09-09 18:26:14,229 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.060s]
2026-09-09 18:26:14,251 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:14,272 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:14,297 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:26:14,331 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]

Indexing Records:  50%|█████     | 11119/22132 [04:28<04:20, 42.25it/s]

2026-09-09 18:26:14,365 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:26:14,385 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:14,407 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:14,439 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:26:14,478 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.037s]

Indexing Records:  50%|█████     | 11124/22132 [04:28<04:38, 39.59it/s]

2026-09-09 18:26:14,497 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:14,519 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:14,548 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:26:14,586 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.037s]
2026-09-09 18:26:14,609 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  50%|█████     | 11129/22132 [04:28<04:41, 39.13it/s]

2026-09-09 18:26:14,634 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:26:14,669 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]
2026-09-09 18:26:14,705 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]
2026-09-09 18:26:14,726 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:14,754 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]

Indexing Records:  50%|█████     | 11134/22132 [04:28<04:51, 37.67it/s]

2026-09-09 18:26:14,775 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:14,795 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:14,817 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:14,838 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:14,875 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]

Indexing Records:  50%|█████     | 11139/22132 [04:29<04:44, 38.69it/s]

2026-09-09 18:26:14,899 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:26:14,918 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:14,936 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:14,957 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:14,984 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  50%|█████     | 11144/22132 [04:29<04:31, 40.48it/s]

2026-09-09 18:26:15,009 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:26:15,033 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:26:15,054 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:15,073 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:15,098 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  50%|█████     | 11149/22132 [04:29<04:24, 41.46it/s]

2026-09-09 18:26:15,118 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:15,137 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:15,156 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:15,176 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:15,198 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  50%|█████     | 11154/22132 [04:29<04:11, 43.64it/s]

2026-09-09 18:26:15,218 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:15,239 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:15,259 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:15,281 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:15,303 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  50%|█████     | 11159/22132 [04:29<04:04, 44.82it/s]

2026-09-09 18:26:15,325 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:15,345 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:15,362 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:15,379 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:15,396 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:15,417 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  50%|█████     | 11165/22132 [04:29<03:52, 47.16it/s]

2026-09-09 18:26:15,439 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:15,461 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:15,482 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:15,564 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.081s]
2026-09-09 18:26:15,615 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.049s]

Indexing Records:  50%|█████     | 11170/22132 [04:29<04:50, 37.80it/s]

2026-09-09 18:26:15,639 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:26:15,667 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:26:15,696 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:26:15,716 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:15,738 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  50%|█████     | 11175/22132 [04:29<04:43, 38.58it/s]

2026-09-09 18:26:15,759 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:15,783 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:26:15,821 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.037s]
2026-09-09 18:26:15,867 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.044s]
2026-09-09 18:26:15,893 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  51%|█████     | 11180/22132 [04:30<05:00, 36.43it/s]

2026-09-09 18:26:15,926 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:26:15,948 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:15,977 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:26:16,013 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]

Indexing Records:  51%|█████     | 11184/22132 [04:30<05:07, 35.62it/s]

2026-09-09 18:26:16,049 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]
2026-09-09 18:26:16,076 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:26:16,099 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:26:16,131 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]

Indexing Records:  51%|█████     | 11188/22132 [04:30<05:11, 35.16it/s]

2026-09-09 18:26:16,176 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.042s]
2026-09-09 18:26:16,218 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.041s]
2026-09-09 18:26:16,237 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:16,256 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  51%|█████     | 11192/22132 [04:30<05:19, 34.22it/s]

2026-09-09 18:26:16,290 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:26:16,341 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.050s]
2026-09-09 18:26:16,368 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:26:16,388 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  51%|█████     | 11196/22132 [04:30<05:31, 33.02it/s]

2026-09-09 18:26:16,424 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]
2026-09-09 18:26:16,453 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:26:16,483 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:26:16,515 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]

Indexing Records:  51%|█████     | 11200/22132 [04:30<05:35, 32.56it/s]

2026-09-09 18:26:16,537 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:16,567 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:26:16,609 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.041s]
2026-09-09 18:26:16,640 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]

Indexing Records:  51%|█████     | 11204/22132 [04:30<05:37, 32.42it/s]

2026-09-09 18:26:16,676 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]
2026-09-09 18:26:16,709 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:26:16,730 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:16,764 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]

Indexing Records:  51%|█████     | 11208/22132 [04:30<05:37, 32.37it/s]

2026-09-09 18:26:16,786 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:16,814 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:26:16,846 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:26:16,878 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]

Indexing Records:  51%|█████     | 11212/22132 [04:31<05:29, 33.12it/s]

2026-09-09 18:26:16,904 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:26:16,942 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.036s]
2026-09-09 18:26:16,982 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.038s]
2026-09-09 18:26:17,002 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  51%|█████     | 11216/22132 [04:31<05:31, 32.88it/s]

2026-09-09 18:26:17,039 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]
2026-09-09 18:26:17,063 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:26:17,089 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:26:17,115 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  51%|█████     | 11220/22132 [04:31<05:24, 33.58it/s]

2026-09-09 18:26:17,140 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:26:17,284 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.142s]
2026-09-09 18:26:17,315 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:26:17,334 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  51%|█████     | 11224/22132 [04:31<06:45, 26.87it/s]

2026-09-09 18:26:17,353 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:17,394 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.040s]
2026-09-09 18:26:17,414 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:17,441 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]

Indexing Records:  51%|█████     | 11228/22132 [04:31<06:12, 29.30it/s]

2026-09-09 18:26:17,463 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:17,494 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:26:17,515 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:17,553 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.037s]

Indexing Records:  51%|█████     | 11232/22132 [04:31<05:51, 30.98it/s]

2026-09-09 18:26:17,576 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:17,598 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:17,630 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:26:17,656 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]

Indexing Records:  51%|█████     | 11236/22132 [04:31<05:30, 32.99it/s]

2026-09-09 18:26:17,682 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:26:17,708 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:26:17,738 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:26:17,765 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]

Indexing Records:  51%|█████     | 11240/22132 [04:31<05:20, 34.03it/s]

2026-09-09 18:26:17,786 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:17,810 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:26:17,846 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]
2026-09-09 18:26:17,868 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  51%|█████     | 11244/22132 [04:32<05:08, 35.33it/s]

2026-09-09 18:26:17,893 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:26:17,912 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:17,931 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:17,952 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:17,972 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  51%|█████     | 11249/22132 [04:32<04:39, 38.89it/s]

2026-09-09 18:26:17,992 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:18,012 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:18,032 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:18,054 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:18,073 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  51%|█████     | 11254/22132 [04:32<04:19, 41.86it/s]

2026-09-09 18:26:18,092 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:18,110 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:18,129 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:18,147 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:18,167 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:18,186 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  51%|█████     | 11260/22132 [04:32<03:59, 45.43it/s]

2026-09-09 18:26:18,207 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:18,227 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:18,249 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:18,269 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:18,291 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  51%|█████     | 11265/22132 [04:32<03:56, 46.01it/s]

2026-09-09 18:26:18,313 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:18,331 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:18,350 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:18,372 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:18,392 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  51%|█████     | 11270/22132 [04:32<03:51, 47.00it/s]

2026-09-09 18:26:18,412 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:18,433 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:18,452 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:18,473 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:18,493 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  51%|█████     | 11275/22132 [04:32<03:47, 47.79it/s]

2026-09-09 18:26:18,517 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:26:18,538 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:18,557 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:18,576 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:18,599 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  51%|█████     | 11280/22132 [04:32<03:48, 47.60it/s]

2026-09-09 18:26:18,619 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:18,640 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:18,660 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:18,680 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:18,699 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  51%|█████     | 11285/22132 [04:32<03:44, 48.23it/s]

2026-09-09 18:26:18,722 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:18,742 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:18,762 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:18,785 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:26:18,806 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  51%|█████     | 11290/22132 [04:32<03:46, 47.81it/s]

2026-09-09 18:26:18,828 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:18,848 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:18,866 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:18,885 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:18,908 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  51%|█████     | 11295/22132 [04:33<03:45, 48.16it/s]

2026-09-09 18:26:18,930 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:18,954 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:26:18,977 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:18,998 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:19,017 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  51%|█████     | 11300/22132 [04:33<03:48, 47.42it/s]

2026-09-09 18:26:19,042 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:26:19,064 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:19,084 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:19,104 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:19,126 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  51%|█████     | 11305/22132 [04:33<03:50, 47.01it/s]

2026-09-09 18:26:19,148 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:19,172 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:26:19,193 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:19,213 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:19,234 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  51%|█████     | 11310/22132 [04:33<03:51, 46.72it/s]

2026-09-09 18:26:19,254 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:19,272 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:19,294 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:19,313 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:19,331 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:19,353 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  51%|█████     | 11316/22132 [04:33<03:45, 47.97it/s]

2026-09-09 18:26:19,375 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:19,397 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:19,417 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:19,438 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:19,460 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  51%|█████     | 11321/22132 [04:33<03:46, 47.65it/s]

2026-09-09 18:26:19,479 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:19,499 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:19,520 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:19,541 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:19,567 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]

Indexing Records:  51%|█████     | 11326/22132 [04:33<03:48, 47.33it/s]

2026-09-09 18:26:19,588 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:19,608 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:19,627 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:19,649 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:19,668 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  51%|█████     | 11331/22132 [04:33<03:45, 47.94it/s]

2026-09-09 18:26:19,687 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:19,706 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:19,728 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:19,750 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:19,769 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  51%|█████     | 11336/22132 [04:33<03:42, 48.44it/s]

2026-09-09 18:26:19,791 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:19,811 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:19,827 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:19,843 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:19,860 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:19,884 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  51%|█████     | 11342/22132 [04:34<03:37, 49.65it/s]

2026-09-09 18:26:19,907 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:19,929 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:19,950 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:19,973 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:26:19,992 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  51%|█████▏    | 11347/22132 [04:34<03:42, 48.54it/s]

2026-09-09 18:26:20,014 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:20,076 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.060s]
2026-09-09 18:26:20,098 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:20,117 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:20,137 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  51%|█████▏    | 11352/22132 [04:34<04:08, 43.42it/s]

2026-09-09 18:26:20,157 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:20,188 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:26:20,207 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:20,228 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:20,246 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  51%|█████▏    | 11357/22132 [04:34<04:04, 44.10it/s]

2026-09-09 18:26:20,266 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:20,286 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:20,320 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]
2026-09-09 18:26:20,340 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:20,360 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  51%|█████▏    | 11362/22132 [04:34<04:04, 43.99it/s]

2026-09-09 18:26:20,384 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:20,405 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:20,424 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:20,445 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:20,462 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  51%|█████▏    | 11367/22132 [04:34<03:57, 45.36it/s]

2026-09-09 18:26:20,483 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:20,502 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:20,523 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:20,543 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:20,566 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  51%|█████▏    | 11372/22132 [04:34<03:52, 46.20it/s]

2026-09-09 18:26:20,584 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:20,600 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:20,619 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:20,637 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:20,660 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:20,679 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  51%|█████▏    | 11378/22132 [04:34<03:42, 48.33it/s]

2026-09-09 18:26:20,698 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:20,716 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:20,733 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:20,750 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:20,768 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:20,790 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  51%|█████▏    | 11384/22132 [04:34<03:34, 50.12it/s]

2026-09-09 18:26:20,812 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:20,832 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:20,851 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:20,869 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:20,891 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:20,910 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  51%|█████▏    | 11390/22132 [04:35<03:35, 49.94it/s]

2026-09-09 18:26:20,931 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:20,952 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:20,974 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:20,998 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:26:21,021 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:26:21,043 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  51%|█████▏    | 11396/22132 [04:35<03:41, 48.42it/s]

2026-09-09 18:26:21,064 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:21,084 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:21,105 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:21,126 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:21,147 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  52%|█████▏    | 11401/22132 [04:35<03:42, 48.30it/s]

2026-09-09 18:26:21,167 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:21,185 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:21,205 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:21,231 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:26:21,254 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  52%|█████▏    | 11406/22132 [04:35<03:43, 47.91it/s]

2026-09-09 18:26:21,278 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:26:21,299 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:21,320 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:21,339 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:21,359 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  52%|█████▏    | 11411/22132 [04:35<03:44, 47.80it/s]

2026-09-09 18:26:21,379 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:21,403 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:26:21,422 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:21,441 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:21,463 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  52%|█████▏    | 11416/22132 [04:35<03:44, 47.82it/s]

2026-09-09 18:26:21,483 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:21,503 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:21,524 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:21,543 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:21,564 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  52%|█████▏    | 11421/22132 [04:35<03:41, 48.39it/s]

2026-09-09 18:26:21,584 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:21,603 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:21,622 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:21,640 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:21,667 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]

Indexing Records:  52%|█████▏    | 11426/22132 [04:35<03:41, 48.42it/s]

2026-09-09 18:26:21,683 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:21,701 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:21,720 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:21,741 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:21,762 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:21,782 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  52%|█████▏    | 11432/22132 [04:35<03:35, 49.58it/s]

2026-09-09 18:26:21,803 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:21,826 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:21,849 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:26:21,872 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:26:21,895 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  52%|█████▏    | 11437/22132 [04:36<03:43, 47.88it/s]

2026-09-09 18:26:21,916 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:21,937 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:21,957 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:21,980 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:21,999 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  52%|█████▏    | 11442/22132 [04:36<03:42, 47.97it/s]

2026-09-09 18:26:22,026 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:26:22,046 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:22,067 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:22,087 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:22,105 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  52%|█████▏    | 11447/22132 [04:36<03:43, 47.80it/s]

2026-09-09 18:26:22,125 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:22,147 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:22,167 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:22,186 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:22,206 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  52%|█████▏    | 11452/22132 [04:36<03:41, 48.25it/s]

2026-09-09 18:26:22,226 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:22,245 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:22,266 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:22,285 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:22,307 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  52%|█████▏    | 11457/22132 [04:36<03:39, 48.59it/s]

2026-09-09 18:26:22,328 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:22,347 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:22,365 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:22,389 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:26:22,405 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:22,420 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  52%|█████▏    | 11463/22132 [04:36<03:33, 50.00it/s]

2026-09-09 18:26:22,438 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:22,457 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:22,479 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:22,497 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:22,518 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:22,534 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  52%|█████▏    | 11469/22132 [04:36<03:29, 50.81it/s]

2026-09-09 18:26:22,552 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:22,570 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:22,592 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:22,612 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:22,633 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:22,651 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  52%|█████▏    | 11475/22132 [04:36<03:28, 51.00it/s]

2026-09-09 18:26:22,683 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:26:22,704 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:22,725 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:22,746 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:22,765 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:22,786 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  52%|█████▏    | 11481/22132 [04:36<03:38, 48.79it/s]

2026-09-09 18:26:22,809 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:22,830 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:22,848 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:22,877 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:26:22,897 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  52%|█████▏    | 11486/22132 [04:37<03:43, 47.64it/s]

2026-09-09 18:26:22,919 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:22,938 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:22,957 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:22,974 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:22,995 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:23,020 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  52%|█████▏    | 11492/22132 [04:37<03:41, 48.03it/s]

2026-09-09 18:26:23,040 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:23,063 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:26:23,085 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:23,107 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:23,131 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  52%|█████▏    | 11497/22132 [04:37<03:45, 47.20it/s]

2026-09-09 18:26:23,155 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:26:23,176 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:23,198 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:23,221 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:23,240 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  52%|█████▏    | 11502/22132 [04:37<03:46, 46.84it/s]

2026-09-09 18:26:23,259 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:23,284 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:26:23,303 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:23,325 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:23,345 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  52%|█████▏    | 11507/22132 [04:37<03:45, 47.06it/s]

2026-09-09 18:26:23,368 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:23,388 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:23,407 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:23,426 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:23,446 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  52%|█████▏    | 11512/22132 [04:37<03:42, 47.73it/s]

2026-09-09 18:26:23,466 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:23,487 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:23,507 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:23,530 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:23,549 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  52%|█████▏    | 11517/22132 [04:37<03:41, 47.95it/s]

2026-09-09 18:26:23,569 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:23,587 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:23,606 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:23,623 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:23,642 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:23,663 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  52%|█████▏    | 11523/22132 [04:37<03:34, 49.40it/s]

2026-09-09 18:26:23,689 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:26:23,709 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:23,728 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:23,747 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:23,766 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  52%|█████▏    | 11528/22132 [04:37<03:35, 49.17it/s]

2026-09-09 18:26:23,788 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:23,806 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:23,831 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:26:23,850 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:23,894 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.042s]

Indexing Records:  52%|█████▏    | 11533/22132 [04:38<03:51, 45.81it/s]

2026-09-09 18:26:23,920 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:26:23,937 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:23,959 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:23,982 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:24,001 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  52%|█████▏    | 11538/22132 [04:38<03:50, 46.02it/s]

2026-09-09 18:26:24,024 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:24,045 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:24,065 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:24,084 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:24,104 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  52%|█████▏    | 11543/22132 [04:38<03:46, 46.76it/s]

2026-09-09 18:26:24,125 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:24,143 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:24,165 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:24,183 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:24,206 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  52%|█████▏    | 11548/22132 [04:38<03:43, 47.39it/s]

2026-09-09 18:26:24,229 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:24,250 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:24,268 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:24,289 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:24,310 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  52%|█████▏    | 11553/22132 [04:38<03:42, 47.61it/s]

2026-09-09 18:26:24,327 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:24,345 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:24,366 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:24,390 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:26:24,417 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]

Indexing Records:  52%|█████▏    | 11558/22132 [04:38<03:43, 47.35it/s]

2026-09-09 18:26:24,438 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:24,466 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:26:24,485 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:24,503 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:24,521 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  52%|█████▏    | 11563/22132 [04:38<03:42, 47.53it/s]

2026-09-09 18:26:24,545 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:26:24,569 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:26:24,591 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:24,611 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:24,630 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  52%|█████▏    | 11568/22132 [04:38<03:44, 47.04it/s]

2026-09-09 18:26:24,661 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:26:24,680 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:24,709 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:26:24,730 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:24,753 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  52%|█████▏    | 11573/22132 [04:38<03:54, 44.96it/s]

2026-09-09 18:26:24,773 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:24,797 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:26:24,819 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:24,840 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:24,860 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  52%|█████▏    | 11578/22132 [04:39<03:52, 45.36it/s]

2026-09-09 18:26:24,882 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:24,902 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:24,921 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:24,939 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:24,958 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  52%|█████▏    | 11583/22132 [04:39<03:48, 46.18it/s]

2026-09-09 18:26:24,984 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:25,004 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:25,026 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:25,044 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:25,065 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  52%|█████▏    | 11588/22132 [04:39<03:43, 47.11it/s]

2026-09-09 18:26:25,089 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:25,115 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:26:25,141 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:26:25,165 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:26:25,188 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  52%|█████▏    | 11593/22132 [04:39<03:54, 44.97it/s]

2026-09-09 18:26:25,226 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.036s]
2026-09-09 18:26:25,250 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:26:25,286 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]
2026-09-09 18:26:25,310 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:26:25,333 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  52%|█████▏    | 11598/22132 [04:39<04:15, 41.20it/s]

2026-09-09 18:26:25,359 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:26:25,381 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:25,407 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:26:25,425 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:25,452 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]

Indexing Records:  52%|█████▏    | 11603/22132 [04:39<04:13, 41.53it/s]

2026-09-09 18:26:25,471 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:25,491 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:25,511 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:25,542 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:26:25,570 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]

Indexing Records:  52%|█████▏    | 11608/22132 [04:39<04:12, 41.75it/s]

2026-09-09 18:26:25,598 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:26:25,619 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:25,642 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:25,664 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:25,701 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]

Indexing Records:  52%|█████▏    | 11613/22132 [04:39<04:19, 40.60it/s]

2026-09-09 18:26:25,726 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:26:25,747 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:25,775 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:26:25,795 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:25,814 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  52%|█████▏    | 11618/22132 [04:39<04:12, 41.66it/s]

2026-09-09 18:26:25,834 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:25,856 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:25,876 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:25,901 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:26:25,925 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  53%|█████▎    | 11623/22132 [04:40<04:06, 42.56it/s]

2026-09-09 18:26:25,957 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:26:25,975 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:25,999 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:26:26,025 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:26:26,054 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]

Indexing Records:  53%|█████▎    | 11628/22132 [04:40<04:13, 41.39it/s]

2026-09-09 18:26:26,075 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:26,099 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:26:26,118 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:26,137 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:26,161 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  53%|█████▎    | 11633/22132 [04:40<04:05, 42.78it/s]

2026-09-09 18:26:26,181 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:26,202 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:26,221 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:26,248 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:26:26,268 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  53%|█████▎    | 11638/22132 [04:40<03:58, 43.95it/s]

2026-09-09 18:26:26,296 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:26:26,318 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:26,337 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:26,390 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.052s]
2026-09-09 18:26:26,412 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  53%|█████▎    | 11643/22132 [04:40<04:18, 40.64it/s]

2026-09-09 18:26:26,431 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:26,449 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:26,468 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:26,494 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:26:26,513 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:26,532 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  53%|█████▎    | 11649/22132 [04:40<04:01, 43.46it/s]

2026-09-09 18:26:26,554 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:26,572 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:26,588 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:26,607 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:26,624 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:26,643 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  53%|█████▎    | 11655/22132 [04:40<03:45, 46.51it/s]

2026-09-09 18:26:26,666 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:26:26,690 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:26:26,714 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:26:26,736 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:26,758 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  53%|█████▎    | 11660/22132 [04:40<03:49, 45.61it/s]

2026-09-09 18:26:26,779 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:26,798 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:26,817 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:26,835 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:26,856 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:26,875 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  53%|█████▎    | 11666/22132 [04:41<03:41, 47.29it/s]

2026-09-09 18:26:26,898 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:26,917 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:26,941 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:26:26,960 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:26,981 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  53%|█████▎    | 11671/22132 [04:41<03:41, 47.22it/s]

2026-09-09 18:26:27,003 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:27,025 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:27,045 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:27,064 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:27,084 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  53%|█████▎    | 11676/22132 [04:41<03:39, 47.64it/s]

2026-09-09 18:26:27,104 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:27,125 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:27,146 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:27,168 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:27,186 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  53%|█████▎    | 11681/22132 [04:41<03:37, 48.02it/s]

2026-09-09 18:26:27,206 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:27,228 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:27,247 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:27,267 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:27,290 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  53%|█████▎    | 11686/22132 [04:41<03:37, 48.06it/s]

2026-09-09 18:26:27,312 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:27,332 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:27,350 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:27,370 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:27,387 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:27,405 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  53%|█████▎    | 11692/22132 [04:41<03:31, 49.28it/s]

2026-09-09 18:26:27,427 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:27,447 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:27,467 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:27,491 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:27,509 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  53%|█████▎    | 11697/22132 [04:41<03:32, 49.00it/s]

2026-09-09 18:26:27,532 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:27,550 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:27,570 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:27,589 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:27,609 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:27,628 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  53%|█████▎    | 11703/22132 [04:41<03:31, 49.40it/s]

2026-09-09 18:26:27,649 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:27,669 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:27,686 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:27,708 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:27,729 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  53%|█████▎    | 11708/22132 [04:41<03:30, 49.42it/s]

2026-09-09 18:26:27,753 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:27,778 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:26:27,799 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:27,818 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:27,839 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  53%|█████▎    | 11713/22132 [04:41<03:36, 48.20it/s]

2026-09-09 18:26:27,909 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.068s]
2026-09-09 18:26:27,928 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:27,947 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:27,968 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:27,986 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  53%|█████▎    | 11718/22132 [04:42<04:02, 43.03it/s]

2026-09-09 18:26:28,006 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:28,025 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:28,046 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:28,064 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:28,085 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:28,104 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  53%|█████▎    | 11724/22132 [04:42<03:49, 45.38it/s]

2026-09-09 18:26:28,123 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:28,143 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:28,163 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:28,182 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:28,200 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:28,220 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  53%|█████▎    | 11730/22132 [04:42<03:40, 47.20it/s]

2026-09-09 18:26:28,237 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:28,257 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:28,279 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:28,296 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:28,312 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:28,333 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  53%|█████▎    | 11736/22132 [04:42<03:32, 48.97it/s]

2026-09-09 18:26:28,353 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:28,373 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:28,389 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:28,413 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:26:28,434 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  53%|█████▎    | 11741/22132 [04:42<03:31, 49.05it/s]

2026-09-09 18:26:28,455 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:28,474 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:28,493 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:28,514 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:28,531 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:28,549 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  53%|█████▎    | 11747/22132 [04:42<03:27, 49.96it/s]

2026-09-09 18:26:28,569 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:28,590 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:28,609 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:28,627 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:28,648 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:28,669 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  53%|█████▎    | 11753/22132 [04:42<03:27, 49.98it/s]

2026-09-09 18:26:28,690 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:28,712 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:28,728 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:28,757 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:26:28,778 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:28,798 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  53%|█████▎    | 11759/22132 [04:42<03:31, 48.96it/s]

2026-09-09 18:26:28,819 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:28,838 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:28,857 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:28,874 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:28,896 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:28,920 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  53%|█████▎    | 11765/22132 [04:43<03:31, 48.99it/s]

2026-09-09 18:26:28,938 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:28,960 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:28,977 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:28,999 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:29,020 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  53%|█████▎    | 11770/22132 [04:43<03:30, 49.18it/s]

2026-09-09 18:26:29,039 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:29,056 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:29,077 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:29,093 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:29,110 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:29,127 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  53%|█████▎    | 11776/22132 [04:43<03:22, 51.26it/s]

2026-09-09 18:26:29,144 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:29,166 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:29,189 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:29,208 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:29,227 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:29,246 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  53%|█████▎    | 11782/22132 [04:43<03:23, 50.91it/s]

2026-09-09 18:26:29,264 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:29,283 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:29,300 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:29,318 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:29,337 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:29,356 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  53%|█████▎    | 11788/22132 [04:43<03:18, 52.00it/s]

2026-09-09 18:26:29,375 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:29,392 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:29,410 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:29,431 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:29,450 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:29,470 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  53%|█████▎    | 11794/22132 [04:43<03:17, 52.28it/s]

2026-09-09 18:26:29,488 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:29,505 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:29,526 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:29,545 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:29,562 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:29,580 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  53%|█████▎    | 11800/22132 [04:43<03:15, 52.88it/s]

2026-09-09 18:26:29,598 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:29,616 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:29,637 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:29,655 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:29,677 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:29,697 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  53%|█████▎    | 11806/22132 [04:43<03:17, 52.39it/s]

2026-09-09 18:26:29,721 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:26:29,741 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:29,762 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:29,780 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:29,802 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:29,820 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  53%|█████▎    | 11812/22132 [04:43<03:21, 51.21it/s]

2026-09-09 18:26:29,840 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:29,862 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:29,881 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:29,904 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:26:29,925 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:29,950 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  53%|█████▎    | 11818/22132 [04:44<03:27, 49.64it/s]

2026-09-09 18:26:29,968 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:29,991 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:30,014 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:30,039 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:26:30,056 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  53%|█████▎    | 11823/22132 [04:44<03:30, 48.93it/s]

2026-09-09 18:26:30,073 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:30,090 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:30,108 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:30,125 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:30,141 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:30,158 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  53%|█████▎    | 11829/22132 [04:44<03:19, 51.67it/s]

2026-09-09 18:26:30,175 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:30,192 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:30,213 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:30,234 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:30,252 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:30,269 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  53%|█████▎    | 11835/22132 [04:44<03:16, 52.39it/s]

2026-09-09 18:26:30,285 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:30,303 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:30,322 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:30,340 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:30,356 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:30,372 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  54%|█████▎    | 11841/22132 [04:44<03:10, 54.04it/s]

2026-09-09 18:26:30,390 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:30,407 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:30,423 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:30,441 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:30,457 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:30,474 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  54%|█████▎    | 11847/22132 [04:44<03:05, 55.42it/s]

2026-09-09 18:26:30,490 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:30,506 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:30,523 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:30,541 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:30,559 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:30,574 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  54%|█████▎    | 11853/22132 [04:44<03:01, 56.67it/s]

2026-09-09 18:26:30,595 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:30,610 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:30,626 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:30,641 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:30,656 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:30,672 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:30,688 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  54%|█████▎    | 11860/22132 [04:44<02:56, 58.23it/s]

2026-09-09 18:26:30,708 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:30,724 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:30,740 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:30,755 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:30,773 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:30,789 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  54%|█████▎    | 11866/22132 [04:44<02:55, 58.44it/s]

2026-09-09 18:26:30,809 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:30,826 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:30,841 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:30,859 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:30,874 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:30,895 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  54%|█████▎    | 11872/22132 [04:45<02:57, 57.92it/s]

2026-09-09 18:26:30,913 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:30,930 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:30,947 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:30,963 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:30,980 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:30,996 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  54%|█████▎    | 11878/22132 [04:45<02:55, 58.47it/s]

2026-09-09 18:26:31,033 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.036s]
2026-09-09 18:26:31,053 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:31,069 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:31,087 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:31,105 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:31,124 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  54%|█████▎    | 11884/22132 [04:45<03:08, 54.40it/s]

2026-09-09 18:26:31,144 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:31,166 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:31,188 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:31,219 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:26:31,238 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:31,255 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  54%|█████▎    | 11890/22132 [04:45<03:18, 51.52it/s]

2026-09-09 18:26:31,274 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:31,289 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:31,305 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:31,323 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:31,340 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:31,357 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  54%|█████▍    | 11896/22132 [04:45<03:11, 53.56it/s]

2026-09-09 18:26:31,373 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:31,388 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:31,406 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:31,422 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:31,438 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:31,454 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:31,472 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  54%|█████▍    | 11903/22132 [04:45<03:03, 55.81it/s]

2026-09-09 18:26:31,489 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:31,506 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:31,522 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:31,537 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:31,554 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:31,572 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  54%|█████▍    | 11909/22132 [04:45<02:59, 56.91it/s]

2026-09-09 18:26:31,589 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:31,607 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:31,624 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:31,641 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:31,656 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:31,675 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  54%|█████▍    | 11915/22132 [04:45<02:58, 57.33it/s]

2026-09-09 18:26:31,693 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:31,708 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:31,725 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:31,743 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:31,758 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:31,777 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  54%|█████▍    | 11921/22132 [04:45<02:57, 57.65it/s]

2026-09-09 18:26:31,798 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:31,819 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:31,835 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:31,851 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:31,867 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:31,885 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  54%|█████▍    | 11927/22132 [04:46<02:58, 57.11it/s]

2026-09-09 18:26:31,903 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:31,919 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:31,935 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:31,950 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:31,966 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:31,983 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:31,998 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  54%|█████▍    | 11934/22132 [04:46<02:54, 58.58it/s]

2026-09-09 18:26:32,015 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:32,031 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:32,047 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:32,064 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:32,080 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:32,095 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:32,114 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  54%|█████▍    | 11941/22132 [04:46<02:52, 59.17it/s]

2026-09-09 18:26:32,132 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:32,147 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:32,163 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:32,180 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:32,198 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:32,214 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  54%|█████▍    | 11947/22132 [04:46<02:51, 59.34it/s]

2026-09-09 18:26:32,231 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:32,247 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:32,263 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:32,278 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:32,294 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:32,310 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:32,326 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  54%|█████▍    | 11954/22132 [04:46<02:48, 60.29it/s]

2026-09-09 18:26:32,344 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:32,361 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:32,376 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:32,391 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:32,408 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:32,423 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:32,439 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  54%|█████▍    | 11961/22132 [04:46<02:47, 60.87it/s]

2026-09-09 18:26:32,458 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:32,476 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:32,493 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:32,511 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:32,533 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:32,551 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:32,570 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  54%|█████▍    | 11968/22132 [04:46<02:54, 58.39it/s]

2026-09-09 18:26:32,591 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:32,608 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:32,624 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:32,640 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:32,657 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:32,674 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  54%|█████▍    | 11974/22132 [04:46<02:54, 58.21it/s]

2026-09-09 18:26:32,690 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:32,711 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:32,731 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:32,748 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:32,764 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:32,780 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  54%|█████▍    | 11980/22132 [04:46<02:56, 57.66it/s]

2026-09-09 18:26:32,804 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:26:32,822 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:32,840 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:32,858 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:32,875 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:32,893 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  54%|█████▍    | 11986/22132 [04:47<03:00, 56.27it/s]

2026-09-09 18:26:32,913 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:32,930 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:32,946 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:32,965 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:32,988 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:33,009 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  54%|█████▍    | 11992/22132 [04:47<03:04, 54.83it/s]

2026-09-09 18:26:33,029 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:33,053 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:26:33,079 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:26:33,096 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:33,115 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:33,131 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  54%|█████▍    | 11998/22132 [04:47<03:10, 53.09it/s]

2026-09-09 18:26:33,150 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:33,170 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:33,188 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:33,206 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:33,225 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:33,243 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  54%|█████▍    | 12004/22132 [04:47<03:10, 53.25it/s]

2026-09-09 18:26:33,267 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:26:33,289 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:33,306 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:33,329 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:33,347 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:33,367 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  54%|█████▍    | 12010/22132 [04:47<03:16, 51.63it/s]

2026-09-09 18:26:33,387 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:33,404 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:33,421 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:33,436 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:33,453 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:33,468 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  54%|█████▍    | 12016/22132 [04:47<03:08, 53.72it/s]

2026-09-09 18:26:33,485 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:33,502 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:33,519 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:33,535 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:33,552 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:33,568 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:33,585 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  54%|█████▍    | 12023/22132 [04:47<03:01, 55.70it/s]

2026-09-09 18:26:33,604 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:33,621 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:33,638 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:33,655 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:33,671 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:33,688 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  54%|█████▍    | 12029/22132 [04:47<02:59, 56.37it/s]

2026-09-09 18:26:33,705 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:33,721 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:33,737 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:33,753 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:33,770 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:33,788 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:33,807 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  54%|█████▍    | 12036/22132 [04:47<02:56, 57.18it/s]

2026-09-09 18:26:33,826 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:33,844 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:33,863 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:33,881 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:33,899 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:33,915 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  54%|█████▍    | 12042/22132 [04:48<02:57, 56.74it/s]

2026-09-09 18:26:33,966 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.046s]
2026-09-09 18:26:33,985 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:34,003 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:34,022 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:34,041 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:34,058 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  54%|█████▍    | 12048/22132 [04:48<03:16, 51.40it/s]

2026-09-09 18:26:34,075 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:34,091 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:34,107 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:34,123 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:34,140 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:34,156 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:34,173 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  54%|█████▍    | 12055/22132 [04:48<03:05, 54.24it/s]

2026-09-09 18:26:34,192 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:34,217 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:26:34,236 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:34,252 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:34,273 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:34,292 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  54%|█████▍    | 12061/22132 [04:48<03:09, 53.03it/s]

2026-09-09 18:26:34,311 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:34,329 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:34,346 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:34,363 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:34,383 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:34,400 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  55%|█████▍    | 12067/22132 [04:48<03:07, 53.73it/s]

2026-09-09 18:26:34,417 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:34,433 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:34,453 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:34,470 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:34,487 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:34,504 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  55%|█████▍    | 12073/22132 [04:48<03:03, 54.87it/s]

2026-09-09 18:26:34,521 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:34,539 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:34,556 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:34,577 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:34,595 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:34,616 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  55%|█████▍    | 12079/22132 [04:48<03:04, 54.53it/s]

2026-09-09 18:26:34,638 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:34,656 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:34,672 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:34,689 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:34,708 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:34,734 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  55%|█████▍    | 12085/22132 [04:48<03:08, 53.38it/s]

2026-09-09 18:26:34,754 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:34,779 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:26:34,800 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:34,824 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:26:34,845 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:34,871 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  55%|█████▍    | 12091/22132 [04:49<03:20, 50.10it/s]

2026-09-09 18:26:34,912 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.039s]
2026-09-09 18:26:34,941 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:26:34,977 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]
2026-09-09 18:26:35,005 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:26:35,032 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:26:35,061 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]

Indexing Records:  55%|█████▍    | 12097/22132 [04:49<03:55, 42.66it/s]

2026-09-09 18:26:35,086 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:26:35,107 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:35,129 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:35,147 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:35,167 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  55%|█████▍    | 12102/22132 [04:49<03:49, 43.75it/s]

2026-09-09 18:26:35,185 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:35,206 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:35,227 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:35,249 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:35,271 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  55%|█████▍    | 12107/22132 [04:49<03:43, 44.77it/s]

2026-09-09 18:26:35,292 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:35,312 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:35,333 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:35,349 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:35,365 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:35,381 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  55%|█████▍    | 12113/22132 [04:49<03:30, 47.58it/s]

2026-09-09 18:26:35,399 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:35,415 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:35,434 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:35,453 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:35,471 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:35,488 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  55%|█████▍    | 12119/22132 [04:49<03:20, 49.91it/s]

2026-09-09 18:26:35,504 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:35,520 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:35,536 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:35,556 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:35,575 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:35,593 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  55%|█████▍    | 12125/22132 [04:49<03:12, 51.97it/s]

2026-09-09 18:26:35,611 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:35,629 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:35,649 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:35,667 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:35,685 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:35,705 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  55%|█████▍    | 12131/22132 [04:49<03:10, 52.40it/s]

2026-09-09 18:26:35,722 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:35,738 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:35,756 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:35,773 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:35,790 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:35,806 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  55%|█████▍    | 12137/22132 [04:49<03:03, 54.34it/s]

2026-09-09 18:26:35,825 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:35,842 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:35,860 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:35,876 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:35,895 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:35,913 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  55%|█████▍    | 12143/22132 [04:50<03:02, 54.85it/s]

2026-09-09 18:26:35,934 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:35,951 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:35,969 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:35,985 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:36,002 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:36,019 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  55%|█████▍    | 12149/22132 [04:50<03:00, 55.42it/s]

2026-09-09 18:26:36,037 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:36,053 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:36,069 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:36,084 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:36,101 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:36,117 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:36,134 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  55%|█████▍    | 12156/22132 [04:50<02:54, 57.10it/s]

2026-09-09 18:26:36,151 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:36,166 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:36,183 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:36,201 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:36,217 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:36,233 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:36,249 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  55%|█████▍    | 12163/22132 [04:50<02:50, 58.31it/s]

2026-09-09 18:26:36,269 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:36,291 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:36,311 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:36,329 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:36,345 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:36,362 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  55%|█████▍    | 12169/22132 [04:50<02:55, 56.72it/s]

2026-09-09 18:26:36,385 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:36,405 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:36,424 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:36,442 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:36,460 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:36,480 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  55%|█████▌    | 12175/22132 [04:50<03:01, 54.83it/s]

2026-09-09 18:26:36,525 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.040s]
2026-09-09 18:26:36,547 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:36,564 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:36,581 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:36,601 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:36,619 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  55%|█████▌    | 12181/22132 [04:50<03:15, 50.79it/s]

2026-09-09 18:26:36,636 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:36,653 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:36,675 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:36,693 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:36,710 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:36,727 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  55%|█████▌    | 12187/22132 [04:50<03:10, 52.20it/s]

2026-09-09 18:26:36,743 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:36,760 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:36,776 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:36,792 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:36,810 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:36,828 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  55%|█████▌    | 12193/22132 [04:50<03:03, 54.11it/s]

2026-09-09 18:26:36,846 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:36,865 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:36,885 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:36,904 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:36,919 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:36,941 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  55%|█████▌    | 12199/22132 [04:51<03:04, 53.75it/s]

2026-09-09 18:26:36,962 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:36,981 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:36,996 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:37,018 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:37,037 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:37,057 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  55%|█████▌    | 12205/22132 [04:51<03:06, 53.23it/s]

2026-09-09 18:26:37,075 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:37,092 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:37,109 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:37,126 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:37,142 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:37,158 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  55%|█████▌    | 12211/22132 [04:51<03:01, 54.81it/s]

2026-09-09 18:26:37,176 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:37,193 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:37,211 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:37,227 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:37,244 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:37,262 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  55%|█████▌    | 12217/22132 [04:51<02:57, 55.76it/s]

2026-09-09 18:26:37,280 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:37,299 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:37,317 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:37,334 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:37,352 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:37,368 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  55%|█████▌    | 12223/22132 [04:51<02:57, 55.97it/s]

2026-09-09 18:26:37,386 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:37,401 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:37,418 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:37,435 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:37,461 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:26:37,477 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  55%|█████▌    | 12229/22132 [04:51<02:58, 55.58it/s]

2026-09-09 18:26:37,494 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:37,509 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:37,525 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:37,542 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:37,559 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:37,574 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:37,589 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  55%|█████▌    | 12236/22132 [04:51<02:51, 57.77it/s]

2026-09-09 18:26:37,607 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:37,624 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:37,640 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:37,656 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:37,672 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:37,689 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:37,706 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  55%|█████▌    | 12243/22132 [04:51<02:49, 58.40it/s]

2026-09-09 18:26:37,724 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:37,740 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:37,757 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:37,774 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:37,790 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:37,810 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  55%|█████▌    | 12249/22132 [04:51<02:49, 58.31it/s]

2026-09-09 18:26:37,826 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:37,845 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:37,860 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:37,876 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:37,892 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:37,908 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:37,926 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  55%|█████▌    | 12256/22132 [04:52<02:47, 58.96it/s]

2026-09-09 18:26:37,947 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:37,966 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:37,980 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:37,996 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:38,015 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:38,031 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  55%|█████▌    | 12262/22132 [04:52<02:49, 58.28it/s]

2026-09-09 18:26:38,048 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:38,077 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:26:38,136 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.058s]
2026-09-09 18:26:38,153 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:38,173 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:38,191 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  55%|█████▌    | 12268/22132 [04:52<03:15, 50.39it/s]

2026-09-09 18:26:38,208 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:38,226 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:38,242 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:38,261 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:38,305 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.039s]
2026-09-09 18:26:38,326 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  55%|█████▌    | 12274/22132 [04:52<03:23, 48.47it/s]

2026-09-09 18:26:38,348 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:38,373 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:26:38,393 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:38,413 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:38,435 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  55%|█████▌    | 12279/22132 [04:52<03:26, 47.71it/s]

2026-09-09 18:26:38,454 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:38,476 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:38,494 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:38,511 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:38,527 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:38,543 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  56%|█████▌    | 12285/22132 [04:52<03:17, 49.87it/s]

2026-09-09 18:26:38,561 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:38,578 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:38,603 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:26:38,629 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:26:38,653 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:26:38,673 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  56%|█████▌    | 12291/22132 [04:52<03:21, 48.76it/s]

2026-09-09 18:26:38,692 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:38,716 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:26:38,735 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:38,755 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:38,772 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:38,790 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  56%|█████▌    | 12297/22132 [04:52<03:19, 49.41it/s]

2026-09-09 18:26:38,813 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:38,831 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:38,848 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:38,865 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:38,884 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:38,902 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  56%|█████▌    | 12303/22132 [04:53<03:13, 50.68it/s]

2026-09-09 18:26:38,920 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:38,941 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:38,959 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:38,977 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:38,995 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:39,012 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  56%|█████▌    | 12309/22132 [04:53<03:09, 51.72it/s]

2026-09-09 18:26:39,032 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:39,050 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:39,072 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:39,089 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:39,107 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:39,124 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  56%|█████▌    | 12315/22132 [04:53<03:07, 52.31it/s]

2026-09-09 18:26:39,141 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:39,163 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:39,179 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:39,195 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:39,212 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:39,229 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  56%|█████▌    | 12321/22132 [04:53<03:02, 53.68it/s]

2026-09-09 18:26:39,247 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:39,264 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:39,282 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:39,299 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:39,315 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:39,331 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  56%|█████▌    | 12327/22132 [04:53<02:58, 55.04it/s]

2026-09-09 18:26:39,352 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:39,369 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:39,386 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:39,402 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:39,419 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:39,437 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  56%|█████▌    | 12333/22132 [04:53<02:56, 55.59it/s]

2026-09-09 18:26:39,454 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:39,469 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:39,487 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:39,503 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:39,519 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:39,535 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:39,552 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  56%|█████▌    | 12340/22132 [04:53<02:51, 57.16it/s]

2026-09-09 18:26:39,570 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:39,591 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:39,606 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:39,621 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:26:39,637 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:39,653 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  56%|█████▌    | 12346/22132 [04:53<02:49, 57.85it/s]

2026-09-09 18:26:39,669 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:39,687 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:39,703 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:39,722 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:39,739 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:39,755 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  56%|█████▌    | 12352/22132 [04:53<02:48, 58.12it/s]

2026-09-09 18:26:39,777 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:39,794 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:39,811 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:39,827 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:39,844 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:39,864 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  56%|█████▌    | 12358/22132 [04:54<02:50, 57.30it/s]

2026-09-09 18:26:39,882 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:39,898 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:39,915 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:39,935 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:39,951 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:39,972 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  56%|█████▌    | 12364/22132 [04:54<02:52, 56.61it/s]

2026-09-09 18:26:39,994 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:40,030 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]
2026-09-09 18:26:40,056 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:26:40,087 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:26:40,107 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:40,126 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  56%|█████▌    | 12370/22132 [04:54<03:15, 49.90it/s]

2026-09-09 18:26:40,145 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:40,163 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:40,179 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:40,197 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:40,215 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:40,234 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  56%|█████▌    | 12376/22132 [04:54<03:09, 51.53it/s]

2026-09-09 18:26:40,251 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:40,268 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:40,286 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:40,303 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:40,322 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:40,341 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  56%|█████▌    | 12382/22132 [04:54<03:04, 52.83it/s]

2026-09-09 18:26:40,360 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:40,378 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:40,394 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:40,412 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:40,428 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:40,447 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  56%|█████▌    | 12388/22132 [04:54<03:00, 53.92it/s]

2026-09-09 18:26:40,465 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:40,483 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:40,500 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:40,517 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:40,534 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:40,550 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  56%|█████▌    | 12394/22132 [04:54<02:56, 55.08it/s]

2026-09-09 18:26:40,568 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:40,584 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:40,601 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:40,619 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:40,635 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:40,652 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  56%|█████▌    | 12400/22132 [04:54<02:53, 56.19it/s]

2026-09-09 18:26:40,670 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:40,687 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:40,702 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:40,719 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:40,736 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:40,752 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  56%|█████▌    | 12406/22132 [04:54<02:50, 57.21it/s]

2026-09-09 18:26:40,769 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:40,786 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:40,802 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:40,819 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:40,835 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:40,851 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:40,867 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  56%|█████▌    | 12413/22132 [04:55<02:46, 58.40it/s]

2026-09-09 18:26:40,884 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:40,901 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:40,916 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:40,934 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:40,957 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:40,977 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  56%|█████▌    | 12419/22132 [04:55<02:49, 57.30it/s]

2026-09-09 18:26:40,995 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:41,018 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:41,042 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:26:41,059 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:41,075 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:41,095 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  56%|█████▌    | 12425/22132 [04:55<02:55, 55.24it/s]

2026-09-09 18:26:41,112 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:41,129 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:41,148 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:41,165 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:41,183 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:41,197 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]

Indexing Records:  56%|█████▌    | 12431/22132 [04:55<02:52, 56.13it/s]

2026-09-09 18:26:41,219 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:41,235 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:41,252 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:41,274 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:41,290 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:41,306 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  56%|█████▌    | 12437/22132 [04:55<02:53, 55.93it/s]

2026-09-09 18:26:41,324 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:41,340 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:41,356 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:41,371 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:41,388 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:41,403 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:41,420 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  56%|█████▌    | 12444/22132 [04:55<02:48, 57.55it/s]

2026-09-09 18:26:41,437 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:41,454 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:41,469 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:41,484 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:41,500 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:41,518 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:41,533 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  56%|█████▋    | 12451/22132 [04:55<02:44, 58.85it/s]

2026-09-09 18:26:41,552 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:41,567 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:41,584 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:41,601 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:41,617 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:41,633 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  56%|█████▋    | 12457/22132 [04:55<02:43, 59.16it/s]

2026-09-09 18:26:41,650 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:41,667 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:41,682 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:26:41,697 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:41,713 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:41,728 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:41,745 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  56%|█████▋    | 12464/22132 [04:55<02:40, 60.30it/s]

2026-09-09 18:26:41,763 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:41,781 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:41,804 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:41,825 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:41,844 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:41,862 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:41,883 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  56%|█████▋    | 12471/22132 [04:56<02:49, 56.83it/s]

2026-09-09 18:26:41,902 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:41,920 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:41,939 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:41,959 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:41,976 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:41,995 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  56%|█████▋    | 12477/22132 [04:56<02:52, 55.94it/s]

2026-09-09 18:26:42,014 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:42,039 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:26:42,063 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:26:42,082 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:42,100 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:42,119 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  56%|█████▋    | 12483/22132 [04:56<03:00, 53.58it/s]

2026-09-09 18:26:42,141 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:42,163 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:42,184 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:42,207 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:42,228 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:42,246 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  56%|█████▋    | 12489/22132 [04:56<03:07, 51.54it/s]

2026-09-09 18:26:42,264 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:42,284 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:42,303 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:42,326 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:42,343 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:42,361 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  56%|█████▋    | 12495/22132 [04:56<03:05, 51.82it/s]

2026-09-09 18:26:42,384 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:42,405 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:42,425 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:42,443 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:42,460 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:42,476 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  56%|█████▋    | 12501/22132 [04:56<03:05, 51.93it/s]

2026-09-09 18:26:42,495 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:42,512 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:42,530 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:42,545 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:42,561 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:42,579 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  57%|█████▋    | 12507/22132 [04:56<02:59, 53.58it/s]

2026-09-09 18:26:42,596 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:42,616 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:42,632 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:42,648 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:42,665 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:42,682 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  57%|█████▋    | 12513/22132 [04:56<02:55, 54.93it/s]

2026-09-09 18:26:42,699 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:42,716 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:42,732 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:42,748 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:42,764 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:42,790 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  57%|█████▋    | 12519/22132 [04:56<02:54, 55.09it/s]

2026-09-09 18:26:42,810 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:42,826 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:42,842 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:42,861 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:42,875 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:26:42,889 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:26:42,907 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  57%|█████▋    | 12526/22132 [04:57<02:49, 56.52it/s]

2026-09-09 18:26:42,927 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:42,944 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:42,962 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:42,978 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:42,995 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:43,019 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  57%|█████▋    | 12532/22132 [04:57<02:52, 55.72it/s]

2026-09-09 18:26:43,044 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:26:43,062 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:43,081 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:43,097 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:43,114 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:43,130 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  57%|█████▋    | 12538/22132 [04:57<02:53, 55.23it/s]

2026-09-09 18:26:43,147 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:43,163 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:43,179 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:43,198 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:43,218 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:43,236 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  57%|█████▋    | 12544/22132 [04:57<02:52, 55.56it/s]

2026-09-09 18:26:43,253 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:43,269 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:43,286 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:43,303 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:43,321 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:43,338 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  57%|█████▋    | 12550/22132 [04:57<02:49, 56.46it/s]

2026-09-09 18:26:43,355 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:43,372 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:43,389 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:43,408 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:43,427 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:43,447 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  57%|█████▋    | 12556/22132 [04:57<02:50, 56.12it/s]

2026-09-09 18:26:43,468 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:43,486 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:43,503 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:43,520 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:43,537 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:43,553 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  57%|█████▋    | 12562/22132 [04:57<02:50, 56.27it/s]

2026-09-09 18:26:43,571 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:43,589 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:43,605 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:43,622 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:43,638 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:43,654 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  57%|█████▋    | 12568/22132 [04:57<02:47, 57.19it/s]

2026-09-09 18:26:43,674 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:43,693 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:43,709 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:43,725 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:43,742 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:43,759 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  57%|█████▋    | 12574/22132 [04:57<02:47, 57.06it/s]

2026-09-09 18:26:43,778 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:43,798 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:43,815 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:43,831 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:43,847 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:43,864 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  57%|█████▋    | 12580/22132 [04:58<02:47, 57.15it/s]

2026-09-09 18:26:43,881 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:43,898 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:43,915 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:43,932 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:43,950 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:43,968 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  57%|█████▋    | 12586/22132 [04:58<02:46, 57.26it/s]

2026-09-09 18:26:43,985 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:44,002 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:44,018 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:44,036 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:44,055 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:44,074 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  57%|█████▋    | 12592/22132 [04:58<02:47, 57.06it/s]

2026-09-09 18:26:44,096 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:44,113 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:44,129 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:44,147 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:44,163 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:44,183 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  57%|█████▋    | 12598/22132 [04:58<02:48, 56.52it/s]

2026-09-09 18:26:44,200 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:44,217 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:44,233 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:44,249 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:44,265 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:44,282 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:44,299 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  57%|█████▋    | 12605/22132 [04:58<02:45, 57.68it/s]

2026-09-09 18:26:44,317 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:44,335 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:44,352 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:44,368 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:44,385 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:44,401 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  57%|█████▋    | 12611/22132 [04:58<02:44, 57.98it/s]

2026-09-09 18:26:44,419 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:44,436 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:44,456 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:44,478 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:44,495 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:44,512 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  57%|█████▋    | 12617/22132 [04:58<02:47, 56.82it/s]

2026-09-09 18:26:44,532 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:44,549 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:44,566 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:44,584 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:44,601 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:44,617 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  57%|█████▋    | 12623/22132 [04:58<02:47, 56.85it/s]

2026-09-09 18:26:44,634 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:44,649 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:44,665 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:44,689 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:26:44,706 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:44,722 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  57%|█████▋    | 12629/22132 [04:58<02:46, 57.07it/s]

2026-09-09 18:26:44,738 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:44,756 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:44,772 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:44,790 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:44,807 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:44,825 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  57%|█████▋    | 12635/22132 [04:58<02:45, 57.37it/s]

2026-09-09 18:26:44,848 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:44,866 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:44,882 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:44,899 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:44,914 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:44,933 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  57%|█████▋    | 12641/22132 [04:59<02:46, 56.84it/s]

2026-09-09 18:26:44,952 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:44,969 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:44,987 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:45,006 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:45,035 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:26:45,054 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  57%|█████▋    | 12647/22132 [04:59<02:54, 54.47it/s]

2026-09-09 18:26:45,072 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:45,091 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:45,112 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:45,133 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:45,151 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:45,172 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  57%|█████▋    | 12653/22132 [04:59<02:57, 53.35it/s]

2026-09-09 18:26:45,189 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:45,206 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:45,223 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:45,239 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:45,255 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:45,272 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  57%|█████▋    | 12659/22132 [04:59<02:52, 55.07it/s]

2026-09-09 18:26:45,291 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:45,309 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:45,325 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:45,340 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:45,357 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:45,374 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  57%|█████▋    | 12665/22132 [04:59<02:48, 56.26it/s]

2026-09-09 18:26:45,392 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:45,409 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:45,427 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:45,447 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:45,463 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:45,481 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  57%|█████▋    | 12671/22132 [04:59<02:48, 56.06it/s]

2026-09-09 18:26:45,501 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:45,519 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:45,536 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:45,552 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:45,570 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:45,587 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  57%|█████▋    | 12677/22132 [04:59<02:47, 56.37it/s]

2026-09-09 18:26:45,606 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:45,623 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:45,639 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:45,655 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:45,672 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:45,689 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  57%|█████▋    | 12683/22132 [04:59<02:45, 57.09it/s]

2026-09-09 18:26:45,705 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:45,721 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:45,737 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:45,760 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:45,776 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:45,792 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  57%|█████▋    | 12689/22132 [04:59<02:44, 57.39it/s]

2026-09-09 18:26:45,809 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:45,824 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:26:45,840 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:45,856 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:45,873 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:45,890 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:45,907 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  57%|█████▋    | 12696/22132 [05:00<02:41, 58.45it/s]

2026-09-09 18:26:45,927 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:45,945 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:45,962 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:45,978 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:45,994 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:46,011 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  57%|█████▋    | 12702/22132 [05:00<02:41, 58.25it/s]

2026-09-09 18:26:46,028 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:46,045 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:46,064 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:46,082 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:46,099 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:46,115 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  57%|█████▋    | 12708/22132 [05:00<02:42, 58.06it/s]

2026-09-09 18:26:46,133 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:46,148 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:46,164 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:46,180 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:46,195 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:46,212 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:46,228 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  57%|█████▋    | 12715/22132 [05:00<02:38, 59.40it/s]

2026-09-09 18:26:46,244 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:46,262 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:46,279 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:46,296 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:46,311 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:46,327 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:46,343 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  57%|█████▋    | 12722/22132 [05:00<02:37, 59.77it/s]

2026-09-09 18:26:46,359 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:46,375 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:46,390 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:46,405 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:46,421 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:46,436 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:46,454 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  58%|█████▊    | 12729/22132 [05:00<02:34, 60.77it/s]

2026-09-09 18:26:46,471 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:46,487 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:46,503 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:46,518 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:46,535 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:46,553 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:46,569 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  58%|█████▊    | 12736/22132 [05:00<02:34, 60.83it/s]

2026-09-09 18:26:46,588 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:46,607 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:46,624 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:46,646 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:46,666 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:46,688 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:46,708 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  58%|█████▊    | 12743/22132 [05:00<02:44, 57.13it/s]

2026-09-09 18:26:46,728 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:46,744 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:46,760 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:46,776 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:46,792 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:46,809 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  58%|█████▊    | 12749/22132 [05:00<02:42, 57.82it/s]

2026-09-09 18:26:46,825 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:46,840 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:46,855 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:46,872 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:46,889 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:46,907 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:46,925 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  58%|█████▊    | 12756/22132 [05:01<02:40, 58.58it/s]

2026-09-09 18:26:46,941 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:46,957 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:46,974 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:46,992 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:47,008 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:47,026 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  58%|█████▊    | 12762/22132 [05:01<02:39, 58.66it/s]

2026-09-09 18:26:47,043 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:47,060 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:47,076 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:47,092 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:47,111 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:47,129 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  58%|█████▊    | 12768/22132 [05:01<02:39, 58.71it/s]

2026-09-09 18:26:47,147 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:47,166 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:47,182 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:47,197 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:47,214 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:47,230 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  58%|█████▊    | 12774/22132 [05:01<02:39, 58.83it/s]

2026-09-09 18:26:47,248 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:47,264 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:47,280 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:47,296 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:47,312 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:47,327 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:47,342 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  58%|█████▊    | 12781/22132 [05:01<02:35, 59.96it/s]

2026-09-09 18:26:47,359 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:47,376 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:47,394 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:47,410 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:47,427 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:47,444 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  58%|█████▊    | 12787/22132 [05:01<02:36, 59.65it/s]

2026-09-09 18:26:47,462 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:47,478 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:47,495 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:47,513 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:47,529 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:47,548 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  58%|█████▊    | 12793/22132 [05:01<02:38, 59.09it/s]

2026-09-09 18:26:47,567 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:47,583 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:47,600 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:47,616 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:47,633 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:47,649 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  58%|█████▊    | 12799/22132 [05:01<02:37, 59.14it/s]

2026-09-09 18:26:47,668 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:47,684 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:47,701 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:47,716 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:47,731 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:47,747 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:47,763 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  58%|█████▊    | 12806/22132 [05:01<02:35, 59.97it/s]

2026-09-09 18:26:47,780 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:47,795 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:47,812 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:47,829 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:47,844 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:47,860 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:47,876 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  58%|█████▊    | 12813/22132 [05:02<02:34, 60.49it/s]

2026-09-09 18:26:47,893 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:47,909 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:47,925 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:47,942 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:47,961 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:47,977 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:47,993 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  58%|█████▊    | 12820/22132 [05:02<02:34, 60.25it/s]

2026-09-09 18:26:48,010 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:48,027 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:48,044 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:48,061 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:48,078 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:48,095 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:48,113 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  58%|█████▊    | 12827/22132 [05:02<02:35, 59.76it/s]

2026-09-09 18:26:48,129 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:48,145 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:48,162 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:48,178 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:48,195 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:48,211 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:48,226 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  58%|█████▊    | 12834/22132 [05:02<02:34, 60.31it/s]

2026-09-09 18:26:48,245 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:48,261 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:48,277 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:48,294 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:48,313 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:48,329 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:48,345 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  58%|█████▊    | 12841/22132 [05:02<02:35, 59.88it/s]

2026-09-09 18:26:48,362 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:48,378 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:48,396 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:48,413 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:48,429 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:48,445 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  58%|█████▊    | 12847/22132 [05:02<02:35, 59.85it/s]

2026-09-09 18:26:48,462 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:48,478 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:48,494 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:48,516 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:48,536 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:48,560 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  58%|█████▊    | 12853/22132 [05:02<02:41, 57.53it/s]

2026-09-09 18:26:48,591 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:26:48,612 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:48,636 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:26:48,749 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.111s]
2026-09-09 18:26:48,776 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:26:48,805 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]

Indexing Records:  58%|█████▊    | 12859/22132 [05:02<03:43, 41.56it/s]

2026-09-09 18:26:48,830 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:26:48,858 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:26:48,886 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:26:48,923 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]
2026-09-09 18:26:48,948 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  58%|█████▊    | 12864/22132 [05:03<03:53, 39.65it/s]

2026-09-09 18:26:48,982 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:26:49,001 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:49,028 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:26:49,048 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:49,067 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  58%|█████▊    | 12869/22132 [05:03<03:49, 40.28it/s]

2026-09-09 18:26:49,090 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:49,111 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:49,130 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:49,150 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:49,171 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  58%|█████▊    | 12874/22132 [05:03<03:39, 42.17it/s]

2026-09-09 18:26:49,192 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:49,211 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:49,230 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:49,248 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:49,268 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:49,288 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  58%|█████▊    | 12880/22132 [05:03<03:27, 44.66it/s]

2026-09-09 18:26:49,307 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:49,325 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:49,344 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:49,364 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:49,382 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:49,400 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  58%|█████▊    | 12886/22132 [05:03<03:16, 47.11it/s]

2026-09-09 18:26:49,419 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:49,439 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:49,458 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:49,475 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:49,494 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:49,513 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  58%|█████▊    | 12892/22132 [05:03<03:08, 48.92it/s]

2026-09-09 18:26:49,533 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:49,555 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:49,580 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:26:49,599 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:49,618 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:49,637 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  58%|█████▊    | 12898/22132 [05:03<03:09, 48.71it/s]

2026-09-09 18:26:49,660 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:49,685 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:26:49,703 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:49,725 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:49,744 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  58%|█████▊    | 12903/22132 [05:03<03:11, 48.15it/s]

2026-09-09 18:26:49,765 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:49,781 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:49,800 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:49,818 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:49,875 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.055s]

Indexing Records:  58%|█████▊    | 12908/22132 [05:04<03:25, 44.92it/s]

2026-09-09 18:26:49,901 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:26:49,918 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:49,941 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:49,963 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:49,981 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  58%|█████▊    | 12913/22132 [05:04<03:22, 45.52it/s]

2026-09-09 18:26:50,003 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:50,026 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:26:50,045 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:50,071 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:26:50,088 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  58%|█████▊    | 12918/22132 [05:04<03:20, 45.86it/s]

2026-09-09 18:26:50,109 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:50,128 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:50,146 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:50,164 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:50,190 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]

Indexing Records:  58%|█████▊    | 12923/22132 [05:04<03:17, 46.68it/s]

2026-09-09 18:26:50,210 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:50,227 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:50,246 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:50,265 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:50,286 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:50,307 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  58%|█████▊    | 12929/22132 [05:04<03:10, 48.19it/s]

2026-09-09 18:26:50,327 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:50,347 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:50,368 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:50,386 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:50,403 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:50,420 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  58%|█████▊    | 12935/22132 [05:04<03:05, 49.68it/s]

2026-09-09 18:26:50,438 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:50,455 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:50,471 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:50,488 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:50,505 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:50,521 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  58%|█████▊    | 12941/22132 [05:04<02:55, 52.36it/s]

2026-09-09 18:26:50,539 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:50,554 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:50,572 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:50,591 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:50,610 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:50,627 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  58%|█████▊    | 12947/22132 [05:04<02:51, 53.57it/s]

2026-09-09 18:26:50,645 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:50,661 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:50,679 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:50,695 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:50,711 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:50,726 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:50,741 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]

Indexing Records:  59%|█████▊    | 12954/22132 [05:04<02:43, 56.06it/s]

2026-09-09 18:26:50,758 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:50,775 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:50,793 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:50,811 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:50,827 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:50,845 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  59%|█████▊    | 12960/22132 [05:04<02:42, 56.53it/s]

2026-09-09 18:26:50,874 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:26:50,892 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:50,910 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:50,928 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:50,947 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:50,967 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  59%|█████▊    | 12966/22132 [05:05<02:49, 54.11it/s]

2026-09-09 18:26:50,986 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:51,002 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:51,027 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:26:51,046 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:51,062 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:51,080 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  59%|█████▊    | 12972/22132 [05:05<02:50, 53.83it/s]

2026-09-09 18:26:51,097 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:51,114 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:51,133 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:51,151 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:51,169 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:51,188 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  59%|█████▊    | 12978/22132 [05:05<02:48, 54.32it/s]

2026-09-09 18:26:51,210 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:51,234 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:26:51,253 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:51,282 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:26:51,305 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:51,331 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]

Indexing Records:  59%|█████▊    | 12984/22132 [05:05<03:03, 49.88it/s]

2026-09-09 18:26:51,354 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:51,380 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:26:51,402 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:51,419 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:51,436 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:51,455 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  59%|█████▊    | 12990/22132 [05:05<03:04, 49.45it/s]

2026-09-09 18:26:51,475 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:51,493 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:51,508 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:51,524 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:51,542 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:51,559 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  59%|█████▊    | 12996/22132 [05:05<02:56, 51.70it/s]

2026-09-09 18:26:51,578 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:51,595 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:51,614 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:51,630 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:51,650 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:51,666 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  59%|█████▊    | 13002/22132 [05:05<02:52, 52.89it/s]

2026-09-09 18:26:51,685 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:51,701 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:51,717 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:51,732 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:51,748 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:51,765 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:51,780 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  59%|█████▉    | 13009/22132 [05:05<02:44, 55.44it/s]

2026-09-09 18:26:51,798 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:51,815 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:51,830 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:51,846 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:51,863 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:51,879 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:51,897 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  59%|█████▉    | 13016/22132 [05:06<02:40, 56.88it/s]

2026-09-09 18:26:51,913 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:51,928 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:51,944 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:51,960 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:51,976 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:51,993 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:52,010 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  59%|█████▉    | 13023/22132 [05:06<02:36, 58.35it/s]

2026-09-09 18:26:52,029 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:52,050 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:52,067 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:52,084 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:52,103 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:52,126 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  59%|█████▉    | 13029/22132 [05:06<02:41, 56.24it/s]

2026-09-09 18:26:52,147 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:52,165 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:52,185 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:52,201 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:52,217 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:52,234 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  59%|█████▉    | 13035/22132 [05:06<02:41, 56.18it/s]

2026-09-09 18:26:52,251 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:52,267 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:52,285 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:52,301 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:52,319 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:52,340 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  59%|█████▉    | 13041/22132 [05:06<02:41, 56.28it/s]

2026-09-09 18:26:52,357 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:52,374 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:52,390 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:52,407 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:52,424 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:52,442 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  59%|█████▉    | 13047/22132 [05:06<02:39, 56.89it/s]

2026-09-09 18:26:52,460 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:52,476 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:52,493 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:52,509 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:52,526 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:52,544 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  59%|█████▉    | 13053/22132 [05:06<02:38, 57.43it/s]

2026-09-09 18:26:52,563 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:52,582 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:52,601 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:52,622 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:52,641 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:52,659 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  59%|█████▉    | 13059/22132 [05:06<02:42, 55.82it/s]

2026-09-09 18:26:52,677 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:52,693 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:52,710 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:52,729 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:52,747 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:52,764 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  59%|█████▉    | 13065/22132 [05:06<02:41, 56.15it/s]

2026-09-09 18:26:52,782 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:52,800 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:52,818 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:52,838 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:52,856 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:52,873 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  59%|█████▉    | 13071/22132 [05:07<02:42, 55.90it/s]

2026-09-09 18:26:52,891 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:52,914 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:52,939 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:26:52,957 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:52,984 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:26:53,005 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  59%|█████▉    | 13077/22132 [05:07<02:53, 52.25it/s]

2026-09-09 18:26:53,023 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:53,043 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:53,061 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:53,079 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:53,096 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:53,122 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  59%|█████▉    | 13083/22132 [05:07<02:53, 52.09it/s]

2026-09-09 18:26:53,142 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:53,160 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:53,182 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:53,200 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:53,217 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:53,236 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  59%|█████▉    | 13089/22132 [05:07<02:53, 52.15it/s]

2026-09-09 18:26:53,257 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:53,281 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:26:53,302 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:53,320 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:53,341 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:53,360 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  59%|█████▉    | 13095/22132 [05:07<02:57, 51.02it/s]

2026-09-09 18:26:53,379 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:53,399 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:53,418 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:53,434 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:53,451 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:53,473 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  59%|█████▉    | 13101/22132 [05:07<02:54, 51.66it/s]

2026-09-09 18:26:53,495 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:53,514 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:53,532 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:53,551 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:53,568 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:53,586 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  59%|█████▉    | 13107/22132 [05:07<02:53, 52.08it/s]

2026-09-09 18:26:53,603 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:53,620 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:53,637 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:53,653 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:53,671 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:53,693 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  59%|█████▉    | 13113/22132 [05:07<02:49, 53.18it/s]

2026-09-09 18:26:53,711 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:53,727 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:53,744 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:53,761 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:53,778 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:53,794 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  59%|█████▉    | 13119/22132 [05:07<02:44, 54.91it/s]

2026-09-09 18:26:53,810 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:53,825 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:53,841 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:53,858 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:53,888 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:26:53,904 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  59%|█████▉    | 13125/22132 [05:08<02:44, 54.71it/s]

2026-09-09 18:26:53,921 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:53,937 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:53,953 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:53,971 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:53,986 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:54,003 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:54,019 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  59%|█████▉    | 13132/22132 [05:08<02:38, 56.66it/s]

2026-09-09 18:26:54,036 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:54,054 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:54,071 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:54,086 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:54,103 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:54,120 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  59%|█████▉    | 13138/22132 [05:08<02:36, 57.41it/s]

2026-09-09 18:26:54,138 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:54,153 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:26:54,170 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:54,186 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:54,201 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:54,219 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:54,234 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  59%|█████▉    | 13145/22132 [05:08<02:33, 58.64it/s]

2026-09-09 18:26:54,250 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:54,268 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:54,283 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:54,299 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:54,315 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:54,331 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:54,348 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  59%|█████▉    | 13152/22132 [05:08<02:30, 59.56it/s]

2026-09-09 18:26:54,366 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:54,382 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:54,398 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:54,414 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:54,431 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:54,448 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  59%|█████▉    | 13158/22132 [05:08<02:30, 59.64it/s]

2026-09-09 18:26:54,464 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:54,479 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:54,495 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:54,513 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:54,531 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:54,549 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  59%|█████▉    | 13164/22132 [05:08<02:30, 59.65it/s]

2026-09-09 18:26:54,567 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:54,585 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:54,602 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:54,618 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:54,636 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:54,652 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  60%|█████▉    | 13170/22132 [05:08<02:31, 59.25it/s]

2026-09-09 18:26:54,670 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:54,687 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:54,704 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:54,719 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:54,736 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:54,752 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  60%|█████▉    | 13176/22132 [05:08<02:30, 59.37it/s]

2026-09-09 18:26:54,770 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:54,788 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:54,806 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:54,826 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:54,842 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:54,860 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  60%|█████▉    | 13182/22132 [05:09<02:33, 58.19it/s]

2026-09-09 18:26:54,880 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:54,902 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:54,918 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:54,942 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:26:54,959 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:54,977 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  60%|█████▉    | 13188/22132 [05:09<02:39, 56.02it/s]

2026-09-09 18:26:54,994 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:55,013 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:55,032 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:55,051 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:55,067 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:55,085 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  60%|█████▉    | 13194/22132 [05:09<02:39, 55.89it/s]

2026-09-09 18:26:55,101 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:55,116 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:55,132 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:55,148 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:55,165 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:55,183 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:55,200 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  60%|█████▉    | 13201/22132 [05:09<02:35, 57.43it/s]

2026-09-09 18:26:55,216 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:55,233 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:55,251 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:55,266 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:55,283 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:55,299 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:55,317 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  60%|█████▉    | 13208/22132 [05:09<02:33, 58.18it/s]

2026-09-09 18:26:55,337 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:55,354 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:55,371 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:55,387 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:55,404 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:55,424 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  60%|█████▉    | 13214/22132 [05:09<02:34, 57.56it/s]

2026-09-09 18:26:55,442 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:55,459 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:55,475 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:55,491 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:55,506 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:26:55,521 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:55,538 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  60%|█████▉    | 13221/22132 [05:09<02:31, 58.71it/s]

2026-09-09 18:26:55,557 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:55,574 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:55,590 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:55,607 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:55,623 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:55,639 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  60%|█████▉    | 13227/22132 [05:09<02:31, 58.85it/s]

2026-09-09 18:26:55,657 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:55,676 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:55,693 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:55,710 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:55,732 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:55,750 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  60%|█████▉    | 13233/22132 [05:09<02:34, 57.48it/s]

2026-09-09 18:26:55,766 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:55,782 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:55,798 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:55,813 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:55,828 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:55,844 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:55,859 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  60%|█████▉    | 13240/22132 [05:09<02:29, 59.55it/s]

2026-09-09 18:26:55,876 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:55,892 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:55,909 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:55,924 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:26:55,938 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:26:55,953 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:55,969 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  60%|█████▉    | 13247/22132 [05:10<02:26, 60.78it/s]

2026-09-09 18:26:55,985 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:56,002 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:56,019 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:56,036 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:56,053 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:56,073 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:56,090 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  60%|█████▉    | 13254/22132 [05:10<02:28, 59.70it/s]

2026-09-09 18:26:56,107 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:56,123 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:56,143 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:56,160 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:56,175 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:56,191 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  60%|█████▉    | 13260/22132 [05:10<02:28, 59.67it/s]

2026-09-09 18:26:56,208 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:56,226 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:56,242 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:56,257 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:56,273 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:56,288 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:56,306 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  60%|█████▉    | 13267/22132 [05:10<02:27, 60.10it/s]

2026-09-09 18:26:56,324 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:56,342 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:56,360 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:56,376 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:56,394 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:56,411 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:56,426 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  60%|█████▉    | 13274/22132 [05:10<02:29, 59.45it/s]

2026-09-09 18:26:56,443 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:56,459 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:56,474 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:56,491 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:56,509 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:56,525 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:56,541 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  60%|██████    | 13281/22132 [05:10<02:27, 59.88it/s]

2026-09-09 18:26:56,559 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:56,576 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:56,592 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:56,608 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:56,625 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:56,641 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:56,658 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  60%|██████    | 13288/22132 [05:10<02:27, 59.79it/s]

2026-09-09 18:26:56,675 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:56,694 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:56,709 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:56,726 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:56,742 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:56,759 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  60%|██████    | 13294/22132 [05:10<02:27, 59.77it/s]

2026-09-09 18:26:56,778 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:56,795 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:56,811 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:56,828 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:56,844 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:56,861 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  60%|██████    | 13300/22132 [05:11<02:28, 59.56it/s]

2026-09-09 18:26:56,879 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:56,895 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:56,912 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:56,927 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:56,944 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:56,960 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:56,977 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  60%|██████    | 13307/22132 [05:11<02:27, 59.80it/s]

2026-09-09 18:26:56,994 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:57,011 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:57,030 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:57,048 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:57,070 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:57,087 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  60%|██████    | 13313/22132 [05:11<02:31, 58.16it/s]

2026-09-09 18:26:57,107 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:57,122 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:57,138 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:57,251 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.111s]
2026-09-09 18:26:57,269 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:57,285 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  60%|██████    | 13319/22132 [05:11<03:11, 46.11it/s]

2026-09-09 18:26:57,300 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:26:57,315 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:26:57,330 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:57,345 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:57,361 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:57,376 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:57,390 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]

Indexing Records:  60%|██████    | 13326/22132 [05:11<02:51, 51.21it/s]

2026-09-09 18:26:57,404 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]
2026-09-09 18:26:57,420 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:57,433 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]
2026-09-09 18:26:57,448 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:57,463 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:26:57,477 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:26:57,492 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]

Indexing Records:  60%|██████    | 13333/22132 [05:11<02:38, 55.66it/s]

2026-09-09 18:26:57,509 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:57,523 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:26:57,536 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]
2026-09-09 18:26:57,550 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]
2026-09-09 18:26:57,565 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:57,580 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:26:57,596 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  60%|██████    | 13340/22132 [05:11<02:29, 58.87it/s]

2026-09-09 18:26:57,612 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:57,627 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:57,646 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:57,661 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:26:57,675 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:26:57,689 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:26:57,703 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]

Indexing Records:  60%|██████    | 13347/22132 [05:11<02:24, 60.71it/s]

2026-09-09 18:26:57,719 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:57,733 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]
2026-09-09 18:26:57,746 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]
2026-09-09 18:26:57,761 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:57,778 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:57,792 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:26:57,805 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]

Indexing Records:  60%|██████    | 13354/22132 [05:11<02:19, 62.82it/s]

2026-09-09 18:26:57,821 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:57,835 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]
2026-09-09 18:26:57,852 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:57,870 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:57,884 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:26:57,898 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]
2026-09-09 18:26:57,912 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]

Indexing Records:  60%|██████    | 13361/22132 [05:12<02:17, 63.60it/s]

2026-09-09 18:26:57,930 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:57,945 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:57,959 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]
2026-09-09 18:26:57,974 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:26:57,989 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:26:58,003 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:26:58,019 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  60%|██████    | 13368/22132 [05:12<02:16, 64.12it/s]

2026-09-09 18:26:58,037 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:58,053 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:58,068 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:58,083 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:26:58,099 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:58,115 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:58,128 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]

Indexing Records:  60%|██████    | 13375/22132 [05:12<02:16, 64.14it/s]

2026-09-09 18:26:58,144 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:58,159 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:26:58,173 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]
2026-09-09 18:26:58,187 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:26:58,202 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:26:58,216 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:26:58,232 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]

Indexing Records:  60%|██████    | 13382/22132 [05:12<02:14, 65.19it/s]

2026-09-09 18:26:58,250 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:58,267 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:58,286 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:58,302 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:58,318 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:26:58,334 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:58,351 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  60%|██████    | 13389/22132 [05:12<02:18, 63.13it/s]

2026-09-09 18:26:58,368 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:58,388 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:58,404 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:58,423 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:58,440 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:58,458 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:58,484 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]

Indexing Records:  61%|██████    | 13396/22132 [05:12<02:26, 59.47it/s]

2026-09-09 18:26:58,502 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:58,520 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:58,542 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:58,562 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:58,581 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:58,602 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:58,649 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.046s]

Indexing Records:  61%|██████    | 13403/22132 [05:12<02:44, 53.05it/s]

2026-09-09 18:26:58,672 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:58,692 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:58,713 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:58,734 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:58,754 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:58,774 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  61%|██████    | 13409/22132 [05:12<02:48, 51.68it/s]

2026-09-09 18:26:58,795 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:58,814 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:58,833 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:58,851 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:58,871 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:58,895 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  61%|██████    | 13415/22132 [05:13<02:50, 51.02it/s]

2026-09-09 18:26:58,914 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:58,933 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:58,953 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:58,977 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:26:59,007 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:26:59,027 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  61%|██████    | 13421/22132 [05:13<02:56, 49.28it/s]

2026-09-09 18:26:59,048 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:59,068 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:59,087 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:59,107 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:59,132 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  61%|██████    | 13426/22132 [05:13<02:58, 48.86it/s]

2026-09-09 18:26:59,154 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:59,175 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:59,194 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:59,214 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:59,234 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  61%|██████    | 13431/22132 [05:13<02:57, 48.96it/s]

2026-09-09 18:26:59,283 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.047s]
2026-09-09 18:26:59,306 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:59,325 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:59,345 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:59,364 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  61%|██████    | 13436/22132 [05:13<03:10, 45.57it/s]

2026-09-09 18:26:59,384 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:59,404 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:59,423 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:59,442 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:59,468 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  61%|██████    | 13441/22132 [05:13<03:08, 46.18it/s]

2026-09-09 18:26:59,488 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:59,509 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:59,530 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:59,549 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:59,571 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  61%|██████    | 13446/22132 [05:13<03:05, 46.87it/s]

2026-09-09 18:26:59,591 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:59,611 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:59,631 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:59,650 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:59,670 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:59,689 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  61%|██████    | 13452/22132 [05:13<03:00, 48.08it/s]

2026-09-09 18:26:59,709 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:59,731 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:26:59,750 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:26:59,770 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:59,792 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  61%|██████    | 13457/22132 [05:13<03:00, 48.15it/s]

2026-09-09 18:26:59,815 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:26:59,836 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:59,855 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:26:59,878 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:26:59,899 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  61%|██████    | 13462/22132 [05:14<03:01, 47.78it/s]

2026-09-09 18:26:59,921 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:26:59,937 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:59,954 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:26:59,971 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:26:59,991 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:00,033 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.040s]

Indexing Records:  61%|██████    | 13468/22132 [05:14<03:05, 46.83it/s]

2026-09-09 18:27:00,091 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.055s]
2026-09-09 18:27:00,170 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.077s]
2026-09-09 18:27:00,247 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.075s]
2026-09-09 18:27:00,294 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.045s]
2026-09-09 18:27:00,316 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  61%|██████    | 13473/22132 [05:14<04:30, 31.95it/s]

2026-09-09 18:27:00,333 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:00,348 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:00,368 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:00,390 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:00,410 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:00,426 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  61%|██████    | 13479/22132 [05:14<03:54, 36.90it/s]

2026-09-09 18:27:00,447 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:00,465 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:00,481 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:00,497 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:00,516 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:00,532 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  61%|██████    | 13485/22132 [05:14<03:28, 41.51it/s]

2026-09-09 18:27:00,550 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:00,567 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:00,584 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:00,600 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:00,621 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:00,636 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  61%|██████    | 13491/22132 [05:14<03:09, 45.52it/s]

2026-09-09 18:27:00,653 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:00,670 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:00,687 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:00,703 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:00,720 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:00,736 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  61%|██████    | 13497/22132 [05:14<02:55, 49.16it/s]

2026-09-09 18:27:00,753 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:00,771 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:00,787 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:00,805 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:00,820 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:27:00,837 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  61%|██████    | 13503/22132 [05:14<02:46, 51.91it/s]

2026-09-09 18:27:00,854 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:00,871 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:00,887 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:00,901 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:00,918 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:00,933 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:00,949 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  61%|██████    | 13510/22132 [05:15<02:36, 55.09it/s]

2026-09-09 18:27:00,965 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:00,981 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:00,996 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:01,013 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:01,029 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:01,051 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  61%|██████    | 13516/22132 [05:15<02:33, 56.05it/s]

2026-09-09 18:27:01,072 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:01,097 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:27:01,139 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.041s]
2026-09-09 18:27:01,196 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.056s]
2026-09-09 18:27:01,247 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.049s]
2026-09-09 18:27:01,270 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  61%|██████    | 13522/22132 [05:15<03:21, 42.82it/s]

2026-09-09 18:27:01,308 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.036s]
2026-09-09 18:27:01,370 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.060s]
2026-09-09 18:27:01,431 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.059s]
2026-09-09 18:27:01,482 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.050s]
2026-09-09 18:27:01,550 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.066s]

Indexing Records:  61%|██████    | 13527/22132 [05:15<04:33, 31.44it/s]

2026-09-09 18:27:01,753 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.201s]
2026-09-09 18:27:01,887 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.133s]
2026-09-09 18:27:02,107 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.217s]
2026-09-09 18:27:02,188 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.080s]

Indexing Records:  61%|██████    | 13531/22132 [05:16<08:45, 16.38it/s]

2026-09-09 18:27:02,278 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.088s]
2026-09-09 18:27:02,381 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.101s]
2026-09-09 18:27:02,459 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.076s]

Indexing Records:  61%|██████    | 13534/22132 [05:16<09:34, 14.98it/s]

2026-09-09 18:27:02,541 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.080s]
2026-09-09 18:27:02,605 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.062s]
2026-09-09 18:27:02,692 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.086s]

Indexing Records:  61%|██████    | 13537/22132 [05:16<09:55, 14.44it/s]

2026-09-09 18:27:02,935 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.240s]
2026-09-09 18:27:03,117 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.180s]
2026-09-09 18:27:03,150 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]

Indexing Records:  61%|██████    | 13540/22132 [05:17<12:45, 11.22it/s]

2026-09-09 18:27:03,188 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.036s]
2026-09-09 18:27:03,220 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:27:03,246 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:27:03,288 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.040s]

Indexing Records:  61%|██████    | 13544/22132 [05:17<10:18, 13.88it/s]

2026-09-09 18:27:03,315 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:27:03,365 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.048s]
2026-09-09 18:27:03,414 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.047s]

Indexing Records:  61%|██████    | 13547/22132 [05:17<09:13, 15.51it/s]

2026-09-09 18:27:03,509 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.092s]
2026-09-09 18:27:03,577 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.067s]
2026-09-09 18:27:03,609 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]

Indexing Records:  61%|██████    | 13550/22132 [05:17<09:14, 15.47it/s]

2026-09-09 18:27:03,655 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.043s]
2026-09-09 18:27:03,696 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.040s]
2026-09-09 18:27:03,741 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.043s]

Indexing Records:  61%|██████    | 13553/22132 [05:17<08:25, 16.96it/s]

2026-09-09 18:27:03,799 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.056s]
2026-09-09 18:27:03,851 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.050s]
2026-09-09 18:27:03,886 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]

Indexing Records:  61%|██████▏   | 13556/22132 [05:18<08:00, 17.83it/s]

2026-09-09 18:27:03,924 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]
2026-09-09 18:27:04,006 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.080s]
2026-09-09 18:27:04,026 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  61%|██████▏   | 13559/22132 [05:18<07:36, 18.77it/s]

2026-09-09 18:27:04,075 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.047s]
2026-09-09 18:27:04,132 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.056s]
2026-09-09 18:27:04,152 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  61%|██████▏   | 13562/22132 [05:18<07:09, 19.97it/s]

2026-09-09 18:27:04,184 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:27:04,224 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.037s]
2026-09-09 18:27:04,245 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:04,266 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  61%|██████▏   | 13566/22132 [05:18<06:03, 23.59it/s]

2026-09-09 18:27:04,289 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:04,311 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:04,337 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:27:04,361 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:27:04,388 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]

Indexing Records:  61%|██████▏   | 13571/22132 [05:18<05:02, 28.25it/s]

2026-09-09 18:27:04,432 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.042s]
2026-09-09 18:27:04,459 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:27:04,483 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:27:04,505 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  61%|██████▏   | 13575/22132 [05:18<04:46, 29.89it/s]

2026-09-09 18:27:04,525 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:04,552 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:27:04,571 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:04,594 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:27:04,628 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]

Indexing Records:  61%|██████▏   | 13580/22132 [05:18<04:19, 32.99it/s]

2026-09-09 18:27:04,677 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.047s]
2026-09-09 18:27:04,702 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:27:04,751 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.048s]
2026-09-09 18:27:04,777 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]

Indexing Records:  61%|██████▏   | 13584/22132 [05:18<04:36, 30.92it/s]

2026-09-09 18:27:04,801 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:27:04,824 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:04,843 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:04,869 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:27:04,888 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  61%|██████▏   | 13589/22132 [05:19<04:06, 34.60it/s]

2026-09-09 18:27:04,913 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:27:04,938 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:27:04,964 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:27:04,986 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:05,017 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]

Indexing Records:  61%|██████▏   | 13594/22132 [05:19<03:58, 35.87it/s]

2026-09-09 18:27:05,052 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:27:05,073 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:05,118 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.044s]
2026-09-09 18:27:05,169 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.049s]

Indexing Records:  61%|██████▏   | 13598/22132 [05:19<04:21, 32.68it/s]

2026-09-09 18:27:05,196 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:27:05,227 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:27:05,254 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:27:05,277 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  61%|██████▏   | 13602/22132 [05:19<04:12, 33.72it/s]

2026-09-09 18:27:05,299 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:05,325 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:27:05,344 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:05,364 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:05,384 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  61%|██████▏   | 13607/22132 [05:19<03:49, 37.22it/s]

2026-09-09 18:27:05,404 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:05,424 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:05,451 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:27:05,470 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:05,490 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  62%|██████▏   | 13612/22132 [05:19<03:33, 39.88it/s]

2026-09-09 18:27:05,512 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:05,536 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:27:05,565 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:27:05,604 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.037s]
2026-09-09 18:27:05,635 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]

Indexing Records:  62%|██████▏   | 13617/22132 [05:19<03:43, 38.08it/s]

2026-09-09 18:27:05,666 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:27:05,717 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.050s]
2026-09-09 18:27:05,747 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:27:05,775 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]

Indexing Records:  62%|██████▏   | 13621/22132 [05:19<04:03, 34.94it/s]

2026-09-09 18:27:05,824 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.047s]
2026-09-09 18:27:05,858 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:27:05,884 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:27:05,908 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  62%|██████▏   | 13625/22132 [05:20<04:14, 33.44it/s]

2026-09-09 18:27:05,932 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:05,954 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:05,977 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:06,001 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:27:06,023 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  62%|██████▏   | 13630/22132 [05:20<03:54, 36.21it/s]

2026-09-09 18:27:06,048 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:27:06,069 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:06,090 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:06,123 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:27:06,142 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  62%|██████▏   | 13635/22132 [05:20<03:44, 37.90it/s]

2026-09-09 18:27:06,175 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:27:06,209 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:27:06,231 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:06,258 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]

Indexing Records:  62%|██████▏   | 13639/22132 [05:20<03:49, 36.97it/s]

2026-09-09 18:27:06,285 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:27:06,313 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:27:06,332 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:06,352 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:06,375 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  62%|██████▏   | 13644/22132 [05:20<03:39, 38.63it/s]

2026-09-09 18:27:06,396 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:06,419 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:06,438 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:06,459 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:06,482 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  62%|██████▏   | 13649/22132 [05:20<03:27, 40.86it/s]

2026-09-09 18:27:06,504 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:06,529 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:27:06,548 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:06,567 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:06,588 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  62%|██████▏   | 13654/22132 [05:20<03:18, 42.62it/s]

2026-09-09 18:27:06,608 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:06,628 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:06,649 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:06,675 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:27:06,694 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  62%|██████▏   | 13659/22132 [05:20<03:13, 43.88it/s]

2026-09-09 18:27:06,719 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:27:06,745 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:27:06,770 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:27:06,792 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:06,818 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]

Indexing Records:  62%|██████▏   | 13664/22132 [05:20<03:17, 42.81it/s]

2026-09-09 18:27:06,838 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:06,864 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:27:06,887 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:27:06,905 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:06,929 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  62%|██████▏   | 13669/22132 [05:21<03:14, 43.43it/s]

2026-09-09 18:27:06,957 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:27:06,983 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:27:07,004 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:07,029 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:27:07,052 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  62%|██████▏   | 13674/22132 [05:21<03:18, 42.52it/s]

2026-09-09 18:27:07,073 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:07,092 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:07,118 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:27:07,144 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:27:07,164 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  62%|██████▏   | 13679/22132 [05:21<03:15, 43.16it/s]

2026-09-09 18:27:07,188 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:07,225 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]
2026-09-09 18:27:07,248 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:27:07,269 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:07,291 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  62%|██████▏   | 13684/22132 [05:21<03:21, 41.91it/s]

2026-09-09 18:27:07,317 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:27:07,337 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:07,357 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:07,377 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:07,397 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  62%|██████▏   | 13689/22132 [05:21<03:14, 43.41it/s]

2026-09-09 18:27:07,417 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:07,436 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:07,458 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:07,478 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:07,500 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  62%|██████▏   | 13694/22132 [05:21<03:08, 44.84it/s]

2026-09-09 18:27:07,528 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:27:07,556 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:27:07,576 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:07,595 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:07,619 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  62%|██████▏   | 13699/22132 [05:21<03:11, 43.98it/s]

2026-09-09 18:27:07,639 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:07,660 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:07,678 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:07,699 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:07,717 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:07,741 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  62%|██████▏   | 13705/22132 [05:21<03:04, 45.58it/s]

2026-09-09 18:27:07,768 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:27:07,793 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:27:07,812 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:07,830 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:07,855 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  62%|██████▏   | 13710/22132 [05:21<03:06, 45.09it/s]

2026-09-09 18:27:07,877 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:07,896 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:07,912 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:07,933 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:07,950 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:07,965 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  62%|██████▏   | 13716/22132 [05:22<02:56, 47.80it/s]

2026-09-09 18:27:07,982 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:07,999 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:08,021 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:08,040 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:08,056 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:08,072 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  62%|██████▏   | 13722/22132 [05:22<02:47, 50.19it/s]

2026-09-09 18:27:08,090 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:08,110 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:08,129 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:08,150 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:08,170 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:08,188 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  62%|██████▏   | 13728/22132 [05:22<02:45, 50.63it/s]

2026-09-09 18:27:08,210 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:08,229 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:08,248 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:08,267 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:08,286 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:08,302 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  62%|██████▏   | 13734/22132 [05:22<02:43, 51.22it/s]

2026-09-09 18:27:08,321 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:08,339 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:08,357 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:08,375 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:08,395 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:08,411 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  62%|██████▏   | 13740/22132 [05:22<02:40, 52.35it/s]

2026-09-09 18:27:08,430 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:08,449 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:08,467 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:08,484 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:08,505 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:08,523 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  62%|██████▏   | 13746/22132 [05:22<02:38, 52.78it/s]

2026-09-09 18:27:08,540 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:08,556 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:08,573 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:08,591 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:08,608 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:08,625 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  62%|██████▏   | 13752/22132 [05:22<02:33, 54.46it/s]

2026-09-09 18:27:08,644 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:08,661 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:08,678 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:08,694 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:08,711 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:08,732 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  62%|██████▏   | 13758/22132 [05:22<02:32, 55.00it/s]

2026-09-09 18:27:08,756 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:27:08,777 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:08,801 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:27:08,820 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:08,839 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:08,856 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  62%|██████▏   | 13764/22132 [05:22<02:38, 52.77it/s]

2026-09-09 18:27:08,877 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:08,894 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:08,910 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:08,926 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:08,943 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:08,960 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  62%|██████▏   | 13770/22132 [05:23<02:34, 54.15it/s]

2026-09-09 18:27:08,976 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:08,995 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:09,015 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:09,034 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:09,055 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:09,076 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  62%|██████▏   | 13776/22132 [05:23<02:36, 53.41it/s]

2026-09-09 18:27:09,094 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:09,113 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:09,130 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:09,148 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:09,166 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:09,184 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  62%|██████▏   | 13782/22132 [05:23<02:34, 54.00it/s]

2026-09-09 18:27:09,206 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:09,231 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:27:09,253 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:09,272 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:09,295 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:09,324 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]

Indexing Records:  62%|██████▏   | 13788/22132 [05:23<02:46, 50.04it/s]

2026-09-09 18:27:09,359 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:27:09,378 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:09,397 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:09,415 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:09,438 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:09,455 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  62%|██████▏   | 13794/22132 [05:23<02:51, 48.74it/s]

2026-09-09 18:27:09,476 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:09,492 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:09,512 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:09,531 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:09,549 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:09,576 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]

Indexing Records:  62%|██████▏   | 13800/22132 [05:23<02:50, 48.94it/s]

2026-09-09 18:27:09,596 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:09,617 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:09,633 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:09,652 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:09,670 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:09,692 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  62%|██████▏   | 13806/22132 [05:23<02:47, 49.76it/s]

2026-09-09 18:27:09,715 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:09,738 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:09,764 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:27:09,786 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:09,805 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:09,827 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  62%|██████▏   | 13812/22132 [05:23<02:53, 48.07it/s]

2026-09-09 18:27:09,846 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:09,866 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:09,888 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:09,911 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:09,938 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]

Indexing Records:  62%|██████▏   | 13817/22132 [05:24<02:56, 47.20it/s]

2026-09-09 18:27:09,958 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:09,980 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:09,998 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:10,018 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:10,039 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  62%|██████▏   | 13822/22132 [05:24<02:53, 47.89it/s]

2026-09-09 18:27:10,061 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:10,081 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:10,100 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:10,126 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:27:10,154 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]

Indexing Records:  62%|██████▏   | 13827/22132 [05:24<02:58, 46.50it/s]

2026-09-09 18:27:10,176 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:10,200 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:27:10,222 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:10,260 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.037s]
2026-09-09 18:27:10,292 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]

Indexing Records:  62%|██████▏   | 13832/22132 [05:24<03:12, 43.01it/s]

2026-09-09 18:27:10,323 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:27:10,351 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:27:10,374 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:10,391 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:10,412 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  63%|██████▎   | 13837/22132 [05:24<03:14, 42.61it/s]

2026-09-09 18:27:10,444 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:27:10,462 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:10,481 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:10,500 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:10,519 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  63%|██████▎   | 13842/22132 [05:24<03:09, 43.81it/s]

2026-09-09 18:27:10,544 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:27:10,567 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:10,587 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:10,605 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:10,622 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  63%|██████▎   | 13847/22132 [05:24<03:03, 45.04it/s]

2026-09-09 18:27:10,640 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:10,657 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:10,674 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:10,691 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:10,708 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:10,724 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  63%|██████▎   | 13853/22132 [05:24<02:49, 48.91it/s]

2026-09-09 18:27:10,742 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:10,765 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:10,785 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:10,805 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:10,821 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:10,837 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  63%|██████▎   | 13859/22132 [05:24<02:44, 50.25it/s]

2026-09-09 18:27:10,856 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:10,873 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:10,892 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:10,908 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:10,927 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:10,946 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  63%|██████▎   | 13865/22132 [05:25<02:40, 51.62it/s]

2026-09-09 18:27:10,965 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:10,981 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:10,998 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:11,017 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:11,033 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:11,049 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  63%|██████▎   | 13871/22132 [05:25<02:34, 53.47it/s]

2026-09-09 18:27:11,069 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:11,086 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:11,104 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:11,120 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:11,136 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:11,152 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  63%|██████▎   | 13877/22132 [05:25<02:30, 54.95it/s]

2026-09-09 18:27:11,170 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:11,185 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:11,202 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:11,218 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:11,235 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:11,257 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  63%|██████▎   | 13883/22132 [05:25<02:28, 55.55it/s]

2026-09-09 18:27:11,280 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:11,300 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:11,318 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:11,340 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:11,357 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:11,374 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  63%|██████▎   | 13889/22132 [05:25<02:32, 54.23it/s]

2026-09-09 18:27:11,391 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:11,407 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:11,423 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:11,441 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:11,457 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:11,476 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  63%|██████▎   | 13895/22132 [05:25<02:28, 55.49it/s]

2026-09-09 18:27:11,494 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:11,511 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:11,526 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:11,542 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:11,558 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:11,575 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:11,591 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  63%|██████▎   | 13902/22132 [05:25<02:23, 57.26it/s]

2026-09-09 18:27:11,609 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:11,625 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:11,641 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:11,658 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:11,675 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:11,691 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:11,707 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  63%|██████▎   | 13909/22132 [05:25<02:21, 58.18it/s]

2026-09-09 18:27:11,725 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:11,740 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:11,756 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:11,772 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:11,788 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:11,805 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:11,829 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  63%|██████▎   | 13916/22132 [05:25<02:21, 57.89it/s]

2026-09-09 18:27:11,848 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:11,866 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:11,882 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:11,898 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:11,915 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:11,932 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  63%|██████▎   | 13922/22132 [05:26<02:21, 58.07it/s]

2026-09-09 18:27:11,952 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:11,974 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:11,992 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:12,012 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:12,035 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:12,056 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  63%|██████▎   | 13928/22132 [05:26<02:29, 54.88it/s]

2026-09-09 18:27:12,073 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:12,089 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:12,106 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:12,124 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:12,142 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:12,157 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  63%|██████▎   | 13934/22132 [05:26<02:26, 56.04it/s]

2026-09-09 18:27:12,174 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:12,192 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:12,208 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:12,225 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:12,243 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:12,261 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  63%|██████▎   | 13940/22132 [05:26<02:24, 56.67it/s]

2026-09-09 18:27:12,278 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:12,294 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:12,315 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:12,333 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:12,350 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:12,367 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  63%|██████▎   | 13946/22132 [05:26<02:24, 56.52it/s]

2026-09-09 18:27:12,387 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:12,403 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:12,419 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:12,435 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:12,452 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:12,468 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  63%|██████▎   | 13952/22132 [05:26<02:22, 57.43it/s]

2026-09-09 18:27:12,485 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:12,505 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:12,523 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:12,539 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:12,558 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:12,575 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  63%|██████▎   | 13958/22132 [05:26<02:23, 56.95it/s]

2026-09-09 18:27:12,594 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:12,615 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:12,632 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:12,653 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:12,676 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:12,696 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  63%|██████▎   | 13964/22132 [05:26<02:29, 54.64it/s]

2026-09-09 18:27:12,714 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:12,742 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:27:12,763 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:12,785 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:12,803 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:12,823 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  63%|██████▎   | 13970/22132 [05:26<02:36, 52.17it/s]

2026-09-09 18:27:12,848 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:27:12,873 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:27:12,891 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:12,911 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:12,929 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:12,948 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  63%|██████▎   | 13976/22132 [05:27<02:40, 50.87it/s]

2026-09-09 18:27:12,965 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:12,982 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:13,001 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:13,022 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:13,038 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:13,054 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  63%|██████▎   | 13982/22132 [05:27<02:35, 52.36it/s]

2026-09-09 18:27:13,073 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:13,091 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:13,108 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:13,125 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:13,142 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:13,159 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  63%|██████▎   | 13988/22132 [05:27<02:31, 53.80it/s]

2026-09-09 18:27:13,176 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:13,194 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:13,211 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:13,227 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:13,242 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:13,257 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:13,274 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  63%|██████▎   | 13995/22132 [05:27<02:25, 55.89it/s]

2026-09-09 18:27:13,295 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:13,313 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:13,332 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:13,349 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:13,365 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:13,384 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  63%|██████▎   | 14001/22132 [05:27<02:26, 55.58it/s]

2026-09-09 18:27:13,404 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:13,422 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:13,478 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.055s]
2026-09-09 18:27:13,495 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:13,511 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:13,526 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  63%|██████▎   | 14007/22132 [05:27<02:39, 50.89it/s]

2026-09-09 18:27:13,543 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:13,559 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:13,576 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:13,595 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:13,613 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:13,633 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  63%|██████▎   | 14013/22132 [05:27<02:35, 52.20it/s]

2026-09-09 18:27:13,651 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:13,666 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:13,683 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:13,700 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:13,716 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:13,732 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:13,750 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  63%|██████▎   | 14020/22132 [05:27<02:28, 54.54it/s]

2026-09-09 18:27:13,767 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:13,783 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:13,801 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:13,816 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:13,832 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:13,848 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:13,866 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  63%|██████▎   | 14027/22132 [05:28<02:23, 56.37it/s]

2026-09-09 18:27:13,886 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:13,903 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:13,921 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:13,937 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:13,955 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:13,970 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  63%|██████▎   | 14033/22132 [05:28<02:23, 56.60it/s]

2026-09-09 18:27:13,987 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:14,005 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:14,034 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:27:14,057 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:27:14,077 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:14,095 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  63%|██████▎   | 14039/22132 [05:28<02:30, 53.95it/s]

2026-09-09 18:27:14,114 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:14,133 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:14,151 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:14,168 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:14,184 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:14,200 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  63%|██████▎   | 14045/22132 [05:28<02:27, 54.74it/s]

2026-09-09 18:27:14,221 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:14,245 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:27:14,261 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:14,278 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:14,297 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:14,313 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  63%|██████▎   | 14051/22132 [05:28<02:28, 54.29it/s]

2026-09-09 18:27:14,330 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:14,348 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:14,367 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:14,387 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:14,406 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:14,427 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  64%|██████▎   | 14057/22132 [05:28<02:30, 53.81it/s]

2026-09-09 18:27:14,452 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:27:14,471 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:14,489 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:14,508 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:14,527 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:14,547 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  64%|██████▎   | 14063/22132 [05:28<02:33, 52.61it/s]

2026-09-09 18:27:14,566 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:14,589 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:14,609 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:14,629 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:14,647 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:14,668 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  64%|██████▎   | 14069/22132 [05:28<02:36, 51.62it/s]

2026-09-09 18:27:14,691 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:14,720 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:27:14,739 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:14,761 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:14,782 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:14,802 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  64%|██████▎   | 14075/22132 [05:28<02:43, 49.35it/s]

2026-09-09 18:27:14,824 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:14,842 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:14,861 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:14,879 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:14,898 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:14,917 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  64%|██████▎   | 14081/22132 [05:29<02:40, 50.17it/s]

2026-09-09 18:27:14,939 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:14,961 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:14,982 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:15,001 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:15,030 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:27:15,066 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]

Indexing Records:  64%|██████▎   | 14087/22132 [05:29<02:51, 46.79it/s]

2026-09-09 18:27:15,086 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:15,104 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:15,120 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:15,137 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:15,155 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:15,171 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  64%|██████▎   | 14093/22132 [05:29<02:42, 49.45it/s]

2026-09-09 18:27:15,189 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:15,205 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:15,221 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:15,237 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:15,253 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:15,268 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:15,284 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  64%|██████▎   | 14100/22132 [05:29<02:31, 53.03it/s]

2026-09-09 18:27:15,302 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:15,317 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:15,334 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:15,351 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:15,368 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:15,383 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:15,401 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  64%|██████▎   | 14107/22132 [05:29<02:25, 55.05it/s]

2026-09-09 18:27:15,420 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:15,436 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:15,454 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:15,469 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:15,486 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:15,502 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  64%|██████▍   | 14113/22132 [05:29<02:22, 56.13it/s]

2026-09-09 18:27:15,518 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:15,534 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:15,550 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:15,567 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:15,584 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:15,600 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:15,618 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  64%|██████▍   | 14120/22132 [05:29<02:19, 57.42it/s]

2026-09-09 18:27:15,638 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:15,653 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:15,670 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:15,686 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:15,701 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:15,718 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:15,735 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  64%|██████▍   | 14127/22132 [05:29<02:17, 58.17it/s]

2026-09-09 18:27:15,752 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:15,769 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:15,785 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:15,802 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:15,820 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:15,838 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  64%|██████▍   | 14133/22132 [05:29<02:17, 58.28it/s]

2026-09-09 18:27:15,855 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:15,871 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:15,890 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:15,908 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:15,925 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:15,943 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  64%|██████▍   | 14139/22132 [05:30<02:17, 57.98it/s]

2026-09-09 18:27:15,960 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:15,976 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:15,992 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:16,010 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:16,028 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:16,046 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  64%|██████▍   | 14145/22132 [05:30<02:17, 57.99it/s]

2026-09-09 18:27:16,068 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:16,089 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:16,115 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:27:16,132 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:16,149 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:16,165 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  64%|██████▍   | 14151/22132 [05:30<02:23, 55.57it/s]

2026-09-09 18:27:16,183 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:16,199 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:16,218 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:16,234 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:16,251 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:16,270 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  64%|██████▍   | 14157/22132 [05:30<02:22, 56.05it/s]

2026-09-09 18:27:16,288 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:16,308 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:16,326 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:16,344 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:16,364 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:16,382 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  64%|██████▍   | 14163/22132 [05:30<02:24, 55.20it/s]

2026-09-09 18:27:16,402 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:16,420 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:16,437 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:16,457 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:16,480 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:16,496 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  64%|██████▍   | 14169/22132 [05:30<02:26, 54.40it/s]

2026-09-09 18:27:16,515 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:16,534 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:16,551 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:16,567 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:16,585 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:16,601 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  64%|██████▍   | 14175/22132 [05:30<02:24, 55.18it/s]

2026-09-09 18:27:16,617 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:16,633 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:16,649 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:16,666 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:16,682 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:16,698 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:16,715 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  64%|██████▍   | 14182/22132 [05:30<02:19, 57.15it/s]

2026-09-09 18:27:16,732 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:16,748 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:16,765 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:16,783 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:16,800 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:16,818 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  64%|██████▍   | 14188/22132 [05:30<02:18, 57.46it/s]

2026-09-09 18:27:16,836 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:16,853 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:16,870 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:16,885 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:16,904 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:16,921 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  64%|██████▍   | 14194/22132 [05:31<02:17, 57.65it/s]

2026-09-09 18:27:16,939 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:16,956 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:16,975 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:16,993 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:17,012 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:17,029 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  64%|██████▍   | 14200/22132 [05:31<02:18, 57.07it/s]

2026-09-09 18:27:17,046 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:17,065 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:17,084 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:17,102 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:17,118 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:17,137 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  64%|██████▍   | 14206/22132 [05:31<02:19, 56.62it/s]

2026-09-09 18:27:17,156 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:17,174 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:17,194 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:17,213 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:17,231 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:17,248 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  64%|██████▍   | 14212/22132 [05:31<02:21, 55.79it/s]

2026-09-09 18:27:17,268 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:17,285 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:17,303 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:17,320 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:17,339 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:17,356 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  64%|██████▍   | 14218/22132 [05:31<02:21, 55.75it/s]

2026-09-09 18:27:17,378 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:17,398 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:17,416 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:17,433 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:17,452 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:17,471 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  64%|██████▍   | 14224/22132 [05:31<02:24, 54.58it/s]

2026-09-09 18:27:17,489 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:17,511 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:17,534 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:27:17,553 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:17,572 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:17,588 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  64%|██████▍   | 14230/22132 [05:31<02:27, 53.60it/s]

2026-09-09 18:27:17,614 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:27:17,631 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:17,648 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:17,665 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:17,683 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:17,700 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  64%|██████▍   | 14236/22132 [05:31<02:27, 53.61it/s]

2026-09-09 18:27:17,718 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:17,736 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:17,754 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:17,772 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:17,790 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:17,807 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  64%|██████▍   | 14242/22132 [05:31<02:25, 54.28it/s]

2026-09-09 18:27:17,826 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:17,845 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:17,864 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:17,884 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:17,900 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:17,916 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  64%|██████▍   | 14248/22132 [05:32<02:24, 54.53it/s]

2026-09-09 18:27:17,935 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:17,953 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:17,970 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:17,986 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:18,004 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:18,020 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  64%|██████▍   | 14254/22132 [05:32<02:22, 55.42it/s]

2026-09-09 18:27:18,037 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:18,055 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:18,078 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:27:18,099 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:18,122 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:18,144 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  64%|██████▍   | 14260/22132 [05:32<02:27, 53.19it/s]

2026-09-09 18:27:18,170 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:27:18,190 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:18,208 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:18,227 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:18,248 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:18,266 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  64%|██████▍   | 14266/22132 [05:32<02:31, 51.87it/s]

2026-09-09 18:27:18,284 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:18,301 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:18,319 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:18,342 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:18,364 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:18,386 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  64%|██████▍   | 14272/22132 [05:32<02:33, 51.34it/s]

2026-09-09 18:27:18,406 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:18,433 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:27:18,455 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:18,474 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:18,506 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:27:18,526 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  65%|██████▍   | 14278/22132 [05:32<02:42, 48.47it/s]

2026-09-09 18:27:18,543 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:18,559 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:18,574 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:18,590 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:18,607 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:18,625 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:18,642 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  65%|██████▍   | 14285/22132 [05:32<02:31, 51.88it/s]

2026-09-09 18:27:18,660 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:18,683 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:27:18,702 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:18,721 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:18,738 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:18,757 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  65%|██████▍   | 14291/22132 [05:32<02:31, 51.87it/s]

2026-09-09 18:27:18,777 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:18,796 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:18,815 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:18,833 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:18,852 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:18,872 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  65%|██████▍   | 14297/22132 [05:33<02:30, 51.98it/s]

2026-09-09 18:27:18,892 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:18,909 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:18,926 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:18,944 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:18,966 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:18,983 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  65%|██████▍   | 14303/22132 [05:33<02:28, 52.64it/s]

2026-09-09 18:27:19,000 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:19,025 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:27:19,044 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:19,062 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:19,082 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:19,101 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  65%|██████▍   | 14309/22132 [05:33<02:30, 52.06it/s]

2026-09-09 18:27:19,123 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:19,141 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:19,164 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:19,188 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:27:19,206 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:19,224 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  65%|██████▍   | 14315/22132 [05:33<02:33, 51.07it/s]

2026-09-09 18:27:19,245 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:19,265 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:19,285 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:19,301 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:19,320 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:19,339 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  65%|██████▍   | 14321/22132 [05:33<02:31, 51.42it/s]

2026-09-09 18:27:19,360 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:19,378 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:19,398 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:19,420 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:19,447 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:27:19,466 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  65%|██████▍   | 14327/22132 [05:33<02:36, 49.96it/s]

2026-09-09 18:27:19,485 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:19,502 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:19,527 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:27:19,549 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:19,577 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:27:19,596 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  65%|██████▍   | 14333/22132 [05:33<02:39, 48.81it/s]

2026-09-09 18:27:19,614 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:19,631 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:19,648 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:19,665 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:19,681 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:19,699 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  65%|██████▍   | 14339/22132 [05:33<02:31, 51.37it/s]

2026-09-09 18:27:19,716 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:19,732 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:19,749 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:19,766 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:19,782 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:19,798 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:19,814 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  65%|██████▍   | 14346/22132 [05:33<02:23, 54.20it/s]

2026-09-09 18:27:19,833 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:19,849 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:19,866 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:19,884 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:19,901 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:19,921 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  65%|██████▍   | 14352/22132 [05:34<02:22, 54.71it/s]

2026-09-09 18:27:19,940 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:19,956 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:19,973 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:19,990 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:20,009 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:20,031 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  65%|██████▍   | 14358/22132 [05:34<02:22, 54.68it/s]

2026-09-09 18:27:20,049 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:20,065 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:20,080 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:20,096 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:20,113 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:20,131 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  65%|██████▍   | 14364/22132 [05:34<02:18, 56.13it/s]

2026-09-09 18:27:20,148 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:20,166 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:20,187 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:20,207 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:20,226 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:20,246 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  65%|██████▍   | 14370/22132 [05:34<02:21, 54.86it/s]

2026-09-09 18:27:20,267 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:20,285 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:20,300 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:20,317 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:20,335 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:20,352 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  65%|██████▍   | 14376/22132 [05:34<02:20, 55.31it/s]

2026-09-09 18:27:20,375 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:20,392 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:20,410 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:20,428 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:20,447 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:20,465 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  65%|██████▍   | 14382/22132 [05:34<02:21, 54.70it/s]

2026-09-09 18:27:20,484 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:20,504 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:20,522 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:20,546 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:27:20,566 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:20,585 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  65%|██████▌   | 14388/22132 [05:34<02:25, 53.22it/s]

2026-09-09 18:27:20,604 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:20,620 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:20,638 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:20,654 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:20,669 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:20,687 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  65%|██████▌   | 14394/22132 [05:34<02:21, 54.80it/s]

2026-09-09 18:27:20,704 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:20,722 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:20,742 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:20,761 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:20,779 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:20,797 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  65%|██████▌   | 14400/22132 [05:34<02:21, 54.62it/s]

2026-09-09 18:27:20,816 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:20,843 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:27:20,861 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:20,878 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:20,900 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:20,921 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  65%|██████▌   | 14406/22132 [05:35<02:26, 52.66it/s]

2026-09-09 18:27:20,939 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:20,957 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:20,975 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:20,992 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:21,011 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:21,028 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  65%|██████▌   | 14412/22132 [05:35<02:23, 53.63it/s]

2026-09-09 18:27:21,045 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:21,067 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:21,085 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:21,105 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:21,128 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:21,150 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  65%|██████▌   | 14418/22132 [05:35<02:27, 52.21it/s]

2026-09-09 18:27:21,176 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:27:21,194 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:21,210 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:21,227 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:21,243 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:21,258 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  65%|██████▌   | 14424/22132 [05:35<02:25, 53.14it/s]

2026-09-09 18:27:21,275 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:21,292 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:21,308 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:21,326 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:21,343 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:21,360 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  65%|██████▌   | 14430/22132 [05:35<02:20, 54.76it/s]

2026-09-09 18:27:21,378 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:21,395 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:21,416 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:21,433 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:21,453 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:21,473 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  65%|██████▌   | 14436/22132 [05:35<02:21, 54.23it/s]

2026-09-09 18:27:21,490 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:21,506 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:21,525 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:21,545 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:21,561 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:21,578 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  65%|██████▌   | 14442/22132 [05:35<02:19, 55.07it/s]

2026-09-09 18:27:21,599 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:21,621 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:21,651 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:27:21,667 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:21,683 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:21,700 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  65%|██████▌   | 14448/22132 [05:35<02:24, 53.13it/s]

2026-09-09 18:27:21,719 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:21,734 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:21,751 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:21,769 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:21,787 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:21,804 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  65%|██████▌   | 14454/22132 [05:35<02:20, 54.49it/s]

2026-09-09 18:27:21,821 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:21,837 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:21,857 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:21,882 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:27:21,916 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:27:21,943 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]

Indexing Records:  65%|██████▌   | 14460/22132 [05:36<02:31, 50.50it/s]

2026-09-09 18:27:21,975 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:27:21,995 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:22,019 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:27:22,043 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:27:22,072 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:27:22,089 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  65%|██████▌   | 14466/22132 [05:36<02:42, 47.23it/s]

2026-09-09 18:27:22,108 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:22,124 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:22,141 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:22,159 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:22,176 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:22,196 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  65%|██████▌   | 14472/22132 [05:36<02:34, 49.60it/s]

2026-09-09 18:27:22,216 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:22,240 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:27:22,256 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:22,272 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:22,289 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:22,307 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  65%|██████▌   | 14478/22132 [05:36<02:30, 50.87it/s]

2026-09-09 18:27:22,327 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:22,344 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:22,360 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:22,377 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:22,393 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:22,410 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  65%|██████▌   | 14484/22132 [05:36<02:24, 52.84it/s]

2026-09-09 18:27:22,428 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:22,447 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:22,464 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:22,481 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:22,497 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:22,512 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  65%|██████▌   | 14490/22132 [05:36<02:20, 54.47it/s]

2026-09-09 18:27:22,530 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:22,548 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:22,564 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:22,588 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:27:22,611 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:27:22,628 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  65%|██████▌   | 14496/22132 [05:36<02:22, 53.60it/s]

2026-09-09 18:27:22,647 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:22,664 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:22,680 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:22,696 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:22,713 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:22,732 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  66%|██████▌   | 14502/22132 [05:36<02:19, 54.88it/s]

2026-09-09 18:27:22,751 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:22,768 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:22,788 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:22,808 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:22,827 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:22,844 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  66%|██████▌   | 14508/22132 [05:36<02:20, 54.40it/s]

2026-09-09 18:27:22,861 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:22,878 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:22,895 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:22,915 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:22,932 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:22,952 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  66%|██████▌   | 14514/22132 [05:37<02:19, 54.76it/s]

2026-09-09 18:27:22,969 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:22,989 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:23,012 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:27:23,028 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:23,045 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:23,062 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  66%|██████▌   | 14520/22132 [05:37<02:19, 54.69it/s]

2026-09-09 18:27:23,079 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:23,096 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:23,113 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:23,130 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:23,148 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:23,165 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  66%|██████▌   | 14526/22132 [05:37<02:16, 55.77it/s]

2026-09-09 18:27:23,184 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:23,201 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:23,217 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:23,233 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:23,250 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:23,265 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  66%|██████▌   | 14532/22132 [05:37<02:13, 56.96it/s]

2026-09-09 18:27:23,281 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:23,299 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:23,314 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:23,330 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:23,347 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:23,364 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:23,385 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  66%|██████▌   | 14539/22132 [05:37<02:12, 57.36it/s]

2026-09-09 18:27:23,404 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:23,419 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:23,436 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:23,455 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:23,475 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:23,491 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  66%|██████▌   | 14545/22132 [05:37<02:12, 57.23it/s]

2026-09-09 18:27:23,511 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:23,532 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:23,549 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:23,564 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:23,581 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:23,598 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  66%|██████▌   | 14551/22132 [05:37<02:13, 56.84it/s]

2026-09-09 18:27:23,618 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:23,635 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:23,654 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:23,670 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:23,686 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:23,701 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  66%|██████▌   | 14557/22132 [05:37<02:12, 57.18it/s]

2026-09-09 18:27:23,717 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:23,733 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:23,751 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:23,767 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:23,783 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:23,799 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:23,815 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  66%|██████▌   | 14564/22132 [05:37<02:09, 58.60it/s]

2026-09-09 18:27:23,832 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:23,848 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:23,878 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:27:23,894 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:23,912 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:23,928 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  66%|██████▌   | 14570/22132 [05:38<02:12, 56.93it/s]

2026-09-09 18:27:23,945 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:23,960 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:23,976 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:23,993 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:24,009 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:24,028 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  66%|██████▌   | 14576/22132 [05:38<02:10, 57.78it/s]

2026-09-09 18:27:24,044 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:24,061 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:24,126 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.064s]
2026-09-09 18:27:24,161 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]
2026-09-09 18:27:24,194 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:27:24,233 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.038s]

Indexing Records:  66%|██████▌   | 14582/22132 [05:38<02:48, 44.86it/s]

2026-09-09 18:27:24,258 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:27:24,297 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.038s]
2026-09-09 18:27:24,331 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]
2026-09-09 18:27:24,372 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.039s]
2026-09-09 18:27:24,445 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.071s]

Indexing Records:  66%|██████▌   | 14587/22132 [05:38<03:27, 36.42it/s]

2026-09-09 18:27:24,467 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:24,490 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:27:24,510 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:24,548 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.036s]
2026-09-09 18:27:24,569 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  66%|██████▌   | 14592/22132 [05:38<03:22, 37.32it/s]

2026-09-09 18:27:24,590 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:24,610 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:24,633 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:27:24,652 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:24,671 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  66%|██████▌   | 14597/22132 [05:38<03:08, 40.02it/s]

2026-09-09 18:27:24,690 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:24,709 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:24,728 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:24,748 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:24,767 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:24,787 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  66%|██████▌   | 14603/22132 [05:38<02:54, 43.14it/s]

2026-09-09 18:27:24,807 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:24,828 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:24,846 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:24,866 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:24,883 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:24,905 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  66%|██████▌   | 14609/22132 [05:39<02:45, 45.38it/s]

2026-09-09 18:27:24,924 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:24,947 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:27:24,968 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:24,987 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:25,004 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:25,026 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  66%|██████▌   | 14615/22132 [05:39<02:41, 46.61it/s]

2026-09-09 18:27:25,045 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:25,063 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:25,082 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:25,102 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:25,122 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:25,140 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  66%|██████▌   | 14621/22132 [05:39<02:35, 48.25it/s]

2026-09-09 18:27:25,161 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:25,181 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:25,201 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:25,236 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]
2026-09-09 18:27:25,257 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  66%|██████▌   | 14626/22132 [05:39<02:41, 46.60it/s]

2026-09-09 18:27:25,279 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:25,346 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.066s]
2026-09-09 18:27:25,365 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:25,384 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:25,404 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  66%|██████▌   | 14631/22132 [05:39<02:57, 42.38it/s]

2026-09-09 18:27:25,423 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:25,442 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:25,465 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:27:25,487 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:25,507 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  66%|██████▌   | 14636/22132 [05:39<02:50, 43.89it/s]

2026-09-09 18:27:25,526 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:25,544 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:25,563 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:25,580 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:25,600 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:25,618 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  66%|██████▌   | 14642/22132 [05:39<02:40, 46.81it/s]

2026-09-09 18:27:25,637 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:25,656 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:25,674 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:25,693 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:25,711 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:25,730 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  66%|██████▌   | 14648/22132 [05:39<02:33, 48.76it/s]

2026-09-09 18:27:25,747 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:25,764 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:25,780 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:25,800 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:25,820 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:25,853 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]

Indexing Records:  66%|██████▌   | 14654/22132 [05:39<02:33, 48.70it/s]

2026-09-09 18:27:25,876 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:25,904 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:27:25,932 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:27:25,965 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:27:25,993 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]

Indexing Records:  66%|██████▌   | 14659/22132 [05:40<02:48, 44.41it/s]

2026-09-09 18:27:26,015 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:26,037 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:26,075 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.037s]
2026-09-09 18:27:26,106 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:27:26,127 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  66%|██████▋   | 14664/22132 [05:40<02:57, 42.18it/s]

2026-09-09 18:27:26,158 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:27:26,178 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:26,201 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:26,219 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:26,236 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  66%|██████▋   | 14669/22132 [05:40<02:53, 43.09it/s]

2026-09-09 18:27:26,254 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:26,274 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:26,290 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:26,309 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:26,331 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:26,349 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  66%|██████▋   | 14675/22132 [05:40<02:42, 45.97it/s]

2026-09-09 18:27:26,367 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:26,383 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:26,400 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:26,416 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:26,432 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:26,448 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:26,464 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  66%|██████▋   | 14682/22132 [05:40<02:27, 50.35it/s]

2026-09-09 18:27:26,482 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:26,498 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:26,515 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:26,530 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:26,547 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:26,564 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  66%|██████▋   | 14688/22132 [05:40<02:20, 52.90it/s]

2026-09-09 18:27:26,580 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:26,596 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:26,613 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:26,630 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:26,645 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:26,662 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:26,678 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  66%|██████▋   | 14695/22132 [05:40<02:13, 55.50it/s]

2026-09-09 18:27:26,694 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:26,709 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:26,726 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:26,742 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:26,757 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:26,773 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:26,788 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  66%|██████▋   | 14702/22132 [05:40<02:08, 57.79it/s]

2026-09-09 18:27:26,806 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:26,821 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:26,836 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:26,852 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:26,869 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:26,885 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:26,902 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  66%|██████▋   | 14709/22132 [05:41<02:05, 59.03it/s]

2026-09-09 18:27:26,918 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:26,935 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:26,952 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:26,967 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:26,983 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:26,999 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:27,016 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  66%|██████▋   | 14716/22132 [05:41<02:04, 59.64it/s]

2026-09-09 18:27:27,032 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:27,047 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:27,065 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:27,081 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:27,099 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:27,115 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:27,131 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  67%|██████▋   | 14723/22132 [05:41<02:03, 59.98it/s]

2026-09-09 18:27:27,148 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:27,164 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:27,182 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:27,197 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:27,212 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:27,229 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:27,245 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  67%|██████▋   | 14730/22132 [05:41<02:02, 60.44it/s]

2026-09-09 18:27:27,263 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:27,279 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:27,294 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:27,310 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:27,325 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:27,341 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:27,357 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  67%|██████▋   | 14737/22132 [05:41<02:00, 61.17it/s]

2026-09-09 18:27:27,374 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:27,391 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:27,408 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:27,423 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:27,439 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:27,454 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:27,469 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  67%|██████▋   | 14744/22132 [05:41<02:00, 61.45it/s]

2026-09-09 18:27:27,489 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:27,504 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:27,519 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:27,534 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:27,551 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:27,579 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:27:27,598 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  67%|██████▋   | 14751/22132 [05:41<02:04, 59.13it/s]

2026-09-09 18:27:27,618 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:27,634 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:27,650 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:27,667 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:27,683 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:27,699 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  67%|██████▋   | 14757/22132 [05:41<02:04, 59.14it/s]

2026-09-09 18:27:27,716 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:27,733 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:27,748 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:27,764 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:27,780 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:27,795 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:27,811 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  67%|██████▋   | 14764/22132 [05:41<02:02, 60.16it/s]

2026-09-09 18:27:27,827 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:27,842 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:27,858 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:27,875 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:27,891 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:27,908 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:27,924 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  67%|██████▋   | 14771/22132 [05:42<02:01, 60.78it/s]

2026-09-09 18:27:27,940 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:27,955 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:27,971 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:27,987 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:28,002 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:28,018 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:28,035 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  67%|██████▋   | 14778/22132 [05:42<01:59, 61.39it/s]

2026-09-09 18:27:28,052 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:28,068 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:28,084 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:28,100 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:28,116 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:28,134 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:28,151 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  67%|██████▋   | 14785/22132 [05:42<02:00, 61.14it/s]

2026-09-09 18:27:28,167 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:28,183 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:28,199 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:28,216 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:28,233 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:28,250 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:28,266 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  67%|██████▋   | 14792/22132 [05:42<02:00, 61.08it/s]

2026-09-09 18:27:28,282 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:28,298 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:28,313 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:28,330 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:28,347 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:28,365 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:28,385 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  67%|██████▋   | 14799/22132 [05:42<02:01, 60.33it/s]

2026-09-09 18:27:28,401 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:28,417 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:28,434 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:28,450 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:28,466 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:28,481 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:28,500 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  67%|██████▋   | 14806/22132 [05:42<02:01, 60.54it/s]

2026-09-09 18:27:28,516 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:28,532 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:28,548 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:28,564 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:28,581 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:28,597 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:28,612 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  67%|██████▋   | 14813/22132 [05:42<01:59, 61.01it/s]

2026-09-09 18:27:28,628 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:28,645 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:28,662 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:28,677 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:28,697 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:28,715 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:28,731 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  67%|██████▋   | 14820/22132 [05:42<02:01, 60.34it/s]

2026-09-09 18:27:28,748 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:28,765 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:28,780 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:28,796 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:28,813 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:28,829 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:28,844 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  67%|██████▋   | 14827/22132 [05:42<01:59, 60.91it/s]

2026-09-09 18:27:28,860 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:28,875 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:28,891 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:28,906 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:28,922 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:28,942 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:28,959 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  67%|██████▋   | 14834/22132 [05:43<01:59, 60.91it/s]

2026-09-09 18:27:28,975 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:28,990 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:29,006 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:29,022 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:29,039 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:29,054 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:29,070 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  67%|██████▋   | 14841/22132 [05:43<01:58, 61.48it/s]

2026-09-09 18:27:29,087 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:29,104 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:29,119 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:29,135 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:29,151 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:29,167 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:29,185 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  67%|██████▋   | 14848/22132 [05:43<01:58, 61.34it/s]

2026-09-09 18:27:29,203 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:29,218 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:29,235 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:29,251 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:29,267 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:29,286 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:29,301 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  67%|██████▋   | 14855/22132 [05:43<01:59, 60.95it/s]

2026-09-09 18:27:29,318 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:29,334 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:29,350 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:29,366 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:29,382 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:29,399 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:29,416 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  67%|██████▋   | 14862/22132 [05:43<01:59, 60.95it/s]

2026-09-09 18:27:29,436 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:29,454 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:29,472 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:29,490 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:29,508 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:29,525 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:29,541 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  67%|██████▋   | 14869/22132 [05:43<02:02, 59.45it/s]

2026-09-09 18:27:29,557 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:29,575 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:29,591 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:29,608 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:29,638 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:27:29,663 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  67%|██████▋   | 14875/22132 [05:43<02:09, 56.18it/s]

2026-09-09 18:27:29,691 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:27:29,707 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:29,727 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:29,745 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:29,764 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:29,786 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  67%|██████▋   | 14881/22132 [05:43<02:14, 53.91it/s]

2026-09-09 18:27:29,811 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:27:29,828 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:29,853 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:27:29,871 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:29,891 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:29,909 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  67%|██████▋   | 14887/22132 [05:44<02:18, 52.43it/s]

2026-09-09 18:27:29,932 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:27:29,953 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:29,971 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:29,991 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:30,024 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:27:30,047 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  67%|██████▋   | 14893/22132 [05:44<02:26, 49.42it/s]

2026-09-09 18:27:30,068 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:30,086 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:30,103 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:30,120 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:30,137 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:30,154 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  67%|██████▋   | 14899/22132 [05:44<02:21, 51.27it/s]

2026-09-09 18:27:30,173 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:30,189 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:30,206 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:30,228 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:27:30,251 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:27:30,267 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  67%|██████▋   | 14905/22132 [05:44<02:19, 51.74it/s]

2026-09-09 18:27:30,283 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:30,299 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:30,316 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:30,331 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:30,347 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:30,366 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:30,384 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  67%|██████▋   | 14912/22132 [05:44<02:13, 54.24it/s]

2026-09-09 18:27:30,406 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:30,427 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:30,444 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:30,460 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:30,475 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:30,491 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  67%|██████▋   | 14918/22132 [05:44<02:11, 54.72it/s]

2026-09-09 18:27:30,507 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:30,524 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:30,540 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:30,555 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:30,572 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:30,589 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:30,607 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  67%|██████▋   | 14925/22132 [05:44<02:07, 56.41it/s]

2026-09-09 18:27:30,626 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:30,643 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:30,658 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:30,675 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:30,691 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:30,709 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  67%|██████▋   | 14931/22132 [05:44<02:06, 57.05it/s]

2026-09-09 18:27:30,726 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:30,744 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:30,760 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:30,778 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:30,794 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:30,811 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  67%|██████▋   | 14937/22132 [05:44<02:04, 57.61it/s]

2026-09-09 18:27:30,829 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:30,844 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:30,860 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:30,876 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:30,892 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:30,908 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:30,926 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  68%|██████▊   | 14944/22132 [05:45<02:02, 58.64it/s]

2026-09-09 18:27:30,943 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:30,960 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:30,979 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:30,997 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:31,018 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:31,034 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  68%|██████▊   | 14950/22132 [05:45<02:04, 57.72it/s]

2026-09-09 18:27:31,052 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:31,069 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:31,088 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:31,104 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:31,121 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:31,138 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  68%|██████▊   | 14956/22132 [05:45<02:04, 57.71it/s]

2026-09-09 18:27:31,156 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:31,173 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:31,191 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:31,209 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:31,226 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:31,245 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  68%|██████▊   | 14962/22132 [05:45<02:05, 57.17it/s]

2026-09-09 18:27:31,263 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:31,281 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:31,297 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:31,313 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:31,329 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:31,345 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:31,360 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  68%|██████▊   | 14969/22132 [05:45<02:02, 58.36it/s]

2026-09-09 18:27:31,377 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:31,394 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:31,411 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:31,427 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:31,443 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:31,459 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:31,476 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  68%|██████▊   | 14976/22132 [05:45<02:01, 58.99it/s]

2026-09-09 18:27:31,493 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:31,508 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:31,526 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:31,543 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:31,558 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:31,575 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:31,592 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  68%|██████▊   | 14983/22132 [05:45<02:00, 59.40it/s]

2026-09-09 18:27:31,608 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:31,624 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:31,642 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:31,658 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:31,675 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:31,692 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:31,709 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  68%|██████▊   | 14990/22132 [05:45<01:59, 59.56it/s]

2026-09-09 18:27:31,762 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.051s]
2026-09-09 18:27:31,787 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:27:31,810 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:27:31,829 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:31,847 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:31,873 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]

Indexing Records:  68%|██████▊   | 14996/22132 [05:46<02:20, 50.72it/s]

2026-09-09 18:27:31,891 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:31,908 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:31,924 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:31,943 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:31,961 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:31,977 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  68%|██████▊   | 15002/22132 [05:46<02:15, 52.54it/s]

2026-09-09 18:27:31,993 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:32,009 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:32,024 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:32,045 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:32,061 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:32,077 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:32,092 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  68%|██████▊   | 15009/22132 [05:46<02:09, 54.91it/s]

2026-09-09 18:27:32,109 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:32,125 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:32,141 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:32,158 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:32,174 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:32,191 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:32,208 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  68%|██████▊   | 15016/22132 [05:46<02:05, 56.58it/s]

2026-09-09 18:27:32,226 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:32,245 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:32,263 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:32,282 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:32,299 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:32,314 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  68%|██████▊   | 15022/22132 [05:46<02:05, 56.50it/s]

2026-09-09 18:27:32,333 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:32,349 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:32,365 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:32,381 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:32,396 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:32,414 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:32,431 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  68%|██████▊   | 15029/22132 [05:46<02:03, 57.51it/s]

2026-09-09 18:27:32,452 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:32,474 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:32,495 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:32,513 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:32,534 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:32,551 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  68%|██████▊   | 15035/22132 [05:46<02:08, 55.30it/s]

2026-09-09 18:27:32,568 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:32,584 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:32,600 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:32,617 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:32,634 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:32,653 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  68%|██████▊   | 15041/22132 [05:46<02:06, 56.19it/s]

2026-09-09 18:27:32,672 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:32,692 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:32,712 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:32,734 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:32,752 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:32,772 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  68%|██████▊   | 15047/22132 [05:46<02:10, 54.44it/s]

2026-09-09 18:27:32,791 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:32,811 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:32,828 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:32,848 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:32,864 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:32,882 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  68%|██████▊   | 15053/22132 [05:47<02:09, 54.48it/s]

2026-09-09 18:27:32,899 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:32,915 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:32,933 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:32,950 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:32,966 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:32,983 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  68%|██████▊   | 15059/22132 [05:47<02:06, 55.87it/s]

2026-09-09 18:27:33,000 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:33,020 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:33,037 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:33,053 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:33,071 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:33,087 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  68%|██████▊   | 15065/22132 [05:47<02:05, 56.28it/s]

2026-09-09 18:27:33,105 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:33,123 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:33,139 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:33,156 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:33,175 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:33,194 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  68%|██████▊   | 15071/22132 [05:47<02:05, 56.31it/s]

2026-09-09 18:27:33,210 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:33,227 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:33,244 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:33,261 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:33,276 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:33,292 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:33,308 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  68%|██████▊   | 15078/22132 [05:47<02:01, 57.92it/s]

2026-09-09 18:27:33,328 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:33,344 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:33,360 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:33,376 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:33,391 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:33,408 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  68%|██████▊   | 15084/22132 [05:47<02:00, 58.46it/s]

2026-09-09 18:27:33,424 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:33,440 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:33,455 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:33,474 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:33,490 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:33,507 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:33,524 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  68%|██████▊   | 15091/22132 [05:47<01:59, 59.04it/s]

2026-09-09 18:27:33,554 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:27:33,572 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:33,590 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:33,609 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:33,628 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:33,644 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  68%|██████▊   | 15097/22132 [05:47<02:05, 56.14it/s]

2026-09-09 18:27:33,664 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:33,683 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:33,708 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:27:33,729 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:33,747 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:33,766 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  68%|██████▊   | 15103/22132 [05:47<02:10, 53.90it/s]

2026-09-09 18:27:33,786 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:33,806 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:33,825 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:33,845 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:33,862 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:33,879 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  68%|██████▊   | 15109/22132 [05:48<02:10, 53.68it/s]

2026-09-09 18:27:33,896 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:33,913 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:33,929 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:33,945 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:33,962 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:33,982 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  68%|██████▊   | 15115/22132 [05:48<02:07, 55.06it/s]

2026-09-09 18:27:33,998 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:34,017 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:34,035 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:34,053 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:34,068 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:34,084 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  68%|██████▊   | 15121/22132 [05:48<02:05, 56.00it/s]

2026-09-09 18:27:34,104 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:34,123 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:34,146 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:34,164 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:34,182 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:34,202 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  68%|██████▊   | 15127/22132 [05:48<02:08, 54.47it/s]

2026-09-09 18:27:34,220 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:34,238 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:34,259 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:34,278 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:34,296 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:34,322 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  68%|██████▊   | 15133/22132 [05:48<02:12, 53.00it/s]

2026-09-09 18:27:34,344 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:34,359 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:34,374 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:34,391 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:34,407 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:34,424 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  68%|██████▊   | 15139/22132 [05:48<02:08, 54.62it/s]

2026-09-09 18:27:34,440 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:34,456 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:34,471 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:34,487 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:34,507 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:34,525 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  68%|██████▊   | 15145/22132 [05:48<02:04, 55.92it/s]

2026-09-09 18:27:34,544 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:34,562 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:34,579 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:34,594 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:34,610 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:34,631 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  68%|██████▊   | 15151/22132 [05:48<02:04, 56.18it/s]

2026-09-09 18:27:34,648 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:34,667 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:34,687 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:34,705 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:34,723 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:34,779 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.055s]

Indexing Records:  68%|██████▊   | 15157/22132 [05:48<02:18, 50.31it/s]

2026-09-09 18:27:34,801 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:34,819 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:34,836 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:34,853 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:34,871 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:34,888 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  69%|██████▊   | 15163/22132 [05:49<02:14, 51.66it/s]

2026-09-09 18:27:34,906 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:34,922 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:34,937 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:34,953 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:34,971 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:34,987 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:35,004 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  69%|██████▊   | 15170/22132 [05:49<02:08, 54.32it/s]

2026-09-09 18:27:35,025 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:35,041 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:35,058 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:35,075 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:35,090 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:35,106 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  69%|██████▊   | 15176/22132 [05:49<02:05, 55.48it/s]

2026-09-09 18:27:35,124 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:35,140 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:35,156 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:35,172 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:35,188 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:35,203 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:35,219 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  69%|██████▊   | 15183/22132 [05:49<02:00, 57.45it/s]

2026-09-09 18:27:35,236 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:35,253 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:35,273 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:35,291 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:35,308 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:35,325 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  69%|██████▊   | 15189/22132 [05:49<02:01, 57.16it/s]

2026-09-09 18:27:35,343 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:35,358 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:35,374 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:35,391 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:35,406 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:35,425 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:35,446 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  69%|██████▊   | 15196/22132 [05:49<02:00, 57.46it/s]

2026-09-09 18:27:35,465 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:35,481 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:35,498 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:35,514 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:35,530 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:35,547 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  69%|██████▊   | 15202/22132 [05:49<01:59, 58.00it/s]

2026-09-09 18:27:35,564 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:35,580 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:35,601 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:35,619 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:35,634 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:35,651 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  69%|██████▊   | 15208/22132 [05:49<01:59, 57.91it/s]

2026-09-09 18:27:35,668 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:35,685 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:35,701 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:35,719 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:35,741 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:35,764 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  69%|██████▊   | 15214/22132 [05:49<02:02, 56.32it/s]

2026-09-09 18:27:35,788 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:35,805 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:35,822 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:35,841 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:35,860 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:35,878 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  69%|██████▉   | 15220/22132 [05:50<02:05, 55.28it/s]

2026-09-09 18:27:35,899 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:35,915 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:35,938 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:35,955 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:35,971 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:35,987 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  69%|██████▉   | 15226/22132 [05:50<02:05, 55.18it/s]

2026-09-09 18:27:36,004 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:36,022 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:36,040 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:36,056 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:36,075 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:36,092 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  69%|██████▉   | 15232/22132 [05:50<02:03, 55.79it/s]

2026-09-09 18:27:36,108 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:36,125 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:36,143 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:36,158 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:36,175 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:36,193 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  69%|██████▉   | 15238/22132 [05:50<02:01, 56.86it/s]

2026-09-09 18:27:36,211 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:36,227 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:36,243 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:36,259 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:36,282 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:27:36,301 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  69%|██████▉   | 15244/22132 [05:50<02:02, 56.45it/s]

2026-09-09 18:27:36,325 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:27:36,353 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:27:36,373 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:36,389 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:36,405 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:36,422 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  69%|██████▉   | 15250/22132 [05:50<02:07, 54.09it/s]

2026-09-09 18:27:36,443 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:36,462 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:36,479 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:36,495 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:36,513 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:36,535 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  69%|██████▉   | 15256/22132 [05:50<02:07, 53.83it/s]

2026-09-09 18:27:36,561 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:27:36,586 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:27:36,616 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:27:36,634 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:36,651 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:36,669 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  69%|██████▉   | 15262/22132 [05:50<02:15, 50.71it/s]

2026-09-09 18:27:36,688 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:36,705 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:36,724 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:36,741 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:36,762 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:36,782 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  69%|██████▉   | 15268/22132 [05:50<02:13, 51.41it/s]

2026-09-09 18:27:36,800 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:36,823 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:27:36,844 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:36,864 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:36,886 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:36,907 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  69%|██████▉   | 15274/22132 [05:51<02:16, 50.34it/s]

2026-09-09 18:27:36,926 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:36,948 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:36,968 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:36,985 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:37,001 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:37,021 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  69%|██████▉   | 15280/22132 [05:51<02:14, 51.04it/s]

2026-09-09 18:27:37,043 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:37,063 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:37,081 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:37,098 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:37,116 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:37,132 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  69%|██████▉   | 15286/22132 [05:51<02:11, 51.88it/s]

2026-09-09 18:27:37,149 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:37,166 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:37,183 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:37,199 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:37,214 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:37,231 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:37,247 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  69%|██████▉   | 15293/22132 [05:51<02:05, 54.58it/s]

2026-09-09 18:27:37,265 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:37,283 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:37,300 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:37,316 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:37,332 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:37,351 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  69%|██████▉   | 15299/22132 [05:51<02:03, 55.51it/s]

2026-09-09 18:27:37,370 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:37,387 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:37,407 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:37,425 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:37,441 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:37,456 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  69%|██████▉   | 15305/22132 [05:51<02:02, 55.90it/s]

2026-09-09 18:27:37,473 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:37,490 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:37,506 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:37,521 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:37,538 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:37,556 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:37,572 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  69%|██████▉   | 15312/22132 [05:51<01:58, 57.34it/s]

2026-09-09 18:27:37,589 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:37,605 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:37,621 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:37,637 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:37,655 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:37,670 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:37,686 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  69%|██████▉   | 15319/22132 [05:51<01:56, 58.55it/s]

2026-09-09 18:27:37,704 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:37,720 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:37,737 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:37,753 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:37,770 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:37,789 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  69%|██████▉   | 15325/22132 [05:51<01:56, 58.49it/s]

2026-09-09 18:27:37,807 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:37,825 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:37,842 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:37,860 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:37,879 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:37,897 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  69%|██████▉   | 15331/22132 [05:52<01:58, 57.56it/s]

2026-09-09 18:27:37,916 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:37,937 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:37,954 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:37,970 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:37,985 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:38,005 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  69%|██████▉   | 15337/22132 [05:52<01:59, 57.03it/s]

2026-09-09 18:27:38,023 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:38,042 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:38,071 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:27:38,089 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:38,106 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:38,123 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  69%|██████▉   | 15343/22132 [05:52<02:03, 55.10it/s]

2026-09-09 18:27:38,140 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:38,155 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:38,171 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:38,187 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:38,203 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:38,218 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:38,235 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  69%|██████▉   | 15350/22132 [05:52<01:58, 57.32it/s]

2026-09-09 18:27:38,255 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:38,271 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:38,286 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:38,302 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:38,320 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:38,337 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  69%|██████▉   | 15356/22132 [05:52<01:57, 57.73it/s]

2026-09-09 18:27:38,354 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:38,372 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:38,388 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:38,407 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:38,423 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:38,439 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  69%|██████▉   | 15362/22132 [05:52<01:56, 57.97it/s]

2026-09-09 18:27:38,457 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:38,474 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:38,489 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:38,504 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:38,520 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:38,536 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:38,552 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  69%|██████▉   | 15369/22132 [05:52<01:54, 59.32it/s]

2026-09-09 18:27:38,570 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:38,588 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:38,606 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:38,628 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:38,644 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:38,663 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  69%|██████▉   | 15375/22132 [05:52<01:57, 57.69it/s]

2026-09-09 18:27:38,680 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:38,696 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:38,713 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:38,729 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:38,748 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:38,767 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  69%|██████▉   | 15381/22132 [05:52<01:57, 57.68it/s]

2026-09-09 18:27:38,784 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:38,800 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:38,817 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:38,832 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:38,850 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:38,879 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]

Indexing Records:  70%|██████▉   | 15387/22132 [05:53<01:59, 56.46it/s]

2026-09-09 18:27:38,898 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:38,914 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:38,930 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:38,947 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:38,964 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:38,979 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  70%|██████▉   | 15393/22132 [05:53<01:57, 57.39it/s]

2026-09-09 18:27:38,996 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:39,012 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:39,028 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:39,045 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:39,063 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:39,079 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:39,095 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  70%|██████▉   | 15400/22132 [05:53<01:55, 58.32it/s]

2026-09-09 18:27:39,119 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:27:39,136 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:39,154 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:39,170 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:39,187 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:39,204 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  70%|██████▉   | 15406/22132 [05:53<01:57, 57.35it/s]

2026-09-09 18:27:39,220 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:39,236 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:39,252 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:39,268 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:39,284 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:39,306 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  70%|██████▉   | 15412/22132 [05:53<01:56, 57.82it/s]

2026-09-09 18:27:39,326 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:39,342 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:39,358 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:39,376 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:39,395 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:39,411 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  70%|██████▉   | 15418/22132 [05:53<01:56, 57.58it/s]

2026-09-09 18:27:39,428 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:39,445 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:39,461 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:39,477 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:39,494 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:39,510 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:39,525 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  70%|██████▉   | 15425/22132 [05:53<01:54, 58.72it/s]

2026-09-09 18:27:39,544 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:39,561 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:39,576 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:39,593 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:39,608 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:39,624 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:39,644 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  70%|██████▉   | 15432/22132 [05:53<01:53, 58.79it/s]

2026-09-09 18:27:39,662 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:39,678 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:39,694 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:39,715 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:39,730 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:39,748 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  70%|██████▉   | 15438/22132 [05:53<01:54, 58.58it/s]

2026-09-09 18:27:39,764 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:39,781 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:39,798 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:39,817 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:39,834 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:39,850 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  70%|██████▉   | 15444/22132 [05:53<01:54, 58.63it/s]

2026-09-09 18:27:39,872 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:39,893 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:39,912 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:39,929 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:39,947 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:39,971 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  70%|██████▉   | 15450/22132 [05:54<02:00, 55.64it/s]

2026-09-09 18:27:39,989 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:40,008 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:40,025 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:40,043 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:40,061 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:40,077 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  70%|██████▉   | 15456/22132 [05:54<01:59, 55.85it/s]

2026-09-09 18:27:40,096 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:40,112 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:40,131 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:40,149 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:40,167 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:40,183 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  70%|██████▉   | 15462/22132 [05:54<01:58, 56.09it/s]

2026-09-09 18:27:40,201 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:40,218 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:40,233 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:40,253 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:40,269 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:40,285 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  70%|██████▉   | 15468/22132 [05:54<01:57, 56.95it/s]

2026-09-09 18:27:40,303 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:40,322 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:40,339 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:40,358 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:40,376 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:40,393 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  70%|██████▉   | 15474/22132 [05:54<01:57, 56.53it/s]

2026-09-09 18:27:40,411 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:40,428 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:40,445 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:40,461 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:40,479 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:40,497 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  70%|██████▉   | 15480/22132 [05:54<01:57, 56.83it/s]

2026-09-09 18:27:40,513 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:40,529 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:40,545 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:40,562 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:40,579 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:40,595 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:40,611 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  70%|██████▉   | 15487/22132 [05:54<01:54, 58.28it/s]

2026-09-09 18:27:40,629 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:40,646 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:40,666 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:40,684 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:40,702 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:40,719 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  70%|███████   | 15493/22132 [05:54<01:55, 57.42it/s]

2026-09-09 18:27:40,736 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:40,754 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:40,772 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:40,788 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:40,806 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:40,821 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  70%|███████   | 15499/22132 [05:54<01:54, 57.82it/s]

2026-09-09 18:27:40,838 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:40,854 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:40,870 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:40,886 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:40,903 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:40,918 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:40,933 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  70%|███████   | 15506/22132 [05:55<01:51, 59.27it/s]

2026-09-09 18:27:40,950 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:40,966 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:40,982 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:41,000 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:41,017 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:41,032 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:41,047 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  70%|███████   | 15513/22132 [05:55<01:50, 59.99it/s]

2026-09-09 18:27:41,064 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:41,079 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:41,095 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:41,112 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:41,129 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:41,148 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  70%|███████   | 15519/22132 [05:55<01:50, 59.87it/s]

2026-09-09 18:27:41,166 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:41,185 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:41,207 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:41,234 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:27:41,251 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:41,267 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  70%|███████   | 15525/22132 [05:55<01:56, 56.76it/s]

2026-09-09 18:27:41,284 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:41,301 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:41,317 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:41,335 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:41,351 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:41,367 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:41,385 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  70%|███████   | 15532/22132 [05:55<01:54, 57.62it/s]

2026-09-09 18:27:41,401 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:41,418 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:41,433 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:41,450 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:41,466 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:41,482 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:41,498 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  70%|███████   | 15539/22132 [05:55<01:51, 58.91it/s]

2026-09-09 18:27:41,514 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:41,531 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:41,546 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:41,563 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:41,578 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:41,593 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:41,609 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  70%|███████   | 15546/22132 [05:55<01:49, 60.15it/s]

2026-09-09 18:27:41,626 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:41,645 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:41,676 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:27:41,699 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:41,717 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:41,738 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:41,758 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  70%|███████   | 15553/22132 [05:55<01:58, 55.35it/s]

2026-09-09 18:27:41,776 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:41,793 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:41,809 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:41,827 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:41,847 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:41,869 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  70%|███████   | 15559/22132 [05:56<01:59, 55.01it/s]

2026-09-09 18:27:41,888 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:41,905 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:41,924 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:41,949 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:27:41,970 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:41,988 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  70%|███████   | 15565/22132 [05:56<02:02, 53.62it/s]

2026-09-09 18:27:42,013 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:27:42,037 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:27:42,058 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:42,080 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:42,097 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:42,115 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  70%|███████   | 15571/22132 [05:56<02:07, 51.62it/s]

2026-09-09 18:27:42,132 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:42,155 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:27:42,173 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:42,190 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:42,206 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:42,223 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  70%|███████   | 15577/22132 [05:56<02:04, 52.66it/s]

2026-09-09 18:27:42,242 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:42,263 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:42,280 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:42,297 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:42,315 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:42,332 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  70%|███████   | 15583/22132 [05:56<02:02, 53.32it/s]

2026-09-09 18:27:42,350 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:42,366 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:42,381 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:42,397 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:42,413 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:42,430 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:42,447 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  70%|███████   | 15590/22132 [05:56<01:57, 55.70it/s]

2026-09-09 18:27:42,465 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:42,481 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:42,497 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:42,514 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:42,530 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:42,545 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:42,564 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  70%|███████   | 15597/22132 [05:56<01:54, 56.95it/s]

2026-09-09 18:27:42,580 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:42,598 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:42,616 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:42,633 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:42,652 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:42,669 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  70%|███████   | 15603/22132 [05:56<01:54, 56.91it/s]

2026-09-09 18:27:42,686 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:42,712 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:27:42,732 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:42,750 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:42,766 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:42,784 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  71%|███████   | 15609/22132 [05:56<01:57, 55.45it/s]

2026-09-09 18:27:42,801 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:42,817 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:42,833 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:42,852 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:42,869 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:42,887 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  71%|███████   | 15615/22132 [05:57<01:55, 56.31it/s]

2026-09-09 18:27:42,904 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:42,921 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:42,937 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:42,954 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:42,973 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:42,991 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  71%|███████   | 15621/22132 [05:57<01:54, 56.71it/s]

2026-09-09 18:27:43,012 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:43,035 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:43,051 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:43,069 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:43,085 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:43,101 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  71%|███████   | 15627/22132 [05:57<01:56, 56.03it/s]

2026-09-09 18:27:43,118 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:43,138 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:43,153 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:43,170 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:43,186 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:43,203 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  71%|███████   | 15633/22132 [05:57<01:54, 56.83it/s]

2026-09-09 18:27:43,223 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:43,241 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:43,257 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:43,274 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:43,289 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:43,306 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  71%|███████   | 15639/22132 [05:57<01:53, 57.18it/s]

2026-09-09 18:27:43,323 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:43,341 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:43,356 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:43,372 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:43,388 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:43,404 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:43,421 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  71%|███████   | 15646/22132 [05:57<01:50, 58.45it/s]

2026-09-09 18:27:43,437 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:43,455 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:43,470 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:43,487 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:43,504 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:43,521 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:43,536 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  71%|███████   | 15653/22132 [05:57<01:49, 59.11it/s]

2026-09-09 18:27:43,553 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:43,570 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:43,587 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:43,603 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:43,620 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:43,636 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:43,656 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  71%|███████   | 15660/22132 [05:57<01:49, 58.99it/s]

2026-09-09 18:27:43,674 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:43,690 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:43,708 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:43,725 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:43,744 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:43,760 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  71%|███████   | 15666/22132 [05:57<01:50, 58.57it/s]

2026-09-09 18:27:43,777 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:43,793 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:43,809 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:43,825 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:43,841 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:43,856 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:43,872 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  71%|███████   | 15673/22132 [05:58<01:48, 59.73it/s]

2026-09-09 18:27:43,890 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:43,907 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:43,923 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:43,939 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:43,955 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:43,973 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  71%|███████   | 15679/22132 [05:58<01:48, 59.74it/s]

2026-09-09 18:27:43,990 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:44,007 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:44,025 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:44,041 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:44,057 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:44,074 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  71%|███████   | 15685/22132 [05:58<01:48, 59.59it/s]

2026-09-09 18:27:44,090 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:44,107 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:44,122 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:44,138 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:44,155 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:44,171 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:44,188 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  71%|███████   | 15692/22132 [05:58<01:47, 60.11it/s]

2026-09-09 18:27:44,206 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:44,222 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:44,237 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:44,253 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:44,273 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:44,291 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:44,306 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  71%|███████   | 15699/22132 [05:58<01:47, 59.86it/s]

2026-09-09 18:27:44,323 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:44,339 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:44,356 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:44,373 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:44,389 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:44,406 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:44,422 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  71%|███████   | 15706/22132 [05:58<01:46, 60.07it/s]

2026-09-09 18:27:44,439 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:44,456 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:44,472 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:44,489 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:44,506 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:44,523 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:44,540 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  71%|███████   | 15713/22132 [05:58<01:47, 59.78it/s]

2026-09-09 18:27:44,556 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:44,572 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:44,587 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:44,605 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:44,620 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:44,637 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:44,653 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  71%|███████   | 15720/22132 [05:58<01:45, 60.51it/s]

2026-09-09 18:27:44,669 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:44,690 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:44,705 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:44,723 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:44,741 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:44,757 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:44,773 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  71%|███████   | 15727/22132 [05:58<01:47, 59.71it/s]

2026-09-09 18:27:44,792 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:44,846 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.053s]
2026-09-09 18:27:44,861 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:44,878 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:44,893 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:44,910 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  71%|███████   | 15733/22132 [05:59<01:57, 54.44it/s]

2026-09-09 18:27:44,927 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:44,942 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:44,958 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:44,973 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:44,990 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:45,008 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:45,028 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  71%|███████   | 15740/22132 [05:59<01:54, 55.78it/s]

2026-09-09 18:27:45,047 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:45,065 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:45,083 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:45,099 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:45,120 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:45,141 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  71%|███████   | 15746/22132 [05:59<01:55, 55.14it/s]

2026-09-09 18:27:45,158 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:45,176 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:45,194 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:45,213 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:45,231 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:45,247 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  71%|███████   | 15752/22132 [05:59<01:54, 55.52it/s]

2026-09-09 18:27:45,264 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:45,281 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:45,297 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:45,312 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:45,328 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:45,344 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:45,360 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  71%|███████   | 15759/22132 [05:59<01:50, 57.46it/s]

2026-09-09 18:27:45,376 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:45,393 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:45,412 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:45,429 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:45,447 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:45,464 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  71%|███████   | 15765/22132 [05:59<01:50, 57.45it/s]

2026-09-09 18:27:45,482 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:45,498 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:45,515 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:45,531 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:45,549 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:45,568 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  71%|███████▏  | 15771/22132 [05:59<01:50, 57.58it/s]

2026-09-09 18:27:45,585 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:45,600 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:45,618 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:45,635 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:45,651 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:45,666 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:45,683 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  71%|███████▏  | 15778/22132 [05:59<01:48, 58.54it/s]

2026-09-09 18:27:45,700 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:45,718 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:45,735 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:45,751 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:45,767 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:45,782 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:45,798 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  71%|███████▏  | 15785/22132 [05:59<01:47, 59.24it/s]

2026-09-09 18:27:45,815 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:45,830 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:45,845 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:45,861 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:45,878 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:45,896 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:45,911 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  71%|███████▏  | 15792/22132 [06:00<01:45, 60.01it/s]

2026-09-09 18:27:45,932 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:45,949 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:45,966 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:45,984 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:46,004 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:46,025 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:46,052 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]

Indexing Records:  71%|███████▏  | 15799/22132 [06:00<01:52, 56.49it/s]

2026-09-09 18:27:46,072 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:46,089 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:46,108 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:46,125 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:46,142 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:46,157 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  71%|███████▏  | 15805/22132 [06:00<01:51, 56.58it/s]

2026-09-09 18:27:46,176 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:46,192 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:46,207 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:46,223 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:46,240 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:46,257 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  71%|███████▏  | 15811/22132 [06:00<01:49, 57.49it/s]

2026-09-09 18:27:46,276 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:46,291 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:46,315 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:27:46,332 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:46,348 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:46,363 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  71%|███████▏  | 15817/22132 [06:00<01:50, 57.30it/s]

2026-09-09 18:27:46,380 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:46,397 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:46,413 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:46,429 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:46,446 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:46,461 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:46,479 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  71%|███████▏  | 15824/22132 [06:00<01:48, 58.29it/s]

2026-09-09 18:27:46,497 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:46,513 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:46,529 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:46,546 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:46,562 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:46,579 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  72%|███████▏  | 15830/22132 [06:00<01:47, 58.66it/s]

2026-09-09 18:27:46,597 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:46,612 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:46,628 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:46,645 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:46,660 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:46,677 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:46,694 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  72%|███████▏  | 15837/22132 [06:00<01:45, 59.45it/s]

2026-09-09 18:27:46,710 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:46,726 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:46,743 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:46,759 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:46,775 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:46,790 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:46,809 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  72%|███████▏  | 15844/22132 [06:00<01:44, 59.94it/s]

2026-09-09 18:27:46,827 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:46,844 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:46,861 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:46,876 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:46,894 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:46,912 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  72%|███████▏  | 15850/22132 [06:01<01:45, 59.30it/s]

2026-09-09 18:27:46,929 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:46,945 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:46,963 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:46,982 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:47,000 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:47,018 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  72%|███████▏  | 15856/22132 [06:01<01:47, 58.63it/s]

2026-09-09 18:27:47,037 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:47,054 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:47,071 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:47,087 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:47,104 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:47,120 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  72%|███████▏  | 15862/22132 [06:01<01:46, 58.70it/s]

2026-09-09 18:27:47,137 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:47,153 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:47,168 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:47,183 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:47,198 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:47,214 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:47,230 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  72%|███████▏  | 15869/22132 [06:01<01:44, 60.14it/s]

2026-09-09 18:27:47,248 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:47,264 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:47,282 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:47,297 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:47,313 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:47,330 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:47,346 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  72%|███████▏  | 15876/22132 [06:01<01:43, 60.27it/s]

2026-09-09 18:27:47,363 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:47,379 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:47,395 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:47,411 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:47,429 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:47,447 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:47,465 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  72%|███████▏  | 15883/22132 [06:01<01:44, 59.73it/s]

2026-09-09 18:27:47,483 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:47,499 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:47,515 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:47,531 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:47,547 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:47,563 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:47,578 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  72%|███████▏  | 15890/22132 [06:01<01:43, 60.36it/s]

2026-09-09 18:27:47,597 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:47,616 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:47,633 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:47,651 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:47,669 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:47,685 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:47,701 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  72%|███████▏  | 15897/22132 [06:01<01:45, 59.27it/s]

2026-09-09 18:27:47,718 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:47,735 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:47,751 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:47,767 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:47,783 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:47,800 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:47,817 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  72%|███████▏  | 15904/22132 [06:01<01:44, 59.60it/s]

2026-09-09 18:27:47,834 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:47,851 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:47,867 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:47,882 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:47,900 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:47,917 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:47,935 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  72%|███████▏  | 15911/22132 [06:02<01:44, 59.58it/s]

2026-09-09 18:27:47,953 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:47,975 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:47,992 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:48,008 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:48,025 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:48,046 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  72%|███████▏  | 15917/22132 [06:02<01:47, 57.94it/s]

2026-09-09 18:27:48,065 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:48,087 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:48,110 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:48,127 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:48,147 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:48,167 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  72%|███████▏  | 15923/22132 [06:02<01:52, 55.38it/s]

2026-09-09 18:27:48,187 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:48,204 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:48,222 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:48,240 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:48,263 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:48,287 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  72%|███████▏  | 15929/22132 [06:02<01:55, 53.72it/s]

2026-09-09 18:27:48,307 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:48,326 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:48,342 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:48,359 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:48,375 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:48,393 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  72%|███████▏  | 15935/22132 [06:02<01:53, 54.47it/s]

2026-09-09 18:27:48,415 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:48,434 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:48,453 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:48,469 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:48,486 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:48,502 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  72%|███████▏  | 15941/22132 [06:02<01:53, 54.72it/s]

2026-09-09 18:27:48,523 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:48,545 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:48,564 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:48,585 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:48,602 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:48,621 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  72%|███████▏  | 15947/22132 [06:02<01:55, 53.39it/s]

2026-09-09 18:27:48,641 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:48,666 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:27:48,683 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:48,701 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:48,718 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:48,737 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  72%|███████▏  | 15953/22132 [06:02<01:56, 52.91it/s]

2026-09-09 18:27:48,768 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:27:48,790 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:48,809 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:48,831 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:48,851 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:48,872 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  72%|███████▏  | 15959/22132 [06:03<02:03, 49.99it/s]

2026-09-09 18:27:48,896 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:27:48,917 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:48,938 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:48,955 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:48,972 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:48,989 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  72%|███████▏  | 15965/22132 [06:03<02:02, 50.44it/s]

2026-09-09 18:27:49,008 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:49,026 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:49,042 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:49,058 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:49,079 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:49,096 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  72%|███████▏  | 15971/22132 [06:03<01:58, 52.00it/s]

2026-09-09 18:27:49,113 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:49,132 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:49,148 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:49,165 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:49,182 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:49,198 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  72%|███████▏  | 15977/22132 [06:03<01:54, 53.81it/s]

2026-09-09 18:27:49,214 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:49,233 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:49,249 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:49,266 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:49,284 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:49,300 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  72%|███████▏  | 15983/22132 [06:03<01:51, 55.25it/s]

2026-09-09 18:27:49,319 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:49,335 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:49,352 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:49,368 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:49,386 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:49,402 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  72%|███████▏  | 15989/22132 [06:03<01:49, 56.34it/s]

2026-09-09 18:27:49,419 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:49,434 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:49,453 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:49,470 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:49,485 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:49,504 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  72%|███████▏  | 15995/22132 [06:03<01:47, 56.97it/s]

2026-09-09 18:27:49,522 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:49,537 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:49,553 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:49,569 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:49,586 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:49,603 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:49,620 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  72%|███████▏  | 16002/22132 [06:03<01:45, 58.14it/s]

2026-09-09 18:27:49,638 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:49,656 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:49,671 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:49,688 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:49,705 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:49,729 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  72%|███████▏  | 16008/22132 [06:03<01:47, 57.16it/s]

2026-09-09 18:27:49,747 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:49,765 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:49,782 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:49,798 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:49,815 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:49,831 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  72%|███████▏  | 16014/22132 [06:03<01:46, 57.68it/s]

2026-09-09 18:27:49,847 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:49,865 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:49,881 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:49,897 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:49,913 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:49,932 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  72%|███████▏  | 16020/22132 [06:04<01:45, 58.14it/s]

2026-09-09 18:27:49,949 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:49,967 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:49,983 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:50,000 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:50,023 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:27:50,041 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  72%|███████▏  | 16026/22132 [06:04<01:46, 57.10it/s]

2026-09-09 18:27:50,058 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:50,075 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:50,091 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:50,110 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:50,129 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:50,150 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  72%|███████▏  | 16032/22132 [06:04<01:47, 56.55it/s]

2026-09-09 18:27:50,172 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:50,192 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:50,209 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:50,227 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:50,244 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:50,261 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  72%|███████▏  | 16038/22132 [06:04<01:49, 55.77it/s]

2026-09-09 18:27:50,285 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:50,305 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:50,324 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:50,341 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:50,358 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:50,378 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  72%|███████▏  | 16044/22132 [06:04<01:52, 54.36it/s]

2026-09-09 18:27:50,397 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:50,414 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:50,432 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:50,451 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:50,467 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:50,484 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  73%|███████▎  | 16050/22132 [06:04<01:50, 54.89it/s]

2026-09-09 18:27:50,506 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:50,524 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:50,541 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:50,559 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:50,575 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:50,592 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  73%|███████▎  | 16056/22132 [06:04<01:50, 55.18it/s]

2026-09-09 18:27:50,612 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:50,631 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:50,647 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:50,664 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:50,682 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:50,699 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  73%|███████▎  | 16062/22132 [06:04<01:49, 55.52it/s]

2026-09-09 18:27:50,715 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:50,736 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:50,752 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:50,770 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:50,787 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:50,804 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  73%|███████▎  | 16068/22132 [06:04<01:48, 55.86it/s]

2026-09-09 18:27:50,823 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:50,843 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:50,860 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:50,878 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:50,901 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:27:50,921 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  73%|███████▎  | 16074/22132 [06:05<01:51, 54.44it/s]

2026-09-09 18:27:50,942 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:50,968 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:27:50,993 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:27:51,021 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:27:51,044 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:27:51,067 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  73%|███████▎  | 16080/22132 [06:05<02:01, 49.66it/s]

2026-09-09 18:27:51,087 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:51,107 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:51,129 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:51,147 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:51,184 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.036s]
2026-09-09 18:27:51,205 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  73%|███████▎  | 16086/22132 [06:05<02:06, 47.63it/s]

2026-09-09 18:27:51,226 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:51,248 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:51,269 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:51,291 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:51,309 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  73%|███████▎  | 16091/22132 [06:05<02:06, 47.68it/s]

2026-09-09 18:27:51,331 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:51,350 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:51,371 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:51,390 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:51,409 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:51,430 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  73%|███████▎  | 16097/22132 [06:05<02:04, 48.30it/s]

2026-09-09 18:27:51,454 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:27:51,477 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:51,499 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:27:51,515 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:51,531 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  73%|███████▎  | 16102/22132 [06:05<02:04, 48.59it/s]

2026-09-09 18:27:51,555 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:27:51,571 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:51,587 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:51,602 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:51,620 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:51,638 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  73%|███████▎  | 16108/22132 [06:05<01:58, 50.82it/s]

2026-09-09 18:27:51,655 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:51,672 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:51,689 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:51,705 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:51,721 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:51,738 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  73%|███████▎  | 16114/22132 [06:05<01:52, 53.32it/s]

2026-09-09 18:27:51,755 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:51,774 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:51,795 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:51,811 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:51,828 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:51,844 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  73%|███████▎  | 16120/22132 [06:05<01:50, 54.20it/s]

2026-09-09 18:27:51,861 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:51,880 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:51,899 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:51,915 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:51,931 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:51,948 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  73%|███████▎  | 16126/22132 [06:06<01:48, 55.23it/s]

2026-09-09 18:27:51,966 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:51,982 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:51,999 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:52,020 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:52,036 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:52,058 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  73%|███████▎  | 16132/22132 [06:06<01:49, 55.04it/s]

2026-09-09 18:27:52,079 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:52,097 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:52,115 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:52,134 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:52,153 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:52,177 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  73%|███████▎  | 16138/22132 [06:06<01:51, 53.53it/s]

2026-09-09 18:27:52,199 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:52,215 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:52,232 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:52,253 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:52,273 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:52,291 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  73%|███████▎  | 16144/22132 [06:06<01:52, 53.31it/s]

2026-09-09 18:27:52,308 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:52,327 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:52,346 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:52,367 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:52,386 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:52,404 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  73%|███████▎  | 16150/22132 [06:06<01:52, 53.23it/s]

2026-09-09 18:27:52,421 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:52,437 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:52,456 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:52,472 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:52,489 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:52,505 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  73%|███████▎  | 16156/22132 [06:06<01:48, 54.92it/s]

2026-09-09 18:27:52,523 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:52,542 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:52,559 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:52,576 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:52,592 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:52,609 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  73%|███████▎  | 16162/22132 [06:06<01:47, 55.73it/s]

2026-09-09 18:27:52,627 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:52,642 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:52,659 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:52,676 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:52,692 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:52,707 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:52,723 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  73%|███████▎  | 16169/22132 [06:06<01:43, 57.60it/s]

2026-09-09 18:27:52,739 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:52,755 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:52,771 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:52,787 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:52,805 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:52,820 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:52,837 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  73%|███████▎  | 16176/22132 [06:06<01:41, 58.77it/s]

2026-09-09 18:27:52,856 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:52,874 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:52,892 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:52,911 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:52,935 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:27:52,959 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  73%|███████▎  | 16182/22132 [06:07<01:46, 55.69it/s]

2026-09-09 18:27:52,979 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:52,997 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:53,021 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:27:53,041 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:53,061 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:53,081 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  73%|███████▎  | 16188/22132 [06:07<01:50, 53.62it/s]

2026-09-09 18:27:53,101 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:53,117 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:53,133 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:53,151 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:53,172 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:53,188 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  73%|███████▎  | 16194/22132 [06:07<01:49, 54.26it/s]

2026-09-09 18:27:53,206 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:53,223 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:53,240 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:53,256 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:53,272 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:53,291 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  73%|███████▎  | 16200/22132 [06:07<01:46, 55.48it/s]

2026-09-09 18:27:53,309 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:53,324 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:53,340 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:53,357 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:53,374 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:53,390 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:53,408 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  73%|███████▎  | 16207/22132 [06:07<01:44, 56.74it/s]

2026-09-09 18:27:53,425 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:53,441 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:53,457 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:53,477 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:53,494 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:53,510 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  73%|███████▎  | 16213/22132 [06:07<01:43, 57.43it/s]

2026-09-09 18:27:53,526 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:53,542 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:53,559 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:53,576 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:53,596 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:53,614 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  73%|███████▎  | 16219/22132 [06:07<01:42, 57.49it/s]

2026-09-09 18:27:53,631 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:53,647 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:53,663 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:53,679 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:53,695 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:53,711 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:53,729 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  73%|███████▎  | 16226/22132 [06:07<01:41, 58.46it/s]

2026-09-09 18:27:53,748 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:53,766 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:53,786 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:53,803 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:53,820 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:53,837 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  73%|███████▎  | 16232/22132 [06:07<01:42, 57.64it/s]

2026-09-09 18:27:53,855 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:53,871 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:53,891 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:53,906 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:53,922 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:53,939 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  73%|███████▎  | 16238/22132 [06:08<01:41, 57.94it/s]

2026-09-09 18:27:53,956 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:53,971 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:53,987 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:54,004 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:54,020 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:54,036 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:54,054 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  73%|███████▎  | 16245/22132 [06:08<01:39, 58.92it/s]

2026-09-09 18:27:54,071 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:54,089 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:54,107 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:54,123 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:54,139 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:54,155 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  73%|███████▎  | 16251/22132 [06:08<01:39, 59.07it/s]

2026-09-09 18:27:54,172 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:54,190 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:54,208 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:54,224 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:54,241 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:54,259 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  73%|███████▎  | 16257/22132 [06:08<01:40, 58.70it/s]

2026-09-09 18:27:54,276 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:54,291 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:54,309 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:54,325 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:54,342 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:54,359 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  73%|███████▎  | 16263/22132 [06:08<01:39, 59.06it/s]

2026-09-09 18:27:54,378 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:54,397 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:54,415 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:54,434 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:54,451 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:54,467 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  74%|███████▎  | 16269/22132 [06:08<01:41, 58.00it/s]

2026-09-09 18:27:54,485 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:54,500 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:54,517 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:54,534 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:54,552 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:54,568 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  74%|███████▎  | 16275/22132 [06:08<01:40, 58.39it/s]

2026-09-09 18:27:54,584 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:54,601 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:54,617 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:54,634 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:54,652 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:54,667 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:54,683 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  74%|███████▎  | 16282/22132 [06:08<01:38, 59.20it/s]

2026-09-09 18:27:54,702 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:54,719 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:54,734 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:54,751 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:54,768 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:54,783 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  74%|███████▎  | 16288/22132 [06:08<01:38, 59.25it/s]

2026-09-09 18:27:54,801 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:54,818 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:54,834 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:54,854 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:54,871 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:54,888 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  74%|███████▎  | 16294/22132 [06:09<01:39, 58.77it/s]

2026-09-09 18:27:54,908 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:54,925 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:54,942 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:54,959 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:54,981 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:55,005 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  74%|███████▎  | 16300/22132 [06:09<01:43, 56.32it/s]

2026-09-09 18:27:55,035 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:27:55,053 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:55,109 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.055s]
2026-09-09 18:27:55,129 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:55,150 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:55,170 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  74%|███████▎  | 16306/22132 [06:09<02:00, 48.42it/s]

2026-09-09 18:27:55,190 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:55,208 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:55,230 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:55,248 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:55,320 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.071s]
2026-09-09 18:27:55,341 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  74%|███████▎  | 16312/22132 [06:09<02:13, 43.50it/s]

2026-09-09 18:27:55,360 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:55,379 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:55,397 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:55,414 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:55,435 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:55,455 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  74%|███████▎  | 16318/22132 [06:09<02:06, 45.95it/s]

2026-09-09 18:27:55,475 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:55,496 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:55,514 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:55,532 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:55,550 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:55,569 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  74%|███████▍  | 16324/22132 [06:09<02:01, 47.75it/s]

2026-09-09 18:27:55,588 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:55,609 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:55,628 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:55,646 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:55,665 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:55,684 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  74%|███████▍  | 16330/22132 [06:09<01:58, 48.91it/s]

2026-09-09 18:27:55,704 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:55,729 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:27:55,746 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:55,765 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:55,783 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:55,801 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  74%|███████▍  | 16336/22132 [06:09<01:56, 49.59it/s]

2026-09-09 18:27:55,826 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:27:55,845 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:55,864 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:55,885 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:55,904 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:55,924 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  74%|███████▍  | 16342/22132 [06:10<01:57, 49.38it/s]

2026-09-09 18:27:55,943 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:55,963 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:55,982 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:56,004 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:56,024 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:56,044 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  74%|███████▍  | 16348/22132 [06:10<01:56, 49.62it/s]

2026-09-09 18:27:56,160 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.114s]
2026-09-09 18:27:56,185 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:27:56,203 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:56,229 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:27:56,246 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:56,263 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  74%|███████▍  | 16354/22132 [06:10<02:24, 39.90it/s]

2026-09-09 18:27:56,282 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:56,302 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:56,320 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:56,341 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:56,364 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  74%|███████▍  | 16359/22132 [06:10<02:17, 42.01it/s]

2026-09-09 18:27:56,384 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:56,401 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:56,419 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:56,437 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:56,458 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:56,478 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  74%|███████▍  | 16365/22132 [06:10<02:08, 44.86it/s]

2026-09-09 18:27:56,498 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:56,516 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:56,534 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:56,552 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:56,571 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:56,586 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  74%|███████▍  | 16371/22132 [06:10<02:00, 47.73it/s]

2026-09-09 18:27:56,604 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:56,619 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:56,634 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:56,650 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:56,668 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:56,685 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:56,700 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  74%|███████▍  | 16378/22132 [06:10<01:51, 51.51it/s]

2026-09-09 18:27:56,717 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:56,734 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:56,752 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:56,768 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:56,784 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:56,800 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:56,815 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  74%|███████▍  | 16385/22132 [06:10<01:45, 54.33it/s]

2026-09-09 18:27:56,832 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:56,848 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:56,864 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:56,879 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:56,896 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:56,911 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:56,927 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  74%|███████▍  | 16392/22132 [06:11<01:41, 56.68it/s]

2026-09-09 18:27:56,946 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:56,965 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:56,983 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:56,999 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:57,019 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:57,039 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  74%|███████▍  | 16398/22132 [06:11<01:42, 55.68it/s]

2026-09-09 18:27:57,062 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:57,080 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:57,097 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:57,120 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:27:57,141 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:57,158 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  74%|███████▍  | 16404/22132 [06:11<01:45, 54.07it/s]

2026-09-09 18:27:57,175 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:57,192 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:57,207 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:57,223 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:57,240 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:57,255 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:57,273 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  74%|███████▍  | 16411/22132 [06:11<01:41, 56.16it/s]

2026-09-09 18:27:57,292 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:57,309 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:57,325 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:57,341 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:57,357 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:57,372 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:57,388 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  74%|███████▍  | 16418/22132 [06:11<01:39, 57.59it/s]

2026-09-09 18:27:57,404 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:57,421 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:57,436 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:57,453 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:57,471 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:57,487 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:57,503 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  74%|███████▍  | 16425/22132 [06:11<01:37, 58.60it/s]

2026-09-09 18:27:57,521 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:57,540 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:57,556 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:57,573 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:57,588 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:57,604 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  74%|███████▍  | 16431/22132 [06:11<01:37, 58.69it/s]

2026-09-09 18:27:57,620 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:57,636 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:57,653 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:57,672 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:57,692 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:57,707 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  74%|███████▍  | 16437/22132 [06:11<01:37, 58.66it/s]

2026-09-09 18:27:57,726 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:57,743 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:57,759 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:57,776 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:57,795 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:57,818 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  74%|███████▍  | 16443/22132 [06:11<01:39, 57.27it/s]

2026-09-09 18:27:57,835 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:57,855 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:57,873 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:57,890 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:57,910 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:57,927 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  74%|███████▍  | 16449/22132 [06:12<01:40, 56.61it/s]

2026-09-09 18:27:57,944 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:57,960 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:57,975 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:57,993 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:58,012 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:58,030 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  74%|███████▍  | 16455/22132 [06:12<01:39, 57.07it/s]

2026-09-09 18:27:58,046 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:58,065 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:58,081 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:58,100 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:58,120 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:58,142 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  74%|███████▍  | 16461/22132 [06:12<01:41, 55.97it/s]

2026-09-09 18:27:58,164 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:58,185 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:27:58,201 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:58,220 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:58,239 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:58,259 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  74%|███████▍  | 16467/22132 [06:12<01:43, 54.51it/s]

2026-09-09 18:27:58,286 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:27:58,307 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:58,336 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:27:58,363 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:27:58,385 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:58,403 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  74%|███████▍  | 16473/22132 [06:12<01:53, 49.91it/s]

2026-09-09 18:27:58,422 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:58,441 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:58,464 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:27:58,485 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:58,501 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:58,518 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  74%|███████▍  | 16479/22132 [06:12<01:51, 50.50it/s]

2026-09-09 18:27:58,535 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:58,553 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:58,569 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:58,587 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:58,606 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:58,629 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  74%|███████▍  | 16485/22132 [06:12<01:49, 51.63it/s]

2026-09-09 18:27:58,645 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:58,660 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:58,677 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:58,692 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:58,708 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:58,724 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:58,742 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  75%|███████▍  | 16492/22132 [06:12<01:43, 54.62it/s]

2026-09-09 18:27:58,758 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:58,776 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:58,792 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:58,809 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:58,826 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:58,845 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  75%|███████▍  | 16498/22132 [06:12<01:41, 55.65it/s]

2026-09-09 18:27:58,862 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:58,878 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:58,893 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:58,909 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:58,926 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:58,941 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:58,957 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  75%|███████▍  | 16505/22132 [06:13<01:37, 57.58it/s]

2026-09-09 18:27:58,975 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:58,994 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:59,010 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:59,025 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:59,041 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:59,057 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  75%|███████▍  | 16511/22132 [06:13<01:36, 58.25it/s]

2026-09-09 18:27:59,078 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:27:59,097 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:59,119 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:27:59,138 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:59,156 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:59,173 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  75%|███████▍  | 16517/22132 [06:13<01:39, 56.28it/s]

2026-09-09 18:27:59,192 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:59,207 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:59,222 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:59,239 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:59,254 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:59,269 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:59,289 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  75%|███████▍  | 16524/22132 [06:13<01:37, 57.56it/s]

2026-09-09 18:27:59,308 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:27:59,324 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:59,340 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:59,356 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:59,371 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:59,387 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:59,403 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  75%|███████▍  | 16531/22132 [06:13<01:35, 58.62it/s]

2026-09-09 18:27:59,421 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:59,436 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:59,453 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:59,469 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:59,484 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:59,503 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:59,519 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  75%|███████▍  | 16538/22132 [06:13<01:34, 59.22it/s]

2026-09-09 18:27:59,536 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:59,552 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:59,568 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:59,584 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:59,601 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:59,616 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:59,633 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  75%|███████▍  | 16545/22132 [06:13<01:33, 59.93it/s]

2026-09-09 18:27:59,649 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:59,664 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:59,679 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:59,695 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:59,710 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:59,726 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:59,741 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  75%|███████▍  | 16552/22132 [06:13<01:31, 61.29it/s]

2026-09-09 18:27:59,758 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:59,773 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:59,790 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:59,808 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:59,825 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:59,841 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:59,858 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  75%|███████▍  | 16559/22132 [06:13<01:31, 60.83it/s]

2026-09-09 18:27:59,875 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:59,891 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:59,909 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:27:59,926 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:27:59,941 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:27:59,959 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:27:59,979 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  75%|███████▍  | 16566/22132 [06:14<01:33, 59.84it/s]

2026-09-09 18:27:59,997 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:00,109 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.111s]
2026-09-09 18:28:00,169 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.060s]
2026-09-09 18:28:00,200 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:28:00,235 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]
2026-09-09 18:28:00,257 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  75%|███████▍  | 16572/22132 [06:14<02:17, 40.48it/s]

2026-09-09 18:28:00,280 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:00,303 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:00,325 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:00,358 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:28:00,382 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  75%|███████▍  | 16577/22132 [06:14<02:17, 40.33it/s]

2026-09-09 18:28:00,409 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:28:00,432 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:00,466 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]
2026-09-09 18:28:00,497 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:28:00,524 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]

Indexing Records:  75%|███████▍  | 16582/22132 [06:14<02:22, 38.93it/s]

2026-09-09 18:28:00,556 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:28:00,577 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:00,601 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:00,621 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:00,640 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  75%|███████▍  | 16587/22132 [06:14<02:18, 39.97it/s]

2026-09-09 18:28:00,661 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:00,677 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:00,694 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:00,710 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:00,727 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:00,746 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  75%|███████▍  | 16593/22132 [06:14<02:05, 44.00it/s]

2026-09-09 18:28:00,766 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:00,782 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:00,799 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:00,818 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:00,835 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:00,853 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  75%|███████▌  | 16599/22132 [06:14<01:57, 47.18it/s]

2026-09-09 18:28:00,873 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:00,891 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:00,909 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:00,926 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:00,947 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:00,964 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  75%|███████▌  | 16605/22132 [06:15<01:52, 49.08it/s]

2026-09-09 18:28:00,985 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:01,005 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:01,031 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:28:01,050 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:01,071 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:01,093 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  75%|███████▌  | 16611/22132 [06:15<01:54, 48.33it/s]

2026-09-09 18:28:01,114 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:01,165 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.050s]
2026-09-09 18:28:01,202 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]
2026-09-09 18:28:01,234 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:28:01,273 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.037s]

Indexing Records:  75%|███████▌  | 16616/22132 [06:15<02:16, 40.36it/s]

2026-09-09 18:28:01,309 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]
2026-09-09 18:28:01,346 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.037s]
2026-09-09 18:28:01,398 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.051s]
2026-09-09 18:28:01,425 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:28:01,525 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.099s]

Indexing Records:  75%|███████▌  | 16621/22132 [06:15<02:55, 31.37it/s]

2026-09-09 18:28:01,675 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.147s]
2026-09-09 18:28:01,773 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.097s]
2026-09-09 18:28:01,832 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.058s]
2026-09-09 18:28:02,031 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.197s]

Indexing Records:  75%|███████▌  | 16625/22132 [06:16<05:00, 18.34it/s]

2026-09-09 18:28:02,170 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.136s]
2026-09-09 18:28:02,286 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.115s]
2026-09-09 18:28:02,438 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.151s]

Indexing Records:  75%|███████▌  | 16628/22132 [06:16<06:31, 14.06it/s]

2026-09-09 18:28:02,561 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.121s]
2026-09-09 18:28:02,630 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.068s]
2026-09-09 18:28:02,697 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.065s]

Indexing Records:  75%|███████▌  | 16631/22132 [06:16<06:50, 13.41it/s]

2026-09-09 18:28:02,733 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]
2026-09-09 18:28:02,787 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.053s]
2026-09-09 18:28:02,859 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.070s]

Indexing Records:  75%|███████▌  | 16634/22132 [06:16<06:22, 14.39it/s]

2026-09-09 18:28:02,920 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.059s]
2026-09-09 18:28:02,994 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.073s]

Indexing Records:  75%|███████▌  | 16636/22132 [06:17<06:20, 14.45it/s]

2026-09-09 18:28:03,046 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.049s]
2026-09-09 18:28:03,113 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.066s]

Indexing Records:  75%|███████▌  | 16638/22132 [06:17<06:08, 14.91it/s]

2026-09-09 18:28:03,198 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.083s]
2026-09-09 18:28:03,274 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.074s]

Indexing Records:  75%|███████▌  | 16640/22132 [06:17<06:25, 14.24it/s]

2026-09-09 18:28:03,329 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.053s]
2026-09-09 18:28:03,364 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]
2026-09-09 18:28:03,399 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]

Indexing Records:  75%|███████▌  | 16643/22132 [06:17<05:33, 16.47it/s]

2026-09-09 18:28:03,436 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.036s]
2026-09-09 18:28:03,468 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:28:03,514 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.045s]

Indexing Records:  75%|███████▌  | 16646/22132 [06:17<04:53, 18.69it/s]

2026-09-09 18:28:03,568 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.052s]
2026-09-09 18:28:03,601 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:28:03,651 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.048s]

Indexing Records:  75%|███████▌  | 16649/22132 [06:17<04:39, 19.61it/s]

2026-09-09 18:28:03,687 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]
2026-09-09 18:28:03,775 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.086s]
2026-09-09 18:28:03,800 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  75%|███████▌  | 16652/22132 [06:17<04:37, 19.76it/s]

2026-09-09 18:28:03,824 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:03,851 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:28:03,875 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:28:03,894 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:03,921 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]

Indexing Records:  75%|███████▌  | 16657/22132 [06:18<03:35, 25.36it/s]

2026-09-09 18:28:03,941 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:03,959 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:03,980 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:04,000 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:04,019 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:04,039 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  75%|███████▌  | 16663/22132 [06:18<02:49, 32.21it/s]

2026-09-09 18:28:04,066 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:28:04,085 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:04,111 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:28:04,134 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:04,154 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  75%|███████▌  | 16668/22132 [06:18<02:35, 35.23it/s]

2026-09-09 18:28:04,193 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.037s]
2026-09-09 18:28:04,212 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:04,236 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:04,263 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]

Indexing Records:  75%|███████▌  | 16672/22132 [06:18<02:33, 35.67it/s]

2026-09-09 18:28:04,284 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:04,304 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:04,346 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.040s]
2026-09-09 18:28:04,383 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.036s]

Indexing Records:  75%|███████▌  | 16676/22132 [06:18<02:36, 34.92it/s]

2026-09-09 18:28:04,430 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.045s]
2026-09-09 18:28:04,518 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.087s]
2026-09-09 18:28:04,553 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]
2026-09-09 18:28:04,585 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]

Indexing Records:  75%|███████▌  | 16680/22132 [06:18<03:10, 28.65it/s]

2026-09-09 18:28:04,605 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:04,627 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:04,655 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:28:04,683 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:28:04,731 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.048s]

Indexing Records:  75%|███████▌  | 16685/22132 [06:18<02:59, 30.31it/s]

2026-09-09 18:28:04,758 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:28:04,787 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:28:04,808 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:04,850 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.041s]

Indexing Records:  75%|███████▌  | 16689/22132 [06:18<02:54, 31.16it/s]

2026-09-09 18:28:04,877 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:28:04,927 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.048s]
2026-09-09 18:28:04,957 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:28:04,985 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]

Indexing Records:  75%|███████▌  | 16693/22132 [06:19<02:57, 30.73it/s]

2026-09-09 18:28:05,027 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.040s]
2026-09-09 18:28:05,072 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.044s]
2026-09-09 18:28:05,108 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]
2026-09-09 18:28:05,150 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.041s]

Indexing Records:  75%|███████▌  | 16697/22132 [06:19<03:10, 28.51it/s]

2026-09-09 18:28:05,184 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:28:05,212 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:28:05,240 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:28:05,261 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  75%|███████▌  | 16701/22132 [06:19<02:58, 30.36it/s]

2026-09-09 18:28:05,291 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:28:05,310 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:05,329 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:05,350 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:05,386 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]

Indexing Records:  75%|███████▌  | 16706/22132 [06:19<02:43, 33.14it/s]

2026-09-09 18:28:05,411 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:28:05,432 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:05,452 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:05,479 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:28:05,513 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]

Indexing Records:  76%|███████▌  | 16711/22132 [06:19<02:35, 34.96it/s]

2026-09-09 18:28:05,537 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:05,556 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:05,579 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:05,600 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:05,622 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  76%|███████▌  | 16716/22132 [06:19<02:23, 37.82it/s]

2026-09-09 18:28:05,642 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:05,664 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:05,690 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:28:05,717 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:28:05,745 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]

Indexing Records:  76%|███████▌  | 16721/22132 [06:19<02:19, 38.70it/s]

2026-09-09 18:28:05,765 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:05,785 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:05,807 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:05,828 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:05,852 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  76%|███████▌  | 16726/22132 [06:19<02:12, 40.79it/s]

2026-09-09 18:28:05,875 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:05,900 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:28:05,922 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:05,945 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:05,966 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  76%|███████▌  | 16731/22132 [06:20<02:09, 41.68it/s]

2026-09-09 18:28:05,990 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:06,009 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:06,030 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:06,052 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:06,074 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  76%|███████▌  | 16736/22132 [06:20<02:05, 43.08it/s]

2026-09-09 18:28:06,096 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:06,115 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:06,139 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:28:06,163 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:28:06,191 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]

Indexing Records:  76%|███████▌  | 16741/22132 [06:20<02:05, 42.97it/s]

2026-09-09 18:28:06,222 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:28:06,244 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:06,265 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:06,300 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]
2026-09-09 18:28:06,320 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  76%|███████▌  | 16746/22132 [06:20<02:09, 41.56it/s]

2026-09-09 18:28:06,343 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:06,366 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:06,387 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:06,409 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:06,429 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  76%|███████▌  | 16751/22132 [06:20<02:05, 42.81it/s]

2026-09-09 18:28:06,454 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:28:06,476 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:06,499 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:06,536 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]
2026-09-09 18:28:06,555 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  76%|███████▌  | 16756/22132 [06:20<02:08, 41.80it/s]

2026-09-09 18:28:06,576 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:06,598 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:06,616 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:06,640 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:06,659 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  76%|███████▌  | 16761/22132 [06:20<02:03, 43.54it/s]

2026-09-09 18:28:06,683 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:06,709 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:28:06,729 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:06,770 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.039s]
2026-09-09 18:28:06,789 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  76%|███████▌  | 16766/22132 [06:20<02:08, 41.85it/s]

2026-09-09 18:28:06,814 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:28:06,841 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:28:06,891 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.049s]
2026-09-09 18:28:06,925 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:28:06,950 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  76%|███████▌  | 16771/22132 [06:21<02:21, 37.88it/s]

2026-09-09 18:28:06,977 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:28:07,001 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:07,023 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:07,051 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]

Indexing Records:  76%|███████▌  | 16775/22132 [06:21<02:19, 38.33it/s]

2026-09-09 18:28:07,078 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:28:07,098 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:07,117 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:07,142 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:28:07,161 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  76%|███████▌  | 16780/22132 [06:21<02:12, 40.25it/s]

2026-09-09 18:28:07,184 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:07,203 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:07,227 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:28:07,246 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:07,266 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  76%|███████▌  | 16785/22132 [06:21<02:06, 42.33it/s]

2026-09-09 18:28:07,285 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:07,307 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:07,326 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:07,344 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:07,364 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:07,383 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  76%|███████▌  | 16791/22132 [06:21<01:58, 45.03it/s]

2026-09-09 18:28:07,405 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:07,427 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:07,445 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:07,472 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:28:07,496 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  76%|███████▌  | 16796/22132 [06:21<01:58, 44.84it/s]

2026-09-09 18:28:07,516 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:07,541 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:28:07,564 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:07,589 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:28:07,614 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  76%|███████▌  | 16801/22132 [06:21<02:00, 44.08it/s]

2026-09-09 18:28:07,637 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:07,657 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:07,675 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:07,696 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:07,715 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  76%|███████▌  | 16806/22132 [06:21<01:57, 45.49it/s]

2026-09-09 18:28:07,746 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:28:07,776 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:28:07,800 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:28:07,819 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:07,840 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  76%|███████▌  | 16811/22132 [06:21<02:01, 43.78it/s]

2026-09-09 18:28:07,858 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:07,876 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:07,894 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:07,913 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:07,929 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:07,947 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  76%|███████▌  | 16817/22132 [06:22<01:52, 47.18it/s]

2026-09-09 18:28:07,965 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:07,982 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:07,999 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:08,022 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:08,041 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:08,060 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  76%|███████▌  | 16823/22132 [06:22<01:48, 49.00it/s]

2026-09-09 18:28:08,082 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:08,098 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:08,116 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:08,134 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:08,150 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:08,167 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  76%|███████▌  | 16829/22132 [06:22<01:43, 51.04it/s]

2026-09-09 18:28:08,187 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:08,206 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:08,222 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:08,238 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:08,255 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:08,274 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  76%|███████▌  | 16835/22132 [06:22<01:40, 52.58it/s]

2026-09-09 18:28:08,290 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:08,306 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:08,323 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:08,339 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:08,357 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:08,373 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:08,391 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  76%|███████▌  | 16842/22132 [06:22<01:36, 54.84it/s]

2026-09-09 18:28:08,410 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:08,428 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:08,446 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:08,464 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:08,480 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:08,497 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  76%|███████▌  | 16848/22132 [06:22<01:35, 55.31it/s]

2026-09-09 18:28:08,517 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:08,538 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:08,556 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:08,573 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:08,589 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:08,613 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  76%|███████▌  | 16854/22132 [06:22<01:37, 54.22it/s]

2026-09-09 18:28:08,636 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:08,652 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:08,671 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:08,694 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:08,714 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:08,734 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  76%|███████▌  | 16860/22132 [06:22<01:39, 52.74it/s]

2026-09-09 18:28:08,753 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:08,775 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:08,798 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:08,837 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.038s]
2026-09-09 18:28:08,860 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:08,931 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.070s]

Indexing Records:  76%|███████▌  | 16866/22132 [06:23<02:01, 43.24it/s]

2026-09-09 18:28:08,953 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:08,971 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:08,992 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:09,009 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:09,026 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:09,042 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  76%|███████▌  | 16872/22132 [06:23<01:54, 46.00it/s]

2026-09-09 18:28:09,066 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:09,087 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:09,105 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:09,123 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:09,139 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:09,157 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  76%|███████▋  | 16878/22132 [06:23<01:50, 47.73it/s]

2026-09-09 18:28:09,174 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:09,190 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:09,209 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:09,224 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:09,241 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:09,256 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:09,272 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  76%|███████▋  | 16885/22132 [06:23<01:42, 51.37it/s]

2026-09-09 18:28:09,291 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:09,309 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:09,324 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:09,343 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:09,359 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:09,375 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  76%|███████▋  | 16891/22132 [06:23<01:38, 53.21it/s]

2026-09-09 18:28:09,392 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:09,407 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:09,425 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:09,443 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:09,461 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:09,487 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]

Indexing Records:  76%|███████▋  | 16897/22132 [06:23<01:38, 53.30it/s]

2026-09-09 18:28:09,505 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:09,528 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:09,551 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:09,573 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:09,591 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:09,612 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  76%|███████▋  | 16903/22132 [06:23<01:41, 51.63it/s]

2026-09-09 18:28:09,630 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:09,651 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:09,668 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:09,687 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:09,706 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:09,723 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  76%|███████▋  | 16909/22132 [06:23<01:39, 52.29it/s]

2026-09-09 18:28:09,748 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:09,767 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:09,783 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:09,806 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:09,828 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:09,847 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  76%|███████▋  | 16915/22132 [06:23<01:42, 51.06it/s]

2026-09-09 18:28:09,865 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:09,881 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:09,898 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:09,915 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:09,932 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:09,953 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  76%|███████▋  | 16921/22132 [06:24<01:38, 52.70it/s]

2026-09-09 18:28:09,973 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:09,989 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:10,011 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:10,040 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:28:10,065 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:28:10,091 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]

Indexing Records:  76%|███████▋  | 16927/22132 [06:24<01:45, 49.55it/s]

2026-09-09 18:28:10,112 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:10,131 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:10,160 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:28:10,187 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:28:10,209 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:10,229 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  77%|███████▋  | 16933/22132 [06:24<01:49, 47.51it/s]

2026-09-09 18:28:10,251 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:10,274 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:10,293 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:10,309 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:10,328 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:10,349 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  77%|███████▋  | 16939/22132 [06:24<01:47, 48.21it/s]

2026-09-09 18:28:10,372 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:10,391 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:10,410 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:10,431 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:10,449 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:10,467 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  77%|███████▋  | 16945/22132 [06:24<01:45, 49.01it/s]

2026-09-09 18:28:10,486 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:10,505 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:10,526 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:10,547 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:10,565 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:10,584 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  77%|███████▋  | 16951/22132 [06:24<01:44, 49.71it/s]

2026-09-09 18:28:10,605 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:10,624 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:10,645 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:10,667 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:10,686 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  77%|███████▋  | 16956/22132 [06:24<01:44, 49.52it/s]

2026-09-09 18:28:10,703 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:10,729 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:28:10,754 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:28:10,773 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:10,796 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  77%|███████▋  | 16961/22132 [06:24<01:46, 48.38it/s]

2026-09-09 18:28:10,816 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:10,836 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:10,859 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:10,882 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:10,910 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]

Indexing Records:  77%|███████▋  | 16966/22132 [06:25<01:49, 47.00it/s]

2026-09-09 18:28:10,933 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:10,958 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:28:10,980 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:11,001 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:11,032 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]

Indexing Records:  77%|███████▋  | 16971/22132 [06:25<01:54, 45.13it/s]

2026-09-09 18:28:11,054 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:11,072 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:11,095 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:11,119 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:28:11,150 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]

Indexing Records:  77%|███████▋  | 16976/22132 [06:25<01:56, 44.22it/s]

2026-09-09 18:28:11,169 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:11,187 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:11,208 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:11,234 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:28:11,253 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  77%|███████▋  | 16981/22132 [06:25<01:53, 45.46it/s]

2026-09-09 18:28:11,274 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:11,295 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:11,314 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:11,347 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:28:11,367 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  77%|███████▋  | 16986/22132 [06:25<01:54, 44.95it/s]

2026-09-09 18:28:11,385 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:11,401 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:11,417 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:11,432 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:11,449 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:11,468 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  77%|███████▋  | 16992/22132 [06:25<01:45, 48.91it/s]

2026-09-09 18:28:11,491 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:11,514 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:11,536 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:11,557 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:11,583 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  77%|███████▋  | 16997/22132 [06:25<01:48, 47.31it/s]

2026-09-09 18:28:11,620 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.036s]
2026-09-09 18:28:11,650 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:28:11,680 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:28:11,703 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:11,719 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  77%|███████▋  | 17002/22132 [06:25<01:57, 43.65it/s]

2026-09-09 18:28:11,736 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:11,754 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:11,772 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:11,792 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:11,812 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:11,836 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  77%|███████▋  | 17008/22132 [06:25<01:51, 45.86it/s]

2026-09-09 18:28:11,862 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:28:11,879 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:11,896 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:11,914 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:11,933 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:11,949 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  77%|███████▋  | 17014/22132 [06:26<01:46, 48.02it/s]

2026-09-09 18:28:11,965 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:11,982 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:11,998 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:12,018 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:12,035 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:12,055 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  77%|███████▋  | 17020/22132 [06:26<01:41, 50.40it/s]

2026-09-09 18:28:12,074 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:12,090 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:12,112 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:12,129 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:12,146 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:12,163 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  77%|███████▋  | 17026/22132 [06:26<01:38, 51.81it/s]

2026-09-09 18:28:12,185 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:12,207 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:12,225 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:12,245 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:12,263 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:12,284 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  77%|███████▋  | 17032/22132 [06:26<01:39, 51.25it/s]

2026-09-09 18:28:12,305 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:12,325 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:12,344 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:12,361 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:12,379 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:12,399 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  77%|███████▋  | 17038/22132 [06:26<01:39, 51.45it/s]

2026-09-09 18:28:12,423 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:12,448 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:28:12,469 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:12,490 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:12,507 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:12,523 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  77%|███████▋  | 17044/22132 [06:26<01:40, 50.49it/s]

2026-09-09 18:28:12,544 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:12,561 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:12,582 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:12,600 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:12,622 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:12,639 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  77%|███████▋  | 17050/22132 [06:26<01:39, 50.93it/s]

2026-09-09 18:28:12,657 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:12,673 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:12,696 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:12,712 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:12,732 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:12,748 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  77%|███████▋  | 17056/22132 [06:26<01:37, 52.03it/s]

2026-09-09 18:28:12,769 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:12,793 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:12,818 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:28:12,840 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:12,867 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:28:12,888 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  77%|███████▋  | 17062/22132 [06:27<01:43, 48.94it/s]

2026-09-09 18:28:12,911 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:12,941 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:28:12,965 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:28:12,988 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:13,015 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]

Indexing Records:  77%|███████▋  | 17067/22132 [06:27<01:50, 45.99it/s]

2026-09-09 18:28:13,040 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:28:13,058 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:13,083 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:28:13,103 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:13,121 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  77%|███████▋  | 17072/22132 [06:27<01:49, 46.26it/s]

2026-09-09 18:28:13,139 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:13,158 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:13,180 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:13,200 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:13,219 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:13,236 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  77%|███████▋  | 17078/22132 [06:27<01:45, 48.05it/s]

2026-09-09 18:28:13,253 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:13,279 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:28:13,297 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:13,317 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:13,336 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  77%|███████▋  | 17083/22132 [06:27<01:44, 48.50it/s]

2026-09-09 18:28:13,358 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:13,376 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:13,396 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:13,416 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:13,434 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:13,451 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  77%|███████▋  | 17089/22132 [06:27<01:41, 49.60it/s]

2026-09-09 18:28:13,469 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:13,486 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:13,502 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:13,518 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:13,537 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:13,553 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  77%|███████▋  | 17095/22132 [06:27<01:36, 52.18it/s]

2026-09-09 18:28:13,573 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:13,589 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:13,607 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:13,627 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:13,647 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:13,670 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  77%|███████▋  | 17101/22132 [06:27<01:36, 51.91it/s]

2026-09-09 18:28:13,694 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:13,715 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:13,734 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:13,751 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:13,771 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:13,788 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  77%|███████▋  | 17107/22132 [06:27<01:37, 51.58it/s]

2026-09-09 18:28:13,815 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:28:13,834 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:13,854 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:13,873 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:13,897 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:28:13,920 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  77%|███████▋  | 17113/22132 [06:28<01:41, 49.56it/s]

2026-09-09 18:28:13,942 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:13,963 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:13,983 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:14,000 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:14,022 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  77%|███████▋  | 17118/22132 [06:28<01:41, 49.38it/s]

2026-09-09 18:28:14,041 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:14,058 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:14,076 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:14,095 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:14,113 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:14,131 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  77%|███████▋  | 17124/22132 [06:28<01:38, 51.04it/s]

2026-09-09 18:28:14,148 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:14,165 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:14,184 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:14,201 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:14,220 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:14,243 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  77%|███████▋  | 17130/22132 [06:28<01:36, 51.81it/s]

2026-09-09 18:28:14,261 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:14,277 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:14,294 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:14,313 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:14,332 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:14,351 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  77%|███████▋  | 17136/22132 [06:28<01:34, 52.93it/s]

2026-09-09 18:28:14,374 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:14,391 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:14,408 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:14,425 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:14,444 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:14,463 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  77%|███████▋  | 17142/22132 [06:28<01:33, 53.12it/s]

2026-09-09 18:28:14,487 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:14,503 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:14,526 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:14,553 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:28:14,573 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:14,592 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  77%|███████▋  | 17148/22132 [06:28<01:37, 50.94it/s]

2026-09-09 18:28:14,611 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:14,629 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:14,647 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:14,667 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:14,683 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:14,702 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  78%|███████▊  | 17154/22132 [06:28<01:35, 51.93it/s]

2026-09-09 18:28:14,720 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:14,742 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:14,761 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:14,779 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:14,798 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:14,816 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  78%|███████▊  | 17160/22132 [06:28<01:35, 52.16it/s]

2026-09-09 18:28:14,833 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:14,852 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:14,871 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:14,888 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:14,905 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:14,922 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  78%|███████▊  | 17166/22132 [06:29<01:32, 53.40it/s]

2026-09-09 18:28:14,939 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:14,959 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:14,981 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:15,003 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:15,036 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:28:15,066 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]

Indexing Records:  78%|███████▊  | 17172/22132 [06:29<01:40, 49.28it/s]

2026-09-09 18:28:15,085 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:15,103 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:15,120 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:15,141 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:15,157 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:15,173 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  78%|███████▊  | 17178/22132 [06:29<01:36, 51.15it/s]

2026-09-09 18:28:15,190 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:15,207 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:15,224 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:15,240 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:15,256 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:15,272 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:15,288 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  78%|███████▊  | 17185/22132 [06:29<01:31, 54.01it/s]

2026-09-09 18:28:15,308 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:15,324 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:15,340 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:15,358 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:15,374 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:15,389 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  78%|███████▊  | 17191/22132 [06:29<01:29, 55.38it/s]

2026-09-09 18:28:15,406 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:15,421 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:15,437 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:15,454 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:15,471 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:15,488 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:15,503 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  78%|███████▊  | 17198/22132 [06:29<01:26, 57.35it/s]

2026-09-09 18:28:15,518 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:15,535 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:15,552 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:15,568 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:15,583 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:15,599 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:15,616 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  78%|███████▊  | 17205/22132 [06:29<01:23, 58.67it/s]

2026-09-09 18:28:15,634 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:15,650 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:15,667 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:15,685 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:15,707 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:15,725 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  78%|███████▊  | 17211/22132 [06:29<01:25, 57.60it/s]

2026-09-09 18:28:15,749 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:15,765 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:15,782 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:15,800 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:15,818 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:15,835 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  78%|███████▊  | 17217/22132 [06:29<01:26, 56.65it/s]

2026-09-09 18:28:15,857 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:15,879 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:15,901 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:15,919 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:15,939 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:15,962 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  78%|███████▊  | 17223/22132 [06:30<01:31, 53.59it/s]

2026-09-09 18:28:15,982 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:16,001 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:16,023 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:16,044 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:16,065 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:16,081 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  78%|███████▊  | 17229/22132 [06:30<01:33, 52.56it/s]

2026-09-09 18:28:16,100 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:16,117 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:16,136 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:16,154 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:16,170 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:16,186 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  78%|███████▊  | 17235/22132 [06:30<01:30, 53.94it/s]

2026-09-09 18:28:16,202 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:16,218 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:16,235 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:16,253 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:16,271 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:16,287 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  78%|███████▊  | 17241/22132 [06:30<01:28, 55.41it/s]

2026-09-09 18:28:16,306 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:16,324 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:16,343 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:16,361 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:16,380 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:16,397 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  78%|███████▊  | 17247/22132 [06:30<01:28, 55.18it/s]

2026-09-09 18:28:16,414 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:16,429 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:16,447 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:16,463 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:16,479 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:16,495 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:16,512 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  78%|███████▊  | 17254/22132 [06:30<01:25, 56.94it/s]

2026-09-09 18:28:16,530 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:16,547 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:16,563 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:16,579 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:16,595 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:16,611 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:16,627 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  78%|███████▊  | 17261/22132 [06:30<01:23, 58.15it/s]

2026-09-09 18:28:16,645 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:16,661 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:16,678 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:16,695 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:16,712 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:16,729 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  78%|███████▊  | 17267/22132 [06:30<01:23, 58.21it/s]

2026-09-09 18:28:16,747 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:16,765 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:16,780 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:16,796 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:16,812 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:16,828 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:16,844 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  78%|███████▊  | 17274/22132 [06:30<01:22, 59.13it/s]

2026-09-09 18:28:16,861 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:16,878 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:16,895 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:16,912 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:16,928 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:16,946 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  78%|███████▊  | 17280/22132 [06:31<01:22, 58.97it/s]

2026-09-09 18:28:16,964 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:16,981 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:16,996 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:17,015 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:17,033 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:17,051 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  78%|███████▊  | 17286/22132 [06:31<01:22, 58.57it/s]

2026-09-09 18:28:17,069 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:17,085 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:17,100 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:17,116 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:17,132 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:17,150 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:17,167 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  78%|███████▊  | 17293/22132 [06:31<01:21, 59.07it/s]

2026-09-09 18:28:17,185 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:17,202 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:17,219 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:17,234 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:17,250 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:17,267 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:17,283 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  78%|███████▊  | 17300/22132 [06:31<01:21, 59.51it/s]

2026-09-09 18:28:17,301 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:17,316 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:17,331 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:17,347 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:17,365 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:17,383 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  78%|███████▊  | 17306/22132 [06:31<01:21, 59.57it/s]

2026-09-09 18:28:17,400 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:17,415 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:17,431 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:17,447 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:17,463 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:17,478 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:17,495 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  78%|███████▊  | 17313/22132 [06:31<01:19, 60.52it/s]

2026-09-09 18:28:17,513 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:17,529 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:17,544 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:17,560 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:17,575 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:17,590 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:17,608 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  78%|███████▊  | 17320/22132 [06:31<01:18, 61.00it/s]

2026-09-09 18:28:17,624 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:17,639 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:17,657 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:17,673 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:17,690 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:17,705 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:17,722 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  78%|███████▊  | 17327/22132 [06:31<01:18, 61.10it/s]

2026-09-09 18:28:17,739 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:17,755 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:17,772 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:17,789 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:17,806 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:17,821 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:17,839 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  78%|███████▊  | 17334/22132 [06:31<01:19, 60.72it/s]

2026-09-09 18:28:17,857 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:17,872 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:17,888 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:17,904 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:17,920 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:17,935 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:17,952 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  78%|███████▊  | 17341/22132 [06:32<01:18, 61.08it/s]

2026-09-09 18:28:17,970 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:17,985 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:18,001 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:18,019 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:18,038 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:18,055 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:18,072 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  78%|███████▊  | 17348/22132 [06:32<01:19, 60.15it/s]

2026-09-09 18:28:18,089 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:18,106 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:18,124 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:18,143 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:18,162 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:18,179 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:18,196 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  78%|███████▊  | 17355/22132 [06:32<01:20, 58.98it/s]

2026-09-09 18:28:18,216 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:18,234 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:18,250 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:18,267 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:18,283 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:18,298 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  78%|███████▊  | 17361/22132 [06:32<01:20, 58.95it/s]

2026-09-09 18:28:18,315 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:18,331 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:18,347 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:18,364 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:18,381 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:18,397 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:18,415 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  78%|███████▊  | 17368/22132 [06:32<01:20, 59.18it/s]

2026-09-09 18:28:18,436 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:18,453 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:18,469 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:18,484 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:18,500 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:18,516 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  79%|███████▊  | 17374/22132 [06:32<01:20, 59.24it/s]

2026-09-09 18:28:18,537 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:18,555 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:18,573 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:18,592 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:18,611 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:18,626 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  79%|███████▊  | 17380/22132 [06:32<01:22, 57.85it/s]

2026-09-09 18:28:18,647 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:18,664 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:18,682 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:18,705 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:18,722 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:18,739 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  79%|███████▊  | 17386/22132 [06:32<01:24, 56.37it/s]

2026-09-09 18:28:18,759 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:18,777 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:18,794 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:18,813 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:18,831 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:18,849 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  79%|███████▊  | 17392/22132 [06:32<01:24, 55.84it/s]

2026-09-09 18:28:18,867 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:18,891 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:28:18,911 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:18,932 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:18,949 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:18,967 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  79%|███████▊  | 17398/22132 [06:33<01:27, 54.38it/s]

2026-09-09 18:28:18,984 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:19,002 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:19,018 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:19,039 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:19,059 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:19,081 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  79%|███████▊  | 17404/22132 [06:33<01:27, 53.88it/s]

2026-09-09 18:28:19,100 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:19,121 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:19,142 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:19,162 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:19,185 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:19,202 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  79%|███████▊  | 17410/22132 [06:33<01:29, 52.53it/s]

2026-09-09 18:28:19,220 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:19,239 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:19,256 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:19,274 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:19,324 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.049s]
2026-09-09 18:28:19,344 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  79%|███████▊  | 17416/22132 [06:33<01:36, 48.91it/s]

2026-09-09 18:28:19,361 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:19,381 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:19,402 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:19,418 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:19,434 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:19,455 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  79%|███████▊  | 17422/22132 [06:33<01:33, 50.32it/s]

2026-09-09 18:28:19,474 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:19,490 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:19,509 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:19,529 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:19,549 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:19,568 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  79%|███████▊  | 17428/22132 [06:33<01:32, 51.13it/s]

2026-09-09 18:28:19,588 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:19,608 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:19,627 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:19,646 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:19,664 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:19,683 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  79%|███████▉  | 17434/22132 [06:33<01:31, 51.53it/s]

2026-09-09 18:28:19,701 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:19,721 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:19,744 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:19,765 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:19,791 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:28:19,813 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  79%|███████▉  | 17440/22132 [06:33<01:34, 49.79it/s]

2026-09-09 18:28:19,842 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:28:19,868 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:28:19,891 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:19,914 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:19,941 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:28:19,964 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  79%|███████▉  | 17446/22132 [06:34<01:41, 46.28it/s]

2026-09-09 18:28:19,988 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:20,007 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:20,039 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:28:20,071 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:28:20,093 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  79%|███████▉  | 17451/22132 [06:34<01:46, 43.94it/s]

2026-09-09 18:28:20,117 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:20,134 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:20,151 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:20,166 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:20,195 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]

Indexing Records:  79%|███████▉  | 17456/22132 [06:34<01:43, 45.20it/s]

2026-09-09 18:28:20,215 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:20,231 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:20,248 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:20,264 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:20,281 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:20,299 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  79%|███████▉  | 17462/22132 [06:34<01:35, 48.69it/s]

2026-09-09 18:28:20,316 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:20,332 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:20,349 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:20,368 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:20,385 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:20,405 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  79%|███████▉  | 17468/22132 [06:34<01:31, 50.81it/s]

2026-09-09 18:28:20,425 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:20,441 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:20,457 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:20,473 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:20,489 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:20,505 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:20,522 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  79%|███████▉  | 17475/22132 [06:34<01:26, 53.65it/s]

2026-09-09 18:28:20,540 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:20,560 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:20,586 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:28:20,606 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:20,624 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:20,643 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  79%|███████▉  | 17481/22132 [06:34<01:28, 52.38it/s]

2026-09-09 18:28:20,663 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:20,683 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:20,702 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:20,719 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:20,738 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:20,755 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  79%|███████▉  | 17487/22132 [06:34<01:28, 52.73it/s]

2026-09-09 18:28:20,777 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:20,795 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:20,811 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:20,829 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:20,847 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:20,868 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  79%|███████▉  | 17493/22132 [06:35<01:27, 52.86it/s]

2026-09-09 18:28:20,892 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:28:20,913 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:20,931 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:20,949 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:20,973 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:20,992 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  79%|███████▉  | 17499/22132 [06:35<01:30, 51.38it/s]

2026-09-09 18:28:21,014 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:21,035 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:21,056 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:21,080 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:21,105 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:28:21,126 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  79%|███████▉  | 17505/22132 [06:35<01:34, 49.18it/s]

2026-09-09 18:28:21,150 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:21,175 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:28:21,202 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:28:21,233 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:28:21,261 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]

Indexing Records:  79%|███████▉  | 17510/22132 [06:35<01:41, 45.38it/s]

2026-09-09 18:28:21,283 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:21,303 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:21,330 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:28:21,352 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:21,373 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  79%|███████▉  | 17515/22132 [06:35<01:42, 45.14it/s]

2026-09-09 18:28:21,391 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:21,415 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:28:21,439 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:21,464 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:28:21,482 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  79%|███████▉  | 17520/22132 [06:35<01:41, 45.33it/s]

2026-09-09 18:28:21,504 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:21,521 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:21,539 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:21,559 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:21,579 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:21,605 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]

Indexing Records:  79%|███████▉  | 17526/22132 [06:35<01:39, 46.35it/s]

2026-09-09 18:28:21,628 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:21,653 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:28:21,676 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:21,700 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:21,719 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  79%|███████▉  | 17531/22132 [06:35<01:40, 45.66it/s]

2026-09-09 18:28:21,740 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:21,758 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:21,775 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:21,799 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:28:21,819 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:21,837 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  79%|███████▉  | 17537/22132 [06:35<01:37, 47.22it/s]

2026-09-09 18:28:21,871 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:28:21,893 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:21,918 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:28:21,936 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:21,958 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  79%|███████▉  | 17542/22132 [06:36<01:40, 45.45it/s]

2026-09-09 18:28:21,980 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:22,004 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:28:22,027 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:22,055 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:28:22,074 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  79%|███████▉  | 17547/22132 [06:36<01:42, 44.76it/s]

2026-09-09 18:28:22,097 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:22,127 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:28:22,152 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:28:22,182 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:28:22,199 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  79%|███████▉  | 17552/22132 [06:36<01:45, 43.26it/s]

2026-09-09 18:28:22,220 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:22,242 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:22,265 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:28:22,283 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:22,307 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  79%|███████▉  | 17557/22132 [06:36<01:43, 44.11it/s]

2026-09-09 18:28:22,325 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:22,345 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:22,368 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:22,386 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:22,403 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:22,426 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  79%|███████▉  | 17563/22132 [06:36<01:39, 45.95it/s]

2026-09-09 18:28:22,447 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:22,469 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:22,488 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:22,510 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:22,532 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  79%|███████▉  | 17568/22132 [06:36<01:38, 46.33it/s]

2026-09-09 18:28:22,557 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:22,575 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:22,597 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:22,619 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:22,639 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  79%|███████▉  | 17573/22132 [06:36<01:38, 46.52it/s]

2026-09-09 18:28:22,660 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:22,691 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:28:22,710 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:22,732 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:22,754 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  79%|███████▉  | 17578/22132 [06:36<01:40, 45.53it/s]

2026-09-09 18:28:22,773 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:22,790 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:22,810 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:22,827 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:22,846 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:22,862 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  79%|███████▉  | 17584/22132 [06:37<01:33, 48.43it/s]

2026-09-09 18:28:22,880 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:22,896 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:22,919 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:22,949 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:28:22,973 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  79%|███████▉  | 17589/22132 [06:37<01:35, 47.48it/s]

2026-09-09 18:28:22,998 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:28:23,039 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.040s]
2026-09-09 18:28:23,072 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:28:23,105 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:28:23,133 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]

Indexing Records:  79%|███████▉  | 17594/22132 [06:37<01:50, 41.19it/s]

2026-09-09 18:28:23,153 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:23,171 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:23,201 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:28:23,231 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:28:23,249 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  80%|███████▉  | 17599/22132 [06:37<01:48, 41.76it/s]

2026-09-09 18:28:23,273 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:23,294 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:23,317 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:23,338 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:23,356 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  80%|███████▉  | 17604/22132 [06:37<01:44, 43.17it/s]

2026-09-09 18:28:23,380 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:28:23,399 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:23,419 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:23,438 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:23,457 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  80%|███████▉  | 17609/22132 [06:37<01:40, 44.83it/s]

2026-09-09 18:28:23,477 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:23,503 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:28:23,524 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:23,545 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:23,564 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  80%|███████▉  | 17614/22132 [06:37<01:39, 45.38it/s]

2026-09-09 18:28:23,583 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:23,601 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:23,619 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:23,641 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:23,659 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:23,679 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  80%|███████▉  | 17620/22132 [06:37<01:34, 47.53it/s]

2026-09-09 18:28:23,701 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:23,718 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:23,735 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:23,752 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:23,769 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:23,787 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  80%|███████▉  | 17626/22132 [06:37<01:30, 49.89it/s]

2026-09-09 18:28:23,805 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:23,822 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:23,842 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:23,860 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:23,879 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:23,898 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  80%|███████▉  | 17632/22132 [06:38<01:28, 51.07it/s]

2026-09-09 18:28:23,919 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:23,936 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:23,956 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:23,975 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:23,997 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:24,016 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  80%|███████▉  | 17638/22132 [06:38<01:28, 51.01it/s]

2026-09-09 18:28:24,037 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:24,055 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:24,073 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:24,090 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:24,109 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:24,127 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  80%|███████▉  | 17644/22132 [06:38<01:26, 51.96it/s]

2026-09-09 18:28:24,158 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:28:24,177 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:24,200 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:24,227 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:28:24,256 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:28:24,273 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  80%|███████▉  | 17650/22132 [06:38<01:33, 47.99it/s]

2026-09-09 18:28:24,292 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:24,310 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:24,328 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:24,346 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:24,363 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:24,385 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  80%|███████▉  | 17656/22132 [06:38<01:30, 49.62it/s]

2026-09-09 18:28:24,403 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:24,421 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:24,440 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:24,461 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:24,478 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:24,495 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  80%|███████▉  | 17662/22132 [06:38<01:27, 50.98it/s]

2026-09-09 18:28:24,514 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:24,548 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]
2026-09-09 18:28:24,567 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:24,588 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:24,608 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:24,629 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  80%|███████▉  | 17668/22132 [06:38<01:31, 49.02it/s]

2026-09-09 18:28:24,647 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:24,668 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:24,686 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:24,704 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:24,722 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:24,746 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  80%|███████▉  | 17674/22132 [06:38<01:29, 49.63it/s]

2026-09-09 18:28:24,767 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:24,786 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:24,805 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:24,823 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:24,840 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:24,859 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  80%|███████▉  | 17680/22132 [06:39<01:28, 50.58it/s]

2026-09-09 18:28:24,880 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:24,901 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:24,919 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:24,941 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:24,965 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:24,989 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  80%|███████▉  | 17686/22132 [06:39<01:30, 49.14it/s]

2026-09-09 18:28:25,011 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:25,031 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:25,050 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:25,069 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:25,091 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  80%|███████▉  | 17691/22132 [06:39<01:30, 49.21it/s]

2026-09-09 18:28:25,110 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:25,130 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:25,150 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:25,167 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:25,187 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:25,208 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  80%|███████▉  | 17697/22132 [06:39<01:28, 49.85it/s]

2026-09-09 18:28:25,227 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:25,247 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:25,267 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:25,286 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:25,304 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:25,323 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  80%|███████▉  | 17703/22132 [06:39<01:27, 50.53it/s]

2026-09-09 18:28:25,342 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:25,360 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:25,379 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:25,399 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:25,418 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:25,438 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  80%|████████  | 17709/22132 [06:39<01:26, 50.95it/s]

2026-09-09 18:28:25,458 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:25,480 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:25,502 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:25,520 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:25,538 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:25,558 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  80%|████████  | 17715/22132 [06:39<01:27, 50.62it/s]

2026-09-09 18:28:25,577 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:25,595 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:25,612 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:25,632 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:25,650 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:25,669 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  80%|████████  | 17721/22132 [06:39<01:25, 51.60it/s]

2026-09-09 18:28:25,688 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:25,707 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:25,726 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:25,748 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:25,766 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:25,785 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  80%|████████  | 17727/22132 [06:39<01:25, 51.72it/s]

2026-09-09 18:28:25,806 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:25,824 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:25,849 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:28:25,870 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:25,902 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:28:25,926 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  80%|████████  | 17733/22132 [06:40<01:30, 48.52it/s]

2026-09-09 18:28:25,950 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:25,970 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:26,036 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.065s]
2026-09-09 18:28:26,057 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:26,076 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  80%|████████  | 17738/22132 [06:40<01:41, 43.29it/s]

2026-09-09 18:28:26,099 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:26,118 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:26,147 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:28:26,168 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:26,190 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  80%|████████  | 17743/22132 [06:40<01:40, 43.51it/s]

2026-09-09 18:28:26,209 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:26,230 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:26,250 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:26,285 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]
2026-09-09 18:28:26,318 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]

Indexing Records:  80%|████████  | 17748/22132 [06:40<01:43, 42.18it/s]

2026-09-09 18:28:26,358 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.038s]
2026-09-09 18:28:26,377 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:26,397 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:26,419 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:26,453 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]

Indexing Records:  80%|████████  | 17753/22132 [06:40<01:48, 40.52it/s]

2026-09-09 18:28:26,495 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.040s]
2026-09-09 18:28:26,536 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.040s]
2026-09-09 18:28:26,564 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:28:26,597 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:28:26,617 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  80%|████████  | 17758/22132 [06:40<01:58, 37.00it/s]

2026-09-09 18:28:26,642 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:28:26,668 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:28:26,691 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:26,712 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:26,732 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  80%|████████  | 17763/22132 [06:40<01:52, 38.69it/s]

2026-09-09 18:28:26,778 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.044s]
2026-09-09 18:28:26,804 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:28:26,823 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:26,850 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]

Indexing Records:  80%|████████  | 17767/22132 [06:40<01:56, 37.35it/s]

2026-09-09 18:28:26,870 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:26,888 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:26,906 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:26,929 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:26,947 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:26,968 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  80%|████████  | 17773/22132 [06:41<01:45, 41.21it/s]

2026-09-09 18:28:26,987 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:27,004 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:27,031 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:28:27,049 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:27,068 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:27,084 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  80%|████████  | 17779/22132 [06:41<01:38, 44.17it/s]

2026-09-09 18:28:27,108 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:27,130 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:27,159 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:28:27,180 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:27,197 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  80%|████████  | 17784/22132 [06:41<01:38, 44.15it/s]

2026-09-09 18:28:27,221 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:27,238 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:27,257 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:27,277 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:27,300 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  80%|████████  | 17789/22132 [06:41<01:35, 45.42it/s]

2026-09-09 18:28:27,321 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:27,341 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:27,359 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:27,381 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:27,400 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  80%|████████  | 17794/22132 [06:41<01:33, 46.61it/s]

2026-09-09 18:28:27,423 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:27,443 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:27,463 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:27,481 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:27,499 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:27,518 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  80%|████████  | 17800/22132 [06:41<01:30, 47.97it/s]

2026-09-09 18:28:27,538 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:27,560 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:27,589 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:28:27,605 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:27,622 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  80%|████████  | 17805/22132 [06:41<01:30, 47.94it/s]

2026-09-09 18:28:27,643 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:27,660 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:27,677 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:27,698 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:27,715 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:27,732 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  80%|████████  | 17811/22132 [06:41<01:26, 49.97it/s]

2026-09-09 18:28:27,748 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:27,763 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:27,780 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:27,798 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:27,817 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:27,833 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  81%|████████  | 17817/22132 [06:41<01:22, 52.58it/s]

2026-09-09 18:28:27,851 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:27,866 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:27,886 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:27,901 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:27,917 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:27,934 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  81%|████████  | 17823/22132 [06:42<01:18, 54.63it/s]

2026-09-09 18:28:27,950 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:27,969 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:27,988 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:28,008 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:28,027 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:28,046 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  81%|████████  | 17829/22132 [06:42<01:19, 54.22it/s]

2026-09-09 18:28:28,064 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:28,079 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:28,095 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:28,111 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:28,127 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:28,145 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:28,163 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  81%|████████  | 17836/22132 [06:42<01:16, 56.09it/s]

2026-09-09 18:28:28,184 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:28,202 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:28,220 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:28,238 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:28,263 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:28:28,284 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  81%|████████  | 17842/22132 [06:42<01:19, 53.93it/s]

2026-09-09 18:28:28,307 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:28,326 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:28,345 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:28,360 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:28,378 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:28,396 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  81%|████████  | 17848/22132 [06:42<01:19, 53.88it/s]

2026-09-09 18:28:28,415 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:28,435 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:28,455 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:28,473 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:28,491 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:28,510 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  81%|████████  | 17854/22132 [06:42<01:19, 53.51it/s]

2026-09-09 18:28:28,526 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:28,542 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:28,557 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:28,572 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:28,589 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:28,605 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:28,621 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  81%|████████  | 17861/22132 [06:42<01:15, 56.33it/s]

2026-09-09 18:28:28,638 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:28,655 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:28,670 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:28,686 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:28,705 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:28,724 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  81%|████████  | 17867/22132 [06:42<01:15, 56.85it/s]

2026-09-09 18:28:28,742 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:28,763 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:28,783 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:28,802 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:28,821 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:28,839 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  81%|████████  | 17873/22132 [06:42<01:16, 55.40it/s]

2026-09-09 18:28:28,856 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:28,873 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:28,888 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:28,904 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:28,921 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:28,937 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:28,958 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  81%|████████  | 17880/22132 [06:43<01:15, 56.45it/s]

2026-09-09 18:28:28,975 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:28,992 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:29,010 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:29,026 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:29,043 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:29,061 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  81%|████████  | 17886/22132 [06:43<01:14, 57.06it/s]

2026-09-09 18:28:29,077 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:29,095 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:29,112 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:29,127 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:29,143 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:29,159 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:29,177 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  81%|████████  | 17893/22132 [06:43<01:13, 57.97it/s]

2026-09-09 18:28:29,197 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:29,214 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:29,231 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:29,249 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:29,265 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:29,282 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  81%|████████  | 17899/22132 [06:43<01:13, 57.74it/s]

2026-09-09 18:28:29,300 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:29,315 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:29,334 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:29,352 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:29,368 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:29,384 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  81%|████████  | 17905/22132 [06:43<01:12, 58.12it/s]

2026-09-09 18:28:29,401 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:29,421 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:29,443 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:29,462 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:29,480 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:29,496 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  81%|████████  | 17911/22132 [06:43<01:14, 56.75it/s]

2026-09-09 18:28:29,512 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:29,528 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:29,546 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:29,563 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:29,581 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:29,598 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  81%|████████  | 17917/22132 [06:43<01:13, 57.33it/s]

2026-09-09 18:28:29,617 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:29,641 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:29,659 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:29,676 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:29,697 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:29,716 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  81%|████████  | 17923/22132 [06:43<01:16, 55.25it/s]

2026-09-09 18:28:29,735 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:29,757 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:29,780 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:29,797 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:29,820 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:29,845 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  81%|████████  | 17929/22132 [06:43<01:20, 52.23it/s]

2026-09-09 18:28:29,864 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:29,884 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:29,905 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:29,924 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:29,945 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:29,960 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  81%|████████  | 17935/22132 [06:44<01:20, 52.22it/s]

2026-09-09 18:28:29,977 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:29,993 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:30,096 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.102s]
2026-09-09 18:28:30,116 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:30,135 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:30,155 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  81%|████████  | 17941/22132 [06:44<01:36, 43.29it/s]

2026-09-09 18:28:30,175 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:30,194 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:30,232 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.037s]
2026-09-09 18:28:30,251 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:30,274 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  81%|████████  | 17946/22132 [06:44<01:37, 42.93it/s]

2026-09-09 18:28:30,297 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:30,315 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:30,334 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:30,363 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:28:30,381 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  81%|████████  | 17951/22132 [06:44<01:35, 43.86it/s]

2026-09-09 18:28:30,400 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:30,419 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:30,438 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:30,457 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:30,476 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:30,496 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  81%|████████  | 17957/22132 [06:44<01:30, 46.28it/s]

2026-09-09 18:28:30,515 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:30,533 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:30,556 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:30,574 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:30,594 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:30,614 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  81%|████████  | 17963/22132 [06:44<01:27, 47.59it/s]

2026-09-09 18:28:30,634 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:30,663 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:28:30,684 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:30,703 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:30,721 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  81%|████████  | 17968/22132 [06:44<01:27, 47.35it/s]

2026-09-09 18:28:30,745 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:30,765 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:30,783 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:30,814 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:28:30,833 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  81%|████████  | 17973/22132 [06:44<01:29, 46.58it/s]

2026-09-09 18:28:30,853 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:30,872 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:30,892 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:30,911 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:30,930 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:30,948 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  81%|████████  | 17979/22132 [06:45<01:26, 48.24it/s]

2026-09-09 18:28:30,967 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:30,986 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:31,012 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:28:31,031 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:31,051 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  81%|████████▏ | 17984/22132 [06:45<01:25, 48.24it/s]

2026-09-09 18:28:31,101 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.048s]
2026-09-09 18:28:31,132 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:28:31,151 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:31,168 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:31,190 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  81%|████████▏ | 17989/22132 [06:45<01:34, 44.07it/s]

2026-09-09 18:28:31,253 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.061s]
2026-09-09 18:28:31,299 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.045s]
2026-09-09 18:28:31,318 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:31,342 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:28:31,368 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]

Indexing Records:  81%|████████▏ | 17994/22132 [06:45<01:49, 37.78it/s]

2026-09-09 18:28:31,389 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:31,407 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:31,427 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:31,445 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:31,466 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:31,483 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  81%|████████▏ | 18000/22132 [06:45<01:39, 41.57it/s]

2026-09-09 18:28:31,504 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:31,522 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:31,541 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:31,559 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:31,576 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:31,594 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  81%|████████▏ | 18006/22132 [06:45<01:31, 44.93it/s]

2026-09-09 18:28:31,616 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:31,634 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:31,651 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:31,666 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:31,682 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:31,698 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  81%|████████▏ | 18012/22132 [06:45<01:25, 48.30it/s]

2026-09-09 18:28:31,717 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:31,732 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:31,752 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:31,773 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:31,789 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:31,804 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  81%|████████▏ | 18018/22132 [06:45<01:21, 50.60it/s]

2026-09-09 18:28:31,823 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:31,839 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:31,855 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:31,871 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:31,886 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:31,903 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:31,919 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  81%|████████▏ | 18025/22132 [06:46<01:16, 53.67it/s]

2026-09-09 18:28:31,937 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:31,955 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:31,973 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:31,991 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:32,007 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:32,023 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  81%|████████▏ | 18031/22132 [06:46<01:14, 54.89it/s]

2026-09-09 18:28:32,040 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:32,058 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:32,074 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:32,091 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:32,109 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:32,125 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  81%|████████▏ | 18037/22132 [06:46<01:13, 55.90it/s]

2026-09-09 18:28:32,142 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:32,157 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:32,173 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:32,189 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:32,206 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:32,223 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:32,239 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  82%|████████▏ | 18044/22132 [06:46<01:10, 57.70it/s]

2026-09-09 18:28:32,256 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:32,272 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:32,289 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:32,304 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:32,320 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:32,336 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:32,351 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  82%|████████▏ | 18051/22132 [06:46<01:09, 59.11it/s]

2026-09-09 18:28:32,369 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:32,388 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:32,404 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:32,422 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:32,438 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:32,455 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  82%|████████▏ | 18057/22132 [06:46<01:09, 58.67it/s]

2026-09-09 18:28:32,471 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:32,487 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:32,502 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:32,518 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:32,535 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:32,552 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:32,568 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  82%|████████▏ | 18064/22132 [06:46<01:08, 59.70it/s]

2026-09-09 18:28:32,586 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:32,602 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:32,620 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:32,635 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:32,653 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:32,668 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  82%|████████▏ | 18070/22132 [06:46<01:07, 59.77it/s]

2026-09-09 18:28:32,685 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:32,701 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:32,719 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:32,736 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:32,753 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:32,769 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  82%|████████▏ | 18076/22132 [06:46<01:07, 59.70it/s]

2026-09-09 18:28:32,786 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:32,801 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:32,817 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:32,833 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:32,850 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:32,865 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:32,881 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  82%|████████▏ | 18083/22132 [06:47<01:06, 60.59it/s]

2026-09-09 18:28:32,902 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:32,919 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:32,936 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:32,952 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:32,969 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:32,985 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:33,001 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  82%|████████▏ | 18090/22132 [06:47<01:07, 59.75it/s]

2026-09-09 18:28:33,020 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:33,040 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:33,056 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:33,072 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:33,091 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:33,113 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  82%|████████▏ | 18096/22132 [06:47<01:09, 58.01it/s]

2026-09-09 18:28:33,131 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:33,148 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:33,164 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:33,181 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:33,197 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:33,214 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  82%|████████▏ | 18102/22132 [06:47<01:09, 58.37it/s]

2026-09-09 18:28:33,231 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:33,249 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:33,267 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:33,286 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:33,304 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:33,325 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  82%|████████▏ | 18108/22132 [06:47<01:10, 57.07it/s]

2026-09-09 18:28:33,343 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:33,363 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:33,383 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:33,400 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:33,417 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:33,436 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  82%|████████▏ | 18114/22132 [06:47<01:11, 56.12it/s]

2026-09-09 18:28:33,455 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:33,472 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:33,495 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:33,521 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:28:33,542 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:33,560 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  82%|████████▏ | 18120/22132 [06:47<01:14, 53.62it/s]

2026-09-09 18:28:33,581 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:33,600 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:33,619 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:33,641 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:33,672 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:28:33,698 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]

Indexing Records:  82%|████████▏ | 18126/22132 [06:47<01:19, 50.16it/s]

2026-09-09 18:28:33,716 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:33,736 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:33,754 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:33,771 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:33,787 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:33,805 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  82%|████████▏ | 18132/22132 [06:47<01:17, 51.72it/s]

2026-09-09 18:28:33,828 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:33,845 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:33,862 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:33,884 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:33,900 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:33,919 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  82%|████████▏ | 18138/22132 [06:48<01:16, 52.08it/s]

2026-09-09 18:28:33,935 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:33,952 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:33,968 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:33,983 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:34,000 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:34,017 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:34,034 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  82%|████████▏ | 18145/22132 [06:48<01:13, 54.59it/s]

2026-09-09 18:28:34,051 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:34,068 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:34,084 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:34,103 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:34,121 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:34,139 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  82%|████████▏ | 18151/22132 [06:48<01:11, 55.34it/s]

2026-09-09 18:28:34,156 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:34,173 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:34,189 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:34,205 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:34,223 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:34,239 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:34,257 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  82%|████████▏ | 18158/22132 [06:48<01:10, 56.67it/s]

2026-09-09 18:28:34,274 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:34,296 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:34,315 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:34,334 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:34,353 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:34,371 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  82%|████████▏ | 18164/22132 [06:48<01:11, 55.40it/s]

2026-09-09 18:28:34,390 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:34,410 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:34,429 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:34,449 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:34,468 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:34,489 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  82%|████████▏ | 18170/22132 [06:48<01:13, 54.02it/s]

2026-09-09 18:28:34,508 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:34,525 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:34,546 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:34,563 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:34,581 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:34,599 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  82%|████████▏ | 18176/22132 [06:48<01:13, 54.19it/s]

2026-09-09 18:28:34,619 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:34,637 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:34,660 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:34,676 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:34,695 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:34,713 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  82%|████████▏ | 18182/22132 [06:48<01:13, 53.74it/s]

2026-09-09 18:28:34,733 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:34,750 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:34,766 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:34,783 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:34,800 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:34,817 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  82%|████████▏ | 18188/22132 [06:48<01:11, 54.84it/s]

2026-09-09 18:28:34,834 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:34,851 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:34,869 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:34,890 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:34,909 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:34,929 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  82%|████████▏ | 18194/22132 [06:49<01:12, 54.46it/s]

2026-09-09 18:28:34,951 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:34,971 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:34,990 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:35,014 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:35,033 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:35,049 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  82%|████████▏ | 18200/22132 [06:49<01:14, 53.00it/s]

2026-09-09 18:28:35,069 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:35,086 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:35,102 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:35,118 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:35,133 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:35,150 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  82%|████████▏ | 18206/22132 [06:49<01:11, 54.69it/s]

2026-09-09 18:28:35,168 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:35,186 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:35,202 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:35,218 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:35,234 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:35,252 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  82%|████████▏ | 18212/22132 [06:49<01:10, 56.00it/s]

2026-09-09 18:28:35,269 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:35,287 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:35,305 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:35,324 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:35,343 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:35,366 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  82%|████████▏ | 18218/22132 [06:49<01:11, 54.88it/s]

2026-09-09 18:28:35,384 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:35,402 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:35,421 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:35,437 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:35,455 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:35,471 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  82%|████████▏ | 18224/22132 [06:49<01:10, 55.55it/s]

2026-09-09 18:28:35,489 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:35,505 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:35,521 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:35,537 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:35,555 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:35,571 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  82%|████████▏ | 18230/22132 [06:49<01:08, 56.81it/s]

2026-09-09 18:28:35,589 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:35,608 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:35,628 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:35,644 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:35,660 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:35,677 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  82%|████████▏ | 18236/22132 [06:49<01:08, 56.78it/s]

2026-09-09 18:28:35,693 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:35,710 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:35,726 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:35,744 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:35,761 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:35,777 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  82%|████████▏ | 18242/22132 [06:49<01:07, 57.68it/s]

2026-09-09 18:28:35,794 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:35,811 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:35,828 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:35,844 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:35,861 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:35,877 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:35,892 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  82%|████████▏ | 18249/22132 [06:50<01:06, 58.70it/s]

2026-09-09 18:28:35,908 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:35,923 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:35,939 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:35,954 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:35,971 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:35,986 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:36,003 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  82%|████████▏ | 18256/22132 [06:50<01:04, 59.98it/s]

2026-09-09 18:28:36,021 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:36,039 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:36,059 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:36,075 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:36,091 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:36,107 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  83%|████████▎ | 18262/22132 [06:50<01:05, 59.30it/s]

2026-09-09 18:28:36,126 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:36,143 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:36,159 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:36,176 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:36,193 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:36,209 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  83%|████████▎ | 18268/22132 [06:50<01:05, 59.16it/s]

2026-09-09 18:28:36,231 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:36,248 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:36,266 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:36,287 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:36,304 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:36,325 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  83%|████████▎ | 18274/22132 [06:50<01:07, 56.91it/s]

2026-09-09 18:28:36,344 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:36,363 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:36,379 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:36,395 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:36,415 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:36,431 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  83%|████████▎ | 18280/22132 [06:50<01:07, 56.75it/s]

2026-09-09 18:28:36,450 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:36,471 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:36,488 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:36,504 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:36,520 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:36,535 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  83%|████████▎ | 18286/22132 [06:50<01:07, 56.97it/s]

2026-09-09 18:28:36,551 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:36,568 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:36,584 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:36,600 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:36,619 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:36,637 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  83%|████████▎ | 18292/22132 [06:50<01:06, 57.63it/s]

2026-09-09 18:28:36,654 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:36,670 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:36,685 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:36,703 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:36,720 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:36,738 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  83%|████████▎ | 18298/22132 [06:50<01:06, 58.01it/s]

2026-09-09 18:28:36,755 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:36,773 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:36,791 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:36,807 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:36,823 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:36,838 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  83%|████████▎ | 18304/22132 [06:50<01:05, 58.59it/s]

2026-09-09 18:28:36,854 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:36,869 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:36,885 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:36,902 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:36,919 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:36,936 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:36,952 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  83%|████████▎ | 18311/22132 [06:51<01:04, 59.63it/s]

2026-09-09 18:28:36,969 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:36,985 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:37,000 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:37,018 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:37,035 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:37,062 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]

Indexing Records:  83%|████████▎ | 18317/22132 [06:51<01:05, 58.04it/s]

2026-09-09 18:28:37,081 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:37,098 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:37,115 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:37,134 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:37,151 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:37,167 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  83%|████████▎ | 18323/22132 [06:51<01:05, 57.76it/s]

2026-09-09 18:28:37,185 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:37,203 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:37,219 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:37,235 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:37,250 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:37,266 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:37,281 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  83%|████████▎ | 18330/22132 [06:51<01:04, 58.88it/s]

2026-09-09 18:28:37,300 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:37,317 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:37,334 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:37,351 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:37,370 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:37,385 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  83%|████████▎ | 18336/22132 [06:51<01:04, 58.47it/s]

2026-09-09 18:28:37,401 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:28:37,418 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:37,437 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:37,455 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:37,472 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:37,488 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  83%|████████▎ | 18342/22132 [06:51<01:04, 58.49it/s]

2026-09-09 18:28:37,505 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:37,521 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:37,537 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:37,552 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:37,568 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:37,585 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:37,603 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  83%|████████▎ | 18349/22132 [06:51<01:03, 59.31it/s]

2026-09-09 18:28:37,620 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:37,637 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:37,653 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:37,669 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:37,685 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:37,701 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:37,717 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  83%|████████▎ | 18356/22132 [06:51<01:03, 59.84it/s]

2026-09-09 18:28:37,734 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:37,751 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:37,768 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:37,784 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:37,804 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:37,822 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  83%|████████▎ | 18362/22132 [06:51<01:03, 59.17it/s]

2026-09-09 18:28:37,840 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:37,856 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:37,872 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:37,889 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:37,906 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:37,923 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  83%|████████▎ | 18368/22132 [06:52<01:03, 59.18it/s]

2026-09-09 18:28:37,941 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:37,957 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:37,975 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:37,990 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:38,006 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:38,023 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  83%|████████▎ | 18374/22132 [06:52<01:03, 59.34it/s]

2026-09-09 18:28:38,040 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:38,057 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:38,075 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:38,092 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:38,107 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:38,123 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:38,138 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  83%|████████▎ | 18381/22132 [06:52<01:02, 59.85it/s]

2026-09-09 18:28:38,156 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:38,172 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:38,188 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:38,205 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:38,224 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:38,242 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  83%|████████▎ | 18387/22132 [06:52<01:03, 59.35it/s]

2026-09-09 18:28:38,261 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:38,277 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:38,294 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:38,313 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:38,331 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:38,351 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  83%|████████▎ | 18393/22132 [06:52<01:04, 58.00it/s]

2026-09-09 18:28:38,375 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:38,395 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:38,411 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:38,430 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:38,450 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:38,470 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  83%|████████▎ | 18399/22132 [06:52<01:07, 55.54it/s]

2026-09-09 18:28:38,490 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:38,511 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:38,533 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:38,550 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:38,568 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:38,583 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  83%|████████▎ | 18405/22132 [06:52<01:08, 54.75it/s]

2026-09-09 18:28:38,600 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:38,616 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:38,633 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:38,650 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:38,667 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:38,689 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  83%|████████▎ | 18411/22132 [06:52<01:07, 55.34it/s]

2026-09-09 18:28:38,710 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:38,735 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:28:38,760 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:28:38,803 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.042s]
2026-09-09 18:28:38,825 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:38,854 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]

Indexing Records:  83%|████████▎ | 18417/22132 [06:52<01:17, 47.93it/s]

2026-09-09 18:28:38,891 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]
2026-09-09 18:28:38,908 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:38,923 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:38,938 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:38,955 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  83%|████████▎ | 18422/22132 [06:53<01:16, 48.27it/s]

2026-09-09 18:28:38,979 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:38,994 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:39,019 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:28:39,039 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:39,057 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  83%|████████▎ | 18427/22132 [06:53<01:16, 48.50it/s]

2026-09-09 18:28:39,075 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:39,092 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:39,111 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:39,134 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:39,164 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]

Indexing Records:  83%|████████▎ | 18432/22132 [06:53<01:17, 48.03it/s]

2026-09-09 18:28:39,185 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:39,206 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:39,224 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:39,244 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:39,264 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  83%|████████▎ | 18437/22132 [06:53<01:16, 48.53it/s]

2026-09-09 18:28:39,283 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:39,299 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:39,324 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:28:39,351 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:28:39,370 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  83%|████████▎ | 18442/22132 [06:53<01:16, 48.16it/s]

2026-09-09 18:28:39,387 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:39,407 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:39,426 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:39,444 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:39,463 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:39,486 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  83%|████████▎ | 18448/22132 [06:53<01:14, 49.27it/s]

2026-09-09 18:28:39,505 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:39,521 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:39,537 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:39,558 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:39,583 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:28:39,604 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  83%|████████▎ | 18454/22132 [06:53<01:13, 49.71it/s]

2026-09-09 18:28:39,624 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:39,645 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:39,665 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:39,683 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:39,702 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:39,721 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  83%|████████▎ | 18460/22132 [06:53<01:13, 50.24it/s]

2026-09-09 18:28:39,741 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:39,757 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:39,778 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:39,796 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:39,812 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:39,829 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  83%|████████▎ | 18466/22132 [06:53<01:10, 51.75it/s]

2026-09-09 18:28:39,847 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:39,864 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:39,881 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:39,899 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:39,917 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:39,935 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  83%|████████▎ | 18472/22132 [06:54<01:08, 53.17it/s]

2026-09-09 18:28:39,952 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:39,970 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:39,985 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:40,002 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:40,021 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:40,039 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  83%|████████▎ | 18478/22132 [06:54<01:07, 54.43it/s]

2026-09-09 18:28:40,068 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:28:40,090 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:40,109 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:40,175 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.064s]
2026-09-09 18:28:40,199 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:28:40,221 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  84%|████████▎ | 18484/22132 [06:54<01:20, 45.49it/s]

2026-09-09 18:28:40,243 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:40,274 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:28:40,295 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:40,316 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:40,334 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  84%|████████▎ | 18489/22132 [06:54<01:20, 45.09it/s]

2026-09-09 18:28:40,353 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:40,373 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:40,398 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:28:40,422 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:28:40,446 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  84%|████████▎ | 18494/22132 [06:54<01:20, 45.02it/s]

2026-09-09 18:28:40,478 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:28:40,501 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:40,524 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:40,546 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:40,563 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  84%|████████▎ | 18499/22132 [06:54<01:21, 44.31it/s]

2026-09-09 18:28:40,582 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:40,600 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:40,617 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:40,634 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:40,650 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:40,668 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  84%|████████▎ | 18505/22132 [06:54<01:15, 47.83it/s]

2026-09-09 18:28:40,686 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:40,706 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:40,722 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:40,741 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:40,762 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:40,781 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  84%|████████▎ | 18511/22132 [06:54<01:13, 49.46it/s]

2026-09-09 18:28:40,799 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:40,816 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:40,835 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:40,851 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:40,868 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:40,884 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  84%|████████▎ | 18517/22132 [06:55<01:09, 51.81it/s]

2026-09-09 18:28:40,901 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:40,917 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:40,934 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:40,951 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:40,966 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:40,983 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:41,003 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  84%|████████▎ | 18524/22132 [06:55<01:06, 54.05it/s]

2026-09-09 18:28:41,023 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:41,039 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:41,055 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:41,073 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:41,091 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:41,107 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  84%|████████▎ | 18530/22132 [06:55<01:05, 55.14it/s]

2026-09-09 18:28:41,123 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:41,142 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:41,158 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:41,175 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:41,191 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:41,207 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  84%|████████▍ | 18536/22132 [06:55<01:03, 56.41it/s]

2026-09-09 18:28:41,226 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:41,247 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:41,266 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:41,282 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:41,299 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:41,316 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  84%|████████▍ | 18542/22132 [06:55<01:04, 55.99it/s]

2026-09-09 18:28:41,333 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:41,350 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:41,369 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:41,385 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:41,402 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:41,418 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  84%|████████▍ | 18548/22132 [06:55<01:03, 56.86it/s]

2026-09-09 18:28:41,434 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:41,451 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:41,468 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:41,483 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:41,504 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:41,520 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  84%|████████▍ | 18554/22132 [06:55<01:02, 57.43it/s]

2026-09-09 18:28:41,539 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:41,557 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:41,576 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:41,595 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:41,612 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:41,629 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  84%|████████▍ | 18560/22132 [06:55<01:03, 56.64it/s]

2026-09-09 18:28:41,646 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:41,662 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:41,678 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:41,697 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:41,715 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:41,730 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  84%|████████▍ | 18566/22132 [06:55<01:02, 57.47it/s]

2026-09-09 18:28:41,747 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:41,764 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:41,780 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:41,800 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:41,818 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:41,836 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  84%|████████▍ | 18572/22132 [06:55<01:02, 57.25it/s]

2026-09-09 18:28:41,853 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:41,869 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:41,885 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:41,901 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:41,918 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:41,933 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:41,952 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  84%|████████▍ | 18579/22132 [06:56<01:01, 58.24it/s]

2026-09-09 18:28:41,971 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:41,987 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:42,004 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:42,021 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:42,038 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:42,054 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  84%|████████▍ | 18585/22132 [06:56<01:00, 58.35it/s]

2026-09-09 18:28:42,071 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:42,088 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:42,104 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:42,121 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:42,136 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:42,152 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:42,170 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  84%|████████▍ | 18592/22132 [06:56<00:59, 59.03it/s]

2026-09-09 18:28:42,187 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:42,204 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:42,222 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:42,238 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:42,256 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:42,275 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  84%|████████▍ | 18598/22132 [06:56<01:00, 58.50it/s]

2026-09-09 18:28:42,294 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:42,311 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:42,329 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:42,348 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:42,365 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:42,382 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  84%|████████▍ | 18604/22132 [06:56<01:01, 57.81it/s]

2026-09-09 18:28:42,399 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:42,415 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:42,434 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:42,451 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:42,468 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:42,486 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  84%|████████▍ | 18610/22132 [06:56<01:00, 57.77it/s]

2026-09-09 18:28:42,503 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:42,521 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:42,538 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:42,556 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:42,576 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:42,593 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  84%|████████▍ | 18616/22132 [06:56<01:01, 57.25it/s]

2026-09-09 18:28:42,612 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:42,630 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:42,646 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:42,663 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:42,679 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:42,695 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  84%|████████▍ | 18622/22132 [06:56<01:00, 57.62it/s]

2026-09-09 18:28:42,715 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:42,733 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:42,751 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:42,767 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:42,785 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:42,803 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  84%|████████▍ | 18628/22132 [06:56<01:01, 57.08it/s]

2026-09-09 18:28:42,821 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:42,837 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:42,855 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:42,872 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:42,888 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:42,906 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  84%|████████▍ | 18634/22132 [06:57<01:01, 57.33it/s]

2026-09-09 18:28:42,923 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:42,940 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:42,955 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:42,972 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:42,988 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:43,005 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:43,024 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  84%|████████▍ | 18641/22132 [06:57<01:00, 58.09it/s]

2026-09-09 18:28:43,045 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:43,062 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:43,078 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:43,094 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:43,114 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:43,134 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  84%|████████▍ | 18647/22132 [06:57<01:01, 56.99it/s]

2026-09-09 18:28:43,151 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:43,166 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:43,181 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:43,198 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:43,217 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:43,233 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:43,251 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  84%|████████▍ | 18654/22132 [06:57<01:00, 57.88it/s]

2026-09-09 18:28:43,268 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:43,284 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:43,300 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:43,316 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:43,332 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:43,348 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:43,364 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  84%|████████▍ | 18661/22132 [06:57<00:58, 59.08it/s]

2026-09-09 18:28:43,381 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:43,396 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:43,413 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:43,430 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:43,446 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:43,462 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:43,480 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  84%|████████▍ | 18668/22132 [06:57<00:58, 59.53it/s]

2026-09-09 18:28:43,496 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:43,512 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:43,530 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:43,547 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:43,564 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:43,581 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  84%|████████▍ | 18674/22132 [06:57<00:58, 59.35it/s]

2026-09-09 18:28:43,598 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:43,615 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:43,632 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:43,648 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:43,666 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:43,683 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  84%|████████▍ | 18680/22132 [06:57<00:58, 59.30it/s]

2026-09-09 18:28:43,700 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:43,717 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:43,734 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:43,753 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:43,769 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:43,785 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  84%|████████▍ | 18686/22132 [06:57<00:58, 59.21it/s]

2026-09-09 18:28:43,803 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:43,819 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:43,835 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:43,852 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:43,873 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:43,894 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  84%|████████▍ | 18692/22132 [06:58<00:59, 57.92it/s]

2026-09-09 18:28:43,912 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:43,928 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:43,944 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:43,960 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:43,978 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:43,996 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  84%|████████▍ | 18698/22132 [06:58<00:59, 58.14it/s]

2026-09-09 18:28:44,015 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:44,031 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:44,046 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:44,061 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:44,078 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:44,094 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:44,110 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  85%|████████▍ | 18705/22132 [06:58<00:57, 59.20it/s]

2026-09-09 18:28:44,126 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:44,141 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:44,156 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:44,173 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:44,188 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:44,204 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:44,220 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  85%|████████▍ | 18712/22132 [06:58<00:56, 60.57it/s]

2026-09-09 18:28:44,236 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:44,252 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:44,268 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:44,286 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:44,302 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:44,319 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:44,335 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  85%|████████▍ | 18719/22132 [06:58<00:56, 60.64it/s]

2026-09-09 18:28:44,354 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:44,369 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:44,389 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:44,407 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:44,422 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:44,439 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:44,456 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  85%|████████▍ | 18726/22132 [06:58<00:57, 59.67it/s]

2026-09-09 18:28:44,474 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:44,490 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:44,508 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:44,527 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:44,543 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:44,559 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  85%|████████▍ | 18732/22132 [06:58<00:57, 59.33it/s]

2026-09-09 18:28:44,576 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:44,595 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:44,614 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:44,637 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:44,659 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:44,684 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  85%|████████▍ | 18738/22132 [06:58<01:00, 55.65it/s]

2026-09-09 18:28:44,701 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:44,718 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:44,736 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:44,752 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:44,769 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:44,787 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  85%|████████▍ | 18744/22132 [06:58<01:00, 56.34it/s]

2026-09-09 18:28:44,808 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:44,825 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:44,841 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:44,859 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:44,875 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:44,893 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  85%|████████▍ | 18750/22132 [06:59<01:00, 56.35it/s]

2026-09-09 18:28:44,910 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:44,926 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:44,941 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:44,957 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:44,973 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:44,989 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:45,006 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  85%|████████▍ | 18757/22132 [06:59<00:58, 58.12it/s]

2026-09-09 18:28:45,033 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:28:45,051 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:45,071 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:45,090 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:45,109 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:45,126 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  85%|████████▍ | 18763/22132 [06:59<01:00, 55.56it/s]

2026-09-09 18:28:45,152 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:28:45,169 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:45,187 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:45,224 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.036s]
2026-09-09 18:28:45,244 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:45,262 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  85%|████████▍ | 18769/22132 [06:59<01:05, 51.62it/s]

2026-09-09 18:28:45,282 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:45,299 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:45,316 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:45,333 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:45,350 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:45,367 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  85%|████████▍ | 18775/22132 [06:59<01:03, 53.21it/s]

2026-09-09 18:28:45,384 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:45,400 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:45,417 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:45,433 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:45,452 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:45,470 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  85%|████████▍ | 18781/22132 [06:59<01:01, 54.53it/s]

2026-09-09 18:28:45,488 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:45,506 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:45,523 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:45,541 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:45,559 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:45,578 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  85%|████████▍ | 18787/22132 [06:59<01:00, 54.85it/s]

2026-09-09 18:28:45,596 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:45,615 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:45,632 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:45,649 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:45,665 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:45,681 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  85%|████████▍ | 18793/22132 [06:59<00:59, 55.81it/s]

2026-09-09 18:28:45,698 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:45,714 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:45,730 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:45,747 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:45,769 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:45,789 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  85%|████████▍ | 18799/22132 [06:59<00:59, 55.77it/s]

2026-09-09 18:28:45,806 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:45,824 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:45,839 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:45,855 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:45,871 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:45,888 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:45,905 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  85%|████████▍ | 18806/22132 [07:00<00:58, 57.17it/s]

2026-09-09 18:28:45,924 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:45,942 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:45,960 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:45,976 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:45,992 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:46,011 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  85%|████████▍ | 18812/22132 [07:00<00:58, 57.05it/s]

2026-09-09 18:28:46,033 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:46,059 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:28:46,077 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:46,094 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:46,112 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:46,129 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  85%|████████▌ | 18818/22132 [07:00<01:00, 55.15it/s]

2026-09-09 18:28:46,146 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:46,163 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:46,179 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:46,195 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:46,211 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:46,227 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:46,244 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  85%|████████▌ | 18825/22132 [07:00<00:58, 56.85it/s]

2026-09-09 18:28:46,260 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:46,276 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:46,291 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:46,308 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:46,324 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:46,340 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:46,356 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  85%|████████▌ | 18832/22132 [07:00<00:56, 58.56it/s]

2026-09-09 18:28:46,373 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:46,390 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:46,408 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:46,425 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:46,442 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:46,462 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  85%|████████▌ | 18838/22132 [07:00<00:56, 58.04it/s]

2026-09-09 18:28:46,480 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:46,497 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:46,513 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:46,530 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:46,547 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:46,562 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  85%|████████▌ | 18844/22132 [07:00<00:56, 58.52it/s]

2026-09-09 18:28:46,579 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:46,595 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:46,610 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:46,626 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:46,642 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:46,658 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:46,675 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  85%|████████▌ | 18851/22132 [07:00<00:55, 59.51it/s]

2026-09-09 18:28:46,697 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:46,716 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:46,732 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:46,749 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:46,765 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:46,780 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  85%|████████▌ | 18857/22132 [07:00<00:55, 58.91it/s]

2026-09-09 18:28:46,796 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:46,813 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:46,830 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:46,846 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:46,863 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:46,880 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  85%|████████▌ | 18863/22132 [07:01<00:55, 59.19it/s]

2026-09-09 18:28:46,896 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:46,915 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:46,931 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:46,949 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:46,965 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:46,981 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  85%|████████▌ | 18869/22132 [07:01<00:55, 59.28it/s]

2026-09-09 18:28:46,998 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:47,015 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:47,031 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:47,048 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:47,065 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:47,081 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:47,096 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  85%|████████▌ | 18876/22132 [07:01<00:54, 59.71it/s]

2026-09-09 18:28:47,113 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:47,129 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:47,147 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:47,163 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:47,179 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:47,196 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:47,212 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  85%|████████▌ | 18883/22132 [07:01<00:54, 59.94it/s]

2026-09-09 18:28:47,230 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:47,246 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:47,263 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:47,279 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:47,294 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:47,310 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:47,327 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  85%|████████▌ | 18890/22132 [07:01<00:53, 60.31it/s]

2026-09-09 18:28:47,343 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:47,359 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:47,375 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:47,392 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:47,409 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:47,426 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:47,441 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  85%|████████▌ | 18897/22132 [07:01<00:53, 60.63it/s]

2026-09-09 18:28:47,456 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:47,472 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:47,488 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:47,505 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:47,521 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:47,540 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:47,556 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  85%|████████▌ | 18904/22132 [07:01<00:53, 60.62it/s]

2026-09-09 18:28:47,573 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:47,588 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:47,603 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:47,620 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:47,637 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:47,654 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:47,675 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  85%|████████▌ | 18911/22132 [07:01<00:53, 60.09it/s]

2026-09-09 18:28:47,692 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:47,708 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:47,724 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:47,742 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:47,760 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:47,782 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:47,800 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  85%|████████▌ | 18918/22132 [07:01<00:54, 58.84it/s]

2026-09-09 18:28:47,818 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:47,836 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:47,859 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:47,881 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:47,898 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:47,915 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  86%|████████▌ | 18924/22132 [07:02<00:56, 56.82it/s]

2026-09-09 18:28:47,933 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:47,952 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:47,969 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:47,988 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:48,006 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:48,025 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  86%|████████▌ | 18930/22132 [07:02<00:56, 56.23it/s]

2026-09-09 18:28:48,042 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:48,059 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:48,078 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:48,096 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:48,114 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:48,131 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  86%|████████▌ | 18936/22132 [07:02<00:56, 56.29it/s]

2026-09-09 18:28:48,149 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:48,167 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:48,184 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:48,201 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:48,220 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:48,236 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  86%|████████▌ | 18942/22132 [07:02<00:56, 56.45it/s]

2026-09-09 18:28:48,256 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:48,274 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:48,290 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:48,313 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:48,330 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:48,347 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  86%|████████▌ | 18948/22132 [07:02<00:57, 55.81it/s]

2026-09-09 18:28:48,367 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:48,384 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:48,403 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:48,423 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:48,439 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:48,457 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  86%|████████▌ | 18954/22132 [07:02<00:57, 55.34it/s]

2026-09-09 18:28:48,476 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:48,493 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:48,510 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:48,531 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:48,560 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:28:48,598 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.037s]

Indexing Records:  86%|████████▌ | 18960/22132 [07:02<01:02, 50.85it/s]

2026-09-09 18:28:48,638 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.038s]
2026-09-09 18:28:48,687 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.048s]
2026-09-09 18:28:48,715 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:28:48,744 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:28:48,766 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:48,792 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]

Indexing Records:  86%|████████▌ | 18966/22132 [07:02<01:14, 42.73it/s]

2026-09-09 18:28:48,812 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:48,836 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:48,863 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:28:48,880 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:48,898 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  86%|████████▌ | 18971/22132 [07:03<01:12, 43.82it/s]

2026-09-09 18:28:48,916 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:48,940 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:28:48,970 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:28:48,999 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:28:49,018 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  86%|████████▌ | 18976/22132 [07:03<01:13, 43.20it/s]

2026-09-09 18:28:49,036 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:49,053 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:49,071 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:49,089 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:49,107 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:49,128 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  86%|████████▌ | 18982/22132 [07:03<01:08, 46.24it/s]

2026-09-09 18:28:49,149 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:49,185 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]
2026-09-09 18:28:49,212 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:28:49,251 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.037s]
2026-09-09 18:28:49,291 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.039s]

Indexing Records:  86%|████████▌ | 18987/22132 [07:03<01:17, 40.59it/s]

2026-09-09 18:28:49,310 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:49,328 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:49,345 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:49,363 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:49,380 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:49,404 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  86%|████████▌ | 18993/22132 [07:03<01:11, 43.91it/s]

2026-09-09 18:28:49,426 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:49,457 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:28:49,490 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:28:49,515 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:28:49,533 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  86%|████████▌ | 18998/22132 [07:03<01:14, 42.34it/s]

2026-09-09 18:28:49,551 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:49,568 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:49,587 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:49,605 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:49,622 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:49,647 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  86%|████████▌ | 19004/22132 [07:03<01:09, 45.19it/s]

2026-09-09 18:28:49,664 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:49,681 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:49,700 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:49,723 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:49,742 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:49,760 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  86%|████████▌ | 19010/22132 [07:03<01:05, 47.40it/s]

2026-09-09 18:28:49,778 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:49,798 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:49,816 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:49,833 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:49,850 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:49,870 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  86%|████████▌ | 19016/22132 [07:04<01:03, 49.37it/s]

2026-09-09 18:28:49,889 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:49,907 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:49,932 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:28:49,951 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:49,968 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:49,987 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  86%|████████▌ | 19022/22132 [07:04<01:02, 49.99it/s]

2026-09-09 18:28:50,007 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:50,025 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:50,045 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:50,063 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:50,081 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:50,104 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  86%|████████▌ | 19028/22132 [07:04<01:01, 50.34it/s]

2026-09-09 18:28:50,122 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:50,146 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:50,167 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:50,187 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:50,204 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:50,221 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  86%|████████▌ | 19034/22132 [07:04<01:01, 50.64it/s]

2026-09-09 18:28:50,239 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:50,302 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.062s]
2026-09-09 18:28:50,319 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:50,336 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:50,353 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:50,370 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  86%|████████▌ | 19040/22132 [07:04<01:05, 46.93it/s]

2026-09-09 18:28:50,390 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:50,408 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:50,425 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:50,444 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:50,461 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:50,478 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  86%|████████▌ | 19046/22132 [07:04<01:02, 49.25it/s]

2026-09-09 18:28:50,496 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:50,513 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:50,532 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:50,549 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:50,568 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:50,590 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  86%|████████▌ | 19052/22132 [07:04<01:00, 50.51it/s]

2026-09-09 18:28:50,608 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:50,627 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:50,644 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:50,663 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:50,683 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:50,701 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  86%|████████▌ | 19058/22132 [07:04<00:59, 51.53it/s]

2026-09-09 18:28:50,719 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:50,737 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:50,756 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:50,775 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:50,793 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:50,810 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  86%|████████▌ | 19064/22132 [07:04<00:58, 52.53it/s]

2026-09-09 18:28:50,840 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:28:50,864 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:50,883 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:50,901 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:50,918 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:50,936 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  86%|████████▌ | 19070/22132 [07:05<01:00, 50.96it/s]

2026-09-09 18:28:50,954 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:50,973 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:50,991 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:51,008 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:51,029 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:51,046 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  86%|████████▌ | 19076/22132 [07:05<00:58, 51.99it/s]

2026-09-09 18:28:51,066 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:51,084 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:51,101 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:51,120 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:51,137 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:51,156 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  86%|████████▌ | 19082/22132 [07:05<00:57, 52.67it/s]

2026-09-09 18:28:51,174 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:51,192 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:51,209 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:51,227 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:51,244 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:51,264 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  86%|████████▌ | 19088/22132 [07:05<00:56, 53.57it/s]

2026-09-09 18:28:51,291 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:28:51,313 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:51,331 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:51,350 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:51,388 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.036s]
2026-09-09 18:28:51,406 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  86%|████████▋ | 19094/22132 [07:05<01:01, 49.64it/s]

2026-09-09 18:28:51,424 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:51,442 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:51,459 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:51,478 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:51,497 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:51,524 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]

Indexing Records:  86%|████████▋ | 19100/22132 [07:05<01:00, 49.88it/s]

2026-09-09 18:28:51,557 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:28:51,580 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:51,598 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:51,615 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:51,635 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:51,652 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  86%|████████▋ | 19106/22132 [07:05<01:01, 48.98it/s]

2026-09-09 18:28:51,669 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:51,697 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:28:51,716 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:51,735 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:51,754 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  86%|████████▋ | 19111/22132 [07:05<01:01, 49.00it/s]

2026-09-09 18:28:51,779 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:28:51,796 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:51,825 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:28:51,845 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:51,865 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  86%|████████▋ | 19116/22132 [07:06<01:02, 47.88it/s]

2026-09-09 18:28:51,888 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:51,908 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:51,928 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:51,950 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:51,972 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  86%|████████▋ | 19121/22132 [07:06<01:03, 47.48it/s]

2026-09-09 18:28:51,993 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:52,013 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:52,038 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:28:52,067 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:28:52,100 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]

Indexing Records:  86%|████████▋ | 19126/22132 [07:06<01:07, 44.82it/s]

2026-09-09 18:28:52,124 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:52,144 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:52,167 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:52,188 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:52,208 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  86%|████████▋ | 19131/22132 [07:06<01:06, 45.15it/s]

2026-09-09 18:28:52,229 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:52,259 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:28:52,282 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:52,305 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:52,334 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]

Indexing Records:  86%|████████▋ | 19136/22132 [07:06<01:08, 43.45it/s]

2026-09-09 18:28:52,354 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:52,373 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:52,394 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:52,416 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:52,438 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  86%|████████▋ | 19141/22132 [07:06<01:06, 44.67it/s]

2026-09-09 18:28:52,461 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:52,479 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:52,496 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:52,514 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:52,532 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:52,550 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  87%|████████▋ | 19147/22132 [07:06<01:02, 47.40it/s]

2026-09-09 18:28:52,569 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:52,587 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:52,605 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:52,622 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:52,640 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:52,659 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  87%|████████▋ | 19153/22132 [07:06<01:00, 49.60it/s]

2026-09-09 18:28:52,677 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:52,694 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:52,712 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:52,731 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:52,748 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:52,766 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  87%|████████▋ | 19159/22132 [07:06<00:57, 51.43it/s]

2026-09-09 18:28:52,784 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:52,803 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:52,822 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:52,844 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:52,862 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:52,879 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  87%|████████▋ | 19165/22132 [07:07<00:57, 51.90it/s]

2026-09-09 18:28:52,897 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:52,916 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:52,933 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:52,950 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:52,967 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:52,985 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  87%|████████▋ | 19171/22132 [07:07<00:55, 53.39it/s]

2026-09-09 18:28:53,006 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:53,023 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:53,042 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:53,059 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:53,076 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:53,094 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  87%|████████▋ | 19177/22132 [07:07<00:54, 53.84it/s]

2026-09-09 18:28:53,112 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:53,129 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:53,146 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:53,169 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:53,215 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.044s]
2026-09-09 18:28:53,235 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  87%|████████▋ | 19183/22132 [07:07<00:59, 49.83it/s]

2026-09-09 18:28:53,255 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:53,273 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:53,294 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:53,312 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:53,330 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:53,347 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  87%|████████▋ | 19189/22132 [07:07<00:57, 50.83it/s]

2026-09-09 18:28:53,365 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:53,383 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:53,403 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:53,422 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:53,439 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:53,458 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  87%|████████▋ | 19195/22132 [07:07<00:56, 51.87it/s]

2026-09-09 18:28:53,475 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:53,494 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:53,512 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:53,529 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:53,546 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:53,563 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  87%|████████▋ | 19201/22132 [07:07<00:54, 53.30it/s]

2026-09-09 18:28:53,582 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:53,599 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:53,618 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:53,635 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:53,652 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:53,670 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  87%|████████▋ | 19207/22132 [07:07<00:54, 54.15it/s]

2026-09-09 18:28:53,693 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:53,712 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:53,729 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:53,749 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:53,769 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:53,786 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  87%|████████▋ | 19213/22132 [07:07<00:54, 53.32it/s]

2026-09-09 18:28:53,806 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:53,824 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:53,841 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:53,858 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:53,876 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:53,894 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  87%|████████▋ | 19219/22132 [07:08<00:53, 53.98it/s]

2026-09-09 18:28:53,913 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:53,940 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:28:53,958 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:53,975 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:53,994 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:54,011 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  87%|████████▋ | 19225/22132 [07:08<00:54, 53.10it/s]

2026-09-09 18:28:54,030 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:54,049 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:54,067 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:54,087 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:54,105 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:54,124 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  87%|████████▋ | 19231/22132 [07:08<00:54, 53.18it/s]

2026-09-09 18:28:54,143 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:54,162 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:54,179 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:54,197 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:54,214 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:54,231 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  87%|████████▋ | 19237/22132 [07:08<00:53, 53.97it/s]

2026-09-09 18:28:54,250 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:54,269 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:54,288 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:54,308 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:54,326 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:54,343 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  87%|████████▋ | 19243/22132 [07:08<00:53, 53.78it/s]

2026-09-09 18:28:54,361 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:54,379 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:54,396 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:54,415 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:54,434 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:54,452 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  87%|████████▋ | 19249/22132 [07:08<00:53, 54.25it/s]

2026-09-09 18:28:54,470 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:54,488 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:54,505 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:54,523 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:54,541 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:54,559 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  87%|████████▋ | 19255/22132 [07:08<00:52, 54.82it/s]

2026-09-09 18:28:54,577 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:54,595 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:54,614 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:54,631 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:54,648 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:54,667 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  87%|████████▋ | 19261/22132 [07:08<00:52, 55.07it/s]

2026-09-09 18:28:54,686 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:54,704 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:54,721 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:54,739 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:54,757 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:54,774 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  87%|████████▋ | 19267/22132 [07:08<00:51, 55.24it/s]

2026-09-09 18:28:54,800 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:28:54,817 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:54,838 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:54,856 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:54,875 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:54,892 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  87%|████████▋ | 19273/22132 [07:09<00:53, 53.85it/s]

2026-09-09 18:28:54,911 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:54,931 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:54,950 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:54,968 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:54,986 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:55,004 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  87%|████████▋ | 19279/22132 [07:09<00:53, 53.82it/s]

2026-09-09 18:28:55,025 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:55,043 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:55,060 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:55,077 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:55,097 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:55,114 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  87%|████████▋ | 19285/22132 [07:09<00:52, 54.06it/s]

2026-09-09 18:28:55,132 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:55,150 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:55,169 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:55,189 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:55,206 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:55,224 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  87%|████████▋ | 19291/22132 [07:09<00:52, 54.24it/s]

2026-09-09 18:28:55,242 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:55,259 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:55,278 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:55,296 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:55,315 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:55,332 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  87%|████████▋ | 19297/22132 [07:09<00:51, 54.54it/s]

2026-09-09 18:28:55,351 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:55,370 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:55,390 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:55,408 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:55,426 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:55,443 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  87%|████████▋ | 19303/22132 [07:09<00:52, 54.37it/s]

2026-09-09 18:28:55,462 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:55,481 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:55,499 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:55,516 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:55,533 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:55,551 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  87%|████████▋ | 19309/22132 [07:09<00:51, 54.71it/s]

2026-09-09 18:28:55,571 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:55,588 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:55,605 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:55,623 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:55,641 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:55,658 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  87%|████████▋ | 19315/22132 [07:09<00:51, 55.19it/s]

2026-09-09 18:28:55,679 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:55,697 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:55,716 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:55,735 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:55,753 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:55,773 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  87%|████████▋ | 19321/22132 [07:09<00:51, 54.16it/s]

2026-09-09 18:28:55,794 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:55,813 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:55,844 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:28:55,863 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:55,881 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:55,899 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  87%|████████▋ | 19327/22132 [07:10<00:53, 52.05it/s]

2026-09-09 18:28:55,918 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:55,936 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:55,954 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:55,972 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:55,990 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:56,008 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  87%|████████▋ | 19333/22132 [07:10<00:52, 52.93it/s]

2026-09-09 18:28:56,030 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:56,048 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:56,068 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:56,086 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:56,105 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:56,123 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  87%|████████▋ | 19339/22132 [07:10<00:53, 52.69it/s]

2026-09-09 18:28:56,148 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:28:56,168 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:56,186 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:56,207 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:56,227 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:56,244 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  87%|████████▋ | 19345/22132 [07:10<00:53, 51.70it/s]

2026-09-09 18:28:56,263 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:56,281 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:56,302 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:56,320 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:56,338 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:56,356 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  87%|████████▋ | 19351/22132 [07:10<00:53, 52.26it/s]

2026-09-09 18:28:56,375 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:56,395 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:56,413 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:56,433 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:56,451 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:56,468 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  87%|████████▋ | 19357/22132 [07:10<00:52, 52.62it/s]

2026-09-09 18:28:56,487 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:56,506 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:56,524 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:56,541 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:56,559 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:56,579 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  87%|████████▋ | 19363/22132 [07:10<00:52, 53.10it/s]

2026-09-09 18:28:56,599 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:56,617 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:56,635 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:56,653 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:56,672 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:56,691 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  88%|████████▊ | 19369/22132 [07:10<00:51, 53.21it/s]

2026-09-09 18:28:56,744 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.050s]
2026-09-09 18:28:56,765 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:56,780 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:56,796 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:56,813 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:56,829 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  88%|████████▊ | 19375/22132 [07:10<00:55, 49.91it/s]

2026-09-09 18:28:56,845 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:56,861 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:56,876 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:28:56,892 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:28:56,912 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:56,929 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  88%|████████▊ | 19381/22132 [07:11<00:52, 52.49it/s]

2026-09-09 18:28:56,947 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:56,964 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:56,982 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:57,000 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:57,019 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:57,036 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  88%|████████▊ | 19387/22132 [07:11<00:51, 53.57it/s]

2026-09-09 18:28:57,058 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:57,075 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:57,093 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:57,111 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:57,132 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:57,152 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  88%|████████▊ | 19393/22132 [07:11<00:51, 53.06it/s]

2026-09-09 18:28:57,170 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:57,188 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:57,206 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:57,226 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:57,244 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:57,263 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  88%|████████▊ | 19399/22132 [07:11<00:51, 53.32it/s]

2026-09-09 18:28:57,284 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:57,303 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:57,320 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:57,338 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:57,356 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:57,374 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  88%|████████▊ | 19405/22132 [07:11<00:50, 53.57it/s]

2026-09-09 18:28:57,394 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:57,412 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:57,429 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:57,448 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:57,465 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:57,483 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  88%|████████▊ | 19411/22132 [07:11<00:50, 53.99it/s]

2026-09-09 18:28:57,501 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:57,521 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:57,539 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:57,557 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:57,578 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:28:57,595 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  88%|████████▊ | 19417/22132 [07:11<00:50, 53.79it/s]

2026-09-09 18:28:57,614 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:57,631 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:57,651 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:57,669 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:57,688 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:57,707 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  88%|████████▊ | 19423/22132 [07:11<00:50, 53.74it/s]

2026-09-09 18:28:57,728 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:57,748 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:57,767 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:57,785 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:57,803 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:57,823 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  88%|████████▊ | 19429/22132 [07:11<00:50, 53.07it/s]

2026-09-09 18:28:57,842 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:57,860 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:57,877 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:57,896 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:57,913 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:57,933 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  88%|████████▊ | 19435/22132 [07:12<00:50, 53.52it/s]

2026-09-09 18:28:57,952 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:57,970 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:57,990 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:58,008 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:58,027 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:58,047 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  88%|████████▊ | 19441/22132 [07:12<00:50, 53.28it/s]

2026-09-09 18:28:58,065 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:58,083 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:58,103 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:58,120 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:58,139 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:58,157 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  88%|████████▊ | 19447/22132 [07:12<00:49, 53.71it/s]

2026-09-09 18:28:58,175 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:58,194 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:58,214 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:58,232 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:58,252 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:58,270 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  88%|████████▊ | 19453/22132 [07:12<00:50, 53.44it/s]

2026-09-09 18:28:58,289 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:58,308 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:58,326 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:58,346 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:58,366 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:58,384 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  88%|████████▊ | 19459/22132 [07:12<00:50, 53.22it/s]

2026-09-09 18:28:58,404 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:58,423 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:58,443 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:58,462 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:58,480 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:58,497 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  88%|████████▊ | 19465/22132 [07:12<00:50, 53.23it/s]

2026-09-09 18:28:58,515 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:58,533 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:58,551 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:58,569 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:58,588 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:58,606 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  88%|████████▊ | 19471/22132 [07:12<00:49, 53.76it/s]

2026-09-09 18:28:58,627 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:58,660 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:28:58,680 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:58,707 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:28:58,768 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.060s]
2026-09-09 18:28:58,825 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.055s]

Indexing Records:  88%|████████▊ | 19477/22132 [07:12<01:03, 41.72it/s]

2026-09-09 18:28:58,859 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:28:58,883 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:28:58,903 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:58,924 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:58,945 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  88%|████████▊ | 19482/22132 [07:13<01:03, 41.67it/s]

2026-09-09 18:28:58,966 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:58,985 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:59,004 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:59,023 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:59,042 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:59,061 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  88%|████████▊ | 19488/22132 [07:13<00:59, 44.41it/s]

2026-09-09 18:28:59,080 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:59,101 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:59,121 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:59,142 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:59,161 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  88%|████████▊ | 19493/22132 [07:13<00:57, 45.71it/s]

2026-09-09 18:28:59,182 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:59,204 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:59,223 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:59,241 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:59,263 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  88%|████████▊ | 19498/22132 [07:13<00:56, 46.68it/s]

2026-09-09 18:28:59,282 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:59,301 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:59,320 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:59,338 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:59,356 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:59,376 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  88%|████████▊ | 19504/22132 [07:13<00:54, 48.54it/s]

2026-09-09 18:28:59,396 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:59,414 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:59,432 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:59,450 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:59,468 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:59,485 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  88%|████████▊ | 19510/22132 [07:13<00:52, 50.34it/s]

2026-09-09 18:28:59,506 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:59,524 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:59,542 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:59,561 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:59,579 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:59,597 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  88%|████████▊ | 19516/22132 [07:13<00:50, 51.40it/s]

2026-09-09 18:28:59,616 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:59,635 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:59,656 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:59,676 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:59,696 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:59,716 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  88%|████████▊ | 19522/22132 [07:13<00:51, 51.08it/s]

2026-09-09 18:28:59,736 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:59,755 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:59,774 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:59,793 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:59,811 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:28:59,828 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  88%|████████▊ | 19528/22132 [07:13<00:50, 51.72it/s]

2026-09-09 18:28:59,847 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:59,866 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:28:59,886 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:28:59,905 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:59,926 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:28:59,944 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  88%|████████▊ | 19534/22132 [07:14<00:50, 51.77it/s]

2026-09-09 18:28:59,963 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:28:59,981 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:00,002 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:00,054 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.051s]
2026-09-09 18:29:00,094 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.038s]
2026-09-09 18:29:00,129 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]

Indexing Records:  88%|████████▊ | 19540/22132 [07:14<00:59, 43.87it/s]

2026-09-09 18:29:00,169 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.038s]
2026-09-09 18:29:00,187 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:00,208 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:00,228 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:00,247 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  88%|████████▊ | 19545/22132 [07:14<00:59, 43.50it/s]

2026-09-09 18:29:00,266 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:00,296 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:29:00,330 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]
2026-09-09 18:29:00,349 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:00,368 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  88%|████████▊ | 19550/22132 [07:14<01:00, 42.81it/s]

2026-09-09 18:29:00,388 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:00,406 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:00,425 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:00,446 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:00,465 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:00,483 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  88%|████████▊ | 19556/22132 [07:14<00:56, 45.43it/s]

2026-09-09 18:29:00,502 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:00,520 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:00,537 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:00,611 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.073s]
2026-09-09 18:29:00,642 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]

Indexing Records:  88%|████████▊ | 19561/22132 [07:14<01:03, 40.46it/s]

2026-09-09 18:29:00,664 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:00,688 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:29:00,707 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:00,726 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:00,746 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  88%|████████▊ | 19566/22132 [07:14<01:00, 42.41it/s]

2026-09-09 18:29:00,765 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:00,794 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:29:00,815 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:00,840 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:29:00,860 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  88%|████████▊ | 19571/22132 [07:15<01:00, 42.48it/s]

2026-09-09 18:29:00,885 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:00,905 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:00,926 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:00,954 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:29:00,973 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  88%|████████▊ | 19576/22132 [07:15<00:59, 43.30it/s]

2026-09-09 18:29:00,994 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:01,015 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:01,037 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:29:01,056 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:01,077 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  88%|████████▊ | 19581/22132 [07:15<00:57, 44.65it/s]

2026-09-09 18:29:01,096 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:01,115 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:01,134 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:01,161 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:29:01,203 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.040s]

Indexing Records:  88%|████████▊ | 19586/22132 [07:15<00:59, 43.06it/s]

2026-09-09 18:29:01,233 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:29:01,253 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:01,272 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:01,297 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:29:01,339 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.041s]

Indexing Records:  89%|████████▊ | 19591/22132 [07:15<01:02, 40.93it/s]

2026-09-09 18:29:01,378 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.037s]
2026-09-09 18:29:01,398 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:01,419 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:01,442 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:29:01,463 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  89%|████████▊ | 19596/22132 [07:15<01:02, 40.78it/s]

2026-09-09 18:29:01,484 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:01,507 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:29:01,526 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:01,551 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:29:01,589 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.036s]

Indexing Records:  89%|████████▊ | 19601/22132 [07:15<01:02, 40.43it/s]

2026-09-09 18:29:01,632 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.041s]
2026-09-09 18:29:01,667 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]
2026-09-09 18:29:01,714 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.045s]
2026-09-09 18:29:01,767 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.052s]
2026-09-09 18:29:01,814 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.046s]

Indexing Records:  89%|████████▊ | 19606/22132 [07:15<01:17, 32.47it/s]

2026-09-09 18:29:01,877 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.061s]
2026-09-09 18:29:01,993 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.114s]
2026-09-09 18:29:02,054 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.060s]
2026-09-09 18:29:02,094 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.039s]

Indexing Records:  89%|████████▊ | 19610/22132 [07:16<01:42, 24.52it/s]

2026-09-09 18:29:02,165 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.069s]
2026-09-09 18:29:02,236 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.069s]
2026-09-09 18:29:02,273 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.036s]

Indexing Records:  89%|████████▊ | 19613/22132 [07:16<01:52, 22.31it/s]

2026-09-09 18:29:02,307 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:29:02,354 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.045s]
2026-09-09 18:29:02,397 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.042s]

Indexing Records:  89%|████████▊ | 19616/22132 [07:16<01:50, 22.72it/s]

2026-09-09 18:29:02,440 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.041s]
2026-09-09 18:29:02,471 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:29:02,502 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]

Indexing Records:  89%|████████▊ | 19619/22132 [07:16<01:44, 23.96it/s]

2026-09-09 18:29:02,536 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:29:02,577 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.040s]
2026-09-09 18:29:02,610 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]

Indexing Records:  89%|████████▊ | 19622/22132 [07:16<01:41, 24.84it/s]

2026-09-09 18:29:02,649 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.036s]
2026-09-09 18:29:02,674 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:29:02,713 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.038s]

Indexing Records:  89%|████████▊ | 19625/22132 [07:16<01:36, 25.87it/s]

2026-09-09 18:29:02,736 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:29:02,758 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:29:02,796 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.036s]
2026-09-09 18:29:02,823 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]

Indexing Records:  89%|████████▊ | 19629/22132 [07:16<01:27, 28.75it/s]

2026-09-09 18:29:02,869 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.044s]
2026-09-09 18:29:02,901 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:29:02,927 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:29:02,954 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]

Indexing Records:  89%|████████▊ | 19633/22132 [07:17<01:25, 29.29it/s]

2026-09-09 18:29:02,976 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:03,004 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:29:03,028 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:29:03,069 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.040s]

Indexing Records:  89%|████████▊ | 19637/22132 [07:17<01:20, 30.84it/s]

2026-09-09 18:29:03,099 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:29:03,133 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]
2026-09-09 18:29:03,167 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]
2026-09-09 18:29:03,231 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.062s]

Indexing Records:  89%|████████▊ | 19641/22132 [07:17<01:26, 28.63it/s]

2026-09-09 18:29:03,287 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.054s]
2026-09-09 18:29:03,346 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.057s]
2026-09-09 18:29:03,381 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]

Indexing Records:  89%|████████▉ | 19644/22132 [07:17<01:36, 25.81it/s]

2026-09-09 18:29:03,406 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:29:03,442 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]
2026-09-09 18:29:03,473 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:29:03,501 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]

Indexing Records:  89%|████████▉ | 19648/22132 [07:17<01:29, 27.88it/s]

2026-09-09 18:29:03,539 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.036s]
2026-09-09 18:29:03,568 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:29:03,608 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.039s]

Indexing Records:  89%|████████▉ | 19651/22132 [07:17<01:28, 27.89it/s]

2026-09-09 18:29:03,656 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.046s]
2026-09-09 18:29:03,695 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.038s]
2026-09-09 18:29:03,743 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.047s]

Indexing Records:  89%|████████▉ | 19654/22132 [07:17<01:35, 26.08it/s]

2026-09-09 18:29:03,816 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.071s]
2026-09-09 18:29:03,852 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]
2026-09-09 18:29:03,880 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]

Indexing Records:  89%|████████▉ | 19657/22132 [07:18<01:39, 24.80it/s]

2026-09-09 18:29:03,919 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.037s]
2026-09-09 18:29:03,953 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:29:03,982 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]

Indexing Records:  89%|████████▉ | 19660/22132 [07:18<01:35, 25.93it/s]

2026-09-09 18:29:04,012 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:29:04,051 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.038s]
2026-09-09 18:29:04,094 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.041s]

Indexing Records:  89%|████████▉ | 19663/22132 [07:18<01:34, 26.21it/s]

2026-09-09 18:29:04,126 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:29:04,155 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:29:04,207 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.051s]

Indexing Records:  89%|████████▉ | 19666/22132 [07:18<01:33, 26.27it/s]

2026-09-09 18:29:04,230 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:29:04,250 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:04,293 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.041s]
2026-09-09 18:29:04,512 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.218s]

Indexing Records:  89%|████████▉ | 19670/22132 [07:18<02:07, 19.35it/s]

2026-09-09 18:29:04,543 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:29:04,576 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:29:04,608 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:29:04,631 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  89%|████████▉ | 19674/22132 [07:18<01:48, 22.59it/s]

2026-09-09 18:29:04,665 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]
2026-09-09 18:29:04,691 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:29:04,753 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.061s]

Indexing Records:  89%|████████▉ | 19677/22132 [07:18<01:46, 23.11it/s]

2026-09-09 18:29:04,785 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:29:04,813 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:29:04,844 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:29:04,876 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]

Indexing Records:  89%|████████▉ | 19681/22132 [07:19<01:35, 25.58it/s]

2026-09-09 18:29:04,899 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:29:04,932 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:29:04,963 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:29:05,005 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.041s]

Indexing Records:  89%|████████▉ | 19685/22132 [07:19<01:30, 27.14it/s]

2026-09-09 18:29:05,043 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.036s]
2026-09-09 18:29:05,067 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:29:05,099 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:29:05,125 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]

Indexing Records:  89%|████████▉ | 19689/22132 [07:19<01:24, 28.77it/s]

2026-09-09 18:29:05,167 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.040s]
2026-09-09 18:29:05,196 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:29:05,231 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]

Indexing Records:  89%|████████▉ | 19692/22132 [07:19<01:25, 28.70it/s]

2026-09-09 18:29:05,256 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:29:05,285 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:29:05,321 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]
2026-09-09 18:29:05,349 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]

Indexing Records:  89%|████████▉ | 19696/22132 [07:19<01:20, 30.23it/s]

2026-09-09 18:29:05,380 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:29:05,410 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:29:05,450 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.038s]
2026-09-09 18:29:05,482 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]

Indexing Records:  89%|████████▉ | 19700/22132 [07:19<01:20, 30.17it/s]

2026-09-09 18:29:05,526 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.042s]
2026-09-09 18:29:05,562 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]
2026-09-09 18:29:05,612 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.049s]
2026-09-09 18:29:05,653 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.041s]

Indexing Records:  89%|████████▉ | 19704/22132 [07:19<01:27, 27.63it/s]

2026-09-09 18:29:05,686 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:29:05,710 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:29:05,735 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:29:05,806 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.069s]

Indexing Records:  89%|████████▉ | 19708/22132 [07:19<01:29, 27.20it/s]

2026-09-09 18:29:05,834 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:29:05,862 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:29:05,894 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:29:05,938 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.042s]

Indexing Records:  89%|████████▉ | 19712/22132 [07:20<01:26, 28.09it/s]

2026-09-09 18:29:05,969 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:29:05,990 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:06,032 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.041s]
2026-09-09 18:29:06,065 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]

Indexing Records:  89%|████████▉ | 19716/22132 [07:20<01:23, 29.03it/s]

2026-09-09 18:29:06,114 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.047s]
2026-09-09 18:29:06,148 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]
2026-09-09 18:29:06,194 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.044s]

Indexing Records:  89%|████████▉ | 19719/22132 [07:20<01:28, 27.36it/s]

2026-09-09 18:29:06,237 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.042s]
2026-09-09 18:29:06,269 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:29:06,305 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]

Indexing Records:  89%|████████▉ | 19722/22132 [07:20<01:28, 27.26it/s]

2026-09-09 18:29:06,324 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:06,345 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:06,362 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:06,397 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]
2026-09-09 18:29:06,416 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  89%|████████▉ | 19727/22132 [07:20<01:14, 32.09it/s]

2026-09-09 18:29:06,435 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:06,466 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:29:06,486 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:06,530 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.043s]

Indexing Records:  89%|████████▉ | 19731/22132 [07:20<01:12, 32.92it/s]

2026-09-09 18:29:06,553 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:06,571 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:06,590 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:06,608 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:06,626 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:06,646 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  89%|████████▉ | 19737/22132 [07:20<01:02, 38.51it/s]

2026-09-09 18:29:06,667 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:06,684 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:06,702 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:06,722 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:06,740 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:06,759 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  89%|████████▉ | 19743/22132 [07:20<00:55, 42.67it/s]

2026-09-09 18:29:06,778 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:06,796 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:06,813 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:06,830 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:06,848 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:06,872 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records:  89%|████████▉ | 19749/22132 [07:21<00:52, 45.72it/s]

2026-09-09 18:29:06,891 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:06,909 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:06,926 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:06,948 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:29:06,966 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:06,983 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  89%|████████▉ | 19755/22132 [07:21<00:49, 48.18it/s]

2026-09-09 18:29:07,003 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:07,025 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:29:07,044 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:07,064 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:07,085 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  89%|████████▉ | 19760/22132 [07:21<00:48, 48.48it/s]

2026-09-09 18:29:07,114 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:29:07,132 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:07,152 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:07,169 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:07,189 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  89%|████████▉ | 19765/22132 [07:21<00:49, 48.23it/s]

2026-09-09 18:29:07,209 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:07,229 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:07,248 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:07,270 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:07,288 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:07,306 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  89%|████████▉ | 19771/22132 [07:21<00:47, 49.26it/s]

2026-09-09 18:29:07,325 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:07,342 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:07,360 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:07,378 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:07,398 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:07,415 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  89%|████████▉ | 19777/22132 [07:21<00:46, 50.91it/s]

2026-09-09 18:29:07,435 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:07,454 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:07,472 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:07,489 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:07,509 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:07,526 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  89%|████████▉ | 19783/22132 [07:21<00:45, 51.86it/s]

2026-09-09 18:29:07,545 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:07,563 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:07,582 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:07,602 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:07,620 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:07,638 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  89%|████████▉ | 19789/22132 [07:21<00:44, 52.37it/s]

2026-09-09 18:29:07,659 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:07,676 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:07,693 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:07,711 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:07,728 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:07,748 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  89%|████████▉ | 19795/22132 [07:21<00:43, 53.12it/s]

2026-09-09 18:29:07,766 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:07,784 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:07,803 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:07,822 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:07,840 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:07,858 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  89%|████████▉ | 19801/22132 [07:21<00:43, 53.52it/s]

2026-09-09 18:29:07,876 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:07,894 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:07,912 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:07,930 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:07,949 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:07,966 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  89%|████████▉ | 19807/22132 [07:22<00:43, 54.03it/s]

2026-09-09 18:29:07,985 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:08,003 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:08,021 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:08,040 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:08,058 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:08,078 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  90%|████████▉ | 19813/22132 [07:22<00:42, 54.00it/s]

2026-09-09 18:29:08,100 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:29:08,125 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:29:08,143 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:08,233 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.088s]
2026-09-09 18:29:08,283 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.049s]
2026-09-09 18:29:08,302 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  90%|████████▉ | 19819/22132 [07:22<00:55, 41.35it/s]

2026-09-09 18:29:08,322 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:08,343 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:08,367 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:29:08,387 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:08,407 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  90%|████████▉ | 19824/22132 [07:22<00:53, 42.80it/s]

2026-09-09 18:29:08,427 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:08,449 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:29:08,476 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:29:08,496 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:08,515 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  90%|████████▉ | 19829/22132 [07:22<00:52, 43.67it/s]

2026-09-09 18:29:08,543 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:29:08,568 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:29:08,592 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:29:08,611 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:08,639 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]

Indexing Records:  90%|████████▉ | 19834/22132 [07:22<00:53, 42.75it/s]

2026-09-09 18:29:08,658 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:08,685 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:29:08,707 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:29:08,727 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:08,747 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  90%|████████▉ | 19839/22132 [07:22<00:52, 43.70it/s]

2026-09-09 18:29:08,769 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:08,788 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:08,809 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:08,827 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:08,849 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  90%|████████▉ | 19844/22132 [07:22<00:50, 45.09it/s]

2026-09-09 18:29:08,874 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:29:08,905 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:29:08,925 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:08,945 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:08,967 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  90%|████████▉ | 19849/22132 [07:23<00:51, 44.32it/s]

2026-09-09 18:29:08,987 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:09,007 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:09,027 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:09,045 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:09,064 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:09,088 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  90%|████████▉ | 19855/22132 [07:23<00:49, 45.94it/s]

2026-09-09 18:29:09,108 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:09,127 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:09,147 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:09,166 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:09,184 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:09,205 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  90%|████████▉ | 19861/22132 [07:23<00:47, 47.53it/s]

2026-09-09 18:29:09,224 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:09,244 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:09,266 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:09,284 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:09,302 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:09,324 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  90%|████████▉ | 19867/22132 [07:23<00:46, 48.38it/s]

2026-09-09 18:29:09,343 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:09,364 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:09,393 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:29:09,412 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:09,430 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  90%|████████▉ | 19872/22132 [07:23<00:47, 48.02it/s]

2026-09-09 18:29:09,452 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:09,473 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:09,492 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:09,511 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:09,529 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:09,547 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  90%|████████▉ | 19878/22132 [07:23<00:45, 49.02it/s]

2026-09-09 18:29:09,567 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:09,588 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:09,607 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:09,641 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:29:09,661 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  90%|████████▉ | 19883/22132 [07:23<00:47, 47.55it/s]

2026-09-09 18:29:09,681 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:09,700 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:09,719 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:09,738 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:09,758 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:09,776 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  90%|████████▉ | 19889/22132 [07:23<00:45, 48.81it/s]

2026-09-09 18:29:09,799 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:29:09,820 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:09,838 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:09,857 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:09,885 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]

Indexing Records:  90%|████████▉ | 19894/22132 [07:24<00:46, 48.07it/s]

2026-09-09 18:29:09,906 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:09,925 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:09,943 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:09,961 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:09,981 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:09,999 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  90%|████████▉ | 19900/22132 [07:24<00:45, 49.36it/s]

2026-09-09 18:29:10,020 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:10,038 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:10,060 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:29:10,079 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:10,100 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  90%|████████▉ | 19905/22132 [07:24<00:45, 49.46it/s]

2026-09-09 18:29:10,120 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:10,139 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:10,166 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:29:10,185 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:10,207 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  90%|████████▉ | 19910/22132 [07:24<00:45, 48.58it/s]

2026-09-09 18:29:10,227 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:10,246 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:10,266 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:10,291 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:29:10,314 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  90%|████████▉ | 19915/22132 [07:24<00:46, 48.15it/s]

2026-09-09 18:29:10,334 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:10,353 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:10,371 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:10,392 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:10,410 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:10,430 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  90%|█████████ | 19921/22132 [07:24<00:44, 49.23it/s]

2026-09-09 18:29:10,449 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:10,468 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:10,488 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:10,507 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:10,525 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:10,544 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  90%|█████████ | 19927/22132 [07:24<00:43, 50.23it/s]

2026-09-09 18:29:10,563 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:10,582 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:10,601 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:10,622 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:10,641 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:10,660 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  90%|█████████ | 19933/22132 [07:24<00:43, 50.73it/s]

2026-09-09 18:29:10,681 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:10,701 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:10,720 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:10,741 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:10,760 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:10,778 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  90%|█████████ | 19939/22132 [07:24<00:43, 50.70it/s]

2026-09-09 18:29:10,798 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:10,822 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:29:10,851 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:29:10,870 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:10,890 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:10,908 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  90%|█████████ | 19945/22132 [07:25<00:44, 49.21it/s]

2026-09-09 18:29:10,943 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.033s]
2026-09-09 18:29:10,963 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:10,985 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:29:11,009 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:29:11,031 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  90%|█████████ | 19950/22132 [07:25<00:46, 46.68it/s]

2026-09-09 18:29:11,054 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:29:11,074 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:11,093 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:11,112 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:11,138 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  90%|█████████ | 19955/22132 [07:25<00:46, 46.70it/s]

2026-09-09 18:29:11,156 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:11,174 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:11,192 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:11,212 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:11,232 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:11,252 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  90%|█████████ | 19961/22132 [07:25<00:44, 48.43it/s]

2026-09-09 18:29:11,271 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:11,290 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:11,310 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:11,331 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:11,353 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  90%|█████████ | 19966/22132 [07:25<00:44, 48.72it/s]

2026-09-09 18:29:11,374 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:11,392 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:11,412 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:11,431 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:11,451 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:11,469 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  90%|█████████ | 19972/22132 [07:25<00:43, 49.57it/s]

2026-09-09 18:29:11,488 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:11,508 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:11,527 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:11,545 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:11,563 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:11,581 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  90%|█████████ | 19978/22132 [07:25<00:42, 50.77it/s]

2026-09-09 18:29:11,603 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:11,621 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:11,641 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:11,659 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:11,677 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:11,696 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  90%|█████████ | 19984/22132 [07:25<00:41, 51.24it/s]

2026-09-09 18:29:11,715 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:11,734 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:11,755 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:11,779 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:29:11,797 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:11,825 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]

Indexing Records:  90%|█████████ | 19990/22132 [07:25<00:43, 49.75it/s]

2026-09-09 18:29:11,841 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:11,858 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:11,875 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:11,891 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:11,906 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:11,922 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:11,939 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  90%|█████████ | 19997/22132 [07:26<00:40, 53.09it/s]

2026-09-09 18:29:11,958 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:11,990 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:29:12,009 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:12,029 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:12,049 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:12,067 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  90%|█████████ | 20003/22132 [07:26<00:41, 51.06it/s]

2026-09-09 18:29:12,084 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:12,100 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:12,118 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:12,135 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:12,158 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:29:12,176 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  90%|█████████ | 20009/22132 [07:26<00:40, 52.23it/s]

2026-09-09 18:29:12,196 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:12,213 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:12,230 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:12,247 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:12,264 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:12,281 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  90%|█████████ | 20015/22132 [07:26<00:39, 53.61it/s]

2026-09-09 18:29:12,298 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:12,316 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:12,335 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:12,353 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:12,371 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:12,387 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  90%|█████████ | 20021/22132 [07:26<00:38, 54.51it/s]

2026-09-09 18:29:12,405 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:12,421 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:12,437 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:12,455 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:12,471 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:12,486 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:12,502 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  90%|█████████ | 20028/22132 [07:26<00:37, 56.42it/s]

2026-09-09 18:29:12,520 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:12,536 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:12,552 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:12,568 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:12,586 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:12,603 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  91%|█████████ | 20034/22132 [07:26<00:36, 57.29it/s]

2026-09-09 18:29:12,619 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:12,636 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:12,651 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:12,668 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:12,685 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:12,701 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:12,716 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  91%|█████████ | 20041/22132 [07:26<00:35, 58.63it/s]

2026-09-09 18:29:12,736 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:12,754 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:12,772 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:12,788 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:12,811 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:29:12,829 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  91%|█████████ | 20047/22132 [07:26<00:36, 56.92it/s]

2026-09-09 18:29:12,847 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:12,871 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:29:12,891 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:12,915 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:29:12,935 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:12,955 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  91%|█████████ | 20053/22132 [07:27<00:38, 53.91it/s]

2026-09-09 18:29:12,974 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:12,991 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:13,009 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:13,029 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:13,047 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:13,064 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  91%|█████████ | 20059/22132 [07:27<00:38, 54.25it/s]

2026-09-09 18:29:13,107 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.041s]
2026-09-09 18:29:13,126 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:13,143 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:13,160 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:13,177 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:13,196 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  91%|█████████ | 20065/22132 [07:27<00:40, 51.30it/s]

2026-09-09 18:29:13,213 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:13,229 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:13,245 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:13,262 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:13,283 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:13,303 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  91%|█████████ | 20071/22132 [07:27<00:39, 52.64it/s]

2026-09-09 18:29:13,324 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:13,430 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.104s]
2026-09-09 18:29:13,450 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:13,471 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:13,488 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:13,505 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  91%|█████████ | 20077/22132 [07:27<00:47, 42.87it/s]

2026-09-09 18:29:13,524 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:13,541 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:13,557 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:13,574 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:13,590 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:13,606 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  91%|█████████ | 20083/22132 [07:27<00:43, 46.69it/s]

2026-09-09 18:29:13,623 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:13,638 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:13,653 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:13,669 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:13,684 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:13,701 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:13,719 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  91%|█████████ | 20090/22132 [07:27<00:40, 50.84it/s]

2026-09-09 18:29:13,739 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:13,757 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:13,774 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:13,791 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:13,808 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:13,823 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  91%|█████████ | 20096/22132 [07:27<00:38, 52.62it/s]

2026-09-09 18:29:13,841 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:13,857 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:13,877 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:13,893 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:13,909 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:13,924 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  91%|█████████ | 20102/22132 [07:28<00:37, 54.51it/s]

2026-09-09 18:29:13,940 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:13,957 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:13,980 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:29:13,997 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:14,017 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:14,033 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  91%|█████████ | 20108/22132 [07:28<00:37, 54.65it/s]

2026-09-09 18:29:14,054 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:14,072 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:14,088 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:14,107 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:14,124 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:14,141 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  91%|█████████ | 20114/22132 [07:28<00:36, 54.94it/s]

2026-09-09 18:29:14,159 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:14,175 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:14,196 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:14,216 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:14,232 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:14,248 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  91%|█████████ | 20120/22132 [07:28<00:36, 55.20it/s]

2026-09-09 18:29:14,269 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:14,289 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:14,307 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:14,327 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:14,346 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:14,372 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]

Indexing Records:  91%|█████████ | 20126/22132 [07:28<00:37, 52.99it/s]

2026-09-09 18:29:14,398 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:29:14,421 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:29:14,441 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:14,459 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:14,477 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:14,494 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  91%|█████████ | 20132/22132 [07:28<00:38, 51.81it/s]

2026-09-09 18:29:14,511 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:14,528 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:14,545 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:14,565 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:14,585 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:14,603 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  91%|█████████ | 20138/22132 [07:28<00:37, 52.81it/s]

2026-09-09 18:29:14,629 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:29:14,654 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:29:14,679 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:29:14,699 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:14,719 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:14,737 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  91%|█████████ | 20144/22132 [07:28<00:39, 50.02it/s]

2026-09-09 18:29:14,757 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:14,781 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:29:14,813 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:29:14,848 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.034s]
2026-09-09 18:29:14,872 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:29:14,892 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  91%|█████████ | 20150/22132 [07:29<00:43, 46.04it/s]

2026-09-09 18:29:14,912 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:14,934 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:29:14,955 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:29:14,974 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:14,992 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  91%|█████████ | 20155/22132 [07:29<00:42, 46.99it/s]

2026-09-09 18:29:15,016 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:29:15,057 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.040s]
2026-09-09 18:29:15,087 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:29:15,109 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:15,128 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  91%|█████████ | 20160/22132 [07:29<00:45, 43.67it/s]

2026-09-09 18:29:15,146 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:15,161 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:15,182 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:15,197 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:15,213 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:15,228 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  91%|█████████ | 20166/22132 [07:29<00:41, 47.81it/s]

2026-09-09 18:29:15,244 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:15,261 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:15,279 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:15,295 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:15,312 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:15,329 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  91%|█████████ | 20172/22132 [07:29<00:38, 51.03it/s]

2026-09-09 18:29:15,346 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:15,363 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:15,378 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:15,393 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:15,410 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:15,426 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:15,443 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  91%|█████████ | 20179/22132 [07:29<00:36, 54.16it/s]

2026-09-09 18:29:15,459 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:15,475 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:15,491 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:15,509 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:15,527 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:15,543 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  91%|█████████ | 20185/22132 [07:29<00:34, 55.68it/s]

2026-09-09 18:29:15,559 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:15,575 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:15,592 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:15,608 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:15,624 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:15,641 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:15,656 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  91%|█████████ | 20192/22132 [07:29<00:33, 57.69it/s]

2026-09-09 18:29:15,673 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:15,690 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:15,705 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:15,721 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:15,736 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:15,752 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:15,767 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  91%|█████████▏| 20199/22132 [07:29<00:32, 59.19it/s]

2026-09-09 18:29:15,784 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:15,799 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:15,815 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:15,835 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:15,853 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:15,871 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  91%|█████████▏| 20205/22132 [07:30<00:32, 58.87it/s]

2026-09-09 18:29:15,891 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:15,906 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:15,924 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:15,939 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:15,955 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:15,970 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:15,987 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  91%|█████████▏| 20212/22132 [07:30<00:32, 59.33it/s]

2026-09-09 18:29:16,004 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:16,021 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:16,037 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:16,053 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:16,069 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:16,092 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  91%|█████████▏| 20218/22132 [07:30<00:32, 58.72it/s]

2026-09-09 18:29:16,111 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:16,129 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:16,144 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:16,159 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:16,174 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:16,190 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:16,207 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  91%|█████████▏| 20225/22132 [07:30<00:32, 59.29it/s]

2026-09-09 18:29:16,225 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:16,240 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:16,256 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:16,271 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:16,287 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:16,304 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:16,321 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  91%|█████████▏| 20232/22132 [07:30<00:31, 59.93it/s]

2026-09-09 18:29:16,341 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:16,364 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:29:16,385 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:16,403 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:16,425 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:29:16,444 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  91%|█████████▏| 20238/22132 [07:30<00:33, 56.34it/s]

2026-09-09 18:29:16,461 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:16,493 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:29:16,509 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:16,526 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:16,543 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:16,559 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  91%|█████████▏| 20244/22132 [07:30<00:34, 55.18it/s]

2026-09-09 18:29:16,575 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:16,593 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:16,610 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:16,627 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:16,643 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:16,659 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  91%|█████████▏| 20250/22132 [07:30<00:33, 56.39it/s]

2026-09-09 18:29:16,676 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:16,691 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:16,706 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:16,723 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:16,738 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:16,754 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:16,773 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  92%|█████████▏| 20257/22132 [07:30<00:32, 58.01it/s]

2026-09-09 18:29:16,792 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:16,807 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:16,822 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:16,839 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:16,854 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:16,872 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:16,889 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  92%|█████████▏| 20264/22132 [07:31<00:31, 58.78it/s]

2026-09-09 18:29:16,907 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:16,923 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:16,939 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:16,956 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:16,973 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:16,988 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:17,004 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  92%|█████████▏| 20271/22132 [07:31<00:31, 59.34it/s]

2026-09-09 18:29:17,020 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:17,036 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:17,051 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:17,067 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:17,083 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:17,099 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:17,115 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  92%|█████████▏| 20278/22132 [07:31<00:30, 60.37it/s]

2026-09-09 18:29:17,134 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:17,148 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:17,164 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:17,179 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:17,195 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:17,211 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:17,226 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  92%|█████████▏| 20285/22132 [07:31<00:30, 61.23it/s]

2026-09-09 18:29:17,244 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:17,259 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:17,276 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:17,293 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:17,309 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:17,324 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:17,339 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  92%|█████████▏| 20292/22132 [07:31<00:29, 61.44it/s]

2026-09-09 18:29:17,355 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:17,370 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:17,386 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:17,401 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:17,417 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:17,434 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:17,451 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  92%|█████████▏| 20299/22132 [07:31<00:29, 61.70it/s]

2026-09-09 18:29:17,468 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:17,484 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:17,499 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:17,514 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:17,531 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:17,547 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:17,563 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  92%|█████████▏| 20306/22132 [07:31<00:29, 62.09it/s]

2026-09-09 18:29:17,579 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:17,596 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:17,611 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:17,628 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:17,643 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:17,660 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:17,675 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  92%|█████████▏| 20313/22132 [07:31<00:29, 62.19it/s]

2026-09-09 18:29:17,692 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:17,709 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:17,727 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:17,743 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:17,761 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:17,779 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:17,795 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  92%|█████████▏| 20320/22132 [07:31<00:29, 60.95it/s]

2026-09-09 18:29:17,812 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:17,829 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:17,849 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:17,865 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:17,882 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:17,898 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:17,915 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  92%|█████████▏| 20327/22132 [07:32<00:29, 60.19it/s]

2026-09-09 18:29:17,931 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:17,947 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:17,968 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:17,987 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:18,006 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:18,024 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:18,047 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  92%|█████████▏| 20334/22132 [07:32<00:31, 57.74it/s]

2026-09-09 18:29:18,067 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:18,086 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:18,108 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:29:18,131 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:29:18,163 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.030s]
2026-09-09 18:29:18,179 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  92%|█████████▏| 20340/22132 [07:32<00:33, 53.80it/s]

2026-09-09 18:29:18,196 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:18,215 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:18,236 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:18,255 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:18,274 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:18,291 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  92%|█████████▏| 20346/22132 [07:32<00:33, 53.80it/s]

2026-09-09 18:29:18,309 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:18,327 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:18,344 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:18,361 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:18,379 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:18,395 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  92%|█████████▏| 20352/22132 [07:32<00:32, 54.86it/s]

2026-09-09 18:29:18,415 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:18,434 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:18,452 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:18,471 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:18,491 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:18,512 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  92%|█████████▏| 20358/22132 [07:32<00:33, 53.73it/s]

2026-09-09 18:29:18,529 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:18,549 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:18,566 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:18,582 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:18,598 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:18,615 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  92%|█████████▏| 20364/22132 [07:32<00:32, 55.03it/s]

2026-09-09 18:29:18,637 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:18,658 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:18,677 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:18,698 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:18,714 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:18,730 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  92%|█████████▏| 20370/22132 [07:32<00:32, 54.08it/s]

2026-09-09 18:29:18,748 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:18,767 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:18,787 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:18,807 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:18,827 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:18,844 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  92%|█████████▏| 20376/22132 [07:32<00:32, 53.74it/s]

2026-09-09 18:29:18,862 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:18,884 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:18,901 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:18,919 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:18,938 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:18,958 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  92%|█████████▏| 20382/22132 [07:33<00:32, 53.39it/s]

2026-09-09 18:29:18,976 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:18,991 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:19,007 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:19,023 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:19,038 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:19,055 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:19,069 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  92%|█████████▏| 20389/22132 [07:33<00:31, 56.17it/s]

2026-09-09 18:29:19,086 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:19,101 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:19,116 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:19,132 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:19,149 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:19,165 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:19,181 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  92%|█████████▏| 20396/22132 [07:33<00:29, 58.13it/s]

2026-09-09 18:29:19,198 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:19,214 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:19,232 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:19,253 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:19,269 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:19,284 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  92%|█████████▏| 20402/22132 [07:33<00:29, 58.15it/s]

2026-09-09 18:29:19,300 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:19,317 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:19,335 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:19,353 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:19,369 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:19,386 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  92%|█████████▏| 20408/22132 [07:33<00:29, 58.37it/s]

2026-09-09 18:29:19,404 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:19,421 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:19,436 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:19,452 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:19,469 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:19,486 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  92%|█████████▏| 20414/22132 [07:33<00:29, 58.77it/s]

2026-09-09 18:29:19,507 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:19,525 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:19,545 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:19,566 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:19,584 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:19,603 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  92%|█████████▏| 20420/22132 [07:33<00:30, 56.36it/s]

2026-09-09 18:29:19,623 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:19,640 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:19,657 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:19,672 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:19,688 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:19,703 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  92%|█████████▏| 20426/22132 [07:33<00:29, 57.36it/s]

2026-09-09 18:29:19,720 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:19,737 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:19,753 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:19,770 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:19,787 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:19,803 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:19,818 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  92%|█████████▏| 20433/22132 [07:33<00:29, 58.45it/s]

2026-09-09 18:29:19,836 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:19,852 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:19,868 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:19,885 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:19,901 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:19,916 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:19,933 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  92%|█████████▏| 20440/22132 [07:34<00:28, 59.32it/s]

2026-09-09 18:29:19,949 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:19,966 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:19,982 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:19,998 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:20,022 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:29:20,045 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  92%|█████████▏| 20446/22132 [07:34<00:29, 57.55it/s]

2026-09-09 18:29:20,069 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:29:20,085 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:20,104 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:20,122 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:20,141 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:20,157 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  92%|█████████▏| 20452/22132 [07:34<00:29, 56.31it/s]

2026-09-09 18:29:20,176 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:20,194 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:20,213 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:20,229 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:20,244 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:20,262 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  92%|█████████▏| 20458/22132 [07:34<00:29, 56.63it/s]

2026-09-09 18:29:20,279 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:20,296 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:20,311 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:20,326 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:20,341 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:20,356 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:20,371 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  92%|█████████▏| 20465/22132 [07:34<00:28, 58.79it/s]

2026-09-09 18:29:20,388 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:20,405 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:20,421 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:20,436 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:20,452 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:20,468 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:20,482 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]

Indexing Records:  92%|█████████▏| 20472/22132 [07:34<00:27, 60.07it/s]

2026-09-09 18:29:20,498 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:20,514 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:20,529 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:20,545 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:20,561 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:20,577 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:20,592 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  93%|█████████▎| 20479/22132 [07:34<00:27, 61.18it/s]

2026-09-09 18:29:20,608 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:20,623 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:20,638 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:20,653 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:20,668 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:29:20,683 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:20,699 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  93%|█████████▎| 20486/22132 [07:34<00:26, 62.50it/s]

2026-09-09 18:29:20,715 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:20,730 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:29:20,747 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:20,763 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:20,779 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:20,794 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:20,810 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  93%|█████████▎| 20493/22132 [07:34<00:26, 62.63it/s]

2026-09-09 18:29:20,832 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:20,853 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:20,872 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:20,893 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:20,913 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:20,928 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:20,945 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  93%|█████████▎| 20500/22132 [07:35<00:27, 58.86it/s]

2026-09-09 18:29:20,962 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:20,981 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:20,999 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:21,021 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:29:21,038 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:21,055 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  93%|█████████▎| 20506/22132 [07:35<00:28, 57.71it/s]

2026-09-09 18:29:21,071 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:21,086 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:21,102 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:21,118 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:21,134 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:21,151 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:21,166 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  93%|█████████▎| 20513/22132 [07:35<00:27, 59.19it/s]

2026-09-09 18:29:21,183 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:21,199 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:21,216 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:21,232 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:21,248 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:21,263 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:21,282 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  93%|█████████▎| 20520/22132 [07:35<00:27, 59.55it/s]

2026-09-09 18:29:21,299 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:21,315 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:21,332 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:21,347 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:21,363 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:21,378 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:21,394 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  93%|█████████▎| 20527/22132 [07:35<00:26, 60.43it/s]

2026-09-09 18:29:21,410 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:21,427 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:21,442 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:21,459 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:21,475 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:21,491 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:21,505 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  93%|█████████▎| 20534/22132 [07:35<00:26, 61.19it/s]

2026-09-09 18:29:21,522 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:21,541 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:21,560 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:21,576 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:21,592 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:21,608 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:21,625 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  93%|█████████▎| 20541/22132 [07:35<00:26, 60.40it/s]

2026-09-09 18:29:21,643 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:21,660 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:21,676 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:21,691 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:21,707 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:21,724 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:21,741 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  93%|█████████▎| 20548/22132 [07:35<00:26, 60.41it/s]

2026-09-09 18:29:21,758 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:21,775 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:21,790 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:21,805 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:21,820 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:21,834 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:29:21,849 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  93%|█████████▎| 20555/22132 [07:35<00:25, 61.53it/s]

2026-09-09 18:29:21,865 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:21,881 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:21,900 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:21,917 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:21,933 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:21,950 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:21,969 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  93%|█████████▎| 20562/22132 [07:36<00:25, 60.63it/s]

2026-09-09 18:29:21,985 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:22,000 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:22,024 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:29:22,042 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:22,058 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:22,076 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:22,091 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  93%|█████████▎| 20569/22132 [07:36<00:26, 59.65it/s]

2026-09-09 18:29:22,107 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:22,123 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:22,138 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:22,168 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:29:22,185 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:22,200 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  93%|█████████▎| 20575/22132 [07:36<00:26, 58.20it/s]

2026-09-09 18:29:22,218 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:22,235 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:22,252 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:22,267 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:22,284 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:22,304 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  93%|█████████▎| 20581/22132 [07:36<00:26, 58.19it/s]

2026-09-09 18:29:22,321 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:22,340 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:22,356 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:22,374 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:22,391 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:22,406 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  93%|█████████▎| 20587/22132 [07:36<00:26, 58.23it/s]

2026-09-09 18:29:22,424 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:22,441 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:22,457 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:22,473 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:22,491 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:22,506 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:22,521 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  93%|█████████▎| 20594/22132 [07:36<00:26, 59.12it/s]

2026-09-09 18:29:22,537 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:22,553 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:22,572 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:22,592 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:22,608 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:22,624 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  93%|█████████▎| 20600/22132 [07:36<00:26, 58.85it/s]

2026-09-09 18:29:22,642 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:22,657 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:22,674 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:22,689 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:22,705 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:22,744 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.038s]

Indexing Records:  93%|█████████▎| 20606/22132 [07:36<00:27, 55.99it/s]

2026-09-09 18:29:22,762 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:22,778 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:22,794 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:22,809 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:22,826 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:22,841 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:22,856 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  93%|█████████▎| 20613/22132 [07:36<00:26, 57.92it/s]

2026-09-09 18:29:22,873 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:22,888 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:22,905 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:22,921 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:22,937 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:22,953 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:22,969 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  93%|█████████▎| 20620/22132 [07:37<00:25, 59.25it/s]

2026-09-09 18:29:22,985 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:23,000 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:23,019 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:23,035 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:23,055 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:23,071 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  93%|█████████▎| 20626/22132 [07:37<00:25, 59.12it/s]

2026-09-09 18:29:23,087 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:23,105 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:23,122 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:23,137 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:23,153 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:23,168 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:23,184 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  93%|█████████▎| 20633/22132 [07:37<00:25, 59.91it/s]

2026-09-09 18:29:23,203 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:23,220 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:23,239 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:23,255 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:23,272 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:23,287 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  93%|█████████▎| 20639/22132 [07:37<00:25, 59.46it/s]

2026-09-09 18:29:23,304 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:23,321 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:23,336 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:23,354 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:23,370 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:23,392 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  93%|█████████▎| 20645/22132 [07:37<00:25, 58.83it/s]

2026-09-09 18:29:23,410 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:23,427 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:23,442 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:23,457 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:23,472 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:23,487 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:23,502 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  93%|█████████▎| 20652/22132 [07:37<00:24, 60.21it/s]

2026-09-09 18:29:23,518 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:23,534 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:23,549 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:23,567 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:23,586 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:23,604 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:23,620 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  93%|█████████▎| 20659/22132 [07:37<00:24, 60.01it/s]

2026-09-09 18:29:23,637 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:23,655 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:23,674 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:23,694 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:23,712 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:23,729 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  93%|█████████▎| 20665/22132 [07:37<00:25, 58.44it/s]

2026-09-09 18:29:23,753 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:29:23,772 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:23,788 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:23,807 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:23,823 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:23,840 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  93%|█████████▎| 20671/22132 [07:37<00:25, 57.16it/s]

2026-09-09 18:29:23,859 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:23,878 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:23,895 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:23,913 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:23,931 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:23,948 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  93%|█████████▎| 20677/22132 [07:38<00:25, 56.67it/s]

2026-09-09 18:29:23,965 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:23,981 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:23,997 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:24,014 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:24,030 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:24,047 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:24,064 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  93%|█████████▎| 20684/22132 [07:38<00:25, 57.81it/s]

2026-09-09 18:29:24,081 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:24,098 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:24,114 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:24,132 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:24,150 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:24,167 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  93%|█████████▎| 20690/22132 [07:38<00:24, 57.94it/s]

2026-09-09 18:29:24,184 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:24,208 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:29:24,224 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:24,241 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:24,264 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:29:24,283 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  94%|█████████▎| 20696/22132 [07:38<00:25, 56.08it/s]

2026-09-09 18:29:24,303 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:24,328 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:29:24,345 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:24,364 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:24,382 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:24,401 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  94%|█████████▎| 20702/22132 [07:38<00:26, 54.35it/s]

2026-09-09 18:29:24,421 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:24,437 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:24,456 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:24,472 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:24,488 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:24,503 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  94%|█████████▎| 20708/22132 [07:38<00:25, 55.67it/s]

2026-09-09 18:29:24,519 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:24,540 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:24,554 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:24,572 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:24,588 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:24,609 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  94%|█████████▎| 20714/22132 [07:38<00:25, 55.92it/s]

2026-09-09 18:29:24,628 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:24,645 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:24,661 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:24,676 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:24,693 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:24,709 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:24,725 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  94%|█████████▎| 20721/22132 [07:38<00:24, 57.36it/s]

2026-09-09 18:29:24,741 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:24,759 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:24,774 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:24,789 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:24,805 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:24,821 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:24,836 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  94%|█████████▎| 20728/22132 [07:38<00:23, 59.07it/s]

2026-09-09 18:29:24,852 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:24,868 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:24,885 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:24,900 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:24,917 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:24,934 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:24,950 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  94%|█████████▎| 20735/22132 [07:39<00:23, 59.72it/s]

2026-09-09 18:29:24,966 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:24,982 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:24,999 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:25,018 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:25,034 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:25,049 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:25,064 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  94%|█████████▎| 20742/22132 [07:39<00:23, 60.20it/s]

2026-09-09 18:29:25,080 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:25,096 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:25,111 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:25,127 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:25,142 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:25,159 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:25,174 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  94%|█████████▍| 20749/22132 [07:39<00:22, 61.25it/s]

2026-09-09 18:29:25,192 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:25,209 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:25,227 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:25,242 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:25,257 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:25,274 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:25,289 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  94%|█████████▍| 20756/22132 [07:39<00:22, 61.09it/s]

2026-09-09 18:29:25,306 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:25,322 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:25,337 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:25,352 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:25,369 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:25,384 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:25,400 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  94%|█████████▍| 20763/22132 [07:39<00:22, 61.77it/s]

2026-09-09 18:29:25,417 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:25,433 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:25,449 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:25,465 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:25,481 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:25,496 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:25,514 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  94%|█████████▍| 20770/22132 [07:39<00:22, 61.68it/s]

2026-09-09 18:29:25,532 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:25,547 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:25,562 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:25,577 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:25,595 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:25,611 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:25,626 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  94%|█████████▍| 20777/22132 [07:39<00:21, 61.80it/s]

2026-09-09 18:29:25,644 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:25,661 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:25,678 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:25,695 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:25,711 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:25,728 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:25,746 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  94%|█████████▍| 20784/22132 [07:39<00:22, 60.83it/s]

2026-09-09 18:29:25,763 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:25,780 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:25,796 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:25,811 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:25,826 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:25,849 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:29:25,868 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  94%|█████████▍| 20791/22132 [07:40<00:22, 59.73it/s]

2026-09-09 18:29:25,888 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:25,909 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:25,929 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:25,948 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:25,968 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:25,989 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  94%|█████████▍| 20797/22132 [07:40<00:23, 56.63it/s]

2026-09-09 18:29:26,007 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:26,035 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:29:26,052 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:26,068 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:26,083 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:26,101 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  94%|█████████▍| 20803/22132 [07:40<00:23, 55.70it/s]

2026-09-09 18:29:26,117 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:26,136 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:26,154 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:26,169 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:26,186 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:26,203 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  94%|█████████▍| 20809/22132 [07:40<00:23, 56.51it/s]

2026-09-09 18:29:26,220 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:26,237 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:26,254 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:26,270 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:26,285 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:26,303 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:26,320 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  94%|█████████▍| 20816/22132 [07:40<00:22, 57.59it/s]

2026-09-09 18:29:26,337 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:26,352 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:26,367 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:26,384 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:26,401 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:26,417 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:26,433 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  94%|█████████▍| 20823/22132 [07:40<00:22, 58.93it/s]

2026-09-09 18:29:26,450 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:26,466 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:26,481 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:26,497 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:26,512 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:26,537 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  94%|█████████▍| 20829/22132 [07:40<00:22, 58.57it/s]

2026-09-09 18:29:26,554 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:26,570 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:26,585 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:26,601 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:26,619 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:26,634 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:26,654 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  94%|█████████▍| 20836/22132 [07:40<00:22, 58.85it/s]

2026-09-09 18:29:26,673 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:26,689 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:26,705 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:26,723 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:26,738 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:26,755 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  94%|█████████▍| 20842/22132 [07:40<00:21, 59.10it/s]

2026-09-09 18:29:26,771 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:26,787 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:26,806 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:26,825 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:26,846 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:26,864 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  94%|█████████▍| 20848/22132 [07:41<00:22, 57.86it/s]

2026-09-09 18:29:26,885 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:26,911 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:29:26,930 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:26,949 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:26,969 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:26,988 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  94%|█████████▍| 20854/22132 [07:41<00:23, 54.79it/s]

2026-09-09 18:29:27,005 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:27,024 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:27,042 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:27,060 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:27,081 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:27,101 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  94%|█████████▍| 20860/22132 [07:41<00:23, 54.21it/s]

2026-09-09 18:29:27,122 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:27,139 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:27,156 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:27,172 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:27,199 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:29:27,214 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  94%|█████████▍| 20866/22132 [07:41<00:23, 53.94it/s]

2026-09-09 18:29:27,231 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:27,248 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:27,263 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:27,279 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:27,295 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:27,311 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:27,327 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  94%|█████████▍| 20873/22132 [07:41<00:22, 56.35it/s]

2026-09-09 18:29:27,343 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:27,360 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:27,375 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:29:27,391 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:27,410 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:27,428 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  94%|█████████▍| 20879/22132 [07:41<00:21, 57.14it/s]

2026-09-09 18:29:27,447 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:27,471 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:29:27,488 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:27,507 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:27,523 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:27,539 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  94%|█████████▍| 20885/22132 [07:41<00:22, 56.17it/s]

2026-09-09 18:29:27,559 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:27,577 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:27,595 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:27,612 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:27,628 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:27,645 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  94%|█████████▍| 20891/22132 [07:41<00:22, 56.39it/s]

2026-09-09 18:29:27,663 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:27,679 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:27,695 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:27,711 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:27,727 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:27,743 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:27,758 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  94%|█████████▍| 20898/22132 [07:41<00:21, 58.01it/s]

2026-09-09 18:29:27,777 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:27,793 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:27,810 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:27,826 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:27,843 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:27,858 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  94%|█████████▍| 20904/22132 [07:41<00:20, 58.55it/s]

2026-09-09 18:29:27,875 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:27,892 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:27,908 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:27,923 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:27,939 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:27,955 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:27,971 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  94%|█████████▍| 20911/22132 [07:42<00:20, 59.64it/s]

2026-09-09 18:29:27,989 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:28,007 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:28,025 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:28,040 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:28,055 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:28,071 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:28,086 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  95%|█████████▍| 20918/22132 [07:42<00:20, 60.15it/s]

2026-09-09 18:29:28,102 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:28,117 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:28,134 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:28,152 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:28,168 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:28,183 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:28,199 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  95%|█████████▍| 20925/22132 [07:42<00:19, 60.68it/s]

2026-09-09 18:29:28,215 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:28,230 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:28,246 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:28,261 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:28,277 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:28,292 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:28,307 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  95%|█████████▍| 20932/22132 [07:42<00:19, 61.78it/s]

2026-09-09 18:29:28,326 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:28,347 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:28,364 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:28,380 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:28,398 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:28,416 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:28,431 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  95%|█████████▍| 20939/22132 [07:42<00:19, 60.10it/s]

2026-09-09 18:29:28,448 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:28,464 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:28,480 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:28,495 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:28,511 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:28,526 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:28,542 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  95%|█████████▍| 20946/22132 [07:42<00:19, 60.94it/s]

2026-09-09 18:29:28,558 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:28,573 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:28,589 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:28,605 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:28,620 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:28,636 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:28,652 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  95%|█████████▍| 20953/22132 [07:42<00:19, 61.72it/s]

2026-09-09 18:29:28,671 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:28,689 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:28,707 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:28,723 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:28,739 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:28,753 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:28,769 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  95%|█████████▍| 20960/22132 [07:42<00:19, 61.12it/s]

2026-09-09 18:29:28,786 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:28,802 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:28,817 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:28,833 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:28,849 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:28,865 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:28,880 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  95%|█████████▍| 20967/22132 [07:43<00:18, 61.70it/s]

2026-09-09 18:29:28,897 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:28,912 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:28,927 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:28,942 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:28,963 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:28,980 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:28,997 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  95%|█████████▍| 20974/22132 [07:43<00:18, 61.19it/s]

2026-09-09 18:29:29,017 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:29,033 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:29,049 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:29,064 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:29,080 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:29,095 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:29,111 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  95%|█████████▍| 20981/22132 [07:43<00:18, 61.25it/s]

2026-09-09 18:29:29,129 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:29,145 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:29,160 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:29,176 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:29,192 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:29,207 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:29,222 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  95%|█████████▍| 20988/22132 [07:43<00:18, 61.70it/s]

2026-09-09 18:29:29,239 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:29,255 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:29,273 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:29,289 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:29,304 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:29,320 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:29,335 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  95%|█████████▍| 20995/22132 [07:43<00:18, 61.83it/s]

2026-09-09 18:29:29,356 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:29,374 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:29,390 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:29,407 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:29,425 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:29,443 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:29,458 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  95%|█████████▍| 21002/22132 [07:43<00:18, 60.21it/s]

2026-09-09 18:29:29,475 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:29,494 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:29,511 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:29,527 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:29,542 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:29,559 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:29,575 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  95%|█████████▍| 21009/22132 [07:43<00:18, 60.20it/s]

2026-09-09 18:29:29,592 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:29,608 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:29,629 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:29,661 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:29:29,689 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:29:29,711 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:29:29,735 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  95%|█████████▍| 21016/22132 [07:43<00:20, 54.10it/s]

2026-09-09 18:29:29,753 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:29,771 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:29,791 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:29,812 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:29,832 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:29,852 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  95%|█████████▍| 21022/22132 [07:43<00:20, 53.23it/s]

2026-09-09 18:29:29,873 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:29,891 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:29,913 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:29:29,932 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:29,956 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:29:29,979 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  95%|█████████▌| 21028/22132 [07:44<00:21, 51.43it/s]

2026-09-09 18:29:30,000 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:30,021 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:30,041 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:30,056 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:30,077 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:30,095 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  95%|█████████▌| 21034/22132 [07:44<00:21, 51.60it/s]

2026-09-09 18:29:30,111 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:30,127 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:30,143 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:30,160 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:30,175 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:30,192 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:30,216 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  95%|█████████▌| 21041/22132 [07:44<00:20, 53.46it/s]

2026-09-09 18:29:30,241 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:29:30,259 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:30,276 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:30,296 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:30,315 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:30,332 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  95%|█████████▌| 21047/22132 [07:44<00:20, 52.95it/s]

2026-09-09 18:29:30,349 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:30,370 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:30,393 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:29:30,415 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:30,432 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:30,449 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  95%|█████████▌| 21053/22132 [07:44<00:20, 52.44it/s]

2026-09-09 18:29:30,465 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:30,481 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:30,497 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:30,513 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:30,528 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:30,544 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:30,561 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  95%|█████████▌| 21060/22132 [07:44<00:19, 55.27it/s]

2026-09-09 18:29:30,578 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:30,594 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:30,609 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:30,624 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:30,639 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:30,654 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:30,669 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  95%|█████████▌| 21067/22132 [07:44<00:18, 57.94it/s]

2026-09-09 18:29:30,686 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:30,704 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:30,720 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:30,737 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:30,755 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:30,771 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  95%|█████████▌| 21073/22132 [07:44<00:18, 58.14it/s]

2026-09-09 18:29:30,788 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:30,803 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:30,821 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:30,840 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:30,859 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:30,875 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  95%|█████████▌| 21079/22132 [07:45<00:18, 58.10it/s]

2026-09-09 18:29:30,896 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:30,916 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:30,935 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:30,952 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:30,969 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:30,985 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  95%|█████████▌| 21085/22132 [07:45<00:18, 57.06it/s]

2026-09-09 18:29:31,004 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:31,025 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:31,045 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:31,065 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:31,084 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:31,102 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  95%|█████████▌| 21091/22132 [07:45<00:18, 55.21it/s]

2026-09-09 18:29:31,122 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:31,140 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:31,155 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:31,176 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:31,195 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:31,212 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  95%|█████████▌| 21097/22132 [07:45<00:18, 55.02it/s]

2026-09-09 18:29:31,229 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:31,246 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:31,261 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:31,276 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:31,294 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:31,311 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:31,329 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  95%|█████████▌| 21104/22132 [07:45<00:18, 56.54it/s]

2026-09-09 18:29:31,346 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:31,362 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:31,382 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:31,398 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:31,414 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:31,431 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  95%|█████████▌| 21110/22132 [07:45<00:17, 57.19it/s]

2026-09-09 18:29:31,447 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:31,463 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:31,479 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:31,497 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:31,514 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:31,530 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:31,545 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  95%|█████████▌| 21117/22132 [07:45<00:17, 58.47it/s]

2026-09-09 18:29:31,564 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:31,583 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:31,600 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:31,616 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:31,633 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:31,652 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  95%|█████████▌| 21123/22132 [07:45<00:17, 57.71it/s]

2026-09-09 18:29:31,669 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:31,686 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:31,702 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:31,718 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:31,736 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:31,755 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  95%|█████████▌| 21129/22132 [07:45<00:17, 57.93it/s]

2026-09-09 18:29:31,781 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:29:31,799 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:31,815 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:31,833 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:31,851 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:31,869 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  95%|█████████▌| 21135/22132 [07:46<00:17, 56.22it/s]

2026-09-09 18:29:31,888 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:31,905 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:31,922 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:31,939 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:31,955 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:31,971 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  96%|█████████▌| 21141/22132 [07:46<00:17, 57.06it/s]

2026-09-09 18:29:31,986 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:29:32,002 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:32,021 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:32,037 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:32,054 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:32,069 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:32,084 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  96%|█████████▌| 21148/22132 [07:46<00:16, 58.58it/s]

2026-09-09 18:29:32,099 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:32,114 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:32,131 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:32,148 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:32,163 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:32,179 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:32,196 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  96%|█████████▌| 21155/22132 [07:46<00:16, 59.71it/s]

2026-09-09 18:29:32,214 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:32,231 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:32,247 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:32,263 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:32,279 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:32,295 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:32,311 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  96%|█████████▌| 21162/22132 [07:46<00:16, 60.16it/s]

2026-09-09 18:29:32,327 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:32,386 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.058s]
2026-09-09 18:29:32,407 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:32,425 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:32,445 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:32,463 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:32,483 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  96%|█████████▌| 21169/22132 [07:46<00:18, 52.35it/s]

2026-09-09 18:29:32,501 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:32,520 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:32,541 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:32,558 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:32,577 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:32,594 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  96%|█████████▌| 21175/22132 [07:46<00:18, 52.79it/s]

2026-09-09 18:29:32,614 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:32,632 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:32,652 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:32,672 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:32,689 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:32,710 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  96%|█████████▌| 21181/22132 [07:46<00:18, 52.48it/s]

2026-09-09 18:29:32,730 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:32,748 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:32,767 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:32,794 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:29:32,812 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:32,831 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  96%|█████████▌| 21187/22132 [07:46<00:18, 51.57it/s]

2026-09-09 18:29:32,852 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:32,870 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:32,890 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:32,911 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:32,931 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:32,950 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  96%|█████████▌| 21193/22132 [07:47<00:18, 51.27it/s]

2026-09-09 18:29:32,972 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:33,000 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:29:33,019 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:33,039 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:33,059 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:33,081 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  96%|█████████▌| 21199/22132 [07:47<00:18, 49.53it/s]

2026-09-09 18:29:33,103 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:33,124 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:33,145 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:33,163 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:33,184 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  96%|█████████▌| 21204/22132 [07:47<00:18, 49.24it/s]

2026-09-09 18:29:33,204 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:33,226 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:33,244 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:33,263 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:33,281 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:33,300 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  96%|█████████▌| 21210/22132 [07:47<00:18, 50.05it/s]

2026-09-09 18:29:33,328 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:29:33,348 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:33,370 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:29:33,390 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:33,442 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.051s]
2026-09-09 18:29:33,463 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  96%|█████████▌| 21216/22132 [07:47<00:20, 45.08it/s]

2026-09-09 18:29:33,483 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:33,503 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:33,522 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:33,548 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:29:33,565 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  96%|█████████▌| 21221/22132 [07:47<00:19, 46.04it/s]

2026-09-09 18:29:33,585 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:33,605 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:33,622 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:33,640 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:33,658 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:33,676 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  96%|█████████▌| 21227/22132 [07:47<00:18, 48.39it/s]

2026-09-09 18:29:33,695 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:33,712 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:33,728 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:33,749 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:33,767 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:33,787 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  96%|█████████▌| 21233/22132 [07:47<00:17, 49.99it/s]

2026-09-09 18:29:33,808 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:33,827 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:33,845 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:33,862 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:33,883 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:33,903 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  96%|█████████▌| 21239/22132 [07:48<00:17, 50.53it/s]

2026-09-09 18:29:33,924 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:33,940 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:33,961 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:33,980 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:33,997 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:34,013 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  96%|█████████▌| 21245/22132 [07:48<00:17, 51.68it/s]

2026-09-09 18:29:34,029 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:34,044 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:34,059 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:34,075 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:34,090 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:34,107 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:34,122 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  96%|█████████▌| 21252/22132 [07:48<00:15, 55.31it/s]

2026-09-09 18:29:34,137 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:34,153 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:34,168 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:34,183 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:34,199 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:34,213 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:29:34,230 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  96%|█████████▌| 21259/22132 [07:48<00:15, 58.08it/s]

2026-09-09 18:29:34,248 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:34,264 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:34,283 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:34,299 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:34,316 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:34,333 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  96%|█████████▌| 21265/22132 [07:48<00:14, 58.07it/s]

2026-09-09 18:29:34,350 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:34,366 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:34,387 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:34,407 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:34,425 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:34,441 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  96%|█████████▌| 21271/22132 [07:48<00:15, 57.38it/s]

2026-09-09 18:29:34,460 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:34,480 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:34,505 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:29:34,525 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:34,545 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:34,562 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  96%|█████████▌| 21277/22132 [07:48<00:15, 54.76it/s]

2026-09-09 18:29:34,582 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:34,600 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:34,641 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.040s]
2026-09-09 18:29:34,663 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:29:34,681 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:34,701 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  96%|█████████▌| 21283/22132 [07:48<00:16, 50.81it/s]

2026-09-09 18:29:34,729 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:29:34,755 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:29:34,785 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:29:34,821 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]
2026-09-09 18:29:34,841 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:34,871 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]

Indexing Records:  96%|█████████▌| 21289/22132 [07:49<00:18, 44.96it/s]

2026-09-09 18:29:34,896 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:29:34,913 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:34,935 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:34,956 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:34,977 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  96%|█████████▌| 21294/22132 [07:49<00:18, 45.49it/s]

2026-09-09 18:29:35,001 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:29:35,021 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:35,041 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:35,058 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:35,078 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  96%|█████████▌| 21299/22132 [07:49<00:17, 46.48it/s]

2026-09-09 18:29:35,099 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:35,116 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:35,137 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:35,156 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:35,175 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:35,193 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  96%|█████████▋| 21305/22132 [07:49<00:17, 48.22it/s]

2026-09-09 18:29:35,212 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:35,233 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:35,254 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:35,276 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:29:35,296 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  96%|█████████▋| 21310/22132 [07:49<00:17, 48.21it/s]

2026-09-09 18:29:35,315 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:35,334 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:35,350 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:35,367 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:35,387 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:35,408 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  96%|█████████▋| 21316/22132 [07:49<00:16, 49.91it/s]

2026-09-09 18:29:35,435 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:29:35,459 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:29:35,480 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:35,501 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:35,520 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:35,539 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  96%|█████████▋| 21322/22132 [07:49<00:16, 48.53it/s]

2026-09-09 18:29:35,556 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:35,579 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:29:35,600 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:35,618 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:35,634 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:35,651 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  96%|█████████▋| 21328/22132 [07:49<00:16, 49.93it/s]

2026-09-09 18:29:35,669 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:35,688 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:35,707 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:35,725 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:35,745 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:35,761 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  96%|█████████▋| 21334/22132 [07:49<00:15, 51.24it/s]

2026-09-09 18:29:35,778 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:35,793 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:35,809 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:35,828 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:35,846 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:35,867 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  96%|█████████▋| 21340/22132 [07:50<00:15, 52.76it/s]

2026-09-09 18:29:35,894 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:29:35,913 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:35,945 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:29:35,970 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:29:35,987 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:36,004 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  96%|█████████▋| 21346/22132 [07:50<00:15, 49.77it/s]

2026-09-09 18:29:36,023 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:36,039 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:36,059 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:36,076 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:36,093 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:36,113 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  96%|█████████▋| 21352/22132 [07:50<00:15, 51.23it/s]

2026-09-09 18:29:36,129 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:36,147 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:36,164 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:36,181 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:36,199 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:36,220 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  97%|█████████▋| 21358/22132 [07:50<00:14, 52.63it/s]

2026-09-09 18:29:36,241 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:36,257 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:36,276 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:36,306 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:29:36,327 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:36,353 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  97%|█████████▋| 21364/22132 [07:50<00:15, 50.12it/s]

2026-09-09 18:29:36,372 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:36,390 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:36,407 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:36,426 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:36,447 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:36,467 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  97%|█████████▋| 21370/22132 [07:50<00:14, 50.80it/s]

2026-09-09 18:29:36,483 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:36,506 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:29:36,527 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:36,546 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:36,564 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:36,581 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  97%|█████████▋| 21376/22132 [07:50<00:14, 51.34it/s]

2026-09-09 18:29:36,598 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:36,614 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:36,631 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:36,647 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:36,664 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:36,686 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  97%|█████████▋| 21382/22132 [07:50<00:14, 52.93it/s]

2026-09-09 18:29:36,705 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:36,730 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:29:36,752 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:29:36,766 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:29:36,784 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:36,801 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  97%|█████████▋| 21388/22132 [07:50<00:14, 52.74it/s]

2026-09-09 18:29:36,819 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:36,836 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:36,856 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:36,877 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:29:36,897 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:36,915 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  97%|█████████▋| 21394/22132 [07:51<00:14, 52.66it/s]

2026-09-09 18:29:36,938 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:29:36,958 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:36,977 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:36,999 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:29:37,023 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:29:37,042 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  97%|█████████▋| 21400/22132 [07:51<00:14, 50.87it/s]

2026-09-09 18:29:37,061 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:37,077 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:37,093 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:37,109 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:37,125 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:37,141 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:37,159 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  97%|█████████▋| 21407/22132 [07:51<00:13, 53.55it/s]

2026-09-09 18:29:37,178 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:37,195 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:37,214 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:37,232 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:37,251 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:37,267 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  97%|█████████▋| 21413/22132 [07:51<00:13, 54.20it/s]

2026-09-09 18:29:37,284 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:37,301 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:37,319 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:37,336 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:37,352 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:37,367 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  97%|█████████▋| 21419/22132 [07:51<00:12, 55.76it/s]

2026-09-09 18:29:37,384 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:37,401 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:37,421 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:37,439 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:37,457 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:37,474 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  97%|█████████▋| 21425/22132 [07:51<00:12, 55.90it/s]

2026-09-09 18:29:37,491 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:37,507 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:37,524 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:37,541 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:37,557 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:37,574 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:37,592 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  97%|█████████▋| 21432/22132 [07:51<00:12, 56.97it/s]

2026-09-09 18:29:37,610 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:37,627 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:37,644 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:37,661 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:37,677 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:37,693 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  97%|█████████▋| 21438/22132 [07:51<00:12, 57.63it/s]

2026-09-09 18:29:37,710 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:37,726 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:37,741 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:37,758 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:37,776 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:37,793 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:37,810 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  97%|█████████▋| 21445/22132 [07:51<00:11, 58.25it/s]

2026-09-09 18:29:37,829 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:37,844 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:37,860 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:37,876 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:37,894 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:37,914 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  97%|█████████▋| 21451/22132 [07:52<00:11, 58.20it/s]

2026-09-09 18:29:37,935 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:37,954 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:37,971 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:37,990 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:38,012 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:29:38,035 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  97%|█████████▋| 21457/22132 [07:52<00:12, 55.33it/s]

2026-09-09 18:29:38,061 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]
2026-09-09 18:29:38,083 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:29:38,102 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:38,119 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:38,136 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:38,152 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  97%|█████████▋| 21463/22132 [07:52<00:12, 54.13it/s]

2026-09-09 18:29:38,170 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:38,187 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:38,203 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:38,219 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:38,235 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:38,252 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:38,268 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  97%|█████████▋| 21470/22132 [07:52<00:11, 56.05it/s]

2026-09-09 18:29:38,284 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:38,300 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:38,316 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:38,334 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:38,352 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:38,374 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  97%|█████████▋| 21476/22132 [07:52<00:11, 56.23it/s]

2026-09-09 18:29:38,392 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:38,409 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:38,427 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:38,443 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:38,460 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:38,484 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  97%|█████████▋| 21482/22132 [07:52<00:11, 55.58it/s]

2026-09-09 18:29:38,507 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:29:38,526 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:38,544 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:38,564 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:38,580 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:38,602 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  97%|█████████▋| 21488/22132 [07:52<00:11, 54.14it/s]

2026-09-09 18:29:38,622 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:38,639 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:38,655 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:38,675 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:38,692 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:38,712 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  97%|█████████▋| 21494/22132 [07:52<00:11, 54.32it/s]

2026-09-09 18:29:38,731 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:38,747 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:38,762 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:38,780 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:38,795 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:38,812 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  97%|█████████▋| 21500/22132 [07:52<00:11, 55.86it/s]

2026-09-09 18:29:38,829 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:38,845 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:38,861 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:38,888 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:29:38,905 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:38,921 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  97%|█████████▋| 21506/22132 [07:53<00:11, 55.64it/s]

2026-09-09 18:29:38,969 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.047s]
2026-09-09 18:29:39,007 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.036s]
2026-09-09 18:29:39,023 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:39,038 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:39,054 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:39,072 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  97%|█████████▋| 21512/22132 [07:53<00:12, 49.67it/s]

2026-09-09 18:29:39,089 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:39,105 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:39,118 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.011s]
2026-09-09 18:29:39,132 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:29:39,145 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]
2026-09-09 18:29:39,158 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]
2026-09-09 18:29:39,172 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]
2026-09-09 18:29:39,186 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]

Indexing Records:  97%|█████████▋| 21520/22132 [07:53<00:11, 55.60it/s]

2026-09-09 18:29:39,201 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:29:39,214 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]
2026-09-09 18:29:39,227 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]
2026-09-09 18:29:39,242 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:39,256 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:29:39,270 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.012s]
2026-09-09 18:29:39,284 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:29:39,299 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]

Indexing Records:  97%|█████████▋| 21528/22132 [07:53<00:10, 60.02it/s]

2026-09-09 18:29:39,315 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:39,331 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:39,346 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:39,364 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:39,379 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:39,394 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:39,409 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  97%|█████████▋| 21535/22132 [07:53<00:09, 61.00it/s]

2026-09-09 18:29:39,427 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:39,444 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:39,462 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:39,480 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:39,496 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:39,513 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:39,529 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  97%|█████████▋| 21542/22132 [07:53<00:09, 60.23it/s]

2026-09-09 18:29:39,547 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:39,566 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:39,582 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:39,599 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:39,617 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:39,634 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:39,651 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  97%|█████████▋| 21549/22132 [07:53<00:09, 59.35it/s]

2026-09-09 18:29:39,667 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:39,683 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:39,700 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:39,717 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:39,734 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:39,754 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  97%|█████████▋| 21555/22132 [07:53<00:09, 59.00it/s]

2026-09-09 18:29:39,772 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:39,788 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:39,806 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:39,821 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:39,839 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:39,855 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  97%|█████████▋| 21561/22132 [07:53<00:09, 59.06it/s]

2026-09-09 18:29:39,873 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:39,889 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:39,907 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:39,928 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:39,948 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:39,968 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  97%|█████████▋| 21567/22132 [07:54<00:09, 57.24it/s]

2026-09-09 18:29:39,988 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:40,006 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:40,025 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:40,089 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.063s]
2026-09-09 18:29:40,111 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:29:40,129 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  97%|█████████▋| 21573/22132 [07:54<00:11, 49.65it/s]

2026-09-09 18:29:40,151 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:40,168 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:40,184 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:40,200 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:40,217 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:40,232 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  98%|█████████▊| 21579/22132 [07:54<00:10, 51.84it/s]

2026-09-09 18:29:40,250 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:40,266 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:40,282 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:40,298 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:40,317 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:40,334 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  98%|█████████▊| 21585/22132 [07:54<00:10, 53.67it/s]

2026-09-09 18:29:40,353 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:40,370 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:40,389 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:40,406 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:40,422 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:40,440 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  98%|█████████▊| 21591/22132 [07:54<00:09, 54.61it/s]

2026-09-09 18:29:40,458 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:40,475 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:40,497 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:29:40,525 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:29:40,548 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:29:40,566 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  98%|█████████▊| 21597/22132 [07:54<00:10, 52.29it/s]

2026-09-09 18:29:40,587 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:40,606 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:40,625 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:40,644 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:40,663 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:40,685 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  98%|█████████▊| 21603/22132 [07:54<00:10, 51.72it/s]

2026-09-09 18:29:40,704 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:40,723 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:40,740 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:40,758 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:40,776 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:40,798 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  98%|█████████▊| 21609/22132 [07:54<00:10, 52.18it/s]

2026-09-09 18:29:40,818 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:40,845 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:29:40,869 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:29:40,894 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:29:40,913 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:40,929 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  98%|█████████▊| 21615/22132 [07:55<00:10, 50.09it/s]

2026-09-09 18:29:40,944 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:40,960 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:40,977 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:40,994 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:41,014 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:41,033 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records:  98%|█████████▊| 21621/22132 [07:55<00:09, 52.06it/s]

2026-09-09 18:29:41,050 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:41,068 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:41,083 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:41,101 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:41,117 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:41,133 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:41,150 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  98%|█████████▊| 21628/22132 [07:55<00:09, 54.42it/s]

2026-09-09 18:29:41,167 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:41,183 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:41,198 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:41,215 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:41,230 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:41,247 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:41,263 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  98%|█████████▊| 21635/22132 [07:55<00:08, 56.67it/s]

2026-09-09 18:29:41,281 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:41,297 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:41,313 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:41,330 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:41,345 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:41,360 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:29:41,375 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  98%|█████████▊| 21642/22132 [07:55<00:08, 58.37it/s]

2026-09-09 18:29:41,393 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:41,411 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:41,427 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:41,446 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:41,463 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:41,480 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  98%|█████████▊| 21648/22132 [07:55<00:08, 58.01it/s]

2026-09-09 18:29:41,500 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:41,517 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:41,535 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:41,552 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:41,568 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:41,584 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  98%|█████████▊| 21654/22132 [07:55<00:08, 58.03it/s]

2026-09-09 18:29:41,600 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:41,617 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:41,633 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:41,650 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:41,666 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:41,682 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:41,700 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  98%|█████████▊| 21661/22132 [07:55<00:08, 58.76it/s]

2026-09-09 18:29:41,716 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:41,732 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:41,748 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:41,764 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:41,781 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:41,799 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:41,815 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  98%|█████████▊| 21668/22132 [07:55<00:07, 59.30it/s]

2026-09-09 18:29:41,832 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:41,848 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:41,864 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:41,881 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:41,897 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:41,914 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:41,932 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  98%|█████████▊| 21675/22132 [07:56<00:07, 59.54it/s]

2026-09-09 18:29:41,949 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:41,965 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:41,985 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:42,003 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:42,031 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:29:42,048 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  98%|█████████▊| 21681/22132 [07:56<00:07, 57.15it/s]

2026-09-09 18:29:42,066 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:42,081 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:42,100 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:42,119 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:42,135 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:42,155 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  98%|█████████▊| 21687/22132 [07:56<00:07, 56.76it/s]

2026-09-09 18:29:42,172 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:42,189 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:42,205 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:42,222 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:42,240 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:42,258 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  98%|█████████▊| 21693/22132 [07:56<00:07, 57.20it/s]

2026-09-09 18:29:42,276 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:42,291 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:42,308 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:42,323 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:42,339 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:42,403 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.062s]

Indexing Records:  98%|█████████▊| 21699/22132 [07:56<00:08, 51.56it/s]

2026-09-09 18:29:42,419 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:42,437 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:42,455 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:42,472 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:42,487 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:42,505 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  98%|█████████▊| 21705/22132 [07:56<00:07, 53.42it/s]

2026-09-09 18:29:42,522 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:42,537 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:42,553 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:42,573 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:42,589 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:42,605 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:42,621 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  98%|█████████▊| 21712/22132 [07:56<00:07, 55.58it/s]

2026-09-09 18:29:42,638 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:42,653 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:42,669 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:42,688 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:42,705 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:42,721 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  98%|█████████▊| 21718/22132 [07:56<00:07, 56.67it/s]

2026-09-09 18:29:42,739 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:42,755 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:42,771 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:42,788 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:42,806 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:42,822 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  98%|█████████▊| 21724/22132 [07:56<00:07, 57.56it/s]

2026-09-09 18:29:42,850 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:29:42,868 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:42,884 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:42,900 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:42,916 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:42,931 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  98%|█████████▊| 21730/22132 [07:57<00:07, 56.68it/s]

2026-09-09 18:29:42,948 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:42,963 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:42,979 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:42,994 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.013s]
2026-09-09 18:29:43,013 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:43,037 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records:  98%|█████████▊| 21736/22132 [07:57<00:06, 56.64it/s]

2026-09-09 18:29:43,055 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:43,073 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:43,091 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:43,110 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:43,128 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:43,146 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  98%|█████████▊| 21742/22132 [07:57<00:06, 56.21it/s]

2026-09-09 18:29:43,170 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:29:43,190 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:43,214 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:29:43,232 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:43,249 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:43,267 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  98%|█████████▊| 21748/22132 [07:57<00:07, 54.10it/s]

2026-09-09 18:29:43,285 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:43,307 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:43,325 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:43,342 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:43,360 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:43,377 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  98%|█████████▊| 21754/22132 [07:57<00:06, 54.20it/s]

2026-09-09 18:29:43,396 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:43,412 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:43,430 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:43,447 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:43,468 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:43,486 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  98%|█████████▊| 21760/22132 [07:57<00:06, 54.50it/s]

2026-09-09 18:29:43,508 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:43,526 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:43,544 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:43,562 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:43,579 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:43,596 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  98%|█████████▊| 21766/22132 [07:57<00:06, 54.41it/s]

2026-09-09 18:29:43,618 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:43,642 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:29:43,662 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:43,678 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:43,698 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:43,716 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  98%|█████████▊| 21772/22132 [07:57<00:06, 53.06it/s]

2026-09-09 18:29:43,736 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:43,755 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:43,775 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:43,792 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:43,809 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:43,827 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  98%|█████████▊| 21778/22132 [07:57<00:06, 53.33it/s]

2026-09-09 18:29:43,843 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:43,861 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:43,878 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:43,896 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:43,914 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:43,931 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  98%|█████████▊| 21784/22132 [07:58<00:06, 54.55it/s]

2026-09-09 18:29:43,947 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:43,964 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:43,981 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:43,998 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:44,021 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:29:44,045 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]

Indexing Records:  98%|█████████▊| 21790/22132 [07:58<00:06, 54.04it/s]

2026-09-09 18:29:44,073 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:29:44,091 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:44,109 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:44,125 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:44,146 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:44,163 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  98%|█████████▊| 21796/22132 [07:58<00:06, 53.02it/s]

2026-09-09 18:29:44,181 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:44,200 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:44,216 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:44,233 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:44,248 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:44,265 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  99%|█████████▊| 21802/22132 [07:58<00:06, 54.64it/s]

2026-09-09 18:29:44,282 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:44,298 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:44,313 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:44,329 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:44,345 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:44,361 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:44,379 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  99%|█████████▊| 21809/22132 [07:58<00:05, 56.73it/s]

2026-09-09 18:29:44,395 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:44,410 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:44,427 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:44,446 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:44,463 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:44,478 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:44,494 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  99%|█████████▊| 21816/22132 [07:58<00:05, 58.02it/s]

2026-09-09 18:29:44,512 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:44,529 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:44,549 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:44,567 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:44,583 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:44,599 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  99%|█████████▊| 21822/22132 [07:58<00:05, 57.77it/s]

2026-09-09 18:29:44,616 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:44,632 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:44,650 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:44,668 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:44,692 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:29:44,714 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records:  99%|█████████▊| 21828/22132 [07:58<00:05, 55.98it/s]

2026-09-09 18:29:44,733 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:44,752 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:44,770 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:44,789 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:44,811 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:29:44,832 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records:  99%|█████████▊| 21834/22132 [07:58<00:05, 54.37it/s]

2026-09-09 18:29:44,854 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:44,873 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:44,889 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:44,904 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:44,921 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:44,938 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  99%|█████████▊| 21840/22132 [07:59<00:05, 55.10it/s]

2026-09-09 18:29:44,955 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:44,974 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:44,989 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:45,005 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:45,027 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:29:45,047 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records:  99%|█████████▊| 21846/22132 [07:59<00:05, 55.03it/s]

2026-09-09 18:29:45,068 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:45,089 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:45,109 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:45,126 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:45,142 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:45,159 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  99%|█████████▊| 21852/22132 [07:59<00:05, 54.62it/s]

2026-09-09 18:29:45,176 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:45,194 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:45,210 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:45,226 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:45,243 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:45,258 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:45,274 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  99%|█████████▉| 21859/22132 [07:59<00:04, 56.53it/s]

2026-09-09 18:29:45,291 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:45,307 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:45,327 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:45,343 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:45,359 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:45,375 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  99%|█████████▉| 21865/22132 [07:59<00:04, 57.31it/s]

2026-09-09 18:29:45,394 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:45,409 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:45,425 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:45,441 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:45,457 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:45,472 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:45,489 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  99%|█████████▉| 21872/22132 [07:59<00:04, 58.50it/s]

2026-09-09 18:29:45,514 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:29:45,543 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:29:45,571 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:29:45,590 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:45,606 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:45,623 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  99%|█████████▉| 21878/22132 [07:59<00:04, 53.87it/s]

2026-09-09 18:29:45,641 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:45,656 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:45,673 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:45,689 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:45,707 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:45,723 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:45,739 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  99%|█████████▉| 21885/22132 [07:59<00:04, 55.80it/s]

2026-09-09 18:29:45,758 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:45,776 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:45,793 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:45,816 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:29:45,832 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:45,848 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  99%|█████████▉| 21891/22132 [07:59<00:04, 55.56it/s]

2026-09-09 18:29:45,865 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:45,882 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:45,899 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:45,915 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:45,930 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:45,948 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:45,963 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  99%|█████████▉| 21898/22132 [08:00<00:04, 57.13it/s]

2026-09-09 18:29:45,983 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:45,999 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:46,019 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:46,037 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:46,054 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:46,073 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  99%|█████████▉| 21904/22132 [08:00<00:04, 56.51it/s]

2026-09-09 18:29:46,089 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:46,110 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:46,126 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:46,141 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:46,157 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:46,173 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  99%|█████████▉| 21910/22132 [08:00<00:03, 57.43it/s]

2026-09-09 18:29:46,193 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:46,209 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:46,228 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:46,243 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:46,260 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:46,276 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  99%|█████████▉| 21916/22132 [08:00<00:03, 57.67it/s]

2026-09-09 18:29:46,294 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:46,309 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:46,325 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:46,342 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:46,359 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:46,376 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  99%|█████████▉| 21922/22132 [08:00<00:03, 58.26it/s]

2026-09-09 18:29:46,394 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:46,411 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:46,428 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:46,446 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:46,464 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:46,483 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  99%|█████████▉| 21928/22132 [08:00<00:03, 57.70it/s]

2026-09-09 18:29:46,499 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:46,516 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:46,534 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:46,552 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:46,571 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:46,586 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  99%|█████████▉| 21934/22132 [08:00<00:03, 57.77it/s]

2026-09-09 18:29:46,603 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:46,620 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:46,635 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:46,650 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:46,665 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:46,681 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:46,697 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  99%|█████████▉| 21941/22132 [08:00<00:03, 59.36it/s]

2026-09-09 18:29:46,715 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:46,731 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:46,746 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:46,763 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:46,781 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:46,796 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:46,812 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  99%|█████████▉| 21948/22132 [08:00<00:03, 59.96it/s]

2026-09-09 18:29:46,828 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:46,844 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:46,860 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:46,877 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:46,895 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:46,911 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:46,926 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  99%|█████████▉| 21955/22132 [08:01<00:02, 60.36it/s]

2026-09-09 18:29:46,942 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:46,957 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:46,973 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:46,990 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:47,005 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:47,022 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:47,040 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records:  99%|█████████▉| 21962/22132 [08:01<00:02, 60.66it/s]

2026-09-09 18:29:47,059 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:47,075 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:47,090 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:47,105 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:47,122 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:47,138 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:47,153 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  99%|█████████▉| 21969/22132 [08:01<00:02, 61.05it/s]

2026-09-09 18:29:47,170 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:47,185 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:47,202 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:47,219 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:47,235 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:47,253 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:47,269 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]

Indexing Records:  99%|█████████▉| 21976/22132 [08:01<00:02, 60.92it/s]

2026-09-09 18:29:47,284 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:47,299 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:47,315 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:47,332 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:47,348 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:47,363 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:47,379 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  99%|█████████▉| 21983/22132 [08:01<00:02, 61.70it/s]

2026-09-09 18:29:47,395 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:47,410 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:47,429 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:47,447 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:47,462 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:47,480 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:47,495 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  99%|█████████▉| 21990/22132 [08:01<00:02, 61.25it/s]

2026-09-09 18:29:47,514 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:47,531 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:47,547 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:47,562 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:47,583 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:47,598 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:47,615 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  99%|█████████▉| 21997/22132 [08:01<00:02, 60.30it/s]

2026-09-09 18:29:47,632 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:47,648 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:47,664 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:47,681 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:47,697 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:47,712 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:47,727 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]

Indexing Records:  99%|█████████▉| 22004/22132 [08:01<00:02, 61.03it/s]

2026-09-09 18:29:47,743 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.014s]
2026-09-09 18:29:47,759 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:47,793 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:29:47,812 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:47,830 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:47,848 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:47,865 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  99%|█████████▉| 22011/22132 [08:02<00:02, 57.45it/s]

2026-09-09 18:29:47,884 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:47,901 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:47,923 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:29:47,940 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:47,960 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:47,977 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records:  99%|█████████▉| 22017/22132 [08:02<00:02, 56.38it/s]

2026-09-09 18:29:47,996 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:48,015 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:48,033 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:48,053 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:48,071 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:48,089 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records: 100%|█████████▉| 22023/22132 [08:02<00:01, 55.57it/s]

2026-09-09 18:29:48,107 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:48,124 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:48,144 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:48,163 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:48,180 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:48,198 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records: 100%|█████████▉| 22029/22132 [08:02<00:01, 55.48it/s]

2026-09-09 18:29:48,217 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:48,236 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:48,258 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:29:48,277 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:48,298 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:48,319 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]

Indexing Records: 100%|█████████▉| 22035/22132 [08:02<00:01, 53.58it/s]

2026-09-09 18:29:48,338 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:48,357 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:48,377 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:48,397 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:48,421 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:29:48,439 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records: 100%|█████████▉| 22041/22132 [08:02<00:01, 52.44it/s]

2026-09-09 18:29:48,458 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:48,476 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:48,503 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.026s]
2026-09-09 18:29:48,524 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:48,547 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:29:48,593 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.044s]

Indexing Records: 100%|█████████▉| 22047/22132 [08:02<00:01, 47.62it/s]

2026-09-09 18:29:48,623 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:29:48,643 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:48,685 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.040s]
2026-09-09 18:29:48,740 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.054s]
2026-09-09 18:29:48,766 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]

Indexing Records: 100%|█████████▉| 22052/22132 [08:02<00:01, 40.76it/s]

2026-09-09 18:29:48,809 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.041s]
2026-09-09 18:29:48,838 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.028s]
2026-09-09 18:29:48,875 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.035s]
2026-09-09 18:29:48,907 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.031s]
2026-09-09 18:29:48,937 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]

Indexing Records: 100%|█████████▉| 22057/22132 [08:03<00:02, 36.83it/s]

2026-09-09 18:29:48,966 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]
2026-09-09 18:29:49,009 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.042s]
2026-09-09 18:29:49,028 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:49,057 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.027s]

Indexing Records: 100%|█████████▉| 22061/22132 [08:03<00:01, 35.95it/s]

2026-09-09 18:29:49,091 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.032s]
2026-09-09 18:29:49,118 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.025s]
2026-09-09 18:29:49,148 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:29:49,172 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]

Indexing Records: 100%|█████████▉| 22065/22132 [08:03<00:01, 35.63it/s]

2026-09-09 18:29:49,193 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:49,213 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:49,244 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.029s]
2026-09-09 18:29:49,265 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:49,287 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]

Indexing Records: 100%|█████████▉| 22070/22132 [08:03<00:01, 37.78it/s]

2026-09-09 18:29:49,305 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:49,326 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:49,349 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:29:49,369 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:49,389 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records: 100%|█████████▉| 22075/22132 [08:03<00:01, 40.64it/s]

2026-09-09 18:29:49,408 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:49,425 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:49,445 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:49,462 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:49,482 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:49,500 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records: 100%|█████████▉| 22081/22132 [08:03<00:01, 44.44it/s]

2026-09-09 18:29:49,517 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.015s]
2026-09-09 18:29:49,535 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:49,555 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:49,575 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:49,592 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:49,609 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records: 100%|█████████▉| 22087/22132 [08:03<00:00, 47.44it/s]

2026-09-09 18:29:49,628 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:49,645 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:49,665 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:49,683 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:49,705 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:29:49,725 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]

Indexing Records: 100%|█████████▉| 22093/22132 [08:03<00:00, 48.70it/s]

2026-09-09 18:29:49,743 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:49,761 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:49,784 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.022s]
2026-09-09 18:29:49,802 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:49,820 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:49,837 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records: 100%|█████████▉| 22099/22132 [08:03<00:00, 50.13it/s]

2026-09-09 18:29:49,857 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:49,874 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:49,894 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:49,918 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.023s]
2026-09-09 18:29:49,936 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:49,954 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records: 100%|█████████▉| 22105/22132 [08:04<00:00, 50.57it/s]

2026-09-09 18:29:49,972 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:49,994 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:50,014 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:50,032 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:50,052 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:50,072 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]

Indexing Records: 100%|█████████▉| 22111/22132 [08:04<00:00, 50.64it/s]

2026-09-09 18:29:50,091 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:50,111 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:50,133 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.021s]
2026-09-09 18:29:50,151 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:50,170 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:50,195 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.024s]

Indexing Records: 100%|█████████▉| 22117/22132 [08:04<00:00, 50.02it/s]

2026-09-09 18:29:50,216 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:50,234 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:50,252 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:50,269 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:50,291 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:50,308 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records: 100%|█████████▉| 22123/22132 [08:04<00:00, 50.88it/s]

2026-09-09 18:29:50,327 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]
2026-09-09 18:29:50,346 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:50,365 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.018s]
2026-09-09 18:29:50,382 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:50,403 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.020s]
2026-09-09 18:29:50,420 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]

Indexing Records: 100%|█████████▉| 22129/22132 [08:04<00:00, 51.68it/s]

2026-09-09 18:29:50,441 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.019s]
2026-09-09 18:29:50,458 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.016s]
2026-09-09 18:29:50,477 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_doc [status:201 request:0.017s]

Indexing Records: 100%|██████████| 22132/22132 [08:04<00:00, 45.67it/s]

Error retrieving document count: name 'client' is not defined

In [41]:
print("Done")

Done

In [42]:
#Check 
res = aos_client.search(index=index_name, body={"query": {"match_all": {}}})
print(f"Records loaded into the index {index_name} is {res['hits']['total']['value']}.")

2026-09-09 18:29:58,891 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_search [status:200 request:8.221s]
Records loaded into the index gte-multi-ft2 is 10000.

In [43]:
aos_client.indices.get_mapping(index=index_name)[index_name]["mappings"]["properties"]["vector"]

2026-09-09 18:30:28,904 - INFO - GET https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_mapping [status:200 request:0.062s]

{'type': 'knn_vector',
 'store': True,
 'dimension': 768,
 'space_type': 'cosinesimil'}

In [44]:
aos_client.indices.get_settings(index=index_name)[index_name]["settings"]["index"]

2026-09-09 18:30:29,662 - INFO - GET https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft2/_settings [status:200 request:0.022s]

{'replication': {'type': 'DOCUMENT'},
 'number_of_shards': '5',
 'provided_name': 'gte-multi-ft2',
 'knn.space_type': 'cosinesimil',
 'knn': 'true',
 'creation_date': '1788969049698',
 'analysis': {'analyzer': {'default': {'type': 'standard',
    'stopwords': '_english_'}}},
 'number_of_replicas': '1',
 'uuid': 'Vm1vFlR3Q4SuniulGwIg-g',
 'version': {'created': '136407827'}}

## 5. Test the model endpoints and perform search in OpenSearch index

In [38]:
from sagemaker_fn import invoke_sagemaker_endpoint_ft

2026-08-25 19:28:42,386 - INFO - Found credentials from IAM Role: BaseNotebookInstanceEc2InstanceRole

In [40]:
endpoint_name ='gte-multi-ft2'
payload = {"inputs": "floods event in Canada"}
vector = invoke_sagemaker_endpoint_ft(endpoint_name, payload)
print(len(vector))

Error invoking SageMaker endpoint gte-multi-ft2: An error occurred (ModelError) when calling the InvokeEndpoint operation: Received client error (400) from primary with message "{
  "code": 400,
  "type": "InternalServerException",
  "message": "unable to mmap 1221487872 bytes from file \u003c/opt/ml/model/model.safetensors\u003e: Cannot allocate memory (12)"
}
". See https://ca-central-1.console.aws.amazon.com/cloudwatch/home?region=ca-central-1#logEventViewer:group=/aws/sagemaker/Endpoints/gte-multi-ft2 in account 759472643633 for more information.

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:4                                                                                    │
│                                                                                                  │
│   1 endpoint_name ='gte-multi-ft2'                                                               │
│   2 payload = {"inputs": "floods event in Canada"}                                               │
│   3 vector = invoke_sagemaker_endpoint_ft(endpoint_name, payload)                                │
│ ❱ 4 print(len(vector))                                                                           │
│   5                                                                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: object of type 'NoneType' has no len()

In [13]:
endpoint_name ='gte-multi-ft2-se'
payload = {"inputs": ["floods event in Canada", "earthquakes"]}

runtime_client = boto3.client('runtime.sagemaker', region_name='ca-central-1')  

response = runtime_client.invoke_endpoint(
            EndpointName=endpoint_name,
            ContentType='application/json',
            Body=json.dumps(payload)
        )

print(response)

{'ResponseMetadata': {'RequestId': '2393cb88-b5c6-454b-b7a0-a25adeb4dfdf', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': '2393cb88-b5c6-454b-b7a0-a25adeb4dfdf', 'x-amzn-invoked-production-variant': 'AllTraffic', 'date': 'Tue, 21 Jul 2026 17:35:07 GMT', 'content-type': 'application/json', 'content-length': '16172', 'connection': 'keep-alive'}, 'RetryAttempts': 0}, 'ContentType': 'application/json', 'InvokedProductionVariant': 'AllTraffic', 'Body': <botocore.response.StreamingBody object at 0x7f5492328a00>}

In [14]:
json.loads(response['Body'].read().decode())

[-0.06540855020284653,
 0.051884137094020844,
 -0.06542105972766876,
 0.022129319608211517,
 -0.020327437669038773,
 -0.04043056443333626,
 -0.03482047840952873,
 0.009951615706086159,
 0.0008859827066771686,
 -0.025461973622441292,
 -0.027091972529888153,
 -0.025003228336572647,
 -0.02428983710706234,
 -0.004127128981053829,
 -0.05269454047083855,
 -0.005767416208982468,
 0.0174634400755167,
 0.011371737346053123,
 0.05050159990787506,
 0.017035048454999924,
 0.059427861124277115,
 0.05286277085542679,
 -0.014053180813789368,
 -0.01908683031797409,
 0.009503193199634552,
 -0.014232094399631023,
 0.015337239019572735,
 -0.06617682427167892,
 -0.0327041894197464,
 0.010586082004010677,
 -0.05081013962626457,
 -0.05046484246850014,
 0.01070164144039154,
 -0.0027587618678808212,
 0.032590825110673904,
 0.01294077467173338,
 0.01709040440618992,
 -0.006858904380351305,
 0.011488605290651321,
 -0.005110503174364567,
 0.019115351140499115,
 -0.053415440022945404,
 0.016735345125198364,
 0.027016906067728996,
 -0.01313547883182764,
 0.026471799239516258,
 -0.03354924917221069,
 0.06604951620101929,
 0.00610636780038476,
 0.0308847576379776,
 0.011095879599452019,
 0.028515996411442757,
 0.03542710468173027,
 0.01128275878727436,
 0.04705600440502167,
 0.022257937118411064,
 -0.047448646277189255,
 0.01522618904709816,
 0.005735419690608978,
 -0.020257271826267242,
 0.02276718243956566,
 -0.011534816585481167,
 0.0016680185217410326,
 -0.020492156967520714,
 -0.022631391882896423,
 -0.01482473686337471,
 0.008850466459989548,
 0.006708149798214436,
 0.12234898656606674,
 0.025928154587745667,
 0.004028881900012493,
 0.05016456916928291,
 -0.016891086474061012,
 0.04776632785797119,
 -0.008138122037053108,
 0.014663510024547577,
 -0.025210915133357048,
 -0.02113361470401287,
 -0.01832849718630314,
 0.03167859464883804,
 -0.007433365564793348,
 -0.0009143460192717612,
 0.022152002900838852,
 0.0037395330145955086,
 -0.01054263487458229,
 -0.012468326836824417,
 -0.04919666051864624,
 -0.0314565971493721,
 -0.03102799318730831,
 0.02516385167837143,
 0.030782779678702354,
 0.005518672522157431,
 0.006890696007758379,
 -0.05328691378235817,
 0.027384493499994278,
 0.04614071547985077,
 0.028607208281755447,
 0.014985624700784683,
 0.0229767058044672,
 0.01938805542886257,
 -0.006761898752301931,
 0.01761195994913578,
 0.0588640458881855,
 -0.007936902344226837,
 0.028045566752552986,
 -0.028592213988304138,
 0.04531430825591087,
 -0.007924219593405724,
 0.008456476032733917,
 -0.007625945378094912,
 0.003400820540264249,
 0.004012530203908682,
 -0.06356117874383926,
 -0.024889307096600533,
 -0.01128630992025137,
 0.030677348375320435,
 0.027015896514058113,
 0.006821237970143557,
 -0.008614170365035534,
 0.011185979470610619,
 -0.03563198447227478,
 0.024707358330488205,
 -0.048758987337350845,
 0.024710094556212425,
 -0.08205244690179825,
 0.025227738544344902,
 -0.009243140928447247,
 0.006253339350223541,
 -0.02476409822702408,
 -0.012746537104249,
 0.016629409044981003,
 0.0027799285016953945,
 0.019992973655462265,
 -0.03359692171216011,
 -0.02066582441329956,
 -0.06712200492620468,
 -0.00597839942201972,
 0.05358405038714409,
 0.03549319505691528,
 -0.028368985280394554,
 -0.07338165491819382,
 0.013833850622177124,
 -0.08060213178396225,
 -0.01794283464550972,
 0.014889051206409931,
 0.013094086199998856,
 -0.029647817835211754,
 -0.0076682670041918755,
 -0.002077597426250577,
 0.04193815216422081,
 -0.011410676874220371,
 0.043597511947155,
 0.04804070293903351,
 0.01256975345313549,
 0.05773938074707985,
 -0.017765209078788757,
 -0.010644173249602318,
 0.04539724439382553,
 -0.030060697346925735,
 0.004422451835125685,
 0.03027721494436264,
 0.01707799918949604,
 0.034358058124780655,
 -0.026081671938300133,
 -0.01705079898238182,
 -0.009325320832431316,
 -0.023112479597330093,
 0.008847685530781746,
 0.03664941340684891,
 -0.0017211836529895663,
 -0.059588491916656494,
 0.04795337840914726,
 0.054232656955718994,
 0.013215172104537487,
 0.017186062410473824,
 0.014751443639397621,
 -0.03939516842365265,
 0.02417389117181301,
 0.025120951235294342,
 0.034837543964385986,
 0.03441799804568291,
 -0.05097624287009239,
 -0.014499678276479244,
 -0.044460445642471313,
 0.069801464676857,
 0.015430710278451443,
 -0.05053994432091713,
 -0.029293939471244812,
 -0.011888731271028519,
 0.006725161336362362,
 0.0027029847260564566,
 0.05381869524717331,
 -0.08292780816555023,
 -0.03164668381214142,
 -0.026243211701512337,
 -0.010989224538207054,
 -0.012909071519970894,
 0.016109274700284004,
 0.006684617605060339,
 0.0202258862555027,
 0.016562702134251595,
 -0.017137082293629646,
 -0.014603608287870884,
 0.046810537576675415,
 -0.04375528544187546,
 -0.012849771417677402,
 -0.005242972169071436,
 -0.026192793622612953,
 -0.008890604600310326,
 -0.046551864594221115,
 0.004666774533689022,
 0.0015542893670499325,
 0.034251198172569275,
 0.031833257526159286,
 -0.027597393840551376,
 -0.030410880222916603,
 0.016954028978943825,
 -0.017402656376361847,
 0.028105325996875763,
 -0.04183840751647949,
 -0.03967829793691635,
 -0.006399010773748159,
 -0.020833352580666542,
 -0.02865295670926571,
 0.012106292881071568,
 -0.019817247986793518,
 -0.028986042365431786,
 0.049819860607385635,
 0.05077311396598816,
 -0.03488657623529434,
 0.006421301048249006,
 -0.024625370278954506,
 0.00797915831208229,
 -0.05376552417874336,
 0.017554018646478653,
 -0.009700078517198563,
 0.0038778604939579964,
 0.011200633831322193,
 -0.03587144985795021,
 -0.02022673934698105,
 0.017850229516625404,
 0.009936166927218437,
 0.014938612468540668,
 -0.026009272783994675,
 0.012036514468491077,
 -0.009483234025537968,
 -0.02852114476263523,
 -0.024447444826364517,
 -0.028291216120123863,
 -0.018554670736193657,
 0.03432583063840866,
 0.007931449450552464,
 0.005076556000858545,
 0.03198534622788429,
 0.0013651133049279451,
 -0.03403138369321823,
 -0.053163059055805206,
 0.03905940428376198,
 -0.011277740821242332,
 -0.007908014580607414,
 -0.025244878605008125,
 -0.028446577489376068,
 -0.002115927403792739,
 0.026189599186182022,
 0.038236696273088455,
 -0.08228951692581177,
 0.02516930364072323,
 -0.010733244940638542,
 -0.02886127680540085,
 0.04298580437898636,
 -0.02983991615474224,
 0.02972606010735035,
 -0.0029825298115611076,
 0.002341519808396697,
 -0.009853066876530647,
 -0.02100682072341442,
 -0.01820783130824566,
 -0.027907462790608406,
 0.02304512821137905,
 -0.042776163667440414,
 0.024591602385044098,
 -0.004266147036105394,
 -0.017597274854779243,
 -0.030678641051054,
 -0.036289554089307785,
 0.025750409811735153,
 0.039869341999292374,
 -0.0177464596927166,
 -0.014905085787177086,
 0.0030959469731897116,
 0.02250736393034458,
 -0.028990263119339943,
 -9.026868065120652e-05,
 0.005951186642050743,
 0.0022784825414419174,
 -0.0003673038736451417,
 -0.03026999719440937,
 0.0671810656785965,
 0.02374797873198986,
 -0.023801688104867935,
 -0.047446005046367645,
 -0.028866255655884743,
 0.04309655353426933,
 0.020162221044301987,
 -0.03946252912282944,
 -0.050474174320697784,
 -0.047651246190071106,
 0.010177506133913994,
 -0.027276987209916115,
 0.03510688245296478,
 -0.04342366009950638,
 0.010793996043503284,
 0.03022262640297413,
 -0.02459775097668171,
 0.044162146747112274,
 0.027936691418290138,
 0.01962994411587715,
 0.007184031885117292,
 -0.011994094587862492,
 0.0229928120970726,
 0.01158896740525961,
 0.12262734770774841,
 -0.03780785948038101,
 -0.0063411034643650055,
 -0.00471546920016408,
 -0.0495627261698246,
 0.003961095120757818,
 0.03775681555271149,
 -0.021402817219495773,
 0.006394231226295233,
 0.046475935727357864,
 -0.004158012568950653,
 -0.02862234227359295,
 -0.07519692182540894,
 0.01008893083781004,
 0.015897968783974648,
 0.03806100785732269,
 -0.023158466443419456,
 0.04041401669383049,
 -0.017403101548552513,
 0.018757440149784088,
 0.05668420344591141,
 -0.06683855503797531,
 -0.006174797657877207,
 0.05829421430826187,
 -0.0035793362185359,
 0.02584204077720642,
 -0.041822392493486404,
 0.016294360160827637,
 -0.0207054503262043,
 0.02271045558154583,
 -0.02163693495094776,
 0.04760893061757088,
 0.029312482103705406,
 -0.04765202850103378,
 0.018640773370862007,
 -0.015801534056663513,
 0.04274030774831772,
 0.03415195271372795,
 0.05847381055355072,
 0.021047819405794144,
 0.03331940993666649,
 0.019177690148353577,
 0.04960404708981514,
 0.015051311813294888,
 -0.014790759421885014,
 -0.04026297852396965,
 0.028791436925530434,
 -0.01674436591565609,
 0.046052247285842896,
 -0.00921338889747858,
 0.009132127277553082,
 0.026332255452871323,
 0.044037044048309326,
 -0.008025971241295338,
 0.0079816784709692,
 0.030102474614977837,
 0.027312273159623146,
 0.03150765970349312,
 -0.0051638539880514145,
 -0.09840791672468185,
 -0.03333955258131027,
 -0.0007245381129905581,
 0.015625063329935074,
 -0.03186579793691635,
 -0.010038449428975582,
 0.028879918158054352,
 -0.03646732494235039,
 -0.022792190313339233,
 -0.019732698798179626,
 0.04127800464630127,
 0.043667349964380264,
 0.008069196715950966,
 -0.03679744154214859,
 0.009136163629591465,
 0.03331396356225014,
 0.032986950129270554,
 0.013773828744888306,
 -0.017521347850561142,
 0.03652273118495941,
 0.02010923996567726,
 -0.013709275051951408,
 0.020120101049542427,
 0.011148542165756226,
 -0.004307810217142105,
 0.017732881009578705,
 0.022519221529364586,
 -0.03636081516742706,
 0.02937197871506214,
 -0.03784729912877083,
 0.03312504291534424,
 -0.022695807740092278,
 0.0014212458627298474,
 -0.03950425982475281,
 -0.006529781501740217,
 0.06194096803665161,
 0.0406867116689682,
 0.06993097811937332,
 0.15519744157791138,
 -0.01014547236263752,
 0.050828710198402405,
 0.037211254239082336,
 0.020226387307047844,
 -0.025129025802016258,
 -0.03703203797340393,
 0.0572720430791378,
 0.02614051103591919,
 0.040974583476781845,
 -0.034864749759435654,
 0.05289061740040779,
 -0.03911299630999565,
 0.03906133025884628,
 0.014345670118927956,
 0.002624805551022291,
 -0.010675208643078804,
 0.05622844398021698,
 0.004642179235816002,
 -0.028178000822663307,
 0.030003145337104797,
 0.0013207722222432494,
 -0.017230335623025894,
 -0.008564595133066177,
 0.03982396796345711,
 0.011950907297432423,
 -0.014914829283952713,
 -0.042800433933734894,
 -0.006626385264098644,
 0.0492553748190403,
 -0.0031653500627726316,
 -0.06374680995941162,
 -0.0433390736579895,
 0.026195775717496872,
 -0.0074330829083919525,
 -0.014301559887826443,
 0.037626463919878006,
 -0.03231338411569595,
 0.01140338834375143,
 -0.05593645200133324,
 0.006299891043454409,
 -0.0998208075761795,
 -0.006628008559346199,
 -0.05024602636694908,
 0.024519117549061775,
 0.05232016742229462,
 0.03797294199466705,
 0.027453774586319923,
 0.01467747613787651,
 0.05542701110243797,
 -0.06730950623750687,
 0.028668582439422607,
 -0.039296697825193405,
 0.05133376643061638,
 0.008867386728525162,
 -0.014171619899570942,
 -0.0032687813509255648,
 0.016992734745144844,
 -0.034711286425590515,
 0.04477349668741226,
 0.012264754623174667,
 -0.08763276785612106,
 0.036851298063993454,
 0.03217482194304466,
 -0.042238205671310425,
 -0.03506709635257721,
 0.03298232704401016,
 0.03133310750126839,
 0.01769922487437725,
 -0.07226420193910599,
 -0.0424894355237484,
 0.03155329078435898,
 0.042570360004901886,
 0.060022998601198196,
 -0.029783593490719795,
 0.013332909904420376,
 0.019110938534140587,
 0.01722474955022335,
 0.030369440093636513,
 0.06820934265851974,
 0.013449047692120075,
 0.03964081406593323,
 -0.049797311425209045,
 -0.020062219351530075,
 0.006327263545244932,
 0.013363797217607498,
 0.04604914039373398,
 -0.014820922166109085,
 0.052270930260419846,
 0.01483818981796503,
 0.014786237850785255,
 0.00989739689975977,
 -0.015597204677760601,
 -0.022950127720832825,
 0.023131810128688812,
 -0.024569112807512283,
 -0.0550675168633461,
 0.011186056770384312,
 0.0034576060716062784,
 0.05401838198304176,
 0.026470500975847244,
 0.017010947689414024,
 0.022882090881466866,
 0.019163450226187706,
 -0.006329891737550497,
 -0.03674018383026123,
 -0.0012216242030262947,
 -0.0443941093981266,
 -0.04506845027208328,
 -0.02078365348279476,
 0.024959200993180275,
 0.019611835479736328,
 -0.017173053696751595,
 0.03580021485686302,
 -0.016781523823738098,
 0.05733590945601463,
 0.03294862061738968,
 0.01012695487588644,
 0.010535486042499542,
 0.047889839857816696,
 -0.02570420317351818,
 0.02355010062456131,
 0.030016057193279266,
 0.006948802620172501,
 0.02941439487040043,
 -0.03233296051621437,
 0.0351475365459919,
 0.029122021049261093,
 -0.008918453007936478,
 -0.08678413182497025,
 -0.02836773917078972,
 0.02721516415476799,
 0.028344526886940002,
 0.0510694645345211,
 0.020395146682858467,
 0.04422024264931679,
 -0.02248011715710163,
 -0.0028461164329200983,
 -0.056577783077955246,
 -0.019471781328320503,
 -0.05957118794322014,
 0.041075270622968674,
 -0.052458275109529495,
 -0.039525892585515976,
 0.020696960389614105,
 0.015960555523633957,
 0.01661626622080803,
 -0.007566393818706274,
 -0.014632018283009529,
 -0.02325642853975296,
 0.022610286250710487,
 0.013440446928143501,
 0.015324142761528492,
 0.041244033724069595,
 0.029653143137693405,
 -0.0023003844544291496,
 0.0063555194064974785,
 0.033260732889175415,
 0.04255955293774605,
 -0.004611357115209103,
 -0.01596415601670742,
 -0.004860531538724899,
 -0.05528237298130989,
 -0.053206104785203934,
 0.054769016802310944,
 0.005188636481761932,
 -0.04135352373123169,
 -0.01259689126163721,
 -0.054623525589704514,
 0.01984121836721897,
 0.01510787382721901,
 -0.03832610696554184,
 -0.030262522399425507,
 0.04470422863960266,
 0.013869565911591053,
 0.0124514764174819,
 -0.046986423432826996,
 -0.003345436416566372,
 0.03431492671370506,
 -0.03716472163796425,
 -0.0021241051144897938,
 0.05098075419664383,
 -0.020469175651669502,
 -0.07717392593622208,
 0.013450763188302517,
 0.03018428012728691,
 0.03731532022356987,
 0.03927294537425041,
 -0.0028979431372135878,
 -0.042031675577163696,
 -0.036888398230075836,
 0.013251000083982944,
 -0.032793499529361725,
 0.0003442654269747436,
 0.02831125631928444,
 -0.015039920806884766,
 0.04016951099038124,
 -0.024881966412067413,
 -0.023733744397759438,
 0.02478337101638317,
 -0.012553210370242596,
 0.019170477986335754,
 -0.04268109053373337,
 0.016431095078587532,
 -0.00496465852484107,
 0.012332974001765251,
 -0.0005930191255174577,
 0.02736269123852253,
 -0.020844796672463417,
 -0.060858990997076035,
 -0.07960770279169083,
 -0.04075778275728226,
 -0.025834821164608,
 -0.005401687230914831,
 0.03353232890367508,
 -0.034420814365148544,
 -0.029814403504133224,
 -0.00042353064054623246,
 -0.04269298538565636,
 -0.023494863882660866,
 -0.04238388314843178,
 0.0005980257992632687,
 0.009785547852516174,
 -0.07749390602111816,
 -0.00022376878769136965,
 0.033105842769145966,
 0.04185673967003822,
 0.037064988166093826,
 0.035861432552337646,
 -0.003832760499790311,
 -0.03862905874848366,
 0.03265273943543434,
 -0.018869534134864807,
 -0.05457698926329613,
 -0.021966855973005295,
 0.08869883418083191,
 -0.021412812173366547,
 0.013549822382628918,
 -0.0408829003572464,
 -0.031369615346193314,
 0.05454056337475777,
 0.11271794140338898,
 0.013102889992296696,
 -0.00106962607242167,
 0.09427037835121155,
 -0.006167978048324585,
 -0.012309234589338303,
 0.025062784552574158,
 0.04366699606180191,
 0.026374874636530876,
 0.003088922007009387,
 -0.010477324016392231,
 -0.026748858392238617,
 -0.02057497762143612,
 0.03449593111872673,
 0.034503474831581116,
 -0.05202895402908325,
 0.02830083668231964,
 0.0432157926261425,
 -0.076033815741539,
 -0.013908677734434605,
 0.03983713313937187,
 -0.021825319156050682,
 0.01603587158024311,
 0.0663309171795845,
 -0.05187391862273216,
 -0.016700245440006256,
 -0.007936223410069942,
 0.009066455997526646,
 -0.03641246631741524,
 0.020029930397868156,
 0.006584306247532368,
 0.03476725518703461,
 0.004744961392134428,
 0.034747492522001266,
 -0.01773260161280632,
 0.043157704174518585,
 -0.037644997239112854,
 0.046250518411397934,
 0.02368040196597576,
 -0.013950328342616558,
 -0.04289022088050842,
 0.04228762537240982,
 -0.014985008165240288,
 0.005522678606212139,
 0.011435801163315773,
 0.02066476084291935,
 -0.01268007978796959,
 0.03258951008319855,
 -0.02268695831298828,
 0.03588739037513733,
 0.05281386524438858,
 0.03139413148164749,
 -0.016575349494814873,
 0.011156028136610985,
 -0.006167218554764986,
 -0.05725502595305443,
 -0.00713918125256896,
 -0.007938487455248833,
 -0.006122472230345011,
 0.04568975046277046,
 0.27975207567214966,
 0.0032862736843526363,
 0.04236500337719917,
 -0.058566946536302567,
 -0.00025885182549245656,
 0.07486725598573685,
 0.0008793365559540689,
 0.019183261319994926,
 0.07229319959878922,
 0.05716031417250633,
 0.04890972375869751,
 0.04010001942515373,
 -0.012398888356983662,
 0.05320560559630394,
 0.0218893364071846,
 -0.04044575244188309,
 -0.015801778063178062,
 -0.024649320170283318,
 -0.04868290200829506,
 0.014250668697059155,
 -0.024399438872933388,
 0.04021827131509781,
 -0.042773228138685226,
 0.031881678849458694,
 0.035333167761564255,
 -0.0028047398664057255,
 0.08235319703817368,
 0.06209462136030197,
 0.1469699591398239,
 -0.02336975932121277,
 0.02573704533278942,
 -0.03743293136358261,
 0.04360204562544823,
 -0.04906647279858589,
 0.03816518187522888,
 0.02992337942123413,
 -0.00017970807675737888,
 -0.005050082691013813,
 -0.016602152958512306,
 -0.03644223138689995,
 0.037569593638181686,
 -0.03231549263000488,
 -0.016925999894738197,
 -0.018830878660082817,
 -0.005216749384999275,
 -0.06153586134314537,
 0.030181506648659706,
 0.020309681072831154,
 -0.007074024528264999]

In [41]:
host = "search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com"
region = "ca-central-1"
service = "es"

credentials = boto3.Session().get_credentials()

auth = Urllib3AWSV4SignerAuth(
    credentials,
    region,
    service
)

aos_client = OpenSearch(
    hosts=[{"host": host, "port": 443}],
    http_auth=auth,
    use_ssl=True,
    verify_certs=True,
    connection_class=Urllib3HttpConnection,
)

query={
    "size": 20,
    "query": {
        "knn": {
            "vector":{
                "vector":vector,
                "k":20
            }
        }
    }
}

res = aos_client.search(index='gte-multi-ft', size=20, body=query, request_timeout=55)
query_result=[]
for hit in res['hits']['hits']:
    row=[hit['_id'],hit['_score'],hit['_source']['title_en'], hit['_source']['organisation'],hit['_source']['id']]
    query_result.append(row)
query_result_df = pd.DataFrame(data=query_result,columns=["_id","relevancy_score","title","org",'uuid'])
display(query_result_df)

2026-08-25 19:29:39,210 - INFO - Found credentials from IAM Role: BaseNotebookInstanceEc2InstanceRole
2026-08-25 19:29:39,255 - WARNING - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft/_search?size=20 [status:400 request:0.044s]

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:33                                                                                   │
│                                                                                                  │
│   30 │   }                                                                                       │
│   31 }                                                                                           │
│   32                                                                                             │
│ ❱ 33 res = aos_client.search(index='gte-multi-ft', size=20, body=query, request_timeout=55)      │
│   34 query_result=[]                                                                             │
│   35 for hit in res['hits']['hits']:                                                             │
│   36 │   row=[hit['_id'],hit['_score'],hit['_source']['title_en'], hit['_source']['organisati    │
│                                                                                                  │
│ /home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/opensearchpy/client/utils.py: │
│ 176 in _wrapped                                                                                  │
│                                                                                                  │
│   173 │   │   │   │   │   if v is not None:                                                      │
│   174 │   │   │   │   │   │   params[p] = _escape(v)                                             │
│   175 │   │   │                                                                                  │
│ ❱ 176 │   │   │   return func(*args, params=params, headers=headers, **kwargs)                   │
│   177 │   │                                                                                      │
│   178 │   │   return _wrapped                                                                    │
│   179                                                                                            │
│                                                                                                  │
│ /home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/opensearchpy/client/__init__. │
│ py:2440 in search                                                                                │
│                                                                                                  │
│   2437 │   │   if "from_" in params:                                                             │
│   2438 │   │   │   params["from"] = params.pop("from_")                                          │
│   2439 │   │                                                                                     │
│ ❱ 2440 │   │   return self.transport.perform_request(                                            │
│   2441 │   │   │   "POST",                                                                       │
│   2442 │   │   │   _make_path(index, "_search"),                                                 │
│   2443 │   │   │   params=params,                                                                │
│                                                                                                  │
│ /home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/opensearchpy/transport.py:457 │
│ in perform_request                                                                               │
│                                                                                                  │
│   454 │   │   │   │   │   if attempt == self.max_retries:                                        │
│   455 │   │   │   │   │   │   raise e                                                            │
│   456 │   │   │   │   else:                                                                      │
│ ❱ 457 │   │   │   │   │   raise e                                                                │
│   458 │   │   │                                                                                  │
│   459 │   │   │   else:                                                                          │
│   460 │   │   │   │   # connection didn't fail, confirm its live status                          │
│                                                                                                  │
│ /home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/opensearchpy/transport.py:418 │
│ in perform_request                                                                               │
│                                                                                                  │
│   415 │   │   │   connection = self.get_connection()                                             │
│   416 │   │   │                                                                                  │
│   417 │   │   │   try:                                                                           │
│ ❱ 418 │   │   │   │   status, headers_response, data = connection.perform_request(               │
│   419 │   │   │   │   │   method,                                                                │
│   420 │   │   │   │   │   url,                                                                   │
│   421 │   │   │   │   │   params,                                                                │
│                                                                                                  │
│ /home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/opensearchpy/connection/http_ │
│ urllib3.py:308 in perform_request                                                                │
│                                                                                                  │
│   305 │   │   │   self.log_request_fail(                                                         │
│   306 │   │   │   │   method, full_url, url, orig_body, duration, response.status, raw_data      │
│   307 │   │   │   )                                                                              │
│ ❱ 308 │   │   │   self._raise_error(                                                             │
│   309 │   │   │   │   response.status,                                                           │
│   310 │   │   │   │   raw_data,                                                                  │
│   311 │   │   │   │   self.get_response_headers(response).get("content-type"),                   │
│                                                                                                  │
│ /home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/opensearchpy/connection/base. │
│ py:315 in _raise_error                                                                           │
│                                                                                                  │
│   312 │   │   except (ValueError, TypeError) as err:                                             │
│   313 │   │   │   logger.warning("Undecodable raw error response from server: %s", err)          │
│   314 │   │                                                                                      │
│ ❱ 315 │   │   raise HTTP_EXCEPTIONS.get(status_code, TransportError)(                            │
│   316 │   │   │   status_code, error_message, additional_info                                    │
│   317 │   │   )                                                                                  │
│   318                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RequestError: RequestError(400, 'x_content_parse_exception', "[1:47] [knn] vector doesn't support values of type:
VALUE_NULL")

In [53]:
payload = {"inputs": "wildfires Canada"}
endpoint_name ='gte-multi-ft-se'
vector = invoke_sagemaker_endpoint_ft(endpoint_name, payload)
query={
    "size": 20,
    "query": {
        "knn": {
            "vector":{
                "vector":vector,
                "k":20
            }
        }
    }
}

res = aos_client.search(index='gte-multi-ft', size=20, body=query, request_timeout=55)
query_result=[]
for hit in res['hits']['hits']:
    row=[hit['_id'],hit['_score'],hit['_source']['title'],hit['_source']['id']]
    query_result.append(row)
query_result_df = pd.DataFrame(data=query_result,columns=["_id","relevancy_score","title",'uuid'])
display(query_result_df)

2026-07-03 13:13:12,825 - INFO - POST https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft/_search?size=20 [status:200 request:0.096s]

,_id,relevancy_score,title,uuid
0,mpHsJ58B7EZDBsAegNgv,0.929031,Fire hydrants,1fdb895a-d8ea-4b5f-af2f-e060e48af530
1,9pHtJ58B7EZDBsAenegf,0.928916,Wildfire Ignition Density,3f0a6405-0a1a-420b-ae99-068a4aeb3b95
2,KJHtJ58B7EZDBsAebeYr,0.928603,Fire hydrant,c5dc2e13-78c5-4eff-9361-a52b003bd69e
3,DJHtJ58B7EZDBsAea-Zc,0.927367,Barracks,772cb76d-54db-4dab-b091-33e48d6173f8
4,WZHtJ58B7EZDBsAecOZA,0.927215,High tides December 2010: Wave break,39bdcc75-dbaf-424d-9dbd-265c282f14f5
5,CpHtJ58B7EZDBsAea-Y8,0.926698,Fire hydrants,f647f5ed-a8f3-4a47-8ceb-977cbf090675
6,PJHsJ58B7EZDBsAei9lN,0.926068,Canada's National Earthquake Scenario Catalogu...,53183b8c-cd09-4f3d-bcbc-b023dea3990c
7,_ZHtJ58B7EZDBsAeFuCb,0.925145,Standard fire hydrant v1,33fdc525-5092-4483-9f0b-b91482cbfce9
8,WJHsJ58B7EZDBsAeVdaB,0.924761,Fire hydrants,e7e90f77-6a1b-4b9e-bc3f-650f8fd30ab8
9,b5HtJ58B7EZDBsAeceau,0.924361,Fire stations,9efd70e6-157a-43c8-861e-b6faecf6a33f
10,GZHtJ58B7EZDBsAeSuS0,0.923845,Fire hydrants,c6085f69-652f-4f33-9b0a-89b24d90ccff
11,dpHtJ58B7EZDBsAelegV,0.923026,Historical wildfire data : 1996 to 2005,301bf91d-6db7-4004-8cc9-40ac7e7b42f7
12,CJHtJ58B7EZDBsAe2OxV,0.922490,Historical wildfire data : 2006 to 2025,a221e7a0-4f46-4be7-9c5a-e29de9a3447e
13,BZHsJ58B7EZDBsAeOtX_,0.922287,BC Wildfire Fire Perimeters - Historical,22c7cb44-1463-48f7-8e47-88857f207702
14,E5HsJ58B7EZDBsAedthJ,0.921929,Fire hydrant,a315e8f8-2e8e-47d3-990d-49f09ecb32d0
15,ZJHtJ58B7EZDBsAegef7,0.921611,Canada Forest Wildfires (2023),104934e9-9102-480f-b355-6d50403bc4e1
16,x5HrJ58B7EZDBsAe1MjI,0.921567,Heat Wave,3e9cc0c9-7e59-478b-befb-a584674baa75
17,i5HtJ58B7EZDBsAepumV,0.921188,Historical wildfire data : 1983 to 1995,5278c6d3-f024-4e6b-87d9-60e4f1848a0b
18,UZHrJ58B7EZDBsAex8I9,0.921030,Earthquakes in Canada,4cedd37e-0023-41fe-8eff-bea45385e469
19,NpHsJ58B7EZDBsAeZtc7,0.920589,Fire Control Zone,73d49815-8e7b-4c48-9294-c267b0d72cfb

In [76]:
mapping = aos_client.indices.get_mapping(index="gte-multi-ft")

fields = mapping["gte-multi-ft"]["mappings"]["properties"]

for field, definition in fields.items():
    print(field, definition.get("type"))

2026-07-13 15:54:11,360 - INFO - GET https://search-semantic-search-arieibeskhrn6vn2qd7gf5br7q.ca-central-1.es.amazonaws.com:443/gte-multi-ft/_mapping [status:200 request:0.009s]
contact None
coordinates geo_shape
created date
description text
eoCollection text
eoFilters None
graphicOverview None
id text
keywords text
language text
options None
organisation text
popularity long
published date
spatialRepresentation text
systemName text
temporalExtent None
title text
topicCategory text
type text
vector knn_vector

In [58]:
payload = {"inputs": "wildfires Canada"}
endpoint_name ='semantic-search-pretrain-all-MiniLM-L6-v2-1781031216'
vector = invoke_sagemaker_endpoint_ft(endpoint_name, payload)
print(vector)

Error invoking SageMaker endpoint semantic-search-pretrain-all-MiniLM-L6-v2-1781031216: An error occurred (ModelError) when calling the InvokeEndpoint operation: Received server error (500) from primary and could not load the entire response body. See https://ca-central-1.console.aws.amazon.com/cloudwatch/home?region=ca-central-1#logEventViewer:group=/aws/sagemaker/Endpoints/semantic-search-pretrain-all-MiniLM-L6-v2-1781031216 in account 759472643633 for more information.
None

In [ ]:
query={
    "size": 20,
    "query": {
        "knn": {
            "vector":{
                "vector":vector,
                "k":20
            }
        }
    }
}

res = aos_client.search(index='minilm-pretrain-knn', size=20, body=query, request_timeout=55)
query_result=[]
for hit in res['hits']['hits']:
    row=[hit['_id'],hit['_score'],hit['_source']['title'],hit['_source']['id']]
    query_result.append(row)
query_result_df = pd.DataFrame(data=query_result,columns=["_id","relevancy_score","title",'uuid'])
display(query_result_df)